### ISSUE TITLE
"string" must be a string, Buffer, or ArrayBuffer when webpack is called

### ISSUE THREAD

**Issue by jamil-alisgandarov** [webpack/webpack#10113]
# Bug report

**What is the current behavior?**
Webpack returns error provided below when webpack is called both with `cli` and `webpack` function. Strange thing is that it started returning this error after reinstalling node modules.

**If the current behavior is a bug, please provide the steps to reproduce.**
`webpack --config=./configs/webpack.config.lib.js`

````

throw new TypeError('"string" must be a string, Buffer, or ArrayBuffer');
    ^

TypeError: "string" must be a string, Buffer, or ArrayBuffer
    at Function.byteLength (buffer.js:481:11)
    at RawSource.size (Documents/GitHub/projectName/node_modules/webpack-sources/lib/Source.js:18:17)
    at obj.assets.compilationAssets.map (Documents/GitHub/projectName/node_modules/webpack/lib/Stats.js:415:20)
    at Array.map (<anonymous>)
    at Stats.toJson (Documents/GitHub/projectName/node_modules/webpack/lib/Stats.js:412:6)
    at Stats.toString (Documents/GitHub/projectName/node_modules/webpack/lib/Stats.js:857:20)
    at compilerCallback (Documents/GitHub/projectName/node_modules/webpack-cli/bin/cli.js:333:32)
    at compiler.run (Documents/GitHub/projectName/node_modules/webpack-cli/bin/cli.js:359:7)
    at finalCallback (Documents/GitHub/projectName/node_modules/webpack/lib/Compiler.js:257:39)
    at hooks.done.callAsync.err (Documents/GitHub/projectName/node_modules/webpack/lib/Compiler.js:306:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (Documents/GitHub/projectName/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (Documents/GitHub/projectName/node_modules/tapable/lib/Hook.js:154:20)
    at emitRecords.err (Documents/GitHub/projectName/node_modules/webpack/lib/Compiler.js:304:22)
    at Compiler.emitRecords (Documents/GitHub/projectName/node_modules/webpack/lib/Compiler.js:499:39)
    at emitAssets.err (Documents/GitHub/projectName/node_modules/webpack/lib/Compiler.js:298:10)
    at hooks.afterEmit.callAsync.err (Documents/GitHub/projectName/node_modules/webpack/lib/Compiler.js:485:14)
    at _err0 (eval at create (Documents/GitHub/projectName/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
    at callback (Documents/GitHub/projectName/node_modules/copy-webpack-plugin/dist/index.js:126:17)
    at afterEmit (Documents/GitHub/projectName/node_modules/copy-webpack-plugin/dist/index.js:220:13)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (Documents/GitHub/projectName/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:7:1)
    at AsyncSeriesHook.lazyCompileHook (Documents/GitHub/projectName/node_modules/tapable/lib/Hook.js:154:20)
    at asyncLib.forEachLimit.err (Documents/GitHub/projectName/node_modules/webpack/lib/Compiler.js:482:27)
    at Documents/GitHub/projectName/node_modules/neo-async/async.js:2818:7
    at done (Documents/GitHub/projectName/node_modules/neo-async/async.js:3522:9)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (Documents/GitHub/projectName/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at outputFileSystem.writeFile.err (Documents/GitHub/projectName/node_modules/webpack/lib/Compiler.js:464:33)
    at Documents/GitHub/projectName/node_modules/graceful-fs/graceful-fs.js:57:14
    at FSReqWrap.oncomplete (fs.js:135:15)
````
**What is the expected behavior?**

**Other relevant information:**
webpack version:  `4.41.0` occurs for `3.12.0` too, works fine on `3.11.0`
Node.js version: `dubnium -> v10.17.0`
Operating System: `MACOS 10.14.2 (18C54)`
Additional tools:

**Comment by evilebottnawi** [comment]
Please create reproducible test repo

**Comment by evilebottnawi** [comment]
Closing due to inactivity. Please test with latest version and feel free to reopen if still regressions. Thanks!
