### ISSUE TITLE
split-chunks-plugin: maxAsyncSize param considered invalid during schema validation

### ISSUE THREAD

**Issue by Alendorff** [webpack/webpack#10156]
# Bug report

**What is the current behavior?**

[Docs](https://webpack.js.org/plugins/split-chunks-plugin/#splitchunksmaxasyncsize) mention `maxAsyncSize` param, but I get schema validation error like this:

```
(node:13484) UnhandledPromiseRejectionWarning: WebpackOptionsValidationError: Invalid configuration object. Webpack has been initiali
sed using a configuration object that does not match the API schema.
 - configuration[0].optimization.splitChunks has an unknown property 'maxAsyncSize'. These properties are valid:
   object { automaticNameDelimiter?, automaticNameMaxLength?, cacheGroups?, chunks?, fallbackCacheGroup?, filename?, hidePathInfo?, m
axAsyncRequests?, maxInitialRequests?, maxSize?, minChunks?, minSize?, name? }
 - configuration[1].optimization.splitChunks has an unknown property 'maxAsyncSize'. These properties are valid:
   object { automaticNameDelimiter?, automaticNameMaxLength?, cacheGroups?, chunks?, fallbackCacheGroup?, filename?, hidePathInfo?, m
axAsyncRequests?, maxInitialRequests?, maxSize?, minChunks?, minSize?, name? }
    at webpack (C:\Users\Alend\WebstormProjects\vue-riskmarket\node_modules\webpack\lib\webpack.js:31:9)
    at rimraf (C:\Users\Alend\WebstormProjects\vue-riskmarket\build\build.js:21:3)
```

Related config part looks like this:

```js
  optimization: {
    splitChunks: {
      minSize: 10000,
      chunks: 'all',
      maxAsyncSize: 100000
    },
   // ...
```

**What is the expected behavior?**

Either no param in docs or there shouldn't be schema validation errors.

**Other relevant information:**
webpack version:  4.41.4
Node.js version: 10.16.0
Operating System: Windows 10

**Comment by sokra** [comment]
`maxAsyncSize` requires at least webpack 5.

**Comment by Alendorff** [comment]
@sokra ok, thanks, haven't noticed it anywhere in docs.

**Comment by evilebottnawi** [comment]
Feel free to update docs/open an issue
