### ISSUE TITLE
[5.0-beta.13] TypeError: this.cache.get is not a function 

### ISSUE THREAD

**Issue by trusktr** [webpack/webpack#10341]
# Bug report

**What is the current behavior?**

```
> NODE_ENV=production webpack --max_old_space_size=8196 --config etc/webpack/webpack.config.js

(node:8203) [DEP_WEBPACK_MODULE_ERRORS] DeprecationWarning: Module.errors was removed (use getErrors instead)
/home/trusktr/src/extensive_sw+arbeit-frontend-projects/common/temp/node_modules/webpack/lib/Compilation.js:2406
                                                this.cache.get(cacheName, usedHash, (err, sourceFromCache) => {
                                                           ^

TypeError: this.cache.get is not a function
    at /home/trusktr/src/extensive_sw+arbeit-frontend-projects/common/temp/node_modules/webpack/lib/Compilation.js:2406:18
    at arrayEach (/home/trusktr/src/extensive_sw+arbeit-frontend-projects/common/temp/node_modules/neo-async/async.js:2405:9)
    at Object.each (/home/trusktr/src/extensive_sw+arbeit-frontend-projects/common/temp/node_modules/neo-async/async.js:2846:9)
    at /home/trusktr/src/extensive_sw+arbeit-frontend-projects/common/temp/node_modules/webpack/lib/Compilation.js:2399:14
    at symbolEach (/home/trusktr/src/extensive_sw+arbeit-frontend-projects/common/temp/node_modules/neo-async/async.js:2444:9)
    at Object.each (/home/trusktr/src/extensive_sw+arbeit-frontend-projects/common/temp/node_modules/neo-async/async.js:2849:16)
    at Compilation.createChunkAssets (/home/trusktr/src/extensive_sw+arbeit-frontend-projects/common/temp/node_modules/webpack/lib/Compilation.js:2377:12)
    at /home/trusktr/src/extensive_sw+arbeit-frontend-projects/common/temp/node_modules/webpack/lib/Compilation.js:1700:12
    at Hook.eval [as callAsync] (eval at create (/home/trusktr/src/extensive_sw+arbeit-frontend-projects/common/temp/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/trusktr/src/extensive_sw+arbeit-frontend-projects/common/temp/node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
    at /home/trusktr/src/extensive_sw+arbeit-frontend-projects/common/temp/node_modules/webpack/lib/Compilation.js:1582:36
    at Hook.eval [as callAsync] (eval at create (/home/trusktr/src/extensive_sw+arbeit-frontend-projects/common/temp/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/trusktr/src/extensive_sw+arbeit-frontend-projects/common/temp/node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
    at Compilation.seal (/home/trusktr/src/extensive_sw+arbeit-frontend-projects/common/temp/node_modules/webpack/lib/Compilation.js:1573:27)
    at /home/trusktr/src/extensive_sw+arbeit-frontend-projects/common/temp/node_modules/webpack/lib/Compiler.js:913:19
    at /home/trusktr/src/extensive_sw+arbeit-frontend-projects/common/temp/node_modules/webpack/lib/Compilation.js:1497:4
    at eval (eval at create (/home/trusktr/src/extensive_sw+arbeit-frontend-projects/common/temp/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /home/trusktr/src/extensive_sw+arbeit-frontend-projects/common/temp/node_modules/neo-async/async.js:2830:7
    at Object.each (/home/trusktr/src/extensive_sw+arbeit-frontend-projects/common/temp/node_modules/neo-async/async.js:2857:9)
    at /home/trusktr/src/extensive_sw+arbeit-frontend-projects/common/temp/node_modules/webpack/lib/FlagDependencyExportsPlugin.js:219:18
    at /home/trusktr/src/extensive_sw+arbeit-frontend-projects/common/temp/node_modules/neo-async/async.js:2830:7
    at Object.each (/home/trusktr/src/extensive_sw+arbeit-frontend-projects/common/temp/node_modules/neo-async/async.js:2857:9)
    at /home/trusktr/src/extensive_sw+arbeit-frontend-projects/common/temp/node_modules/webpack/lib/FlagDependencyExportsPlugin.js:40:16
    at Hook.eval [as callAsync] (eval at create (/home/trusktr/src/extensive_sw+arbeit-frontend-projects/common/temp/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:5:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/trusktr/src/extensive_sw+arbeit-frontend-projects/common/temp/node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
    at Compilation.finish (/home/trusktr/src/extensive_sw+arbeit-frontend-projects/common/temp/node_modules/webpack/lib/Compilation.js:1462:28)
    at /home/trusktr/src/extensive_sw+arbeit-frontend-projects/common/temp/node_modules/webpack/lib/Compiler.js:908:18
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
```

**If the current behavior is a bug, please provide the steps to reproduce.**

I am working in a proprietary repo unfortunately. I wanted to try the Persistent Cache feature.

Is there any other info I can provide?

**What is the expected behavior?**

**Other relevant information:**
webpack version:  5.0-beta.13
Node.js version: 13.7.0
Operating System: Manjaro Linux 5.4.14-2
Additional tools:

**Comment by sokra** [comment]
Check your plugins. This can happen when a incompatible plugin is writing `compiler.cache`.
I should really make this readonly...

**Comment by sokra** [comment]
Try the change above. I think it should point you to the correct plugin.

Hint: You can use a github npm dependencies in your package.json: `"webpack": "webpack/webpack"`. This gives you the latest unpublished version on the master branch.

**Comment by trusktr** [comment]
@sokra Ah, thanks! :pray: That helps exactly point out the issue with specific plugins.
