### ISSUE TITLE
The developer tests fail for the webpack v5

### ISSUE THREAD

**Issue by nairsajjal** [webpack/webpack#10483]
# Bug report
After Installing the Webpack on the local machine, I ran tests on the project, one of the test scripts has issues as to the following

**What is the current behaviour?**
```
Summary of all failing tests
 FAIL  test/StatsTestCases.test.js (21.825s)
  ● StatsTestCases › should print correct stats for module-not-found-error

    expect(received).toMatchSnapshot()

    Snapshot name: `StatsTestCases should print correct stats for module-not-found-error 1`

    - Snapshot  - 10
    + Received  +  0

    @@ -1,15 +1,5 @@
    - ERROR in ./index.js 1:0-17
    - Module not found: Error: Can't resolve 'buffer' in 'Xdir/module-not-found-error'
    -
    - BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
    - This is no longer the case. Verify if you need these module and configure a polyfill for it.
    -
    - If you want to include a polyfill, you need to install 'buffer'.
    - If you don't want to include a polyfill, you can use an empty module like this:
    -   resolve.alias: { "buffer": false }
    -
      ERROR in ./index.js 2:0-13
      Module not found: Error: Can't resolve 'os' in 'Xdir/module-not-found-error'

      BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
      This is no longer the case. Verify if you need these modules and configure a polyfill for it.

      192 |                                     .replace(/(\w)\\(\w)/g, "$1/$2")
      193 |                                     .replace(/, additional resolving: Xms/g, "");
    > 194 |                             expect(actual).toMatchSnapshot();
          |                                            ^
      195 |                             if (testConfig.validate) testConfig.validate(stats, stderr.toString());
      196 |                             done();
      197 |                     });

      at test/StatsTestCases.test.js:194:20
      at finalCallback (lib/Compiler.js:354:32)
      at lib/Compiler.js:371:13
      at Hook.eval [as callAsync] (eval at create (node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
      at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (node_modules/tapable/lib/Hook.js:18:14)
      at onCompiled (lib/Compiler.js:369:21)
      at lib/Compiler.js:930:16
      at Hook.eval [as callAsync] (eval at create (node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
      at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (node_modules/tapable/lib/Hook.js:18:14)
      at lib/Compiler.js:926:32


Snapshot Summary
 › 1 snapshot failed from 1 test suite.
```
This is the snapshot of command line which occurs while running the tests.

**If the current behaviour is a bug, please provide the steps to reproduce.**

**What is the expected behaviour?**
The test cases must pass in all conditions and the snapshot: "StatsTestCases should print correct stats for module-not-found-error 1" must match its snapshot. Should print correct stats instead of "module-not-found-error"

**Other relevant information:**
webpack version: 5.0.0-beta.13 
Node.js version: v12.16.1
Operating System: Ubuntu 18.04 Xenial
Additional tools: Yarn

**Comment by sokra** [comment]
Hmm weird. Seems like you have the `buffer` package in your nide_modules which should not be there.

Try:
* Deleting node_modules and reinstall
* Upgrade yarn
* Check if there is no node_modules in any parent path of the clones repo

**Comment by evilebottnawi** [comment]
Answer above
