### ISSUE TITLE
Please provide more information with `No loader specified` error from RuleSet.js:389 on v4 branch

### ISSUE THREAD

**Issue by OiYouYeahYou** [webpack/webpack#10649]
**What is the expected behavior?**

That when an error is thrown, context is given with it to indicate what needs to be implemented

**What is motivation or use case for adding/changing the behavior?**

To help users of webpack understand why the error is being thrown, and how to fix it

**How should this be implemented in your opinion?**

Perhaps include a JSON string of the item without the loader

**Context**

I've been upgrading an old application and I've hit this error (formatted for readability). And without any context from the error, I'm forced to trial-and-error or to inspect a webpack to trace what is going on

    $ webpack-cli --progress --profile --colors --config webpack.config.production.js

    ./node_modules/webpack/lib/RuleSet.js:389
                throw new Error("No loader specified");
                ^

    Error: No loader specified
        at Function.normalizeUseItem                           (./node_modules/webpack/lib/RuleSet.js:389:10)
        at Function.normalizeUse                               (./node_modules/webpack/lib/RuleSet.js:360:19)
        at Function.normalizeRule                              (./node_modules/webpack/lib/RuleSet.js:288:26)
        at ./node_modules/webpack/lib/RuleSet.js:110:20
        at Array.map                                           (<anonymous>)
        at Function.normalizeRules                             (./node_modules/webpack/lib/RuleSet.js:109:17)
        at new RuleSet                                         (./node_modules/webpack/lib/RuleSet.js:104:24)
        at new NormalModuleFactory                             (./node_modules/webpack/lib/NormalModuleFactory.js:115:18)
        at Compiler.createNormalModuleFactory                  (./node_modules/webpack/lib/Compiler.js:636:31)
        at Compiler.newCompilationParams                       (./node_modules/webpack/lib/Compiler.js:653:30)
        at Compiler.compile                                    (./node_modules/webpack/lib/Compiler.js:661:23)
        at ./node_modules/webpack/lib/Compiler.js:321:11
        at Compiler.readRecords                                (./node_modules/webpack/lib/Compiler.js:529:11)
        at ./node_modules/webpack/lib/Compiler.js:318:10
        at AsyncSeriesHook.eval [as callAsync] (eval at create (./node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
        at AsyncSeriesHook.lazyCompileHook                     (./node_modules/webpack/node_modules/tapable/lib/Hook.js:154:20)
        at ./node_modules/webpack/lib/Compiler.js:315:19
        at AsyncSeriesHook.eval [as callAsync] (eval at create (./node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
        at AsyncSeriesHook.lazyCompileHook                     (./node_modules/webpack/node_modules/tapable/lib/Hook.js:154:20)
        at Compiler.run                                        (./node_modules/webpack/lib/Compiler.js:312:24)
        at processOptions                                      (./node_modules/webpack-cli/bin/cli.js:353:14)
        at ./node_modules/webpack-cli/bin/cli.js:364:3
        at Object.parse                                        (./node_modules/webpack-cli/node_modules/yargs/yargs.js:567:18)
        at ./node_modules/webpack-cli/bin/cli.js:49:8
        at Object.<anonymous>                                  (./node_modules/webpack-cli/bin/cli.js:366:3)
        at Module._compile                                     internal/modules/cjs/loader.js:1139:30)
        at Object.Module._extensions..js                       internal/modules/cjs/loader.js:1159:10)
        at Module.load                                         internal/modules/cjs/loader.js:988:32)
        at Function.Module._load                               internal/modules/cjs/loader.js:896:14)
        at Function.executeUserEntryPoint [as runMain]         internal/modules/run_main.js:71:12)
        at internal/main/run_main_module.js:17:47

--------

Additionally, it would be nice if there was some documentation to help debug the error

**Comment by evilebottnawi** [comment]
Maybe `No loader specified for "name.extension" file.`?

**Comment by evilebottnawi** [comment]
bump

**Comment by sokra** [comment]
I think this is fixed
