### ISSUE TITLE
Module parse failed: Unexpected character '#' (1:13)

### ISSUE THREAD

**Issue by wiktort** [webpack/webpack#10641]
# Bug report

**What is the current behavior?**

When I run: 'npm run build' I get following status: 

```
Webpack
Compiled with some errors in 14.32s
Error: ./.cache/plugins/strapi-plugin-settings-manager/admin/src/components/HeaderNav/styles.scss 1:13
Module parse failed: Unexpected character '#' (1:13)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders'
> $linkcolour: #f5f5f5;
| 
| .stmheaderNav {
    at /usr/local/var/www/trip4share-cms/node_modules/strapi-admin/index.js:191:23
    at finalCallback (/usr/local/var/www/trip4share-cms/node_modules/webpack/lib/Compiler.js:257:39)
    at /usr/local/var/www/trip4share-cms/node_modules/webpack/lib/Compiler.js:273:13
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/usr/local/var/www/trip4share-cms/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:22:1)
    at AsyncSeriesHook.lazyCompileHook (/usr/local/var/www/trip4share-cms/node_modules/tapable/lib/Hook.js:154:20)
    at onCompiled (/usr/local/var/www/trip4share-cms/node_modules/webpack/lib/Compiler.js:271:21)
    at /usr/local/var/www/trip4share-cms/node_modules/webpack/lib/Compiler.js:681:15
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/usr/local/var/www/trip4share-cms/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
    at AsyncSeriesHook.lazyCompileHook (/usr/local/var/www/trip4share-cms/node_modules/tapable/lib/Hook.js:154:20)
    at /usr/local/var/www/trip4share-cms/node_modules/webpack/lib/Compiler.js:678:31
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/usr/local/var/www/trip4share-cms/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:7:1)
    at AsyncSeriesHook.lazyCompileHook (/usr/local/var/www/trip4share-cms/node_modules/tapable/lib/Hook.js:154:20)
    at /usr/local/var/www/trip4share-cms/node_modules/webpack/lib/Compilation.js:1423:35
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/usr/local/var/www/trip4share-cms/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:7:1)
    at AsyncSeriesHook.lazyCompileHook (/usr/local/var/www/trip4share-cms/node_modules/tapable/lib/Hook.js:154:20)
    at /usr/local/var/www/trip4share-cms/node_modules/webpack/lib/Compilation.js:1414:32
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! trip4share-cms@1.0.0 build: `strapi build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the trip4share-cms@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Lord-of-the-Mac/.npm/_logs/2020-03-30T21_29_45_998Z-debug.log`

```

I have cleaned the cache, deleted node_modules however it did not help. 

Do you have any idea how to solve it? 

Thank you in advance!
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

No parsing error. 

**Other relevant information:**
webpack version:  4.42.1
Node.js version: 12.16.1
Operating System: MacOS Catalina
Additional tools: Strapi.io

**Comment by chenxsan** [comment]
> Error: ./.cache/plugins/strapi-plugin-settings-manager/admin/src/components/HeaderNav/styles.scss 1:13
Module parse failed: Unexpected character '#' (1:13)
> You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file

Since you're importing `scss` file, please refer to https://github.com/webpack-contrib/sass-loader document for how to configure it.

**Comment by wiktort** [comment]
Thank you! I had added it in Strapi-Admin folder and it has resolved the problem!
