### ISSUE TITLE
Error: No element indexed by 1

### ISSUE THREAD

**Issue by volkanunsal** [webpack/webpack#1071]
I get this error when I'm packaging the bundle for production.

```
~/node_modules/webpack/node_modules/webpack-core/node_modules/source-map/lib/source-map/array-set.js:84
      throw new Error('No element indexed by ' + aIdx);
      ^
  Error: No element indexed by 1
    at ArraySet_at [as at] (~/node_modules/webpack/node_modules/webpack-core/node_modules/source-map/lib/source-map/array-set.js:84:11)
    at SourceMapConsumer_parseMappings [as _parseMappings] (~/node_modules/webpack/node_modules/webpack-core/node_modules/source-map/lib/source-map/source-map-consumer.js:410:44)
    at SourceMapConsumer.Object.defineProperty.get (~/node_modules/webpack/node_modules/webpack-core/node_modules/source-map/lib/source-map/source-map-consumer.js:73:14)
    at SourceMapConsumer_eachMapping [as eachMapping] (~/node_modules/webpack/node_modules/webpack-core/node_modules/source-map/lib/source-map/source-map-consumer.js:139:24)
    at Function.SourceNode_fromStringWithSourceMap [as fromStringWithSourceMap] (~/node_modules/webpack/node_modules/webpack-core/node_modules/source-map/lib/source-map/source-node.js:84:26)
```

My config file:

```javascript
var webpack = require('webpack');
var commonsPlugin = webpack.optimize.CommonsChunkPlugin;
var dirDescription = webpack.ResolverPlugin.DirectoryDescriptionFilePlugin;
var path = require('path');
var fs = require('fs');
var autoprefixer = require('autoprefixer');

  
// The build is DEV by default
var isDev = JSON.stringify(JSON.parse(process.env.BUILD_DEV || 'true'));
// Pass the BUILD_RELEASE flag to pack it for production
var isPrerelease = JSON.stringify(JSON.parse(process.env.BUILD_PRERELEASE || 'false'));

var definePlugin = new webpack.DefinePlugin({
  __PRERELEASE__: ('true' === isPrerelease),
  __DEV__: ('false' === isPrerelease)
});

var entryFileNameTemplate = isPrerelease === 'true' ? '[name]-[hash].js' : '[name].js';
var commonFileNameTemplate = isPrerelease === 'true' ? 'common-[hash].js' : 'common.js';

var plugins = [
    definePlugin,
    // Generates an extra chunk, which contains common modules shared between at least minChunks entry points. You must load the generated chunk before the entry point:
    // The second argument is the name of the chunk, as gleaned from the entrypoint hash above. Update it new entrypoints are added
    new commonsPlugin('common.js',commonFileNameTemplate,2),
    new webpack.ResolverPlugin(new dirDescription('bower.json', ['main']))
  ];


var outputLocation = __dirname + '/assets/bundles';

var entries = {
  bootstrap: 'bootstrap-sass!./entry/bootstrap.config.js',
  App: './entry/AppEntry'
};

// Output the assets to a separate folder for prerelease build.
var outputLocation = __dirname + '/public/assets';

// Minimize all javascript output of chunks. Loaders are switched into minimizing mode. You can pass an object containing UglifyJs options.
var uglifyPlugin = webpack.optimize.UglifyJsPlugin;
plugins.push(
  new uglifyPlugin({
    comments: false,
    compress: {
      warnings: false,
      drop_console: true,
      dead_code: true
    },
    mangle: {
      reserved: '$,require,exports,L,d3,webpackJsonp'
    }
  })
);

var CompressionPlugin = require("compression-webpack-plugin");
plugins.push(
  new CompressionPlugin({
      asset: "{file}.gz",
      algorithm: "gzip",
      regExp: /\.js$|\.html$/,
      threshold: 10240,
      minRatio: 0.8
  })
);

// The stats json contains a useful property assetsByChunkName which is a object containing chunk name as key and filename(s) as value.
plugins.push(
  function() {
    this.plugin("done", function(stats) {

      var assets = {};
      stats.toJson()['assets'].forEach(function(item){
        if(/(jpg|gif|png|js)$/.test(item.name)){
          // assets.push(item.name);
          var np = item.name.match(/^(.*)-\w+(\..+)$/);
          if(np){
            assets[np[1]+np[2]] = np[0];
          }
        }
      });
      var manifest = {assets: assets}
      require("fs").writeFileSync(
        path.join(__dirname, 'assets', "manifest.json"), JSON.stringify(manifest));
    });
  }
)

// Search for equal or similar files and deduplicate them in the output. This comes with some overhead for the entry chunk, but can reduce file size effectively.
plugins.push(new webpack.optimize.DedupePlugin());

// Assign the module and chunk ids by occurrence count. Ids that are used often get lower (shorter) ids. This make ids predictable, reduces to total file size and is recommended.
// plugins.push(new webpack.optimize.OccurenceOrderPlugin());




// Generate source maps
devtool = isPrerelease === 'true' ? '@source-map' : null;


module.exports = {

  // 'context' sets the directory where webpack looks for module files you list in
  // your 'require' statements
  context: __dirname + '/assets',

  // 'entry' specifies the entry point, where webpack starts reading all
  // dependencies listed and bundling them into the output file.
  // The entrypoint can be anywhere and named anything - here we are calling it
  // '_application' and storing it in the 'assets/javascripts' directory
  entry: entries,

  // 'output' specifies the filepath for saving the bundled output generated by
  // wepback.
  // It is an object with options, and you can interpolate the name of the entry
  // file using '[name]' in the filename.
  // You will want to add the bundled filename to your '.gitignore'.
  output: {
    filename: entryFileNameTemplate,
    // We want to save the bundle in a bundles director
    path: outputLocation,
    // But we will expose it from the assets endpoint
    publicPath: '/assets/'
    , sourceMapFilename: '[file].map'
  },

  devtool: devtool,

  resolve: {
    // you can now require('file') instead of require('file.coffee')
    extensions: ['', '.js', '.json', '.coffee'],
    // Now you can require('file') instead of require('../../file')
    root: [__dirname + '/assets', path.join(__dirname, 'vendor/assets/components'), path.join(__dirname,'vendor/assets/javascripts')]
  },

  postcss: [ autoprefixer({ browsers: ['last 2 version'] }) ],

  // The 'module' and 'loaders' options tell webpack to use loaders.
  // @see http://webpack.github.io/docs/using-loaders.html
  module: {
    loaders: [
      // Pattern matches the coffeescript files with JSX markup
      // Pattern matches the coffeescript files
      {
        test: /\.js$/,
        loaders: ['babel?stage=1','jsx?harmony&stripTypes&target=es6&nonStrictEs6module'],
        exclude: /node_modules\/(?!react-bootstrap)|(bootstrap(-sass)?\.config.*)/
      },
      // Pattern matches the coffeescript files
      {
        test: /\.coffee$/,
        loaders: ['babel?stage=1','jsx?harmony', 'coffee']
      },
      // the url-loader uses DataUrls.
      {
        test: /\.woff(2)?(\?v=[0-9]\.[0-9]\.[0-9])?$/,
        loader: 'url?limit=10000&minetype=application/font-woff'
      },
      {
        test: /\.ttf(\?v=\d+\.\d+\.\d+)?$/,
        loader: "url?limit=10000&minetype=application/octet-stream"
      },
      // the file emits files.
      {
        test: /\.eot(\?v=\d+\.\d+\.\d+)?$/,
        loader: "file"
      },
      {
        test: /\.svg(\?v=\d+\.\d+\.\d+)?$/,
        loader: "url?limit=10000&minetype=image/svg+xml"
      },
      {
        test: /\.scss$/,
        // Query parameters are passed to node-sass
        loader: 'style!css!postcss-loader!sass?outputStyle=expanded&includePaths[]=' + (path.resolve(__dirname, './node_modules'))
      },
      {
        test: /bootstrap-sass\/assets\/javascripts\//,
        // This is needed so that each bootstrap js file required by bootstrap-webpack has access to the jQuery object
        loader: 'imports?jQuery=jquery'
      },
      {
        test: /\.css$/,
        loader: 'style!css!postcss-loader'
      },
      // the url is like the file, but it inlines the image if it's below a certain file size.
      {
        test: /\.(png|jpg)$/,
        loader: 'url?limit=8192&name=[name]-[hash].[ext]'
      }
    ]
  },


  plugins: plugins
};
```

**Comment by volkanunsal** [comment]
I think the error is coming from UglifyJS. But I can't figure out what to do about it...

**Comment by volkanunsal** [comment]
Somebody please help... this is happening with every single version I've tried.

**Comment by volkanunsal** [comment]
When I disable sourcemaps from the devtools option, this error goes away.


This is the only configuration that works.

```
devtool = 'eval'
```

**Comment by pk-nb** [comment]
Having the same issue with `webpack -p`. Disabling source maps with `devtool: 'eval'`also fixes the issue. (thanks @volkanunsal)

**Comment by cadebward** [comment]
Also getting this error. From my research, it appears that `devtool: 'eval'` removes some of the production optimizations, so I don't want to settle for that solution. Anyone had any more breakthroughs on this?

**Comment by aikoven** [comment]
I've had this issue for a long time without solution, but somehow it's fixed by deleting `node_modules` and then `npm i` again.

**Comment by cadebward** [comment]
We fixed it by removing `-p` from our build command. Then we manually added in the uglify plugin in the webpack config with the option `sourceMap: false`. It appears that if you add in that option, and then pass the `-p` flag, the flag overrides the plugin options.

**Comment by volkanunsal** [comment]
@cadebward What did you end up using for `devtool`?

**Comment by volkanunsal** [comment]
When I try adding `sourceMap: false`, I get this error:

```
/webpack/lib/Compiler.js:255
				var content = source.source();
TypeError: Property 'source' of object #<Source> is not a function
```

**Comment by cadebward** [comment]
@volkanunsal We used nothing for `devtool`. Inside of plugins: `new webpack.optimize.UglifyJsPlugin({sourceMap: false})`

**Comment by halt-hammerzeit** [comment]
I have the same issue: my library uses inline maps, and when included into another project produces this error.
More info on the same issue: http://stackoverflow.com/questions/30893458/using-inline-source-maps-breaks-webpack-build

**Comment by halt-hammerzeit** [comment]
So, I found the issue in my case:

If you do some Googling
https://www.google.ru/search?newwindow=1&safe=off&es_sm=93&q=%22No+element+indexed+by+1%22&oq=%22No+element+indexed+by+1%22&gs_l=serp.3...25063.25245.0.25668.2.2.0.0.0.0.62.119.2.2.0....0...1c.1.64.serp..2.0.0.-ZDOlWEKDQU

You'll get the idea that its because of somehow malformed source maps of the corresponding npm module being imported in the project
https://github.com/mozilla/source-map/issues/76

My module was built with babel like this:
```sh
"babel-transpiled-modules": "babel ./source --optional runtime --out-dir ./babel-transpiled-modules --source-maps inline"
```

I switched it from inline source maps to external source maps:
```sh
"babel-transpiled-modules": "babel ./source --optional runtime --out-dir ./babel-transpiled-modules --source-maps"
```

And now it works

**Comment by DLMR** [comment]
So I'm having the same problem when building with Webpack. I have created a minimal example that shows this error consistently and I will outline what I'm trying to do below. 

I have a module that I build using  [__Babel__](https://github.com/babel/babel) with source maps that I would like to include into my Webpack build. To do this I have installed the [__Source Map Loader__](https://github.com/webpack/source-map-loader) and when I have `devtool` set to `source-map` I get the following error.
````
node_modules/webpack-core/lib/NormalModuleMixin.js:151
				throw e;
				^
Error: No element indexed by 1
````

Just to test I also tried to set `devtool` to `cheap-module-source-map`. I then get the following error, the same as in #954.
````
node_modules/webpack-core/lib/NormalModuleMixin.js:151
				throw e;
				^

TypeError: Cannot read property 'readableIdentifier' of undefined
````

I have inspected the source map that __Babel__ generates and what __Source Map Loader__ reads and both seems to look fine. I'm unsure why this happens but from what I have been able to understand something, when using the `source-map` option, is merged in a incorrect way because the source maps that are processed by [__Source Map__](https://github.com/mozilla/source-map) is not the same as the one that was generated and read by __Babel__ and __Source Map Loader__.

[Here is a simple example project that shows this behaviour.](https://github.com/DLMR/webpack-source-maps)

Help on this matter is greatly appreciated!

**Comment by ccorcos** [comment]
So this is 100% a sourcemap issue. I got webpack running, but without sourcemaps :-1:

**Comment by bebraw** [comment]
Can you still see this issue?

**Comment by ccorcos** [comment]
@bebraw I haven't seen it for a while now...

**Comment by bebraw** [comment]
Ok, let's close this then. Thanks. 👍
