### ISSUE TITLE
Invalid configuration object: `mangleExports` using 5.0.0-beta.14

### ISSUE THREAD

**Issue by JAicewizard** [webpack/webpack#10739]
# Bug report

**What is the current behavior?**
When I use the example configuration for mangleExports:
```
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.optimization has an unknown property 'mangleExports'. These properties are valid:
   object { checkWasmTypes?, chunkIds?, concatenateModules?, flagIncludedChunks?, hashedModuleIds?, mangleWasmImports?, mergeDuplicateChunks?, minimize?, minimizer?, moduleIds?, namedChunks?, namedModules?, noEmitOnErrors?, nodeEnv?, occurrenceOrder?, portableRecords?, providedExports?, removeAvailableModules?, removeEmptyChunks?, runtimeChunk?, sideEffects?, splitChunks?, usedExports? }
   -> Enables/Disables integrated optimizations
```

**If the current behavior is a bug, please provide the steps to reproduce.**

create webpack.config.js as example profided in documentation:
```
module.exports = {
  //...
  optimization: {
    mangleExports: false
  }
};
```

**What is the expected behavior?**
Webpack should not mangle exports like the documentation provides

**Other relevant information:**
webpack version:  5.0.0-beta-14
Node.js version: v13.12.0
Operating System: linux
Additional tools: webpack-cli@4.0.0-beta.8

**Comment by sokra** [comment]
The error message is coming from webpack 4. Check that you are really using webpack 5.

**Comment by JAicewizard** [comment]
```
$ webpack --version
5.0.0-beta.14
[webpack-cli] Promise rejection: Error: Cannot find module '../../../../package.json'
Require stack:
- /usr/lib/node_modules/webpack-cli/lib/groups/HelpGroup.js
- /usr/lib/node_modules/webpack-cli/lib/webpack-cli.js
- /usr/lib/node_modules/webpack-cli/lib/bootstrap.js
[webpack-cli] Error: Cannot find module '../../../../package.json'
Require stack:
- /usr/lib/node_modules/webpack-cli/lib/groups/HelpGroup.js
- /usr/lib/node_modules/webpack-cli/lib/webpack-cli.js
- /usr/lib/node_modules/webpack-cli/lib/bootstrap.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:976:15)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at HelpGroup.outputVersion (/usr/lib/node_modules/webpack-cli/lib/groups/HelpGroup.js:43:25)
    at WebpackCLI.runVersion (/usr/lib/node_modules/webpack-cli/lib/webpack-cli.js:303:32)
    at runCLI (/usr/lib/node_modules/webpack-cli/lib/bootstrap.js:54:13)
    at Object.<anonymous> (/usr/lib/node_modules/webpack-cli/lib/bootstrap.js:117:1)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
```

```
$ cat webpack.config.js
module.exports = {
	optimization: {
		mangleExports: true
	}
};
$ webpack js/main.js -o dist/main.js
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.optimization has an unknown property 'mangleExports'. These properties are valid:
   object { checkWasmTypes?, chunkIds?, concatenateModules?, flagIncludedChunks?, hashedModuleIds?, mangleWasmImports?, mergeDuplicateChunks?, minimize?, minimizer?, moduleIds?, namedChunks?, namedModules?, noEmitOnErrors?, nodeEnv?, occurrenceOrder?, portableRecords?, providedExports?, removeAvailableModules?, removeEmptyChunks?, runtimeChunk?, sideEffects?, splitChunks?, usedExports? }
   -> Enables/Disables integrated optimizations
```

**Comment by evilebottnawi** [comment]
@JAicewizard Can you create reproducible test repo?

**Comment by JAicewizard** [comment]
https://github.com/JAicewizard/webpack_issue

I have installed webpack and webpack cli using:
```
# npm install -g webpack@5.0.0-beta.14
# npm install -g webpack-cli@4.0.0-beta.8
```
