### ISSUE TITLE
"Module parse failed: Maximum call stack size exceeded" with too many environment variables for EnvironmentPlugin

### ISSUE THREAD

**Issue by TAGraves** [webpack/webpack#10895]
# Bug report

**What is the current behavior?**
If you have enough environment variables (I'd guess roughly as many as the node stack-size) configured for EnvironmentPlugin, Webpack will blow up with the following error when referencing `process`:
```
ERROR in ./index.js
Module parse failed: Maximum call stack size exceeded
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
RangeError: Maximum call stack size exceeded
    at new Function (<anonymous>)
    at SyncBailHookCodeFactory.create (/Users/homedir/code/envvar-error-example/node_modules/tapable/lib/HookCodeFactory.js:19:10)
    at SyncBailHook.compile (/Users/homedir/code/envvar-error-example/node_modules/tapable/lib/SyncBailHook.js:38:18)
    at SyncBailHook._createCall (/Users/homedir/code/envvar-error-example/node_modules/tapable/lib/Hook.js:24:15)
    at SyncBailHook.lazyCompileHook [as call] (/Users/homedir/code/envvar-error-example/node_modules/tapable/lib/Hook.js:153:21)
    at Parser.walkVariableDeclaration (/Users/homedir/code/envvar-error-example/node_modules/webpack/lib/Parser.js:1455:38)
    at Parser.walkStatement (/Users/homedir/code/envvar-error-example/node_modules/webpack/lib/Parser.js:997:10)
    at Parser.walkStatements (/Users/homedir/code/envvar-error-example/node_modules/webpack/lib/Parser.js:868:9)
    at Parser.parse (/Users/homedir/code/envvar-error-example/node_modules/webpack/lib/Parser.js:2297:9)
    at /Users/homedir/code/envvar-error-example/node_modules/webpack/lib/NormalModule.js:482:32
    at /Users/homedir/code/envvar-error-example/node_modules/webpack/lib/NormalModule.js:358:12
    at /Users/homedir/code/envvar-error-example/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/homedir/code/envvar-error-example/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/Users/homedir/code/envvar-error-example/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /Users/homedir/code/envvar-error-example/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at context.callback (/Users/homedir/code/envvar-error-example/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /Users/homedir/code/envvar-error-example/node_modules/babel-loader/lib/index.js:59:71
 @ multi ./index.js main[0]
```

**If the current behavior is a bug, please provide the steps to reproduce.**
Here's a repository that reproduces the issue with a very simple Webpack and Babel configuration and one line of source code. https://github.com/TAGraves/envvar-error-example

After cloning the repository and running `yarn install`, just run `./bin/make-it-blow-up`. This runs webpack with 8000 environment variables configured.

**What is the expected behavior?**
Webpack should be able to successfully compile with any number of environment variables, or it should produce an error informing the user that there is a maximum size to the environment.

**Other relevant information:**
webpack version:  4.43.0
Node.js version: v13.12.0
Operating System: Mac OS 10.15.4
Additional tools: N/A

**Comment by sokra** [comment]
The idea of the argument of the EnvironmentPlugin is that you selectively list the env variables to are using and you do not accidentally leak others into your bundle.

Anyway the problem is still worth fixing
