### ISSUE TITLE
Documentation error webpack.js.org/configuration/externals/

### ISSUE THREAD

**Issue by MaxmaxmaximusGitHub** [webpack/webpack#10951]
https://webpack.js.org/configuration/externals/

```javascript
function(context, request, callback) {
      if (/^yourregex$/.test(request)){
        return callback(null, 'commonjs ' + request);
      }
      callback();
    },
```

is error, its must be:

```javascript
function(context, request, callback) {
      if (/^yourregex$/.test(request)){
        return callback(null, 'commonjs ' + context); // instead "+ request"
      }
      callback();
    },
```

**Comment by snitin315** [comment]
Looking into it.

**Comment by sokra** [comment]
I don't think so... Why do you think it's wrong?

**Comment by MaxmaxmaximusGitHub** [comment]
@sokra 

![image](https://user-images.githubusercontent.com/60403187/82847476-efc48a80-9ef6-11ea-8a51-fd36c45339d5.png)

![image](https://user-images.githubusercontent.com/60403187/82847480-f6530200-9ef6-11ea-90ca-4f44e96daa3c.png)


i get error:
```cms
internal/modules/cjs/loader.js:960
  throw err;
  ^

Error: Cannot find module './es'
Require stack:
- C:\localhost\csgo\server\build\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:957:15)
    at Function.Module._load (internal/modules/cjs/loader.js:840:27)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object../es (C:\localhost\csgo\server\build\index.js:153:18)
    at __webpack_require__ (C:\localhost\csgo\server\build\index.js:20:30)
    at Object.../node_modules/core-js/index.js (C:\localhost\csgo\server\build\index.js:96:1)
    at __webpack_require__ (C:\localhost\csgo\server\build\index.js:20:30)
    at Module../index.js (C:\localhost\csgo\server\build\index.js:166:65)
    at __webpack_require__ (C:\localhost\csgo\server\build\index.js:20:30) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'C:\\localhost\\csgo\\server\\build\\index.js' ]
}

```

**Comment by MaxmaxmaximusGitHub** [comment]
@sokra oh, sorry, I'm completely wrong =) typo
