### ISSUE TITLE
Webpack 5, watchOptions.ignored with a RegExp object is broken

### ISSUE THREAD

**Issue by georeith** [webpack/webpack#10985]
# Bug report

**What is the current behavior?**

Passing an array including RegExp to `watchOptions.ignore` results in the following error:

```
/Users/george/Documents/marvel/mkiii/src/sites/marvel3/node_modules/glob-to-regexp/index.js:3
    throw new TypeError('Expected a string');
    ^

TypeError: Expected a string
    at module.exports (/Users/george/Documents/marvel/mkiii/src/sites/marvel3/node_modules/glob-to-regexp/index.js:3:11)
    at stringToRegexp (/Users/george/Documents/marvel/mkiii/src/sites/marvel3/node_modules/watchpack/lib/watchpack.js:26:17)
    at /Users/george/Documents/marvel/mkiii/src/sites/marvel3/node_modules/watchpack/lib/watchpack.js:34:38
    at Array.map (<anonymous>)
    at ignoredToRegexp (/Users/george/Documents/marvel/mkiii/src/sites/marvel3/node_modules/watchpack/lib/watchpack.js:34:29)
    at normalizeOptions (/Users/george/Documents/marvel/mkiii/src/sites/marvel3/node_modules/watchpack/lib/watchpack.js:49:12)
    at cachedNormalizeOptions (/Users/george/Documents/marvel/mkiii/src/sites/marvel3/node_modules/watchpack/lib/watchpack.js:58:21)
    at new Watchpack (/Users/george/Documents/marvel/mkiii/src/sites/marvel3/node_modules/watchpack/lib/watchpack.js:71:25)
    at NodeWatchFileSystem.watch (/Users/george/Documents/marvel/mkiii/src/sites/marvel3/node_modules/webpack/lib/node/NodeWatchFileSystem.js:70:18)
    at Watching.watch (/Users/george/Documents/marvel/mkiii/src/sites/marvel3/node_modules/webpack/lib/Watching.js:176:48)
    at /Users/george/Documents/marvel/mkiii/src/sites/marvel3/node_modules/webpack/lib/Watching.js:155:11
    at processTicksAndRejections (internal/process/task_queues.js:82:9)
    at runNextTicks (internal/process/task_queues.js:59:3)
    at processImmediate (internal/timers.js:412:9)
```

**If the current behavior is a bug, please provide the steps to reproduce.**

```js
watchOptions: {
  ignored: [/node_modules/],
}
```

**What is the expected behavior?**

Should be able to take an array of RegExp objects as configuration [as per the documentation](https://webpack.js.org/configuration/watch/#watchoptionsignored) or the breaking change should be noted in [the migration docs](https://webpack.js.org/migrate/5/).

This was working in 4.41.0

**Other relevant information:**
webpack version:  5.0.0-beta.16
Node.js version: 12.4.0
Operating System: macOS mojave
Additional tools:

**Comment by sokra** [comment]
While there is certainy

**Comment by georeith** [comment]
@sokra it says:

> It is also possible to have and use multiple anymatch patterns:

Which are described [here](https://github.com/micromatch/anymatch/blob/master/README.md) (where it links out to) as:
> String to be directly matched, string with glob patterns, regular expression test, function that takes the testString as an argument and returns a truthy value if it should be matched, or an array of any number and mix of these types.

**Comment by sokra** [comment]
hmm that's true, for the start we should fix the documentation. And then add support for Regexp in the array.

**Comment by ScriptedAlchemy** [comment]
i ran into a similar issue yesterday while upgrading a third party plugin, mixing an array of strings with regex did not work well

**Comment by evilebottnawi** [comment]
@ScriptedAlchemy Feel free to send a PR :star:

**Comment by ScriptedAlchemy** [comment]
it was not a blocking issue for me, but ill take a look next week :)

**Comment by evilebottnawi** [comment]
Fixed https://github.com/webpack/webpack/pull/11498
