### ISSUE TITLE
Cannot create Next production build due to issues with aliases "configuration[0].resolve.alias['extensions'] should be a string."

### ISSUE THREAD

**Issue by steffieharner** [webpack/webpack#10993]
Trying to bump next from 7.0.3 to 9.3.2 and running into some webpack issues. It definitely stems from not having a full understanding of webpack and promises. I would love any pointers in the right direction, so thank you in advance.

Here is my `next.conig.js`

```
const env = process.env.ENV || "development";
const path = require("path");
const showdown = require("showdown");

const withSass = require("@zeit/next-sass");
const withCSS = require("@zeit/next-css");
const withProgressBar = require("next-progressbar");
const withOptimizedImages = require("next-optimized-images");
const sharp = require("responsive-loader/sharp");

module.exports = withProgressBar(
  withOptimizedImages(
    withCSS(
      withSass({
        sassLoaderOptions: {
          sourceMap: env,
        },
        handleImages: ["jpeg", "png"],
        optimizeImages: false,
        optimizeImagesInDev: false,
        responsive: {
          adapter: sharp,
          sizes: [960, 1920, 2800],
          disable: false,
        },
        webpack(config) {
          config.module.rules.push({
            test: /\.(otf|eot|svg|gif|ttf|woff|woff2)(\?.+)?$/,
            loader: "url-loader",
          });

          config.module.rules.push({
            test: /\.md$/,
            include: path.join(__dirname, "static"),
            loader: "post-loader",
            options: {
              render(data) {
                const converter = new showdown.Converter();
                converter.setOption("tables", true);
                converter.setOption("tasklists", true);

                return converter.makeHtml(data);
              },
            },
          });

          // Fixes npm packages that depend on `fs` module
          config.node = {
            fs: "empty",
          };

          config.resolve.alias = {
            ...config.resolve.alias,
            extensions: [".js", ".jsx"],
            alias: {
              root: path.resolve(__dirname, ""),
              components: path.resolve(__dirname, "components"),
              common: path.resolve(__dirname, "components/common"),
              data: path.resolve(__dirname, "components/data"),
              utils: path.resolve(__dirname, "utils"),
            },
          };

          return config;
        },
      })
    )
  )
);
```

This is the errors that I get:

```
(node:39769) UnhandledPromiseRejectionWarning: WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration[0].resolve.alias['extensions'] should be a string.
   -> New request
 - configuration[1].resolve.alias['extensions'] should be a string.
   -> New request
    at webpack (/Users/steffieharner/Desktop/CC/website/node_modules/next/node_modules/webpack/lib/webpack.js:31:9)
    at Promise (/Users/steffieharner/Desktop/CC/website/node_modules/next/dist/build/compiler.js:1:529)
    at new Promise (<anonymous>)
    at runCompiler (/Users/steffieharner/Desktop/CC/website/node_modules/next/dist/build/compiler.js:1:458)
    at build (/Users/steffieharner/Desktop/CC/website/node_modules/next/dist/build/index.js:11:348)
(node:39769) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:39769) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Creating an optimized production build ...
```

Has the structure of declaring aliases changed?

🙏🏼

**Comment by chenxsan** [comment]
It might be caused by the wrong assignment in your code:

```js
config.resolve.alias = {
            ...config.resolve.alias,
            extensions: [".js", ".jsx"],
            alias: {
              root: path.resolve(__dirname, ""),
              components: path.resolve(__dirname, "components"),
              common: path.resolve(__dirname, "components/common"),
              data: path.resolve(__dirname, "components/data"),
              utils: path.resolve(__dirname, "utils"),
            },
          };
```
Should it be:

```js
config.resolve = {
            extensions: [".js", ".jsx"],
            alias: {
              ...config.resolve.alias,
              root: path.resolve(__dirname, ""),
              components: path.resolve(__dirname, "components"),
              common: path.resolve(__dirname, "components/common"),
              data: path.resolve(__dirname, "components/data"),
              utils: path.resolve(__dirname, "utils"),
            },
          };
```

**Comment by steffieharner** [comment]
even after that change, I am getting the same error. @sokra
