### ISSUE TITLE
how to resolve the issue, i have no idea.

### ISSUE THREAD

**Issue by rodchen-king** [webpack/webpack#11002]
error in ./node_modules/monaco-editor/esm/vs/editor/contrib/suggest/media/suggest.css

Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/css-loader-1/index.js):
TypeError: exports[name].indexOf is not a function
at exportScopedName (E:\workspace\antdesign-pro-amis\node_modules\css-loader-1\node_modules\postcss-modules-scope\lib\index.js:50:25)
at localizeNode (E:\workspace\antdesign-pro-amis\node_modules\css-loader-1\node_modules\postcss-modules-scope\lib\index.js:64:28)
at Array.map ()
at localizeNode (E:\workspace\antdesign-pro-amis\node_modules\css-loader-1\node_modules\postcss-modules-scope\lib\index.js:60:38)
at traverseNode (E:\workspace\antdesign-pro-amis\node_modules\css-loader-1\node_modules\postcss-modules-scope\lib\index.js:78:20)
at Array.map ()
at traverseNode (E:\workspace\antdesign-pro-amis\node_modules\css-loader-1\node_modules\postcss-modules-scope\lib\index.js:84:38)
at Array.map ()
at traverseNode (E:\workspace\antdesign-pro-amis\node_modules\css-loader-1\node_modules\postcss-modules-scope\lib\index.js:84:38)
at callback (E:\workspace\antdesign-pro-amis\node_modules\css-loader-1\node_modules\postcss-modules-scope\lib\index.js:103:25)
at callback (E:\workspace\antdesign-pro-amis\node_modules\postcss\lib\container.es6:198:28)
at callback (E:\workspace\antdesign-pro-amis\node_modules\postcss\lib\container.es6:109:26)
at Root.each (E:\workspace\antdesign-pro-amis\node_modules\postcss\lib\container.es6:77:22)
at Root.walk (E:\workspace\antdesign-pro-amis\node_modules\postcss\lib\container.es6:108:21)
at Root.walkRules (E:\workspace\antdesign-pro-amis\node_modules\postcss\lib\container.es6:196:25)
at E:\workspace\antdesign-pro-amis\node_modules\css-loader-1\node_modules\postcss-modules-scope\lib\index.js:101:9
at runLoaders (E:\workspace\antdesign-pro-amis\node_modules\webpack\lib\NormalModule.js:316:20)
at E:\workspace\antdesign-pro-amis\node_modules\loader-runner\lib\LoaderRunner.js:367:11
at E:\workspace\antdesign-pro-amis\node_modules\loader-runner\lib\LoaderRunner.js:233:18
at context.callback (E:\workspace\antdesign-pro-amis\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
at Object. (E:\workspace\antdesign-pro-amis\node_modules\css-loader-1\lib\loader.js:44:18)
at E:\workspace\antdesign-pro-amis\node_modules\css-loader-1\lib\processCss.js:216:4

@ ./node_modules/monaco-editor/esm/vs/editor/contrib/suggest/suggestWidget.js 25:0-29
@ ./node_modules/monaco-editor/esm/vs/editor/contrib/suggest/suggestController.js
@ ./node_modules/monaco-editor/esm/vs/editor/editor.all.js
@ ./node_modules/monaco-editor/esm/vs/editor/edcore.main.js
@ ./node_modules/monaco-editor/esm/vs/editor/editor.main.js
@ ./node_modules/amis/lib/components/Editor.js
@ ./node_modules/amis/lib/components/index.js
@ ./node_modules/amis/lib/index.js
@ ./src/pages/List/BasicList.js
@ ./src/pages/.umi/router.js
@ ./src/pages/.umi/umi.js
@ multi ./node_modules/af-webpack/lib/webpackHotDevClient.js ./src/pages/.umi/umi.js

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

I have no idea how I can help with the unreadable problem
