### ISSUE TITLE
dependOn in module.exports[entry] breaks webpack

### ISSUE THREAD

**Issue by AriaMoradi** [webpack/webpack#11123]
# Bug report

**What is the current behavior?**
using dependOn in module.exports[entry] breaks webpack, same as the title

**If the current behavior is a bug, please provide the steps to reproduce.**
this repository reproduces the problem: [repo](https://github.com/AriaMoradi/webpack-issue-20200705) (this is a django project that uses react and webpack to manage js assets)

try running `yarn watch`
here's the output i got: 
```bash
$ yarn watch
yarn run v1.22.4
$ webpack --watch --config webpack.config.watch.js --mode development

webpack is watching the files…

TypeError: requestWithoutMatchResource.startsWith is not a function
    at /home/armor/programming/python/dorebazar/node_modules/webpack/lib/NormalModuleFactory.js:180:57
    at /home/armor/programming/python/dorebazar/node_modules/webpack/lib/NormalModuleFactory.js:129:4
    at /home/armor/programming/python/dorebazar/node_modules/webpack/lib/NormalModuleFactory.js:400:5
    at AsyncSeriesWaterfallHook.eval [as callAsync] (eval at create (/home/armor/programming/python/dorebazar/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
    at NormalModuleFactory.create (/home/armor/programming/python/dorebazar/node_modules/webpack/lib/NormalModuleFactory.js:381:28)
    at /home/armor/programming/python/dorebazar/node_modules/webpack/lib/Compilation.js:1063:18
    at Semaphore.acquire (/home/armor/programming/python/dorebazar/node_modules/webpack/lib/util/Semaphore.js:29:4)
    at Compilation._addModuleChain (/home/armor/programming/python/dorebazar/node_modules/webpack/lib/Compilation.js:1062:18)
    at Compilation.addEntry (/home/armor/programming/python/dorebazar/node_modules/webpack/lib/Compilation.js:1164:8)
    at /home/armor/programming/python/dorebazar/node_modules/webpack/lib/DynamicEntryPlugin.js:59:19
    at new Promise (<anonymous>)
    at addEntry (/home/armor/programming/python/dorebazar/node_modules/webpack/lib/DynamicEntryPlugin.js:58:13)
    at /home/armor/programming/python/dorebazar/node_modules/webpack/lib/DynamicEntryPlugin.js:72:16
    at Array.map (<anonymous>)
    at /home/armor/programming/python/dorebazar/node_modules/webpack/lib/DynamicEntryPlugin.js:71:27
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**What is the expected behavior?**
as stated [here](https://webpack.js.org/configuration/entry-context/#dependencies) the code should work.

**Other relevant information:**
webpack version:  4.43.0
Node.js version: 12.17.0
Operating System: Arch Linux x86_64
Additional tools: bash?

**Comment by AriaMoradi** [comment]
looks like `webpack/lib/NormalModuleFactory.js` at line 180 expects a string but `requestWithoutMatchResource` is an object.

**Comment by evilebottnawi** [comment]
Thanks for the issue, bug

**Comment by AriaMoradi** [comment]
@evilebottnawi this is webpack v4

**Comment by sokra** [comment]
`dependOn` is a webpack 5 feature. It doesn't work in webpack 4.
