### ISSUE TITLE
DeprecationWarning: process.binding() is deprecated

### ISSUE THREAD

**Issue by OAFCROB** [webpack/webpack#11145]
# Bug report

*Receiving node deprecation warning for [process.binding()](https://nodejs.org/api/deprecations.html#deprecations_dep0111_process_binding) from usage of lodash in webpack**

Apologises if this has already been raised but we're currently receiving the following error in our logs every time we hit out Lambdas, when we have the node options to show the pending deprecation warnings. 

`NODE_OPTIONS: "--trace-warnings --pending-deprecation"` 

```
ERROR	(node:8) [DEP0111] DeprecationWarning: process.binding() is deprecated. Please use public APIs instead.
    at /var/task/src/handlers/webpack:/node_modules/lodash/_nodeUtil.js:26:62
    at Object.<anonymous> (/var/task/src/handlers/webpack:/node_modules/lodash/_nodeUtil.js:16:16)
    at Object.call (/var/task/src/handlers/index.js:1030:16134)
    at r (/var/task/src/handlers/webpack:/webpack/bootstrap:19:22)
    at Object.call (/var/task/src/handlers/webpack:/node_modules/lodash/isTypedArray.js:3:16)
    at r (/var/task/src/handlers/webpack:/webpack/bootstrap:19:22)
    at Object.call (/var/task/src/handlers/webpack:/node_modules/lodash/_arrayLikeKeys.js:6:20)
    at r (/var/task/src/handlers/webpack:/webpack/bootstrap:19:22)
    at Object.call (/var/task/src/handlers/webpack:/node_modules/lodash/keys.js:1:21)
    at r (/var/task/src/handlers/webpack:/webpack/bootstrap:19:22)
```

**If the current behavior is a bug, please provide the steps to reproduce.**

- Enable pending deprecation warnings and trace warnings for node
`NODE_OPTIONS: "--trace-warnings --pending-deprecation"` 

**What is the expected behavior?**
No deprecation warnings for node 10+

**Other relevant information:**
webpack version:  4.43.0
Node.js version: nodejs12.x
Operating System: 
Additional tools:

**Comment by evilebottnawi** [comment]
Please open an issue in `lodash`, you can see it in stacktrace

**Comment by evilebottnawi** [comment]
We don't use `lodash` in `v4` (https://github.com/webpack/webpack/blob/v4.43.0/package.json#L7) and `v5` (https://github.com/webpack/webpack/blob/v5.0.0-beta.22/package.json#L7)

**Comment by OAFCROB** [comment]
Nice 👍 that will definitely solve the problem, is there any timeframe to when v5 is going to be out of beta?

**Comment by evilebottnawi** [comment]
@OAFCROB Roadmap here https://github.com/webpack/webpack/projects/5
