### ISSUE TITLE
Cannot read property 'filter' of undefined

### ISSUE THREAD

**Issue by novaknole** [webpack/webpack#11178]
**What is the current behavior?**

Here is the code I am using :

```js
const mode = process.env.NODE_ENV;

const BundleAnalyzerPlugin      = require('webpack-bundle-analyzer').BundleAnalyzerPlugin;
const OptimizeCSSAssetsPlugin   = require('optimize-css-assets-webpack-plugin');
const TerserPlugin              = require('terser-webpack-plugin');
const CompressionPlugin         = require('compression-webpack-plugin');

const md5 = require('md5');

module.exports = {
  publicPath: '/',
  outputDir: 'dist',
  css: { 
    extract: mode === 'production'
  },

  productionSourceMap: mode !== 'production',

  chainWebpack: config => {
    // remove the prefetch plugin
    config.plugins.delete('prefetch')

    if(mode === 'production') config.module.rules.delete('eslint');

    config.plugin('CompressionPlugin').use(CompressionPlugin);
    
  },

  configureWebpack: {
    // Define the asset compression properties
    optimization: {

        minimizer: [
          new OptimizeCSSAssetsPlugin({
              cssProcessorPluginOptions: {
                  preset: [ 'default', { discardComments: { removeAll: true } } ]
              }
          }),

          new TerserPlugin({
              parallel: true,
              extractComments: {
                  condition: true,
                  filename: (fileData) => {
                      return `${fileData.filename}.LICENSE.txt${fileData.query}`;
                  },
                  banner: () => ''
              }
          })
        ],


        splitChunks: {
            chunks: 'all',
            maxInitialRequests: Infinity,
            minSize: 0,
            cacheGroups: {
                vendors: {
                    test: /[\\/]node_modules[\\/].*\.js$/,
                    chunks: 'all',
                    name: module => {

                        const packageName = module.context.match(/[\\/]node_modules[\\/](.*?)([\\/]|$)/)[1];

                        return md5(`npm.${packageName}`)
                            .substring(0, 8);

                    }
                }
            }
        }
    },
    plugins: [
      // new BundleAnalyzerPlugin()
    ]
  }


}
```

This is what I have in `package.json`

```
"serve": "rimraf -rf ./node_modules/.cache/vue-loader && node --max_old_space_size=4096 ./node_modules/@vue/cli-service/bin/vue-cli-service.js serve --open",
```

After running `npm run serve`, all looks fine. If I hit `ctrl+s` to save something I changed, it builts again, but exits from terminal with the following error: 

```
const removedModules = records.chunkModuleIds[chunkId].filter(
                                                                                                                       ^
TypeError: Cannot read property 'filter' of undefined

```

The file that this happens is `HotModuleReplacementPlugin.js:272`. 

**What is the expected behavior?**
Expected behaviour is that after saving file , it should rebuilt without any errors.

I'd appreciate if you give me the direction of why this happens. Maybe this is solely related to vue-cli doing something in the nutshell.

**Other relevant information:**
webpack version:  Whatever vue-cli-service is using. Vue-cli version is `^4.4.6"`
Node.js version: 12.14.1
Operating System:  MacOs
Additional tools:

**Comment by evilebottnawi** [comment]
Please provide reporoducible test repo or full stack of error

**Comment by novaknole** [comment]
```
90% additional chunk assets processing HotModuleReplacementPlugin/Applications/XAMPP/xamppfiles/htdocs/fleet-fe/node_modules/webpack/lib/HotModuleReplacementPlugin.js:272
                                                                const removedModules = records.chunkModuleIds[chunkId].filter(
                                                                                                                       ^

TypeError: Cannot read property 'filter' of undefined
    at compilation.hooks.additionalChunkAssets.tap (/Applications/XAMPP/xamppfiles/htdocs/fleet-fe/node_modules/webpack/lib/HotModuleReplacementPlugin.js:272:64)
    at SyncHook.eval [as call] (eval at create (/Applications/XAMPP/xamppfiles/htdocs/fleet-fe/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:12:1)
    at SyncHook.lazyCompileHook (/Applications/XAMPP/xamppfiles/htdocs/fleet-fe/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.optimizeTree.callAsync.err (/Applications/XAMPP/xamppfiles/htdocs/fleet-fe/node_modules/webpack/lib/Compilation.js:1399:37)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Applications/XAMPP/xamppfiles/htdocs/fleet-fe/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at AsyncSeriesHook.lazyCompileHook (/Applications/XAMPP/xamppfiles/htdocs/fleet-fe/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.seal (/Applications/XAMPP/xamppfiles/htdocs/fleet-fe/node_modules/webpack/lib/Compilation.js:1342:27)
    at compilation.finish.err (/Applications/XAMPP/xamppfiles/htdocs/fleet-fe/node_modules/webpack/lib/Compiler.js:675:18)
    at hooks.finishModules.callAsync.err (/Applications/XAMPP/xamppfiles/htdocs/fleet-fe/node_modules/webpack/lib/Compilation.js:1261:4)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Applications/XAMPP/xamppfiles/htdocs/fleet-fe/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:20:1)
    at AsyncSeriesHook.lazyCompileHook (/Applications/XAMPP/xamppfiles/htdocs/fleet-fe/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.finish (/Applications/XAMPP/xamppfiles/htdocs/fleet-fe/node_modules/webpack/lib/Compilation.js:1253:28)
    at hooks.make.callAsync.err (/Applications/XAMPP/xamppfiles/htdocs/fleet-fe/node_modules/webpack/lib/Compiler.js:672:17)
    at _done (eval at create (/Applications/XAMPP/xamppfiles/htdocs/fleet-fe/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at _err1 (eval at create (/Applications/XAMPP/xamppfiles/htdocs/fleet-fe/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:32:22)
    at _addModuleChain (/Applications/XAMPP/xamppfiles/htdocs/fleet-fe/node_modules/webpack/lib/Compilation.js:1185:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vuesax-vuejs-dashboard-admin-template@2.0.0 serve: `rimraf -rf ./node_modules/.cache/vue-loader && node --max_old_space_size=4096 ./node_modules/@vue/cli-service/bin/vue-cli-service.js serve --open
`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vuesax-vuejs-dashboard-admin-template@2.0.0 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jordan/.npm/_logs/2020-07-15T15_24_41_360Z-debug.log
```

**Comment by evilebottnawi** [comment]
Looks like some kind of plugin remove chunk or change something, sorry without configuration or reproducible test repo I can't help

**Comment by novaknole** [comment]
Yes, I copied the whole `vue.config.js` ..

**Comment by evilebottnawi** [comment]
Please open an issue in `vue-cli` repo, vue-cli added plugin which break webpack, we can't solve it on our side. Can you try to update webpack to latest version?

**Comment by evilebottnawi** [comment]
Duplicate of https://github.com/webpack/webpack/issues/4759

**Comment by evilebottnawi** [comment]
https://stackoverflow.com/questions/43633762/webpack-2-hot-reload-error-typeerror-cannot-read-property-filter-of-undefined

**Comment by novaknole** [comment]
Just realised that this causes the error appear.

@evilebottnawi 

```
splitChunks: {
            chunks: 'all',
            maxInitialRequests: Infinity,
            minSize: 0,
            cacheGroups: {
                vendors: {
                    test: /[\\/]node_modules[\\/].*\.js$/,
                    chunks: 'all',
                    name: module => {

                        const packageName = module.context.match(/[\\/]node_modules[\\/](.*?)([\\/]|$)/)[1];

                        return md5(`npm.${packageName}`)
                            .substring(0, 8);

                    }
                }
            }
        }
```

**Comment by evilebottnawi** [comment]
Why do you use `md5`?

**Comment by evilebottnawi** [comment]
Closing due to inactivity. Please test with latest version and feel free to reopen if still regressions. Thanks!
