### ISSUE TITLE
Error: Cannot find module 'webpack/lib/ParserHelpers' (Angular 10)

### ISSUE THREAD

**Issue by GChuf** [webpack/webpack#11332]
# Bug report

**What is the current behavior?**

When running ng serve or ng build (angular) , I get:
`Error: Cannot find module 'webpack/lib/ParserHelpers'.`

```
Angular CLI: 10.0.6
Node: 12.18.2
OS: win32 x64


Angular: 10.0.9
... common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.6
@angular-devkit/build-angular     0.1000.6
@angular-devkit/build-optimizer   0.1000.6
@angular-devkit/build-webpack     0.1000.6
@angular-devkit/core              10.0.6
@angular-devkit/schematics        10.0.6
@angular/cli                      10.0.6
@ngtools/webpack                  10.0.6
@schematics/angular               10.0.6
@schematics/update                0.1000.6
rxjs                              6.6.2
typescript                        3.9.7
webpack                           5.0.0-beta.26
```

```
[error] Error: Cannot find module 'webpack/lib/ParserHelpers'
Require stack:
- C:\Work\Angular\ipro-alis-ng10 working version\node_modules\worker-plugin\dist\worker-plugin.js
- C:\Work\Angular\ipro-alis-ng10 working version\node_modules\@angular-devkit\build-angular\src\angular-cli-files\models\webpack-configs\worker.js
- C:\Work\Angular\ipro-alis-ng10 working version\node_modules\@angular-devkit\build-angular\src\angular-cli-files\models\webpack-configs\index.js
- C:\Work\Angular\ipro-alis-ng10 working version\node_modules\@angular-devkit\build-angular\src\browser\index.js
- C:\Work\Angular\ipro-alis-ng10 working version\node_modules\@angular-devkit\architect\node\node-modules-architect-host.js
- C:\Work\Angular\ipro-alis-ng10 working version\node_modules\@angular-devkit\architect\node\index.js
- C:\Work\Angular\ipro-alis-ng10 working version\node_modules\@angular\cli\models\architect-command.js
- C:\Work\Angular\ipro-alis-ng10 working version\node_modules\@angular\cli\commands\build-impl.js
- C:\Work\Angular\ipro-alis-ng10 working version\node_modules\@angular-devkit\schematics\tools\export-ref.js
- C:\Work\Angular\ipro-alis-ng10 working version\node_modules\@angular-devkit\schematics\tools\index.js
- C:\Work\Angular\ipro-alis-ng10 working version\node_modules\@angular\cli\utilities\json-schema.js
- C:\Work\Angular\ipro-alis-ng10 working version\node_modules\@angular\cli\models\command-runner.js
- C:\Work\Angular\ipro-alis-ng10 working version\node_modules\@angular\cli\lib\cli\index.js
- C:\Users\M0119905\AppData\Roaming\npm\node_modules\@angular\cli\lib\init.js
- C:\Users\M0119905\AppData\Roaming\npm\node_modules\@angular\cli\bin\ng
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Work\Angular\ipro-alis-ng10 working version\node_modules\worker-plugin\dist\worker-plugin.js:5:37)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Work\Angular\ipro-alis-ng10 working version\node_modules\@angular-devkit\build-angular\src\angular-cli-files\models\webpack-configs\worker.js:13:22)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)

```

**If the current behavior is a bug, please provide the steps to reproduce.**

Just install webpack  5.0.0-beta.26 and try to run "ng build".

**What is the expected behavior?**

No errors. When downgrading to webpack v4, everything works as expected.
(and when bumping to v5 again, the error remains)

**Other relevant information:**
webpack version:  5.0.0-beta.26
Node.js version: v12.18.2.
Operating System: Windows 10 64bit

I tried:
- reinstalling node_modules
- running npm i webpack-cli@4.0.0-beta.8 html-webpack-plugin@latest webpack-dev-server@latest

**Comment by evilebottnawi** [comment]
Please report the issue to `angilar-cli`

**Comment by GChuf** [comment]
Done:
https://github.com/angular/angular-cli/issues/18556
