### ISSUE TITLE
Symlink for node_modules can break resolveFilename

### ISSUE THREAD

**Issue by tajo** [webpack/webpack#1134]
Sometimes it's useful to have `node_modules/` in a different location than the rest of project (caching). In that case, you have to create a symbolic symlink in the root of your project and it works fine:

```
node_modules -> /some/absolute/path/node_modules/
```

However, the endpoint folder must be called `node_modules`. This symlink doesn't work: 

```
node_modules -> /some/absolute/path/modules/
```

It throws this error:

```
Error: Cannot find module 'webpack/lib/ConcatSource'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/some/absolute/path/modules/extract-text-webpack-plugin/index.js:5:20)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

That can be confusing.

**Comment by foxx** [comment]
I had no idea that renaming to `node_modules` would fix this symlink problem, thank you @tajo!

This has been raised in `npm`;
https://github.com/npm/npm/issues/9479
