### ISSUE TITLE
[webpack 5] generators broken in production mode 

### ISSUE THREAD

**Issue by evilebottnawi** [webpack/webpack#11353]
We are seeing an error when trying to compile a package in webpack 5.0.0-beta.27 (as well as a few earlier betas), but only when compiling in production mode. It works fine in webpack 4.44.1 in both production and development mode. A reproduction repo and instructions are at https://github.com/blink1073/vega-webpack-5. The file that seems to be giving problems is https://github.com/vega/vega/blob/master/packages/vega-statistics/src/numbers.js, perhaps because of a default export that is a generator function?

```js
export default function*(values, valueof) {
  if (valueof == null) {
    for (let value of values) {
...
```
The error we are seeing when compiling with webpack 5.0.0-beta.27 (and a few earlier betas as well) in production mode is:

```
ERROR in ./node_modules/vega/index.js + 950 modules
Unexpected token (1:71)
| /* harmony default export */ function __WEBPACK_MODULE_DEFAULT_EXPORT__*(values, valueof) {
|   if (valueof == null) {
|     for (let value of values) {
while analysing module /[snip]/vega-webpack-5/node_modules/vega-statistics/src/numbers.js for concatenation
```
CC @blink1073, @domoritz

_Originally posted by @jasongrout in https://github.com/webpack/webpack/issues/9802#issuecomment-676826884_

**Comment by jasongrout** [comment]
I simplified the reproduction to a single simple file in https://github.com/blink1073/vega-webpack-5/tree/plain and elaborated a bit more on the versions of terser and terser-webpack-plugin, which look relevant. The error is now clearly from terser. Interestingly, when downgrading to webpack 4 (which works), we have the same version of terser, but  terser-webpack-plugin does downgrade.

**Comment by jasongrout** [comment]
Error from terser in https://github.com/blink1073/vega-webpack-5/tree/plain:

```sh
ERROR in main.js from Terser
Unexpected token operator «*», expected punc «(» [main.js:3,64]
    at ee (/[snip]/vega-webpack-5/node_modules/terser/dist/bundle.min.js:1:19541)
    at c (/[snip]/vega-webpack-5/node_modules/terser/dist/bundle.min.js:1:28244)
    at l (/[snip]/vega-webpack-5/node_modules/terser/dist/bundle.min.js:1:28335)
    at p (/[snip]/vega-webpack-5/node_modules/terser/dist/bundle.min.js:1:28475)
    at _ (/[snip]/vega-webpack-5/node_modules/terser/dist/bundle.min.js:1:28587)
    at /[snip]/vega-webpack-5/node_modules/terser/dist/bundle.min.js:1:38014
    at x (/[snip]/vega-webpack-5/node_modules/terser/dist/bundle.min.js:1:38144)
    at F (/[snip]/vega-webpack-5/node_modules/terser/dist/bundle.min.js:1:34820)
    at /[snip]/vega-webpack-5/node_modules/terser/dist/bundle.min.js:1:32263
    at /[snip]/vega-webpack-5/node_modules/terser/dist/bundle.min.js:1:28976
```

**Comment by evilebottnawi** [comment]
@jasongrout Can you try to use latest `terser-webpack-plugin`?

**Comment by evilebottnawi** [comment]
Can you write `npm ls terser`?

**Comment by jasongrout** [comment]
I'm using yarn. From the readme at https://github.com/blink1073/vega-webpack-5/tree/plain:

> We see the error with `terser` 4.8.0 and `terser-webpack-plugin` 3.1.0.

> If I change the webpack version in `package.json` to `^4`, `yarn run build:prod` now works, and the generated file contains the generator function. In this case, `terser` 4.8.0 is still installed, but `terser-webpack-plugin` is downgraded to 1.4.5.

I notice that terser-webpack-plugin has released 4.1.0. I'll try that.

**Comment by evilebottnawi** [comment]
Bug on `webpack` side

**Comment by evilebottnawi** [comment]
Generated code:
```js
/******/ (() => { // webpackBootstrap
    /******/        "use strict";
    /* harmony default export */ function __WEBPACK_DEFAULT_EXPORT__*() {
        for (let i=0; i<10; i++) {
            yield i;
        }
    }

    /******/ })()
;

```

Expected:
```js
/******/ (() => { // webpackBootstrap
    /******/        "use strict";
    /* harmony default export */ function* __WEBPACK_DEFAULT_EXPORT__() {
        for (let i=0; i<10; i++) {
            yield i;
        }
    }

    /******/ })()
;

```

**Comment by jasongrout** [comment]
Yeah, manually forcing terser-webpack-plugin to `^4` and terser to `^5` still has an error: https://github.com/blink1073/vega-webpack-5/tree/plain-upgrade-terser

**Comment by jasongrout** [comment]
> Bug on `webpack` side

Ah, right, so the bug is also in `yarn run build` (i.e., dev mode), but I didn't notice it because I wasn't actually running the file. Terser caught it, though, which is why we saw the error. Good catch.

**Comment by sokra** [comment]
Seem like a problem in the module concatenation code -> ConcatenatedModule.js

**Comment by evilebottnawi** [comment]
Yes, thanks for the issue

**Comment by sokra** [comment]
Bug is here https://github.com/webpack/webpack/blob/e32daa9be5fed184c8befac87216a88872f7df4a/lib/dependencies/HarmonyExportDependencyParserPlugin.js#L92

The `*` should be in the prefix instead of the suffix

**Comment by sokra** [comment]
Send a pr

**Comment by jungleBadger** [comment]
> Send a pr

I tried to contribute with this one, please let me know if I can improve it in any way: https://github.com/webpack/webpack/pull/11354
