### ISSUE TITLE
Deprecation Warnings when migrated from Webpack4  to Webpack5

### ISSUE THREAD

**Issue by vishalrajole** [webpack/webpack#11393]
I am upgrading existing apps from webpack 4.43.0 to webpack 5.0.0-beta.28. I am seeing multiple deprecation warnings. I am using

```
"webpack": "^5.0.0-beta.28",
"webpack-cli": "3.3.12",
"webpack-dev-server": "3.11.0",
"html-webpack-plugin": "4.3.0",
"duplicate-package-checker-webpack-plugin": "3.0.0",

```
With above setup, when I run 
`node --trace-deprecation node_modules/webpack/bin/webpack.js --config ./webpack/webpack.development.js`
 
I am seeing following Deprecation warnings coming from `last-call-webpack-plugin` and `html-webpack-plugin` plugins

```
(node:47918) [DEP_WEBPACK_COMPILATION_OPTIMIZE_CHUNK_ASSETS] DeprecationWarning: optimizeChunkAssets is deprecated (use Compilation.hook.processAssets instead and use one of Compilation.PROCESS_ASSETS_STAGE_* as stage option)
    at /Users/vrajole/sg-core/raisin-frontend/node_modules/last-call-webpack-plugin/src/index.js:176:49
    at Hook.eval [as call] (eval at create (/Users/vrajole/sg-core/raisin-frontend/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:198:1)
    at Hook.CALL_DELEGATE [as _call] (/Users/vrajole/sg-core/raisin-frontend/node_modules/webpack/node_modules/tapable/lib/Hook.js:14:14)
    at Compiler.newCompilation (/Users/vrajole/sg-core/raisin-frontend/node_modules/webpack/lib/Compiler.js:910:26)
    at /Users/vrajole/sg-core/raisin-frontend/node_modules/webpack/lib/Compiler.js:951:29

```

```
(node:47918) [DEP_WEBPACK_MAIN_TEMPLATE_GET_PUBLIC_PATH] DeprecationWarning: MainTemplate.getPublicPath is deprecated (use Compilation.getAssetPath(compilation.outputOptions.publicPath, options) instead)
    at HtmlWebpackPlugin.htmlWebpackPluginAssets (/Users/vrajole/sg-core/raisin-frontend/node_modules/html-webpack-plugin/index.js:532:56)
    at /Users/vrajole/sg-core/raisin-frontend/node_modules/html-webpack-plugin/index.js:164:29
    at _next0 (eval at create (/Users/vrajole/sg-core/raisin-frontend/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:31:1)
    at eval (eval at create (/Users/vrajole/sg-core/raisin-frontend/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:48:1)
    at /Users/vrajole/sg-core/raisin-frontend/node_modules/duplicate-package-checker-webpack-plugin/lib/index.js:190:5
    at Hook.eval [as callAsync] (eval at create (/Users/vrajole/sg-core/raisin-frontend/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:43:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/vrajole/sg-core/raisin-frontend/node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
    at Compiler.emitAssets (/Users/vrajole/sg-core/raisin-frontend/node_modules/webpack/lib/Compiler.js:729:19)
    at /Users/vrajole/sg-core/raisin-frontend/node_modules/webpack/lib/Compiler.js:392:10
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
```

```
(node:47918) [DEP_WEBPACK_MODULE_ISSUER] DeprecationWarning: Module.issuer: Use new ModuleGraph API
    at Function.getModuleGraphForModule (/Users/vrajole/sg-core/raisin-frontend/node_modules/webpack/lib/ModuleGraph.js:695:10)
    at NormalModule.get issuer [as issuer] (/Users/vrajole/sg-core/raisin-frontend/node_modules/webpack/lib/Module.js:243:22)
    at /Users/vrajole/sg-core/raisin-frontend/node_modules/duplicate-package-checker-webpack-plugin/lib/index.js:105:29
    at Set.forEach (<anonymous>)
    at /Users/vrajole/sg-core/raisin-frontend/node_modules/duplicate-package-checker-webpack-plugin/lib/index.js:74:25
    at Hook.eval [as callAsync] (eval at create (/Users/vrajole/sg-core/raisin-frontend/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:43:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/vrajole/sg-core/raisin-frontend/node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
    at Compiler.emitAssets (/Users/vrajole/sg-core/raisin-frontend/node_modules/webpack/lib/Compiler.js:729:19)
    at /Users/vrajole/sg-core/raisin-frontend/node_modules/webpack/lib/Compiler.js:392:10
    at processTicksAndRejections (internal/process/task_queues.js:75:11)

```

Attaching screenshots for reference.

![Screenshot 2020-08-28 at 4 39 10 PM](https://user-images.githubusercontent.com/4668780/91580308-30e09680-e94d-11ea-9e7a-b89ad98e1a79.png)

![Screenshot 2020-08-28 at 4 38 50 PM](https://user-images.githubusercontent.com/4668780/91580351-3dfd8580-e94d-11ea-8d04-fbda51e8e4a9.png)

**Comment by vishalrajole** [comment]
@ScriptedAlchemy

**Comment by evilebottnawi** [comment]
Please open an issues in `last-call-webpack-plugin`, `html-webpack-plugin` and `duplicate-package-checker-webpack-plugin` plugins, we can't fix it on our side. My reccomendation to migrate from `last-call-webpack-plugin` on official CSS minimizer plugin https://github.com/webpack-contrib/css-minimizer-webpack-plugin

**Comment by vishalrajole** [comment]
It looks like `last-call-webpack-plugin` is being used by webpack internally. @evilebottnawi

**Comment by evilebottnawi** [comment]
webpack never uses `last-call-webpack-plugin`
