### ISSUE TITLE
Strange ValidationError, when config is ok

### ISSUE THREAD

**Issue by artem-malko** [webpack/webpack#11396]
# Bug report

I have the following config (optimization part):

```ts
 optimization: {
    runtimeChunk: {
      name: 'runtime',
    },

    splitChunks: {
      minChunks: 2,
      minSize: 30000,

      cacheGroups: {
        clientApplication: {
          name: 'clientApplication',
          test: /applications\/client/,
          chunks: 'all',
          enforce: true,
        },
      },
    },
```

**What is the current behavior?**

Error in logs while production build:

```bash
/Users/a.malko/Work/frontend/node_modules/schema-utils/dist/validate.js:96
    throw new _ValidationError.default(errors, schema, configuration);
          ^
ValidationError: Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
 - configuration.optimization.splitChunks should be one of these:
   false | object { automaticNameDelimiter?, cacheGroups?, chunks?, enforceSizeThreshold?, fallbackCacheGroup?, filename?, hidePathInfo?, maxAsyncRequests?, maxAsyncSize?, maxInitialRequests?, maxInitialSize?, maxSize?, minChunks?, minRemainingSize?, minSize?, name?, usedExports? }
   -> Optimize duplication and caching by splitting chunks by shared modules and cache group.
   Details:
    * configuration.optimization.splitChunks.cacheGroups['clientApplication'].test should be one of these:
      RegExp | string | function
      -> Assign modules to a cache group by module name.
      Details:
       * configuration.optimization.splitChunks.cacheGroups['clientApplication'].test should be an instance of RegExp.
       * configuration.optimization.splitChunks.cacheGroups['clientApplication'].test should be a string.
       * configuration.optimization.splitChunks.cacheGroups['clientApplication'].test should be an instance of function.
    at validate (/Users/a.malko/Work/frontend/node_modules/schema-utils/dist/validate.js:96:11)
    at validateSchema (/Users/a.malko/Work/frontend/node_modules/webpack/lib/validateSchema.js:45:2)
    at webpack (/Users/a.malko/Work/frontend/node_modules/webpack/lib/webpack.js:100:2)
    at f (/Users/a.malko/Work/frontend/node_modules/webpack/lib/index.js:31:15)
    at processOptions (/Users/a.malko/Work/frontend/node_modules/webpack-cli/bin/cli.js:272:16)
    at /Users/a.malko/Work/frontend/node_modules/webpack-cli/bin/cli.js:364:3
    at Object.parse (/Users/a.malko/Work/frontend/node_modules/yargs/yargs.js:576:18)
    at /Users/a.malko/Work/frontend/node_modules/webpack-cli/bin/cli.js:49:8
    at Object.<anonymous> (/Users/a.malko/Work/frontend/node_modules/webpack-cli/bin/cli.js:366:3)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
    at Function.Module._load (internal/modules/cjs/loader.js:929:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```

**If the current behavior is a bug, please provide the steps to reproduce.**

You can clone this repo https://github.com/artem-malko/webpack-5-beta-config-bug and try it by yourself.

**What is the expected behavior?**

No errors)

**Other relevant information:**
webpack version:  v5.0.0-beta.26-v5.0.0-beta.29
Node.js version: v14.1.0
Operating System: macOS Catalina
Additional tools:

**Comment by evilebottnawi** [comment]
@artem-malko just note, you don't need `brotli-webpack-plugin`, because https://github.com/webpack-contrib/compression-webpack-plugin#using-brotli

**Comment by evilebottnawi** [comment]
Something buggy on `ts` side, because because webpack gets:
```
{ clientApplication:
   { name: 'clientApplication',
     test: {},
     chunks: 'all',
     enforce: true } }
```

**Comment by evilebottnawi** [comment]
Yes, bug on `webpack-merge` side

**Comment by evilebottnawi** [comment]
Close in favor https://github.com/survivejs/webpack-merge/issues/145

**Comment by artem-malko** [comment]
@evenstensberg thx a lot!
