### ISSUE TITLE
Webpack 5 : HookWebpackError: chunk.files.delete is not a function

### ISSUE THREAD

**Issue by jimblue** [webpack/webpack#11450]
# Bug report

**What is the current behavior?**

Webpack trow the following error on build:

```bash
HookWebpackError: chunk.files.delete is not a function
    at makeWebpackError (/Users/jimblue/Dev/website/node_modules/webpack/lib/HookWebpackError.js:49:9)
    at /Users/jimblue/Dev/website/node_modules/webpack/lib/Compilation.js:1978:11
    at eval (eval at create (/Users/jimblue/Dev/website/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:1:1), <anonymous>:24:1)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
-- inner error --
TypeError: chunk.files.delete is not a function
    at Compilation.renameAsset (/Users/jimblue/Dev/website/node_modules/webpack/lib/Compilation.js:2858:22)
    at /Users/jimblue/Dev/website/node_modules/webpack/lib/optimize/RealContentHashPlugin.js:262:21
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 9)
    at async /Users/jimblue/Dev/website/node_modules/webpack/lib/optimize/RealContentHashPlugin.js:234:6

caused by plugins in Compilation.hooks.processAssets
TypeError: chunk.files.delete is not a function
    at Compilation.renameAsset (/Users/jimblue/Dev/website/node_modules/webpack/lib/Compilation.js:2858:22)
    at /Users/jimblue/Dev/website/node_modules/webpack/lib/optimize/RealContentHashPlugin.js:262:21
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 9)
    at async /Users/jimblue/Dev/website/node_modules/webpack/lib/optimize/RealContentHashPlugin.js:234:6
```

**What is the expected behavior?**

Webpack should build without error.

**Other relevant information:**
webpack version:  5.0.0-beta.29
Node.js version: 14.9.0
Operating System: macOS Catalina 10.15.6

**Comment by evilebottnawi** [comment]
@jimblue Can you create reproducible test repo?

**Comment by sokra** [comment]
Could you run `yarn why webpack` resp. `npm ls webpack` to see if you have multiple different webpack versions installed?

**Comment by jimblue** [comment]
@sokra indeed seems to have multiple version installed:

```bash
├─┬ purgecss-webpack-plugin@2.3.0
│ └── webpack@4.44.1
└── UNMET PEER DEPENDENCY webpack@5.0.0-beta.29

npm ERR! peer dep missing: webpack@>=2, required by babel-loader@8.1.0
npm ERR! peer dep missing: webpack@^4.27.0 || ^5.0.0, required by css-loader@4.3.0
npm ERR! peer dep missing: webpack@^1 || ^2 || ^3 || ^4, required by dotenv-webpack@2.0.0
npm ERR! peer dep missing: webpack@^4.0.0 || ^5.0.0, required by eslint-webpack-plugin@2.1.0
npm ERR! peer dep missing: webpack@^4.0.0 || ^5.0.0, required by file-loader@6.1.0
npm ERR! peer dep missing: webpack@^4.0.0, required by friendly-errors-webpack-plugin@2.0.0-beta.2
npm ERR! peer dep missing: webpack@^4.4.0 || ^5.0.0, required by mini-css-extract-plugin@0.11.1
npm ERR! peer dep missing: webpack@^4.0.0 || ^5.0.0, required by postcss-loader@4.0.1
npm ERR! peer dep missing: webpack@^4.36.0 || ^5.0.0, required by sass-loader@10.0.2
npm ERR! peer dep missing: webpack@^4.0.0 || ^5.0.0, required by stylelint-webpack-plugin@2.1.0
npm ERR! peer dep missing: webpack@^4.0.0 || ^5.0.0, required by terser-webpack-plugin@4.1.0
npm ERR! peer dep missing: webpack@>=4.4.0, required by webpack-assets-manifest@3.1.1
npm ERR! peer dep missing: webpack@^4.0.0 || ^5.0.0, required by webpack-dev-server@3.11.0
npm ERR! peer dep missing: webpack@^4 || ^5, required by webpack-dev-server-waitpage@2.0.1
```

**Comment by evilebottnawi** [comment]
You have two version of webpack, https://github.com/FullHuman/purgecss/blob/master/packages/purgecss-webpack-plugin/package.json#L38, please report issue in `purgecss-webpack-plugin`, we can't fix it on our side

**Comment by jimblue** [comment]
I think you close that issue way to fast @evilebottnawi.
10min is not enough time to investigate...

Anyway just remove `purgecss-webpack-plugin` and check for multiple webpack version:

```bash
└── UNMET PEER DEPENDENCY webpack@5.0.0-beta.29

npm ERR! peer dep missing: webpack@>=2, required by babel-loader@8.1.0
npm ERR! peer dep missing: webpack@^4.27.0 || ^5.0.0, required by css-loader@4.3.0
npm ERR! peer dep missing: webpack@^1 || ^2 || ^3 || ^4, required by dotenv-webpack@2.0.0
npm ERR! peer dep missing: webpack@^4.0.0 || ^5.0.0, required by eslint-webpack-plugin@2.1.0
npm ERR! peer dep missing: webpack@^4.0.0 || ^5.0.0, required by file-loader@6.1.0
npm ERR! peer dep missing: webpack@^4.0.0, required by friendly-errors-webpack-plugin@2.0.0-beta.2
npm ERR! peer dep missing: webpack@^4.4.0 || ^5.0.0, required by mini-css-extract-plugin@0.11.1
npm ERR! peer dep missing: webpack@^4.0.0 || ^5.0.0, required by postcss-loader@4.0.1
npm ERR! peer dep missing: webpack@^4.36.0 || ^5.0.0, required by sass-loader@10.0.2
npm ERR! peer dep missing: webpack@^4.0.0 || ^5.0.0, required by stylelint-webpack-plugin@2.1.0
npm ERR! peer dep missing: webpack@^4.0.0 || ^5.0.0, required by terser-webpack-plugin@4.1.0
npm ERR! peer dep missing: webpack@>=4.4.0, required by webpack-assets-manifest@3.1.1
npm ERR! peer dep missing: webpack@^4.0.0 || ^5.0.0, required by webpack-dev-server@3.11.0
npm ERR! peer dep missing: webpack@^4 || ^5, required by webpack-dev-server-waitpage@2.0.1
```

But still getting the same error.

Can you please re open, thank you 😄

**Comment by evilebottnawi** [comment]
@jimblue you remove section `How we can reproduce?`, please update the original issue and I will reopen, we can't fix something somewhere

**Comment by evilebottnawi** [comment]
`dotenv-webpack` and `friendly-errors-webpack-plugin` do not have compatibility with webpack@5

**Comment by jimblue** [comment]
@evilebottnawi, I've just try to disable `dotenv-webpack`, `friendly-errors-webpack-plugin` and `purgecss-webpack-plugin` from webpack config but still getting the same error.

I'll try to create a repo so you can reproduce.

**Comment by evilebottnawi** [comment]
@jimblue feel free to ping me

**Comment by evilebottnawi** [comment]
Do not forget you need to remove `purgecss-webpack-plugin` from node_modules too

**Comment by jimblue** [comment]
sure thank you @evilebottnawi 👍🏼

**Comment by jimblue** [comment]
🌮  This is fixed with V5 release 🌮
