### ISSUE TITLE
Webpack 5 build failure: Error: "." is not in the SourceMap

### ISSUE THREAD

**Issue by AlonMiz** [webpack/webpack#11469]
# Bug report

**What is the current behavior?**
Build is breaking in webpack 5.0.0-beta.28, something related to sourcemap
`UnhandledPromiseRejectionWarning: Error: "." is not in the SourceMap`
while the build with 5.0.0-beta.27 works great

```
[compile:ci] (node:78) [DEP_WEBPACK_MAIN_TEMPLATE_GET_ASSET_PATH] DeprecationWarning: MainTemplate.getAssetPath is deprecated (use Compilation.getAssetPath instead)
[compile:ci] (node:78) UnhandledPromiseRejectionWarning: Error: "." is not in the SourceMap.
[compile:ci]     at BasicSourceMapConsumer.SourceMapConsumer_sourceContentFor [as sourceContentFor] (/src/node_modules/source-map/lib/source-map-consumer.js:753:13)
[compile:ci]     at /src/app-frontend/node_modules/webpack-sources/lib/applySourceMap.js:144:46
[compile:ci]     at SourceNode_walk [as walk] (/src/node_modules/source-map/lib/source-node.js:230:9)
[compile:ci]     at SourceNode_walk [as walk] (/src/node_modules/source-map/lib/source-node.js:226:13)
[compile:ci]     at applySourceMap (/src/app-frontend/node_modules/webpack-sources/lib/applySourceMap.js:58:13)
[compile:ci]     at SourceMapSource.node (/src/app-frontend/node_modules/webpack-sources/lib/SourceMapSource.js:198:11)
[compile:ci]     at exports.getSourceAndMap (/src/app-frontend/node_modules/webpack-sources/lib/helpers.js:17:21)
[compile:ci]     at SourceMapSource.sourceAndMap (/src/app-frontend/node_modules/webpack-sources/lib/SourceMapSource.js:184:10)
[compile:ci]     at getTaskForFile (/src/app-frontend/node_modules/webpack/lib/SourceMapDevToolPlugin.js:77:30)
[compile:ci]     at /src/app-frontend/node_modules/webpack/lib/SourceMapDevToolPlugin.js:264:22
[compile:ci]     at /src/app-frontend/node_modules/webpack/lib/Cache.js:93:5
[compile:ci]     at Hook.eval [as callAsync] (eval at create (/src/app-frontend/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
[compile:ci]     at Cache.get (/src/app-frontend/node_modules/webpack/lib/Cache.js:75:18)
[compile:ci]     at ItemCacheFacade.get (/src/app-frontend/node_modules/webpack/lib/CacheFacade.js:116:15)
[compile:ci]     at /src/app-frontend/node_modules/webpack/lib/SourceMapDevToolPlugin.js:215:18
[compile:ci]     at arrayEach (/src/node_modules/neo-async/async.js:2405:9)
[compile:ci]     at Object.each (/src/node_modules/neo-async/async.js:2846:9)
[compile:ci]     at /src/app-frontend/node_modules/webpack/lib/SourceMapDevToolPlugin.js:202:15
[compile:ci]     at _next1 (eval at create (/src/app-frontend/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:22:1)
[compile:ci]     at eval (eval at create (/src/app-frontend/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:38:1)
[compile:ci]     at processTicksAndRejections (internal/process/task_queues.js:93:5)
[compile:ci] (node:78) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
[compile:ci] (node:78) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**If the current behavior is a bug, please provide the steps to reproduce.**
```
const config = {
  context,
  mode: 'production',
  devtool: 'source-map',
  entry: {
    app: './app/app.ts',
  },
  output: {
    pathinfo: false,
    path: path.join(context, '../dist'),
    filename: '[name].app.bundle.[contenthash].js',
    chunkFilename: '[name].app.bundle.[contenthash].js',
  },
  module: {
    rules: [tsRule({ configFile: tsConfigFilePath, transpileOnly: true }), cssRule, htmlRule, lessRule, staticRule],
  },
  resolve,
  optimization,
  plugins: [
    new ForkTsCheckerWebpackPlugin({
      tsconfig: tsConfigFilePath,
    }),
    new webpack.DefinePlugin({
      ENV_NAME: JSON.stringify(ENV_NAME) || '"LOCAL"',
      ENV_OVERRIDE: JSON.stringify(ENV_OVERRIDE),
    }),
    new HtmlWebpackPlugin(htmlPluginOptions),
    new CopyWebpackPlugin([
      {
        context: './assets',
        from: '**',
        to: './assets',
      },
    ]),
    new CopyWebpackPlugin([
      {
        context: './static',
        from: '**',
        to: './static',
      },
    ]),
  ],
};

```

**What is the expected behavior?**
the build to work with a working sourcemap

**Other relevant information:**
webpack version:  webpack 5.0.0-beta.28
Node.js version: v12.14.1
Operating System: mac os
Additional tools:

**Comment by goto-bus-stop** [comment]
I think this is a terser-webpack-plugin issue. I'm seeing the same thing, and the build runs fine when setting `optimization.minimize: false`.

**Comment by evilebottnawi** [comment]
You have broken source maps, without reproducible test repo we can't help, please open new issue in `terser-webpack-plugin` with reproducible test repo

**Comment by leaves4j** [comment]
the same, `terser-webpack-plugin` version 4.1.0 is fine.

**Comment by evilebottnawi** [comment]
@leaves4j Can you open new issue in terser-webpack-plugin with reproducible example?

**Comment by dlong500** [comment]
@evilebottnawi For what it's worth, I'm also experiencing this error with terser-webpack-plugin v4.2.x.  Everything works fine with v4.1.0.  I don't have time at the moment to look into it but just wanted to voice a concern that something definitely seems to be broken.  I'll open an issue over there when I have time to create a minimal example (assuming it doesn't get fixed before then).

**Comment by evilebottnawi** [comment]
Yes, please create reproducible test repo in `terser-webpack-plugin`, we don't change source map handling, maybe `ts` stuff have updates?
