### ISSUE TITLE
throw err:Cannot find modele 'assert/'

### ISSUE THREAD

**Issue by ningrixin** [webpack/webpack#1147]
I followed the webpack tutorial and got this error.
ningrixindeMacBook-Pro:wptest ningrixin$ webpack ./entry.js bundle.js
module.js:338
    throw err;
    ^
Error: Cannot find module 'assert/'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.require.resolve (module.js:388:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/node-libs-browser/index.js:1:93)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/webpack/lib/node/NodeSourcePlugin.js:7:23)

Here is the same question in stackoverflow(https://stackoverflow.com/questions/30624753/error-with-webpack-when-follow-official-tutorial)

**Comment by shama** [comment]
It looks like your question was answered on stackoverflow, mind closing the issue here?
