### ISSUE TITLE
corejs error after update to beta 30

### ISSUE THREAD

**Issue by daveisfera** [webpack/webpack#11484]
# Bug report

**What is the current behavior?**
Our build worked with beta 29 and previous, but is failing with beta 30 with the following error:
```
[
    {
        "moduleIdentifier": "/usr/src/app/node_modules/@babel/runtime-corejs2/helpers/esm/extends.js",
        "moduleName": "../node_modules/@babel/runtime-corejs2/helpers/esm/extends.js",
        "loc": "1:0-57",
        "message": "Module not found: Error: Can't resolve '../../core-js/object/assign' in '/usr/src/app/node_modules/@babel/runtime-corejs2/helpers/esm'",
        "moduleId": "../node_modules/@babel/runtime-corejs2/helpers/esm/extends.js",
        "moduleTrace": [
            {
                "originIdentifier": "/usr/src/app/node_modules/react-bootstrap/es/utils/bootstrapUtils.js",
                "originName": "../node_modules/react-bootstrap/es/utils/bootstrapUtils.js",
                "moduleIdentifier": "/usr/src/app/node_modules/@babel/runtime-corejs2/helpers/esm/extends.js",
                "moduleName": "../node_modules/@babel/runtime-corejs2/helpers/esm/extends.js",
                "dependencies": [
                    {
                        "loc": "2:0-66"
                    },
                    {
                        "loc": "55:24-32"
                    },
                    {
                        "loc": "93:24-32"
                    }
                ],
                "originId": "../node_modules/react-bootstrap/es/utils/bootstrapUtils.js",
                "moduleId": "../node_modules/@babel/runtime-corejs2/helpers/esm/extends.js"
            },
            {
                "originIdentifier": "/usr/src/app/node_modules/react-bootstrap/es/Tooltip.js",
                "originName": "../node_modules/react-bootstrap/es/Tooltip.js",
                "moduleIdentifier": "/usr/src/app/node_modules/react-bootstrap/es/utils/bootstrapUtils.js",
                "moduleName": "../node_modules/react-bootstrap/es/utils/bootstrapUtils.js",
                "dependencies": [
                    {
                        "loc": "8:0-84"
                    },
                    {
                        "loc": "71:24-36"
                    },
                    {
                        "loc": "75:31-42"
                    },
                    {
                        "loc": "91:17-23"
                    },
                    {
                        "loc": "94:17-23"
                    },
                    {
                        "loc": "103:15-22"
                    }
                ],
                "originId": "../node_modules/react-bootstrap/es/Tooltip.js",
                "moduleId": "../node_modules/react-bootstrap/es/utils/bootstrapUtils.js"
            },
            {
                "originIdentifier": "/usr/src/app/node_modules/react-bootstrap/es/index.js",
                "originName": "../node_modules/react-bootstrap/es/index.js",
                "moduleIdentifier": "/usr/src/app/node_modules/react-bootstrap/es/Tooltip.js",
                "moduleName": "../node_modules/react-bootstrap/es/Tooltip.js",
                "dependencies": [
                    {
                        "loc": "137:0-33"
                    },
                    {
                        "loc": "138:0-31"
                    }
                ],
                "originId": "../node_modules/react-bootstrap/es/index.js",
                "moduleId": "../node_modules/react-bootstrap/es/Tooltip.js"
            },
            {
                "originIdentifier": "/usr/src/app/node_modules/babel-loader/lib/index.js??ruleSet[1].rules[0].use[0]!/usr/src/app/admin/src/apps/admin/components/CreateUserModal.jsx",
                "originName": "./src/apps/admin/components/CreateUserModal.jsx",
                "moduleIdentifier": "/usr/src/app/node_modules/react-bootstrap/es/index.js",
                "moduleName": "../node_modules/react-bootstrap/es/index.js",
                "dependencies": [
                    {
                        "loc": "10:22-48"
                    }
                ],
                "originId": "./src/apps/admin/components/CreateUserModal.jsx",
                "moduleId": "../node_modules/react-bootstrap/es/index.js"
            },
            {
                "originIdentifier": "/usr/src/app/node_modules/babel-loader/lib/index.js??ruleSet[1].rules[0].use[0]!/usr/src/app/admin/src/apps/admin/components/UsersPage.jsx",
                "originName": "./src/apps/admin/components/UsersPage.jsx",
                "moduleIdentifier": "/usr/src/app/node_modules/babel-loader/lib/index.js??ruleSet[1].rules[0].use[0]!/usr/src/app/admin/src/apps/admin/components/CreateUserModal.jsx",
                "moduleName": "./src/apps/admin/components/CreateUserModal.jsx",
                "dependencies": [
                    {
                        "loc": "14:46-74"
                    }
                ],
                "originId": "./src/apps/admin/components/UsersPage.jsx",
                "moduleId": "./src/apps/admin/components/CreateUserModal.jsx"
            },
            {
                "originIdentifier": "/usr/src/app/node_modules/babel-loader/lib/index.js??ruleSet[1].rules[0].use[0]!/usr/src/app/admin/src/apps/admin/app.jsx",
                "originName": "./src/apps/admin/app.jsx",
                "moduleIdentifier": "/usr/src/app/node_modules/babel-loader/lib/index.js??ruleSet[1].rules[0].use[0]!/usr/src/app/admin/src/apps/admin/components/UsersPage.jsx",
                "moduleName": "./src/apps/admin/components/UsersPage.jsx",
                "dependencies": [
                    {
                        "loc": "27:40-73"
                    }
                ],
                "originId": "./src/apps/admin/app.jsx",
                "moduleId": "./src/apps/admin/components/UsersPage.jsx"
            }
        ],
        "details": "resolve '../../core-js/object/assign' in '/usr/src/app/node_modules/@babel/runtime-corejs2/helpers/esm'\n  using description file: /usr/src/app/node_modules/@babel/runtime-corejs2/helpers/esm/package.json (relative path: .)\n    Field 'browser' doesn't contain a valid alias configuration\n    using description file: /usr/src/app/node_modules/@babel/runtime-corejs2/package.json (relative path: ./core-js/object/assign)\n      Field 'browser' doesn't contain a valid alias configuration\n      /usr/src/app/node_modules/@babel/runtime-corejs2/core-js/object/assign doesn't exist",
        "stack": "ModuleNotFoundError: Module not found: Error: Can't resolve '../../core-js/object/assign' in '/usr/src/app/node_modules/@babel/runtime-corejs2/helpers/esm'\n    at /usr/src/app/node_modules/webpack/lib/Compilation.js:1470:28\n    at /usr/src/app/node_modules/webpack/lib/NormalModuleFactory.js:647:13\n    at eval (eval at create (/usr/src/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:8:1)\n    at /usr/src/app/node_modules/webpack/lib/NormalModuleFactory.js:233:22\n    at eval (eval at create (/usr/src/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:7:1)\n    at /usr/src/app/node_modules/webpack/lib/NormalModuleFactory.js:357:22\n    at /usr/src/app/node_modules/webpack/lib/NormalModuleFactory.js:116:11\n    at /usr/src/app/node_modules/webpack/lib/NormalModuleFactory.js:576:24\n    at finishWithoutResolve (/usr/src/app/node_modules/enhanced-resolve/lib/Resolver.js:284:11)\n    at /usr/src/app/node_modules/enhanced-resolve/lib/Resolver.js:350:15"
    },
    {
        "moduleIdentifier": "/usr/src/app/node_modules/@babel/runtime-corejs2/helpers/esm/inheritsLoose.js",
        "moduleName": "../node_modules/@babel/runtime-corejs2/helpers/esm/inheritsLoose.js",
        "loc": "1:0-57",
        "message": "Module not found: Error: Can't resolve '../../core-js/object/create' in '/usr/src/app/node_modules/@babel/runtime-corejs2/helpers/esm'",
        "moduleId": "../node_modules/@babel/runtime-corejs2/helpers/esm/inheritsLoose.js",
        "moduleTrace": [
            {
                "originIdentifier": "/usr/src/app/node_modules/react-bootstrap/es/Tooltip.js",
                "originName": "../node_modules/react-bootstrap/es/Tooltip.js",
                "moduleIdentifier": "/usr/src/app/node_modules/@babel/runtime-corejs2/helpers/esm/inheritsLoose.js",
                "moduleName": "../node_modules/@babel/runtime-corejs2/helpers/esm/inheritsLoose.js",
                "dependencies": [
                    {
                        "loc": "3:0-78"
                    },
                    {
                        "loc": "49:2-16"
                    }
                ],
                "originId": "../node_modules/react-bootstrap/es/Tooltip.js",
                "moduleId": "../node_modules/@babel/runtime-corejs2/helpers/esm/inheritsLoose.js"
            },
            {
                "originIdentifier": "/usr/src/app/node_modules/react-bootstrap/es/index.js",
                "originName": "../node_modules/react-bootstrap/es/index.js",
                "moduleIdentifier": "/usr/src/app/node_modules/react-bootstrap/es/Tooltip.js",
                "moduleName": "../node_modules/react-bootstrap/es/Tooltip.js",
                "dependencies": [
                    {
                        "loc": "137:0-33"
                    },
                    {
                        "loc": "138:0-31"
                    }
                ],
                "originId": "../node_modules/react-bootstrap/es/index.js",
                "moduleId": "../node_modules/react-bootstrap/es/Tooltip.js"
            },
            {
                "originIdentifier": "/usr/src/app/node_modules/babel-loader/lib/index.js??ruleSet[1].rules[0].use[0]!/usr/src/app/admin/src/apps/admin/components/CreateUserModal.jsx",
                "originName": "./src/apps/admin/components/CreateUserModal.jsx",
                "moduleIdentifier": "/usr/src/app/node_modules/react-bootstrap/es/index.js",
                "moduleName": "../node_modules/react-bootstrap/es/index.js",
                "dependencies": [
                    {
                        "loc": "10:22-48"
                    }
                ],
                "originId": "./src/apps/admin/components/CreateUserModal.jsx",
                "moduleId": "../node_modules/react-bootstrap/es/index.js"
            },
            {
                "originIdentifier": "/usr/src/app/node_modules/babel-loader/lib/index.js??ruleSet[1].rules[0].use[0]!/usr/src/app/admin/src/apps/admin/components/UsersPage.jsx",
                "originName": "./src/apps/admin/components/UsersPage.jsx",
                "moduleIdentifier": "/usr/src/app/node_modules/babel-loader/lib/index.js??ruleSet[1].rules[0].use[0]!/usr/src/app/admin/src/apps/admin/components/CreateUserModal.jsx",
                "moduleName": "./src/apps/admin/components/CreateUserModal.jsx",
                "dependencies": [
                    {
                        "loc": "14:46-74"
                    }
                ],
                "originId": "./src/apps/admin/components/UsersPage.jsx",
                "moduleId": "./src/apps/admin/components/CreateUserModal.jsx"
            },
            {
                "originIdentifier": "/usr/src/app/node_modules/babel-loader/lib/index.js??ruleSet[1].rules[0].use[0]!/usr/src/app/admin/src/apps/admin/app.jsx",
                "originName": "./src/apps/admin/app.jsx",
                "moduleIdentifier": "/usr/src/app/node_modules/babel-loader/lib/index.js??ruleSet[1].rules[0].use[0]!/usr/src/app/admin/src/apps/admin/components/UsersPage.jsx",
                "moduleName": "./src/apps/admin/components/UsersPage.jsx",
                "dependencies": [
                    {
                        "loc": "27:40-73"
                    }
                ],
                "originId": "./src/apps/admin/app.jsx",
                "moduleId": "./src/apps/admin/components/UsersPage.jsx"
            }
        ],
        "details": "resolve '../../core-js/object/create' in '/usr/src/app/node_modules/@babel/runtime-corejs2/helpers/esm'\n  using description file: /usr/src/app/node_modules/@babel/runtime-corejs2/helpers/esm/package.json (relative path: .)\n    Field 'browser' doesn't contain a valid alias configuration\n    using description file: /usr/src/app/node_modules/@babel/runtime-corejs2/package.json (relative path: ./core-js/object/create)\n      Field 'browser' doesn't contain a valid alias configuration\n      /usr/src/app/node_modules/@babel/runtime-corejs2/core-js/object/create doesn't exist",
        "stack": "ModuleNotFoundError: Module not found: Error: Can't resolve '../../core-js/object/create' in '/usr/src/app/node_modules/@babel/runtime-corejs2/helpers/esm'\n    at /usr/src/app/node_modules/webpack/lib/Compilation.js:1470:28\n    at /usr/src/app/node_modules/webpack/lib/NormalModuleFactory.js:647:13\n    at eval (eval at create (/usr/src/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:8:1)\n    at /usr/src/app/node_modules/webpack/lib/NormalModuleFactory.js:233:22\n    at eval (eval at create (/usr/src/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:7:1)\n    at /usr/src/app/node_modules/webpack/lib/NormalModuleFactory.js:357:22\n    at /usr/src/app/node_modules/webpack/lib/NormalModuleFactory.js:116:11\n    at /usr/src/app/node_modules/webpack/lib/NormalModuleFactory.js:576:24\n    at finishWithoutResolve (/usr/src/app/node_modules/enhanced-resolve/lib/Resolver.js:284:11)\n    at /usr/src/app/node_modules/enhanced-resolve/lib/Resolver.js:350:15"
    },
    {
        "moduleIdentifier": "/usr/src/app/node_modules/@babel/runtime-corejs2/helpers/esm/objectWithoutPropertiesLoose.js",
        "moduleName": "../node_modules/@babel/runtime-corejs2/helpers/esm/objectWithoutPropertiesLoose.js",
        "loc": "1:0-53",
        "message": "Module not found: Error: Can't resolve '../../core-js/object/keys' in '/usr/src/app/node_modules/@babel/runtime-corejs2/helpers/esm'",
        "moduleId": "../node_modules/@babel/runtime-corejs2/helpers/esm/objectWithoutPropertiesLoose.js",
        "moduleTrace": [
            {
                "originIdentifier": "/usr/src/app/node_modules/react-bootstrap/es/Tooltip.js",
                "originName": "../node_modules/react-bootstrap/es/Tooltip.js",
                "moduleIdentifier": "/usr/src/app/node_modules/@babel/runtime-corejs2/helpers/esm/objectWithoutPropertiesLoose.js",
                "moduleName": "../node_modules/@babel/runtime-corejs2/helpers/esm/objectWithoutPropertiesLoose.js",
                "dependencies": [
                    {
                        "loc": "2:0-108"
                    },
                    {
                        "loc": "69:16-45"
                    }
                ],
                "originId": "../node_modules/react-bootstrap/es/Tooltip.js",
                "moduleId": "../node_modules/@babel/runtime-corejs2/helpers/esm/objectWithoutPropertiesLoose.js"
            },
            {
                "originIdentifier": "/usr/src/app/node_modules/react-bootstrap/es/index.js",
                "originName": "../node_modules/react-bootstrap/es/index.js",
                "moduleIdentifier": "/usr/src/app/node_modules/react-bootstrap/es/Tooltip.js",
                "moduleName": "../node_modules/react-bootstrap/es/Tooltip.js",
                "dependencies": [
                    {
                        "loc": "137:0-33"
                    },
                    {
                        "loc": "138:0-31"
                    }
                ],
                "originId": "../node_modules/react-bootstrap/es/index.js",
                "moduleId": "../node_modules/react-bootstrap/es/Tooltip.js"
            },
            {
                "originIdentifier": "/usr/src/app/node_modules/babel-loader/lib/index.js??ruleSet[1].rules[0].use[0]!/usr/src/app/admin/src/apps/admin/components/CreateUserModal.jsx",
                "originName": "./src/apps/admin/components/CreateUserModal.jsx",
                "moduleIdentifier": "/usr/src/app/node_modules/react-bootstrap/es/index.js",
                "moduleName": "../node_modules/react-bootstrap/es/index.js",
                "dependencies": [
                    {
                        "loc": "10:22-48"
                    }
                ],
                "originId": "./src/apps/admin/components/CreateUserModal.jsx",
                "moduleId": "../node_modules/react-bootstrap/es/index.js"
            },
            {
                "originIdentifier": "/usr/src/app/node_modules/babel-loader/lib/index.js??ruleSet[1].rules[0].use[0]!/usr/src/app/admin/src/apps/admin/components/UsersPage.jsx",
                "originName": "./src/apps/admin/components/UsersPage.jsx",
                "moduleIdentifier": "/usr/src/app/node_modules/babel-loader/lib/index.js??ruleSet[1].rules[0].use[0]!/usr/src/app/admin/src/apps/admin/components/CreateUserModal.jsx",
                "moduleName": "./src/apps/admin/components/CreateUserModal.jsx",
                "dependencies": [
                    {
                        "loc": "14:46-74"
                    }
                ],
                "originId": "./src/apps/admin/components/UsersPage.jsx",
                "moduleId": "./src/apps/admin/components/CreateUserModal.jsx"
            },
            {
                "originIdentifier": "/usr/src/app/node_modules/babel-loader/lib/index.js??ruleSet[1].rules[0].use[0]!/usr/src/app/admin/src/apps/admin/app.jsx",
                "originName": "./src/apps/admin/app.jsx",
                "moduleIdentifier": "/usr/src/app/node_modules/babel-loader/lib/index.js??ruleSet[1].rules[0].use[0]!/usr/src/app/admin/src/apps/admin/components/UsersPage.jsx",
                "moduleName": "./src/apps/admin/components/UsersPage.jsx",
                "dependencies": [
                    {
                        "loc": "27:40-73"
                    }
                ],
                "originId": "./src/apps/admin/app.jsx",
                "moduleId": "./src/apps/admin/components/UsersPage.jsx"
            }
        ],
        "details": "resolve '../../core-js/object/keys' in '/usr/src/app/node_modules/@babel/runtime-corejs2/helpers/esm'\n  using description file: /usr/src/app/node_modules/@babel/runtime-corejs2/helpers/esm/package.json (relative path: .)\n    Field 'browser' doesn't contain a valid alias configuration\n    using description file: /usr/src/app/node_modules/@babel/runtime-corejs2/package.json (relative path: ./core-js/object/keys)\n      Field 'browser' doesn't contain a valid alias configuration\n      /usr/src/app/node_modules/@babel/runtime-corejs2/core-js/object/keys doesn't exist",
        "stack": "ModuleNotFoundError: Module not found: Error: Can't resolve '../../core-js/object/keys' in '/usr/src/app/node_modules/@babel/runtime-corejs2/helpers/esm'\n    at /usr/src/app/node_modules/webpack/lib/Compilation.js:1470:28\n    at /usr/src/app/node_modules/webpack/lib/NormalModuleFactory.js:647:13\n    at eval (eval at create (/usr/src/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:8:1)\n    at /usr/src/app/node_modules/webpack/lib/NormalModuleFactory.js:233:22\n    at eval (eval at create (/usr/src/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:7:1)\n    at /usr/src/app/node_modules/webpack/lib/NormalModuleFactory.js:357:22\n    at /usr/src/app/node_modules/webpack/lib/NormalModuleFactory.js:116:11\n    at /usr/src/app/node_modules/webpack/lib/NormalModuleFactory.js:576:24\n    at finishWithoutResolve (/usr/src/app/node_modules/enhanced-resolve/lib/Resolver.js:284:11)\n    at /usr/src/app/node_modules/enhanced-resolve/lib/Resolver.js:350:15"
    }
]
```

**What is the expected behavior?**
Build should continue to work as it did before

**Other relevant information:**
webpack version:  5.0.0-beta.30
Node.js version: 12.18.3
Operating System: debian 10.5
Additional tools: babel-loader 8.1.0

**Comment by evilebottnawi** [comment]
Please use search https://github.com/webpack/webpack/issues/11467

**Comment by daveisfera** [comment]
Thanks for the quick response! I added the recommended rule and it's now working:
https://github.com/webpack/webpack/issues/11467#issuecomment-691982478

**Comment by evilebottnawi** [comment]
It is bug from babel
