### ISSUE TITLE
5.0.0-rc.0 throws "Maximum call stack size exceeded"

### ISSUE THREAD

**Issue by EvHaus** [webpack/webpack#11518]
# Bug report

**What is the current behavior?**

Running the code in [this repository](https://github.com/EvHaus/webpack-5-rc-issue) using webpack 5.0.0-rc.0 results in the following crash:

```
/Users/evhaus/Git/webpack-5-rc-issue/node_modules/enhanced-resolve/lib/Resolver.js:362
			newStack = new Set(resolveContext.stack);
			           ^

RangeError: Maximum call stack size exceeded
    at Set.add (<anonymous>)
    at new Set (<anonymous>)
    at Resolver.doResolve (/Users/evhaus/Git/webpack-5-rc-issue/node_modules/enhanced-resolve/lib/Resolver.js:362:15)
    at resolver.getHook.tapAsync (/Users/evhaus/Git/webpack-5-rc-issue/node_modules/enhanced-resolve/lib/JoinRequestPlugin.js:38:14)
    at Hook.eval [as callAsync] (eval at create (/Users/evhaus/Git/webpack-5-rc-issue/node_modules/enhanced-resolve/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:7:1)
    at Resolver.doResolve (/Users/evhaus/Git/webpack-5-rc-issue/node_modules/enhanced-resolve/lib/Resolver.js:394:16)
    at resolver.getHook.tapAsync (/Users/evhaus/Git/webpack-5-rc-issue/node_modules/enhanced-resolve/lib/NextPlugin.js:30:14)
    at _next0 (eval at create (/Users/evhaus/Git/webpack-5-rc-issue/node_modules/enhanced-resolve/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:8:1)
    at _fn0 (eval at create (/Users/evhaus/Git/webpack-5-rc-issue/node_modules/enhanced-resolve/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:30:1)
    at resolver.getHook.tapAsync (/Users/evhaus/Git/webpack-5-rc-issue/node_modules/enhanced-resolve/lib/ExportsFieldPlugin.js:66:31)
    ...
```

There's some kind of interplay between `stylus-relative-loader` and `mini-css-extract-plugin` and `webpack@5.0.0-rc.0` that causes this failure.

Downgrading to `5.0.0-beta.29` makes the problem go away.

**If the current behavior is a bug, please provide the steps to reproduce.**

- Checkout this repository https://github.com/EvHaus/webpack-5-rc-issue
- Run `npm install`
- Run `npm run start`

**What is the expected behavior?**

No failure and properly compiled files in the /dist directory.

**Other relevant information:**
webpack version:  5.0.0-rc.0
Node.js version:  14.11.0
Operating System: macOS 10.15.6 Catalina
Additional tools: N/A

**Comment by evilebottnawi** [comment]
/cc @vankop @sokra Interesting bug, if I comment
```
var stylus = require('stylus');
```

inside `stylus-relative-loader`, no problems

**Comment by sokra** [comment]
I think that's already fixed on master

**Comment by evilebottnawi** [comment]
@sokra Tried master, problem still exist
