### ISSUE TITLE
Webpack produces buggy code: "Cannot assign to read only property 'exports' of object '#<Object>'"

### ISSUE THREAD

**Issue by Domiii** [webpack/webpack#11510]
# Bug report

## Problem Description

* I am transpiling [`ws`](https://www.npmjs.com/package/ws) to support Node 7 (yes, I know Node 7 is at the end of life, but there is an important reason; would love not having to do this, but its absolutely necessary for now).
* `ws` contains a file `constants.js` which looks like this:
  ```js 
  'use strict';

  module.exports = {
    BINARY_TYPES: ['nodebuffer', 'arraybuffer', 'fragments'],
    GUID: '258EAFA5-E914-47DA-95CA-C5AB0DC85B11',
    kStatusCode: Symbol('status-code'),
    kWebSocket: Symbol('websocket'),
    EMPTY_BUFFER: Buffer.alloc(0),
    NOOP: () => {}
  };
  ```
* It becomes (and looks good to me):
  ```js
  /***/ "../../node_modules/ws/lib/constants.js":
  /*!**************************************************************!*\
    !*** /my/project/node_modules/ws/lib/constants.js ***!
    \**************************************************************/
  /*! no exports provided */
  /***/ (function(module, __webpack_exports__, __webpack_require__) {

  "use strict";
  __webpack_require__.r(__webpack_exports__);
  /* WEBPACK VAR INJECTION */(function(module) {/* harmony import */ var core_js_modules_es_symbol_description__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! core-js/modules/es.symbol.description */ "core-js/modules/es.symbol.description");
  /* harmony import */ var core_js_modules_es_symbol_description__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(core_js_modules_es_symbol_description__WEBPACK_IMPORTED_MODULE_0__);


  module.exports = {
    BINARY_TYPES: ['nodebuffer', 'arraybuffer', 'fragments'],
    GUID: '258EAFA5-E914-47DA-95CA-C5AB0DC85B11',
    kStatusCode: Symbol('status-code'),
    kWebSocket: Symbol('websocket'),
    EMPTY_BUFFER: Buffer.alloc(0),
    NOOP: () => {} };
  /* WEBPACK VAR INJECTION */}.call(this, __webpack_require__(/*! ./../../webpack/buildin/harmony-module.js */ "../../node_modules/webpack/buildin/harmony-module.js")(module)))

  /***/ }),
* **However**, when running it, I get the following error:
  ```
  module.exports = {
                 ^
  TypeError: Cannot assign to read only property 'exports' of object '#<Object>'
      at Module.<anonymous> (/my/project/dist/ws.js:298:16)
      at Module.../node_modules/ws/lib/constants.js (/my/project/dist/ws.js:305:30)
      at __webpack_require__ (/my/project/dist/ws.js:21:30)
      at Object.../node_modules/ws/lib/buffer-util.js (/my/project/dist/ws.js:157:26)
      at __webpack_require__ (/my/project/dist/ws.js:21:30)
      at Module.<anonymous> (/my/project/dist/ws.js:819:20)
      at Module.../node_modules/ws/lib/permessage-deflate.js (/my/project/dist/ws.js:1327:30)
      at __webpack_require__ (/my/project/dist/ws.js:21:30)
      at Object.../node_modules/ws/lib/websocket.js (/my/project/dist/ws.js:2911:27)
      at __webpack_require__ (/my/project/dist/ws.js:21:30)
  ```



## Steps to reproduce

1. Install `ws` (e.g. `yarn add --dev ws`)
1. Use the following `webpack.config.js`
1. `npx webpack`
1. `node ./dist/ws.js`
1. -> Error!


```js
// webpack.config.js
const path = require('path');
const nodeExternals = require('webpack-node-externals');

const ProjectRoot = __dirname;
const DependencyRoot = ProjectRoot;
const buildMode = 'development';

const babelOptions = {
  sourceMaps: true,
  retainLines: true,
  presets: [
    [
      '@babel/preset-env',
      {
        targets: {
          node: '7'
        },
        useBuiltIns: 'usage',
        corejs: 3
      }
    ]
  ]
};

const wsPath = path.resolve(DependencyRoot, 'node_modules', 'ws');

// ###########################################################################
// entry
// ###########################################################################

const entry = {
  // [fix ws]
  ws: path.join(wsPath, 'index.js')
};

// ###########################################################################
// resolve.modules
// ###########################################################################

const modules = [
  path.join(DependencyRoot, 'node_modules'),
  path.join(wsPath, 'lib'),
  path.join(wsPath, 'node_modules')
];

// ###########################################################################
// externals
// ###########################################################################

const externals = [
  nodeExternals({
    additionalModuleDirs: [
      path.join(DependencyRoot, 'node_modules'),
      path.join(ProjectRoot, 'node_modules')
    ],
    allowlist: ['ws']
  })
];


// ###########################################################################
// final result
// ###########################################################################

module.exports = {
  mode: buildMode,
  entry,
  target: 'node',
  devtool: 'source-map',
  context: ProjectRoot,
  output: {
    filename: '[name].js',
    path: path.resolve(ProjectRoot, 'dist'),
    publicPath: 'dist',
    libraryTarget: "commonjs2",
    devtoolModuleFilenameTemplate: "../[resource-path]",
  },
  resolve: {
    modules
  },
  module: {
    rules: [
      {
        test: /\.jsx?$/,
        loader: 'babel-loader',
        include: [
          path.join(wsPath, 'lib')
        ],
        options: babelOptions,
        enforce: 'pre'
      }
    ]
  },
  node: {
    __dirname: true,
    __filename: true
  },
  externals
};
```

## What is the expected behavior?

When running `node dist/ws.js`, it should just run and exit immediately, without any errors.

## Other relevant information

webpack version:  4.44.1
Node.js version: I use `v12.18.1` to build it (and it doesn't matter which version I run it with, it always bugs out)
Operating System: Mac OS 10.14.6
Additional tools: `Babel` 7, `babel-loader` 8.1.0

**Comment by Domiii** [comment]
Turns out to be [this babel problem](https://github.com/babel/babel/issues/10792#issuecomment-561119049). 

Fix: add `sourceType: "unambiguous"` to babel config.

**Comment by quannt-paypay** [comment]
Thank you so much, after days of searching the web and pulling my hairs out, this finally fixes it for me.
