### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: "." is not in the SourceMap

### ISSUE THREAD

**Issue by rob-baker-ar** [webpack/webpack#11517]
# Bug report

**What is the current behavior?**

Running `webpack --config webpack.config.js` results in the above error and following stack trace:

```
(node:31428) UnhandledPromiseRejectionWarning: Error: "." is not in the SourceMap.
    at BasicSourceMapConsumer.SourceMapConsumer_sourceContentFor [as sourceContentFor] (C:\...\webpack-issue\node_modules\source-map\lib\source-map-consumer.js:753:13)
    at C:\...\webpack-issue\node_modules\webpack\node_modules\webpack-sources\lib\applySourceMap.js:144:46
    at SourceNode_walk [as walk] (C:\...\webpack-issue\node_modules\source-map\lib\source-node.js:230:9)
    at SourceNode_walk [as walk] (C:\...\webpack-issue\node_modules\source-map\lib\source-node.js:226:13)
    at applySourceMap (C:\...\webpack-issue\node_modules\webpack\node_modules\webpack-sources\lib\applySourceMap.js:58:13)
    at SourceMapSource.node (C:\...\webpack-issue\node_modules\webpack\node_modules\webpack-sources\lib\SourceMapSource.js:198:11)
    at exports.getSourceAndMap (C:\...\webpack-issue\node_modules\webpack\node_modules\webpack-sources\lib\helpers.js:17:21)
    at SourceMapSource.sourceAndMap (C:\...\webpack-issue\node_modules\webpack\node_modules\webpack-sources\lib\SourceMapSource.js:184:10)
    at getTaskForFile (C:\...\webpack-issue\node_modules\webpack\lib\SourceMapDevToolPlugin.js:77:30)
    at C:\...\webpack-issue\node_modules\webpack\lib\SourceMapDevToolPlugin.js:264:22
    at C:\...\webpack-issue\node_modules\webpack\lib\Cache.js:93:5
    at Hook.eval [as callAsync] (eval at create (C:\...\webpack-issue\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:4:1)
    at Cache.get (C:\...\webpack-issue\node_modules\webpack\lib\Cache.js:75:18)
    at ItemCacheFacade.get (C:\...\webpack-issue\node_modules\webpack\lib\CacheFacade.js:116:15)
    at C:\...\webpack-issue\node_modules\webpack\lib\SourceMapDevToolPlugin.js:215:18
    at arrayEach (C:\...\webpack-issue\node_modules\neo-async\async.js:2405:9)
    at Object.each (C:\...\webpack-issue\node_modules\neo-async\async.js:2846:9)
    at C:\...\webpack-issue\node_modules\webpack\lib\SourceMapDevToolPlugin.js:202:15
    at _next0 (eval at create (C:\...\webpack-issue\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:20:1)
    at eval (eval at create (C:\...\webpack-issue\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:35:1)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

... and no files are produced as output.

This seems to be happening only when producing a source map with `devtool: "sourcemap"`. If you swap that for `devtool: false` the build succeeds.

**If the current behavior is a bug, please provide the steps to reproduce.**

Running `npm run js` in repository root to trigger `webpack --config webpack.config.js` results in the error: `(node:31428) UnhandledPromiseRejectionWarning: Error: "." is not in the SourceMap.`

Issue reproducible with configuration in this repo: https://github.com/rob-baker-ar/webpack-issue

**What is the expected behavior?**

The build succeeds and produces a source map.

Babel is in use - the issue does not occur if it is removed from the process, however I believe there is a bug of some sort in the source map generation because if you disable the source map (`devtool: false`) the build succeeds with the exact same Babel configuration.

**Other relevant information:**

webpack version:  5.0.0-rc.0
Node.js version: v12.18.4 
npm version: 6.14.6
Operating System: Windows 10

Using Babel in latest stable versions, this is the snippet from `package.json` indicating versions:

```
"@babel/core": "^7.11.6",
"@babel/preset-env": "^7.11.5",
"@babel/runtime": "^7.11.2",
```

**Comment by rob-baker-ar** [comment]
Looks like this:

https://github.com/webpack/webpack-sources/issues/89

Maybe close this If I'm right.

**Comment by evilebottnawi** [comment]
Close in favor https://github.com/webpack/webpack-sources/issues/89
