### ISSUE TITLE
Error: Cyclic dependency with Block Connections

### ISSUE THREAD

**Issue by javier-garcia-meteologica** [webpack/webpack#11589]
# Bug report

**What is the current behavior?**

Latest webpack v4.44.2 cannot build our large typescript project.

```
Error: Cyclic dependency
  at visit (<project_path>/node_modules/toposort/index.js:36:13)
```

**If the current behavior is a bug, please provide the steps to reproduce.**

The error doesn't happen with v4.44.1 or lower versions. I've traced it down to the commit https://github.com/webpack/webpack/commit/235b87bf9c1460506deff35b4d21e79c92172a5d

**What is the expected behavior?**

Chunk dependencies are resolved like in v4.44.1, without cyclic chunk groups dependencies.

**Other relevant information:**
webpack version:  4.44.2
Node.js version: 10.22.1
Operating System: Fedora 32
Additional tools:

**Comment by evilebottnawi** [comment]
Because you have Cyclic dependency, please create reproducible test repo

**Comment by sokra** [comment]
Webpack itself doesn't use toposort. This seem to be caused by an plugin?

**Comment by javier-garcia-meteologica** [comment]
`toposort` is used by the plugin `html-webpack-plugin`

```
(node:399665) UnhandledPromiseRejectionWarning: Error: Cyclic dependency
    at visit (<project_path>/node_modules/toposort/index.js:35:13)
    at visit (<project_path>/node_modules/toposort/index.js:53:9)
    at visit (<project_path>/node_modules/toposort/index.js:53:9)
    at visit (<project_path>/node_modules/toposort/index.js:53:9)
    at visit (<project_path>/node_modules/toposort/index.js:53:9)
    at visit (<project_path>/node_modules/toposort/index.js:53:9)
    at Function.toposort [as array] (<project_path>/node_modules/toposort/index.js:22:22)
    at Object.module.exports.dependency (<project_path>/node_modules/html-webpack-plugin/lib/chunksorter.js:50:35)
    at HtmlWebpackPlugin.sortChunks (<project_path>/node_modules/html-webpack-plugin/index.js:364:35)
    at <project_path>/node_modules/html-webpack-plugin/index.js:113:21
    at AsyncSeriesHook.eval [as callAsync] (eval at create (<project_path>/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:2
4:1)
    at AsyncSeriesHook.lazyCompileHook (<project_path>/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.emitAssets (<project_path>/node_modules/webpack/lib/Compiler.js:491:19)
    at onCompiled (<project_path>/node_modules/webpack/lib/Watching.js:51:19)
    at hooks.afterCompile.callAsync.err (<project_path>/node_modules/webpack/lib/Compiler.js:681:15)
    at _next0 (eval at create (<project_path>/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
```

If I use webpack v4.44.1 with the same versions of html-webpack-plugin and toposort, the error doesn't happen. When I debugged the errors, the plugin wantend to sort ChunkGroups, which were objects of roughly this shape:

```
interface ChunkGroup {
  groupDebugId: number
  _children: Set()
  _parents: Set()
  chunks: [{
    _modules: Map()
  }]
}
```

I traced their origin to webpack, and as far as I know `html-webpack-plugin` and `toposort` didn't modify them.

I will try to make a reproductible test repo, but this is a large project and will take quite some time.

**Comment by javier-garcia-meteologica** [comment]
Oh, I found out that our project was using `html-webpack-plugin` v3.2.0 which is kind of obsolete. With `html-webpack-plugin` v4.5.0, which doesn't use toposort, the error doesn't occur.

I've test our project with webpack v4.44.2 and `html-webpack-plugin` v4.5.0. Everything seemed to work fine, without build or runtime cyclic dependencies.

**Comment by sokra** [comment]
Great. Toposorting chunk groups isn't possible in general. It's always possible to have cycles in the graph.

**Comment by javier-garcia-meteologica** [comment]
Thank you and sorry for bothering you needlessly.
