### ISSUE TITLE
[Webpack 5] Default export for JSON modules for arrays

### ISSUE THREAD

**Issue by MichielDeMey** [webpack/webpack#11580]
# Bug report

Assuming you have a JSON file `prices.json` with the following content:
```json
[
    {
      "key": "startup",
      "title": "Startup",
      "price": 75
    },
    {
      "key": "basic",
      "title": "Basic",
      "price": 150,
      "featured": true
    },
    {
      "key": "partnership",
      "title": "Partnership",
      "price": null
    }
  ]
```
Note that the root object is simply an array.

And you import it using the default export as required by Webpack 5:

```ts
import pricing from "./pricing.json";
```

**What is the current behavior?**

Gives an error when Next.js tries to compile:

```
TypeError: undefined is not a function
```

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

I believe it should be possible to map the prices.
```ts
prices.map((price) => console.log)
```

Changing the `prices.json` to be an object with a key works:

```json
{
  "prices": [
    {
      "key": "startup",
      "title": "Startup",
      "price": 75
    },
    {
      "key": "basic",
      "title": "Basic",
      "price": 150,
      "featured": true
    },
    {
      "key": "partnership",
      "title": "Partnership",
      "price": null
    }
  ]
}

```

Works now using the additional key
```ts
prices.prices.map((price) => console.log)
```

**Other relevant information:**
webpack version:  `webpack@5.0.0-rc.3`
Node.js version: `v12.18.3`
Operating System: MacOS 10.15.7
Additional tools:

**Comment by evilebottnawi** [comment]
Please open an issue in `Next.js` repo,

**Comment by evilebottnawi** [comment]
Also `json` doesn't have `default` export

**Comment by sokra** [comment]
This looks like a bug. Do you have a stack trace for this error?

Is it reproducible without next.js?

**Comment by MichielDeMey** [comment]
The error suddenly manifested when I upgraded Webpack from `5.0.0-beta.28` to `5.0.0-rc.3` so I assumed it was a Webpack issue. 🙂 

Full stack trace:
```
Error occurred prerendering page "/". Read more: https://err.sh/next.js/prerender-error
TypeError: undefined is not a function
    at PricingTable (/Users/michiel/Documents/monitr/repos/monitr.be/.next/server/pages/index.js:2983:32)
    at d (/Users/michiel/Documents/monitr/repos/monitr.be/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:498)
    at $a (/Users/michiel/Documents/monitr/repos/monitr.be/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:39:16)
    at a.b.render (/Users/michiel/Documents/monitr/repos/monitr.be/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:476)
    at a.b.read (/Users/michiel/Documents/monitr/repos/monitr.be/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:18)
    at renderToString (/Users/michiel/Documents/monitr/repos/monitr.be/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:54:364)
    at renderPage (/Users/michiel/Documents/monitr/repos/monitr.be/node_modules/next/dist/next-server/server/render.js:50:851)
    at Object.ctx.renderPage (/Users/michiel/Documents/monitr/repos/monitr.be/.next/server/pages/_document.js:675:28)
    at Function.getInitialProps (/Users/michiel/Documents/monitr/repos/monitr.be/.next/server/pages/_document.js:153:19)
    at Function.getInitialProps (/Users/michiel/Documents/monitr/repos/monitr.be/.next/server/pages/_document.js:679:83)
```

I haven't been able to create a repro without Next.js though.

**Comment by evilebottnawi** [comment]
@MichielDeMey If you create reproducible test repo with next I can point to bug line

**Comment by MichielDeMey** [comment]
I've create a minimal repo here: https://github.com/MichielDeMey/nextjs-webpack5

Uses Next.js `9.5.4-canary.23`, which has been updated to fix a change in the configuration schema introduced in Webpack `^5.0.0-beta.28`. Webpack version used is `^5.0.0-rc.3`.

**Comment by vankop** [comment]
@MichielDeMey thanks for repro, we will work on fix.
fast fix for you will be to change webpack config option manually via https://nextjs.org/docs/api-reference/next.config.js/custom-webpack-config
```
config.optimization.concatenateModules = false;
```
https://webpack.js.org/configuration/optimization/#optimizationconcatenatemodules

**Comment by wojtekmaj** [comment]
As noted in https://github.com/webpack/webpack/issues/11588, it doesn't seem to be Next.js specific (I'm using pure Webpack). 

The version in which mapping over arrays imported from JSONs seem to have been broken is 5.0.0-beta.31.

**Comment by evilebottnawi** [comment]
@wojtekmaj It is not Next.js specific, it is bug in webpack and we are working on fix
