### ISSUE TITLE
electron/index.js bundled since webpack@5.0.0-beta.30

### ISSUE THREAD

**Issue by MayaWolf** [webpack/webpack#11599]
# Bug report

**What is the current behavior?**
Since version 5.0.0-beta.30, webpack bundles the `electron/index.js` file when using `require('electron')` with target `electron-main`. This causes it to fail, as that file uses `__dirname` to refer to other files in its directory.

**If the current behavior is a bug, please provide the steps to reproduce.**
webpack.config.js
```js
module.exports = {
    entry: './main.js',
    output: {path: __dirname + '/app', filename: 'main.js'},
    target: 'electron-main',
};
```
main.js
```js
const {app} = require('electron');
```

**What is the expected behavior?**
`electron` is properly `require`-d as an external dependency, not bundled. This worked up until and including 5.0.0-beta.29.

**Other relevant information:**
webpack version:  5.0.0-rc.4
Node.js version: 12.14.0
Operating System: Windows 10
Additional tools: Electron

**Comment by evilebottnawi** [comment]
Why do you want to bundle `electron`?

**Comment by MayaWolf** [comment]
I don't. I'm saying the new version _does_ (at least the index.js file), and that's causing problems.

**Comment by MayaWolf** [comment]
```js
module.exports = {
    entry: './main.js',
    output: {path: __dirname + '/app', filename: 'main.js'},
    target: 'electron-main',
    externalsType: 'commonjs',
    externals: ['electron']
};
```
Do you mean this? That does appear to work, but it's very much a breaking change.

If `target: 'electron-main'` _intentionally_ no longer does this, what's the difference/advantage compared to using `target: 'node'`?

**Comment by MayaWolf** [comment]
For reference, I have also tried
```js
module.exports = {
    entry: './main.js',
    output: {path: __dirname + '/app', filename: 'main.js'},
    target: 'electron-main',
    externalsPresets: {electron: true, electronMain: true, node: true}
};
```
which doesn't work either (electron/index.js is still bundled). Unless I'm missing anything, I suspect there is a bug in how `externalsPresets` are processed.

**Comment by evilebottnawi** [comment]
Weird. Can you create reproducible test repo?

**Comment by MayaWolf** [comment]
https://github.com/MayaWolf/webpack-issue-11599 Sure thing, here you go.

**Comment by evilebottnawi** [comment]
hm, no problems with your repo, no `elector` in bundle, same for `target: 'electron-main',`, maybe you have globally installed webpack?

**Comment by MayaWolf** [comment]
I do not have webpack globally installed, and I just tried to clone and run from scratch again. This is what's happening for me.

```
PS D:\workspaces> git clone https://github.com/MayaWolf/webpack-issue-11599.git
Cloning into 'webpack-issue-11599'...
remote: Enumerating objects: 8, done.
remote: Counting objects: 100% (8/8), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 8 (delta 0), reused 8 (delta 0), pack-reused 0
Unpacking objects: 100% (8/8), done.
PS D:\workspaces> cd .\webpack-issue-11599\
PS D:\workspaces\webpack-issue-11599> yarn install
yarn install v1.12.3
warning package.json: No license field
warning No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "webpack > terser-webpack-plugin@4.2.3" has incorrect peer dependency "webpack@^4.0.0 || ^5.0.0".
warning " > webpack-cli@4.0.0-rc.1" has incorrect peer dependency "webpack@4.x.x || 5.x.x".
warning "webpack-cli > @webpack-cli/info@1.0.1-rc.1" has incorrect peer dependency "webpack-cli@4.x.x".
warning "webpack-cli > @webpack-cli/init@1.0.1-rc.1" has incorrect peer dependency "webpack@4.x.x || 5.x.x".
warning "webpack-cli > @webpack-cli/init@1.0.1-rc.1" has incorrect peer dependency "webpack-cli@4.x.x".
warning "webpack-cli > @webpack-cli/serve@1.0.1-rc.1" has incorrect peer dependency "webpack-cli@4.x.x".
warning "webpack-cli > @webpack-cli/init > @webpack-cli/generators@1.0.1-rc.1" has incorrect peer dependency "webpack@4.x.x || 5.x.x".
warning "webpack-cli > @webpack-cli/init > @webpack-cli/generators@1.0.1-rc.1" has incorrect peer dependency "webpack-cli@3.x.x || 4.x.x".
warning "webpack-cli > @webpack-cli/init > @webpack-cli/utils@1.0.1-rc.1" has incorrect peer dependency "webpack@4.x.x || 5.x.x".
warning "webpack-cli > @webpack-cli/init > @webpack-cli/utils@1.0.1-rc.1" has incorrect peer dependency "webpack-cli@4.x.x".
[4/4] Building fresh packages...
Done in 6.11s.
PS D:\workspaces\webpack-issue-11599> yarn build                                                                                                             yarn run v1.12.3
warning package.json: No license field
$ webpack --mode development
asset main.js 2.95 KiB [emitted] (name: main)
cacheable modules 625 bytes
  ./main.js 34 bytes [built] [code generated]
  ./node_modules/electron/index.js 591 bytes [built] [code generated]
external "fs" 42 bytes [built] [code generated]
external "path" 42 bytes [built] [code generated]
webpack 5.0.0-rc.4 compiled successfully in 95 ms

Done in 0.77s.
PS D:\workspaces\webpack-issue-11599> yarn start
yarn run v1.12.3
warning package.json: No license field
$ electron app

App threw an error during load
Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
    at getElectronPath (D:\workspaces\webpack-issue-11599\app\main.js:26:11)
    at Object../node_modules/electron/index.js (D:\workspaces\webpack-issue-11599\app\main.js:30:18)
    at __webpack_require__ (D:\workspaces\webpack-issue-11599\app\main.js:82:41)
    at D:\workspaces\webpack-issue-11599\app\main.js:95:15
    at D:\workspaces\webpack-issue-11599\app\main.js:96:3
    at Object.<anonymous> (D:\workspaces\webpack-issue-11599\app\main.js:98:12)
    at Module._compile (internal/modules/cjs/loader.js:1145:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1166:10)
    at Module.load (internal/modules/cjs/loader.js:981:32)
    at Module._load (internal/modules/cjs/loader.js:881:14)
```

This is the bundle it generates.
```js
/******/ (() => { // webpackBootstrap
/******/ 	var __webpack_modules__ = ({

/***/ "./node_modules/electron/index.js":
/*!****************************************!*\
  !*** ./node_modules/electron/index.js ***!
  \****************************************/
/*! unknown exports (runtime-defined) */
/*! runtime requirements: module, __webpack_require__ */
/*! CommonJS bailout: module.exports is used directly at 18:0-14 */
/***/ ((module, __unused_webpack_exports, __webpack_require__) => {

var fs = __webpack_require__(/*! fs */ "fs")
var path = __webpack_require__(/*! path */ "path")

var pathFile = path.join(__dirname, 'path.txt')

function getElectronPath () {
  if (fs.existsSync(pathFile)) {
    var executablePath = fs.readFileSync(pathFile, 'utf-8')
    if (process.env.ELECTRON_OVERRIDE_DIST_PATH) {
      return path.join(process.env.ELECTRON_OVERRIDE_DIST_PATH, executablePath)
    }
    return path.join(__dirname, 'dist', executablePath)
  } else {
    throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again')
  }
}

module.exports = getElectronPath()


/***/ }),

/***/ "fs":
/*!*********************!*\
  !*** external "fs" ***!
  \*********************/
/*! dynamic exports */
/*! exports [maybe provided (runtime-defined)] [no usage info] */
/*! runtime requirements: module */
/***/ ((module) => {

"use strict";
module.exports = require("fs");;

/***/ }),

/***/ "path":
/*!***********************!*\
  !*** external "path" ***!
  \***********************/
/*! dynamic exports */
/*! exports [maybe provided (runtime-defined)] [no usage info] */
/*! runtime requirements: module */
/***/ ((module) => {

"use strict";
module.exports = require("path");;

/***/ })

/******/ 	});
/************************************************************************/
/******/ 	// The module cache
/******/ 	var __webpack_module_cache__ = {};
/******/ 	
/******/ 	// The require function
/******/ 	function __webpack_require__(moduleId) {
/******/ 		// Check if module is in cache
/******/ 		if(__webpack_module_cache__[moduleId]) {
/******/ 			return __webpack_module_cache__[moduleId].exports;
/******/ 		}
/******/ 		// Create a new module (and put it into the cache)
/******/ 		var module = __webpack_module_cache__[moduleId] = {
/******/ 			// no module.id needed
/******/ 			// no module.loaded needed
/******/ 			exports: {}
/******/ 		};
/******/ 	
/******/ 		// Execute the module function
/******/ 		__webpack_modules__[moduleId](module, module.exports, __webpack_require__);
/******/ 	
/******/ 		// Return the exports of the module
/******/ 		return module.exports;
/******/ 	}
/******/ 	
/************************************************************************/
(() => {
/*!*****************!*\
  !*** ./main.js ***!
  \*****************/
/*! unknown exports (runtime-defined) */
/*! runtime requirements: __webpack_require__ */
const {app} = __webpack_require__(/*! electron */ "./node_modules/electron/index.js");
})();

/******/ })()
;
```
As you can see it includes electron/index.js, which then fails because it relies on __dirname.

**Comment by sokra** [comment]
Yep it's a bug.

In this line: https://github.com/webpack/webpack/blob/d10b08b4b5151a02a193b41c63f58589445ae239/lib/electron/ElectronTargetPlugin.js#L34

There is a `.apply(compiler)` missing.

Do you want to send a PR?
