### ISSUE TITLE
[5.0.0] Possible (AssignLibraryPlugin.js) problem after upgrade to webpack 5.0.0

### ISSUE THREAD

**Issue by doberkofler** [webpack/webpack#11632]
# Bug report

**What is the current behavior?**

After upgrading to webpack 5, I get the following error when building:

```
~/MyDev/ljs_app/trunk/desktop/ttr/web $ node --trace-deprecation node_modules/webpack/bin/webpack.js
(node:9875) [DEP_WEBPACK_MODULE_ERRORS] DeprecationWarning: Module.errors was removed (use getErrors instead)
    at Object.reportTranspileErrors (/Users/doberkofler/MyDev/ljs_app/trunk/desktop/ttr/web/node_modules/ts-loader/dist/instances.js:263:24)
    at successLoader (/Users/doberkofler/MyDev/ljs_app/trunk/desktop/ttr/web/node_modules/ts-loader/dist/index.js:28:17)
    at Object.loader (/Users/doberkofler/MyDev/ljs_app/trunk/desktop/ttr/web/node_modules/ts-loader/dist/index.js:24:5)
    at LOADER_EXECUTION (/Users/doberkofler/MyDev/ljs_app/trunk/desktop/ttr/web/node_modules/loader-runner/lib/LoaderRunner.js:132:14)
    at runSyncOrAsync (/Users/doberkofler/MyDev/ljs_app/trunk/desktop/ttr/web/node_modules/loader-runner/lib/LoaderRunner.js:133:4)
    at iterateNormalLoaders (/Users/doberkofler/MyDev/ljs_app/trunk/desktop/ttr/web/node_modules/loader-runner/lib/LoaderRunner.js:251:2)
    at iterateNormalLoaders (/Users/doberkofler/MyDev/ljs_app/trunk/desktop/ttr/web/node_modules/loader-runner/lib/LoaderRunner.js:240:10)
    at /Users/doberkofler/MyDev/ljs_app/trunk/desktop/ttr/web/node_modules/loader-runner/lib/LoaderRunner.js:255:3
    at Object.context.callback (/Users/doberkofler/MyDev/ljs_app/trunk/desktop/ttr/web/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at Object.module.exports (/Users/doberkofler/MyDev/ljs_app/trunk/desktop/ttr/web/node_modules/ifdef-loader/ifdef-loader.js:34:14)
[webpack-cli] Error: Library name must be a string or string array
    at AssignLibraryPlugin.parseOptions (/Users/doberkofler/MyDev/ljs_app/trunk/desktop/ttr/web/node_modules/webpack/lib/library/AssignLibraryPlugin.js:110:11)
    at AssignLibraryPlugin._parseOptionsCached (/Users/doberkofler/MyDev/ljs_app/trunk/desktop/ttr/web/node_modules/webpack/lib/library/AbstractLibraryPlugin.js:120:23)
    at /Users/doberkofler/MyDev/ljs_app/trunk/desktop/ttr/web/node_modules/webpack/lib/library/AbstractLibraryPlugin.js:60:27
    at Hook.eval [as callAsync] (eval at create (/Users/doberkofler/MyDev/ljs_app/trunk/desktop/ttr/web/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:41:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/doberkofler/MyDev/ljs_app/trunk/desktop/ttr/web/node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
    at Compilation.finish (/Users/doberkofler/MyDev/ljs_app/trunk/desktop/ttr/web/node_modules/webpack/lib/Compilation.js:1695:28)
    at /Users/doberkofler/MyDev/ljs_app/trunk/desktop/ttr/web/node_modules/webpack/lib/Compiler.js:973:19
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
```
**If the current behavior is a bug, please provide the steps to reproduce.**

**webpack.config.js:**
```js
const path = require('path');
const fse = require('fs-extra');
const webpack = require('webpack');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');
const CopyWebpackPlugin = require('copy-webpack-plugin');
const ImageminPlugin = require('imagemin-webpack-plugin').default;

const IMAGE_COMPRESS_OPTIONS = {
	mozjpeg: {
		progressive: true,
	},
	gifsicle: {
		interlaced: false,
	},
	optipng: {
		optimizationLevel: 4,
	},
	pngquant: {
		quality: [0.75, 0.90],
		speed: 3,
	}
};

module.exports = function (env, options) {
	const dist = path.resolve('dist');
	fse.emptyDirSync(dist);

	return {
		entry: {
			index: './src/index.tsx',
			index_be: './src/be/index.ts',
		},
		output: {
			path: dist,
			filename: '[name].js',
			chunkFilename: '[id].js',
			libraryTarget: 'var'
		},
		resolve: {
			extensions: ['.ts', '.tsx', '.js', '.jsx'],
		},
		module: {
			rules: [
				{
					test: /.tsx?$/i,
					exclude: [/node_modules/],
					use: [{
						loader: 'ts-loader',
						options: {
							transpileOnly: true
						}
					},
					{
						loader: 'ifdef-loader',
						options: {
							'ifdef-verbose': false,
							'DEBUG': false
						}
					}]
				},
				{
					// Load css resources in "regular" source modules:
					test: /\.css$/i,
					include: [/src/],
					use: [
						MiniCssExtractPlugin.loader,
						{
							loader: 'css-loader',
							options: {
								sourceMap: false,
								importLoaders: 1
							}
						}
					]
				},
				{
					// Load and compress images
					test: /\.(png|gif|jpe?g|svg|ico)$/i,
					include: [/img/, /src/, /vendor/, /node_modules/],
					use: [
						{
							loader: 'file-loader',
							options: {
								name: '[name].[ext]'
							}
						},
						{
							loader: 'image-webpack-loader',
							options: IMAGE_COMPRESS_OPTIONS
						}
					]
				},
			]
		},
		plugins: [
			// compress all copied images
			new ImageminPlugin({
				IMAGE_COMPRESS_OPTIONS
			}),

			// Extract text plugin
			new MiniCssExtractPlugin({
				// Options similar to the same options in webpackOptions.output both options are optional
				filename: '[name].css',
				chunkFilename: '[name].css'
			}),

			// add plugin to copy resources
			new CopyWebpackPlugin({
				// @ts-ignore
				patterns: [
					{context: './public', from: '*.*'},
				]
			}),

		],
		devtool: (options && typeof options.mode === 'string' && options.mode.toLowerCase() === 'production') ? 'source-map' : 'eval-source-map',
	};
};
```

**What is the expected behavior?**

This is my first attempt to upgrade from webpack 4 towebpack 5 by following the migration guide.
I did not have to make any changes to my `webpack.config.js` but received the above error message when trying to compile my project. I'm pretty sure, I'm doing something wrong or missed something in the migration guide and it would be most appreciated to get a hint on what might cause this kind of error or how to track it down?

**Other relevant information:**
webpack version:  5.0.0
Node.js version:  14.13.0
Operating System:  macOS 10.15.7
Additional tools:

**Comment by doberkofler** [comment]
I've just discovered that this problem seems to be related to the unused `libraryTarget: 'var'`configuration option.
In webpack 4 this option didi not cause any problem but in version 5 it seems to cause the described error but is not reported as a configuration error.

**Comment by evilebottnawi** [comment]
Yes, we should improve this, thanks for the issue

**Comment by sokra** [comment]
Send a PR to improve the error message.

It should be either:

``` js
output: {
  library: {
    type: "var",
    name: "someGlobal"
  }
}
```

or (the old syntax)

``` js
output: {
  libraryTarget: "var",
  library: "someGlobal"
}
```

**Comment by huchangfa123** [comment]
So when can you fix this problem 👀
