### ISSUE TITLE
WP5: Unexpected lazy element in stream

### ISSUE THREAD

**Issue by ScriptedAlchemy** [webpack/webpack#11661]
# Bug report

**What is the current behavior?**
When requiring specific libraries. I'll get a serialization error. 
For example, requiring this middleware inside a custom express dev server will throw the error
`const xrayExpress = require("aws-xray-sdk-express");`

This bug was not seen in previous RC releases (last known to work on beta28) 

**If the current behavior is a bug, please provide the steps to reproduce.**

I can create a reproducible repo, but i believe simply requiring x-ray SDK will cause a failure. 

This only occurs in development mode and looks related to the new caching structure. 

```
Error: Unexpected lazy element in stream
    at readU8 (/Users/zjackson/wae-coco/node_modules/webpack/lib/serialization/BinaryMiddleware.js:414:11)
    at BinaryMiddleware._deserialize (/Users/zjackson/wae-coco/node_modules/webpack/lib/serialization/BinaryMiddleware.js:450:19)
    at BinaryMiddleware.deserialize (/Users/zjackson/wae-coco/node_modules/webpack/lib/serialization/BinaryMiddleware.js:361:15)
    at Serializer.deserialize (/Users/zjackson/wae-coco/node_modules/webpack/lib/serialization/Serializer.js:41:26)
    at PackFileCacheStrategy._openPack (/Users/zjackson/wae-coco/node_modules/webpack/lib/cache/PackFileCacheStrategy.js:779:5)
    at new PackFileCacheStrategy (/Users/zjackson/wae-coco/node_modules/webpack/lib/cache/PackFileCacheStrategy.js:759:27)
    at WebpackOptionsApply.process (/Users/zjackson/wae-coco/node_modules/webpack/lib/WebpackOptionsApply.js:496:9)
    at createCompiler (/Users/zjackson/wae-coco/node_modules/webpack/lib/webpack.js:78:28)
    at /Users/zjackson/wae-coco/node_modules/webpack/lib/webpack.js:41:48
    at Array.map (<anonymous>)
✨  Done in 3.91s.

```

**What is the expected behavior?**
the build should execute without error

**Other relevant information:**
webpack version:  5
Node.js version: v12.13.1
Operating System: MacOs
Additional tools: uses next.js

**Comment by vankop** [comment]
worked for me with
```
module.exports = {
	mode: "development",
	target: "node",
	devtool: false,
	cache: {
		type: "filesystem"
	},
};
```

please provide a repro

**Comment by ScriptedAlchemy** [comment]
Hmm interesting. I also found that if I require it at the top level, I would get this error. If I require it elsewhere like inline or inside a conditional, it works. Strangest thing. I'll try and extract a repo.

**Comment by ScriptedAlchemy** [comment]
I'll work on it this weekend

**Comment by evilebottnawi** [comment]
@ScriptedAlchemy Friendly ping, we try to close all critical issues ASAP, but without reproducible example we can't do it

**Comment by alexander-akait** [comment]
Let's close due inactivity, I think it was bug on Next.js side, anyway if somebody faced with the bug, feel free to feedback or open an issue with with minimum reproducible test repo, based on stacktrace it was from a plugin

**Comment by danoc** [comment]
I've run into this same issue and created a small repro: https://github.com/vercel/next.js/issues/27792

I also think this is a bug in Next.js, not Webpack 5. Hopefully they'll be able to provide some insight in that issue.
