### ISSUE TITLE
From 1.9.10 to 1.9.11: ERROR in Entry module not found: Error: Cannot resolve 'file' or 'directory'

### ISSUE THREAD

**Issue by huangp** [webpack/webpack#1168]
I am getting this error when upgraded webpack from 1.9.10 to 1.9.11.
My webpack config is:
```
var webpack = require('webpack');
var path = require('path');

// default destination
var bundleDest = __dirname;
process.argv.forEach(function(arg) {
  if (/^bundleDest=.+$/.test(arg)) {
    bundleDest = arg.split('=')[1];
  }
});

module.exports = {
  context: __dirname,
  entry: [
    './index.js'
  ],
  output: {
    path: bundleDest,
    filename: path.basename(__dirname) + '.bundle.min.js',
    pathinfo: true
  },
  module: {
    loaders: [
      {
        test: /\.jsx?$/,
        exclude: /node_modules/,
        loader: 'babel-loader'
      }
    ]
  },
  plugins: [
    new webpack.DefinePlugin({ "global.GENTLY": false }),
    new webpack.IgnorePlugin(/^\.\/locale$/, /moment$/),
    new webpack.optimize.UglifyJsPlugin(
    ),
    new webpack.optimize.DedupePlugin(),
    new webpack.DefinePlugin({
      "process.env": {
        NODE_ENV: JSON.stringify("production")
      }
    }),
    new webpack.NoErrorsPlugin()
  ],
  resolve: {
    extensions: ['', '.js', '.jsx', '.json']
  },
  node: {
    __dirname: true
  }
};
```

and I invoke it with:
```
npm run NODE_ENV=production webpack -p --config webpack.prod.config.js --display-error-details --bail bundleDest=/home/pahuang/work/root/server/frontend/target/build/META-INF/resources
```

My ```__dirname``` or CWD is ```/home/pahuang/work/root/server/frontend/target/web/user-profile-page```.
The ```bundleDest``` passed in as node argument should be resolved as absolute path and in success build, the final output will be put under that path. Now with version 1.9.11:
```
EntryModuleNotFoundError: Entry module not found: Error: Cannot resolve 'file' or 'directory' /home/pahuang/work/root/server/frontend/target/build/META-INF/resources in /home/pahuang/work/root/server/frontend/target/web/user-profile-page
    at Tapable.<anonymous> (/home/pahuang/work/root/server/frontend/target/web/user-profile-page/node_modules/webpack/lib/Compilation.js:350:28)
    at Tapable.onDoneResolving (/home/pahuang/work/root/server/frontend/target/web/user-profile-page/node_modules/webpack/lib/NormalModuleFactory.js:28:20)
    at Tapable.<anonymous> (/home/pahuang/work/root/server/frontend/target/web/user-profile-page/node_modules/webpack/lib/NormalModuleFactory.js:83:20)
    at /home/pahuang/work/root/server/frontend/target/web/user-profile-page/node_modules/webpack/node_modules/async/lib/async.js:251:17
    at done (/home/pahuang/work/root/server/frontend/target/web/user-profile-page/node_modules/webpack/node_modules/async/lib/async.js:126:15)
    at /home/pahuang/work/root/server/frontend/target/web/user-profile-page/node_modules/webpack/node_modules/async/lib/async.js:32:16
    at /home/pahuang/work/root/server/frontend/target/web/user-profile-page/node_modules/webpack/node_modules/async/lib/async.js:248:21
    at /home/pahuang/work/root/server/frontend/target/web/user-profile-page/node_modules/webpack/node_modules/async/lib/async.js:572:34
    at /home/pahuang/work/root/server/frontend/target/web/user-profile-page/node_modules/webpack/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:24:19
    at onResolved (/home/pahuang/work/root/server/frontend/target/web/user-profile-page/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:38:18)
    at /home/pahuang/work/root/server/frontend/target/web/user-profile-page/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:127:10
    at /home/pahuang/work/root/server/frontend/target/web/user-profile-page/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:191:15
    at applyPluginsParallelBailResult.createInnerCallback.log (/home/pahuang/work/root/server/frontend/target/web/user-profile-page/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:110:4)
    at loggingCallbackWrapper (/home/pahuang/work/root/server/frontend/target/web/user-profile-page/node_modules/webpack/node_modules/enhanced-resolve/lib/createInnerCallback.js:21:19)
    at /home/pahuang/work/root/server/frontend/target/web/user-profile-page/node_modules/webpack/node_modules/tapable/lib/Tapable.js:134:6
    at Tapable.<anonymous> (/home/pahuang/work/root/server/frontend/target/web/user-profile-page/node_modules/webpack/node_modules/enhanced-resolve/lib/DirectoryDescriptionFilePlugin.js:24:12)
    at Storage.finished (/home/pahuang/work/root/server/frontend/target/web/user-profile-page/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at evalmachine.<anonymous>:208:20
    at OpenReq.Req.done (/home/pahuang/work/root/server/frontend/target/web/user-profile-page/node_modules/webpack/node_modules/enhanced-resolve/node_modules/graceful-fs/graceful-fs.js:141:5)
    at OpenReq.done (/home/pahuang/work/root/server/frontend/target/web/user-profile-page/node_modules/webpack/node_modules/enhanced-resolve/node_modules/graceful-fs/graceful-fs.js:61:22)
    at Object.oncomplete (evalmachine.<anonymous>:108:15)
resolve file
  /home/pahuang/work/root/server/frontend/target/build/META-INF/resources doesn't exist
  /home/pahuang/work/root/server/frontend/target/build/META-INF/resources.js doesn't exist
  /home/pahuang/work/root/server/frontend/target/build/META-INF/resources.jsx doesn't exist
  /home/pahuang/work/root/server/frontend/target/build/META-INF/resources.json doesn't exist
resolve directory
  /home/pahuang/work/root/server/frontend/target/build/META-INF/resources doesn't exist (directory default file)
  /home/pahuang/work/root/server/frontend/target/build/META-INF/resources/package.json doesn't exist (directory description file)
npm ERR! weird error 1
npm ERR! not ok code 0
```

If I change my output.path to something different it still reads that value from command line argument and generate the same error.
Is there anything I need to fix in my config to make it work? Thanks.

**Comment by sokra** [comment]
The CLI argument `bundleDest=/home/pahuang/work/root/server/frontend/target/build/META-INF/resources` adds an entry point `bundleDest` just like `entry: {bundleDest: "/home/pahuang/work/root/server/frontend/target/build/META-INF/resources"}`

You should be able to pass `--env.bundleDest=/home/pahuang/work/root/server/frontend/target/build/META-INF/resources` instead.

`--env...` is future proof because with webpack-2 `--env` options will be passed to the webpack.config.js.

**Comment by huangp** [comment]
Thanks. The suggestion works.

**Comment by huangp** [comment]
For the convenience of whoever come to this issue later, to use the --env.someOption in webpack config, you need to access it as:
```
process.env.npm_config_env_someOption
```
