### ISSUE TITLE
Module build failed: Error: Final loader (unknown) didn't return a Buffer or String

### ISSUE THREAD

**Issue by vbartusevicius** [webpack/webpack#11705]
# Bug report

**What is the current behavior?**
Webpack 5.1.0 throws an error on compile, while webpack 4.44.2 completes successfully:
```
ERROR in #web/bundles/sonatacore/vendor/select2/select2.css
Module build failed: Error: Final loader (unknown) didn't return a Buffer or String
    at processResult (/home/app/src/node_modules/webpack/lib/NormalModule.js:592:17)
    at runLoaders (/home/app/src/node_modules/webpack/lib/NormalModule.js:669:5)
    at /home/app/src/node_modules/loader-runner/lib/LoaderRunner.js:404:3
    at iterateNormalLoaders (/home/app/src/node_modules/loader-runner/lib/LoaderRunner.js:233:10)
    at processResource (/home/app/src/node_modules/loader-runner/lib/LoaderRunner.js:227:3)
    at iteratePitchingLoaders (/home/app/src/node_modules/loader-runner/lib/LoaderRunner.js:171:10)
    at runLoaders (/home/app/src/node_modules/loader-runner/lib/LoaderRunner.js:395:2)
    at NormalModule.doBuild (/home/app/src/node_modules/webpack/lib/NormalModule.js:624:3)
    at NormalModule.build (/home/app/src/node_modules/webpack/lib/NormalModule.js:768:15)
    at module.needBuild (/home/app/src/node_modules/webpack/lib/Compilation.js:1083:12)
    at NormalModule.needBuild (/home/app/src/node_modules/webpack/lib/NormalModule.js:969:32)
    at Compilation._buildModule (/home/app/src/node_modules/webpack/lib/Compilation.js:1066:10)
    at hooks.beforeStart.callAsync.err (/home/app/src/node_modules/webpack/lib/util/AsyncQueue.js:235:10)
    at Hook.eval [as callAsync] (eval at create (/home/app/src/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncQueue._startProcessing (/home/app/src/node_modules/webpack/lib/util/AsyncQueue.js:228:26)
    at AsyncQueue._ensureProcessing (/home/app/src/node_modules/webpack/lib/util/AsyncQueue.js:218:9)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
 @ ./src/Evp/Bundle/AdminBundle/Resources/assets/standard-layout/style.js 1:219-278
```

the contens of `style.js`:
```
import 'font-awesome/css/font-awesome.css';
import '#web/bundles/sonatacore/vendor/ionicons/css/ionicons.css';
import '#web/bundles/sonatacore/vendor/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.css';
import '#web/bundles/sonatacore/vendor/select2/select2.css';
import '#web/bundles/sonatacore/vendor/select2-bootstrap-css/select2-bootstrap.min.css';
import '#web/bundles/sonataadmin/vendor/admin-lte/dist/css/skins/skin-black-light.css';
import '#web/bundles/sonataadmin/vendor/jqueryui/themes/base/jquery-ui.css';
import '#web/bundles/sonataadmin/vendor/iCheck/skins/square/blue.css';
import '#web/bundles/sonataadmin/vendor/admin-lte/dist/css/AdminLTE.css';
import '#web/bundles/sonataadmin/vendor/x-editable/dist/bootstrap3-editable/css/bootstrap-editable.css';
import '#web/bundles/sonataadmin/css/styles.css';
import '#web/bundles/sonataadmin/css/layout.css';
import '#web/bundles/sonataadmin/css/tree.css';
import 'bootstrap3-wysihtml5-bower/dist/bootstrap3-wysihtml5.css';
import '#evp_admin/standard-layout/less/backend_theme.less';
```

the webpack.config.js part regarding styles looks like this:
```
            {
                test: /\.(css|less|scss)$/i,
                exclude: modulePath => /ckeditor5-/.test(modulePath),
                use: [
                    {
                        loader: MiniCssExtractPlugin.loader,
                    },
                    {
                        loader: 'css-loader',
                        options: {
                            sourceMap: true,
                        },
                    },
                    {
                        loader: 'postcss-loader',
                        options: {
                            postcssOptions: {
                                plugins: [
                                    [
                                        'postcss-preset-env',
                                    ],
                                ],
                            },
                        },
                    },
                ],
            },
            {
                test: /\.less$/i,
                enforce: 'pre',
                use: [
                    {
                        loader: 'less-loader',
                        options: {
                            sourceMap: true,
                        },
                    },
                ],
            },
            {
                test: /\.scss$/i,
                enforce: 'pre',
                use: [
                    {
                        loader: 'sass-loader',
                        options: {
                            sourceMap: true,
                        },
                    },
                ],
            },
```
package.json:
```
    "cache-loader": "^4.1.0",
    "bundle-loader": "^0.5.6",
    "babel-loader": "^8.1.0",
    "css-loader": "^5.0.0",
    "exports-loader": "^1.1.1",
    "expose-loader": "^1.0.1",
    "file-loader": "^6.1.1",
    "image-webpack-loader": "^7.0.1",
    "imports-loader": "^1.2.0",
    "null-loader": "^4.0.1",
    "less-loader": "^7.0.2",
    "raw-loader": "^4.0.2",
    "sass-loader": "^10.0.3",
    "script-loader": "^0.7.2",
    "style-loader": "^2.0.0",
    "worker-loader": "^3.0.4",
    "postcss-loader": "^4.0.4",
    
    "mini-css-extract-plugin": "^1.0.0",
    "optimize-css-assets-webpack-plugin": "^5.0.4",
    "terser-webpack-plugin": "^4.2.3",
    
    "webpack": "^5.1.0",
    "webpack-cli": "^3.3.12",
    "webpack-dev-server": "^3.11.0",
```

**If the current behavior is a bug, please provide the steps to reproduce.**
https://github.com/vbartusevicius/webpack5-final-loader-null

**What is the expected behavior?**
It should compile the assets.

**Other relevant information:**
webpack version:  5.1.0
Node.js version: 10.18.1
Operating System: Linux c26e1fafd4c7 5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
Additional tools: n/a

**Comment by sokra** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by evilebottnawi** [comment]
Problem in `image-webpack-loader`, please migrate on https://github.com/webpack-contrib/image-minimizer-webpack-plugin, also please do not use `optimize-css-assets-webpack-plugin`, migrate to https://github.com/webpack-contrib/css-minimizer-webpack-plugin, feel free to feedback

**Comment by vbartusevicius** [comment]
Installed "css-minimizer-webpack-plugin": "^1.1.5", "image-minimizer-webpack-plugin": "^1.0.0"
Removed "image-webpack-loader" and "optimize-css-assets-webpack-plugin"

The result is still the same:
`Module build failed: Error: Final loader (unknown) didn't return a Buffer or String`

**Comment by vbartusevicius** [comment]
I also see some warnings:
```
(node:10523) [DEP_WEBPACK_COMPILATION_NORMAL_MODULE_LOADER_HOOK] DeprecationWarning: Compilation.hooks.normalModuleLoader was moved to NormalModule.getCompilationHooks(compilation).loader
(node:10523) [DEP_WEBPACK_COMPILATION_OPTIMIZE_CHUNK_ASSETS] DeprecationWarning: optimizeChunkAssets is deprecated (use Compilation.hook.processAssets instead and use one of Compilation.PROCESS_ASSETS_STAGE_* as stage option)
(node:10523) [DEP_WEBPACK_DEPRECATION_ARRAY_TO_SET] DeprecationWarning: Compilation.chunks was changed from Array to Set (using Array method 'reduce' is deprecated)
(node:10523) [DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
	Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
	Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.

```

how could I trace the corrupted loader here?

**Comment by evilebottnawi** [comment]
@vbartusevicius some plugin doesn't have compatibility with webpack@5, if you want to help please provide reproducible test repo  (or configuration(s))

**Comment by vbartusevicius** [comment]
@evilebottnawi - I will try to. 
Maybe you also could give me a little hint where I should put `console.log` to quickly identify the broken plugin?

**Comment by evilebottnawi** [comment]
No, because i don't know your configuration

**Comment by vbartusevicius** [comment]
@evilebottnawi - please check the reproducible repo: https://github.com/vbartusevicius/webpack5-final-loader-null

**Comment by evilebottnawi** [comment]
Reproduced, WIP

**Comment by evilebottnawi** [comment]
Notes:
- you don't need `cache-loader` with `webpack@5`, look at https://webpack.js.org/configuration/other-options/#cache, `image-minimizer-webpack-plugin` respect this option
- https://github.com/webpack/webpack-dev-server/issues/628 fixed
- Do not override `resolve.extensions` and `resolve.modules`
- Avoid using `cacheDirectory` and `cacheCompression` for `babel-loader`, this makes no sense
- You have deprecations warnings, please open issues in repos which is not fix compatibility with webpack@5

And main answer, do not use `#` in imports, because it is wrong, in `import` you use `URL`, `#test` is fragment (hash) of url

**Comment by evilebottnawi** [comment]
I can provide more information and a link to the specification if you want to see it

**Comment by vbartusevicius** [comment]
Thanks, so basically we need to change `#` to something different, like `!` or `*` not related to the URL spec?
Would gladly see more information.

**Comment by evilebottnawi** [comment]
> Thanks, so basically we need to change # to something different, like ! or * not related to the URL spec?

Avoid using special characters, because not all file systems supports it, just use `web/`

> Would gladly see more information.

What exactly would you like to know?

**Comment by vbartusevicius** [comment]
> I can provide more information and a link to the specification if you want to see it

**Comment by vbartusevicius** [comment]
I think we moved to `#` prefix because otherwise, the esilnt complains about missing package `#web/bundles` vs `web/bundles` - no such package `web`

**Comment by vbartusevicius** [comment]
Thanks!

**Comment by parasharsh** [comment]
Upgrading from Webpack 4 to Webpack 5 , alias starting with '#' does not work. https://github.com/webpack/webpack/issues/11705#issuecomment-712875972 mentions that we should not use '#'. Is this a change in behavior in Webpack 5?
