### ISSUE TITLE
webpack-dev-server can't use

### ISSUE THREAD

**Issue by yeminxuan** [webpack/webpack#11798]
# Bug report
use webpack 5.1.3 and webpack-dev-server found a mistack:
cmd console:
Error: Cannot find module 'webpack-cli/bin/config-yargs'
Require stack:
- F:\webpack-demo\node_modules\webpack-dev-server\bin\webpack-dev-server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (F:\webpack-demo\node_modules\webpack-dev-server\bin\webpack-dev-server.js:65:1)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'F:\\webpack-demo\\node_modules\\webpack-dev-server\\bin\\webpack-dev-server.js'
  ]
}

**Other relevant information:**
webpack version:  5.1.3
Node.js version: 12.19.0
Operating System: win10
Additional tools:webpack,webpack-cli,Chrome

**Comment by evilebottnawi** [comment]
Please open `webpack-dev-server` repo and look at pinned issue

**Comment by evilebottnawi** [comment]
https://github.com/webpack/webpack-dev-server/issues/2424
