### ISSUE TITLE
Unexpected token '!==' when importing external module using ModuleFederationPlugin

### ISSUE THREAD

**Issue by alex-vukov** [webpack/webpack#11805]
# Bug report

**What is the current behavior?**
When trying to build an application importing an external module exported via ModuleFederationPlugin I get the following error:
Uncaught SyntaxError: Unexpected token '!=='
The following code is generated by Webpack:
`/***/ "webpack/container/reference/BillingMFE":
/*!*****************************!*\
  !*** external "BillingMFE" ***!
  \*****************************/
/*! dynamic exports */
/*! exports [maybe provided (runtime-defined)] [no usage info] */
/*! runtime requirements: module, __webpack_require__.l, __webpack_require__.* */
/***/ (function(module, __unused_webpack_exports, __webpack_require__) {

"use strict";
var error = new Error();
module.exports = new Promise(function(resolve, reject) {
	if(**typeof  !== "undefined"**) return resolve();
	__webpack_require__.l("BillingMFE", function(event) {
		if(**typeof  !== "undefined"**) return resolve();
		var errorType = event && (event.type === 'load' ? 'missing' : event.type);
		var realSrc = event && event.target && event.target.src;
		error.message = 'Loading script failed.\n(' + errorType + ': ' + realSrc + ')';
		error.name = 'ScriptExternalLoadError';
		error.type = errorType;
		error.request = realSrc;
		reject(error);
	}, "");
}).then(function() { return ; });`

**What is the expected behavior?**
Expected behavior is for Webpack to insert a variable name in the generated code `if(typeof VARIABLE !== "undefined")`

**Other relevant information:**
webpack version:  5.2.0
Node.js version: 12.18.4
Operating System: Windows 10
Additional tools: n.a.

**Comment by evilebottnawi** [comment]
Please provide good information for the issue, you issue is not readable, I will reopen it after you fix it

**Comment by alex-vukov** [comment]
Edited. Please re-open

**Comment by evilebottnawi** [comment]
> I couldn't understand why I need both name and library with the same name for the remote module

Because you can have multiple them?

**Comment by tmkasun** [comment]
I'm having the same issue, 

I followed [basic host remote](https://github.com/module-federation/module-federation-examples/tree/master/basic-host-remote)  example pattern, and

I got following error when running a production build in webpack.
```java
ERROR in main.c759254c956de7e37d70.js from Terser
Unexpected token: operator (!==) [external "application_b":3,0][main.c759254c956de7e37d70.js:21,12]
    at js_error (/Users/user/testing/modulefederation/app1/node_modules/terser/dist/bundle.min.js:550:11)
    at croak (/Users/user/testing/modulefederation/app1/node_modules/terser/dist/bundle.min.js:1274:9)
    at token_error (/Users/user/testing/modulefederation/app1/node_modules/terser/dist/bundle.min.js:1282:9)
    at unexpected (/Users/user/testing/modulefederation/app1/node_modules/terser/dist/bundle.min.js:1288:9)
    at expr_atom (/Users/user/testing/modulefederation/app1/node_modules/terser/dist/bundle.min.js:2525:9)
    at maybe_unary (/Users/user/testing/modulefederation/app1/node_modules/terser/dist/bundle.min.js:3294:19)
    at maybe_unary (/Users/user/testing/modulefederation/app1/node_modules/terser/dist/bundle.min.js:3289:57)
    at expr_ops (/Users/user/testing/modulefederation/app1/node_modules/terser/dist/bundle.min.js:3345:24)
    at maybe_conditional (/Users/user/testing/modulefederation/app1/node_modules/terser/dist/bundle.min.js:3350:20)
    at maybe_assign (/Users/user/testing/modulefederation/app1/node_modules/terser/dist/bundle.min.js:3427:20)

ERROR in main.59760e1e42431bc60e23.js from Terser
Unexpected token: operator (!==) [main.59760e1e42431bc60e23.js:21,12]
    at js_error (/Users/user/testing/modulefederation/app1/node_modules/terser/dist/bundle.min.js:550:11)
    at croak (/Users/user/testing/modulefederation/app1/node_modules/terser/dist/bundle.min.js:1274:9)
    at token_error (/Users/user/testing/modulefederation/app1/node_modules/terser/dist/bundle.min.js:1282:9)
    at unexpected (/Users/user/testing/modulefederation/app1/node_modules/terser/dist/bundle.min.js:1288:9)
    at expr_atom (/Users/user/testing/modulefederation/app1/node_modules/terser/dist/bundle.min.js:2525:9)
    at maybe_unary (/Users/user/testing/modulefederation/app1/node_modules/terser/dist/bundle.min.js:3294:19)
    at maybe_unary (/Users/user/testing/modulefederation/app1/node_modules/terser/dist/bundle.min.js:3289:57)
    at expr_ops (/Users/user/testing/modulefederation/app1/node_modules/terser/dist/bundle.min.js:3345:24)
    at maybe_conditional (/Users/user/testing/modulefederation/app1/node_modules/terser/dist/bundle.min.js:3350:20)
    at maybe_assign (/Users/user/testing/modulefederation/app1/node_modules/terser/dist/bundle.min.js:3427:20)

webpack 5.36.1 compiled with 2 errors in 8185 ms
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react_module_federation_app1@1.0.0 build:prod: `npm run clean && webpack --mode production`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react_module_federation_app1@1.0.0 build:prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/user/.npm/_logs/2021-04-30T10_56_02_416Z-debug.log
```

Below is my App1 (Host app) webpack config,

```js
const path = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const ModuleFederationPlugin = require('webpack/lib/container/ModuleFederationPlugin');

const config = {
  entry: [
    './source/index.jsx',
  ],
  output: {
    path: path.resolve(__dirname, 'public'),
    filename: '[name].[contenthash].js',
    publicPath: 'auto',
  },
  module: {
    rules: [
      {
        test: /\.(js|jsx)$/,
        use: 'babel-loader',
        exclude: /node_modules/,
      },
      {
        test: /\.css$/i,
        use: ['style-loader', 'css-loader'],
      },
    ],
  },
  resolve: {
    extensions: ['.js', '.jsx'],
    alias: {
      'react-dom': '@hot-loader/react-dom',
    },
  },
  devtool: 'source-map',
  plugins: [
    new HtmlWebpackPlugin({
      template: 'source/assets/index.html',
    }),
    // New
    new ModuleFederationPlugin({
      name: 'application_master',
      remotes: {
        application_b: 'application_b',
      },
      shared: ['react', 'react-dom', '@material-ui/core', '@material-ui/icons', 'react-router-dom'],
    }),
  ],
};

module.exports = () => {
  return config;
};
```

I have noticed that In the example [application 1](https://github.com/module-federation/module-federation-examples/blob/master/basic-host-remote/app1/webpack.config.js#L39) It has used the remote hostname with `@http://remote.host.name/remoteEntry.js` when defining the remotes.

But in my case , I have used a `<script>` tag to import the remote entry file, Hence I omit the entry file path in my webpack config 
like below

```js
remotes: {
        application_b: 'application_b',
      },
```
Is this an invalid config ?

If I provide the hostname in the remote value, OR if I define an expose component and library config(then no need to provide entry file), It builds successfully.

example 

```js
new ModuleFederationPlugin({
      name: 'application_master',
      library: { type: 'var', name: 'application_master' },
      filename: 'masterRemoteEntry.js',
      exposes: {
        welcomeFromA: './source/Application/pages/Welcome.jsx',
      },
      remotes: {
        application_b: 'application_b',
      },
      shared: ['react', 'react-dom', '@material-ui/core', '@material-ui/icons', 'react-router-dom'],
    }),
```

The above config also works fine,

Why do I need to give a remote entry file when I'm not exposing any component in the remotes?

**Comment by alexander-akait** [comment]
What is `terser` version? Run `npm ls terser`/`yarn why terser`

**Comment by tmkasun** [comment]
The output of `npm ls terser`

```node
➜  npm ls terser
react_module_federation_app1@1.0.0 /Users/user/testing/modulefederation/app1
├─┬ html-webpack-plugin@5.3.1
│ └─┬ html-minifier-terser@5.1.1
│   └── terser@4.8.0 
└─┬ webpack@5.36.1
  └─┬ terser-webpack-plugin@5.1.1
    └── terser@5.7.0 
```

BTW can you please point me documentation for `ModuleFederationPlugin` configuration options ?
I searched in [webpack docs](https://webpack.js.org/concepts/module-federation) and [module-federation](https://module-federation.github.io/)

 But couldn't find details about, some of the configuration parameters, like `library`, 'remote' etc

**Comment by alexander-akait** [comment]
@tmkasun feel free to open an issue in https://github.com/webpack/webpack.js.org and describe what is not good described

Anyway problem is interesting, maybe terser bug or we generate broken code, can you provide example?

**Comment by tmkasun** [comment]
Hi @alexander-akait ,

I have pushed my sample code to Github, You can find it [here](https://github.com/tmkasun/webpack-MF-with-React/blob/main/app1/webpack.config.js)

I basically followed the `basic host remote` example from [module-federation-examples](https://github.com/module-federation/module-federation-examples)

In development build, Following exception thrown at the runtime in browser,

![image](https://user-images.githubusercontent.com/3313885/116721005-754f9500-a9fa-11eb-8a17-e1bfd3e4f655.png)

Here is the generated code in browser 

```js
/***/ "webpack/container/reference/application_b":
/*!********************************!*\
  !*** external "application_b" ***!
  \********************************/
/***/ ((module, __unused_webpack_exports, __webpack_require__) => {

"use strict";
var __webpack_error__ = new Error();
module.exports = new Promise((resolve, reject) => {
	if(typeof  !== "undefined") return resolve();
	__webpack_require__.l("application_b", (event) => {
		if(typeof  !== "undefined") return resolve();
		var errorType = event && (event.type === 'load' ? 'missing' : event.type);
		var realSrc = event && event.target && event.target.src;
		__webpack_error__.message = 'Loading script failed.\n(' + errorType + ': ' + realSrc + ')';
		__webpack_error__.name = 'ScriptExternalLoadError';
		__webpack_error__.type = errorType;
		__webpack_error__.request = realSrc;
		reject(__webpack_error__);
	}, "");
}).then(() => ());
```

In production build, I get following error at the build time

```js
➜  app1 git:(master) ✗ npm run build:prod

> react_module_federation_app1@1.0.0 build:prod /Users/user/testing/modulefederation/app1
> npm run clean && webpack --mode production


> react_module_federation_app1@1.0.0 clean /Users/user/testing/modulefederation/app1
> rm -Rf public/*

assets by status 393 KiB [cached] 9 assets
orphan modules 514 KiB [orphan] 211 modules
runtime modules 22.5 KiB 15 modules
built modules 887 KiB (javascript) 420 bytes (consume-shared) 132 bytes (share-init) 6 bytes (remote) [built]
  modules by path ./node_modules/ 853 KiB 78 modules
  consume-shared-module modules 420 bytes 10 modules
  modules by path ./source/ 33.7 KiB
    modules by path ./source/Application/ 32.5 KiB 7 modules
    modules by path ./source/*.jsx 1.18 KiB 2 modules
  provide-module modules 126 bytes
    provide shared module (default) react-dom@17.0.1+4.13.0 = ./node_modules/@hot-loader/react-dom/index.js 42 bytes [built] [code generated]
    provide shared module (default) react-router-dom@5.2.0 = ./node_modules/react-router-dom/esm/react-router-dom.js 42 bytes [built] [code generated]
    provide shared module (default) react@17.0.2 = ./node_modules/react/index.js 42 bytes [built] [code generated]
  remote application_b/SayHelloFromB 6 bytes (remote) 6 bytes (share-init) [built] [code generated]
  external "application_b" 42 bytes [built] [code generated]

ERROR in main.c759254c956de7e37d70.js from Terser
Unexpected token: operator (!==) [external "application_b":3,0][main.c759254c956de7e37d70.js:21,12]
    at js_error (/Users/user/testing/modulefederation/app1/node_modules/terser/dist/bundle.min.js:550:11)
    at croak (/Users/user/testing/modulefederation/app1/node_modules/terser/dist/bundle.min.js:1274:9)
    at token_error (/Users/user/testing/modulefederation/app1/node_modules/terser/dist/bundle.min.js:1282:9)
    at unexpected (/Users/user/testing/modulefederation/app1/node_modules/terser/dist/bundle.min.js:1288:9)
    at expr_atom (/Users/user/testing/modulefederation/app1/node_modules/terser/dist/bundle.min.js:2525:9)
    at maybe_unary (/Users/user/testing/modulefederation/app1/node_modules/terser/dist/bundle.min.js:3294:19)
    at maybe_unary (/Users/user/testing/modulefederation/app1/node_modules/terser/dist/bundle.min.js:3289:57)
    at expr_ops (/Users/user/testing/modulefederation/app1/node_modules/terser/dist/bundle.min.js:3345:24)
    at maybe_conditional (/Users/user/testing/modulefederation/app1/node_modules/terser/dist/bundle.min.js:3350:20)
    at maybe_assign (/Users/user/testing/modulefederation/app1/node_modules/terser/dist/bundle.min.js:3427:20)

ERROR in main.59760e1e42431bc60e23.js from Terser
Unexpected token: operator (!==) [main.59760e1e42431bc60e23.js:21,12]
    at js_error (/Users/user/testing/modulefederation/app1/node_modules/terser/dist/bundle.min.js:550:11)
    at croak (/Users/user/testing/modulefederation/app1/node_modules/terser/dist/bundle.min.js:1274:9)
    at token_error (/Users/user/testing/modulefederation/app1/node_modules/terser/dist/bundle.min.js:1282:9)
    at unexpected (/Users/user/testing/modulefederation/app1/node_modules/terser/dist/bundle.min.js:1288:9)
    at expr_atom (/Users/user/testing/modulefederation/app1/node_modules/terser/dist/bundle.min.js:2525:9)
    at maybe_unary (/Users/user/testing/modulefederation/app1/node_modules/terser/dist/bundle.min.js:3294:19)
    at maybe_unary (/Users/user/testing/modulefederation/app1/node_modules/terser/dist/bundle.min.js:3289:57)
    at expr_ops (/Users/user/testing/modulefederation/app1/node_modules/terser/dist/bundle.min.js:3345:24)
    at maybe_conditional (/Users/user/testing/modulefederation/app1/node_modules/terser/dist/bundle.min.js:3350:20)
    at maybe_assign (/Users/user/testing/modulefederation/app1/node_modules/terser/dist/bundle.min.js:3427:20)

webpack 5.36.1 compiled with 2 errors in 6950 ms
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react_module_federation_app1@1.0.0 build:prod: `npm run clean && webpack --mode production`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react_module_federation_app1@1.0.0 build:prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/user/.npm/_logs/2021-04-30T16_21_57_408Z-debug.log
```

Let me know if you need further information

**Comment by tmkasun** [comment]
I inspected the generated code after adding `@` to the remotes value 

example:

```js
.
.
.
new ModuleFederationPlugin({
      name: 'application_master',
      remotes: {
        application_b: 'application_b@',
      },
      shared: ['react', 'react-dom', '@material-ui/core', '@material-ui/icons', 'react-router-dom'],
    })
.
.

```

then the application renders correctly and generated code as below

![image](https://user-images.githubusercontent.com/3313885/116724939-e5601a00-a9fe-11eb-82c2-195db02c517b.png)

Without the `@` in the value of the remotes 
```
application_b: 'application_b@',
```

it throws that syntax error

**Comment by alexander-akait** [comment]
We need throw an error in this case and improve docs

**Comment by vankop** [comment]
can not reproduce with latest webpack, getting
```
ERROR in external "aaa"
Invalid request "aaa"
Error: Invalid request "aaa"
```
