### ISSUE TITLE
Webpack exits with 0 if there is a loader dependency problem

### ISSUE THREAD

**Issue by nkbt** [webpack/webpack#1193]
Our build process "completed" successfully with code `0`, but nothing was actually built.

We use `--bail` option, so it fails in case of any errors.

In our case that happened, because node-sass did not have proper `bindings.node`, but the case could be reproduced quite easily by adding `throw`:
#### /node_modules/node-sass/lib/index.js:25

``` js
// ...
function getVersionInfo(binding) {

  throw new Error('OMFG!'); // <--- here we go

  return [
           ['node-sass', pkg.version, '(Wrapper)', '[JavaScript]'].join('\t'),
           ['libsass  ', binding.libsassVersion(), '(Sass Compiler)', '[C/C++]'].join('\t'),
  ].join(eol);
}
// ...
process.sass.versionInfo = getVersionInfo(binding);
// ...
```

So now `sass-loader` cannot be loaded correctly because its dependency `node-sass` fails.

Then run `wabpack --bail` and get the same error for each sass file included

``` sh
Error: OMFG!
  at getVersionInfo (/Users/nkbt/www/frontend/node_modules/node-sass/lib/index.js:25:9)
  at Object.<anonymous> (/Users/nkbt/www/frontend/node_modules/node-sass/lib/index.js:419:28)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (/Users/nkbt/www/frontend/node_modules/hamlc-loader/node_modules/haml-coffee/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/Users/nkbt/www/frontend/node_modules/sass-loader/index.js:4:12)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (/Users/nkbt/www/frontend/node_modules/hamlc-loader/node_modules/haml-coffee/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at DependenciesBlock.loadPitch (/Users/nkbt/www/frontend/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:193:17)
  at DependenciesBlock.loadPitch (/Users/nkbt/www/frontend/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:186:21)
  at DependenciesBlock.loadPitch (/Users/nkbt/www/frontend/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:223:61)
  at DependenciesBlock.doBuild (/Users/nkbt/www/frontend/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:241:4)
  at DependenciesBlock.build (/Users/nkbt/www/frontend/node_modules/webpack/lib/NormalModule.js:83:14)
  at Tapable.Compilation.buildModule (/Users/nkbt/www/frontend/node_modules/webpack/lib/Compilation.js:122:9)
  at Tapable.<anonymous> (/Users/nkbt/www/frontend/node_modules/webpack/lib/Compilation.js:301:9)
  at Tapable.<anonymous> (/Users/nkbt/www/frontend/node_modules/webpack/lib/NormalModuleFactory.js:57:13)
  at Tapable.applyPluginsAsyncWaterfall (/Users/nkbt/www/frontend/node_modules/webpack/node_modules/tapable/lib/Tapable.js:75:69)
  at Tapable.onDoneResolving (/Users/nkbt/www/frontend/node_modules/webpack/lib/NormalModuleFactory.js:37:10)
  at Tapable.onDoneResolving (/Users/nkbt/www/frontend/node_modules/webpack/lib/NormalModuleFactory.js:118:6)
  at Tapable.<anonymous> (/Users/nkbt/www/frontend/node_modules/webpack/lib/NormalModuleFactory.js:96:29)
  at /Users/nkbt/www/frontend/node_modules/webpack/node_modules/async/lib/async.js:251:17
  at done (/Users/nkbt/www/frontend/node_modules/webpack/node_modules/async/lib/async.js:132:19)
  at /Users/nkbt/www/frontend/node_modules/webpack/node_modules/async/lib/async.js:32:16
  at /Users/nkbt/www/frontend/node_modules/webpack/node_modules/async/lib/async.js:248:21
  at /Users/nkbt/www/frontend/node_modules/webpack/node_modules/async/lib/async.js:572:34
  at Tapable.resolve (/Users/nkbt/www/frontend/node_modules/webpack/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:21:11)
  at Tapable.async.parallel.loaders (/Users/nkbt/www/frontend/node_modules/webpack/lib/NormalModuleFactory.js:80:28)
  at /Users/nkbt/www/frontend/node_modules/webpack/node_modules/async/lib/async.js:567:21
  at /Users/nkbt/www/frontend/node_modules/webpack/node_modules/async/lib/async.js:246:17
  at /Users/nkbt/www/frontend/node_modules/webpack/node_modules/async/lib/async.js:122:13
  at _each (/Users/nkbt/www/frontend/node_modules/webpack/node_modules/async/lib/async.js:46:13)
  at async.each (/Users/nkbt/www/frontend/node_modules/webpack/node_modules/async/lib/async.js:121:9)
  at _asyncMap (/Users/nkbt/www/frontend/node_modules/webpack/node_modules/async/lib/async.js:245:13)
  at Object.map (/Users/nkbt/www/frontend/node_modules/webpack/node_modules/async/lib/async.js:216:23)
  at _parallel (/Users/nkbt/www/frontend/node_modules/webpack/node_modules/async/lib/async.js:565:20)
  at Object.async.parallel (/Users/nkbt/www/frontend/node_modules/webpack/node_modules/async/lib/async.js:595:9)
  at Tapable.<anonymous> (/Users/nkbt/www/frontend/node_modules/webpack/lib/NormalModuleFactory.js:73:10)
  at Tapable.<anonymous> (/Users/nkbt/www/frontend/node_modules/webpack/lib/NormalModuleFactory.js:27:4)
  at Tapable.<anonymous> (/Users/nkbt/www/frontend/node_modules/webpack/lib/NormalModuleFactory.js:153:3)
  at Tapable.applyPluginsAsyncWaterfall (/Users/nkbt/www/frontend/node_modules/webpack/node_modules/tapable/lib/Tapable.js:75:69)
  at Tapable.NormalModuleFactory.create (/Users/nkbt/www/frontend/node_modules/webpack/lib/NormalModuleFactory.js:138:7)
  at Tapable.<anonymous> (/Users/nkbt/www/frontend/node_modules/webpack/lib/Compilation.js:207:11)
  at /Users/nkbt/www/frontend/node_modules/webpack/node_modules/async/lib/async.js:122:13
  at _each (/Users/nkbt/www/frontend/node_modules/webpack/node_modules/async/lib/async.js:46:13)
  at Object.async.each (/Users/nkbt/www/frontend/node_modules/webpack/node_modules/async/lib/async.js:121:9)
  at Tapable.Compilation.addModuleDependencies (/Users/nkbt/www/frontend/node_modules/webpack/lib/Compilation.js:178:8)
  at Tapable.Compilation.processModuleDependencies (/Users/nkbt/www/frontend/node_modules/webpack/lib/Compilation.js:164:7)
  at Tapable.<anonymous> (/Users/nkbt/www/frontend/node_modules/webpack/lib/Compilation.js:312:11)
  at /Users/nkbt/www/frontend/node_modules/webpack/lib/Compilation.js:119:4
  at Array.forEach (native)
  at callback (/Users/nkbt/www/frontend/node_modules/webpack/lib/Compilation.js:118:12)
  at Tapable.<anonymous> (/Users/nkbt/www/frontend/node_modules/webpack/lib/Compilation.js:136:10)
  at DependenciesBlock.<anonymous> (/Users/nkbt/www/frontend/node_modules/webpack/lib/NormalModule.js:114:10)
  at DependenciesBlock.onModuleBuild (/Users/nkbt/www/frontend/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
  at DependenciesBlock.nextLoader (/Users/nkbt/www/frontend/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
  at DependenciesBlock.<anonymous> (/Users/nkbt/www/frontend/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:236:16)
  at runSyncOrAsync (/Users/nkbt/www/frontend/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:160:12)
  at DependenciesBlock.loadPitch (/Users/nkbt/www/frontend/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:227:3)
  at DependenciesBlock.doBuild (/Users/nkbt/www/frontend/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:241:4)
  at DependenciesBlock.build (/Users/nkbt/www/frontend/node_modules/webpack/lib/NormalModule.js:83:14)
  at Tapable.Compilation.buildModule (/Users/nkbt/www/frontend/node_modules/webpack/lib/Compilation.js:122:9)
  at Tapable.<anonymous> (/Users/nkbt/www/frontend/node_modules/webpack/lib/Compilation.js:301:9)
  at Tapable.<anonymous> (/Users/nkbt/www/frontend/node_modules/webpack/lib/NormalModuleFactory.js:57:13)
  at Tapable.applyPluginsAsyncWaterfall (/Users/nkbt/www/frontend/node_modules/webpack/node_modules/tapable/lib/Tapable.js:75:69)
  at Tapable.onDoneResolving (/Users/nkbt/www/frontend/node_modules/webpack/lib/NormalModuleFactory.js:37:10)
  at Tapable.onDoneResolving (/Users/nkbt/www/frontend/node_modules/webpack/lib/NormalModuleFactory.js:118:6)
  at Tapable.<anonymous> (/Users/nkbt/www/frontend/node_modules/webpack/lib/NormalModuleFactory.js:114:23)
  at /Users/nkbt/www/frontend/node_modules/webpack/node_modules/async/lib/async.js:251:17
  at done (/Users/nkbt/www/frontend/node_modules/webpack/node_modules/async/lib/async.js:132:19)
  at /Users/nkbt/www/frontend/node_modules/webpack/node_modules/async/lib/async.js:32:16
  at /Users/nkbt/www/frontend/node_modules/webpack/node_modules/async/lib/async.js:248:21
  at /Users/nkbt/www/frontend/node_modules/webpack/node_modules/async/lib/async.js:572:34
  at Tapable.resolveRequestArray (/Users/nkbt/www/frontend/node_modules/webpack/lib/NormalModuleFactory.js:159:32)
  at /Users/nkbt/www/frontend/node_modules/webpack/node_modules/async/lib/async.js:567:21
  at /Users/nkbt/www/frontend/node_modules/webpack/node_modules/async/lib/async.js:246:17
  at /Users/nkbt/www/frontend/node_modules/webpack/node_modules/async/lib/async.js:122:13
  at _each (/Users/nkbt/www/frontend/node_modules/webpack/node_modules/async/lib/async.js:46:13)
  at async.each (/Users/nkbt/www/frontend/node_modules/webpack/node_modules/async/lib/async.js:121:9)
  at _asyncMap (/Users/nkbt/www/frontend/node_modules/webpack/node_modules/async/lib/async.js:245:13)
  at Object.map (/Users/nkbt/www/frontend/node_modules/webpack/node_modules/async/lib/async.js:216:23)
  at _parallel (/Users/nkbt/www/frontend/node_modules/webpack/node_modules/async/lib/async.js:565:20)
  at Object.async.parallel (/Users/nkbt/www/frontend/node_modules/webpack/node_modules/async/lib/async.js:595:9)
  at Tapable.<anonymous> (/Users/nkbt/www/frontend/node_modules/webpack/lib/NormalModuleFactory.js:107:12)
  at /Users/nkbt/www/frontend/node_modules/webpack/node_modules/async/lib/async.js:251:17
  at done (/Users/nkbt/www/frontend/node_modules/webpack/node_modules/async/lib/async.js:132:19)
  at /Users/nkbt/www/frontend/node_modules/webpack/node_modules/async/lib/async.js:32:16
  at /Users/nkbt/www/frontend/node_modules/webpack/node_modules/async/lib/async.js:248:21
  at /Users/nkbt/www/frontend/node_modules/webpack/node_modules/async/lib/async.js:572:34
  at /Users/nkbt/www/frontend/node_modules/webpack/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:29:4
  at onResolved (/Users/nkbt/www/frontend/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:39:10)
  at /Users/nkbt/www/frontend/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:123:21
  at /Users/nkbt/www/frontend/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:191:15
  at applyPluginsParallelBailResult.createInnerCallback.log (/Users/nkbt/www/frontend/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:104:30)
  at loggingCallbackWrapper (/Users/nkbt/www/frontend/node_modules/webpack/node_modules/enhanced-resolve/lib/createInnerCallback.js:21:19)
  at /Users/nkbt/www/frontend/node_modules/webpack/node_modules/tapable/lib/Tapable.js:134:6
  at innerCallback (/Users/nkbt/www/frontend/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:90:37)
  at loggingCallbackWrapper (/Users/nkbt/www/frontend/node_modules/webpack/node_modules/enhanced-resolve/lib/createInnerCallback.js:21:19)
  at /Users/nkbt/www/frontend/node_modules/webpack/node_modules/tapable/lib/Tapable.js:134:6
  at Tapable.<anonymous> (/Users/nkbt/www/frontend/node_modules/webpack/node_modules/enhanced-resolve/lib/ResultSymlinkPlugin.js:39:32)
  at /Users/nkbt/www/frontend/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:191:15
  at /Users/nkbt/www/frontend/node_modules/webpack/node_modules/enhanced-resolve/lib/ResultSymlinkPlugin.js:36:5
  at Storage.finished (/Users/nkbt/www/frontend/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
  at Object.oncomplete (evalmachine.<anonymous>:108:15)
```

And then webpack exits without any error and build process carries on.

**Comment by sokra** [comment]
The exit code changes with webpack 2...

**Comment by lo1tuma** [comment]
Today I had a similar issue in combination with uglifyjs. The following error message is written to stdout

```
ERROR in js-bundle.js from UglifyJs
Unexpected token: name (Alternatives) [js-bundle.js:95739,5]
```

but the exit code is still `0`.

**Comment by 59naga** [comment]
[I also encountered a similar issue](https://travis-ci.org/itakojs/itako-audio-reader-audio-context/jobs/123570907#L1217). this failure is reported in the [stdout](https://github.com/abigailjs/abigail-plugin-exit/issues/1#issuecomment-213575702).

**Comment by costa** [comment]
yep, this is definitely a major-version-level issue

**Comment by TheLarkInn** [comment]
Closing as this I believe is working in webpack@latest.
