### ISSUE TITLE
fix(ContextModuleFactory): RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by petermetz** [webpack/webpack#11965]
# Bug report

**What is the current behavior?**

Crashes with a stack trace of

```sh
$ npm run webpack:dev

> @hyperledger/cactus@ webpack:dev *REDACTED_PATH*
> node --max-old-space-size=8192 node_modules/webpack/bin/webpack.js --display-error-details --env env-csv=dev --env target-csv=node

*REDACTED_PATH*/node_modules/webpack/lib/ContextModuleFactory.js:371
                                                        if (item) flattenedResult.push(...item);
                                                                                  ^

RangeError: Maximum call stack size exceeded
    at *REDACTED_PATH*/node_modules/webpack/lib/ContextModuleFactory.js:371:34
    at done (*REDACTED_PATH*/node_modules/neo-async/async.js:2931:13)
    at *REDACTED_PATH*/node_modules/webpack/lib/ContextModuleFactory.js:374:7
    at done (*REDACTED_PATH*/node_modules/neo-async/async.js:2931:13)
    at *REDACTED_PATH*/node_modules/webpack/lib/ContextModuleFactory.js:374:7
    at done (*REDACTED_PATH*/node_modules/neo-async/async.js:2931:13)
    at *REDACTED_PATH*/node_modules/webpack/lib/ContextModuleFactory.js:374:7
    at done (*REDACTED_PATH*/node_modules/neo-async/async.js:2931:13)
    at *REDACTED_PATH*/node_modules/webpack/lib/ContextModuleFactory.js:374:7
    at done (*REDACTED_PATH*/node_modules/neo-async/async.js:2931:13)
    at *REDACTED_PATH*/node_modules/webpack/lib/ContextModuleFactory.js:374:7
    at done (*REDACTED_PATH*/node_modules/neo-async/async.js:2931:13)
    at *REDACTED_PATH*/node_modules/webpack/lib/ContextModuleFactory.js:374:7
    at done (*REDACTED_PATH*/node_modules/neo-async/async.js:2931:13)
    at *REDACTED_PATH*/node_modules/webpack/lib/ContextModuleFactory.js:374:7
    at done (*REDACTED_PATH*/node_modules/neo-async/async.js:2931:13)
    at *REDACTED_PATH*/node_modules/webpack/lib/ContextModuleFactory.js:374:7
    at done (*REDACTED_PATH*/node_modules/neo-async/async.js:2931:13)
    at *REDACTED_PATH*/node_modules/webpack/lib/ContextModuleFactory.js:374:7
    at done (*REDACTED_PATH*/node_modules/neo-async/async.js:2931:13)
    at *REDACTED_PATH*/node_modules/webpack/lib/ContextModuleFactory.js:374:7
    at done (*REDACTED_PATH*/node_modules/neo-async/async.js:2931:13)
    at *REDACTED_PATH*/node_modules/webpack/lib/ContextModuleFactory.js:374:7
    at done (*REDACTED_PATH*/node_modules/neo-async/async.js:2931:13)
    at *REDACTED_PATH*/node_modules/webpack/lib/ContextModuleFactory.js:374:7
    at done (*REDACTED_PATH*/node_modules/neo-async/async.js:2931:13)
    at *REDACTED_PATH*/node_modules/webpack/lib/ContextModuleFactory.js:374:7
    at done (*REDACTED_PATH*/node_modules/neo-async/async.js:2931:13)
    at *REDACTED_PATH*/node_modules/webpack/lib/ContextModuleFactory.js:374:7
    at done (*REDACTED_PATH*/node_modules/neo-async/async.js:2931:13)
```

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Clone the repo where the failure can be reproduced: https://github.com/petermetz/blockchain-integration-framework/tree/build/webpack-optimization-139
2. Check out the branch called `build/webpack-optimization-139`
3. Execute `npm run configure` which will produce the crash logs stated above.
4. You can observe the effective webpack config file after the build has run at least once at `./webpack.config.json`

**What is the expected behavior?**

Build succeeds without RangeError.

**Other relevant information:**
webpack version:  `v5.4.0`
Node.js version: `v12.16.3`
Operating System: `Ubuntu 20.04 LTS`
Additional tools: `Lerna, Typescript, ts-loader`

**Comment by shaodahong** [comment]
same error when use module federation

**Comment by sokra** [comment]
@shaodahong this is not the same problem. Please report a separate issue.

**Comment by alexander-akait** [comment]
After updating to the latest version no original problem, but I found other problem here - `TypeError: Cannot read property 'availableChildren' of undefined` (duplicate https://github.com/webpack/webpack/issues/11740), why it happens? Due `cactus/examples/cactus-example-supply-chain-frontend/src/main/typescript/index.ts` doesn't exists. How I debug it? Just remove `dependOn` from the each entry. Also you can find `"./examples/cactus-example-supply-chain-frontend/undefined",` in `webpack.config.json`, i.e. you get this problem when webpack can't resolve something in `dependOn`. Let's close in favor https://github.com/webpack/webpack/issues/11740. We need improve the error.
