### ISSUE TITLE
Unable to resolve loaders if directory contains an octothorpe

### ISSUE THREAD

**Issue by rymdkapten** [webpack/webpack#12156]
# Bug report

**What is the current behavior?**

Webpack is unable to resolve loaders if the folder name contains # (octothorpe/number sign/pound/hash)
The error output shows a whitespace character being added in front of the symbol which in turn causes the required files not to be found.

**If the current behavior is a bug, please provide the steps to reproduce.**

Create a project where the root directory or any directory leading up to it has a name containing the #-symbol, e.g. "#Test".
Add webpack and any loader (e.g. ts-loader) as dependencies.
When trying to run a webpack build it will throw an exception such as the following;
(Note the prepended whitespace in the error message which is not seen in the require stack)
```
ERROR in ../ #Test/src/main.ts
Module build failed (from ../ #Test/node_modules/ts-loader/index.js):
Error: Cannot find module 'C:\Projects\ #Test\node_modules\ts-loader\index.js'
Require stack:
- C:\Projects\#Test\node_modules\loader-runner\lib\loadLoader.js
- C:\Projects\#Test\node_modules\loader-runner\lib\LoaderRunner.js
- C:\Projects\#Test\node_modules\webpack\lib\NormalModule.js
- C:\Projects\#Test\node_modules\webpack\lib\NormalModuleFactory.js
- C:\Projects\#Test\node_modules\webpack\lib\Compiler.js
- C:\Projects\#Test\node_modules\webpack\lib\webpack.js
- C:\Projects\#Test\node_modules\webpack\lib\index.js
- C:\Projects\#Test\node_modules\webpack-cli\lib\utils\package-exists.js
- C:\Projects\#Test\node_modules\webpack-cli\lib\webpack-cli.js
- C:\Projects\#Test\node_modules\webpack-cli\lib\bootstrap.js
- C:\Projects\#Test\node_modules\webpack-cli\bin\cli.js
- C:\Projects\#Test\node_modules\webpack\bin\webpack.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (C:\Projects\#Test\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at loadLoader (C:\Projects\#Test\node_modules\loader-runner\lib\loadLoader.js:19:17)
    at iteratePitchingLoaders (C:\Projects\#Test\node_modules\loader-runner\lib\LoaderRunner.js:183:2)
    at runLoaders (C:\Projects\#Test\node_modules\loader-runner\lib\LoaderRunner.js:396:2)
    at NormalModule.doBuild (C:\Projects\#Test\node_modules\webpack\lib\NormalModule.js:631:3)
    at NormalModule.build (C:\Projects\#Test\node_modules\webpack\lib\NormalModule.js:775:15)
    at C:\Projects\#Test\node_modules\webpack\lib\Compilation.js:1193:12
```

**What is the expected behavior?**
Loaders being found regardless of special characters in the full path name.

**Other relevant information:**
webpack version: 5.10.0
Node.js version: 14.15.1
Operating System: Windows 10
Additional tools: -

**Comment by alexander-akait** [comment]
Do you have ` ` (space) in directory name?

**Comment by rymdkapten** [comment]
> 
> 
> Do you have ` ` (space) in directory name? Directory name is `Projects #Test`, right?

No, the directory is
`C:\Projects\#Test\`

Compare it to the error message;
```
Error: Cannot find module 'C:\Projects\ #Test\node_modules\ts-loader\index.js'
                                       ^ there is a space here
```

**Comment by sokra** [comment]
Seem to be a bug in loader path handling. I guess the space is really a \0

**Comment by TNThacker2015** [comment]
I can reproduce. One of my project folders contains a #, and I was going insane trying to find why it wasn't detecting the loaders.

**Comment by alexander-akait** [comment]
@MelnCat Can you provide example of the problem

**Comment by benderbr22** [comment]
Just found this issue after posting a similar issue, but the error message I get is different and I'm not having the issue with it inserting a space, so these might be separate issues. I don't know if any of the information I provided might help though. #12574

**Comment by alexander-akait** [comment]
@benderbr22 not related to your problem

**Comment by alexander-akait** [comment]
Reproduce example too https://github.com/webpack/webpack/issues/12574#issuecomment-772435703

**Comment by rymdkapten** [comment]
Tried updating to 5.35.1. While the prepended space is now removed in the error message, there still seem to be issues resolving loaders.

This can be tested by renaming the working directory to anything containing the #-symbol, causing webpack to be unable to find any loader.

Another perhaps simpler way to test this is by copying a loader to a folder containing the #-symbol, e.g.;
```
module: {
  rules: [
    test: /\.ts$/,
    use: [
      {
        loader: path.resolve(__dirname, 'loaders/my-loader.js'), // Works
      },
      {
        loader: path.resolve(__dirname, 'loaders#/my-loader.js'), // Error: Cannot find module...
      },
    ],
  ],
},
```

Let me know if I should create a new issue for this.

**Comment by alexander-akait** [comment]
Yep, please open an issue issue
