### ISSUE TITLE
Migration 5.1.0-5.1.1 is failing  inputSource.sourceAndMap is not a function

### ISSUE THREAD

**Issue by ievgennaida** [webpack/webpack#12186]
The project cannot be migrated from v4 to the latest v5.
Problem is reproduced on update  5.1.0-5.1.1

Sources:

Webpack config:
https://github.com/ievgennaida/animation-timeline-control/blob/master/webpack.config.js

package.json
https://github.com/ievgennaida/animation-timeline-control/blob/master/package.json

# Bug report

Exception when moving
HookWebpackError: inputSource.sourceAndMap is not a function
    at makeWebpackError (C:\dev\Vector-editor\js-animation-timeline-control\node_modules\webpack\lib\HookWebpackError.js:49:9)
    at C:\dev\Vector-editor\js-animation-timeline-control\node_modules\webpack\lib\Compilation.js:1997:11
    at eval (eval at create (C:\dev\Vector-editor\js-animation-timeline-control\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:39:1)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
-- inner error --
TypeError: inputSource.sourceAndMap is not a function
    at C:\dev\Vector-editor\js-animation-timeline-control\node_modules\terser-webpack-plugin\dist\index.js:323:27
    at C:\dev\Vector-editor\js-animation-timeline-control\node_modules\terser-webpack-plugin\node_modules\p-limit\index.js:23:31
    at run (C:\dev\Vector-editor\js-animation-timeline-control\node_modules\terser-webpack-plugin\node_modules\p-limit\index.js:23:43)
    at C:\dev\Vector-editor\js-animation-timeline-control\node_modules\terser-webpack-plugin\node_modules\p-limit\index.js:45:20
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
caused by plugins in Compilation.hooks.processAssets

**What is the expected behavior?**

Migration plan or should not fail.

**Comment by alexander-akait** [comment]
Please open an issue in `unminified-webpack-plugin` plugin, no compatibility with webpack@5

**Comment by CooLNuanfeng** [comment]
+1
