### ISSUE TITLE
Can not run example at webpack@4.44.2

### ISSUE THREAD

**Issue by techbirds** [webpack/webpack#12295]
# Bug report

**What is the current behavior?**

do 
```
git clone https://github.com/webpack/webpack.git
cd webpack
git checkout v4.44.2
yarn
yarn setup
yarn add --dev webpack-cli
cd example/aggressive-merging
node build.js
```

ref: https://github.com/webpack/webpack/blob/v4.44.2/examples/README.md

error
```
➜  aggressive-merging git:(2efeb4b57) ✗ node build.js
error: unknown option '--display-reasons'
[webpack-cli] Run 'webpack --help' to see available commands and options

Error: Command failed: node /Users/vvadmin/code/learn_webpack/webpack/bin/webpack.js --mode production  --display-reasons --display-used-exports --display-provided-exports --display-chunks --display-max-modules 99999 --display-origins --display-entrypoints --output-public-path "dist/"
error: unknown option '--display-reasons'
[webpack-cli] Run 'webpack --help' to see available commands and options

    at ChildProcess.exithandler (child_process.js:295:12)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:210:5)
    at Pipe.<anonymous> (net.js:659:12) {
  killed: false,
  code: 2,
  signal: null,
  cmd: 'node /Users/vvadmin/code/learn_webpack/webpack/bin/webpack.js --mode production  --display-reasons --display-used-exports --display-provided-exports --display-chunks --display-max-modules 99999 --display-origins --display-entrypoints --output-public-path "dist/"  '
}
error: unknown option '--output-pathinfo'
[webpack-cli] Run 'webpack --help' to see available commands and options
```

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Other relevant information:**
webpack version:  4.44.2
Node.js version:  12.13.1
Operating System: Mac 
Additional tools: iTerm

**Comment by sokra** [comment]
You need to install an older version of the webpack-cli.
