### ISSUE TITLE
output.libraryTarget: var with empty output.library gives error

### ISSUE THREAD

**Issue by tlmii** [webpack/webpack#12316]
# Bug report

**What is the current behavior?**

If you specify `output.libraryTarget: 'var'` and  `output.library: ''`, an error:

```console
Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
 - configuration.output.library should be an non-empty string.
```

or if you specify `output.libraryTarget: 'var'` and leave `output.library` out altogether, a different error:

```console
Error: Library name must be a string or string array
    at AssignLibraryPlugin.parseOptions (...\node_modules\webpack\lib\library\AssignLibraryPlugin.js:110:11)
    at AssignLibraryPlugin._parseOptionsCached (...\node_modules\webpack\lib\library\AbstractLibraryPlugin.js:120:23)
    at ...\node_modules\webpack\lib\library\AbstractLibraryPlugin.js:60:27
    at Hook.eval [as callAsync] (eval at create (...\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:18:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (...\node_modules\tapable\lib\Hook.js:18:14)
    at Compilation.finish (...\node_modules\webpack\lib\Compilation.js:1848:28)
    at ...\node_modules\webpack\lib\Compiler.js:1045:19
    at processTicksAndRejections (node:internal/process/task_queues:75:11)
```

**If the current behavior is a bug, please provide the steps to reproduce.**

in your webpack config, specify `output.libraryTarget: 'var'` and `output.library: ''`, e.g.:

```javascript
module.exports = {
  mode: 'development',
  entry: './src/index.js',
  output: {
    filename: 'main.js',
    path: path.resolve(__dirname, 'dist'),
    libraryTarget: 'var',
    library: ''
  },
  target: ['web', 'es5'],
};
```

for a GH repo example, see the v5-var folder in https://github.com/tlmii/webpack-v4-to-v5-example. 
1. Navigate to the v5-var folder, 
2. `npm install` 
3. `npx webpack` 
4. You'll see the error.

These examples are for an empty string (given what the documentation says below) but I also specified what happens if you just leave it out completely in the previous section)

**What is the expected behavior?**

Per the [`output.libraryTarget` documentation when specifying `var`](https://webpack.js.org/configuration/output/#expose-a-variable):

> When using this option, an empty output.library will result in no assignment.

I would expect that to mean that the compilation would occur without error, and the `var variableName;variableName = ` at the beginning of the output would just be omitted. 

**Other relevant information:**
webpack version:  5.11.1
Node.js version: 15.5.0
Operating System: Win10

I don't know whether this is a documentation bug (either because it is incorrect or it is just unclear) or a bug in webpack. I'm hoping for the latter, because I'd like the behavior that matches my understanding of what the documentation says.

**Comment by sokra** [comment]
An empty string is invalid. You must specify a valid identifier that should be assigned.

**Comment by alexander-akait** [comment]
@sokra Should we move this to docs issues?
