### ISSUE TITLE
bug: ModuleFederationPlugin filename xx.js Error

### ISSUE THREAD

**Issue by crazyair** [webpack/webpack#12320]
# Bug report
https://github.com/crazyair/webpack-demo

**What is the current behavior?**
```
➜  webpack-demo git:(master) ✗ yarn build
yarn run v1.22.5
warning package.json: No license field
$ webpack --progress --mode production --profile
assets by status 10.3 KiB [cached] 3 assets
runtime modules 5.29 KiB 7 modules
built modules 63 bytes [built]
  ./src/index.js 21 bytes [built] [code generated]
    48 ms (resolving: 35 ms, restoring: 0 ms, integration: 0 ms, building: 13 ms, storing: 0 ms, additional resolving: 16 ms)
  container entry 42 bytes [built] [code generated]
    3 ms (resolving: 0 ms, restoring: 0 ms, integration: 0 ms, building: 2 ms, storing: 1 ms)

ERROR in demo.js from Terser
Unexpected token: operator (-) [demo.js:1,11]
    at js_error (/Users/crazyair/Code/webpack-demo/node_modules/terser/dist/bundle.min.js:546:11)
    at croak (/Users/crazyair/Code/webpack-demo/node_modules/terser/dist/bundle.min.js:1264:9)
    at token_error (/Users/crazyair/Code/webpack-demo/node_modules/terser/dist/bundle.min.js:1272:9)
    at unexpected (/Users/crazyair/Code/webpack-demo/node_modules/terser/dist/bundle.min.js:1278:9)
    at semicolon (/Users/crazyair/Code/webpack-demo/node_modules/terser/dist/bundle.min.js:1309:56)
    at statement (/Users/crazyair/Code/webpack-demo/node_modules/terser/dist/bundle.min.js:1497:17)
    at _embed_tokens_wrapper (/Users/crazyair/Code/webpack-demo/node_modules/terser/dist/bundle.min.js:1322:26)
    at parse_toplevel (/Users/crazyair/Code/webpack-demo/node_modules/terser/dist/bundle.min.js:3439:23)
    at parse (/Users/crazyair/Code/webpack-demo/node_modules/terser/dist/bundle.min.js:3451:7)
    at minify (/Users/crazyair/Code/webpack-demo/node_modules/terser/dist/bundle.min.js:26237:38)

webpack 5.11.1 compiled with 1 error in 347 ms
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**If the current behavior is a bug, please provide the steps to reproduce.**

```
yarn
yarn build
```

**What is the expected behavior?**

**Other relevant information:**
webpack version:  latest
Node.js version: latest
Operating System: mac
Additional tools:

**Comment by sokra** [comment]
ModuleFederationPlugin.name must be a valid identifier when using the default `ModuleFederationPlugin.library`.

**Comment by alexander-akait** [comment]
duplicate https://github.com/webpack/webpack/issues/11923
