### ISSUE TITLE
webpack 5 has troubles to load vue-loader

### ISSUE THREAD

**Issue by tarkhil** [webpack/webpack#12374]
# Bug report

**What is the current behavior?**

With a very simple config

```
const { VueLoaderPlugin } = require('vue-loader')

module.exports = {
    entry: {
        caller: './src/caller.js',
        clients: './src/clients.js'
    },
    output: {
        filename: '[name].js',
        path: __dirname + '/public'
    },
    module: {
        rules: [
            {
                test: /\.vue$/,
                exclude: /node_modules/,
                loader: 'vue-loader'
            },
            {
                test: /\.js$/,
                exclude: /node_modules/,
                loader: 'babel-loader'
            },
            {
                test: /\.css$/i,
                use: ['style-loader', 'css-loader'],
            },
            { test: /\.(png|woff|woff2|eot|ttf|svg)$/, use: ['url-loader?limit=100000'] },
        ]
    },
    plugins: [
        new VueLoaderPlugin(),
    ],
};
```

I run webpack and it fails with

```
[webpack-cli] TypeError: The 'compilation' argument must be an instance of Compilation
    at Function.getCompilationHooks (/usr/home/tarkhil/client_base/node_modules/webpack/lib/NormalModule.js:171:10)
    at /usr/home/tarkhil/client_base/node_modules/vue-loader/lib/plugin-webpack5.js:36:70
    at Hook.eval [as call] (eval at create (/usr/local/lib/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:100:1)
    at Hook.CALL_DELEGATE [as _call] (/usr/local/lib/node_modules/webpack/node_modules/tapable/lib/Hook.js:14:14)
    at Compiler.newCompilation (/usr/local/lib/node_modules/webpack/lib/Compiler.js:943:26)
    at /usr/local/lib/node_modules/webpack/lib/Compiler.js:984:29
    at Hook.eval [as callAsync] (eval at create (/usr/local/lib/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/usr/local/lib/node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
    at Compiler.compile (/usr/local/lib/node_modules/webpack/lib/Compiler.js:979:28)
    at /usr/local/lib/node_modules/webpack/lib/Compiler.js:470:12
    at Compiler.readRecords (/usr/local/lib/node_modules/webpack/lib/Compiler.js:821:11)
    at /usr/local/lib/node_modules/webpack/lib/Compiler.js:467:11
    at Hook.eval [as callAsync] (eval at create (/usr/local/lib/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/usr/local/lib/node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
    at /usr/local/lib/node_modules/webpack/lib/Compiler.js:464:20
    at Hook.eval [as callAsync] (eval at create (/usr/local/lib/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
```

Tried vue-loader 14.2.4

```
[webpack-cli] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:278:15)
    at validateString (node:internal/validators:123:11)
    at Object.basename (node:path:1156:5)
    at new module.exports (/usr/home/tarkhil/client_base/node_modules/vue-loader/lib/loader.js:32:25)
    at Object.<anonymous> (/usr/home/tarkhil/client_base/webpack.config.js:33:9)
    at Module._compile (/usr/local/lib/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1131:10)
    at Module.load (node:internal/modules/cjs/loader:967:32)
    at Function.Module._load (node:internal/modules/cjs/loader:807:14)
    at Module.require (node:internal/modules/cjs/loader:991:19) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```
package.json is simple as well
```
{
  "name": "client_base",
  "version": "1.0.0",
  "description": "",
  "main": "caller-b.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "query-string": "^6.9.0",
    "vue": "^2.6.12",
    "vuejs-auto-complete": "^0.9.0"
  },
  "devDependencies": {
    "@babel/core": "^7.12.10",
    "babel-loader": "^8.2.2",
    "babel-preset-env": "^1.7.0",
    "css-loader": "^5.0.1",
    "html-webpack-plugin": "^4.5.1",
    "path": "^0.12.7",
    "postcss": "^8.2.3",
    "style-loader": "^2.0.0",
    "url-loader": "^4.1.1",
    "vue-loader": "^15.9.6",
    "vue-template-compiler": "^2.6.12",
    "webpack": "^5.11.1"
  }
}
```

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

Surely I was expecting webpack to run.

**Other relevant information:**
webpack version:  

webpack-cli 4.2.0

webpack 5.4.0

Node.js version: v15.3.0
Operating System: FreeBSD 12.1-RELEASE-p10
Additional tools:

**Comment by tarkhil** [comment]
Well, total removal of all globally installed node-modules and reinstallation of global webpack and webpack-cli saved. I can only wonder if it is possible without such a great purge, but just reinstalling of webpack did not help
