### ISSUE TITLE
webpackMissingModule on webpack reload

### ISSUE THREAD

**Issue by deslee** [webpack/webpack#1238]
I am using webpack to compile my backend (because my frontend uses reactjs, and I'm rendering my html on my server using react)

I'm trying to use an email module, and I've tried both nodemailer and sendgrid. When I require/import them in my server code, my server is able to successfully run at first, but when I make a change (and webpack reloads the code), I get this error:

`
desmond@deshome:~/Projects/deslee-rebirth/build$ node server.js 
/home/desmond/Projects/deslee-rebirth/build/server.js:15312
d module \"./../package.json\""); e.code = 'MODULE_NOT_FOUND'; throw e; }()));
                                                                     ^
Error: Cannot find module "./../package.json"
    at webpackMissingModule (/home/desmond/Projects/deslee-rebirth/build/server.js:15312:85)
    at Object.<anonymous> (/home/desmond/Projects/deslee-rebirth/build/server.js:15312:179)
    at __webpack_require__ (/home/desmond/Projects/deslee-rebirth/build/server.js:26:30)
    at Object.<anonymous> (/home/desmond/Projects/deslee-rebirth/build/server.js:15304:19)
    at __webpack_require__ (/home/desmond/Projects/deslee-rebirth/build/server.js:26:30)
    at Object.<anonymous> (/home/desmond/Projects/deslee-rebirth/build/server.js:15253:18)
    at __webpack_require__ (/home/desmond/Projects/deslee-rebirth/build/server.js:26:30)
    at Object.<anonymous> (/home/desmond/Projects/deslee-rebirth/build/server.js:126:24)
    at __webpack_require__ (/home/desmond/Projects/deslee-rebirth/build/server.js:26:30)
    at newObj (/home/desmond/Projects/deslee-rebirth/build/server.js:61:18)
`

And the error happens when I try to include an email related module.

**Comment by bebraw** [comment]
Can you set up a standalone test case so it's easier to study this?
