### ISSUE TITLE
webpack 5 terser issue

### ISSUE THREAD

**Issue by raravi** [webpack/webpack#12437]
# Bug report

**What is the current behavior?**
After migrating from 4.44.2 to 5.XX.X, my website on repo [amithraravi2.com](https://github.com/raravi/amithraravi2.com) doesn't build anymore.

I get the below output:

```
#!/bin/bash -eo pipefail
npm run webpack

> amith-raravi@2.0.0 webpack /home/circleci/repo
> webpack --mode production

assets by status 251 KiB [cached] 1 asset
runtime modules 780 bytes 4 modules
orphan modules 6.81 KiB [orphan] 1 module
cacheable modules 244 KiB
  ./js/_main.js + 1 modules 28.7 KiB [built] [code generated]
  ./js/vendor/jquery-3.3.1.min.js 130 KiB [built] [code generated]
  ./js/vendor/barba.min.js 20.1 KiB [built] [code generated]
  ./js/vendor/imagesloaded.pkgd.min.js 7.39 KiB [built] [code generated]
  ./js/vendor/modernizr-custom-3.6.0.js 38.1 KiB [built] [code generated]
  ./js/vendor/anime.min.js 17.3 KiB [built] [code generated]
  ./js/vendor/classie.js 1.91 KiB [built] [code generated]

ERROR in main.js from Terser
Unexpected token punc «,», expected punc «:» [main.js:1431,208]
    at js_error (/home/circleci/repo/node_modules/terser/dist/bundle.min.js:546:11)
    at croak (/home/circleci/repo/node_modules/terser/dist/bundle.min.js:1264:9)
    at token_error (/home/circleci/repo/node_modules/terser/dist/bundle.min.js:1272:9)
    at expect_token (/home/circleci/repo/node_modules/terser/dist/bundle.min.js:1285:9)
    at expect (/home/circleci/repo/node_modules/terser/dist/bundle.min.js:1288:36)
    at maybe_conditional (/home/circleci/repo/node_modules/terser/dist/bundle.min.js:3312:13)
    at maybe_assign (/home/circleci/repo/node_modules/terser/dist/bundle.min.js:3385:20)
    at expression (/home/circleci/repo/node_modules/terser/dist/bundle.min.js:3410:24)
    at params_or_seq_ (/home/circleci/repo/node_modules/terser/dist/bundle.min.js:2031:24)
    at expr_atom (/home/circleci/repo/node_modules/terser/dist/bundle.min.js:2437:29)

webpack 5.12.2 compiled with 1 error in 2108 ms
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! amith-raravi@2.0.0 webpack: `webpack --mode production`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the amith-raravi@2.0.0 webpack script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/circleci/.npm/_logs/2021-01-11T00_42_15_979Z-debug.log


Exited with code exit status 1
CircleCI received exit code 1
```

**If the current behavior is a bug, please provide the steps to reproduce.**
In the repo mentioned above, just upgrade webpack to 5.XX and try build with the command `npm run webpack`

**What is the expected behavior?**
The build command should complete successfully!

**Other relevant information:**
webpack version:  5.11.0
Node.js version: 13.13.0
Operating System: macOS Big Sur 11.1
Additional tools:

**Comment by akgupta0777** [comment]
@raravi  with webpack v5 or above versions come with terser-webpack-plugin. So before building it out you should need to instantiate the terser-webpack-plugin in your webpack.config.js configuration file. 
also in optimizations in your webpack config file

```
optimization: {
    minimize: true,
    minimizer: [new TerserPlugin()],
  }
```
you have to add `terserPlugin()` as a minimizer that minimizes your js files with terser.

Head towards this [page](https://webpack.js.org/plugins/terser-webpack-plugin/) for more info 

hope this helps

**Comment by akgupta0777** [comment]
It built successfully on my computer I cloned your repo

```

Abhay@DESKTOP-I04BUTC MINGW64 /e/Github/amithraravi2.com (master)
$ npm run webpack

> amith-raravi@2.0.0 webpack E:\Github\amithraravi2.com
> webpack --mode production

Hash: 3988b5dde1fddd59d93b
Version: webpack 4.46.0
Time: 5868ms
Built at: 17/01/2021 8:27:52 pm
  Asset     Size  Chunks             Chunk Names
main.js  136 KiB       0  [emitted]  main
Entrypoint main = main.js
[0] ./js/vendor/jquery-3.3.1.min.js 130 KiB {0} [built]       
[1] ./js/vendor/barba.min.js 20.1 KiB {0} [built]
[2] ./js/vendor/anime.min.js 17.3 KiB {0} [built]
[3] ./js/vendor/classie.js 1.91 KiB {0} [built]
[4] ./js/vendor/imagesloaded.pkgd.min.js 7.39 KiB {0} [built] 
[5] (webpack)/buildin/module.js 497 bytes {0} [built]
[6] ./js/vendor/modernizr-custom-3.6.0.js 38.4 KiB {0} [built]
[7] ./js/_main.js + 1 modules 29 KiB {0} [built]
    | ./js/_main.js 22.1 KiB [built]
    | ./js/vendor/AnimOnScroll.js 6.82 KiB [built]
```

**Comment by raravi** [comment]
@akgupta0777 Thank you, that worked!!
