### ISSUE TITLE
Spotted Deprecation warning while running javascriptParser.unittest.js

### ISSUE THREAD

**Issue by akgupta0777** [webpack/webpack#12460]
# Bug report
I am exploring webpack and tried running some tests.

**What is the current behavior?**
While running unit test it shows a very long deprecation warning 
```
(node:5440) DeprecationWarning: HookMap#tap(key,…) is deprecated. Use HookMap#for(key).tap(
d.
    at Object.<anonymous> (E:\Github\webpack\test\JavascriptParser.unittest.js:319:25)
    at Object.<anonymous> (E:\Github\webpack\test\JavascriptParser.unittest.js:319:25)
    at Object.asyncJestTest (E:\Github\webpack\node_modules\jest-jasmine2\build\jasmineAsyn
    at Object.<anonymous> (E:\Github\webpack\test\JavascriptParser.unittest.js:319:25)
    at Object.asyncJestTest (E:\Github\webpack\node_modules\jest-jasmine2\build\jasmineAsyncInstall.js:106:37)    at E:\Github\webpack\node_modules\jest-jasmine2\build\queueRunner.js:45:12
    at new Promise (<anonymous>)
    at mapper (E:\Github\webpack\node_modules\jest-jasmine2\build\queueRunner.js:28:19)
    at E:\Github\webpack\node_modules\jest-jasmine2\build\queueRunner.js:75:41
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

```

**If the current behavior is a bug, please provide the steps to reproduce.**
It is not a bug but we should avoid warnings. 
Run javascriptParser.unittest.js from `test` directory.

**What is the expected behavior?**
The test should PASS without any warnings.

**Other relevant information:**
webpack version:  5.13.0
Node.js version:  14.15.1
Operating System:  Windows 10 Home.
Additional tools: Windows Terminal

**Comment by alexander-akait** [comment]
Expected, because tests existing for testing deprecation API too
