### ISSUE TITLE
Pound symbol in project path breaks webpack

### ISSUE THREAD

**Issue by benderbr22** [webpack/webpack#12574]
# Bug report

**What is the current behavior?**

Running "yarn run dev" (or "npm run dev") on a Laravel project to build JS/CSS fails when the project path contains a # pound symbol. Removing the # pound symbol from the path allows it to run with no other changes.

**If the current behavior is a bug, please provide the steps to reproduce.**

Just add a # symbol to your project path and try to run webpack. Presumably it will fail for you too? This is the error;

```
PS E:\#test\repo> yarn run dev
yarn run v1.22.10
$ npm run development

> development
> mix

87% sealing module hashinginternal/crypto/hash.js:84
    throw new ERR_INVALID_ARG_TYPE(
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at Hash.update (internal/crypto/hash.js:84:11)
    at BulkUpdateDecorator.update (E:\#test\repo\node_modules\webpack\lib\util\createHash.js:51:14)
    at NormalModule.updateHash (E:\#test\repo\node_modules\webpack\lib\NormalModule.js:1120:8)
    at Compilation._createModuleHash (E:\#test\repo\node_modules\webpack\lib\Compilation.js:3085:10)
    at Compilation.createModuleHashes (E:\#test\repo\node_modules\webpack\lib\Compilation.js:3057:10)
    at E:\#test\repo\node_modules\webpack\lib\Compilation.js:2334:11
    at Hook.eval [as callAsync] (eval at create (E:\#test\repo\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:10:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (E:\#test\repo\node_modules\tapable\lib\Hook.js:18:14)
    at E:\#test\repo\node_modules\webpack\lib\Compilation.js:2294:36
    at Hook.eval [as callAsync] (eval at create (E:\#test\repo\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:10:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (E:\#test\repo\node_modules\tapable\lib\Hook.js:18:14)
    at Compilation.seal (E:\#test\repo\node_modules\webpack\lib\Compilation.js:2285:27)
    at E:\#test\repo\node_modules\webpack\lib\Compiler.js:1056:20
    at E:\#test\repo\node_modules\webpack\lib\Compilation.js:2104:4
    at eval (eval at create (E:\#test\repo\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:42:1)
    at E:\#test\repo\node_modules\webpack\lib\FlagDependencyExportsPlugin.js:332:11 {
  code: 'ERR_INVALID_ARG_TYPE'
}
npm ERR! code 1
npm ERR! path E:\#test\repo
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c webpack --progress --config=node_modules\\laravel-mix\\setup\\webpack.config.js

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\username\AppData\Local\npm-cache\_logs\2021-02-03T03_18_26_556Z-debug.log
npm ERR! code 1
npm ERR! path E:\#test\repo
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c mix

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\username\AppData\Local\npm-cache\_logs\2021-02-03T03_18_26_612Z-debug.log
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**What is the expected behavior?**

I assume that legal characters in path names should not fail, so having a # pound symbol in the project path should run the build without issue.

**Other relevant information:**
webpack version:  5.20.0
Node.js version: 14.15.4
Operating System: Windows 10
Additional tools: 

Here is my package.json

```
{
    "private": true,
    "scripts": {
        "dev": "npm run development",
        "development": "mix",
        "watch": "mix watch",
        "watch-poll": "mix watch -- --watch-options-poll=1000",
        "hot": "mix watch --hot",
        "prod": "npm run production",
        "production": "mix --production"
    },
    "devDependencies": {
        "autoprefixer": "^10.2.4",
        "axios": "^0.21",
        "laravel-mix": "^6.0.6",
        "lodash": "^4.17.19",
        "postcss": "^8.1.14",
        "postcss-import": "^14.0.0",
        "resolve-url-loader": "^3.1.2",
        "sass-loader": "^10.1.1",
        "tailwindcss": "^2.0.2",
        "vue": "^2.6.12",
        "vue-loader": "^15.9.5",
        "vue-template-compiler": "^2.6.12"
    },
    "dependencies": {
        "webpack": "^5.20.0"
    }
}
```

Here is my webpack.mix.js

```
const mix = require('laravel-mix');

mix.js('resources/js/app.js', 'public/js')
    .vue()
    .postCss('resources/css/app.css', 'public/css', [
        require('postcss-import'),
        require('tailwindcss')('tailwind.config.js'),
    ]);
```

**Comment by benderbr22** [comment]
Just noticed issue #12156, which seems similar but the error messages are different and I'm not having the issue of a space inserted in the path. Not sure if they are related or separate issues.

**Comment by alexander-akait** [comment]
@benderbr22 Can you provide minimum reproducible test repo

**Comment by benderbr22** [comment]
Well it happens for me on a default Laravel install. I don't have to do anything at all to make it happen, it doesn't even require any code or modifications to happen. Sequence of commands to reproduce in Windows 10, from a PowerShell;

```
e:
mkdir e:\#test
cd e:\#test
composer create-project laravel/laravel test
cd test
npm install
npm run dev
```

That's it. I then get the above error. No code changes done at all, nothing beyond the commands I typed above, just a plain default Laravel install. I can copy/paste the above commands one at a time in to a PowerShell and it's the same outcome every time. Then if I do this;

```
cd ..
cd ..
Rename-Item e:\#test e:\test
cd test
cd test
npm run dev
```

Now it runs fine. No difference at all except the renamed folder to remove the # pound symbol. I'll paste some other info from the e:\test\test folder in case it helps;

```
PS E:\test\test> node --version
v14.15.4
```

```
PS E:\test\test> npm ls -g
C:\Users\username\AppData\Roaming\npm
+-- npm@7.5.2
`-- yarn@1.22.10
```

```
PS E:\test\test> npm ls
test@ E:\test\test
+-- axios@0.21.1
+-- laravel-mix@6.0.11
+-- lodash@4.17.20
`-- postcss@8.2.4
```

```
PS E:\test\test> composer --version
Composer version 2.0.9 2021-01-27 16:09:27
```

```
PS E:\test\test> composer global show
Changed current directory to C:/Users/username/AppData/Roaming/Composer
```

```
PS E:\test\test> composer show
asm89/stack-cors                   v2.0.2  Cross-origin resource sharing library and stack middleware
brick/math                         0.9.2   Arbitrary-precision arithmetic library
dnoegel/php-xdg-base-dir           v0.1.1  implementation of xdg base directory specification for php
doctrine/inflector                 2.0.3   PHP Doctrine Inflector is a small library that can perform string manipulations with regard to upper/lowercase and singular/plural forms of words.
doctrine/instantiator              1.4.0   A small, lightweight utility to instantiate objects in PHP without invoking their constructors
doctrine/lexer                     1.2.1   PHP Doctrine Lexer parser library that can be used in Top-Down, Recursive Descent Parsers.
dragonmantank/cron-expression      v3.1.0  CRON for PHP: Calculate the next or previous run date and determine if a CRON expression is due
egulias/email-validator            2.1.25  A library for validating emails against several RFCs
facade/flare-client-php            1.3.7   Send PHP errors to Flare
facade/ignition                    2.5.10  A beautiful error page for Laravel applications.
facade/ignition-contracts          1.0.2   Solution contracts for Ignition
fakerphp/faker                     v1.13.0 Faker is a PHP library that generates fake data for you.
fideloper/proxy                    4.4.1   Set trusted proxies for Laravel
filp/whoops                        2.9.2   php error handling for cool kids
fruitcake/laravel-cors             v2.0.3  Adds CORS (Cross-Origin Resource Sharing) headers support in your Laravel application
graham-campbell/result-type        v1.0.1  An Implementation Of The Result Type
guzzlehttp/guzzle                  7.2.0   Guzzle is a PHP HTTP client library
guzzlehttp/promises                1.4.0   Guzzle promises library
guzzlehttp/psr7                    1.7.0   PSR-7 message implementation that also provides common utility methods
hamcrest/hamcrest-php              v2.0.1  This is the PHP port of Hamcrest Matchers
laravel/framework                  v8.26.1 The Laravel Framework.
laravel/sail                       v1.3.0  Docker files for running a basic Laravel application.
laravel/tinker                     v2.6.0  Powerful REPL for the Laravel framework.
league/commonmark                  1.5.7   Highly-extensible PHP Markdown parser which fully supports the CommonMark spec and Github-Flavored Markdown (GFM)
league/flysystem                   1.1.3   Filesystem abstraction: Many filesystems, one API.
league/mime-type-detection         1.7.0   Mime-type detection for Flysystem
mockery/mockery                    1.4.2   Mockery is a simple yet flexible PHP mock object framework
monolog/monolog                    2.2.0   Sends your logs to files, sockets, inboxes, databases and various web services
myclabs/deep-copy                  1.10.2  Create deep copies (clones) of your objects
nesbot/carbon                      2.44.0  An API extension for DateTime that supports 281 different languages.
nikic/php-parser                   v4.10.4 A PHP parser written in PHP
nunomaduro/collision               v5.3.0  Cli error handling for console/command-line PHP applications.
opis/closure                       3.6.1   A library that can be used to serialize closures (anonymous functions) and arbitrary objects.
phar-io/manifest                   2.0.1   Component for reading phar.io manifest information from a PHP Archive (PHAR)
phar-io/version                    3.0.4   Library for handling version information and constraints
phpdocumentor/reflection-common    2.2.0   Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock  5.2.2   With this component, a library can provide support for annotations via DocBlocks or otherwise retrieve information that is embedded in a DocBlock.
phpdocumentor/type-resolver        1.4.0   A PSR-5 based resolver of Class names, Types and Structural Element Names
phpoption/phpoption                1.7.5   Option Type for PHP
phpspec/prophecy                   1.12.2  Highly opinionated mocking framework for PHP 5.3+
phpunit/php-code-coverage          9.2.5   Library that provides collection, processing, and rendering functionality for PHP code coverage information.
phpunit/php-file-iterator          3.0.5   FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-invoker                3.1.1   Invoke callables with a timeout
phpunit/php-text-template          2.0.4   Simple template engine.
phpunit/php-timer                  5.0.3   Utility class for timing
phpunit/phpunit                    9.5.2   The PHP Unit Testing framework.
psr/container                      1.0.0   Common Container Interface (PHP FIG PSR-11)
psr/event-dispatcher               1.0.0   Standard interfaces for event handling.
psr/http-client                    1.0.1   Common interface for HTTP clients
psr/http-message                   1.0.1   Common interface for HTTP messages
psr/log                            1.1.3   Common interface for logging libraries
psr/simple-cache                   1.0.1   Common interfaces for simple caching
psy/psysh                          v0.10.6 An interactive shell for modern PHP.
ralouphie/getallheaders            3.0.3   A polyfill for getallheaders.
ramsey/collection                  1.1.3   A PHP 7.2+ library for representing and manipulating collections.
ramsey/uuid                        4.1.1   A PHP library for generating and working with universally unique identifiers (UUIDs).
sebastian/cli-parser               1.0.1   Library for parsing CLI options
sebastian/code-unit                1.0.8   Collection of value objects that represent the PHP code units
sebastian/code-unit-reverse-lookup 2.0.3   Looks up which function or method a line of code belongs to
sebastian/comparator               4.0.6   Provides the functionality to compare PHP values for equality
sebastian/complexity               2.0.2   Library for calculating the complexity of PHP code units
sebastian/diff                     4.0.4   Diff implementation
sebastian/environment              5.1.3   Provides functionality to handle HHVM/PHP environments
sebastian/exporter                 4.0.3   Provides the functionality to export PHP variables for visualization
sebastian/global-state             5.0.2   Snapshotting of global state
sebastian/lines-of-code            1.0.3   Library for counting the lines of code in PHP source code
sebastian/object-enumerator        4.0.4   Traverses array structures and object graphs to enumerate all referenced objects
sebastian/object-reflector         2.0.4   Allows reflection of object attributes, including inherited and non-public ones
sebastian/recursion-context        4.0.4   Provides functionality to recursively process PHP variables
sebastian/resource-operations      3.0.3   Provides a list of PHP built-in functions that operate on resources
sebastian/type                     2.3.1   Collection of value objects that represent the types of the PHP type system
sebastian/version                  3.0.2   Library that helps with managing the version number of Git-hosted PHP projects
swiftmailer/swiftmailer            v6.2.5  Swiftmailer, free feature-rich PHP mailer
symfony/console                    v5.2.3  Eases the creation of beautiful and testable command line interfaces
symfony/css-selector               v5.2.3  Converts CSS selectors to XPath expressions
symfony/deprecation-contracts      v2.2.0  A generic function and convention to trigger deprecation notices
symfony/error-handler              v5.2.3  Provides tools to manage errors and ease debugging PHP code
symfony/event-dispatcher           v5.2.3  Provides tools that allow your application components to communicate with each other by dispatching events and listening to them
symfony/event-dispatcher-contracts v2.2.0  Generic abstractions related to dispatching event
symfony/finder                     v5.2.3  Finds files and directories via an intuitive fluent interface
symfony/http-client-contracts      v2.3.1  Generic abstractions related to HTTP clients
symfony/http-foundation            v5.2.3  Defines an object-oriented layer for the HTTP specification
symfony/http-kernel                v5.2.3  Provides a structured process for converting a Request into a Response
symfony/mime                       v5.2.3  Allows manipulating MIME messages
symfony/polyfill-ctype             v1.22.0 Symfony polyfill for ctype functions
symfony/polyfill-iconv             v1.22.0 Symfony polyfill for the Iconv extension
symfony/polyfill-intl-grapheme     v1.22.0 Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-idn          v1.22.0 Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-intl-normalizer   v1.22.0 Symfony polyfill for intl's Normalizer class and related functions
symfony/polyfill-mbstring          v1.22.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php72             v1.22.0 Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/polyfill-php73             v1.22.0 Symfony polyfill backporting some PHP 7.3+ features to lower PHP versions
symfony/polyfill-php80             v1.22.0 Symfony polyfill backporting some PHP 8.0+ features to lower PHP versions
symfony/process                    v5.2.3  Executes commands in sub-processes
symfony/routing                    v5.2.3  Maps an HTTP request to a set of configuration variables
symfony/service-contracts          v2.2.0  Generic abstractions related to writing services
symfony/string                     v5.2.3  Provides an object-oriented API to strings and deals with bytes, UTF-8 code points and grapheme clusters in a unified way
symfony/translation                v5.2.3  Provides tools to internationalize your application
symfony/translation-contracts      v2.3.0  Generic abstractions related to translation
symfony/var-dumper                 v5.2.3  Provides mechanisms for walking through any arbitrary PHP variable
theseer/tokenizer                  1.2.0   A small library for converting tokenized PHP source code into XML and potentially other formats
tijsverkoyen/css-to-inline-styles  2.2.3   CssToInlineStyles is a class that enables you to convert HTML-pages/files into HTML-pages/files with inline styles. This is very useful when you're sending emails.
vlucas/phpdotenv                   v5.3.0  Loads environment variables from `.env` to `getenv()`, `$_ENV` and `$_SERVER` automagically.
voku/portable-ascii                1.5.6   Portable ASCII library - performance optimized (ascii) string functions for php.
webmozart/assert                   1.9.1   Assertions to validate method input/output with nice error messages.
```

**Comment by alexander-akait** [comment]
Without `#` all works fine?

**Comment by benderbr22** [comment]
Yes, in the example above I showed a series of command to rename the e:\#test folder to just e:\test, then run "npm run dev" again and it works. With the only difference that I renamed e:\#test to e:\test. After doing that it runs fine.

```
   Laravel Mix v6.0.11


✔ Compiled Successfully in 1085ms
┌──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬─────────┐
│                                                                                                                                                                                                                                             File │ Size    │
├──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼─────────┤
│                                                                                                                                                                                                                                       /js/app.js │ 596 KiB │
│                                                                                                                                                                                                                                      css/app.css │ 1 bytes │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴─────────┘
PS E:\test\test>
```

**Comment by alexander-akait** [comment]
Yep, bug, thanks

**Comment by alexander-akait** [comment]
Let's close in favor https://github.com/webpack/webpack/issues/12156 (I have changed title), yes, we have problems with `#`
