### ISSUE TITLE
The "path" argument must be of type string. Received type undefined

### ISSUE THREAD

**Issue by kikyous** [webpack/webpack#12616]
# Bug report

**What is the current behavior?**
when using persistent cache, webpack dev server fail to start
```
 HookWebpackError: The "path" argument must be of type string. Received type undefined
    at makeWebpackError (/Users/kikyous/PycharmProjects/lms/node_modules/webpack/lib/HookWebpackError.js:49:9)
    at /Users/kikyous/PycharmProjects/lms/node_modules/webpack/lib/Compilation.js:2383:12
    at eval (eval at create (/Users/kikyous/PycharmProjects/lms/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:12:1)
    at fn (/Users/kikyous/PycharmProjects/lms/node_modules/webpack/lib/Compilation.js:373:17)
    at Hook.eval [as callAsync] (eval at create (/Users/kikyous/PycharmProjects/lms/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/kikyous/PycharmProjects/lms/node_modules/tapable/lib/Hook.js:18:14)
    at cont (/Users/kikyous/PycharmProjects/lms/node_modules/webpack/lib/Compilation.js:2380:34)
    at /Users/kikyous/PycharmProjects/lms/node_modules/webpack/lib/Compilation.js:2426:10
    at /Users/kikyous/PycharmProjects/lms/node_modules/neo-async/async.js:2830:7
    at done (/Users/kikyous/PycharmProjects/lms/node_modules/neo-async/async.js:2865:11)
-- inner error --
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:112:11)
    at Object.dirname (path.js:1128:5)
    at WebpackAssetsManifest.handleProcessAssetsAnalyse (/Users/kikyous/PycharmProjects/lms/node_modules/webpack-assets-manifest/src/WebpackAssetsManifest.js:496:31)
    at fn (/Users/kikyous/PycharmProjects/lms/node_modules/webpack/lib/Compilation.js:371:10)
    at Hook.eval [as callAsync] (eval at create (/Users/kikyous/PycharmProjects/lms/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/kikyous/PycharmProjects/lms/node_modules/tapable/lib/Hook.js:18:14)
    at cont (/Users/kikyous/PycharmProjects/lms/node_modules/webpack/lib/Compilation.js:2380:34)
    at /Users/kikyous/PycharmProjects/lms/node_modules/webpack/lib/Compilation.js:2426:10
    at /Users/kikyous/PycharmProjects/lms/node_modules/neo-async/async.js:2830:7
    at done (/Users/kikyous/PycharmProjects/lms/node_modules/neo-async/async.js:2865:11)
✖ ｢wdm｣: caused by plugins in Compilation.hooks.processAssets
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:112:11)
    at Object.dirname (path.js:1128:5)
    at WebpackAssetsManifest.handleProcessAssetsAnalyse (/Users/kikyous/PycharmProjects/lms/node_modules/webpack-assets-manifest/src/WebpackAssetsManifest.js:496:31)
    at fn (/Users/kikyous/PycharmProjects/lms/node_modules/webpack/lib/Compilation.js:371:10)
    at Hook.eval [as callAsync] (eval at create (/Users/kikyous/PycharmProjects/lms/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/kikyous/PycharmProjects/lms/node_modules/tapable/lib/Hook.js:18:14)
    at cont (/Users/kikyous/PycharmProjects/lms/node_modules/webpack/lib/Compilation.js:2380:34)
    at /Users/kikyous/PycharmProjects/lms/node_modules/webpack/lib/Compilation.js:2426:10
    at /Users/kikyous/PycharmProjects/lms/node_modules/neo-async/async.js:2830:7
    at done (/Users/kikyous/PycharmProjects/lms/node_modules/neo-async/async.js:2865:11)
```
**If the current behavior is a bug, please provide the steps to reproduce.**
set [path] in assetModuleFilename, and enable persistent cache, start webpack to build cache, then restart webpack
```json
    output: {
      filename: "[name].js",
      path: path.resolve(__dirname, "static"),
      assetModuleFilename: '[path][name].[ext][query]',
      publicPath: "/static/",
    },
```

**What is the expected behavior?**
no error

**Other relevant information:**
webpack version:  5.21.1
Node.js version: v12.14.1
Operating System: mac os
Additional tools:

**Comment by alexander-akait** [comment]
Bug in `webpack-assets-manifest` plugin, we can't fix it here, sorry
