### ISSUE TITLE
loaders: undefined is not a function

### ISSUE THREAD

**Issue by haf** [webpack/webpack#1266]
Webpack should not crash with NullRefException, it should validate input and provide proper error messages.

```
➜  cmdui git:(master) ✗ node node_modules/karma/bin/karma start karma.conf.js
Hash: 8344a6c0a9b3c44a5636
Version: webpack 1.10.1
Time: 9ms
webpack: bundle is now VALID.
webpack: bundle is now INVALID.
19 07 2015 15:31:31.957:ERROR [karma]: [TypeError: undefined is not a function]
TypeError: undefined is not a function
  at /Users/h/dev/logibit/cmdui/node_modules/webpack/node_modules/webpack-core/lib/LoadersList.js:81:5
  at Array.reduce (native)
  at LoadersList.match (/Users/h/dev/logibit/cmdui/node_modules/webpack/node_modules/webpack-core/lib/LoadersList.js:80:27)
  at Tapable.<anonymous> (/Users/h/dev/logibit/cmdui/node_modules/webpack/lib/NormalModuleFactory.js:109:65)
  at /Users/h/dev/logibit/cmdui/node_modules/async/lib/async.js:251:17
  at done (/Users/h/dev/logibit/cmdui/node_modules/async/lib/async.js:132:19)
  at /Users/h/dev/logibit/cmdui/node_modules/async/lib/async.js:32:16
  at /Users/h/dev/logibit/cmdui/node_modules/async/lib/async.js:248:21
  at /Users/h/dev/logibit/cmdui/node_modules/async/lib/async.js:572:34
  at /Users/h/dev/logibit/cmdui/node_modules/webpack/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:29:4
  at onResolved (/Users/h/dev/logibit/cmdui/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:39:10)
  at /Users/h/dev/logibit/cmdui/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:123:21
  at /Users/h/dev/logibit/cmdui/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:191:15
  at applyPluginsParallelBailResult.createInnerCallback.log (/Users/h/dev/logibit/cmdui/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:104:30)
  at loggingCallbackWrapper (/Users/h/dev/logibit/cmdui/node_modules/webpack/node_modules/enhanced-resolve/lib/createInnerCallback.js:21:19)
  at /Users/h/dev/logibit/cmdui/node_modules/webpack/node_modules/tapable/lib/Tapable.js:134:6
  at innerCallback (/Users/h/dev/logibit/cmdui/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:90:37)
  at loggingCallbackWrapper (/Users/h/dev/logibit/cmdui/node_modules/webpack/node_modules/enhanced-resolve/lib/createInnerCallback.js:21:19)
  at /Users/h/dev/logibit/cmdui/node_modules/webpack/node_modules/tapable/lib/Tapable.js:134:6
  at Tapable.<anonymous> (/Users/h/dev/logibit/cmdui/node_modules/webpack/node_modules/enhanced-resolve/lib/DirectoryDescriptionFileFieldAliasPlugin.js:101:26)
  at /Users/h/dev/logibit/cmdui/node_modules/webpack/node_modules/enhanced-resolve/lib/DirectoryDescriptionFileFieldAliasPlugin.js:52:26
  at Storage.finished (/Users/h/dev/logibit/cmdui/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
  at evalmachine.<anonymous>:334:14
  at /Users/h/dev/logibit/cmdui/node_modules/webpack/node_modules/enhanced-resolve/node_modules/graceful-fs/graceful-fs.js:102:5
  at FSReqWrap.oncomplete (evalmachine.<anonymous>:95:15)

```

Karma.conf.js:

```
➜  cmdui git:(master) ✗ cat karma.conf.js
var webpack = require('webpack');

module.exports = function(config) {
  config.set({
    basePath: '',
    frameworks: ['mocha'],
    files: [
      'tests/index.js',
    ],
    exclude: [
      '**/*.swp'
    ],
    preprocessors: {
      'tests/*': ['webpack']
    },
    webpack: {
      resolve: {
        extensions: ["", ".js", ".coffee"]
      },
      module: {
        loaders: [
          {
            test: /\.js$/,
            exclude: /node_modules/,
            loaders: 'babel-loader'
          }
          /*{ test: /\.coffee$/,
            exclude: /node_modules/,
            loaders: 'coffee-loader'
          }*/
        ]
      }
    },
    webpackMiddleware: {
      stats: { colors: true }
    },
    reporters: ['progress'],
    port: 9876,
    colors: true,
    logLevel: config.LOG_INFO,
    autoWatch: true,
    browsers: ['Chrome'], //browsers: ['Chrome', 'Firefox', 'PhantomJS'],
    singleRun: false,
    captureTimeout: 60000,
    plugins: [
      require("karma-mocha"),
      require("karma-spec-reporter"),
      require("karma-chrome-launcher"),
      require("karma-webpack"),
    ]
  })
}
```

packages.json:

```
  "dependencies": {
    "react": "^0.13.3"
  },
  "devDependencies": {
    "async": "^0.9.0",
    "coffee-loader": "^0.7.2",
    "coffee-script": "^1.9.3",
    "karma": ">=0.13.2 < 1",
    "karma-chrome-launcher": "~0.2.0",
    "karma-mocha": "~0.2.0",
    "karma-spec-reporter": "~0.0.20",
    "karma-webpack": "git+https://github.com/Dignifiedquire/karma-webpack.git#29fb1d801158f29cb0eb784edff69356705a7b74",
    "loader-utils": "^0.2.11",
    "lodash": "^3.10.0",
    "source-map": "^0.4.4",
    "webpack": "^1.10.1",
    "webpack-dev-middleware": "^1.2.0"
  },
```

**Comment by haf** [comment]
I think this stems from using 'babel-loader'.

**Comment by bebraw** [comment]
@haf Can you still see the issue?

**Comment by haf** [comment]
No, I worked around it a while back by removing something duplicate.
