### ISSUE TITLE
PostCSS Loader (BrowserslistError) - WIndows

### ISSUE THREAD

**Issue by mrrosoff** [webpack/webpack#12702]
# Bug report

**What is the current behavior?**

When attempting to compile project on Windows, Webpack throws a BrowserslistError. This does not occur on MacOS or Linux. The error is derived from `postcss`, but has appeared in other packages as well.

Here is the full error log.

```
ERROR in ./static/styles/global.scss (./node_modules/css-loader/dist/cjs.js!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[2].use[2]!./node_modules/sass-loader/dist/cjs.js!./static/styles/global.scss)
Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
BrowserslistError: Unknown browser query `basedir=$(dirname "$(echo "$0" | sed -e 's`. Maybe you are using old Browserslist or made typo in query.
    at unknownQuery (D:\a\Kings-Corner\Kings-Corner\client\node_modules\browserslist\index.js:285:10)
    at D:\a\Kings-Corner\Kings-Corner\client\node_modules\browserslist\index.js:372:11
    at Array.reduce (<anonymous>)
    at resolve (D:\a\Kings-Corner\Kings-Corner\client\node_modules\browserslist\index.js:318:18)
    at browserslist (D:\a\Kings-Corner\Kings-Corner\client\node_modules\browserslist\index.js:444:21)
    at D:\a\Kings-Corner\Kings-Corner\client\node_modules\postcss-preset-env\index.js:434:29
    at creator (D:\a\Kings-Corner\Kings-Corner\client\node_modules\postcss-preset-env\node_modules\postcss\lib\postcss.js:133:35)
    at Function.get (D:\a\Kings-Corner\Kings-Corner\client\node_modules\postcss-preset-env\node_modules\postcss\lib\postcss.js:142:27)
    at Processor.normalize (D:\a\Kings-Corner\Kings-Corner\client\node_modules\postcss\lib\processor.js:39:13)
    at new Processor (D:\a\Kings-Corner\Kings-Corner\client\node_modules\postcss\lib\processor.js:9:25)
 @ ./static/styles/global.scss 2:12-209 9:17-24 13:7-21 45:20-34 49:6-59:7 50:38-52 56:26-40 58:21-28 68:15-29 47:4-60:5
 @ ./index.js 3:0-55
```

**If the current behavior is a bug, please provide the steps to reproduce.**

The error can be found in [this](https://github.com/M3tanym/Kings-Corner) repository. Building application fails. `npm run buildElectron`. My guess is Browserslist has not updated their code to be Webpack v5 compliant, but I don't see others with this issue, or any issues in the postcss repo, so I am creating issues in both locations.

**What is the expected behavior?**

Module resolution completes and postcss loader is properly used to traverse `.css` files.

**Other relevant information:**
webpack version:  5.22.0
Node.js version: 14.15.4
Operating System: Windows
Additional tools: None

**Comment by alexander-akait** [comment]
Won't fix in webpack, please look at stack trace, problem from `postcss-preset-env` and `browserslist`, please report the problem in these repos

**Comment by mrrosoff** [comment]
FYI. This issue just disappeared without a trace. It could be related to a Windows update. I was building on GitHub Actions so not sure. 🤷
