### ISSUE TITLE
Error: Rule can only have one resource source

### ISSUE THREAD

**Issue by name-used** [webpack/webpack#12782]
The Error Messages Are As Follow:

Error: Rule can only have one resource source (provided resource and test + include + exclude) in {
  "exclude": [
    null
  ],
  "use": [
    {
      "loader": "C:\\Users\\jizhe\\Desktop\\article-html\\node_modules\\@vue\\cli-plugin-babel\\node_modules\\cache-loader\\dist\\cjs.js",
      "options": {
        "cacheDirectory": "C:\\Users\\jizhe\\Desktop\\article-html\\node_modules\\.cache\\babel-loader",
        "cacheIdentifier": "3602f06b"
      },
      "ident": "clonedRuleSet-38.use[0]"
    },
    {
      "loader": "C:\\Users\\jizhe\\Desktop\\article-html\\node_modules\\babel-loader\\lib\\index.js",
      "options": "undefined",
      "ident": "undefined"
    }
  ]
}
    at checkResourceSource (C:\Users\jizhe\Desktop\article-html\node_modules\@vue\cli-service\node_modules\webpack\lib\RuleSet.js:167:11)
    at Function.normalizeRule (C:\Users\jizhe\Desktop\article-html\node_modules\@vue\cli-service\node_modules\webpack\lib\RuleSet.js:198:4)
    at C:\Users\jizhe\Desktop\article-html\node_modules\@vue\cli-service\node_modules\webpack\lib\RuleSet.js:110:20
    at Array.map (<anonymous>)
    at Function.normalizeRules (C:\Users\jizhe\Desktop\article-html\node_modules\@vue\cli-service\node_modules\webpack\lib\RuleSet.js:109:17)
    at new RuleSet (C:\Users\jizhe\Desktop\article-html\node_modules\@vue\cli-service\node_modules\webpack\lib\RuleSet.js:104:24)
    at new NormalModuleFactory (C:\Users\jizhe\Desktop\article-html\node_modules\@vue\cli-service\node_modules\webpack\lib\NormalModuleFactory.js:115:18)
    at Compiler.createNormalModuleFactory (C:\Users\jizhe\Desktop\article-html\node_modules\@vue\cli-service\node_modules\webpack\lib\Compiler.js:636:31)
    at Compiler.newCompilationParams (C:\Users\jizhe\Desktop\article-html\node_modules\@vue\cli-service\node_modules\webpack\lib\Compiler.js:653:30)
    at Compiler.compile (C:\Users\jizhe\Desktop\article-html\node_modules\@vue\cli-service\node_modules\webpack\lib\Compiler.js:661:23)
    at C:\Users\jizhe\Desktop\article-html\node_modules\@vue\cli-service\node_modules\webpack\lib\Watching.js:77:18
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\jizhe\Desktop\article-html\node_modules\@vue\cli-service\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:24:1)
    at AsyncSeriesHook.lazyCompileHook (C:\Users\jizhe\Desktop\article-html\node_modules\@vue\cli-service\node_modules\tapable\lib\Hook.js:154:20)
    at Watching._go (C:\Users\jizhe\Desktop\article-html\node_modules\@vue\cli-service\node_modules\webpack\lib\Watching.js:41:32)
    at C:\Users\jizhe\Desktop\article-html\node_modules\@vue\cli-service\node_modules\webpack\lib\Watching.js:33:9
    at Compiler.readRecords (C:\Users\jizhe\Desktop\article-html\node_modules\@vue\cli-service\node_modules\webpack\lib\Compiler.js:529:11)
npm ERR! code 1
npm ERR! path C:\Users\jizhe\Desktop\article-html
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c vue-cli-service serve

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jizhe\AppData\Local\npm-cache\_logs\2021-02-25T15_35_16_105Z-debug.log

But I cant find the code where I used them.

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

Please ask this in `vue-cli` repo
