### ISSUE TITLE
TerserError while building using DefinePlugin

### ISSUE THREAD

**Issue by reynard80** [webpack/webpack#12857]
# Bug report

**What is the current behavior?**
When trying to inject variables with the DefinePlugin, I get a TerserPlugin punc error. When leaving out the DefinePlugin, the build is successful.

**If the current behavior is a bug, please provide the steps to reproduce.**
Try to build with the following command:
` build:prod: webpack --env prod --progress`

With webpack.config.js:
`            

```
...
new webpack.DefinePlugin({
    __APPLICATION_ROOT__: './consultant/',
    __API_URL__: './api',
}),
...
```

Gets me:

```
99% done plugins clean-webpack-pluginclean-webpack-plugin: pausing due to webpack errors
assets by status 25.4 KiB [cached] 3 assets
modules by path ./src/typescript/base/*.ts 10.1 KiB 6 modules
modules by path ./src/typescript/*.ts 1.95 KiB
  ./src/typescript/app.ts 1.71 KiB [built] [code generated]
  ./src/typescript/config.ts 245 bytes [built] [code generated]

....
ERROR in app.bundle.js from Terser
Unexpected token: punc (.) [app.bundle.js:363,18]
    at js_error (F:\xxxxxx-extranet\node_modules\terser\dist\bundle.min.js:548:11)
    at croak (F:\xxxxxx-extranet\node_modules\terser\dist\bundle.min.js:1272:9)
    at token_error (F:\xxxxxx-extranet\node_modules\terser\dist\bundle.min.js:1280:9)
    at unexpected (F:\xxxxxx-extranet\node_modules\terser\dist\bundle.min.js:1286:9)
    at expr_atom (F:\xxxxxx-extranet\node_modules\terser\dist\bundle.min.js:2491:25)
    at maybe_unary (F:\xxxxxx-extranet\node_modules\terser\dist\bundle.min.js:3299:19)
    at expr_ops (F:\xxxxxx-extranet\node_modules\terser\dist\bundle.min.js:3350:24)
    at maybe_conditional (F:\xxxxxx-extranet\node_modules\terser\dist\bundle.min.js:3355:20)
    at maybe_assign (F:\xxxxxx-extranet\node_modules\terser\dist\bundle.min.js:3432:20)
    at maybe_assign (F:\xxxxxx-extranet\node_modules\terser\dist\bundle.min.js:3443:32)
```

Leaving out the DefinePlugin results in a successful build.

**What is the expected behavior?**
Using the DefinePlugin should result in a successful build.

**Other relevant information:**
webpack version:  5.24.4
Node.js version: 14.16.0
Operating System: Windows 10
Additional tools:

**Comment by alexander-akait** [comment]
Please add `JSON.stringify` to `__APPLICATION_ROOT__` and `__API_URL__`, `DefinePlugin` doesn't protect from broken code

**Comment by alexander-akait** [comment]
```
new webpack.DefinePlugin({
    __APPLICATION_ROOT__: JSON.stringofy('./consultant/'),
    __API_URL__: JSON.stringofy('./api')
}),
```

**Comment by reynard80** [comment]
Thanks!
