### ISSUE TITLE
"parser.isAsiPosition is not a function" build error when using DefinePlugin.

### ISSUE THREAD

**Issue by biziosan** [webpack/webpack#12858]
# Bug report

**What is the current behavior?**
I inject a static variable with DefinePlugin:

```
const pkg = require('../../package.json');

cfg.plugins.push(
    new DefinePlugin({
        __STATIC_VAR__: JSON.stringify(pkg.version),
    })
);
```

With Webpack 4.46.0, I usually used the new variable in this way:

```
declare const __STATIC_VAR__: string;
console.log(__STATIC_VAR__);
```

However, building with Webpack 5.24.4 I get the following build error:

```
Module parse failed: parser.isAsiPosition is not a function
File was processed with these loaders:
 * ./node_modules/@angular-builders/custom-webpack/node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js
 * ./node_modules/@angular-builders/custom-webpack/node_modules/@ngtools/webpack/src/ivy/index.js
You may need an additional loader to handle the result of these loaders.
TypeError: parser.isAsiPosition is not a function
    at /home/eyeris/runtime/dev_ws/insight/node_modules/webpack/lib/DefinePlugin.js:233:18
    at SyncBailHook.eval (eval at create (/home/eyeris/runtime/dev_ws/insight/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:16)
    at SyncBailHook.lazyCompileHook (/home/eyeris/runtime/dev_ws/insight/node_modules/tapable/lib/Hook.js:154:20)
    at Parser.walkIdentifier (/home/eyeris/runtime/dev_ws/insight/node_modules/@angular-builders/custom-webpack/node_modules/webpack/lib/Parser.js:1986:25)
    at Parser.walkExpression (/home/eyeris/runtime/dev_ws/insight/node_modules/@angular-builders/custom-webpack/node_modules/webpack/lib/Parser.js:1604:10)
    at Parser.walkExpressions (/home/eyeris/runtime/dev_ws/insight/node_modules/@angular-builders/custom-webpack/node_modules/webpack/lib/Parser.js:1569:10)
    at Parser.walkCallExpression (/home/eyeris/runtime/dev_ws/insight/node_modules/@angular-builders/custom-webpack/node_modules/webpack/lib/Parser.js:1949:35)
    at Parser.walkExpression (/home/eyeris/runtime/dev_ws/insight/node_modules/@angular-builders/custom-webpack/node_modules/webpack/lib/Parser.js:1592:10)
    at Parser.walkExpressionStatement (/home/eyeris/runtime/dev_ws/insight/node_modules/@angular-builders/custom-webpack/node_modules/webpack/lib/Parser.js:1022:8)
    at Parser.walkStatement (/home/eyeris/runtime/dev_ws/insight/node_modules/@angular-builders/custom-webpack/node_modules/webpack/lib/Parser.js:964:10)
    at Parser.walkStatements (/home/eyeris/runtime/dev_ws/insight/node_modules/@angular-builders/custom-webpack/node_modules/webpack/lib/Parser.js:868:9)
    at /home/eyeris/runtime/dev_ws/insight/node_modules/@angular-builders/custom-webpack/node_modules/webpack/lib/Parser.js:1017:9
    at Parser.inBlockScope (/home/eyeris/runtime/dev_ws/insight/node_modules/@angular-builders/custom-webpack/node_modules/webpack/lib/Parser.js:2060:3)
    at Parser.walkBlockStatement (/home/eyeris/runtime/dev_ws/insight/node_modules/@angular-builders/custom-webpack/node_modules/webpack/lib/Parser.js:1014:8)
    at Parser.walkStatement (/home/eyeris/runtime/dev_ws/insight/node_modules/@angular-builders/custom-webpack/node_modules/webpack/lib/Parser.js:949:10)
    at /home/eyeris/runtime/dev_ws/insight/node_modules/@angular-builders/custom-webpack/node_modules/webpack/lib/Parser.js:1702:10
```

**If the current behavior is a bug, please provide the steps to reproduce.**

1.  Add a DefinePlugin: 

```
    cfg.plugins.push(
        new DefinePlugin({
            __STATIC_VAR__: JSON.stringify("test string"),
        })
    );
```

2. In any TS file:

```
declare const __STATIC_VAR__: string;
console.log(__STATIC_VAR__);
```

**What is the expected behavior?**
With Webpack 4.46.0, I was able to build and use the injected variable.

**Other relevant information:**
webpack version:  5.24.4
Node.js version: 14.16.0
Operating System: Linux Ubuntu 20.4
Additional tools: Angular custom-webpack build.

**Comment by alexander-akait** [comment]
Please open an issue in `@angular-devkit`/`@ngtools` repo, can't reproduce:
```
asset index.js 214 bytes [emitted] (name: main)
./src/index.ts 43 bytes [built] [code generated]
webpack 5.24.4 compiled successfully in 962 ms
Done in 1.74s.
```

**bundle/index.js**

```js
/******/ (() => { // webpackBootstrap
/******/ 	"use strict";
var __webpack_exports__ = {};
/*!**********************!*\
  !*** ./src/index.ts ***!
  \**********************/

console.log("1.0.0");

/******/ })()
;
```

or please create reproducible test repo and I will investigate it, if I found bug on webpack side I will reopen

Also maybe you have two version of `webpack`, please run `npm ls wepback`
