### ISSUE TITLE
Terser fails on dynamic imports

### ISSUE THREAD

**Issue by Neunerlei** [webpack/webpack#12865]
# Bug report

Hello there, it seems like webpack 5 / terser has an issue with dynamic imports(). 

**What is the current behavior?**

Every time I try to let webpack create a production build, it fails with an error like:

```
ERROR in 581.bundle.js from Terser
Unexpected token: punc (:) [581.bundle.js:3,9]
    at js_error (W:\dev\labor-digital\bits\demo\node_modules\terser\dist\bundle.min.js:548:11)
    at croak (W:\dev\labor-digital\bits\demo\node_modules\terser\dist\bundle.min.js:1272:9)
    at token_error (W:\dev\labor-digital\bits\demo\node_modules\terser\dist\bundle.min.js:1280:9)
    at unexpected (W:\dev\labor-digital\bits\demo\node_modules\terser\dist\bundle.min.js:1286:9)
    at semicolon (W:\dev\labor-digital\bits\demo\node_modules\terser\dist\bundle.min.js:1324:56)
    at simple_statement (W:\dev\labor-digital\bits\demo\node_modules\terser\dist\bundle.min.js:1581:73)
    at statement (W:\dev\labor-digital\bits\demo\node_modules\terser\dist\bundle.min.js:1375:20)
    at _embed_tokens_wrapper (W:\dev\labor-digital\bits\demo\node_modules\terser\dist\bundle.min.js:1337:26)
    at block_ (W:\dev\labor-digital\bits\demo\node_modules\terser\dist\bundle.min.js:2170:20)
    at statement (W:\dev\labor-digital\bits\demo\node_modules\terser\dist\bundle.min.js:1401:29
```

**If the current behavior is a bug, please provide the steps to reproduce.**

package.json
```
{
	"name": "@labor-digital/broken",
	"version": "1.0.0",
	"scripts": {
		"build": "npx webpack",
		"watch": "npx webpack --config ./webpack.watch.js"
	},
	"license": "Apache-2.0",
	"devDependencies": {
		"webpack-merge": "^5.7.3",
		"webpack-cli": "4.5.0",
		"webpack": "5.24.2"
	}
}
```

webpack.config.json
```
module.exports = {
    mode: 'production',
    entry: './src/main.js',
    target: 'es5',
    output: {
        filename: 'bundle.js',
        path: path.resolve(__dirname, 'dist')
    },
};
```

webpack.watch.js
```
const {merge} = require('webpack-merge');
const common = require('./webpack.common.js');

module.exports = merge(common, {
    mode: 'development',
    watch: true
});
```

main.js
`import('./Test/A');`

Test/A.js
```
export class A{}
```

If I run "npm run watch" everything works as expected. The dynamic import works, too. If I run "npm run build" the build fails and I get the error mentioned above. I tried to narrow it down and removed all loaders and project code until I got this, minimal setup. 

I think the issue is somewhere in the generated code of the import chunk:
```
{

/***/ "./src/Test/A.js": // <<<---  terser seems to not expect this colon here.
/*!***********************!*\
  !*** ./src/Test/A.js ***!
  \***********************/
/***/ (function(__unused_webpack_module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
```

**What is the expected behavior?**

It should work as it did with webpack 4 🙈 

**Other relevant information:**
webpack version: 5.24.2
Node.js version: 14.5.0
Operating System: Windows 10pro 1909
Additional tools: npm 6.14.6

**Comment by sokra** [comment]
Try `target: ['web', 'es5']`

**Comment by alexander-akait** [comment]
Answer above, we should set `web` target by default when `platform` target doesn't exists, i.e. `web`/`browser`/`webworker`/`node`/`elector`/`nwjs`

**Comment by alexander-akait** [comment]
Oh, not we can't , because `es5` not provide platform, please use `target: ['web', 'es5']`
