### ISSUE TITLE
Regression: Lazy compilation broken after v5.26.0

### ISSUE THREAD

**Issue by apostolos** [webpack/webpack#12941]
# Bug report

**What is the current behavior?**

When enabling lazy compilation webpack crashes when it first tries to compile a lazy import.

```bash
/███/██████/node_modules/webpack/lib/NormalModule.js:1049
[0]             return this.generator.getTypes(this);
[0]                                   ^
[0]
[0] TypeError: Cannot read property 'getTypes' of undefined
[0]     at NormalModule.getSourceTypes (/███/██████/node_modules/webpack/lib/NormalModule.js:1049:25)
[0]     at addModuleToChunksInfoMap (/███/██████/node_modules/webpack/lib/optimize/SplitChunksPlugin.js:1119:34)
[0]     at /███/██████/node_modules/webpack/lib/optimize/SplitChunksPlugin.js:1193:9
[0]     at Hook.eval [as call] (eval at create (/███/██████/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:13:16)
[0]     at Hook.CALL_DELEGATE [as _call] (/███/██████/node_modules/tapable/lib/Hook.js:14:14)
[0]     at Compilation.seal (/███/██████/node_modules/webpack/lib/Compilation.js:2292:36)
[0]     at /███/██████/node_modules/webpack/lib/Compiler.js:1078:20
[0]     at /███/██████/node_modules/webpack/lib/Compilation.js:2116:4
[0]     at Hook.eval [as callAsync] (eval at create (/███/██████/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:24:1)
[0]     at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/███/██████/node_modules/tapable/lib/Hook.js:18:14)
[0] npm ERR! code 1
[0] npm ERR! path /███/██████/
[0] npm ERR! command failed
[0] npm ERR! command sh -c webpack serve
```

The client side error returned is:

```
Error: Problem communicating active modules to the server: undefined undefined:undefined:undefined undefined
    at ██/████.js:3570:6
    at Set.forEach (<anonymous>)
    at EventSource.activeEventSource.onerror (██/████..js:3568:18)
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Enable lazy compilation in latest webpack version and do a dynamic module `import()`

**What is the expected behavior?**

Webpack should not crash

**Other relevant information:**
webpack version:  v5.27.1
Node.js version: v15.x
Operating System: Linux

**Comment by chenxsan** [comment]
Seems I can reproduce it with webpack 5.26.3, here's how:

1. clone `https://github.com/webpack/webpack.js.org`
2. run `yarn` to install
3. run `yarn start` to start the dev server
4. now open `localhost:3000` in browser and wait
5. we'll soon see this error under terminal:

    ```bash
    (node:4189) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'getTypes' of undefined
        at NormalModule.getSourceTypes (/Users/sam/Documents/githubRepos/webpack.js.org/node_modules/webpack/lib/NormalModule.js:1024:25)
        at addModuleToChunksInfoMap (/Users/sam/Documents/githubRepos/webpack.js.org/node_modules/webpack/lib/optimize/SplitChunksPlugin.js:1119:34)
        at /Users/sam/Documents/githubRepos/webpack.js.org/node_modules/webpack/lib/optimize/SplitChunksPlugin.js:1193:9
        at Hook.eval [as call] (eval at create (/Users/sam/Documents/githubRepos/webpack.js.org/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:39:16)
        at Hook.CALL_DELEGATE [as _call] (/Users/sam/Documents/githubRepos/webpack.js.org/node_modules/tapable/lib/Hook.js:14:14)
        at Compilation.seal (/Users/sam/Documents/githubRepos/webpack.js.org/node_modules/webpack/lib/Compilation.js:2292:36)
        at /Users/sam/Documents/githubRepos/webpack.js.org/node_modules/webpack/lib/Compiler.js:1078:20
        at /Users/sam/Documents/githubRepos/webpack.js.org/node_modules/webpack/lib/Compilation.js:2116:4
        at eval (eval at create (/Users/sam/Documents/githubRepos/webpack.js.org/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:42:1)
        at /Users/sam/Documents/githubRepos/webpack.js.org/node_modules/webpack/lib/FlagDependencyExportsPlugin.js:343:11
    ```
