### ISSUE TITLE
Throw error if accidentally using webpack.config.json instead of webpack.config.js?

### ISSUE THREAD

**Issue by simondlr** [webpack/webpack#1297]
Spent aeons debugging the following error when running webpack:

```
module.js:485
    throw err;
          ^
SyntaxError: /Users/simon/code/ethereum/js/ether_reactor/example/webpack.config.json: Unexpected token m
    at Object.parse (native)
    at Object.Module._extensions..json (module.js:482:27)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at module.exports (/Users/simon/nvm/v0.10.26/lib/node_modules/webpack/bin/convert-argv.js:68:13)
    at Object.<anonymous> (/Users/simon/nvm/v0.10.26/lib/node_modules/webpack/bin/webpack.js:54:40)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
```

It was completely an error where it was totally obvious, but you don't realise it, if you don't know what you are looking for. This is just a small suggestion... but perhaps throw an error if people accidentally use .json as the extension?

As far as I understand it, it is Node.js that is adding/trying .json if it is not finding .js?

Is this something useful to add, or was I just too dumb/oblivious to spot it? ;)

**Comment by shama** [comment]
A `webpack.config.json` is ok to use just as long as it's valid JSON:
```json
{
  "entry": "./index.js",
  "output": {
      "path": "./dist/",
      "filename": "bundle.js"
  }
}
```

The above error was letting you know there was a `SyntaxError` in your JSON: `/Users/simon/code/ethereum/js/ether_reactor/example/webpack.config.json: Unexpected token m`

I'm guessing your JSON file had `module.exports = {}`
which is why it errored with: `Unexpected token m`
