### ISSUE TITLE
Dynamic require breaks webpack

### ISSUE THREAD

**Issue by ijsf** [webpack/webpack#1299]
I've been trying to move a particular project called `the-graph` (https://github.com/the-grid/the-graph) over from browserify to webpack.

Unfortunately, the dependencies of this project (notably `noflo`) are using dynamic require() calls. While these do work in browserify, they basically break webpack, up to a point where it gets incredibly cumbersome to debug the actual issue (due to lack of proper error reporting in the webpack output).

Easy steps to reproduce:

1. Clone https://github.com/the-grid/the-graph
2. Follow installation instructions:

        $ bower install
        $ npm install

3. Create a file `test.js` with the following contents:

        var noflo = require('noflo');

4. Attempt to build with webpack:

        $ webpack test.js output.js

The following error is thrown with the current version:

    /usr/local/lib/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:33
    		request: request.path,
    		                ^
    TypeError: Cannot read property 'path' of null
        at Tapable.resolve (/usr/local/lib/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:33:19)
        at Tapable.resolve (/usr/local/lib/node_modules/webpack/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:23:14)
        at /usr/local/lib/node_modules/webpack/node_modules/async/lib/async.js:567:21
        at /usr/local/lib/node_modules/webpack/node_modules/async/lib/async.js:246:17
        at /usr/local/lib/node_modules/webpack/node_modules/async/lib/async.js:122:13
        at _each (/usr/local/lib/node_modules/webpack/node_modules/async/lib/async.js:46:13)
        at async.each (/usr/local/lib/node_modules/webpack/node_modules/async/lib/async.js:121:9)
        at _asyncMap (/usr/local/lib/node_modules/webpack/node_modules/async/lib/async.js:245:13)
        at Object.map (/usr/local/lib/node_modules/webpack/node_modules/async/lib/async.js:216:23)
        at _parallel (/usr/local/lib/node_modules/webpack/node_modules/async/lib/async.js:565:20)
        at Object.async.parallel (/usr/local/lib/node_modules/webpack/node_modules/async/lib/async.js:595:9)
        at Tapable.<anonymous> (/usr/local/lib/node_modules/webpack/lib/ContextModuleFactory.js:52:9)
        at Tapable.applyPluginsAsyncWaterfall (/usr/local/lib/node_modules/webpack/node_modules/tapable/lib/Tapable.js:75:69)
        at Tapable.ContextModuleFactory.create (/usr/local/lib/node_modules/webpack/lib/ContextModuleFactory.js:20:7)
        at Tapable.<anonymous> (/usr/local/lib/node_modules/webpack/lib/Compilation.js:208:11)
        at /usr/local/lib/node_modules/webpack/node_modules/async/lib/async.js:122:13
        at _each (/usr/local/lib/node_modules/webpack/node_modules/async/lib/async.js:46:13)
        at Object.async.each (/usr/local/lib/node_modules/webpack/node_modules/async/lib/async.js:121:9)
        at Tapable.Compilation.addModuleDependencies (/usr/local/lib/node_modules/webpack/lib/Compilation.js:179:8)
        at Tapable.Compilation.processModuleDependencies (/usr/local/lib/node_modules/webpack/lib/Compilation.js:165:7)
        at Tapable.<anonymous> (/usr/local/lib/node_modules/webpack/lib/Compilation.js:313:11)
        at /usr/local/lib/node_modules/webpack/lib/Compilation.js:120:4
        at Array.forEach (native)
        at callback (/usr/local/lib/node_modules/webpack/lib/Compilation.js:119:12)
        at Tapable.<anonymous> (/usr/local/lib/node_modules/webpack/lib/Compilation.js:137:10)
        at DependenciesBlock.<anonymous> (/usr/local/lib/node_modules/webpack/lib/NormalModule.js:114:10)
        at DependenciesBlock.onModuleBuild (/usr/local/lib/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
        at nextLoader (/usr/local/lib/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
        at /usr/local/lib/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
        at Storage.finished (/usr/local/lib/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)

I believe I have narrowed it down to a few unusual dynamic require() calls in the following file: https://github.com/noflo/noflo/blob/master/src/lib/ComponentLoader.coffee - which, when compiled, are converted into the following JS:

    ...
    implementation = require(implementation);

    ...
    graphImplementation = require(this.components['Graph']);

And these might also be related, although they shouldn't:

    ...
    source = source.replace("require('noflo')", "require('./NoFlo')");
    source = source.replace('require("noflo")', 'require("./NoFlo")');

**Comment by bergie** [comment]
@ijsf you could try requiring only the Graph module:

`require('noflo/lib/Graph')`

**Comment by ijsf** [comment]
@bergie Thanks. This is exactly what we ended up doing :)
