### ISSUE TITLE
How to distinguish server side vs browser side code for isomorphic apps through webpack?

### ISSUE THREAD

**Issue by SudoPlz** [webpack/webpack#1301]
I'm trying to run a library called  [react-bootstrap-modal](https://github.com/jquense/react-bootstrap-modal/blob/master/lib/Modal.js#L26) and it has calls to `document`. 

I'm building an isomorphic app so calls to `document` are TOTALLY accepted when they run browser side but NOT when they run on the server side through node. 

What can I do to stop getting errors like 
```javascript
 var modal = document.createElement("div"),
              ^
ReferenceError: document is not defined
    at /Users/Dynopia/Development/DS_Stalker_Frontend/node_modules/react-bootstrap-modal/lib/Modal.js:27:15
    at Object.<anonymous> (/Users/Dynopia/Development/DS_Stalker_Frontend/node_modules/react-bootstrap-modal/lib/Modal.js:47:3)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/Dynopia/Development/DS_Stalker_Frontend/bin/serverEntryPoint.js:1762:19)
    at __webpack_require__ (/Users/Dynopia/Development/DS_Stalker_Frontend/bin/serverEntryPoint.js:20:30)
```

I guess it would be ok if I could just ignore this module WHEN packing everything for server side. But how can I ignore this?

This is my webpack configuration file  for the server side code:  (I use another one for browser side code)

```
var webpack = require('webpack');
var path = require('path');
var fs = require('fs');

var nodeModules = {};
fs.readdirSync('node_modules')
    .filter(function(x) {
        return ['.bin'].indexOf(x) === -1;
    })
    .forEach(function(mod) {
        nodeModules[mod] = 'commonjs ' + mod;
    });

//console.log('Node Modules: '+ JSON.stringify(nodeModules));
module.exports =

{
    // The configuration for the server-side rendering
    name: 'server',
    target: 'node',
    entry: './app/server/serverEntryPrototype.js',
    output: {
        path: './bin/',
        publicPath: 'bin/',
        filename: 'serverEntryPoint.js'
    },
    externals: nodeModules,
    module: {
        loaders: [
            { test: /\.js$/,

                loaders: [
                    'react-hot',
                    'babel-loader'
                    //,'jsx-loader'
                ]
            },
            //{ test: /\.css$/,  loader: path.join(__dirname, 'server', 'style-collector') + '!css-loader' },
            { test:  /\.json$/, loader: 'json-loader' }
            //{ test: /\.ejs$/, loader: 'ejs-loader?variable=data' }
        ]
    }
};```

**Comment by sokra** [comment]
Do one of these:

* Only write DOM code in `componentDidMount` etc.
* use `resolve.extensions` to resolve to different modules on server/client side
* Use the `browser` field in package.json to replace modules for the browser
* use the NormalModuleReplacementPlugin to replace modules

**Comment by SudoPlz** [comment]
1) I cannot write DOM code because I don't own the node_module that I wish to use. Thus I can't edit it myself.
2-3-4) I will see into that, I have no idea how to do this atm.
