### ISSUE TITLE
vuejs/eslint-plugin-vue Module build failed (from ./node_modules/eslint-loader/dist/cjs.js): Error: Cannot find module 'eslint'

### ISSUE THREAD

**Issue by mohammad-bede** [webpack/webpack#13061]
I'm having issue running my nuxt app. When I do npm run dev I get this error: `Module build failed (from ./node_modules/eslint-loader/dist/cjs.js): Error: Cannot find module 'eslint'.` I have tried clearing my cache, npm install and running again but didn't solve my issue. This is my package.json:
```
{
  "name": "client",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "dev": "nuxt",
    "build": "nuxt build",
    "start": "nuxt start",
    "generate": "nuxt generate",
    "test": "jest"
  },
  "dependencies": {
    "@kevinfaguiar/vue-twemoji-picker": "^5.7.4",
    "@nuxtjs/auth": "^4.9.1",
    "@nuxtjs/axios": "^5.13.1",
    "@nuxtjs/dotenv": "^1.4.1",
    "aws-amplify": "^3.3.26",
    "axios": "^0.21.1",
    "bootstrap": "^4.6.0",
    "bootstrap-vue": "^2.21.2",
    "core-js": "^3.8.3",
    "hooper": "^0.3.4",
    "moment": "^2.29.1",
    "nuxt": "^2.15.3",
    "pubnub": "^4.30.1",
    "vue-cookie": "^1.1.4"
  },
  "devDependencies": {
    "@nuxtjs/google-fonts": "^1.2.0",
    "@nuxtjs/proxy": "^2.1.0",
    "@vue/test-utils": "^1.1.2",
    "babel-core": "7.0.0-bridge.0",
    "babel-jest": "^26.6.3",
    "eslint-loader": "^4.0.2",
    "fibers": "^5.0.0",
    "jest": "^26.6.3",
    "sass": "^1.32.8",
    "sass-loader": "^10.1.1",
    "vue-jest": "^3.0.4",
    "webpack": "^4.46.0"
  }
}
```
Also on the terminal I get this error:
```
Module build failed (from ./node_modules/eslint-loader/dist/cjs.js):                                  friendly-errors 21:42:49
Error: Cannot find module 'eslint'
Require stack:
- /Users/user/Desktop/Work/frontend copy/node_modules/eslint-loader/dist/getOptions.js
- /Users/user/Desktop/Work/frontend copy/node_modules/eslint-loader/dist/index.js
- /Users/user/Desktop/Work/frontend copy/node_modules/eslint-loader/dist/cjs.js
- /Users/user/Desktop/Work/frontend copy/node_modules/webpack/node_modules/loader-runner/lib/loadLoader.js
- /Users/user/Desktop/Work/frontend copy/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js
- /Users/user/Desktop/Work/frontend copy/node_modules/webpack/lib/NormalModule.js
- /Users/user/Desktop/Work/frontend copy/node_modules/webpack/lib/NormalModuleFactory.js
- /Users/user/Desktop/Work/frontend copy/node_modules/webpack/lib/Compiler.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at n (/Users/user/Desktop/Work/frontend copy/node_modules/jiti/dist/v8cache.js:2:2349)
    at getOptions (/Users/user/Desktop/Work/frontend copy/node_modules/eslint-loader/dist/getOptions.js:28:7)
    at Object.loader (/Users/user/Desktop/Work/frontend copy/node_modules/eslint-loader/dist/index.js:17:43)
```
I'm using `"@nuxt/webpack": "2.15.4"` Anyone knows how to fix it?

**Comment by alexander-akait** [comment]
`eslint-loader` is deprecated (https://github.com/webpack-contrib/eslint-loader) please migrate on https://github.com/webpack-contrib/eslint-webpack-plugin
