### ISSUE TITLE
Vue3, vue-cli - npm run serve error, node 16, npm 7

### ISSUE THREAD

**Issue by gopz19** [webpack/webpack#13230]
Full trace of error:

xxxxxx@xxxxxx_machine xxxxxx_proj % npm run serve

> projnew3@0.1.0 serve
> vue-cli-service serve src/main/webapp/WEB-INF/views/src/main.js

 INFO  Starting development server...
12% building 18/19 modules 1 active .../xxxxxx_workspace/xxxxxx_proj/node_modules/babel-loader/lib/index.js!/Users/xxxxxx/Documents/xxxxxx_workspace/xxxxxx_proj/src/main/webapp/WEB-INF/views/src/main.js/Users/xxxxxx/Documents/xxxxxx_workspace/xxxxxx_proj/node_modules/webpack/lib/Dependency.js:246
		throw new Error(
		^

Error: module property was removed from Dependency (use compilation.moduleGraph.updateModule(dependency, module) instead)
    at ProvidedDependency.set (/Users/xxxxxx/Documents/xxxxxx_workspace/xxxxxx_proj/node_modules/webpack/lib/Dependency.js:246:9)
    at iterationDependencies (/Users/xxxxxx/Documents/xxxxxx_workspace/xxxxxx_proj/node_modules/@vue/cli-service/node_modules/webpack/lib/Compilation.js:940:21)
    at /Users/xxxxxx/Documents/xxxxxx_workspace/xxxxxx_proj/node_modules/@vue/cli-service/node_modules/webpack/lib/Compilation.js:950:8
    at /Users/xxxxxx/Documents/xxxxxx_workspace/xxxxxx_proj/node_modules/@vue/cli-service/node_modules/webpack/lib/NormalModuleFactory.js:409:6
    at /Users/xxxxxx/Documents/xxxxxx_workspace/xxxxxx_proj/node_modules/@vue/cli-service/node_modules/webpack/lib/NormalModuleFactory.js:155:13
    at eval (eval at create (/Users/xxxxxx/Documents/xxxxxx_workspace/xxxxxx_proj/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:14:1)
    at /Users/xxxxxx/Documents/xxxxxx_workspace/xxxxxx_proj/node_modules/case-sensitive-paths-webpack-plugin/index.js:158:9
    at /Users/xxxxxx/Documents/xxxxxx_workspace/xxxxxx_proj/node_modules/case-sensitive-paths-webpack-plugin/index.js:113:7
    at /Users/xxxxxx/Documents/xxxxxx_workspace/xxxxxx_proj/node_modules/case-sensitive-paths-webpack-plugin/index.js:113:7
    at CaseSensitivePathsPlugin.fileExistsWithCase (/Users/xxxxxx/Documents/xxxxxx_workspace/xxxxxx_proj/node_modules/case-sensitive-paths-webpack-plugin/index.js:83:5)
    at /Users/xxxxxx/Documents/xxxxxx_workspace/xxxxxx_proj/node_modules/case-sensitive-paths-webpack-plugin/index.js:106:10
    at CaseSensitivePathsPlugin.getFilenamesInDir (/Users/xxxxxx/Documents/xxxxxx_workspace/xxxxxx_proj/node_modules/case-sensitive-paths-webpack-plugin/index.js:51:5)
    at CaseSensitivePathsPlugin.fileExistsWithCase (/Users/xxxxxx/Documents/xxxxxx_workspace/xxxxxx_proj/node_modules/case-sensitive-paths-webpack-plugin/index.js:89:8)
    at /Users/xxxxxx/Documents/xxxxxx_workspace/xxxxxx_proj/node_modules/case-sensitive-paths-webpack-plugin/index.js:106:10
    at Array.<anonymous> (/Users/xxxxxx/Documents/xxxxxx_workspace/xxxxxx_proj/node_modules/case-sensitive-paths-webpack-plugin/index.js:67:5)
    at Storage.finished (/Users/xxxxxx/Documents/xxxxxx_workspace/xxxxxx_proj/node_modules/@vue/cli-service/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.
