### ISSUE TITLE
Handle invalid `remotes` items for module federation

### ISSUE THREAD

**Issue by alexander-akait** [webpack/webpack#13287]
Hi @alexander-akait ,

I have pushed my sample code to Github, You can find it [here](https://github.com/tmkasun/webpack-MF-with-React/blob/main/app1/webpack.config.js)

I basically followed the `basic host remote` example from [module-federation-examples](https://github.com/module-federation/module-federation-examples)

In development build, Following exception thrown at the runtime in browser,

![image](https://user-images.githubusercontent.com/3313885/116721005-754f9500-a9fa-11eb-8a17-e1bfd3e4f655.png)

Here is the generated code in browser 

```js
/***/ "webpack/container/reference/application_b":
/*!********************************!*\
  !*** external "application_b" ***!
  \********************************/
/***/ ((module, __unused_webpack_exports, __webpack_require__) => {

"use strict";
var __webpack_error__ = new Error();
module.exports = new Promise((resolve, reject) => {
	if(typeof  !== "undefined") return resolve();
	__webpack_require__.l("application_b", (event) => {
		if(typeof  !== "undefined") return resolve();
		var errorType = event && (event.type === 'load' ? 'missing' : event.type);
		var realSrc = event && event.target && event.target.src;
		__webpack_error__.message = 'Loading script failed.\n(' + errorType + ': ' + realSrc + ')';
		__webpack_error__.name = 'ScriptExternalLoadError';
		__webpack_error__.type = errorType;
		__webpack_error__.request = realSrc;
		reject(__webpack_error__);
	}, "");
}).then(() => ());
```

In production build, I get following error at the build time

```js
➜  app1 git:(master) ✗ npm run build:prod

> react_module_federation_app1@1.0.0 build:prod /Users/user/testing/modulefederation/app1
> npm run clean && webpack --mode production


> react_module_federation_app1@1.0.0 clean /Users/user/testing/modulefederation/app1
> rm -Rf public/*

assets by status 393 KiB [cached] 9 assets
orphan modules 514 KiB [orphan] 211 modules
runtime modules 22.5 KiB 15 modules
built modules 887 KiB (javascript) 420 bytes (consume-shared) 132 bytes (share-init) 6 bytes (remote) [built]
  modules by path ./node_modules/ 853 KiB 78 modules
  consume-shared-module modules 420 bytes 10 modules
  modules by path ./source/ 33.7 KiB
    modules by path ./source/Application/ 32.5 KiB 7 modules
    modules by path ./source/*.jsx 1.18 KiB 2 modules
  provide-module modules 126 bytes
    provide shared module (default) react-dom@17.0.1+4.13.0 = ./node_modules/@hot-loader/react-dom/index.js 42 bytes [built] [code generated]
    provide shared module (default) react-router-dom@5.2.0 = ./node_modules/react-router-dom/esm/react-router-dom.js 42 bytes [built] [code generated]
    provide shared module (default) react@17.0.2 = ./node_modules/react/index.js 42 bytes [built] [code generated]
  remote application_b/SayHelloFromB 6 bytes (remote) 6 bytes (share-init) [built] [code generated]
  external "application_b" 42 bytes [built] [code generated]

ERROR in main.c759254c956de7e37d70.js from Terser
Unexpected token: operator (!==) [external "application_b":3,0][main.c759254c956de7e37d70.js:21,12]
    at js_error (/Users/user/testing/modulefederation/app1/node_modules/terser/dist/bundle.min.js:550:11)
    at croak (/Users/user/testing/modulefederation/app1/node_modules/terser/dist/bundle.min.js:1274:9)
    at token_error (/Users/user/testing/modulefederation/app1/node_modules/terser/dist/bundle.min.js:1282:9)
    at unexpected (/Users/user/testing/modulefederation/app1/node_modules/terser/dist/bundle.min.js:1288:9)
    at expr_atom (/Users/user/testing/modulefederation/app1/node_modules/terser/dist/bundle.min.js:2525:9)
    at maybe_unary (/Users/user/testing/modulefederation/app1/node_modules/terser/dist/bundle.min.js:3294:19)
    at maybe_unary (/Users/user/testing/modulefederation/app1/node_modules/terser/dist/bundle.min.js:3289:57)
    at expr_ops (/Users/user/testing/modulefederation/app1/node_modules/terser/dist/bundle.min.js:3345:24)
    at maybe_conditional (/Users/user/testing/modulefederation/app1/node_modules/terser/dist/bundle.min.js:3350:20)
    at maybe_assign (/Users/user/testing/modulefederation/app1/node_modules/terser/dist/bundle.min.js:3427:20)

ERROR in main.59760e1e42431bc60e23.js from Terser
Unexpected token: operator (!==) [main.59760e1e42431bc60e23.js:21,12]
    at js_error (/Users/user/testing/modulefederation/app1/node_modules/terser/dist/bundle.min.js:550:11)
    at croak (/Users/user/testing/modulefederation/app1/node_modules/terser/dist/bundle.min.js:1274:9)
    at token_error (/Users/user/testing/modulefederation/app1/node_modules/terser/dist/bundle.min.js:1282:9)
    at unexpected (/Users/user/testing/modulefederation/app1/node_modules/terser/dist/bundle.min.js:1288:9)
    at expr_atom (/Users/user/testing/modulefederation/app1/node_modules/terser/dist/bundle.min.js:2525:9)
    at maybe_unary (/Users/user/testing/modulefederation/app1/node_modules/terser/dist/bundle.min.js:3294:19)
    at maybe_unary (/Users/user/testing/modulefederation/app1/node_modules/terser/dist/bundle.min.js:3289:57)
    at expr_ops (/Users/user/testing/modulefederation/app1/node_modules/terser/dist/bundle.min.js:3345:24)
    at maybe_conditional (/Users/user/testing/modulefederation/app1/node_modules/terser/dist/bundle.min.js:3350:20)
    at maybe_assign (/Users/user/testing/modulefederation/app1/node_modules/terser/dist/bundle.min.js:3427:20)

webpack 5.36.1 compiled with 2 errors in 6950 ms
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react_module_federation_app1@1.0.0 build:prod: `npm run clean && webpack --mode production`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react_module_federation_app1@1.0.0 build:prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/user/.npm/_logs/2021-04-30T16_21_57_408Z-debug.log
```

Let me know if you need further information

_Originally posted by @tmkasun in https://github.com/webpack/webpack/issues/11805#issuecomment-830209233_

**Comment by snitin315** [comment]
Bump.

**Comment by vankop** [comment]
can not reproduce https://github.com/webpack/webpack/issues/11805#issuecomment-1064836537
