### ISSUE TITLE
Object.assign didn't return a function

### ISSUE THREAD

**Issue by ericelliott** [webpack/webpack#1338]
In [exercise-builder](https://github.com/jshomes/exercise-builder) the build is throwing errors at the Webpack step. Not sure what's causing it:

```
$ node --version
v0.12.5
$ npm --version
2.11.2
```

```
> exercise-builder@1.0.2 build /Users/eric/dev/exercise-builder
> NODE_ENV=production webpack && npm run build:min && npm run build:doc

Hash: d9f2eead3307d16f76f3
Version: webpack 1.11.0
Time: 498ms
    + 1 hidden modules

ERROR in Loader /Users/eric/dev/exercise-builder/node_modules/babel/index.js?plugins=object-assign didn't return a function
```

**Comment by SpaceK33z** [comment]
You don't have `babel-loader` installed, install it with `npm install babel-loader --save-dev`.

**Comment by shama** [comment]
@ericelliott Did @SpaceK33z suggestion fix your issue?

**Comment by ericelliott** [comment]
No. I have babel-loader installed, now, but I still get this error:

```
ERROR in ./source/index.js
Module build failed: ReferenceError: Unknown plugin "object-assign"
    at PluginManager.subnormaliseString (/Users/eric/Dropbox/dev/exercise-builder/node_modules/babel-loader/node_modules/babel-core/lib/transformation/file/plugin-manager.js:147:13)
    at PluginManager.add (/Users/eric/Dropbox/dev/exercise-builder/node_modules/babel-loader/node_modules/babel-core/lib/transformation/file/plugin-manager.js:190:40)
    at File.buildTransformers (/Users/eric/Dropbox/dev/exercise-builder/node_modules/babel-loader/node_modules/babel-core/lib/transformation/file/index.js:237:21)
    at new File (/Users/eric/Dropbox/dev/exercise-builder/node_modules/babel-loader/node_modules/babel-core/lib/transformation/file/index.js:139:10)
    at Pipeline.transform (/Users/eric/Dropbox/dev/exercise-builder/node_modules/babel-loader/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
    at transpile (/Users/eric/Dropbox/dev/exercise-builder/node_modules/babel-loader/index.js:12:22)
    at Object.module.exports (/Users/eric/Dropbox/dev/exercise-builder/node_modules/babel-loader/index.js:69:12)
```

**Comment by ericelliott** [comment]
See the [webpack build error branch](https://github.com/jshomes/exercise-builder/tree/webpack-build-error).

**Comment by shama** [comment]
Try this instead: `npm i babel-plugin-object-assign --save-dev`
and update your webpack config to:
```js
loaders: ['babel?plugins=babel-plugin-object-assign'],
```

**Comment by shama** [comment]
Related to this issue (where I found the above solution): https://github.com/babel-plugins/babel-plugin-object-assign/issues/1

**Comment by hipsterror** [comment]
You should add `exclude: /node_modules/` to your webpack.config.js like:
> module: {
>        loaders: [
>            { test: /\.js[x]?$/,
>                exclude: /node_modules/, //to avoid 'ReferenceError: Unknown plugin "object-assign"'                                                                                        
>                loaders:['babel-loader']
> ...
So you probably might not need to use the object-assign plugin

**Comment by bebraw** [comment]
I see you ended up with `loaders: ['babel?plugins=object-assign']` kind of declaration. Closing.
