### ISSUE TITLE
TypeError: The 'compilation' argument must be an instance of Compilation

### ISSUE THREAD

**Issue by notflorian** [webpack/webpack#13380]
# Bug report

**What is the current behavior?**
After the migration of webpack v4.41.6 to v5.37.0 our build fail with to following stack strace:
```
An error occurred during the build:
TypeError: The 'compilation' argument must be an instance of Compilation
    at Function.getCompilationHooks (/home/runner/work/theGardener/theGardener/frontend/node_modules/webpack/lib/javascript/JavascriptModulesPlugin.js:125:10)
    at /home/runner/work/theGardener/theGardener/frontend/node_modules/terser-webpack-plugin/dist/index.js:566:67
    at _next43 (eval at create (/home/runner/work/theGardener/theGardener/frontend/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:40:1)
    at _next21 (eval at create (/home/runner/work/theGardener/theGardener/frontend/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:97:1)
    at Hook.eval [as call] (eval at create (/home/runner/work/theGardener/theGardener/frontend/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:143:1)
    at Hook.CALL_DELEGATE [as _call] (/home/runner/work/theGardener/theGardener/frontend/node_modules/tapable/lib/Hook.js:14:14)
    at Compiler.newCompilation (/home/runner/work/theGardener/theGardener/frontend/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Compiler.js:1031:26)
    at /home/runner/work/theGardener/theGardener/frontend/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Compiler.js:1073:29
    at Hook.eval [as callAsync] (eval at create (/home/runner/work/theGardener/theGardener/frontend/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/runner/work/theGardener/theGardener/frontend/node_modules/tapable/lib/Hook.js:18:14)
    at Compiler.compile (/home/runner/work/theGardener/theGardener/frontend/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Compiler.js:1068:28)
    at /home/runner/work/theGardener/theGardener/frontend/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Compiler.js:496:12
    at Compiler.readRecords (/home/runner/work/theGardener/theGardener/frontend/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Compiler.js:908:11)
    at /home/runner/work/theGardener/theGardener/frontend/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Compiler.js:493:11
    at Hook.eval [as callAsync] (eval at create (/home/runner/work/theGardener/theGardener/frontend/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/runner/work/theGardener/theGardener/frontend/node_modules/tapable/lib/Hook.js:18:14)
An unhandled exception occurred: The 'compilation' argument must be an instance of Compilation
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Github repository: https://github.com/KelkooGroup/theGardener/blob/feature/update-angular-12/frontend/package.json
Failing Github CI build: https://github.com/KelkooGroup/theGardener/runs/2576502917

**What is the expected behavior?**

`ng build` should not fail with the `TypeError: The 'compilation' argument must be an instance of Compilation` error with webpack 5.

**Other relevant information:**
webpack version:  5.37.0
Node.js version: 14.16.1
Operating System: Alpine
Additional tools: Github Actions

**Comment by alexander-akait** [comment]
Please open an issue in `@angular-devkit` repo, some plugins is not compatibility

**Comment by alexander-akait** [comment]
And run `yarn why webpack`/`npm ls webpack`

**Comment by notflorian** [comment]
> npm ls webpack

frontend@0.0.0 /home/fauvarqf/work/Common/theGardener/frontend
├─┬ @angular-devkit/build-angular@12.0.0
│ └── webpack@5.36.2
└── webpack@5.37.0

**Comment by alexander-akait** [comment]
As you can see you have two version of webpack, `@angular-devkit` already have own webpack, you don't  need to install `webpack` by self (I think, but better ask this in `@angular-devkit` repo)

**Comment by alexander-akait** [comment]
Try to remove own webpack (i.e. remove it from `package.json`) and run build again

**Comment by notflorian** [comment]
Thanks it works.

Indeed this was a bug in angular CLI with webpack 5.37.0, fixed by this commit: https://github.com/angular/angular-cli/pull/20735/commits/56b348db311dbdc83cfa2e678f3758e888073671
