### ISSUE TITLE
Webpack 2 to webpack 3

### ISSUE THREAD

**Issue by imadarif** [webpack/webpack#13508]
Hi I have just updated the webpack 2 from webpack 3 i have got this error

G:\web_app\build\server.js:98800
throw new Error("Module build failed: ");
^
Error: Module build failed:
at Object.<anonymous> (G:\web_app\build\server.js:98800:7)
at webpack_require (G:\web_app\build\webpack:\webpack\bootstrap 7344fdcfe8d5a6b67db0:19:1)
at Object.<anonymous> (G:\web_app\build\server.js:95376:75)
at webpack_require (G:\web_app\build\webpack:\webpack\bootstrap 7344fdcfe8d5a6b67db0:19:1)
at Object.<anonymous> (G:\web_app\build\server.js:95295:67)
at webpack_require (G:\web_app\build\webpack:\webpack\bootstrap 7344fdcfe8d5a6b67db0:19:1)
at Object.<anonymous> (G:\web_app\build\webpack:\src\routes\index.js:9:1)
at webpack_require (G:\web_app\build\webpack:\webpack\bootstrap 7344fdcfe8d5a6b67db0:19:1)
at Object.<anonymous> (G:\web_app\build\server.js:42204:67)
at webpack_require (G:\web_app\build\webpack:\webpack\bootstrap 7344fdcfe8d5a6b67db0:19:1)
at Object.<anonymous> (G:\web_app\build\server.js:42149:18)
at webpack_require (G:\web_app\build\webpack:\webpack\bootstrap 7344fdcfe8d5a6b67db0:19:1)
at G:\web_app\build\webpack:\webpack\bootstrap 7344fdcfe8d5a6b67db0:62:1
at Object.<anonymous> (G:\web_app\build\server.js:68:10)
at Module._compile (internal/modules/cjs/loader.js:759:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
G:\web_app\tools\runServer.js:60
throw new Error(Server terminated unexpectedly with code: ${code} signal: ${signal});
^

Error: Server terminated unexpectedly with code: 1 signal: null
at ChildProcess.<anonymous> (G:/web_app/tools/runServer.js:44:17)
at Object.onceWrapper (events.js:284:20)
at ChildProcess.emit (events.js:196:13)
at ChildProcess.EventEmitter.emit (domain.js:471:20)
at Process.ChildProcess._handle.onexit (internal/child_process.js:256:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
PS G:\web_app>>

anyone have idea ?

**Comment by imadarif** [comment]
question
