### ISSUE TITLE
Swallowed error when building examples/labeled-modules without 'npm install'

### ISSUE THREAD

**Issue by edgydot** [webpack/webpack#1350]
# Problem
I tried to build the [*labeled-modules*](https://github.com/webpack/webpack/tree/master/examples/labeled-modules) example, which failed because I had forgotten to run `npm install` in base directory. More of a problem was the error message, which didn't help, as it was unrelated to the root cause.

# Findings
After some debugging, I found that the true error message seems to be swallowed by `remainingTimes` condition in `examples/build-common.js`. `remainingTimes` equals 3, but before retry kicks in, another exception is thrown and output, and the error message of the first exception is lost.

# Suggested fix
- make sure, both errors are output
- add hint about `npm install` to [Build section of examples/README.md](https://github.com/webpack/webpack/blob/master/examples/README.md#build)

# Steps to reproduce
- `git clone https://github.com/webpack/webpack` (HEAD at c0afdf9c)
- `cd webpack/examples/labeled-modules`
- `node build.js` (node v0.12.0)
- 2nd exception (misleading, shown to users):

    ```
    fs.js:502
      return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
		     ^
    Error: ENOENT, no such file or directory '.../examples/labeled-modules/js/output.js'
	at Error (native)
	at Object.fs.openSync (fs.js:502:18)
	at Object.fs.readFileSync (fs.js:354:15)
	at /home/user/tmp/webpack/examples/template-common.js:32:13
	at String.replace (native)
	at module.exports (/home/user/tmp/webpack/examples/template-common.js:28:18)
	at /home/user/tmp/webpack/examples/build-common.js:27:13
	at ChildProcess.exithandler (child_process.js:751:5)
	at ChildProcess.emit (events.js:110:17)
	at maybeClose (child_process.js:1008:16)
    ```
- 1st exception (root cause, hidden from users):

    ```
    module.js:338
	throw err;
	      ^
    Error: Cannot find module 'optimist'
	at Function.Module._resolveFilename (module.js:336:15)
	at Function.Module._load (module.js:278:25)
	at Module.require (module.js:365:17)
	at require (module.js:384:17)
	at Object.<anonymous> (/home/user/tmp/webpack/bin/webpack.js:15:16)
	at Module._compile (module.js:460:26)
	at Object.Module._extensions..js (module.js:478:10)
	at Module.load (module.js:355:32)
	at Function.Module._load (module.js:310:12)
	at Function.Module.runMain (module.js:501:10)
    ```

**Comment by bebraw** [comment]
@edgydot Can you try it out against the current version and webpack 2 beta?

**Comment by edgydot** [comment]
@bebraw
- On master, docs are good now. 1st exception is still hidden, though (if I ignore the docs and don't run `npm install`).
- At v2.0.0-beta, docs are still old and 1st exception is still hidden.

**Comment by bebraw** [comment]
Ok, let's close this now given the PR got merged.
