### ISSUE TITLE
[5.42.0 Regression] TypeError: Cannot read property 'dataUrl' of undefined

### ISSUE THREAD

**Issue by AviVahl** [webpack/webpack#13701]
# Bug report

This is a regression we've had when moving from 5.41.1 to 5.42.0.
When compiler is In watch mode (using `webpack-dev-middleware`), on a second file change, I get the following crash:
```
Exception has occurred: TypeError: Cannot read property 'dataUrl' of undefined
  at AssetGenerator.getTypes (/home/avi/projects/my-project/node_modules/webpack/lib/asset/AssetGenerator.js:268:24)
    at NormalModule.getSourceTypes (/home/avi/projects/my-project/node_modules/webpack/lib/NormalModule.js:1091:39)
    at NormalModule.cleanupForCache (/home/avi/projects/my-project/node_modules/webpack/lib/NormalModule.js:362:45)
    at NormalModuleFactory.cleanupForCache (/home/avi/projects/my-project/node_modules/webpack/lib/NormalModuleFactory.js:670:11)
    at Compiler._cleanupLastNormalModuleFactory (/home/avi/projects/my-project/node_modules/webpack/lib/Compiler.js:383:34)
    at Compiler.createNormalModuleFactory (/home/avi/projects/my-project/node_modules/webpack/lib/Compiler.js:1049:8)
    at Compiler.newCompilationParams (/home/avi/projects/my-project/node_modules/webpack/lib/Compiler.js:1071:30)
    at Compiler.compile (/home/avi/projects/my-project/node_modules/webpack/lib/Compiler.js:1082:23)
```

@sokra I suspect it might be related to https://github.com/webpack/webpack/pull/13680

**What is the current behavior?**

Crashes the process with that exception.
The `Module` instance without the buildInfo is for an svg file loaded from css using `url`. handled by native asset modules:
```
{
  test: /\.(png|jpg|gif|svg|woff2|ttf)$/i,
  type: 'asset'
}
```

I checked and it also occurs with url-loader handling that asset.

**If the current behavior is a bug, please provide the steps to reproduce.**

This is where it gets tricky. I'll try to create an isolated example, but even within our private repository, it happens only with specific entrypoints. I kinda hope that the stack trace will point us in the right direction.

**What is the expected behavior?**

Don't crash, and continue bundling in watch mode.

**Other relevant information:**
webpack version:  5.42.0
Node.js version: v14.17.1
Operating System: Fedora 34

**Comment by alexander-akait** [comment]
Duplicate https://github.com/webpack/webpack/issues/13691, sorry for this regression
