### ISSUE TITLE
[Bug?] Module not found although it is there in node_modules.

### ISSUE THREAD

**Issue by trusktr** [webpack/webpack#1373]
I'm tyring to apply the `glslify` transform by using `transform-loader` to apply the transform, but I get a "cannot resolve module" error:

```
 ❯ webpack                                                                                                                                                             [22:03:18]
Hash: 9a56cc72acac2de6f40c
Version: webpack 1.11.0
Time: 38ms
    + 1 hidden modules

ERROR in ./entry.js
Module build failed: Error: Cannot resolve module 'glslify' in /Users/josephpea/test/famous-with-webpack
    at innerCallback (/Users/josephpea/test/famous-with-webpack/node_modules/enhanced-resolve/lib/Resolver.js:91:16)
    at loggingCallbackWrapper (/Users/josephpea/test/famous-with-webpack/node_modules/enhanced-resolve/lib/createInnerCallback.js:21:19)
    at /Users/josephpea/test/famous-with-webpack/node_modules/tapable/lib/Tapable.js:134:6
    at /Users/josephpea/test/famous-with-webpack/node_modules/enhanced-resolve/lib/ModulesInDirectoriesPlugin.js:54:23
    at /Users/josephpea/test/famous-with-webpack/node_modules/enhanced-resolve/lib/Resolver.js:191:15
    at /Users/josephpea/test/famous-with-webpack/node_modules/enhanced-resolve/lib/ModulesInDirectoriesPlugin.js:45:26
    at loggingCallbackWrapper (/Users/josephpea/test/famous-with-webpack/node_modules/enhanced-resolve/lib/createInnerCallback.js:21:19)
    at /Users/josephpea/test/famous-with-webpack/node_modules/tapable/lib/Tapable.js:134:6
    at /Users/josephpea/test/famous-with-webpack/node_modules/enhanced-resolve/lib/Resolver.js:122:33
    at /Users/josephpea/test/famous-with-webpack/node_modules/enhanced-resolve/lib/Resolver.js:191:15
    at applyPluginsParallelBailResult.createInnerCallback.log (/Users/josephpea/test/famous-with-webpack/node_modules/enhanced-resolve/lib/Resolver.js:110:4)
    at loggingCallbackWrapper (/Users/josephpea/test/famous-with-webpack/node_modules/enhanced-resolve/lib/createInnerCallback.js:21:19)
    at /Users/josephpea/test/famous-with-webpack/node_modules/tapable/lib/Tapable.js:134:6
    at /Users/josephpea/test/famous-with-webpack/node_modules/enhanced-resolve/lib/DirectoryDefaultFilePlugin.js:37:24
    at /Users/josephpea/test/famous-with-webpack/node_modules/enhanced-resolve/lib/Resolver.js:191:15
    at /Users/josephpea/test/famous-with-webpack/node_modules/enhanced-resolve/lib/DirectoryDefaultFilePlugin.js:34:13
    at loggingCallbackWrapper (/Users/josephpea/test/famous-with-webpack/node_modules/enhanced-resolve/lib/createInnerCallback.js:21:19)
    at innerCallback (/Users/josephpea/test/famous-with-webpack/node_modules/enhanced-resolve/lib/Resolver.js:88:19)
    at loggingCallbackWrapper (/Users/josephpea/test/famous-with-webpack/node_modules/enhanced-resolve/lib/createInnerCallback.js:21:19)
    at /Users/josephpea/test/famous-with-webpack/node_modules/tapable/lib/Tapable.js:134:6
    at innerCallback (/Users/josephpea/test/famous-with-webpack/node_modules/enhanced-resolve/lib/Resolver.js:88:19)
    at loggingCallbackWrapper (/Users/josephpea/test/famous-with-webpack/node_modules/enhanced-resolve/lib/createInnerCallback.js:21:19)
    at /Users/josephpea/test/famous-with-webpack/node_modules/tapable/lib/Tapable.js:134:6
    at loggingCallbackWrapper (/Users/josephpea/test/famous-with-webpack/node_modules/enhanced-resolve/lib/createInnerCallback.js:21:19)
    at innerCallback (/Users/josephpea/test/famous-with-webpack/node_modules/enhanced-resolve/lib/Resolver.js:94:11)
    at loggingCallbackWrapper (/Users/josephpea/test/famous-with-webpack/node_modules/enhanced-resolve/lib/createInnerCallback.js:21:19)
    at /Users/josephpea/test/famous-with-webpack/node_modules/tapable/lib/Tapable.js:134:6
    at /Users/josephpea/test/famous-with-webpack/node_modules/enhanced-resolve/lib/ModulesInDirectoriesPlugin.js:54:23
    at /Users/josephpea/test/famous-with-webpack/node_modules/enhanced-resolve/lib/Resolver.js:191:15
    at /Users/josephpea/test/famous-with-webpack/node_modules/enhanced-resolve/lib/ModulesInDirectoriesPlugin.js:45:26
```

Any ideas why?

**Comment by trusktr** [comment]
I made a reproduction at https://g.trusktr.io/trusktr/webpack-issue-1373.git. Clone that repo, then run `npm install && webpack` inside the repo to see the error.

**Comment by bebraw** [comment]
Can you test against webpack 2?
