### ISSUE TITLE
webpack5 migrate thrown an 'can not get final name' error

### ISSUE THREAD

**Issue by olabala** [webpack/webpack#13762]
# Bug report
I'm using [react-virtualized](https://github.com/bvaughn/react-virtualized) which uses [babel-plugin-flow-react-proptypes](https://github.com/brigand/babel-plugin-flow-react-proptypes),

**What is the current behavior?**

and when I tried to migrate to webpack 5 from webpack 4, got this error.
```
Error: Cannot get final name for export 'babelPluginFlowReactPropTypes_proptype_AnimationTimeoutId' of ./node_modules/react-virtualized/dist/es/utils/requestAnimationTimeout.js
while generating the root export 'babelPluginFlowReactPropTypes_proptype_AnimationTimeoutId' (used name: 'rM')
    at getFinalBinding (/Users/xx/Desktop/xx/chat/node_modules/webpack/lib/optimize/ConcatenatedModule.js:467:10)
    at getFinalName (/Users/xx/Desktop/xx/chat/node_modules/webpack/lib/optimize/ConcatenatedModule.js:523:18)
    at /Users/xx/Desktop/xx/chat/node_modules/webpack/lib/optimize/ConcatenatedModule.js:1387:24
    at ConcatenatedModule.codeGeneration (/Users/xx/Desktop/xx/chat/node_modules/webpack/lib/optimize/ConcatenatedModule.js:1435:7)
    at /Users/xx/Desktop/xx/chat/node_modules/webpack/lib/Compilation.js:2727:22
    at /Users/xx/Desktop/xx/chat/node_modules/webpack/lib/Cache.js:93:5
    at Hook.eval [as callAsync] (eval at create (/Users/xx/Desktop/xx/chat/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Cache.get (/Users/xx/Desktop/xx/chat/node_modules/webpack/lib/Cache.js:75:18)
    at ItemCacheFacade.get (/Users/xx/Desktop/xx/chat/node_modules/webpack/lib/CacheFacade.js:117:15)
    at Compilation._codeGenerationModule (/Users/xx/Desktop/xx/chat/node_modules/webpack/lib/Compilation.js:2720:9)
```
(It worked perfect in webpack4)

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Other relevant information:**
webpack version:  ^5.43.0
Node.js version: v16.3.0
Operating System: macos
Additional tools:

**Comment by alexander-akait** [comment]
> If the current behavior is a bug, please provide the steps to reproduce.

Please fix it and we will reopen an issue
