### ISSUE TITLE
False positives regarding WebpackOptionsValidationError?  (configuration.module.rules[0].use should be non-empty string)

### ISSUE THREAD

**Issue by yukihirop** [webpack/webpack#13818]
# Bug report

**What is the current behavior?**

I have set up a custom loader in the `chainWebpack` settings in `vue.config.js`.
As follows

```js
/**
 * @see https://github.com/yukihirop/vue-i18n-translation-each-component/blob/for_webpack/bug_report/vue-config/vue-filename-injector.js
 */
 
const loader = (content) => { .... }

config.module
    .rule("vue")
    .use("vue-filename-inejctor")
    .loader(loader)
    .options(options)
    .after("vue-loader")
    .end();
```

`configuration.module.rules[0].use`  is not empty as you can see.
However, when I try to compile, I get the following error.

```
$ yarn serve
yarn run v1.22.10
$ vue-cli-service serve
 INFO  Starting development server...
 ERROR  WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.module.rules[0].use should be one of these:
   non-empty string | function | object { ident?, loader?, options?, query? } | function | [non-empty string | function | object { ident?, loader?, options?, query? }]
   -> Modifiers applied to the module when rule is matched
   Details:
    * configuration.module.rules[0].use[2].loader should be a string.
    * configuration.module.rules[0].use[2].loader should be one of these:
      non-empty string
      -> Loader name
WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.module.rules[0].use should be one of these:
   non-empty string | function | object { ident?, loader?, options?, query? } | function | [non-empty string | function | object { ident?, loader?, options?, query? }]
   -> Modifiers applied to the module when rule is matched
   Details:
    * configuration.module.rules[0].use[2].loader should be a string.
    * configuration.module.rules[0].use[2].loader should be one of these:
      non-empty string
      -> Loader name
    at webpack (/Users/yukihirop/JavaScriptProjects/vue-i18n-translation-each-component/node_modules/webpack/lib/webpack.js:31:9)
    at serve (/Users/yukihirop/JavaScriptProjects/vue-i18n-translation-each-component/node_modules/@vue/cli-service/lib/commands/serve.js:163:22)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**If the current behavior is a bug, please provide the steps to reproduce.**

```bash
{
   git clone git@github.com:yukihirop/vue-i18n-translation-each-component.git -b for_webpack/bug_report
   cd vue-i18n-translation-each-component
   yarn && yarn serve
}
```

**What is the expected behavior?**

Compile finishes without error.

```
$ yarn serve
yarn run v1.22.10
$ vue-cli-service serve
 INFO  Starting development server...
98% after emitting CopyPlugin

 WARNING  Compiled with 1 warning                                                                                                                                                                   16:47:45

Module Warning (from ./node_modules/eslint-loader/index.js):

/Users/yukihirop/JavaScriptProjects/vue-i18n-translation-each-component/src/App.vue
  13:3   warning  Missing return type on function  @typescript-eslint/explicit-module-boundary-types
  14:16  warning  Forbidden non-null assertion     @typescript-eslint/no-non-null-assertion
  14:16  warning  Forbidden non-null assertion     @typescript-eslint/no-non-null-assertion

✖ 3 problems (0 errors, 3 warnings)


You may use special comments to disable some warnings.
Use // eslint-disable-next-line to ignore the next line.
Use /* eslint-disable */ to ignore all warnings in a file.

  App running at:
  - Local:   http://localhost:8080/
  - Network: http://192.168.10.104:8080/

  Note that the development build is not optimized.
  To create a production build, run yarn build.

No issues found.
```

**Other relevant information:**
webpack version:  `4.46.0`
Node.js version: `v12.10.0`
Operating System: `macOS Mojave (Version 10.14.6)`
Additional tools:

**Comment by yukihirop** [comment]
Excuse me. Was self resolved.
It was because I was giving a function to `loader`.  🙇🏻‍♂️

https://webpack.js.org/contribute/writing-a-loader/#setup
