### ISSUE TITLE
throw an Error with type: 'asset', parser.dataUrlCondition.maxSize

### ISSUE THREAD

**Issue by richardchen85** [webpack/webpack#13827]
# Bug report

**What is the current behavior?**

I got an `TypeError: Cannot read property 'get' of undefined` when rebuild with config `type: 'asset', parser.dataUrlCondition.maxSize=1000`

**If the current behavior is a bug, please provide the steps to reproduce.**

- webpack.config.js
```js
module.exports = {
  module: {
    rules: [
      {
        test: /\.png/,
        type: 'asset',
        parser: {
          dataUrlCondition: {
            maxSize: 10000
          }
        }
      }
    ]
  }
}
```

- require a image with size under 10000
- rebuild and got error

```
ERROR in [entry] [initial]
Cannot read property 'get' of undefined
TypeError: Cannot read property 'get' of undefined
    at /Users/cdchenliqiang/workspace/4a-bdp-fe/mkt-cpm-ui/node_modules/webpack/lib/asset/AssetModulesPlugin.js:183:29
    at Hook.eval (eval at create (/Users/cdchenliqiang/workspace/4a-bdp-fe/mkt-cpm-ui/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:10:16)
    at Hook.CALL_DELEGATE [as _call] (/Users/cdchenliqiang/workspace/4a-bdp-fe/mkt-cpm-ui/node_modules/tapable/lib/Hook.js:14:14)
    at Compilation.getRenderManifest (/Users/cdchenliqiang/workspace/4a-bdp-fe/mkt-cpm-ui/node_modules/webpack/lib/Compilation.js:3774:36)
    at /Users/cdchenliqiang/workspace/4a-bdp-fe/mkt-cpm-ui/node_modules/webpack/lib/Compilation.js:3793:22
    at symbolEach (/Users/cdchenliqiang/workspace/4a-bdp-fe/mkt-cpm-ui/node_modules/neo-async/async.js:2444:9)
    at Object.each (/Users/cdchenliqiang/workspace/4a-bdp-fe/mkt-cpm-ui/node_modules/neo-async/async.js:2849:16)
    at Compilation.createChunkAssets (/Users/cdchenliqiang/workspace/4a-bdp-fe/mkt-cpm-ui/node_modules/webpack/lib/Compilation.js:3787:12)
    at /Users/cdchenliqiang/workspace/4a-bdp-fe/mkt-cpm-ui/node_modules/webpack/lib/Compilation.js:2548:14
    at /Users/cdchenliqiang/workspace/4a-bdp-fe/mkt-cpm-ui/node_modules/webpack/lib/Compilation.js:2680:5
```

**What is the expected behavior?**

rebuild without error

**Other relevant information:**
webpack version:  5.45.1
Node.js version: 12.20.1
Operating System: macOS 10.14.4
Additional tools:

**Comment by alexander-akait** [comment]
Seems you have broken data URI

**Comment by richardchen85** [comment]
it works fine if i comment codes below

```js
// webpack/lib/NormalModuleFactory.js

cleanupForCache() {
  for (const module of this._restoredUnsafeCacheEntries) {
    ChunkGraph.clearChunkGraphForModule(module);
    ModuleGraph.clearModuleGraphForModule(module);
    // works fine if comment this line
    // module.cleanupForCache();
  }
}
```

**Comment by alexander-akait** [comment]
never do it

**Comment by alexander-akait** [comment]
Please provide code

**Comment by richardchen85** [comment]
[webpack-learn.zip](https://github.com/webpack/webpack/files/6852243/webpack-learn.zip)

Here is my code and reproduce steps:

- run `npm start`
- type some words in `./src/index.js` and save
- get error `TypeError: Cannot read property 'get' of undefined`

**Comment by richardchen85** [comment]
`cache.type = 'filesystem'` and `devServer.hot = true` are the key

**Comment by alexander-akait** [comment]
Update webpack to v5.45.1, can't reproduce using your repo, works fine
