### ISSUE TITLE
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.

### ISSUE THREAD

**Issue by hhimanshu** [webpack/webpack#13871]
# Bug report

**What is the current behavior?**
The `npx size-limit` command fails with the following error
```
➜  ts-react-components-lib git:(hhimanshu/update-deps) ✗ npx size-limit
✖ Adding to empty webpack project
 ERROR  WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.entry['index'] should be an non-empty array.
   -> A non-empty array of non-empty strings
    at webpack (/Users/hhimanshu/code/prsnl/ts/ts-react-components-lib/node_modules/webpack/lib/webpack.js:31:9)
    at /Users/hhimanshu/code/prsnl/ts/ts-react-components-lib/node_modules/@size-limit/webpack/run-webpack.js:5:20
    at new Promise (<anonymous>)
    at runWebpack (/Users/hhimanshu/code/prsnl/ts/ts-react-components-lib/node_modules/@size-limit/webpack/run-webpack.js:4:10)
    at Object.step40 (/Users/hhimanshu/code/prsnl/ts/ts-react-components-lib/node_modules/@size-limit/webpack/index.js:88:38)
    at /Users/hhimanshu/code/prsnl/ts/ts-react-components-lib/node_modules/size-limit/calc.js:17:47
    at Array.map (<anonymous>)
    at step (/Users/hhimanshu/code/prsnl/ts/ts-react-components-lib/node_modules/size-limit/calc.js:16:29)
    at calc (/Users/hhimanshu/code/prsnl/ts/ts-react-components-lib/node_modules/size-limit/calc.js:44:42)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

```

**If the current behavior is a bug, please provide the steps to reproduce.**
- Please checkout `hhimanshu/update-deps` branch from https://github.com/hhimanshu/ts-react-components-lib
- Run `yarn install`
- Run `yarn size`

**What is the expected behavior?**
The command should have ran successfully

**Other relevant information:**
The `package.json` is available at https://github.com/hhimanshu/ts-react-components-lib/blob/hhimanshu/update-deps/package.json

webpack version:  
Node.js version
```
➜  ts-react-components-lib git:(hhimanshu/update-deps) ✗ node -v
v14.17.0
➜  ts-react-components-lib git:(hhimanshu/update-deps) npm -v
7.17.0
➜  ts-react-components-lib git:(hhimanshu/update-deps)
```

Operating System: Mac
Additional tools:

**Comment by hhimanshu** [comment]
There is a Github Action demonstrating this issue at https://github.com/hhimanshu/ts-react-components-lib/pull/7/checks?check_run_id=3163107139

**Comment by hhimanshu** [comment]
Here you go, and thanks for looking into it
```
➜  ts-react-components-lib git:(hhimanshu/update-deps) npx size-limit --debug
✖ Adding to empty webpack project
{
  "cwd": "/Users/hhimanshu/code/prsnl/ts/ts-react-components-lib",
  "configPath": "package.json",
  "checks": [
    {
      "path": "dist/p2.cjs.production.min.js",
      "limit": "10 KB",
      "files": [],
      "ignore": [
        "react",
        "styled-components"
      ],
      "name": "",
      "sizeLimit": 10000,
      "webpackOutput": "/var/folders/gx/s6ww02yn1mgfnn7h0bqn_zbw0000gn/T/size-limit-jOzU7tny2pCoCEk3m8rup",
      "webpackConfig": {
        "entry": {
          "index": []
        },
        "output": {
          "path": "/var/folders/gx/s6ww02yn1mgfnn7h0bqn_zbw0000gn/T/size-limit-jOzU7tny2pCoCEk3m8rup"
        },
        "optimization": {
          "concatenateModules": true
        },
        "resolve": {
          "plugins": [
            {
              "topLevelLoader": {}
            }
          ]
        },
        "resolveLoader": {
          "plugins": [
            {}
          ]
        },
        "module": {
          "rules": [
            {
              "test": {},
              "use": "file-loader"
            },
            {
              "test": {},
              "exclude": {},
              "use": [
                "style-loader",
                "css-loader"
              ]
            },
            {
              "test": {},
              "use": [
                "style-loader",
                {
                  "loader": "css-loader",
                  "options": {
                    "modules": true
                  }
                }
              ]
            }
          ]
        },
        "plugins": [
          {
            "pluginDescriptor": {
              "name": "OptimizeCssAssetsWebpackPlugin"
            },
            "options": {
              "assetProcessors": [
                {
                  "phase": "compilation.optimize-chunk-assets",
                  "regExp": {}
                }
              ],
              "assetNameRegExp": {},
              "cssProcessor": {
                "version": "8.3.6",
                "plugins": [
                  {
                    "postcssPlugin": "postcss-discard-comments"
                  },
                  {
                    "postcssPlugin": "postcss-minify-gradients"
                  },
                  {
                    "postcssPlugin": "postcss-reduce-initial"
                  },
                  {
                    "postcssPlugin": "postcss-svgo"
                  },
                  {
                    "postcssPlugin": "postcss-normalize-display-values"
                  },
                  {
                    "postcssPlugin": "postcss-reduce-transforms"
                  },
                  {
                    "postcssPlugin": "postcss-colormin"
                  },
                  {
                    "postcssPlugin": "postcss-normalize-timing-functions"
                  },
                  {
                    "postcssPlugin": "postcss-calc"
                  },
                  {
                    "postcssPlugin": "postcss-convert-values"
                  },
                  {
                    "postcssPlugin": "postcss-ordered-values"
                  },
                  {
                    "postcssPlugin": "postcss-minify-selectors"
                  },
                  {
                    "postcssPlugin": "postcss-minify-params"
                  },
                  {
                    "postcssPlugin": "postcss-normalize-charset"
                  },
                  {
                    "postcssPlugin": "postcss-discard-overridden"
                  },
                  {
                    "postcssPlugin": "postcss-normalize-string"
                  },
                  {
                    "postcssPlugin": "postcss-normalize-unicode"
                  },
                  {
                    "postcssPlugin": "postcss-minify-font-values"
                  },
                  {
                    "postcssPlugin": "postcss-normalize-url"
                  },
                  {
                    "postcssPlugin": "postcss-normalize-repeat-style"
                  },
                  {
                    "postcssPlugin": "postcss-normalize-positions"
                  },
                  {
                    "postcssPlugin": "postcss-normalize-whitespace"
                  },
                  {
                    "postcssPlugin": "postcss-merge-longhand"
                  },
                  {
                    "postcssPlugin": "postcss-discard-duplicates"
                  },
                  {
                    "postcssPlugin": "postcss-merge-rules"
                  },
                  {
                    "postcssPlugin": "postcss-discard-empty"
                  },
                  {
                    "postcssPlugin": "postcss-unique-selectors"
                  },
                  {
                    "postcssPlugin": "css-declaration-sorter"
                  },
                  {
                    "postcssPlugin": "cssnano-util-raw-cache"
                  }
                ]
              },
              "cssProcessorOptions": {},
              "cssProcessorPluginOptions": {}
            },
            "phaseAssetProcessors": {
              "compilation.optimize-chunk-assets": [
                {
                  "phase": "compilation.optimize-chunk-assets",
                  "regExp": {}
                }
              ],
              "compilation.optimize-assets": [],
              "emit": []
            },
            "deleteAssetsMap": {}
          }
        ]
      }
    },
    {
      "path": "dist/p2.esm.js",
      "limit": "10 KB",
      "files": [],
      "ignore": [
        "react",
        "styled-components"
      ],
      "name": "",
      "sizeLimit": 10000,
      "webpackOutput": "/var/folders/gx/s6ww02yn1mgfnn7h0bqn_zbw0000gn/T/size-limit-fO-KEZTRuGjYWq03K5GhO",
      "webpackConfig": {
        "entry": {
          "index": []
        },
        "output": {
          "path": "/var/folders/gx/s6ww02yn1mgfnn7h0bqn_zbw0000gn/T/size-limit-fO-KEZTRuGjYWq03K5GhO"
        },
        "optimization": {
          "concatenateModules": true
        },
        "resolve": {
          "plugins": [
            {
              "topLevelLoader": {}
            }
          ]
        },
        "resolveLoader": {
          "plugins": [
            {}
          ]
        },
        "module": {
          "rules": [
            {
              "test": {},
              "use": "file-loader"
            },
            {
              "test": {},
              "exclude": {},
              "use": [
                "style-loader",
                "css-loader"
              ]
            },
            {
              "test": {},
              "use": [
                "style-loader",
                {
                  "loader": "css-loader",
                  "options": {
                    "modules": true
                  }
                }
              ]
            }
          ]
        },
        "plugins": [
          {
            "pluginDescriptor": {
              "name": "OptimizeCssAssetsWebpackPlugin"
            },
            "options": {
              "assetProcessors": [
                {
                  "phase": "compilation.optimize-chunk-assets",
                  "regExp": {}
                }
              ],
              "assetNameRegExp": {},
              "cssProcessor": {
                "version": "8.3.6",
                "plugins": [
                  {
                    "postcssPlugin": "postcss-discard-comments"
                  },
                  {
                    "postcssPlugin": "postcss-minify-gradients"
                  },
                  {
                    "postcssPlugin": "postcss-reduce-initial"
                  },
                  {
                    "postcssPlugin": "postcss-svgo"
                  },
                  {
                    "postcssPlugin": "postcss-normalize-display-values"
                  },
                  {
                    "postcssPlugin": "postcss-reduce-transforms"
                  },
                  {
                    "postcssPlugin": "postcss-colormin"
                  },
                  {
                    "postcssPlugin": "postcss-normalize-timing-functions"
                  },
                  {
                    "postcssPlugin": "postcss-calc"
                  },
                  {
                    "postcssPlugin": "postcss-convert-values"
                  },
                  {
                    "postcssPlugin": "postcss-ordered-values"
                  },
                  {
                    "postcssPlugin": "postcss-minify-selectors"
                  },
                  {
                    "postcssPlugin": "postcss-minify-params"
                  },
                  {
                    "postcssPlugin": "postcss-normalize-charset"
                  },
                  {
                    "postcssPlugin": "postcss-discard-overridden"
                  },
                  {
                    "postcssPlugin": "postcss-normalize-string"
                  },
                  {
                    "postcssPlugin": "postcss-normalize-unicode"
                  },
                  {
                    "postcssPlugin": "postcss-minify-font-values"
                  },
                  {
                    "postcssPlugin": "postcss-normalize-url"
                  },
                  {
                    "postcssPlugin": "postcss-normalize-repeat-style"
                  },
                  {
                    "postcssPlugin": "postcss-normalize-positions"
                  },
                  {
                    "postcssPlugin": "postcss-normalize-whitespace"
                  },
                  {
                    "postcssPlugin": "postcss-merge-longhand"
                  },
                  {
                    "postcssPlugin": "postcss-discard-duplicates"
                  },
                  {
                    "postcssPlugin": "postcss-merge-rules"
                  },
                  {
                    "postcssPlugin": "postcss-discard-empty"
                  },
                  {
                    "postcssPlugin": "postcss-unique-selectors"
                  },
                  {
                    "postcssPlugin": "css-declaration-sorter"
                  },
                  {
                    "postcssPlugin": "cssnano-util-raw-cache"
                  }
                ]
              },
              "cssProcessorOptions": {},
              "cssProcessorPluginOptions": {}
            },
            "phaseAssetProcessors": {
              "compilation.optimize-chunk-assets": [
                {
                  "phase": "compilation.optimize-chunk-assets",
                  "regExp": {}
                }
              ],
              "compilation.optimize-assets": [],
              "emit": []
            },
            "deleteAssetsMap": {}
          }
        ]
      }
    }
  ]
}
 ERROR  WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.entry['index'] should be an non-empty array.
   -> A non-empty array of non-empty strings
    at webpack (/Users/hhimanshu/code/prsnl/ts/ts-react-components-lib/node_modules/webpack/lib/webpack.js:31:9)
    at /Users/hhimanshu/code/prsnl/ts/ts-react-components-lib/node_modules/@size-limit/webpack/run-webpack.js:5:20
    at new Promise (<anonymous>)
    at runWebpack (/Users/hhimanshu/code/prsnl/ts/ts-react-components-lib/node_modules/@size-limit/webpack/run-webpack.js:4:10)
    at Object.step40 (/Users/hhimanshu/code/prsnl/ts/ts-react-components-lib/node_modules/@size-limit/webpack/index.js:88:38)
    at /Users/hhimanshu/code/prsnl/ts/ts-react-components-lib/node_modules/size-limit/calc.js:17:47
    at Array.map (<anonymous>)
    at step (/Users/hhimanshu/code/prsnl/ts/ts-react-components-lib/node_modules/size-limit/calc.js:16:29)
    at calc (/Users/hhimanshu/code/prsnl/ts/ts-react-components-lib/node_modules/size-limit/calc.js:44:42)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**Comment by tejparekh** [comment]
@hhimanshu  Hey did you find a solution to this issue? 
I am facing a similar issue during the compilation of app using webpack 5, https://github.com/ant-design/ant-design-pro/issues/8828 @amol222patil

Please see if you can provide any inputs. 
Thanks,

**Comment by hhimanshu** [comment]
Hello @tejparekh , in my case, it was because my expected file names in `package.json` did not match the ones produced by `yarn build`. The related bug is https://github.com/ai/size-limit/issues/241
Check id this is the same thing in your case. Hope that helps

**Comment by tejparekh** [comment]
@hhimanshu Thanks for your response. 
I was able to solve this. Here are the details. 
[](https://github.com/ant-design/ant-design-pro/issues/8828#issuecomment-890671623)
