### ISSUE TITLE
Build is not working on the 5th version

### ISSUE THREAD

**Issue by AnToX1c** [webpack/webpack#13883]
# Bug report

**What is the current behavior?**
```
PS C:\projects\Maestro\m3-ui-cli\libs\aws-plugin> npm start

> @m3-ui-base/aws-plugin@0.0.1 start C:\projects\Maestro\m3-ui-cli\libs\aws-plugin
> webpack --config webpack.config.js

C:\projects\Maestro\m3-ui-cli\libs\aws-plugin\node_modules\webpack\lib\stats\DefaultStatsPrinterPlugin.js:266
                const [, prefix, resource] = /^(.*!)?([^!]*)$/.exec(name);
                                             ^

TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))
    at Object.module.name (C:\projects\Maestro\m3-ui-cli\libs\aws-plugin\node_modules\webpack\lib\stats\DefaultStatsPrinterPlugin.js:266:32)
    at C:\projects\Maestro\m3-ui-cli\libs\aws-plugin\node_modules\webpack\lib\stats\DefaultStatsPrinterPlugin.js:1145:29
    at Hook.eval [as call] (eval at create (C:\projects\Maestro\m3-ui-cli\libs\aws-plugin\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:7:16)
    at C:\projects\Maestro\m3-ui-cli\libs\aws-plugin\node_modules\webpack\lib\stats\StatsPrinter.js:150:9
    at StatsPrinter._forEachLevel (C:\projects\Maestro\m3-ui-cli\libs\aws-plugin\node_modules\webpack\lib\stats\StatsPrinter.js:93:19)
    at StatsPrinter._print (C:\projects\Maestro\m3-ui-cli\libs\aws-plugin\node_modules\webpack\lib\stats\StatsPrinter.js:149:26)
    at StatsPrinter.print (C:\projects\Maestro\m3-ui-cli\libs\aws-plugin\node_modules\webpack\lib\stats\StatsPrinter.js:123:16)
    at C:\projects\Maestro\m3-ui-cli\libs\aws-plugin\node_modules\webpack\lib\stats\StatsPrinter.js:190:27
    at Array.map (<anonymous>)
    at StatsPrinter._print (C:\projects\Maestro\m3-ui-cli\libs\aws-plugin\node_modules\webpack\lib\stats\StatsPrinter.js:189:38)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @m3-ui-base/aws-plugin@0.0.1 start: `webpack --config webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @m3-ui-base/aws-plugin@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Anton_Lapshyn\AppData\Roaming\npm-cache\_logs\2021-07-28T12_13_50_517Z-debug.log
```

**If the current behavior is a bug, please provide the steps to reproduce.**
Trying to update 'webpack' version from 4.46.0 to 5.47.0; webpack-cli version is the latest (for now) - 4.7.2.

**What is the expected behavior?**

**Other relevant information:**
webpack version:  5.47.0
Node.js version: 14.15.3
Operating System: Windows 10 Enterprise
Additional tools:

**Comment by alexander-akait** [comment]
Sorry not related to webpack, please open an issue in aws-plugin, run npm ls webpack, looks like you have two webpack version, feel feee to feedback
