### ISSUE TITLE
No unique hash info entry for unspecified runtime for 'xxxxxxx'

### ISSUE THREAD

**Issue by lanmch** [webpack/webpack#13960]
# Bug report

**What is the current behavior?**
I update the webpack version from 4 to 5, and i get this problem.
```
/Users/mc/mc/project/bear-web/node_modules/webpack/lib/ChunkGraph.js:1225
                                throw new Error(
                                ^

Error: No unique hash info entry for unspecified runtime for /Users/mc/mc/project/bear-web/node_modules/cache-loader/dist/cjs.js!/Users/mc/mc/project/bear-web/node_modules/thread-loader/dist/cjs.js??ruleSet[1].rules[0].use[1]!/Users/mc/mc/project/bear-web/node_modules/babel-loader/lib/index.js??ruleSet[1].rules[0].use[2]!/Users/mc/mc/project/bear-web/node_modules/ts-loader/index.js??ruleSet[1].rules[0].use[3]!/Users/mc/mc/project/bear-web/src/common/helpers/colorHelper.ts (existing runtimes: manifest_app+manifest_lark_app+manifest_lark_sheet_app+manifest_sheet_app, manifest_app, manifest_lark_app+manifest_lark_sheet_app).
Caller might not support runtime-dependent code generation (opt-out via optimization.usedExports: "global").
    at ChunkGraph._getModuleHashInfo (/Users/mc/mc/project/bear-web/node_modules/webpack/lib/ChunkGraph.js:1225:11)
    at ChunkGraph.getRenderedModuleHash (/Users/mc/mc/project/bear-web/node_modules/webpack/lib/ChunkGraph.js:1280:15)
    at NormalModule.get renderedHash [as renderedHash] (/Users/mc/mc/project/bear-web/node_modules/webpack/lib/Module.js:210:5)
    at /Users/mc/mc/project/bear-web/config/webpack-output-hash-plugin.js:97:90
    at Array.find (<anonymous>)
    at /Users/mc/mc/project/bear-web/config/webpack-output-hash-plugin.js:97:56
    at Array.forEach (<anonymous>)
    at reHashChunk (/Users/mc/mc/project/bear-web/config/webpack-output-hash-plugin.js:72:34)
    at /Users/mc/mc/project/bear-web/config/webpack-output-hash-plugin.js:215:7
    at Array.forEach (<anonymous>)
    at /Users/mc/mc/project/bear-web/config/webpack-output-hash-plugin.js:213:18
    at Hook.eval [as callAsync] (eval at create (/Users/mc/mc/project/bear-web/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:26:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/mc/mc/project/bear-web/node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
    at Compiler.emitAssets (/Users/mc/mc/project/bear-web/node_modules/webpack/lib/Compiler.js:862:19)
    at /Users/mc/mc/project/bear-web/node_modules/webpack/lib/Watching.js:167:21
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
error Command failed with exit code 1.
```

The following is the configuration of the suggested ruleSet error report：
```
{
          test: /\.tsx?$/,
          exclude: /node_modules/,
          // use: getTsxLoaders()
          use: [
            {loader: 'cache-loader'},
            {
              loader: 'thread-loader',
              options: {
                workers: 3
              }
            },
            getBabelLoader({
              cacheDirectory: true,
              plugins: [],
            }),
            {
              loader: 'ts-loader',
              options: {
                // disable type checker - we will use it in fork plugin
                // transpileOnly: true
                happyPackMode: true
              }
            }
          ]
        }
```

**If the current behavior is a bug, please provide the steps to reproduce.**
when i set the typescript rules, then the error comes. I have never encountered this problem before. And now, I can't find the source of the problem and solve it through webpack's error report.
I am expecting a reply!!

**What is the expected behavior?**
compile success

**Other relevant information:**
webpack version:  5.45.1
Node.js version: 14.16.0
Operating System: macOS 11.4
Additional tools:vscode

**Comment by alexander-akait** [comment]
1. Do not use `cache-loader` for webpack v5, if you need cache please use https://webpack.js.org/configuration/cache/
2. `webpack-output-hash-plugin` is outdated and deprecated, remove it, just use `[contenthash]` to generate md4/md5 hashes

**Comment by lanmch** [comment]
> 1. ou need cache please use [htt](https://webpack.js.org/configuration/cache/)

thanks, i will try it later
