### ISSUE TITLE
TypeError: Cannot read property 'javascript' of undefined 

### ISSUE THREAD

**Issue by alexsoin** [webpack/webpack#14005]
# Bug report

```
 TypeError: Cannot read property 'javascript' of undefined
    at /mnt/c/projects/gw-starter-kit/node_modules/terser-webpack-plugin/dist/index.js:607:38
    at SyncHook.eval [as call] (eval at create (/mnt/c/projects/gw-starter-kit/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:83:1)
    at SyncHook.lazyCompileHook (/mnt/c/projects/gw-starter-kit/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.newCompilation (/mnt/c/projects/gw-starter-kit/node_modules/webpack-stream/node_modules/webpack/lib/Compiler.js:631:26)
    at /mnt/c/projects/gw-starter-kit/node_modules/webpack-stream/node_modules/webpack/lib/Compiler.js:667:29
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/mnt/c/projects/gw-starter-kit/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/mnt/c/projects/gw-starter-kit/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.compile (/mnt/c/projects/gw-starter-kit/node_modules/webpack-stream/node_modules/webpack/lib/Compiler.js:662:28)
    at /mnt/c/projects/gw-starter-kit/node_modules/webpack-stream/node_modules/webpack/lib/Compiler.js:321:11
    at Compiler.readRecords (/mnt/c/projects/gw-starter-kit/node_modules/webpack-stream/node_modules/webpack/lib/Compiler.js:529:11)
```

**What is the current behavior?**

Replaced `uglifyjs-webpack-plugin` with `terser-webpack-plugin`. When building the project, the error **"TypeError: Cannot read property 'javascript' of undefined"** is displayed. The project uses webpack 5. You can view the project in more detail by following the [link](https://github.com/alexsoin/gw-starter-kit/tree/terser).

**Other relevant information:**
webpack version:  5
Node.js version: 14.16.1
Operating System: Windows 10 (WSL)
Additional tools: yarn

**Comment by alexander-akait** [comment]
Because you have webpack v4, but uses plugin for webpack v5, please run `npm ls webpack`, feel free to feedback

**Comment by alexsoin** [comment]
Thank you! Yes, it was a problem due to the `webpack-stream` plugin which depends on version 4 of the webpack. Unfortunately, this plugin does not support version 5 and now it is supported only in the [pull request](https://github.com/shama/webpack-stream/pull/235#issuecomment-898454149). We are waiting for the merge))))
