### ISSUE TITLE
Unexpected token: keyword (var)

### ISSUE THREAD

**Issue by januwA** [webpack/webpack#14240]
The following error occurred in `production` mode

```sh
ERROR in js/e808bf2c.js
js/e808bf2c.js from Terser plugin
Unexpected token: keyword (var) [js/e808bf2c.js:11,16]
    at js_error (D:\ajanuw\webpack-scaffold\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:550:11)
    at croak (D:\ajanuw\webpack-scaffold\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:1274:9)
    at token_error (D:\ajanuw\webpack-scaffold\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:1282:9)
    at unexpected (D:\ajanuw\webpack-scaffold\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:1288:9)
    at expr_atom (D:\ajanuw\webpack-scaffold\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:2525:9)
    at maybe_unary (D:\ajanuw\webpack-scaffold\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:3294:19)
    at expr_ops (D:\ajanuw\webpack-scaffold\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:3345:24)
    at maybe_conditional (D:\ajanuw\webpack-scaffold\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:3350:20)
    at maybe_assign (D:\ajanuw\webpack-scaffold\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:3427:20)
    at expression (D:\ajanuw\webpack-scaffold\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:3452:24)

ERROR in js/e808bf2c.js
js/e808bf2c.js from Terser plugin
Unexpected token: keyword (var) [js/e808bf2c.js:11,16]
    at js_error (D:\ajanuw\webpack-scaffold\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:550:11)
    at croak (D:\ajanuw\webpack-scaffold\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:1274:9)
    at token_error (D:\ajanuw\webpack-scaffold\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:1282:9)
    at unexpected (D:\ajanuw\webpack-scaffold\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:1288:9)
    at expr_atom (D:\ajanuw\webpack-scaffold\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:2525:9)
    at maybe_unary (D:\ajanuw\webpack-scaffold\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:3294:19)
    at expr_ops (D:\ajanuw\webpack-scaffold\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:3345:24)
    at maybe_conditional (D:\ajanuw\webpack-scaffold\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:3350:20)
    at maybe_assign (D:\ajanuw\webpack-scaffold\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:3427:20)
    at expression (D:\ajanuw\webpack-scaffold\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:3452:24)

ERROR in js/155fe674.js
js/155fe674.js from Terser plugin
Unexpected token: keyword (var) [js/155fe674.js:11,16]
    at js_error (D:\ajanuw\webpack-scaffold\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:550:11)
    at croak (D:\ajanuw\webpack-scaffold\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:1274:9)
    at token_error (D:\ajanuw\webpack-scaffold\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:1282:9)
    at unexpected (D:\ajanuw\webpack-scaffold\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:1288:9)
    at expr_atom (D:\ajanuw\webpack-scaffold\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:2525:9)
    at maybe_unary (D:\ajanuw\webpack-scaffold\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:3294:19)
    at expr_ops (D:\ajanuw\webpack-scaffold\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:3345:24)
    at maybe_conditional (D:\ajanuw\webpack-scaffold\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:3350:20)
    at maybe_assign (D:\ajanuw\webpack-scaffold\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:3427:20)
    at expression (D:\ajanuw\webpack-scaffold\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:3452:24)

ERROR in js/155fe674.js
js/155fe674.js from Terser plugin
Unexpected token: keyword (var) [js/155fe674.js:11,16]
    at js_error (D:\ajanuw\webpack-scaffold\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:550:11)
    at croak (D:\ajanuw\webpack-scaffold\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:1274:9)
    at token_error (D:\ajanuw\webpack-scaffold\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:1282:9)
    at unexpected (D:\ajanuw\webpack-scaffold\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:1288:9)
    at expr_atom (D:\ajanuw\webpack-scaffold\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:2525:9)
    at maybe_unary (D:\ajanuw\webpack-scaffold\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:3294:19)
    at expr_ops (D:\ajanuw\webpack-scaffold\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:3345:24)
    at maybe_conditional (D:\ajanuw\webpack-scaffold\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:3350:20)
    at maybe_assign (D:\ajanuw\webpack-scaffold\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:3427:20)
    at expression (D:\ajanuw\webpack-scaffold\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:3452:24)

webpack compiled with 4 errors
```

Version:
```
    "webpack": "^5.52.1",
    "webpack-cli": "^4.8.0",
    "webpack-dev-server": "^4.2.1",
    "webpack-merge": "^5.8.0",
```

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

**Comment by alexander-akait** [comment]
Based on error you have syntax unsupported by terser, but you don't provide more information, so we can't help
