### ISSUE TITLE
NPM install fail cause of fsevents@0.3.8 install Error

### ISSUE THREAD

**Issue by wenshin** [webpack/webpack#1435]
### Environment

```
node -v v0.12.7
npm -v v2.11.3
node-gyp -v v2.0.1
System Darwin 14.5.0，OSX Yosemite 10.10.5
```

### Run `npm install -g webpack`

```bash
$ npm install -g webpack
\
> fsevents@0.3.8 install ~/.nvm/versions/node/v0.12.7/lib/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: incorrect header check
gyp ERR! stack     at Zlib._handle.onerror (zlib.js:366:17)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "node" "~/.nvm/versions/node/v0.12.7/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd ~/.nvm/versions/node/v0.12.7/lib/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
npm WARN optional dep failed, continuing fsevents@0.3.8
~/.nvm/versions/node/v0.12.7/bin/webpack -> ~/.nvm/versions/node/v0.12.7/lib/node_modules/webpack/bin/webpack.js
webpack@1.12.1 ~/.nvm/versions/node/v0.12.7/lib/node_modules/webpack
├── interpret@0.6.5
├── tapable@0.1.9
├── async@1.4.2
├── clone@1.0.2
├── memory-fs@0.2.0
├── supports-color@3.1.1 (has-flag@1.0.0)
├── enhanced-resolve@0.9.0 (graceful-fs@3.0.8)
├── esprima@2.6.0
├── mkdirp@0.5.1 (minimist@0.0.8)
├── optimist@0.6.1 (wordwrap@0.0.3, minimist@0.0.10)
├── webpack-core@0.6.6 (source-list-map@0.1.5, source-map@0.4.4)
├── uglify-js@2.4.24 (uglify-to-browserify@1.0.2, async@0.2.10, yargs@3.5.4, source-map@0.1.34)
├── node-libs-browser@0.5.2 (https-browserify@0.0.0, tty-browserify@0.0.0, os-browserify@0.1.2, constants-browserify@0.0.1, string_decoder@0.10.31, process@0.11.2, path-browserify@0.0.0, punycode@1.3.2, domain-browser@1.1.4, querystring-es3@0.2.1, assert@1.3.0, timers-browserify@1.4.1, stream-browserify@1.0.0, events@1.0.2, console-browserify@1.1.0, vm-browserify@0.0.4, util@0.10.3, http-browserify@1.7.0, url@0.10.3, readable-stream@1.1.13, buffer@3.4.3, browserify-zlib@0.1.4, crypto-browserify@3.2.8)
└── watchpack@0.2.8 (graceful-fs@3.0.8, async@0.9.2, chokidar@1.0.5)
```

### only install fsevents

```bash
$ npm install fsevents@0.3.8
npm WARN package.json performance@1.0.0 No repository field.
npm WARN package.json performance@1.0.0 No README data
npm WARN package.json performance@1.0.0 No license field.
-
> fsevents@0.3.8 install ~/node_modules/fsevents
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: incorrect header check
gyp ERR! stack     at Zlib._handle.onerror (zlib.js:366:17)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "node" "~/.nvm/versions/node/v0.12.7/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd ~/node_modules/fsevents
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
npm ERR! Darwin 14.5.0
npm ERR! argv "~/.nvm/versions/node/v0.12.7/bin/node" "~/.nvm/versions/node/v0.12.7/bin/npm" "install" "fsevents@0.3.8"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! fsevents@0.3.8 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fsevents@0.3.8 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the fsevents package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls fsevents
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     ~/npm-debug.log
```

**Comment by sokra** [comment]
It's an optional dependency. So it's fine when it fails.

**Comment by wenshin** [comment]
OK，Thanks

**Comment by JeffreyWay** [comment]
Seems this happens when you prematurely abort `npm install`.

https://github.com/PolymerElements/polymer-starter-kit/issues/51

**Comment by aligit** [comment]
This problem persist on Windows. I can't install webpack due to chokidar/fsevents incompatibility with my Windows

**Comment by JD-Robbs** [comment]
Same here - although it's an optional dependency, the webpack package won't install at all.

**Comment by karthik2706** [comment]
@JD-Robbs - Try npm install --no-optional
This should skip fsevents as it is optional

**Comment by silkentrance** [comment]
@karthik2706 even with that option it still produces an error where in the past it would just produce a warning.

**Comment by omouse** [comment]
to echo @silkentrance we're experiencing this issue on Windows 10, it complains about fsevents requiring 'darwin' kernel and we did run with `npm install --no-optional`

**Comment by ngokli** [comment]
In case y'all are still struggling: there was a bug in `npm` that has been fixed in `npm @3.10.10`: https://github.com/npm/npm/issues/14042

If you have `fsevents` in your `package.json` or `npm-shrinkwrap.json`,  it needs to be marked as optional, or the fix won't help you.  Once it's set up correctly, I think you don't need the `--no-optional`.  And with `npm@3.10.10`, shrinkwrapping should set fsevents as an optional dependency in `npm-shrinkwrap.json`.

**Comment by ngokli** [comment]
Oh, and I guess that goes for `npm@4.0.2` as well, though I haven't tried it.

**Comment by omouse** [comment]
@ngokli yep I found out that someone had added fsevents to npm-shrinkwrap.json, removing it fixed the issue

**Comment by brickgale** [comment]
Encountering an issue when using request (https://github.com/request/request). It is using fs.

**Comment by hemnath11** [comment]
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\c
okidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents
1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia3
"})

how to fix this

**Comment by omouse** [comment]
@hemnath11 there's nothing to fix, yours is working and correctly skipping installing the fsevents library since you're using Windows.

**Comment by hitao123** [comment]
```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
```
i meet this problem too! i was struggling with it! i want cry!!!

**Comment by sokra** [comment]
@hitao123 read the comment above!
