### ISSUE TITLE
Webpack 5 only compiles DOM urls, not node urls

### ISSUE THREAD

**Issue by Achder** [webpack/webpack#14417]
# Bug report

**What is the current behavior?**
Node URLs don't seem to get compiled.

**If the current behavior is a bug, please provide the steps to reproduce.**
Try to load a worker_thread with a node URL. The file won't get compiled correctly.

**What is the expected behavior?**
Webpack should follow the link and compile the referenced file.

**Other relevant information:**
webpack version:  
Node.js version: 
Operating System: 
Additional tools:

There exists a workaround where a DOM URL is used and then cast to a Node URL. 
See https://github.com/andywer/threads-plugin/issues/43#issuecomment-889719490

**Comment by alexander-akait** [comment]
What do you mean? Please provide reproducible test repo

**Comment by Achder** [comment]
Check out this repo: https://github.com/DustinJSilk/web-worker-ts-webpack-test

**Comment by vankop** [comment]
I think it is possible to define "your" worker. @sokra can you help with configuration in this case?

**Comment by alexander-akait** [comment]
@Achder Do you want bundle worker_thread for browser?

**Comment by alexander-akait** [comment]
@Achder example:
```
const path = require("path");
const HtmlWebpackPlugin = require("html-webpack-plugin");

module.exports = {
  entry: "./src/index.ts",
  mode: "development",
  devtool: false,
  target: "web",
  module: {
    rules: [
      {
        test: /.tsx?$/,
        loader: "ts-loader",
        exclude: /node_modules/,
      },
    ],
  },
  // we get `Worker` from `self`, you can use `globalThis` if your env supports it
  externals: [{
    "worker_threads": "self"
  }],
  output: {
    filename: "main.js",
    path: path.resolve(__dirname, "dist"),
  },
  plugins: [new HtmlWebpackPlugin()],
  resolve: {
    extensions: [".tsx", ".ts", "..."],
  },
};
```

**Comment by Achder** [comment]
I forgot to mention I'm running electron. I trying to use worker_threads from the main thread. It only worked with the mentioned fix.

**Comment by alexander-akait** [comment]
@Achder Please provide full steps to reproduce the problem

**Comment by Achder** [comment]
https://github.com/Achder/webpack-worker-bug
Critical line in index.ts line 57.
Workaround in comment below

**Comment by alexander-akait** [comment]
@alexander-akait I don't see workarounds here, what is your target? What is `Critical line in index.ts line 57.`?

**Comment by Achder** [comment]
I linked repo with a reproducible example. What else can I do?
https://github.com/Achder/webpack-worker-bug

**Comment by alexander-akait** [comment]
Change ` "worker_threads": "self"` on your global variables, if your env supports Workers, if not, it is impossible to do

**Comment by Achder** [comment]
Please download the example and try running it.

**Comment by vankop** [comment]
@Achder there is a check for `URL` here https://github.com/webpack/webpack/blob/main/lib/dependencies/WorkerPlugin.js#L104 , so webpack supports only `URL`

**Comment by Achder** [comment]
I do: https://github.com/Achder/webpack-worker-bug/blob/main/src/index.ts#L3

**Comment by Achder** [comment]
"Webpack 5 seems to only compile WebWorkers using a DOM URL, not Node Worker Threads when using a Node URL to point to the file."

**Comment by alexander-akait** [comment]
I don't see any problems with cast, it is not related

**Comment by vankop** [comment]
@Achder It should work:
```
import { URL } from 'url';
const worker = new Worker(new URL('./worker.ts', import.meta.url));
```

**Comment by Achder** [comment]
```
import { Worker } from 'worker_threads'
const worker = new Worker(new URL('./export.worker.ts', import.meta.url))
```

Is not working. It's giving me: 

> Argument of type 'URL' is not assignable to parameter of type 'string | URL'.

worker_threads need NodeURLs, not DOM URLs.

**Comment by alexander-akait** [comment]
> Argument of type 'URL' is not assignable to parameter of type 'string | URL'.

How it is related to webpack? It is typescript problem

**Comment by alexander-akait** [comment]
I can't run (`start`):
```
An unhandled exception has occurred inside Forge:
Cannot read property 'close' of undefined
TypeError: Cannot read property 'close' of undefined
```

`make`:
```
An unhandled rejection has occurred inside Forge:
Error: Cannot make for rpm, the following external binaries need to be installed: rpmbuild
    at MakerRpm.ensureExternalBinariesExist (/home/evilebottnawi/IdeaProjects/webpack-worker-bug/node_modules/@electron-forge/maker-base/src/Maker.ts:147:13)
    at _default (/home/evilebottnawi/IdeaProjects/webpack-worker-bug/node_modules/@electron-forge/core/src/api/make.ts:155:11)
    at /home/evilebottnawi/IdeaProjects/webpack-worker-bug/node_modules/@electron-forge/cli/src/electron-forge-make.ts:44:5

Electron Forge was terminated. Location:
{}
```

Again, please answer on my questions. Does your env supports `Worker`? Do you have `new URL` syntax supported by your env? What is your `target` for `Worker`? Try to remove `ts-loader` and reproduce it using pure JS. What is steps to reproduce?

**Comment by Achder** [comment]
It's a hacky workaround.
worker_threads should work with Node URLs. (and no, they do not. At least if you start importing stuff inside your worker)

**Comment by alexander-akait** [comment]
It already works, I can't reproduce, please provide full steps to reproduce the problem, I don't understand why do you ignore my questions
