### ISSUE TITLE
unable to load @webpack-cli/serve command

### ISSUE THREAD

**Issue by zendevil** [webpack/webpack#14443]
# Bug report

**What is the current behavior?**
doing `npm start` which runs `webpack serve --mode development --env development` gives:
```
[webpack-cli] Unable to load '@webpack-cli/serve' command
[webpack-cli] TypeError: options.forEach is not a function
    at WebpackCLI.makeCommand (/Users/prikshetsharma/Desktop/hello/node_modules/webpack-cli/lib/webpack-cli.js:108:21)
    at ServeCommand.apply (/Users/prikshetsharma/Desktop/hello/node_modules/webpack-cli/node_modules/@webpack-cli/serve/lib/index.js:41:19)
    at loadCommandByName (/Users/prikshetsharma/Desktop/hello/node_modules/webpack-cli/lib/webpack-cli.js:626:35)
    at Command.<anonymous> (/Users/prikshetsharma/Desktop/hello/node_modules/webpack-cli/lib/webpack-cli.js:1091:23)
    at Command.listener [as _actionHandler] (/Users/prikshetsharma/Desktop/hello/node_modules/webpack-cli/node_modules/commander/index.js:922:31)
    at Command._parseCommand (/Users/prikshetsharma/Desktop/hello/node_modules/webpack-cli/node_modules/commander/index.js:1503:14)
    at Command.parse (/Users/prikshetsharma/Desktop/hello/node_modules/webpack-cli/node_modules/commander/index.js:1292:10)
    at Command.parseAsync (/Users/prikshetsharma/Desktop/hello/node_modules/webpack-cli/node_modules/commander/index.js:1318:10)
    at WebpackCLI.run (/Users/prikshetsharma/Desktop/hello/node_modules/webpack-cli/lib/webpack-cli.js:1123:28)
    at runCLI (/Users/prikshetsharma/Desktop/hello/node_modules/webpack-cli/lib/bootstrap.js:11:19)
```

**If the current behavior is a bug, please provide the steps to reproduce.**

follow the steps here: 

https://smartcontracts.org/docs/quickstart/local-quickstart.html

webpack config:

https://github.com/zendevil/hello/blob/main/webpack.config.js

**What is the expected behavior?**

npm start works without an error and localhost:3000 is accessible.

**Other relevant information:**
webpack version:  5.24.4
Node.js version: v16.10.0
Operating System: macos big sur

**Comment by alexander-akait** [comment]
Duplicate https://github.com/webpack/webpack-cli/issues/2990

**Comment by alexander-akait** [comment]
Answer https://github.com/webpack/webpack-cli/issues/2990#issuecomment-937701533
