### ISSUE TITLE
webpack uses deprecated md4 hashFunction

### ISSUE THREAD

**Issue by manisandro** [webpack/webpack#14560]
# Bug report

**What is the current behavior?**
Throughout the webpack code, md4 is used as has function. md4 is deprecated, and disabled by default in openssl-3.0.0+ (https://www.openssl.org/docs/manmaster/man3/MD4_Final.html)

**If the current behavior is a bug, please provide the steps to reproduce.**
With any current webpack release, on a system with openssl-3.0.0 (i.e. Fedora rawhide), i.e. webpack serve will give

    9% setup compilation DefinePluginnode:internal/crypto/hash:67
    this[kHandle] = new _Hash(algorithm, xofLen);
                    ^

    Error: error:0308010C:digital envelope routines::unsupported
        at new Hash (node:internal/crypto/hash:67:19)
        at Object.createHash (node:crypto:130:10)
        at BulkUpdateDecorator.hashFactory (/home/sandro/Documents/Devel/berlinerglas/berlinerglas-webmap/node_modules/webpack/lib/util/createHash.js:155:18)
        at BulkUpdateDecorator.digest (/home/sandro/Documents/Devel/berlinerglas/berlinerglas-webmap/node_modules/webpack/lib/util/createHash.js:80:21)
        at /home/sandro/Documents/Devel/berlinerglas/berlinerglas-webmap/node_modules/webpack/lib/DefinePlugin.js:595:38
        at Hook.eval [as call] (eval at create (/home/sandro/Documents/Devel/berlinerglas/berlinerglas-webmap/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:198:1)
        at Hook.CALL_DELEGATE [as _call] (/home/sandro/Documents/Devel/berlinerglas/berlinerglas-webmap/node_modules/webpack/node_modules/tapable/lib/Hook.js:14:14)
        at Compiler.newCompilation (/home/sandro/Documents/Devel/berlinerglas/berlinerglas-webmap/node_modules/webpack/lib/Compiler.js:1053:26)
        at /home/sandro/Documents/Devel/berlinerglas/berlinerglas-webmap/node_modules/webpack/lib/Compiler.js:1097:29
        at Hook.eval [as callAsync] (eval at create (/home/sandro/Documents/Devel/berlinerglas/berlinerglas-webmap/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:22:1) {
    opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
    library: 'digital envelope routines',
    reason: 'unsupported',
    code: 'ERR_OSSL_EVP_UNSUPPORTED'
    }
    error Command failed with exit code 1.

**What is the expected behavior?**
No `ERR_OSSL_EVP_UNSUPPORTED` error

**Other relevant information:**

webpack version:  5.59.1
Node.js version: nodejs-16.11.1-1.fc36.x86_64 
Operating System: Fedora rawhide
Additional tools: -

Workaround:

    cd node_modules/webpack/lib
    find -type f -exec sed -i 's|md4|sha512|g' {} \;

**Comment by igaldino** [comment]
The workaround worked for me in Fedora 36, using node 16.

**Comment by AlvaroHeringer** [comment]
The workaround worked for me too, using Fedora 36.

**Comment by linux019** [comment]
ton of libs still use legacy md4

**Comment by koteisaev** [comment]
> ton of libs still use legacy md4

Some libs, like `file-loader` or `loader-utils`, seems to just ignore webpack settings, or may be it is too vague documented how to specify default hash options for `[contentHash]` placeHolders and alike at webpack config level and how to pass them on across plugins.
This is somewhere in side `interpolateName` and `getHashDigest` extracted from that obscure (to me) RegExp whose optional parameters seems to be not documented at all, but related to `[hash]` and `[contentHash]` interpolation tags.
```js
/\[(?:([^:\]]+):)?(?:hash|contenthash)(?::([a-z]+\d*))?(?::(\d+))?\]/gi,
        (all, hashType, digestType, maxLength) =>
          getHashDigest(content, hashType, digestType, parseInt(maxLength, 10))
      )
      .replace(/\[emoji(?::(\d+))?\]/gi, (all, length) =>
        encodeStringToEmoji(content, parseInt(length, 10))
      );
```
I was not able to get it working via template name, so has to fallback to node parameters about enabling obsolete SSL options with command line switch for webpack/grunt process.
