### ISSUE TITLE
Warning from PackFileCacheStrategy: Serializing big strings (747kiB) impacts deserialization performance (consider using Buffer instead and decode when needed)

### ISSUE THREAD

**Issue by Clarkkkk** [webpack/webpack#14666]
# Bug report

**What is the current behavior?**
The same warnings occur multiple times when compile is finished.
I add `console.trace()` as https://github.com/webpack-contrib/mini-css-extract-plugin/issues/643 mentioned.
```
[webpack.cache.PackFileCacheStrategy] Serializing big strings (361kiB) impacts deserialization performance (consider using Buffer instead and decode when needed)
Trace
    at process (C:\Users\...\react-ts\node_modules\webpack\lib\serialization\ObjectMiddleware.js:501:14)
    at write (C:\Users\...\react-ts\node_modules\webpack\lib\serialization\ObjectMiddleware.js:387:6)
    at PlainObjectSerializer.serialize (C:\Users\...\react-ts\node_modules\webpack\lib\serialization\PlainObjectSerializer.js:56:5)
    at process (C:\Users\...\react-ts\node_modules\webpack\lib\serialization\ObjectMiddleware.js:480:17)
    at write (C:\Users\...\react-ts\node_modules\webpack\lib\serialization\ObjectMiddleware.js:387:6)
    at MapObjectSerializer.serialize (C:\Users\...\react-ts\node_modules\webpack\lib\serialization\MapObjectSerializer.js:14:4)
    at process (C:\Users\...\react-ts\node_modules\webpack\lib\serialization\ObjectMiddleware.js:480:17)
    at write (C:\Users\...\react-ts\node_modules\webpack\lib\serialization\ObjectMiddleware.js:387:6)
    at PackContentItems.serialize (C:\Users\...\react-ts\node_modules\webpack\lib\cache\PackFileCacheStrategy.js:655:4)
    at ClassSerializer.serialize (C:\Users\...\react-ts\node_modules\webpack\lib\util\makeSerializable.js:15:7)
```

**If the current behavior is a bug, please provide the steps to reproduce.**
It is a pretty large project, and I cannot reproduce the issue currently. Maybe you can offer some instructions?

**What is the expected behavior?**
No warnings.

**Other relevant information:**
webpack version:  5.51.1
Node.js version: v16.13.0
Operating System: Windows 10

`package.json`
```json
  "dependencies": {
    "@ant-design/icons": "^4.0.0-alpha.18",
    "@antv/f2": "^3.6.4-beta.2",
    "@antv/g2": "^4.1.11",
    "@antv/g2plot": "^2.3.2",
    "@babel/runtime": "^7.6.3",
    "@babel/runtime-corejs3": "^7.7.7",
    "@loadable/component": "^5.10.3",
    "@material-ui/core": "^4.8.3",
    "@material-ui/styles": "^4.9.14",
    "@reduxjs/toolkit": "^1.6.1",
    "@tippyjs/react": "^4.2.5",
    "@types/numeral": "0.0.28",
    "animate.css": "^3.7.2",
    "antd": "4.1.4",
    "antd-dayjs-webpack-plugin": "^1.0.0",
    "antd-mobile": "^2.3.1",
    "axios": "^0.21.1",
    "better-xlsx": "^0.7.5",
    "bignumber.js": "^9.0.0",
    "bizcharts": "^3.5.9",
    "bizgoblin": "^0.2.0",
    "blueimp-md5": "^2.12.0",
    "classnames": "^2.3.1",
    "copy-to-clipboard": "^3.3.1",
    "crypto-js": "^3.1.9-1",
    "dayjs": "^1.8.18",
    "file-saver": "^2.0.5",
    "fingerprintjs2": "^2.1.0",
    "html2canvas": "1.0.0-rc.4",
    "jquery": "^3.5.1",
    "js-audio-recorder": "^1.0.7",
    "js-base64": "^2.5.1",
    "js-cookie": "^2.2.1",
    "jstz": "^2.1.1",
    "klinecharts": "7.5.0",
    "lamejs": "^1.2.0",
    "lodash": "^4.17.15",
    "lodash.random": "^3.2.0",
    "lodash.samplesize": "^4.2.0",
    "moment": "^2.29.1",
    "numeral": "^2.0.6",
    "pako": "^1.0.10",
    "qrcode.react": "^1.0.0",
    "qs": "^6.9.1",
    "react": "^17.0.2",
    "react-color": "^2.19.3",
    "react-content-loader": "^4.3.4",
    "react-copy-to-clipboard": "^5.0.3",
    "react-dom": "^17.0.2",
    "react-globe": "^5.0.2",
    "react-grid-layout": "^1.1.1",
    "react-helmet": "^6.1.0",
    "react-lazyload": "^2.6.5",
    "react-number-format": "^4.3.1",
    "react-redux": "^7.2.4",
    "react-router-dom": "^5.2.1",
    "react-slick": "^0.26.1",
    "react-transition-group": "^4.4.2",
    "reconnecting-websocket": "^4.2.0",
    "redux": "^4.1.1",
    "redux-thunk": "^2.3.0",
    "slick-carousel": "^1.8.1",
    "sprintf-js": "^1.1.2",
    "three": "0.109.0",
    "tim-js-sdk": "^2.15.0",
    "tim-upload-plugin": "^1.0.3",
    "trading-view": "^1.0.7",
    "trim-newlines": "^3.0.1",
    "ua-parser-js": "^0.7.20",
    "use-error-boundary": "^2.0.6",
    "use-long-press": "^1.1.1",
    "web-widget": "^0.3.6"
  },
  "devDependencies": {
    "@babel/core": "^7.15.0",
    "@babel/plugin-proposal-class-properties": "^7.14.5",
    "@babel/plugin-proposal-nullish-coalescing-operator": "^7.14.5",
    "@babel/plugin-proposal-optional-chaining": "^7.14.5",
    "@babel/plugin-transform-runtime": "^7.15.0",
    "@babel/plugin-transform-typescript": "^7.15.4",
    "@babel/preset-env": "^7.15.0",
    "@babel/preset-react": "^7.14.5",
    "@babel/preset-typescript": "^7.15.0",
    "@pmmmwh/react-refresh-webpack-plugin": "^0.5.0-rc.6",
    "@types/blueimp-md5": "^2.7.0",
    "@types/crypto-js": "^3.1.43",
    "@types/file-saver": "^2.0.1",
    "@types/fingerprintjs2": "^2.0.0",
    "@types/jquery": "^3.5.5",
    "@types/js-base64": "^2.3.1",
    "@types/js-cookie": "^2.2.4",
    "@types/loadable__component": "^5.10.0",
    "@types/lodash": "^4.14.144",
    "@types/mockjs": "^1.0.2",
    "@types/node": "^12.12.47",
    "@types/pako": "^1.0.1",
    "@types/puppeteer": "^3.0.1",
    "@types/qrcode.react": "^1.0.0",
    "@types/qs": "^6.5.3",
    "@types/react": "^16.9.34",
    "@types/react-copy-to-clipboard": "^4.3.0",
    "@types/react-dom": "^16.9.6",
    "@types/react-grid-layout": "^0.17.2",
    "@types/react-helmet": "^5.0.16",
    "@types/react-lazyload": "^2.6.0",
    "@types/react-redux": "^7.1.5",
    "@types/react-router-dom": "^5.1.1",
    "@types/react-slick": "^0.23.4",
    "@types/sprintf-js": "^1.1.2",
    "@types/ua-parser-js": "^0.7.33",
    "@types/webpack-env": "^1.16.0",
    "@typescript-eslint/eslint-plugin": "^2.6.0",
    "@typescript-eslint/parser": "^2.6.0",
    "autoprefixer": "^10.3.6",
    "babel-eslint": "^10.0.3",
    "babel-loader": "^8.0.6",
    "babel-plugin-import": "^1.12.2",
    "babel-plugin-lodash": "^3.3.4",
    "circular-dependency-plugin": "^5.2.0",
    "clean-webpack-plugin": "^3.0.0",
    "css-loader": "^6.3.0",
    "css-minimizer-webpack-plugin": "^3.0.2",
    "eslint": "^6.6.0",
    "eslint-config-standard": "^14.1.1",
    "eslint-plugin-import": "^2.22.1",
    "eslint-plugin-node": "^10.0.0",
    "eslint-plugin-promise": "^4.2.1",
    "eslint-plugin-react": "^7.16.0",
    "eslint-plugin-standard": "^4.0.1",
    "fibers": "^5.0.0",
    "fork-ts-checker-webpack-plugin": "^6.3.2",
    "html-webpack-plugin": "^5.3.2",
    "image-minimizer-webpack-plugin": "^2.2.0",
    "imagemin-gifsicle": "^7.0.0",
    "imagemin-jpegtran": "^7.0.0",
    "imagemin-optipng": "^8.0.0",
    "imagemin-pngquant": "^9.0.2",
    "imagemin-svgo": "^9.0.0",
    "less": "^3.10.3",
    "less-loader": "^10.0.1",
    "mini-css-extract-plugin": "^2.2.0",
    "mockjs": "^1.1.0",
    "postcss": "^8.3.6",
    "postcss-loader": "^6.1.1",
    "puppeteer": "^4.0.1",
    "react-refresh": "^0.10.0",
    "redux-devtools-extension": "^2.13.8",
    "sass": "^1.38.1",
    "sass-loader": "^12.1.0",
    "shelljs": "^0.8.4",
    "speed-measure-webpack-plugin": "^1.5.0",
    "style-loader": "^1.0.0",
    "terser-webpack-plugin": "^3.0.0",
    "timers-browserify": "^2.0.12",
    "ts-node": "^8.10.2",
    "typescript": "^4.4.2",
    "webpack": "^5.51.1",
    "webpack-bundle-analyzer": "^4.4.2",
    "webpack-cli": "^4.8.0",
    "webpack-dev-server": "^4.0.0",
    "webpack-merge": "^5.8.0",
    "webpackbar": "^5.0.0-3",
    "yargs": "^15.3.1"
  }
```

`webpack.config.js`
```js
module.exports = {
  entry: {
    main: './src/index.tsx'
  },
  mode: 'production',
  stats: "errors-only",
  resolve: {
    symlinks: false,
    extensions: [ '.tsx', '.ts', '.js', '.jsx' ],
    fallback: {
      'timers': require.resolve('timers-browserify')
    }
  },
  output: {
    chunkFilename: `${buildRoot}/[name]-[contenthash:8].min.js`,
    filename: `${buildRoot}/[name]-[contenthash:8].min.js`,
  },
  cache: {
    type: 'filesystem',
    name: `${projectName}_${isRelease ? 'release' : 'prod'}`,
    buildDependencies: {
      config: [ __filename ]
    },
  },
  module: {
    rules: [ {
      test: /\.[tj]sx?$/,
      exclude: /node_modules/,
      use: [
        'babel-loader?cacheDirectory',
      ]
    },
    {
      test: /\.less$/,
      use: [
        {
          loader: MiniCssExtractPlugin.loader,
          options: {
            publicPath: '../'
          }
        },
        'css-loader',
        {
          loader: 'less-loader',
          options: {
            lessOptions: {
              modifyVars: {
                styleVariables, '@primary-color': '#00d0c4'
              },
              javascriptEnabled: true
            }
          }
        }
      ]
    },
    {
      test: /\.css$/,
      include: /node_modules/,
      use: [
        {
          loader: MiniCssExtractPlugin.loader,
          options: {
            publicPath: '../'
          }
        },
        'css-loader',
        'postcss-loader',
      ]
    },
    {
      test: /\.(sa|sc)ss$/,
      exclude: /node_modules/,
      use: [
        {
          loader: MiniCssExtractPlugin.loader,
          options: {
            publicPath: '../'
          }
        },
        {
          loader: 'css-loader',
          options: {
            modules: {
              exportLocalsConvention: 'camelCase'
            },
          }
        },
        'postcss-loader',
        {
          loader: 'sass-loader',
          options: {
            sassOptions: {
              charset: false
            },
            additionalData: Object.keys(styleVariables)
              .map(k => `$${k}: ${styleVariables[ k ]};`)
              .join('\n')
          }
        }
      ]
    },
    {
      test: /\.(jpe?g|png|gif|webp|svg)$/i,
      type: 'asset',
      generator: {
        filename: `${buildRoot}/images/[name]-[contenthash:8][ext]`,
        publicPath: '../../'
      },
      parser: {
        dataUrlCondition: {
          maxSize: 5 * 1024
        }
      }
    },
    {
      test: /\.(woff|eot|ttf|otf)$/i,
      type: 'asset/resource',
      generator: {
        filename: `${buildRoot}/font/[name]-[contenthash:8][ext]`,
        publicPath: '../../'
      }
    } ]
  },
  externals: {
    react: 'React',
    'react-dom': 'ReactDOM'
  },
  plugins: [
    new CleanWebpackPlugin({
      cleanOnceBeforeBuildPatterns: [ buildRoot ]
    }),

    new MiniCssExtractPlugin({
      filename: `${buildRoot}/css/[name]-[contenthash:8].min.css`,
      ignoreOrder: true
    }),

    new HtmlWebpackPlugin(),
  ],
  optimization: {
    runtimeChunk: 'single',
    moduleIds: 'deterministic',
    minimizer: [
      new TerserPlugin(),
      new CssMinimizerPlugin(),
      new ImageMinimizerPlugin({
        test: /\.(jpe?g|png|gif|svg)$/i,
        severityError: 'warning',
        filter: (source) => source.byteLength > 50000,
        minimizerOptions: {
          plugins: [
            [ 'jpegtran', {progressive: true} ],
            [ 'pngquant', {
              speed: 10
            } ],
            [ 'optipng', {
              optimizationLevel: 0
            } ],
            [ 'svgo' ],
          ],
        }
      })
    ]
  }
}
```

**Comment by alexander-akait** [comment]
I think problem in `babel-loader`, as you can read from warning, need to use `Buffer`, we can't fix it here

**Comment by alexander-akait** [comment]
Run `npx webpack-cli info`

**Comment by Clarkkkk** [comment]
> I think problem in `babel-loader`, as you can read from warning, need to use `Buffer`, we can't fix it here

Thanks for your reply, should I open an issue in [babel-loader](https://github.com/babel/babel-loader)?

> Run `npx webpack-cli info`

Here is the result:
```
System:
    OS: Windows 10 10.0.22000
    CPU: (16) x64 AMD Ryzen 7 5800 8-Core Processor
    Memory: 8.53 GB / 15.87 GB
  Binaries:
    Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
    npm: 7.24.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (95.0.1020.44)
    Internet Explorer: 11.0.22000.120
  Packages:
    antd-dayjs-webpack-plugin: ^1.0.0 => 1.0.6 
    clean-webpack-plugin: ^3.0.0 => 3.0.0 
    css-minimizer-webpack-plugin: ^3.0.2 => 3.0.2 
    fork-ts-checker-webpack-plugin: ^6.3.2 => 6.3.3 
    html-webpack-plugin: ^5.3.2 => 5.3.2 
    image-minimizer-webpack-plugin: ^2.2.0 => 2.2.0 
    speed-measure-webpack-plugin: ^1.5.0 => 1.5.0 
    terser-webpack-plugin: ^3.0.0 => 3.1.0 
    webpack: ^5.51.1 => 5.55.1 
    webpack-bundle-analyzer: ^4.4.2 => 4.4.2 
    webpack-cli: ^4.8.0 => 4.8.0 
    webpack-dev-server: ^4.0.0 => 4.3.0 
    webpack-merge: ^5.8.0 => 5.8.0 
    webpackbar: ^5.0.0-3 => 5.0.0-3 
```

**Comment by alexander-akait** [comment]
Can you try to update deps firstly to the latest?

**Comment by Clarkkkk** [comment]
Warnings remain after updating deps.
```
System:
    OS: Windows 10 10.0.22000
    CPU: (16) x64 AMD Ryzen 7 5800 8-Core Processor
    Memory: 9.98 GB / 15.87 GB
  Binaries:
    Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (95.0.1020.44)
    Internet Explorer: 11.0.22000.120
  Packages:
    antd-dayjs-webpack-plugin: ^1.0.0 => 1.0.6 
    babel-loader: ^8.0.6 => 8.2.3 
    clean-webpack-plugin: ^3.0.0 => 3.0.0 
    css-loader: ^6.3.0 => 6.5.1 
    css-minimizer-webpack-plugin: ^3.0.2 => 3.1.1 
    fork-ts-checker-webpack-plugin: ^6.3.2 => 6.4.0 
    html-webpack-plugin: ^5.3.2 => 5.5.0 
    image-minimizer-webpack-plugin: ^2.2.0 => 2.2.0 
    less-loader: ^10.0.1 => 10.2.0 
    postcss-loader: ^6.1.1 => 6.2.0 
    react-content-loader: ^4.3.4 => 4.3.4 
    sass-loader: ^12.1.0 => 12.3.0 
    speed-measure-webpack-plugin: ^1.5.0 => 1.5.0 
    style-loader: ^1.0.0 => 1.3.0 
    terser-webpack-plugin: ^3.0.0 => 3.1.0 
    webpack: ^5.51.1 => 5.62.1 
    webpack-bundle-analyzer: ^4.4.2 => 4.5.0 
    webpack-cli: ^4.8.0 => 4.9.1 
    webpack-dev-server: ^4.0.0 => 4.4.0 
    webpack-merge: ^5.8.0 => 5.8.0 
    webpackbar: ^5.0.0-3 => 5.0.2 
```

Plus, Module build failed with `mini-css-extract-plugin@2.4.4` (OK with `@2.3.9`). I may open another issue in that repo.

**Comment by alexander-akait** [comment]
Yes, let's do it and can you provide small example, we need investigate it

**Comment by Clarkkkk** [comment]
I need some time to reproduce it.
The error info is like this:
```
ERROR in ./src/pages/theminvite/components/Head/Head.module.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
HookWebpackError: Invalid URL
    at tryRunOrWebpackError (C:\Users\...\react-ts\node_modules\webpack\lib\HookWebpackError.js:88:9)
    at __webpack_require_module__ (C:\Users\...\react-ts\node_modules\webpack\lib\Compilation.js:4976:12)
    at __webpack_require__ (C:\Users\...\react-ts\node_modules\webpack\lib\Compilation.js:4933:18)
    at C:\Users\...\react-ts\node_modules\webpack\lib\Compilation.js:5004:20
    at symbolIterator (C:\Users\...\react-ts\node_modules\neo-async\async.js:3485:9)
    at done (C:\Users\...\react-ts\node_modules\neo-async\async.js:3527:9)
    at Hook.eval [as callAsync] (eval at create (C:\Users\...\react-ts\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
    at C:\Users\...\react-ts\node_modules\webpack\lib\Compilation.js:4911:43
    at symbolIterator (C:\Users\...\react-ts\node_modules\neo-async\async.js:3482:9)
    at timesSync (C:\Users\...\react-ts\node_modules\neo-async\async.js:2297:7)
-- inner error --
TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:371:5)
    at onParseError (node:internal/url:552:9)
    at new URL (node:internal/url:628:5)
    at Module.<anonymous> (C:\Users\...\react-ts\node_modules\css-loader\dist\cjs.js??ruleSet[1].rules[3].use[1]!C:\Users\...\react-ts\node_modules\postcss-loader\dist\cjs.js!C:\Users\...\react-ts\node_modules\sass-loader\dist\cjs.js??ruleSet[1].rules[3].use[3]!C:\Users\...\react-ts\src\pages\theminvite\components\Head\Head.module.scss:12:37)
    at C:\Users\...\react-ts\node_modules\webpack\lib\javascript\JavascriptModulesPlugin.js:432:11
    at Hook.eval [as call] (eval at create (C:\Users\...\react-ts\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:7:1)
    at C:\Users\...\react-ts\node_modules\webpack\lib\Compilation.js:4978:39
    at tryRunOrWebpackError (C:\Users\...\react-ts\node_modules\webpack\lib\HookWebpackError.js:83:7)
    at __webpack_require_module__ (C:\Users\...\react-ts\node_modules\webpack\lib\Compilation.js:4976:12)
    at __webpack_require__ (C:\Users\...\react-ts\node_modules\webpack\lib\Compilation.js:4933:18)

Generated code for C:\Users\...\react-ts\node_modules\css-loader\dist\cjs.js??ruleSet[1].rules[3].use[1]!C:\Users\...\react-ts\node_modules\postcss-loader\dist\cjs.js!C:\Users\...\react-ts\node_modules\sass-loader\dist\cjs.js??ruleSet[1].rules[3].use[3]!C:\Users\...\react-ts\src\pages\theminvite\components\Head\Head.module.scss 
 1 | __webpack_require__.r(__webpack_exports__);
 2 | /* harmony import */ var _node_modules_css_loader_dist_runtime_noSourceMaps_js__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__("C:\\Users\\...\\react-ts\\node_modules\\css-loader\\dist\\runtime\\noSourceMaps.js");
 3 | /* harmony import */ var _node_modules_css_loader_dist_runtime_noSourceMaps_js__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(_node_modules_css_loader_dist_runtime_noSourceMaps_js__WEBPACK_IMPORTED_MODULE_0__);
 4 | /* harmony import */ var _node_modules_css_loader_dist_runtime_api_js__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__("C:\\Users\\...\\react-ts\\node_modules\\css-loader\\dist\\runtime\\api.js");
 5 | /* harmony import */ var _node_modules_css_loader_dist_runtime_api_js__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/__webpack_require__.n(_node_modules_css_loader_dist_runtime_api_js__WEBPACK_IMPORTED_MODULE_1__);       
 6 | /* harmony import */ var _node_modules_css_loader_dist_runtime_getUrl_js__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__("C:\\Users\\...\\react-ts\\node_modules\\css-loader\\dist\\runtime\\getUrl.js");
 7 | /* harmony import */ var _node_modules_css_loader_dist_runtime_getUrl_js__WEBPACK_IMPORTED_MODULE_2___default = /*#__PURE__*/__webpack_require__.n(_node_modules_css_loader_dist_runtime_getUrl_js__WEBPACK_IMPORTED_MODULE_2__); 
 8 | // Imports
 9 | 
10 | 
11 | 
12 | var ___CSS_LOADER_URL_IMPORT_0___ = new URL(/* asset import */ __webpack_require__("asset|C:\\Users\\...\\react-ts\\node_modules\\image-minimizer-webpack-plugin\\dist\\loader.js??ruleSet[1].rules[7]!C:\\Users\\...\\react-ts\\src\\pages\\theminvite\\components\\Head\\assets\\bg@2x.png"), __webpack_require__.b);
13 | var ___CSS_LOADER_EXPORT___ = _node_modules_css_loader_dist_runtime_api_js__WEBPACK_IMPORTED_MODULE_1___default()((_node_modules_css_loader_dist_runtime_noSourceMaps_js__WEBPACK_IMPORTED_MODULE_0___default()));
14 | var ___CSS_LOADER_URL_REPLACEMENT_0___ = _node_modules_css_loader_dist_runtime_getUrl_js__WEBPACK_IMPORTED_MODULE_2___default()(___CSS_LOADER_URL_IMPORT_0___);
15 | // Module
16 | ___CSS_LOADER_EXPORT___.push([module.id, ".OEFQEmjpsR6GDesDjBOc{display:flex;justify-content:space-between;min-height:700px;padding-top:42px;padding-bottom:58px}.OEFQEmjpsR6GDesDjBOc::after{position:absolute;z-index:-1;top:80px;right:0;left:0;height:700px;content:\"\";background-color:#15205a;background-image:url(" + ___CSS_LOADER_URL_REPLACEMENT_0___ + ");background-repeat:no-repeat;background-position:center;background-size:1920px auto}.OEFQEmjpsR6GDesDjBOc h2{font-size:52px;font-weight:500;line-height:57px;margin-top:34px;margin-bottom:20px;color:#fff}.OEFQEmjpsR6GDesDjBOc h3{font-size:34px;font-weight:500;line-height:37px;margin:0;color:#fff}.OEFQEmjpsR6GDesDjBOc h3:first-of-type{margin-bottom:20px}.hbZjo__sDmVazi3qnzJK{align-self:center}.hbZjo__sDmVazi3qnzJK>p{font-size:18px;font-weight:500;line-height:24px;max-width:460px;margin-bottom:29px;color:#00ccc2}.qfoaVBIoVTJCZmmX_o_N{width:434px}.nOky6SSqHSSJ46iober6{font-size:14px;font-weight:400;line-height:18px;margin:23px 0 0 0;color:#333}", ""]);
17 | // Exports
18 | ___CSS_LOADER_EXPORT___.locals = {
19 |    "root": "OEFQEmjpsR6GDesDjBOc",
20 |    "reg-container": "hbZjo__sDmVazi3qnzJK",
21 |    "regContainer": "hbZjo__sDmVazi3qnzJK",
22 |    "reg": "qfoaVBIoVTJCZmmX_o_N",
23 |    "footer": "nOky6SSqHSSJ46iober6"
24 | };
25 | /* harmony default export */ __webpack_exports__["default"] = (___CSS_LOADER_EXPORT___);
26 | 
 @ ./src/pages/theminvite/components/Head/Head.tsx 1:148-186 1:431-441 1:656-674 1:867-876 1:949-961
 @ ./src/pages/theminvite/components/index.ts 1:0-25 1:0-25
 @ ./src/pages/theminvite/index.tsx 1:132-186 1:738-742 1:765-777 1:800-809
 @ ./src/pages/****/Routes/routes.tsx
 @ ./src/pages/****/index.tsx 1:1354-1391 4:619-630
 @ ./src/routes.ts
 @ ./src/index.tsx 1:1297-1332 2:614-626
```

**Comment by alexander-akait** [comment]
It means you try to improve URL above your root of project

**Comment by Clarkkkk** [comment]
The `output` config is like this:
```
// ...
path: path.resolve(__dirname, `../../../${gitRepository}/dist'}/`),
publicPath: '/',
// ...
```
You're right. The `path` is indeed above the root of project, in another repo. But it does work with `mini-css-extract-plugin@2.3.0` 😂.

**Comment by alexander-akait** [comment]
I recommend to avoid using `publicPath: '/'`, just use `auto` value (default)

**Comment by vankop** [comment]
> I recommend to avoid using `publicPath: '/'`, just use `auto` value (default)

`publicPath: '/'` is fine, auto adds some small webpack runtime. @alexander-akait

**Comment by alexander-akait** [comment]
@vankop yes, but it will add more flexibility way to calculate public path, I want to say it is recommend by default

**Comment by Clarkkkk** [comment]
> I recommend to avoid using `publicPath: '/'`, just use `auto` value (default)

Thanks for your advice. I will study it. Back to this issue, is there any other information you need? Or I still need to provide a reproduce example?

**Comment by alexander-akait** [comment]
Will be great if you provide example

**Comment by Clarkkkk** [comment]
It turns out I'm use an old version of `terser-webpack-plugin`😂. Solved by updating the plugin to the latest version
