### ISSUE TITLE
WebPack 5.62.0 raises "Unexpected token: punc ()) "

### ISSUE THREAD

**Issue by Carsten-Leue** [webpack/webpack#14662]
After upgrading to `5.62.0` I am getting:
```
ERROR in main.js
main.js from Terser plugin
Unexpected token: punc ()) [webpack://./node_modules/graceful-fs/graceful-fs.js:87,6][main.js:41529,37]
    at js_error (C:\d\blaze-secrets-injector-cli-deb\node_modules\terser\dist\bundle.min.js:550:11)
    at croak (C:\d\blaze-secrets-injector-cli-deb\node_modules\terser\dist\bundle.min.js:1274:9)
    at token_error (C:\d\blaze-secrets-injector-cli-deb\node_modules\terser\dist\bundle.min.js:1282:9)
    at unexpected (C:\d\blaze-secrets-injector-cli-deb\node_modules\terser\dist\bundle.min.js:1288:9)
    at semicolon (C:\d\blaze-secrets-injector-cli-deb\node_modules\terser\dist\bundle.min.js:1326:56)
    at simple_statement (C:\d\blaze-secrets-injector-cli-deb\node_modules\terser\dist\bundle.min.js:1583:73)
    at statement (C:\d\blaze-secrets-injector-cli-deb\node_modules\terser\dist\bundle.min.js:1396:19)
    at _embed_tokens_wrapper (C:\d\blaze-secrets-injector-cli-deb\node_modules\terser\dist\bundle.min.js:1339:26)
    at block_ (C:\d\blaze-secrets-injector-cli-deb\node_modules\terser\dist\bundle.min.js:2172:20)
    at _function_body (C:\d\blaze-secrets-injector-cli-deb\node_modules\terser\dist\bundle.min.js:2084:21)
```

Compiling the identical project with `5.61.0` is working without errors.

**Comment by Carsten-Leue** [comment]
```js
const webpack = require('webpack');

module.exports = {
  entry: './index.js',
  devtool: 'source-map',
  target: 'node14',
  mode: 'production',
  resolve: {
    extensions: ['.js'],
  },
  plugins: [
    new webpack.BannerPlugin({
      banner: '#!/usr/bin/env node',
      raw: true,
    }),
  ],
};

```

**Comment by sokra** [comment]
Could you disable `optimization.minimize: true` and look into line `main.js:41529`?

**Comment by cbartondock** [comment]
I am also seeing this error after upgrading from 5.61 to 5.62

**Comment by sokra** [comment]
Found the problem... Fixing...

**Comment by sokra** [comment]
https://github.com/webpack/webpack/releases/tag/v5.62.1
