### ISSUE TITLE
Maximum call stack size exceeded occurs when loading a large script into Webpack.

### ISSUE THREAD

**Issue by logue** [webpack/webpack#14742]
When I try to process a large file (8M) with Webpack, it stops with the error `HookWebpackError: Maximum call stack size exceeded`.

```
 ERROR  HookWebpackError: Maximum call stack size exceeded
HookWebpackError: Maximum call stack size exceeded
    at makeWebpackError (E:\Documents\Projects\NgsWebTool\node_modules\webpack\lib\HookWebpackError.js:48:9)
    at E:\Documents\Projects\NgsWebTool\node_modules\webpack\lib\Compilation.js:3055:12
    at eval (eval at create (E:\Documents\Projects\NgsWebTool\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:54:1)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
-- inner error --
RangeError: Maximum call stack size exceeded
    at String.match (<anonymous>)
    at OriginalSource.streamChunks (E:\Documents\Projects\NgsWebTool\node_modules\webpack\node_modules\webpack-sources\lib\OriginalSource.js:64:32)
    at module.exports (E:\Documents\Projects\NgsWebTool\node_modules\webpack\node_modules\webpack-sources\lib\helpers\streamChunks.js:13:17)
    at ReplaceSource.streamChunks (E:\Documents\Projects\NgsWebTool\node_modules\webpack\node_modules\webpack-sources\lib\ReplaceSource.js:175:44)
    at module.exports (E:\Documents\Projects\NgsWebTool\node_modules\webpack\node_modules\webpack-sources\lib\helpers\streamChunks.js:13:17)
    at ConcatSource.streamChunks (E:\Documents\Projects\NgsWebTool\node_modules\webpack\node_modules\webpack-sources\lib\ConcatSource.js:112:55)
    at module.exports (E:\Documents\Projects\NgsWebTool\node_modules\webpack\node_modules\webpack-sources\lib\helpers\streamChunks.js:13:17)
    at streamAndGetSourceAndMap (E:\Documents\Projects\NgsWebTool\node_modules\webpack\node_modules\webpack-sources\lib\helpers\streamAndGetSourceAndMap.js:27:53)
    at CachedSource.streamChunks (E:\Documents\Projects\NgsWebTool\node_modules\webpack\node_modules\webpack-sources\lib\CachedSource.js:208:35)
    at module.exports (E:\Documents\Projects\NgsWebTool\node_modules\webpack\node_modules\webpack-sources\lib\helpers\streamChunks.js:13:17)
    at ConcatSource.streamChunks (E:\Documents\Projects\NgsWebTool\node_modules\webpack\node_modules\webpack-sources\lib\ConcatSource.js:112:55)
    at module.exports (E:\Documents\Projects\NgsWebTool\node_modules\webpack\node_modules\webpack-sources\lib\helpers\streamChunks.js:13:17)
    at streamAndGetSourceAndMap (E:\Documents\Projects\NgsWebTool\node_modules\webpack\node_modules\webpack-sources\lib\helpers\streamAndGetSourceAndMap.js:27:53)
    at CachedSource.streamChunks (E:\Documents\Projects\NgsWebTool\node_modules\webpack\node_modules\webpack-sources\lib\CachedSource.js:208:35)
    at module.exports (E:\Documents\Projects\NgsWebTool\node_modules\webpack\node_modules\webpack-sources\lib\helpers\streamChunks.js:13:17)
    at ConcatSource.streamChunks (E:\Documents\Projects\NgsWebTool\node_modules\webpack\node_modules\webpack-sources\lib\ConcatSource.js:112:55)
```

This error occurs when opencv.js is loaded, so I temporarily externalize it using externals and manually write a script tag on the index.html side to deal with it, but is there a better way?

```
module.exports = {
  // ...
  externals: {
    '@techstark/opencv-js': 'cv',
  },
  // ...
  plugins: [
     new CopyPlugin({
        patterns: [
          {
            from: 'node_modules/@techstark/opencv-js/dist/opencv.js',
            to: 'js',
            force: true,
          },
        ],
      }),
  ],
}
```

**Comment by sokra** [comment]
This was fixed by https://github.com/webpack/webpack-sources/pull/142

Please upgrade to the latest version of webpack-sources or webpack.

**Comment by vankop** [comment]
Answer above, feel free to feedback
