### ISSUE TITLE
Webpack unable to resolve loaders path contains a special character

### ISSUE THREAD

**Issue by alan-agius4** [webpack/webpack#14755]
**What is the current behavior?**
When the path contains a special character Webpack is unable to correctly resolve loaders.

**If the current behavior is a bug, please provide the steps to reproduce.**
- Create a directory with a special character, example `/Users/reproductions/webpack-#`
- Install and configure a loader 
- Run Webpack

Config
```js
const { resolve } = require("path");

module.exports = {
  mode: "development",
  entry: "./index.js",
  output: {
    path: resolve(__dirname, "dist"),
    filename: "[name].js",
  },
  module: {
    rules: [
      {
        test: /.css/,
        loader: 'postcss-loader',
      },
    ],
  }
};
```

**What is the expected behavior?**
Build works, but instead it errors out with the below

```
➜  webpack-# git:(main) ✗ yarn webpack
yarn run v1.22.17
$ '/Users/reproductions/webpack-#/node_modules/.bin/webpack'
asset main.js 3.39 KiB [compared for emit] (name: main)
../webpack-#/index.js 39 bytes [not cacheable] [built] [code generated] [1 error]

ERROR in ../webpack-#/index.js
Module build failed (from ../webpack-#/node_modules/postcss-loader/dist/cjs.js):
Error: Cannot find module '/Users/reproductions/webpack-#/node_modules/postcss-loader/dist/cjs.js'
Require stack:
- /Users/reproductions/webpack-#/node_modules/loader-runner/lib/loadLoader.js
- /Users/reproductions/webpack-#/node_modules/loader-runner/lib/LoaderRunner.js
- /Users/reproductions/webpack-#/node_modules/webpack/lib/NormalModuleFactory.js
- /Users/reproductions/webpack-#/node_modules/webpack/lib/Compiler.js
- /Users/reproductions/webpack-#/node_modules/webpack/lib/webpack.js
- /Users/reproductions/webpack-#/node_modules/webpack/lib/index.js
- /Users/reproductions/webpack-#/node_modules/webpack-cli/lib/webpack-cli.js
- /Users/reproductions/webpack-#/node_modules/webpack-cli/lib/bootstrap.js
- /Users/reproductions/webpack-#/node_modules/webpack-cli/bin/cli.js
- /Users/reproductions/webpack-#/node_modules/webpack/bin/webpack.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at loadLoader (/Users/reproductions/webpack-#/node_modules/loader-runner/lib/loadLoader.js:19:17)
    at iteratePitchingLoaders (/Users/reproductions/webpack-#/node_modules/loader-runner/lib/LoaderRunner.js:182:2)
    at runLoaders (/Users/reproductions/webpack-#/node_modules/loader-runner/lib/LoaderRunner.js:397:2)
    at NormalModule._doBuild (/Users/reproductions/webpack-#/node_modules/webpack/lib/NormalModule.js:812:3)
    at NormalModule.build (/Users/reproductions/webpack-#/node_modules/webpack/lib/NormalModule.js:956:15)
    at /Users/reproductions/webpack-#/node_modules/webpack/lib/Compilation.js:1367:12

webpack 5.64.0 compiled with 1 error in 79 ms
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.




// Check with Yarn
yarn why postcss-loader
yarn why v1.22.17
warning package.json: No license field
warning ../package.json: No license field
[1/4] 🤔  Why do we have the module "postcss-loader"...?
[2/4] 🚚  Initialising dependency graph...
warning No license field
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "postcss-loader@6.2.0"
info Has been hoisted to "postcss-loader"
info This module exists because it's specified in "dependencies".
info Disk size without dependencies: "108KB"
info Disk size with unique dependencies: "688KB"
info Disk size with transitive dependencies: "1.92MB"
info Number of shared dependencies: 6
✨  Done in 0.15s.



// File exists
➜  webpack-# git:(main) ✗ cat /Users/reproductions/webpack-#/node_modules/postcss-loader/dist/cjs.js
"use strict";

module.exports = require("./index").default;
```

**Other relevant information:**
webpack version:  "5.64.0
Node.js version: 16.13.0
Operating System: darwin x64
Additional tools:

**Comment by vankop** [comment]
Thanks for your report, this was fixed some times ago.. maybe we did not fix problem with loader.
