### ISSUE TITLE
node-loader -  unable to load native Node.js module

### ISSUE THREAD

**Issue by zam6ak** [webpack/webpack#1481]
I have explained entire issue in more detail on this SO question.
http://stackoverflow.com/questions/32832179/using-webpack-with-nodejs-native-modules

After mode investigation, I have noticed that the error message is coming from node-loader:
see: https://github.com/webpack/node-loader/blob/master/index.js

If I run the app without webpack, everything works and module loads.
For posterity, here is the error with stacktrace once more:

```
Error: Cannot open X:\myapp\lib\modules\my-module\build\Release\mymodule.node: Error: The specified module could not be found.
[object Object]
    at Object.<anonymous> (X:\myapp\main-backend.bundle.js:23043:162)
    at __webpack_require__ (X:\myapp\main-backend.bundle.js:20:30)
    at Object.<anonymous> (X:\myapp\main-backend.bundle.js:23019:21)
    at __webpack_require__ (X:\myapp\main-backend.bundle.js:20:30)
    at Object.<anonymous> (X:\myapp\main-backend.bundle.js:22573:15)
    at __webpack_require__ (X:\myapp\main-backend.bundle.js:20:30)
    at Object.<anonymous> (X:\myapp\main-backend.bundle.js:22375:20)
    at __webpack_require__ (X:\myapp\main-backend.bundle.js:20:30)
    at Object.<anonymous> (X:\myapp\main-backend.bundle.js:3781:24)
    at __webpack_require__ (X:\myapp\main-backend.bundle.js:20:30)
```

**Comment by sokra** [comment]
I don't have time to investigate here, but if you find the bug you can send a PR.

As workaround try to make the package `external`.

**Comment by bebraw** [comment]
@zam6ak Did you have any luck with this?

**Comment by zam6ak** [comment]
@bebraw  No luck on this. We found a way to get rid off the native module so I haven't spent any time on it.

**Comment by evilebottnawi** [comment]
@zam6ak problem still exists? Do you have solution? Also can you create minimum reproducible test repo with `node-loader` to demonstrate problem?
