### ISSUE TITLE
Error: No element indexed by 1

### ISSUE THREAD

**Issue by ccorcos** [webpack/webpack#1485]
I keep running into this error in a variety of places and I can't figure out why. Note that this is my first webpack project so I may be missing something.
1. The first time I ran into this was when I wanted to add source-maps to my code so i can get more reasonable error information from the Chrome Dev Tools. Right now it just tells me where the error is in the generated bundle.

Here's my webpack.config.dev.js:

``` js
var path = require("path")
var webpack = require("webpack")

module.exports = {
  entry: {
    styleguide: ['webpack-hot-middleware/client', './styleguide/main.js']
  },
  output: {
    path: path.join(__dirname, "dist"),
    filename: "[name].bundle.js"
  },
  resolve: {
    root: [
      __dirname
    ],
    extensions: [
      '',
      '.webpack.js',
      '.web.js',
      '.js',
      '.coffee',
      '.scss'
    ],
    modulesDirectories: [
      'node_modules'
    ],
  },
  plugins: [
    new webpack.optimize.OccurenceOrderPlugin(),
    new webpack.HotModuleReplacementPlugin(),
    new webpack.NoErrorsPlugin()
  ],
  module: {
    loaders: [
      // coffeescript - then babel for HMR, but no coffee classes!
      {
        test: /\.coffee$/,
        loader: 'babel!coffee-loader',
      },
      // babel
      {
        test: /\.js$/,
        loader: 'babel',
        exclude: /(node_modules|bower_components)/,
      },
      // scss
      {
        test: /\.scss$/,
        loader: 'style!css!sass?' +
          "includePaths[]=" + encodeURIComponent(path.resolve(__dirname)) + "&" +
          "includePaths[]=" + encodeURIComponent(path.resolve(__dirname, "node_modules")),
      }
    ]
  },
  devtool: "source-map"
}
```

And here's the dev server I'm running:

``` coffee
path = require('path')
express = require('express')
webpack = require('webpack')
config = require('./webpack.config.dev')

app = express()
compiler = webpack(config)

app.use require('webpack-dev-middleware')(compiler, {
  noInfo: true,
})

app.use require('webpack-hot-middleware')(compiler)

app.get '*', (req, res) ->
  res.sendFile path.join(__dirname, 'styleguide', 'index.html')

app.listen 3000, 'localhost', (err) ->
  if err
    console.log(err)
    return
  console.log('Listening at http://localhost:3000')
```

If I remove `devtool: "source-map"` and run `coffee devServer.coffee` then everything works fine. But when I add `devtool: "source-map"` or `devtool: "inline-source-map"`, I get the following error:

```
/Users/chetcorcos/code/styleguide/node_modules/webpack/node_modules/webpack-core/node_modules/source-map/lib/source-map/array-set.js:93
    throw new Error('No element indexed by ' + aIdx);
          ^
Error: No element indexed by 1
  at ArraySet_at [as at] (/Users/chetcorcos/code/styleguide/node_modules/webpack/node_modules/webpack-core/node_modules/source-map/lib/source-map/array-set.js:93:11)
  at SourceMapConsumer.<anonymous> (/Users/chetcorcos/code/styleguide/node_modules/webpack/node_modules/webpack-core/node_modules/source-map/lib/source-map/source-map-consumer.js:147:79)
  at Array.map (native)
  at SourceMapConsumer_eachMapping [as eachMapping] (/Users/chetcorcos/code/styleguide/node_modules/webpack/node_modules/webpack-core/node_modules/source-map/lib/source-map/source-map-consumer.js:146:16)
  at Function.SourceNode_fromStringWithSourceMap (/Users/chetcorcos/code/styleguide/node_modules/webpack/node_modules/webpack-core/node_modules/source-map/lib/source-map/source-node.js:84:26)
  at SourceMapSource.node (/Users/chetcorcos/code/styleguide/node_modules/webpack/node_modules/webpack-core/lib/SourceMapSource.js:41:20)
  at ReplaceSource.node (/Users/chetcorcos/code/styleguide/node_modules/webpack/node_modules/webpack-core/lib/ReplaceSource.js:55:29)
  at CachedSource.node (/Users/chetcorcos/code/styleguide/node_modules/webpack/node_modules/webpack-core/lib/CachedSource.js:41:22)
  at PrefixSource.node (/Users/chetcorcos/code/styleguide/node_modules/webpack/node_modules/webpack-core/lib/PrefixSource.js:27:26)
  at /Users/chetcorcos/code/styleguide/node_modules/webpack/node_modules/webpack-core/lib/ConcatSource.js:38:49
  at Array.map (native)
  at ConcatSource.node (/Users/chetcorcos/code/styleguide/node_modules/webpack/node_modules/webpack-core/lib/ConcatSource.js:37:60)
  at /Users/chetcorcos/code/styleguide/node_modules/webpack/node_modules/webpack-core/lib/ConcatSource.js:38:49
  at Array.map (native)
  at ConcatSource.node (/Users/chetcorcos/code/styleguide/node_modules/webpack/node_modules/webpack-core/lib/ConcatSource.js:37:60)
  at /Users/chetcorcos/code/styleguide/node_modules/webpack/node_modules/webpack-core/lib/ConcatSource.js:38:49
  at Array.map (native)
  at ConcatSource.node (/Users/chetcorcos/code/styleguide/node_modules/webpack/node_modules/webpack-core/lib/ConcatSource.js:37:60)
  at /Users/chetcorcos/code/styleguide/node_modules/webpack/node_modules/webpack-core/lib/ConcatSource.js:38:49
  at Array.map (native)
  at ConcatSource.node (/Users/chetcorcos/code/styleguide/node_modules/webpack/node_modules/webpack-core/lib/ConcatSource.js:37:60)
  at ConcatSource.proto.sourceAndMap (/Users/chetcorcos/code/styleguide/node_modules/webpack/node_modules/webpack-core/lib/SourceAndMapMixin.js:22:18)
  at CachedSource.sourceAndMap (/Users/chetcorcos/code/styleguide/node_modules/webpack/node_modules/webpack-core/lib/CachedSource.js:34:28)
  at Compilation.<anonymous> (/Users/chetcorcos/code/styleguide/node_modules/webpack/lib/SourceMapDevToolPlugin.js:55:32)
  at Array.map (native)
  at Compilation.<anonymous> (/Users/chetcorcos/code/styleguide/node_modules/webpack/lib/SourceMapDevToolPlugin.js:43:84)
  at Array.forEach (native)
  at Compilation.<anonymous> (/Users/chetcorcos/code/styleguide/node_modules/webpack/lib/SourceMapDevToolPlugin.js:42:11)
  at Compilation.applyPlugins (/Users/chetcorcos/code/styleguide/node_modules/webpack/node_modules/tapable/lib/Tapable.js:26:37)
  at Compilation.<anonymous> (/Users/chetcorcos/code/styleguide/node_modules/webpack/lib/Compilation.js:570:10)
  at Compilation.applyPluginsAsync (/Users/chetcorcos/code/styleguide/node_modules/webpack/node_modules/tapable/lib/Tapable.js:60:69)
  at Compilation.<anonymous> (/Users/chetcorcos/code/styleguide/node_modules/webpack/lib/Compilation.js:566:9)
  at Compilation.applyPluginsAsync (/Users/chetcorcos/code/styleguide/node_modules/webpack/node_modules/tapable/lib/Tapable.js:60:69)
  at Compilation.<anonymous> (/Users/chetcorcos/code/styleguide/node_modules/webpack/lib/Compilation.js:562:8)
  at Compilation.applyPluginsAsync (/Users/chetcorcos/code/styleguide/node_modules/webpack/node_modules/tapable/lib/Tapable.js:60:69)
  at Compilation.seal (/Users/chetcorcos/code/styleguide/node_modules/webpack/lib/Compilation.js:524:7)
  at Compiler.<anonymous> (/Users/chetcorcos/code/styleguide/node_modules/webpack/lib/Compiler.js:397:15)
  at /Users/chetcorcos/code/styleguide/node_modules/webpack/node_modules/tapable/lib/Tapable.js:103:11
  at Compilation.<anonymous> (/Users/chetcorcos/code/styleguide/node_modules/webpack/lib/Compilation.js:444:10)
  at /Users/chetcorcos/code/styleguide/node_modules/webpack/lib/Compilation.js:416:12
  at /Users/chetcorcos/code/styleguide/node_modules/webpack/lib/Compilation.js:331:10
  at /Users/chetcorcos/code/styleguide/node_modules/webpack/node_modules/async/lib/async.js:52:16
  at done (/Users/chetcorcos/code/styleguide/node_modules/webpack/node_modules/async/lib/async.js:248:21)
  at /Users/chetcorcos/code/styleguide/node_modules/webpack/node_modules/async/lib/async.js:44:16
  at /Users/chetcorcos/code/styleguide/node_modules/webpack/lib/Compilation.js:331:10
  at /Users/chetcorcos/code/styleguide/node_modules/webpack/node_modules/async/lib/async.js:52:16
  at done (/Users/chetcorcos/code/styleguide/node_modules/webpack/node_modules/async/lib/async.js:248:21)
  at /Users/chetcorcos/code/styleguide/node_modules/webpack/node_modules/async/lib/async.js:44:16
  at /Users/chetcorcos/code/styleguide/node_modules/webpack/lib/Compilation.js:331:10
  at /Users/chetcorcos/code/styleguide/node_modules/webpack/node_modules/async/lib/async.js:52:16
  at done (/Users/chetcorcos/code/styleguide/node_modules/webpack/node_modules/async/lib/async.js:248:21)
  at /Users/chetcorcos/code/styleguide/node_modules/webpack/node_modules/async/lib/async.js:44:16
  at /Users/chetcorcos/code/styleguide/node_modules/webpack/lib/Compilation.js:331:10
  at /Users/chetcorcos/code/styleguide/node_modules/webpack/node_modules/async/lib/async.js:52:16
  at done (/Users/chetcorcos/code/styleguide/node_modules/webpack/node_modules/async/lib/async.js:248:21)
  at /Users/chetcorcos/code/styleguide/node_modules/webpack/node_modules/async/lib/async.js:44:16
  at /Users/chetcorcos/code/styleguide/node_modules/webpack/lib/Compilation.js:331:10
  at /Users/chetcorcos/code/styleguide/node_modules/webpack/node_modules/async/lib/async.js:52:16
  at done (/Users/chetcorcos/code/styleguide/node_modules/webpack/node_modules/async/lib/async.js:248:21)
  at /Users/chetcorcos/code/styleguide/node_modules/webpack/node_modules/async/lib/async.js:44:16
  at /Users/chetcorcos/code/styleguide/node_modules/webpack/lib/Compilation.js:331:10
  at /Users/chetcorcos/code/styleguide/node_modules/webpack/node_modules/async/lib/async.js:52:16
  at done (/Users/chetcorcos/code/styleguide/node_modules/webpack/node_modules/async/lib/async.js:248:21)
  at /Users/chetcorcos/code/styleguide/node_modules/webpack/node_modules/async/lib/async.js:44:16
  at process._tickCallback (node.js:355:11)
```
1. When I try to compile distribution files for my project, I have a similar issue. Here's my webpack.config.prod.js.

``` js
var path = require("path")
var webpack = require("webpack")

module.exports = {
  entry: {
    styleguide: './styleguide/main.js'
  },
  output: {
    path: path.join(__dirname, "dist"),
    filename: "[name]/[hash].bundle.js"
  },
  resolve: {
    root: [
      __dirname
    ],
    extensions: [
      '',
      '.webpack.js',
      '.web.js',
      '.js',
      '.coffee',
      '.scss'
    ],
    modulesDirectories: [
      'node_modules'
    ],
  },
  plugins: [
    new webpack.optimize.OccurenceOrderPlugin(),
    new webpack.optimize.DedupePlugin(),
    new webpack.optimize.UglifyJsPlugin({ output: {comments: false}}),
  ],
  module: {
    loaders: [
      // coffeescript - then babel for HMR, but no coffee classes!
      {
        test: /\.coffee$/,
        loader: 'babel!coffee-loader',
      },
      // babel
      {
        test: /\.js$/,
        loader: 'babel',
        exclude: /(node_modules|bower_components)/,
      },
      // scss
      {
        test: /\.scss$/,
        loader: 'style!css!sass?' +
          "includePaths[]=" + encodeURIComponent(path.resolve(__dirname)) + "&" +
          "includePaths[]=" + encodeURIComponent(path.resolve(__dirname, "node_modules")),
      }
    ]
  }
}
```

when I run `webpack --config webpack.condig.prod.js` I get the same error but through UglifyJsPlugin

```
ERROR in styleguide/05382e8603218fb6f5fe.bundle.js from UglifyJs
Error: No element indexed by 1
  at ArraySet_at [as at] (/Users/chetcorcos/code/styleguide/node_modules/webpack/node_modules/webpack-core/node_modules/source-map/lib/source-map/array-set.js:93:11)
  at SourceMapConsumer.<anonymous> (/Users/chetcorcos/code/styleguide/node_modules/webpack/node_modules/webpack-core/node_modules/source-map/lib/source-map/source-map-consumer.js:147:79)
  at Array.map (native)
  at SourceMapConsumer_eachMapping [as eachMapping] (/Users/chetcorcos/code/styleguide/node_modules/webpack/node_modules/webpack-core/node_modules/source-map/lib/source-map/source-map-consumer.js:146:16)
  at Function.SourceNode_fromStringWithSourceMap (/Users/chetcorcos/code/styleguide/node_modules/webpack/node_modules/webpack-core/node_modules/source-map/lib/source-map/source-node.js:84:26)
  at SourceMapSource.node (/Users/chetcorcos/code/styleguide/node_modules/webpack/node_modules/webpack-core/lib/SourceMapSource.js:41:20)
  at ReplaceSource.node (/Users/chetcorcos/code/styleguide/node_modules/webpack/node_modules/webpack-core/lib/ReplaceSource.js:55:29)
  at CachedSource.node (/Users/chetcorcos/code/styleguide/node_modules/webpack/node_modules/webpack-core/lib/CachedSource.js:41:22)
  at PrefixSource.node (/Users/chetcorcos/code/styleguide/node_modules/webpack/node_modules/webpack-core/lib/PrefixSource.js:27:26)
  at /Users/chetcorcos/code/styleguide/node_modules/webpack/node_modules/webpack-core/lib/ConcatSource.js:38:49
  at Array.map (native)
  at ConcatSource.node (/Users/chetcorcos/code/styleguide/node_modules/webpack/node_modules/webpack-core/lib/ConcatSource.js:37:60)
  at /Users/chetcorcos/code/styleguide/node_modules/webpack/node_modules/webpack-core/lib/ConcatSource.js:38:49
  at Array.map (native)
  at ConcatSource.node (/Users/chetcorcos/code/styleguide/node_modules/webpack/node_modules/webpack-core/lib/ConcatSource.js:37:60)
  at /Users/chetcorcos/code/styleguide/node_modules/webpack/node_modules/webpack-core/lib/ConcatSource.js:38:49
  at Array.map (native)
  at ConcatSource.node (/Users/chetcorcos/code/styleguide/node_modules/webpack/node_modules/webpack-core/lib/ConcatSource.js:37:60)
  at /Users/chetcorcos/code/styleguide/node_modules/webpack/node_modules/webpack-core/lib/ConcatSource.js:38:49
  at Array.map (native)
  at ConcatSource.node (/Users/chetcorcos/code/styleguide/node_modules/webpack/node_modules/webpack-core/lib/ConcatSource.js:37:60)
  at ConcatSource.proto.sourceAndMap (/Users/chetcorcos/code/styleguide/node_modules/webpack/node_modules/webpack-core/lib/SourceAndMapMixin.js:22:18)
  at CachedSource.sourceAndMap (/Users/chetcorcos/code/styleguide/node_modules/webpack/node_modules/webpack-core/lib/CachedSource.js:34:28)
  at /Users/chetcorcos/code/styleguide/node_modules/webpack/lib/optimize/UglifyJsPlugin.js:55:33
  at Array.forEach (native)
  at Compilation.<anonymous> (/Users/chetcorcos/code/styleguide/node_modules/webpack/lib/optimize/UglifyJsPlugin.js:44:10)
  at Compilation.applyPluginsAsync (/Users/chetcorcos/code/styleguide/node_modules/webpack/node_modules/tapable/lib/Tapable.js:71:13)
  at Compilation.<anonymous> (/Users/chetcorcos/code/styleguide/node_modules/webpack/lib/Compilation.js:566:9)
  at Compilation.applyPluginsAsync (/Users/chetcorcos/code/styleguide/node_modules/webpack/node_modules/tapable/lib/Tapable.js:60:69)
  at Compilation.<anonymous> (/Users/chetcorcos/code/styleguide/node_modules/webpack/lib/Compilation.js:562:8)
  at Compilation.applyPluginsAsync (/Users/chetcorcos/code/styleguide/node_modules/webpack/node_modules/tapable/lib/Tapable.js:60:69)
  at Compilation.seal (/Users/chetcorcos/code/styleguide/node_modules/webpack/lib/Compilation.js:524:7)
  at Compiler.<anonymous> (/Users/chetcorcos/code/styleguide/node_modules/webpack/lib/Compiler.js:397:15)
  at /Users/chetcorcos/code/styleguide/node_modules/webpack/node_modules/tapable/lib/Tapable.js:103:11
  at Compilation.<anonymous> (/Users/chetcorcos/code/styleguide/node_modules/webpack/lib/Compilation.js:444:10)
  at /Users/chetcorcos/code/styleguide/node_modules/webpack/lib/Compilation.js:416:12
  at /Users/chetcorcos/code/styleguide/node_modules/webpack/lib/Compilation.js:331:10
  at /Users/chetcorcos/code/styleguide/node_modules/webpack/node_modules/async/lib/async.js:52:16
  at done (/Users/chetcorcos/code/styleguide/node_modules/webpack/node_modules/async/lib/async.js:248:21)
  at /Users/chetcorcos/code/styleguide/node_modules/webpack/node_modules/async/lib/async.js:44:16
  at /Users/chetcorcos/code/styleguide/node_modules/webpack/lib/Compilation.js:331:10
  at /Users/chetcorcos/code/styleguide/node_modules/webpack/node_modules/async/lib/async.js:52:16
  at done (/Users/chetcorcos/code/styleguide/node_modules/webpack/node_modules/async/lib/async.js:248:21)
  at /Users/chetcorcos/code/styleguide/node_modules/webpack/node_modules/async/lib/async.js:44:16
  at /Users/chetcorcos/code/styleguide/node_modules/webpack/lib/Compilation.js:331:10
  at /Users/chetcorcos/code/styleguide/node_modules/webpack/node_modules/async/lib/async.js:52:16
  at done (/Users/chetcorcos/code/styleguide/node_modules/webpack/node_modules/async/lib/async.js:248:21)
  at /Users/chetcorcos/code/styleguide/node_modules/webpack/node_modules/async/lib/async.js:44:16
  at /Users/chetcorcos/code/styleguide/node_modules/webpack/lib/Compilation.js:331:10
  at /Users/chetcorcos/code/styleguide/node_modules/webpack/node_modules/async/lib/async.js:52:16
  at done (/Users/chetcorcos/code/styleguide/node_modules/webpack/node_modules/async/lib/async.js:248:21)
  at /Users/chetcorcos/code/styleguide/node_modules/webpack/node_modules/async/lib/async.js:44:16
  at /Users/chetcorcos/code/styleguide/node_modules/webpack/lib/Compilation.js:331:10
  at /Users/chetcorcos/code/styleguide/node_modules/webpack/node_modules/async/lib/async.js:52:16
  at done (/Users/chetcorcos/code/styleguide/node_modules/webpack/node_modules/async/lib/async.js:248:21)
  at /Users/chetcorcos/code/styleguide/node_modules/webpack/node_modules/async/lib/async.js:44:16
  at process._tickCallback (node.js:355:11)
```

Any ideas where this is coming from and how to fix it? I've spend a solid day on this issue...

**Comment by ccorcos** [comment]
This is a similar issue btw. But perhaps different causes

https://github.com/webpack/webpack/issues/1071

**Comment by ccorcos** [comment]
Still battling with this :(

**Comment by bebraw** [comment]
Are you still seeing this?

**Comment by rodoabad** [comment]
We're still having this issue.

**Comment by bebraw** [comment]
@rodoabad Can you see it with webpack 2?

**Comment by trxcllnt** [comment]
I still see this with webpack 2 and webpack-closure-compiler.

**Comment by dyu** [comment]
Still got this error with the same exact usecase as @trxcllnt

**Comment by rodoabad** [comment]
@bebraw yep, same with the rest. `1.13.x`, `1.14.x`, and `2.x`.

**Comment by bebraw** [comment]
@rodoabad Ok. Could you set up a tiny project showcasing the issue and link to it?

**Comment by Slapbox** [comment]
I'm getting `ERROR in unknown: No element indexed by 4`

What does this error even mean? If I had the slightest clue the source of the problem I would set up a small project to show the issue, but I have no idea what the source of the issue is and I can't just post the whole source.
