### ISSUE TITLE
`TypeError: Cannot read property '0' of undefined` when using disk cache, web-workers and trusted types

### ISSUE THREAD

**Issue by alan-agius4** [webpack/webpack#15153]
# Bug report

**What is the current behavior?**
When using `trustedTypes`, `web worker` and disk `cache` when removing or adding an import the below error is shown.
```
Cannot read property '0' of undefined
while analysing module /Users//webpack-test/worker-file.js for concatenation
TypeError: Cannot read property '0' of undefined
while analysing module /Users//webpack-test/worker-file.js for concatenation
    at CreateScriptUrlDependencyTemplate.apply (/Users//webpack-test/node_modules/webpack/lib/dependencies/CreateScriptUrlDependency.js:44:26)
    at JavascriptGenerator.sourceDependency (/Users//webpack-test/node_modules/webpack/lib/javascript/JavascriptGenerator.js:206:12)
    at JavascriptGenerator.sourceModule (/Users//webpack-test/node_modules/webpack/lib/javascript/JavascriptGenerator.js:112:9)
    at JavascriptGenerator.generate (/Users//webpack-test/node_modules/webpack/lib/javascript/JavascriptGenerator.js:98:8)
    at NormalModule.codeGeneration (/Users//webpack-test/node_modules/webpack/lib/NormalModule.js:1196:22)
    at ConcatenatedModule._analyseModule (/Users//webpack-test/node_modules/webpack/lib/optimize/ConcatenatedModule.js:1659:29)
    at ConcatenatedModule.codeGeneration (/Users//webpack-test/node_modules/webpack/lib/optimize/ConcatenatedModule.js:1102:9)
    at /Users//webpack-test/node_modules/webpack/lib/Compilation.js:3321:22
    at /Users//webpack-test/node_modules/webpack/lib/Cache.js:85:6
    at /Users//webpack-test/node_modules/webpack/lib/Cache.js:39:11
```

**If the current behavior is a bug, please provide the steps to reproduce.**

```
$ git clone https://github.com/alan-agius4/webpack-cache-trusted-types-workers.git
$ cd webpack-cache-trusted-types-workers
$ yarn
$ yarn webpack (Build okay)
// Uncomment commented code in `index.js`
$ yarn webpack (Error)
$ rm -rf node_modules/.cache
$ yarn webpack (Build okay)
```

The second `yarn webpack` command should fail with `Cannot read property '0' of undefined`.

**What is the expected behavior?**
No error. 

This has been brought to our attention via https://github.com/angular/angular-cli/issues/22428

**Other relevant information:**
webpack version:  5.66.0
Node.js version: 14.18.1
Operating System: darwin x64
Additional tools:

**Comment by alexander-akait** [comment]
Fix https://github.com/webpack/webpack/pull/15154

**Comment by alan-agius4** [comment]
Wow @alexander-akait that was fast. Thanks for the prompt action.

**Comment by alan-agius4** [comment]
Wow @alexander-akait that was fast. Thanks for the prompt action.
