### ISSUE TITLE
Using `DefinePlugin` to define `import` throws an error

### ISSUE THREAD

**Issue by connor4312** [webpack/webpack#15364]
# Bug report

**What is the current behavior?**

Have a webpack config that looks like this:

```
			new DefinePlugin({
				// defined to access the native browner import, which is ordinarily
				// prevented by (1) TS compiling import to require(), and(2) webpack
				// compiling import() to its own native import. This bypasses both.
				__non_webpack_import__: 'import',
			}),
```

Upon compilation, you'll get an error

```
SyntaxError: Unexpected token (1:7)
    at Object.pp$4.raise (C:\Users\Connor\Documents\Github\vscode-dev\client\node_modules\acorn\dist\acorn.js:3460:15)
    at Object.pp$9.unexpected (C:\Users\Connor\Documents\Github\vscode-dev\client\node_modules\acorn\dist\acorn.js:756:10)
    at Object.pp$5.parseExprImport (C:\Users\Connor\Documents\Github\vscode-dev\client\node_modules\acorn\dist\acorn.js:2854:12)
    at Object.pp$5.parseExprAtom (C:\Users\Connor\Documents\Github\vscode-dev\client\node_modules\acorn\dist\acorn.js:2829:21)
    at Object.pp$5.parseExprSubscripts (C:\Users\Connor\Documents\Github\vscode-dev\client\node_modules\acorn\dist\acorn.js:2627:21)
    at Object.pp$5.parseMaybeUnary (C:\Users\Connor\Documents\Github\vscode-dev\client\node_modules\acorn\dist\acorn.js:2593:19)
    at Object.pp$5.parseExprOps (C:\Users\Connor\Documents\Github\vscode-dev\client\node_modules\acorn\dist\acorn.js:2520:21)
    at Object.pp$5.parseMaybeConditional (C:\Users\Connor\Documents\Github\vscode-dev\client\node_modules\acorn\dist\acorn.js:2503:2
```

This is due to the

**If the current behavior is a bug, please provide the steps to reproduce.**

See above

**What is the expected behavior?**

It should not throw an error.

This is due to the recursion check in the `DefinePlugin`

![image](https://user-images.githubusercontent.com/2230985/153305953-366a2120-955b-4f34-a36b-a68bb5542954.png)

...the JavaScript evaluator tries to parse it as `(import)`, which is not valid.

![image](https://user-images.githubusercontent.com/2230985/153306028-e3da6479-8916-4f32-b425-f8fb81058471.png)

Perhaps if the parsing fails, the code should be emitted as-is?

**Other relevant information:**
webpack version:  5.68.0
Node.js version: v16.13.2
Operating System: Windows 10
Additional tools: N/A

**Comment by vankop** [comment]
`import` is a reserved word, not sure that this must works. you can use/define your own `require`
