### ISSUE TITLE
RuntimeIdRuntimeModule must be in a single runtime LimitChunkCountPlugin maxChunks 1

### ISSUE THREAD

**Issue by arpu** [webpack/webpack#15416]
For building a lib i want to disable codeSplitting with webpack 

adding the LimitChunkCountPlugin

```
   plugins: [
    new webpack.optimize.LimitChunkCountPlugin({
      maxChunks: 1,
    }),
  ],
```

but get this error on build

```
ERROR in webpack/runtime/runtimeId
RuntimeIdRuntimeModule must be in a single runtime
Error: RuntimeIdRuntimeModule must be in a single runtime
    at RuntimeIdRuntimeModule.generate (/home/arpu/Work/projects/vland_app/vland_app/node_modules/webpack/lib/runtime/RuntimeIdRuntimeModule.js:22:10)
    at RuntimeIdRuntimeModule.getGeneratedCode (/home/arpu/Work/projects/vland_app/vland_app/node_modules/webpack/lib/RuntimeModule.js:182:44)
    at RuntimeIdRuntimeModule.codeGeneration (/home/arpu/Work/projects/vland_app/vland_app/node_modules/webpack/lib/RuntimeModule.js:137:30)
    at /home/arpu/Work/projects/vland_app/vland_app/node_modules/webpack/lib/Compilation.js:3324:22
    at /home/arpu/Work/projects/vland_app/vland_app/node_modules/webpack/lib/Cache.js:93:5
    at Hook.eval [as callAsync] (eval at create (/home/arpu/Work/projects/vland_app/vland_app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Cache.get (/home/arpu/Work/projects/vland_app/vland_app/node_modules/webpack/lib/Cache.js:75:18)
    at ItemCacheFacade.get (/home/arpu/Work/projects/vland_app/vland_app/node_modules/webpack/lib/CacheFacade.js:111:15)
    at Compilation._codeGenerationModule (/home/arpu/Work/projects/vland_app/vland_app/node_modules/webpack/lib/Compilation.js:3317:9)
    at /home/arpu/Work/projects/vland_app/vland_app/node_modules/webpack/lib/Compilation.js:3224:11

```

without the plugin all works fine 

node v14.19.0
webpack 5.69.1

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

Please fix it and I will reopen, maybe duplicate https://github.com/webpack/webpack/issues/11431

**Comment by vankop** [comment]
You probably have several entrypoints, so you can not limit chunk count to one, not sure.. please recreate issue with small reproducible repo, thanks.

**Comment by arpu** [comment]
Thanks for the comment, not sure i can make a simple reproduce testcase for this.

the entrypoint is one file
```entry: {
		main: './src/index-webcomponent.js',
	  },

```
and using preact as alias

```
alias: {
			"react": "preact/compat",
			"react-dom": "preact/compat",
		},
```

**Comment by mohsinulhaq** [comment]
@arpu how did you resolve this issue?

**Comment by alexander-akait** [comment]
> You probably have several entrypoints, so you can not limit chunk count to one, not sure.. 

There is answer, it is a limitation in some cases, anyway please provide more infromation, so we can answer better why

**Comment by mohsinulhaq** [comment]
@alexander-akait For me, the error started popping up after I removed `worker-loader` in favor of Webpack 5's native support for Web Workers. I am sure it's caused due to `LimitChunkCountPlugin` because disabling it causes builds to pass.

**Comment by alexander-akait** [comment]
When you have `native support for Web Workers`, you always have more than 1 chunk... You can try:
```js
new webpack.optimize.LimitChunkCountPlugin({
      maxChunks: 2,
}),
```
