### ISSUE TITLE
AMDRequireArrayDependency is not defined

### ISSUE THREAD

**Issue by tcoopman** [webpack/webpack#155]
I'm new to webpack, so maybe I'm missing something here, but I was looking into using the esri arcgis api with webpack (https://developers.arcgis.com/javascript/).
Now when I try to load the esri.js (http://js.arcgis.com/3.8/init.js) with:

```
define(["./init.js"], function(file) {
    console.log('done');
});
```

I get the error:

```
ERROR in ./js/init.js
Module parse failed: c:\Workspace\rio-inspecties\dist\js\init.js AMDRequireArrayDependency is not defined
ReferenceError: AMDRequireArrayDependency is not defined
    at Tapable.module.exports.AbstractPlugin.create.call define:amd:array (C:\Users\thomas.PC1612DT\AppData\Roaming\npm\node_modules\webpack\lib\dependencies\AMDDefineDependencyParserPlugin.js:126:18)
    at Tapable.applyPluginsBailResult (C:\Users\thomas.PC1612DT\AppData\Roaming\npm\node_modules\webpack\node_modules\tapable\lib\Tapable.js:31:50)
    at Tapable.module.exports.AbstractPlugin.create.call define (C:\Users\thomas.PC1612DT\AppData\Roaming\npm\node_modules\webpack\lib\dependencies\AMDDefineDependencyParserPlugin.js:68:22)
    at Tapable.applyPluginsBailResult (C:\Users\thomas.PC1612DT\AppData\Roaming\npm\node_modules\webpack\node_modules\tapable\lib\Tapable.js:31:50)
    at Tapable.walkExpression (C:\Users\thomas.PC1612DT\AppData\Roaming\npm\node_modules\webpack\lib\Parser.js:578:23)
    at Tapable.walkStatement (C:\Users\thomas.PC1612DT\AppData\Roaming\npm\node_modules\webpack\lib\Parser.js:346:8)
    at Tapable.<anonymous> (C:\Users\thomas.PC1612DT\AppData\Roaming\npm\node_modules\webpack\lib\Parser.js:334:8)
    at Array.forEach (native)
    at Tapable.walkStatements (C:\Users\thomas.PC1612DT\AppData\Roaming\npm\node_modules\webpack\lib\Parser.js:333:13)
    at Tapable.parse (C:\Users\thomas.PC1612DT\AppData\Roaming\npm\node_modules\webpack\lib\Parser.js:729:8)
 @ ./js/test.js 4:0-6:2
```

This looks like a bug, but maybe I'm doing something wrong...

**Comment by harrytospring** [comment]
I was also trying to use webpack to bundle the arcgis api for js.
And i have found these two projects:https://github.com/Nordth/dojo-webpack-loader,https://github.com/Esri/arcgis-js-api.
A little progress i have made.But there were still some little problems.Have you any better way for this?Thanks.

**Comment by lapint** [comment]
https://github.com/Robert-W/esri-redux

This guy has a lot of good resources around this. He has a working version of webpack + esri

**Comment by tomwayson** [comment]
FYI - the relevant webpack config and related code from https://github.com/Robert-W/esri-redux has been extracted to a few other gists/repos that are not not react related:

https://gist.github.com/gund/6b22d5ffae42849252abc9a689eb656d
https://github.com/lobsteropteryx/esri-webpack-typescript
https://github.com/tomwayson/esri-webpack-babel

An alternative way is to use the [esri-loader](https://github.com/tomwayson/esri-loader) library to load the ArcGIS API modules.

I wrote a [blog post](http://tomwayson.com/2016/11/27/using-the-arcgis-api-for-javascript-in-applications-built-with-webpack/) to compare those patterns and help explain why these kinds of patterns are necessary (TLDR: Dojo) and why you can't just `import` ArcGIS modules the way you would modules from other libraries.
