### ISSUE TITLE
I am migrating my webpack v4 to v5 i'm facing the below issue

### ISSUE THREAD

**Issue by hariseshathri** [webpack/webpack#15547]
[webpack-cli] D:\22.05\FORMS-1065\core-ui-application\node_modules\webpack-dev-server\lib\servers\WebsocketServer.js:10
  static heartbeatInterval = 1000;
                           ^

SyntaxError: Unexpected token =
    at Module._compile (internal/modules/cjs/loader.js:760:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Server.getServerTransport (D:\22.05\FORMS-1065\core-ui-application\node_modules\webpack-dev-server\lib\Server.js:1663:28)
    at Server.createWebSocketServer (D:\22.05\FORMS-1065\core-ui-application\node_modules\webpack-dev-server\lib\Server.js:2443:57)
    at Server.start (D:\22.05\FORMS-1065\core-ui-application\node_modules\webpack-dev-server\lib\Server.js:3229:12)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)``

**Comment by vankop** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us by recreating the issue using one of our templates.

Please fill out all fields, we can't help you without it.

From stack trace it looks like your code has [`static` keyword](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/static), I think webpack parser does not support it. Please use babel (or equal tool) to transpile your code.

**Comment by progerchai** [comment]
same issue with me:



# Bug report






**What is the current behavior?**


**If the current behavior is a bug, please provide the steps to reproduce.**









**What is the expected behavior?**
```bash
[webpack-cli] /opt/app-root/src/www/mo_prod/frontend/node_modules/webpack-dev-server/lib/servers/WebsocketServer.js:10
  static heartbeatInterval = 1000;
                           ^

SyntaxError: Unexpected token =
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Server.getServerTransport (/opt/app-root/src/www/mo_prod/frontend/node_modules/webpack-dev-server/lib/Server.js:1664:28)
    at Server.createWebSocketServer (/opt/app-root/src/www/mo_prod/frontend/node_modules/webpack-dev-server/lib/Server.js:2444:57)
    at Server.start (/opt/app-root/src/www/mo_prod/frontend/node_modules/webpack-dev-server/lib/Server.js:3234:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ start: `cross-env NODE_OPTIONS=--max-old-space-size=8096 CONFIG_ENV=development better-npm-run start-dev`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the @ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /opt/app-root/src/.npm/_logs/2022-04-20T01_27_10_737Z-debug.log
```




**Other relevant information:**

```bash
[admin@m-remote-xx frontend]$ npx webpack-cli info

  System:
    OS: Linux 3.10 CentOS Linux 7 (Core)
    CPU: (4) x64 Intel Core Processor (Skylake)
    Memory: 7.28 GB / 15.51 GB
  Binaries:
    Node: 12.13.1 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 5.10.0 - ~/www/mo_prod/frontend/node_modules/.bin/npm
  Packages:
    babel-loader: ^8.1.0 => 8.2.5 
    clean-webpack-plugin: ^4.0.0 => 4.0.0 
    copy-webpack-plugin: ^9.1.0 => 9.1.0 
    css-hot-loader: ^1.4.4 => 1.4.4 
    css-loader: ^5.0.1 => 5.2.7 
    esbuild-webpack-plugin: ^1.1.0 => 1.1.0 
    file-loader: ^6.0.0 => 6.2.0 
    fine-uploader: ^5.16.2 => 5.16.2 
    fine-uploader-wrappers: ^1.0.1 => 1.0.1 
    html-webpack-plugin: ^5.5.0 => 5.5.0 
    less-loader: ^8.0.0 => 8.1.1 
    postcss-loader: ^6.2.1 => 6.2.1 
    react-fine-uploader: ^1.1.0 => 1.1.1 
    react-hot-loader: ^4.12.21 => 4.13.0 
    speed-measure-webpack-plugin: ^1.3.3 => 1.5.0 
    string-replace-loader: ^2.3.0 => 2.3.0 
    style-loader: ^2.0.0 => 2.0.0 
    terser-webpack-plugin: ^5.3.1 => 5.3.1 
    uglifyjs-webpack-plugin: ^2.2.0 => 2.2.0 
    url-loader: ^4.1.1 => 4.1.1 
    webpack: ^5.68.0 => 5.72.0 
    webpack-bundle-analyzer: ^4.5.0 => 4.5.0 
    webpack-cli: ^4.9.2 => 4.9.2 
    webpack-dev-server: ^4.7.4 => 4.8.1 
    webpack-merge: ^5.8.0 => 5.8.0 
    webpack-parallel-uglify-plugin: ^2.0.0 => 2.0.0 

```
webpack version:  v5.72.0 
Node.js version: v12.13.1
Operating System: Linux 3.10 CentOS Linux 7 (Core)
Additional tools:

**Comment by alexander-akait** [comment]
@vankop I think we should fix it, does acorn support it?

**Comment by progerchai** [comment]
it seems to be the problem with npm version?
in my case, the project used the wrong npm unser node_modules
I run `rm -rf ~/www/mo_prod/frontend/node_modules/.bin/npm` 
the npm directory back to my default install directory `/usr/local/bin/npm` ,and the npm version is back to v6.12.1
However,  it worked!

**Comment by alexander-akait** [comment]
What is node version?

**Comment by progerchai** [comment]
> What is node version?

still v12.13.1
