### ISSUE TITLE
Vue 3 try start development server: Cannot read properties of undefined (reading 'NormalModule')

### ISSUE THREAD

**Issue by macJames976** [webpack/webpack#15557]
```
Debugger attached.
 INFO  Starting development server...
 ERROR  TypeError: Cannot read properties of undefined (reading 'NormalModule')
TypeError: Cannot read properties of undefined (reading 'NormalModule')
    at VueLoaderPlugin.apply (C:\Users\myUser\myProject\node_modules\vue-loader-v16\dist\pluginWebpack5.js:44:47)
    at webpack (C:\Users\myUser\myProject\node_modules\@vue\cli-service\node_modules\webpack\lib\webpack.js:51:13)
    at serve (C:\Users\myUser\myProject\@vue\cli-service\lib\commands\serve.js:163:22)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
My package.json

```
{
  "name": "myprject",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint"
  },
  "dependencies": {
    "@fortawesome/fontawesome-svg-core": "^6.1.0",
    "@fortawesome/free-solid-svg-icons": "^6.1.0",
    "@fortawesome/vue-fontawesome": "^3.0.0-4",
    "core-js": "^3.21.1",
    "emailjs-com": "^3.2.0",
    "font-awesome": "^4.7.0",
    "module": "^1.0.0",
    "vue": "^3.2.31",
    "vue-loader": "^17.0.0",
    "vue-recaptcha-v3": "^2.0.1",
    "vue-router": "^4.0.14",
    "vue-server-renderer": "^2.6.14",
    "vuex": "^4.0.2"
  },
  "devDependencies": {
    "@babel/eslint-parser": "^7.17.0",
    "@vue/cli-plugin-babel": "^5.0.3",
    "@vue/cli-plugin-eslint": "^5.0.3",
    "@vue/cli-service": "^4.5.16",
    "@vue/compiler-sfc": "^3.2.31",
    "eslint": "^8.11.0",
    "eslint-plugin-vue": "^8.5.0",
    "fibers": "^5.0.1",
    "sass": "^1.49.9",
    "sass-loader": "^12.6.0",
    "style-resources-loader": "^1.5.0",
    "webpack": "^5.70.0",
    "webpack-cli": "^4.9.2"
  },
  "eslintConfig": {
    "root": true,
    "env": {
      "node": true
    },
    "extends": [
      "plugin:vue/vue3-essential",
      "eslint:recommended"
    ],
    "parserOptions": {
      "parser": "@babel/eslint-parser"
    },
    "rules": {}
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not dead"
  ]
}
```

**Comment by alexander-akait** [comment]
Please open an issue in `vue-loader-v16`

**Comment by marimendez88** [comment]
hey @vankop -> 
I ran into the same issue, no information on forums, but I managed to solve it by installing a specific version of webpack:


`npm install webpack@4.39.3 --save`'

**Comment by vankop** [comment]
hm.. you should not get this warning for `webpack@4`, anyway ask in vue-loader issue tracker

**Comment by gormonn** [comment]
i have similar problem, when trying to upgrade deps after eject from cra with webpack v5
