### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'buildMeta')

### ISSUE THREAD

**Issue by 17736638254** [webpack/webpack#15609]
# Bug report

After executing the package command, the console prompts

<img width="384" alt="image" src="https://user-images.githubusercontent.com/59221382/161218256-99484627-a41e-46be-be4d-f4a3dbbd7075.png">

`
/Users/it00013208/Desktop/privateProject/set-user-blog/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:165
                return moduleGraph.getParentModule(this).buildMeta.strictHarmonyModule
                                                        ^

TypeError: Cannot read properties of undefined (reading 'buildMeta')
    at HarmonyImportSpecifierDependency._getEffectiveExportPresenceLevel (/Users/it00013208/Desktop/privateProject/set-user-blog/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:165:43)
    at HarmonyImportSpecifierDependency.getWarnings (/Users/it00013208/Desktop/privateProject/set-user-blog/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:176:32)
    at Compilation.reportDependencyErrorsAndWarnings (/Users/it00013208/Desktop/privateProject/set-user-blog/node_modules/webpack/lib/Compilation.js:3131:24)
    at /Users/it00013208/Desktop/privateProject/set-user-blog/node_modules/webpack/lib/Compilation.js:2728:28
    at _next2 (eval at create (/Users/it00013208/Desktop/privateProject/set-user-blog/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:25:1)
    at eval (eval at create (/Users/it00013208/Desktop/privateProject/set-user-blog/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:52:1)
    at /Users/it00013208/Desktop/privateProject/set-user-blog/node_modules/webpack/lib/FlagDependencyExportsPlugin.js:385:11
    at /Users/it00013208/Desktop/privateProject/set-user-blog/node_modules/neo-async/async.js:2830:7
    at Object.each (/Users/it00013208/Desktop/privateProject/set-user-blog/node_modules/neo-async/async.js:2850:39)
    at /Users/it00013208/Desktop/privateProject/set-user-blog/node_modules/webpack/lib/FlagDependencyExportsPlugin.js:361:18
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
`

**Comment by 17736638254** [comment]
I lowered and locked the webpack version, and that's it.
<img width="350" alt="image" src="https://user-images.githubusercontent.com/59221382/161219749-5f2bc80f-a69d-4f73-924d-ffcd929c3e3f.png">

**Comment by vankop** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us by recreating the issue using one of our templates.

Please fill out all fields, we can't help you without it
