### ISSUE TITLE
yarn benchmark failed with "Your test suite must contain at least one test."

### ISSUE THREAD

**Issue by rluvaton** [webpack/webpack#15621]
I'm thinking of contributing and I'm trying to run the benchmarks but it failed with "Your test suite must contain at least one test."

❯ yarn benchmark
yarn run v1.22.18
$ node --max-old-space-size=4096 --experimental-vm-modules --trace-deprecation node_modules/jest-cli/bin/jest --testMatch "<rootDir>/test/*.benchmark.js" --runInBand
(node:19705) ExperimentalWarning: VM Modules is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
 FAIL  test/BenchmarkTestCases.benchmark.js
  ● Test suite failed to run

    Your test suite must contain at least one test.

      at onResult (node_modules/@jest/core/build/TestScheduler.js:175:18)
      at node_modules/@jest/core/build/TestScheduler.js:316:17
      at node_modules/emittery/index.js:260:13
          at Array.map (<anonymous>)
      at Emittery.emit (node_modules/emittery/index.js:258:23)

**Comment by rluvaton** [comment]
So I'm running `node benchmark/benchmark.js` which seems to run benchmarks but fails because of missing fixtures...
