### ISSUE TITLE
 Gatsby Develop > ERROR #98123  WEBPACK

### ISSUE THREAD

**Issue by benackles** [webpack/webpack#15790]
# Bug report

**What is the current behavior?**
I am getting two WEBPACK ERROR #98123 when I am building a Gatsby site.

```
 ERROR #98123  WEBPACK

Generating development JavaScript bundle failed

You must provide the URL of lib/mappings.wasm by calling SourceMapConsumer.initialize({ 'lib/mappings.wasm': ... }) before using SourceMapConsumer

File: .cache/app.js


 ERROR #98123  WEBPACK

Generating development JavaScript bundle failed

You must provide the URL of lib/mappings.wasm by calling SourceMapConsumer.initialize({ 'lib/mappings.wasm': ... }) before using SourceMapConsumer

File: .cache/polyfill-entry.js

failed Building development bundle - 3.044s
ERROR in ./.cache/app.js
Module build failed (from ./node_modules/@pmmmwh/react-refresh-webpack-plugin/loader/index.js):
Error: You must provide the URL of lib/mappings.wasm by calling SourceMapConsumer.initialize({ 'lib/mappings.wasm': ... }) before using SourceMapConsumer
    at readWasm (/Users/benjamins/Sites/whatsgatsby/node_modules/source-map/lib/read-wasm.js:8:13)
    at wasm (/Users/benjamins/Sites/whatsgatsby/node_modules/source-map/lib/wasm.js:25:16)
    at /Users/benjamins/Sites/whatsgatsby/node_modules/source-map/lib/source-map-consumer.js:264:14
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Object._loader (/Users/benjamins/Sites/whatsgatsby/node_modules/@pmmmwh/react-refresh-webpack-plugin/loader/index.js:81:9)

ERROR in ./.cache/polyfill-entry.js
Module build failed (from ./node_modules/@pmmmwh/react-refresh-webpack-plugin/loader/index.js):
Error: You must provide the URL of lib/mappings.wasm by calling SourceMapConsumer.initialize({ 'lib/mappings.wasm': ... }) before using SourceMapConsumer
    at readWasm (/Users/benjamins/Sites/whatsgatsby/node_modules/source-map/lib/read-wasm.js:8:13)
    at wasm (/Users/benjamins/Sites/whatsgatsby/node_modules/source-map/lib/wasm.js:25:16)
    at /Users/benjamins/Sites/whatsgatsby/node_modules/source-map/lib/source-map-consumer.js:264:14
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Object._loader (/Users/benjamins/Sites/whatsgatsby/node_modules/@pmmmwh/react-refresh-webpack-plugin/loader/index.js:81:9)

develop compiled with 2 errors
```

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Run `gatsby develop` from the terminal
2. Get Webpack errors

**What is the expected behavior?**
I'd expect it to build without failing.

**Other relevant information:**
webpack: 5.72.0
System:
    OS: macOS 12.2.1
    CPU: (8) arm64 Apple M1
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.0.0 - /opt/homebrew/bin/node
    npm: 8.9.0 - /opt/homebrew/bin/npm
  Languages:
    Python: 2.7.18 - /usr/bin/python
  Browsers:
    Chrome: 101.0.4951.54
    Safari: 15.3
  npmPackages:
    gatsby: ^4.13.1 => 4.13.1
    gatsby-plugin-gatsby-cloud: ^4.13.0 => 4.13.0
    gatsby-plugin-image: ^2.13.0 => 2.13.0
    gatsby-plugin-manifest: ^4.13.0 => 4.13.0
    gatsby-plugin-offline: ^5.13.0 => 5.13.0
    gatsby-plugin-react-helmet: ^5.13.0 => 5.13.0
    gatsby-plugin-sharp: ^4.13.0 => 4.13.0
    gatsby-source-filesystem: ^4.13.0 => 4.13.0
    gatsby-transformer-sharp: ^4.13.0 => 4.13.0
  npmGlobalPackages:
    gatsby-cli: 4.13.0

**Comment by alexander-akait** [comment]
Please open an issue in `gatsby`, thanks
