### ISSUE TITLE
Cannot build with devtool set to anything other than eval

### ISSUE THREAD

**Issue by nicolechung** [webpack/webpack#1582]
When I set `devtool` to anything other than `eval` I get the following error:

```
ERROR in ./app/main.js
Module build failed: TypeError: /Users/<me>/chat_connect_webpack_v1/node_modules/react-hot-loader/index.js!/Users/<me>/chat_connect_webpack_v1/node_modules/babel-loader/index.js!/Users/<me>/chat_connect_webpack_v1/app/main.js: Cannot read property 'match' of undefined
    at urlParse (/Users/<me>/chat_connect_webpack_v1/node_modules/babel-core/node_modules/source-map/lib/util.js:33:21)
    at normalize (/Users/<me>/chat_connect_webpack_v1/node_modules/babel-core/node_modules/source-map/lib/util.js:82:15)
    at Array.map (native)
    at SourceMapConsumer.BasicSourceMapConsumer (/Users/<me>/chat_connect_webpack_v1/node_modules/babel-core/node_modules/source-map/lib/source-map-consumer.js:308:8)
    at new SourceMapConsumer (/Users/<me>/chat_connect_webpack_v1/node_modules/babel-core/node_modules/source-map/lib/source-map-consumer.js:22:9)
    at File.mergeSourceMap (/Users/<me>/chat_connect_webpack_v1/node_modules/babel-core/lib/transformation/file/index.js:511:31)
    at File.generate (/Users/<me>/chat_connect_webpack_v1/node_modules/babel-core/lib/transformation/file/index.js:808:25)
    at File.transform (/Users/<me>/chat_connect_webpack_v1/node_modules/babel-core/lib/transformation/file/index.js:625:17)
    at /Users/<me>/chat_connect_webpack_v1/node_modules/babel-core/lib/transformation/pipeline.js:168:19
    at File.wrap (/Users/<me>/chat_connect_webpack_v1/node_modules/babel-core/lib/transformation/file/index.js:639:16)
    at Pipeline.transform (/Users/<me>/chat_connect_webpack_v1/node_modules/babel-core/lib/transformation/pipeline.js:165:17)
    at transpile (/Users/<me>/chat_connect_webpack_v1/node_modules/babel-loader/index.js:12:22)
    at Object.module.exports (/Users/<me>/chat_connect_webpack_v1/node_modules/babel-loader/index.js:69:12)
 @ multi app
```

Below is my webpack-config:

```
var path = require('path');
var ExtractTextPlugin = require('extract-text-webpack-plugin');
var webpack = require('webpack');

module.exports = {
  devtool: 'source-map',
  entry: 
    {
      app: [ 
      //'webpack-dev-server/client?http://0.0.0.0:3000', // WebpackDevServer host and port
      //'webpack/hot/only-dev-server', // "only" prevents reload on syntax errors
    './app/main.js'],
      vendor: ['lodash']
    },
  output: {
    path: path.join(__dirname, 'static'),
    publicPath: '/static/',
    filename: 'app.js'
  },
  module: {
    loaders: [
      { test: /\.js$/, loaders: ['react-hot', 'babel'], exclude: /node_modules/ },
      { test: /.jsx?$/, loaders: ['react-hot', 'babel'], exclude: /node_modules/ },
      { test: /\.css/, loader: ExtractTextPlugin.extract('css') },
      { test: /\.scss$/, loader: ExtractTextPlugin.extract('!css!sass?sourceMap') }
    ]
  },
  sassLoader: {
    includePaths: [ path.resolve(__dirname, './sass/')]
  },
  plugins: [
    new webpack.HotModuleReplacementPlugin(),// don't use if using cli
    new webpack.NoErrorsPlugin(),
    new webpack.optimize.CommonsChunkPlugin("vendor", "vendor.js", Infinity),
    new ExtractTextPlugin('./css/style.css',{
            allChunks: true
        })
  ],
  debug: true
  //watch: true
};
```

**Comment by bebraw** [comment]
Note that line

```javascript
{ test: /\.js$/, loaders: ['react-hot', 'babel'], exclude: /node_modules/ },
```

is redundant. You might want to remove that.

I also recommend setting up a separate build configuration without `react-hot`. You don't need that for a production build.

Perhaps doing these steps will help.

**Comment by sokra** [comment]
> You might want to remove that.

> Perhaps doing these steps will help.

I think so.

**Comment by nicolechung** [comment]
I see, will do thank you.
