### ISSUE TITLE
Can't use UMD externals with Module Federation

### ISSUE THREAD

**Issue by amannn** [webpack/webpack#15879]
# Bug report

**What is the current behavior?**

Webpack produces a broken build when using Module Federation in combination with UMD externals.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Open https://stackblitz.com/edit/github-socemj?file=config.js
2. The project works correctly.
3. Switch the `useExternals` flag in `config.js` to `true` and the app doesn't run anymore.

```
Uncaught ReferenceError: __WEBPACK_EXTERNAL_MODULE_react__ is not defined
    at Object.react (remoteEntry.js:268:18)
    at __webpack_require__ (remoteEntry.js:297:33)
    at fn (remoteEntry.js:563:21)
    at eval (App.js:5:63)
    at Module../src/App.js (src_App_js.js:18:1)
    at __webpack_require__ (remoteEntry.js:297:33)
    at fn (remoteEntry.js:563:21)
    at eval (container_entry:3:66)
    at Object.__webpack_require__.m.<computed> (main.js:579:34)
    at __webpack_require__ (main.js:340:33)
```

Note that React and ReactDOM is provided via external script tags in `index.html`.

The only way I found to get this working is to configure the externals like this:
```
{
  react: 'React',
  'react-dom': 'ReactDOM',
}
```
… and removing `library: { type: 'umd' }`.

**What is the expected behavior?**

webpack produces a working build.

**Other relevant information:**
webpack version:  "^5.38.1"
Node.js version: v16.14.2
Operating System: StackBlitz
Additional tools:

**Comment by vankop** [comment]
you should use 
```diff
module.exports = {
  entry: './src/index',
  mode: 'development',
  target: 'web',
  devServer: {
    static: path.join(__dirname, 'dist'),
    port: 3001,
  },
  output: {
    publicPath: 'auto',
-    library: { type: 'umd' },
  },
  module: {
    rules: [
      {
        test: /\.jsx?$/,
        loader: 'babel-loader',
        exclude: /node_modules/,
        options: {
          presets: ['@babel/preset-react'],
        },
      },
    ],
  },
  plugins: [
    new ModuleFederationPlugin({
      name: 'app1',
      remotes: {
        app2: 'app2@[app2Url]/remoteEntry.js',
      },
-       shared: { react: { singleton: true }, 'react-dom': { singleton: true } },
    }),
    new ExternalTemplateRemotesPlugin(),
    new HtmlWebpackPlugin({
      template: './public/index.html',
    }),
  ],
  externals: config.useExternals
    ? {
-        react: {
-          commonjs: 'react',
-          commonjs2: 'react',
-          amd: 'react',
-          root: 'React',
-        },
-        'react-dom': {
-          commonjs: 'react-dom',
-          commonjs2: 'react-dom',
-          amd: 'react-dom',
-          root: 'ReactDOM',
-        },
+       react: "React",
+       "react-dom": "ReactDOM".
      }
    : undefined,
};
```

**Comment by wwglala** [comment]
@vankop in Micro frontends i need to set **libraryTarget: 'umd'**. What to do in this situation
