### ISSUE TITLE
Can't use scoped package names with Module Federation

### ISSUE THREAD

**Issue by amannn** [webpack/webpack#15880]
# Bug report

**What is the current behavior?**

When using a configuration like this:

```js
new ModuleFederationPlugin({
  name: '@scope/app-1',
  remotes: {
    '@scope/app-2': '@scope/app-2@[app2Url]/remoteEntry.js',
  }
}),
```

… webpack throws with:

```
Error: Invalid request "@scope/app-2@[app2Url]/remoteEntry.js"
    at extractUrlAndGlobal (/home/projects/github-s4x4iq/node_modules/webpack/lib/util/extractUrlAndGlobal.js:15:9)
    at eval (/home/projects/github-s4x4iq/node_modules/external-remotes-plugin/index.js:24:41)
    at Array.map (<anonymous>)
    at eval (/home/projects/github-s4x4iq/node_modules/external-remotes-plugin/index.js:23:39)
    at Hook.eval [as call] (eval at _0x29f4ba (https://github-s4x4iq.w.staticblitz.com/blitz.670e941965b7233a68cb924e1ca43e6a0f35bf71.js:15:285376), <anonymous>:7:1)
    at Hook.CALL_DELEGATE [as _call] (/home/projects/github-s4x4iq/node_modules/tapable/lib/Hook.js:14:14)
    at eval (/home/projects/github-s4x4iq/node_modules/webpack/lib/Compilation.js:3022:38)
    at eval (/home/projects/github-s4x4iq/node_modules/webpack/lib/Compilation.js:3277:6)
    at eval (/home/projects/github-s4x4iq/node_modules/neo-async/async.js:2818:7)
    at done (/home/projects/github-s4x4iq/node_modules/neo-async/async.js:3522:9)
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Open [this StackBlitz reproduction](https://stackblitz.com/edit/github-s4x4iq?file=app1%2Fwebpack.config.js).

**What is the expected behavior?**

webpack should support scoped package names the same way it supports camel-cased modules. Kebab-case seems to also be a problem.

Is this generally a non-goal? I saw that federated modules declare a global variable name on the `window` in their built bundle.

**Other relevant information:**
webpack version: ^5.38.1
Node.js version: v16.14.2
Operating System: StackBlitz
Additional tools:

**Comment by vankop** [comment]
> webpack should support scoped package names the same way

this is not a package name, this is global name. Remote is considered as external module see https://webpack.js.org/configuration/externals/#syntax
