### ISSUE TITLE
Stacktraces are printed when `errorStack` is `false`

### ISSUE THREAD

**Issue by alan-agius4** [webpack/webpack#15980]
Follow up from https://github.com/webpack-contrib/sass-loader/issues/1068#issuecomment-1165806693

# Bug report
In some cases error stacktraces are printed even though [`errorStack`](https://webpack.js.org/configuration/stats/#statserrorstack) is set to `false`.  In some cases `hideStack` is taken into consideration instead. This seems to be a conflict in logic and causes too verbose error messages due to long stack.

From end users stacktraces are rarely useful.

Example
```
./src/styles.scss.webpack[javascript/auto]!=!./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[5].rules[0].oneOf[0].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[5].rules[0].oneOf[0].use[2]!./node_modules/resolve-url-loader/index.js??ruleSet[1].rules[5].rules[1].use[0]!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[5].rules[1].use[1]!./src/styles.scss - Error: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Can't find stylesheet to import.
  ╷
1 │ import "invalid";
  │         ^^^^^^^^^
  ╵
  src/styles.scss 1:9  root stylesheet

./src/styles.scss - Error: Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
HookWebpackError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Can't find stylesheet to import.
  ╷
1 │ import "invalid";
  │         ^^^^^^^^^
  ╵
  src/styles.scss 1:9  root stylesheet
    at tryRunOrWebpackError (/usr/local/xxxxxxx/cli-reproductions/showwcase-v14-rc0/node_modules/webpack/lib/HookWebpackError.js:88:9)
    at __webpack_require_module__ (/usr/local/xxxxxxx/cli-reproductions/showwcase-v14-rc0/node_modules/webpack/lib/Compilation.js:5051:12)
    at __webpack_require__ (/usr/local/xxxxxxx/cli-reproductions/showwcase-v14-rc0/node_modules/webpack/lib/Compilation.js:5008:18)
    at /usr/local/xxxxxxx/cli-reproductions/showwcase-v14-rc0/node_modules/webpack/lib/Compilation.js:5079:20
    at symbolIterator (/usr/local/xxxxxxx/cli-reproductions/showwcase-v14-rc0/node_modules/neo-async/async.js:3485:9)
    at done (/usr/local/xxxxxxx/cli-reproductions/showwcase-v14-rc0/node_modules/neo-async/async.js:3527:9)
    at Hook.eval [as callAsync] (eval at create (/usr/local/xxxxxxx/cli-reproductions/showwcase-v14-rc0/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/usr/local/xxxxxxx/cli-reproductions/showwcase-v14-rc0/node_modules/tapable/lib/Hook.js:18:14)
    at /usr/local/xxxxxxx/cli-reproductions/showwcase-v14-rc0/node_modules/webpack/lib/Compilation.js:4986:43
    at symbolIterator (/usr/local/xxxxxxx/cli-reproductions/showwcase-v14-rc0/node_modules/neo-async/async.js:3482:9)
-- inner error --
Error: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Can't find stylesheet to import.
  ╷
1 │ import "invalid";
  │         ^^^^^^^^^
  ╵
  src/styles.scss 1:9  root stylesheet
    at Object.<anonymous> (/usr/local/xxxxxxx/cli-reproductions/showwcase-v14-rc0/node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[5].rules[0].oneOf[0].use[1]!/usr/local/xxxxxxx/cli-reproductions/showwcase-v14-rc0/node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[5].rules[0].oneOf[0].use[2]!/usr/local/xxxxxxx/cli-reproductions/showwcase-v14-rc0/node_modules/resolve-url-loader/index.js??ruleSet[1].rules[5].rules[1].use[0]!/usr/local/xxxxxxx/cli-reproductions/showwcase-v14-rc0/node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[5].rules[1].use[1]!/usr/local/xxxxxxx/cli-reproductions/showwcase-v14-rc0/src/styles.scss:1:7)
    at /usr/local/xxxxxxx/cli-reproductions/showwcase-v14-rc0/node_modules/webpack/lib/javascript/JavascriptModulesPlugin.js:441:11
    at Hook.eval [as call] (eval at create (/usr/local/xxxxxxx/cli-reproductions/showwcase-v14-rc0/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:1)
    at Hook.CALL_DELEGATE [as _call] (/usr/local/xxxxxxx/cli-reproductions/showwcase-v14-rc0/node_modules/tapable/lib/Hook.js:14:14)
    at /usr/local/xxxxxxx/cli-reproductions/showwcase-v14-rc0/node_modules/webpack/lib/Compilation.js:5053:39
    at tryRunOrWebpackError (/usr/local/xxxxxxx/cli-reproductions/showwcase-v14-rc0/node_modules/webpack/lib/HookWebpackError.js:83:7)
    at __webpack_require_module__ (/usr/local/xxxxxxx/cli-reproductions/showwcase-v14-rc0/node_modules/webpack/lib/Compilation.js:5051:12)
    at __webpack_require__ (/usr/local/xxxxxxx/cli-reproductions/showwcase-v14-rc0/node_modules/webpack/lib/Compilation.js:5008:18)
    at /usr/local/xxxxxxx/cli-reproductions/showwcase-v14-rc0/node_modules/webpack/lib/Compilation.js:5079:20
    at symbolIterator (/usr/local/xxxxxxx/cli-reproductions/showwcase-v14-rc0/node_modules/neo-async/async.js:3485:9)

Generated code for /usr/local/xxxxxxx/cli-reproductions/showwcase-v14-rc0/node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[5].rules[0].oneOf[0].use[1]!/usr/local/xxxxxxx/cli-reproductions/showwcase-v14-rc0/node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[5].rules[0].oneOf[0].use[2]!/usr/local/xxxxxxx/cli-reproductions/showwcase-v14-rc0/node_modules/resolve-url-loader/index.js??ruleSet[1].rules[5].rules[1].use[0]!/usr/local/xxxxxxx/cli-reproductions/showwcase-v14-rc0/node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[5].rules[1].use[1]!/usr/local/xxxxxxx/cli-reproductions/showwcase-v14-rc0/src/styles.scss
1 | throw new Error("Module build failed (from ./node_modules/sass-loader/dist/cjs.js):\nSassError: Can't find stylesheet to import.\n  ╷\n1 │ https://github.com/import \"invalid\";\n  │         ^^^^^^^^^\n  ╵\n  src/styles.scss 1:9  root stylesheet");
```

Examples of problematic code. (Not limited too):
- https://github.com/webpack/webpack/blob/e2f1592f7e4d8f0578e5bb23d6a863b4a2b5f309/lib/ModuleBuildError.js#L31-L32
- https://github.com/webpack/webpack/blob/e2f1592f7e4d8f0578e5bb23d6a863b4a2b5f309/lib/ModuleParseError.js#L79-L81

- https://github.com/webpack/webpack/blob/e2f1592f7e4d8f0578e5bb23d6a863b4a2b5f309/lib/ModuleDependencyError.js#L33

**What is the expected behavior?**
When `errorStack` is set to `false` no stacktraces are displayed.

**Other relevant information:**
```
Webpack: 5.73.0
 System:
    OS: Linux 5.17 Debian GNU/Linux rodete 12 (rodete)
    CPU: (48) x64 AMD EPYC 7B12
    Memory: 152.19 GB / 188.89 GB
  Binaries:
    Node: 14.19.2 - ~/.nvm/versions/node/v14.19.2/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v14.19.2/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v14.19.2/bin/npm
  Browsers:
    Chrome: 103.0.5060.53
    Firefox: 91.10.0esr
```

FYI: @alexander-akait

**Comment by sokra** [comment]
`errorStack` only refers to (webpack)-internal stack traces.
Stack traces from loaders can be disabled with `errorDetails: false`

**Comment by alan-agius4** [comment]
I am pretty sure that sure that even when `errorDetails` is set to false the above stacktraces are also shown.

**Comment by alan-agius4** [comment]
bump

**Comment by alexander-akait** [comment]
Okay, I done investigation on the latest version of webpack and sass-loader (and other CSS like loaders), shorty:
- `errorStack` allows to enable and disable stack, so it works correctly
- `errorDetails` show details from error in some cases it not looks good, because it duplicate an error message
- `hideStack` works fine and webpack hine stack

The main problems some tools (for example node-sass, maybe due bindling) put stack inside message, so because of `errorDetails` enabled by default you see the stack, but this stack just in error message...

Anyway I see this problem:
- when `hideStack: true` and `errorDetails: true`, webpack duplicate error mesage

**Comment by alexander-akait** [comment]
Example:
```js
console.log("---");
console.log("Message:", sassError.message);
console.log("Stack:", sassError.stack);
console.log("---");
```

```
---
Message: Can't find stylesheet to import.
  ╷
1 │ @import "font-sawessome/scss/font-awesome";
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  src/test.scss 1:9  root stylesheet
Stack: Error: Can't find stylesheet to import.
  ╷
1 │ @import "font-sawessome/scss/font-awesome";
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  src/test.scss 1:9  root stylesheet
    at Object.wrapException (/home/akait/IdeaProjects/webpack/node_modules/sass/sass.dart.js:1237:17)
    at NodeImporter._handleImportResult$4 (/home/akait/IdeaProjects/webpack/node_modules/sass/sass.dart.js:87729:17)
    at /home/akait/IdeaProjects/webpack/node_modules/sass/sass.dart.js:87649:50
    at _wrapJsFunctionForAsync_closure.$protected (/home/akait/IdeaProjects/webpack/node_modules/sass/sass.dart.js:3828:15)
    at _wrapJsFunctionForAsync_closure.call$2 (/home/akait/IdeaProjects/webpack/node_modules/sass/sass.dart.js:28886:12)
    at _awaitOnObject_closure.call$1 (/home/akait/IdeaProjects/webpack/node_modules/sass/sass.dart.js:28874:32)
    at Object._rootRunUnary (/home/akait/IdeaProjects/webpack/node_modules/sass/sass.dart.js:4203:18)
    at StaticClosure.<anonymous> (/home/akait/IdeaProjects/webpack/node_modules/sass/sass.dart.js:101628:16)
    at _CustomZone.runUnary$2$2 (/home/akait/IdeaProjects/webpack/node_modules/sass/sass.dart.js:30283:39)
    at _Future__propagateToListeners_handleValueCallback.call$0 (/home/akait/IdeaProjects/webpack/node_modules/sass/sass.dart.js:29355:51)
---
```

**Comment by Soham-0816** [comment]
Hi! I’d like to work on fixing this issue. I plan to update the error handling logic so that errorStack: false is respected. Thanks!
