### ISSUE TITLE
ProviderPlugin fails with TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by zackp30** [webpack/webpack#1601]
Trying to use the ProviderPlugin using:

```javascript
var webpack = require('webpack');
var path = require('path');
module.exports = {
    entry: "./source/javascripts/main.js",
    output: {
        path: __dirname,
        filename: "build/bundle.js"
    },
    module: {
        loaders: [
            { test: /\.css$/, loader: "style!css" },
            { test: /\.jsx?$/, loader: "babel" },
            { test: /jquery\/src\/selector\.js$/, loader: 'amd-define-factory-patcher-loader' }
        ]
    },
    resolve: {
        root: [path.join(__dirname, 'bower_components')]
    },
    plugins: [
        new webpack.ResolverPlugin(
            new webpack.ResolverPlugin.DirectoryDescriptionFilePlugin('bower.json', ['main'])
        ),
        new webpack.ProvidePlugin({
            $: 'jquery/src/jquery.js',
            jQuery: 'jquery/src/jquery.js',
            "window.jQuery": 'jquery/src/jquery.js',
            "root.jQuery": 'jquery/src/jquery.js'
        })
    ]
};
```

Fails with:

```
$ webpack-dev-server --hot --inline --port 8089                                             0
http://localhost:8089/
webpack result is served from /
content is served from /home/zack/research
/home/zack/.nvm/versions/io.js/v3.0.0/lib/node_modules/webpack-dev-server/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:163
                        if(isError) throw e;
                                    ^

TypeError: Cannot read property 'name' of undefined
    at Compilation.addModuleDependencies (/home/zack/.nvm/versions/io.js/v3.0.0/lib/node_modules/webpack-dev-server/node_modules/webpack/lib/Compilation.js:180:108)
    at Compilation.processModuleDependencies (/home/zack/.nvm/versions/io.js/v3.0.0/lib/node_modules/webpack-dev-server/node_modules/webpack/lib/Compilation.js:170:7)
    at Compilation.<anonymous> (/home/zack/.nvm/versions/io.js/v3.0.0/lib/node_modules/webpack-dev-server/node_modules/webpack/lib/Compilation.js:319:11)
    at /home/zack/.nvm/versions/io.js/v3.0.0/lib/node_modules/webpack-dev-server/node_modules/webpack/lib/Compilation.js:123:4
    at Array.forEach (native)
    at callback (/home/zack/.nvm/versions/io.js/v3.0.0/lib/node_modules/webpack-dev-server/node_modules/webpack/lib/Compilation.js:122:12)
    at Compilation.<anonymous> (/home/zack/.nvm/versions/io.js/v3.0.0/lib/node_modules/webpack-dev-server/node_modules/webpack/lib/Compilation.js:140:10)
    at DependenciesBlock.<anonymous> (/home/zack/.nvm/versions/io.js/v3.0.0/lib/node_modules/webpack-dev-server/node_modules/webpack/lib/NormalModule.js:115:10)
    at DependenciesBlock.onModuleBuild (/home/zack/.nvm/versions/io.js/v3.0.0/lib/node_modules/webpack-dev-server/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
    at nextLoader (/home/zack/.nvm/versions/io.js/v3.0.0/lib/node_modules/webpack-dev-server/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
```

**Comment by zackp30** [comment]
Never mind, outdated webpack-dev-server.
