### ISSUE TITLE
Dev mode hashUpdate method not found

### ISSUE THREAD

**Issue by blueiceprj** [webpack/webpack#16057]
Hi,
When I start  angular app getting this error and stop running. I have never changed app configuration and before everything was working properly.  

```
Angular CLI: 14.0.6
Node: 16.16.0
Package Manager: npm 8.11.0 
OS: darwin x64

Angular: 14.0.6
... animations, cli, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1400.6
@angular-devkit/build-angular   14.0.6
@angular-devkit/core            14.0.6
@angular-devkit/schematics      14.0.6
@schematics/angular             14.0.6
rxjs                            7.5.6
typescript                      4.7.4

```

```
...../node_modules/webpack/lib/cache/getLazyHashedEtag.js:35
                        this._obj.updateHash(hash);
                                  ^

TypeError: this._obj.updateHash is not a function
    at LazyHashedEtag.toString (/../node_modules/webpack/lib/cache/getLazyHashedEtag.js:35:14)
    at ../node_modules/webpack/lib/cache/PackFileCacheStrategy.js:1213:53
    at async Promise.all (index 22)
```

```
"webpack": "5.71.0"
"webpack-bundle-analyzer": "4.5.0",
"webpack-cli": "4.10.0",
"webpack-merge": "5.8.0",
"webpack-notifier": "1.15.0"
"typescript": "4.7.4",

```

**Comment by alexander-akait** [comment]
Pleae open an issue in `angular` or fill out all fields in the issue template, especially - `How we can reproduce`, otherwise we can't help, thank you, I will reopen when you fixed it

**Comment by blueiceprj** [comment]
Sorry this my fault. Finally I found it. I use "compression-webpack-plugin".  This plugin cause the problem. I moved plugin config from development to production on custom webpack configuration. Its working properly right now.
Before

```
 new CompressionPlugin()

```

Now 

```
 new CompressionPlugin({
                algorithm: 'gzip',
            })
```

**Comment by 0xdevalias** [comment]
See also:

- https://github.com/webpack-contrib/compression-webpack-plugin/issues/346
