### ISSUE TITLE
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'babel-preset-env' imported from /app/babel-virtual-resolve-base.js

### ISSUE THREAD

**Issue by ridhwaans** [webpack/webpack#16062]
I already have @babel/preset-env installed and in `.babelrc` but for some reason it is throwing a babel-preset-env error  
All my packages + peerdependency are the latest version, see `package.json`.  
I removed `package-lock.json`, `/node_modules`, ran `npm cache clean --force` and npm i reinstalled, still getting the same error when building webpack 

```
npm run build

> app build
> webpack

assets by status 1.44 KiB [cached] 1 asset
./src/components/app/index.js 39 bytes [built] [code generated] [1 error]

ERROR in ./src/components/app/index.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'babel-preset-env' imported from app/babel-virtual-resolve-base.js
    at new NodeError (app/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:2669:5)
    at packageResolve (app/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:3325:9)
    at moduleResolve (app/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:3359:18)
    at defaultResolve (app/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:3398:13)
    at app/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:3421:14
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (//node_modules/@babel/core/lib/vendor/import-meta-resolve.js:63:103)
    at _next (//node_modules/@babel/core/lib/vendor/import-meta-resolve.js:65:194)
    at //node_modules/@babel/core/lib/vendor/import-meta-resolve.js:65:364
    at new Promise (<anonymous>)

webpack 5.73.0 compiled with 1 error in 235 ms
```

.babelrc
```
{
  "presets": [
    "@babel/preset-env",
    "@babel/preset-react"
  ]
}
```

package.json
```
"scripts": {
    "prepare": "npm run build",
    "start": "webpack-dev-server --config webpack.config.dev.js",
    "build": "webpack",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "prettier": {
    "singleQuote": true,
    "trailingComma": "all",
    "arrowParens": "avoid",
    "tabWidth": 2,
    "useTabs": false,
    "printWidth": 120
  },
"devDependencies": {
    "@babel/core": "^7.18.6",
    "@babel/preset-env": "^7.18.6",
    "babel-loader": "^8.2.5",
    "eslint": "^8.20.0",
    "eslint-config-airbnb": "^19.0.4",
    "eslint-config-prettier": "^8.5.0",
    "eslint-plugin-import": "^2.26.0",
    "eslint-plugin-jsx-a11y": "^6.6.0",
    "eslint-plugin-prettier": "^4.2.1",
    "eslint-plugin-react": "^7.30.1",
    "eslint-plugin-react-hooks": "^4.6.0",
    "prettier": "^2.7.1",
    "webpack": "^5.73.0",
    "webpack-cli": "^4.10.0",
    "webpack-dev-server": "^4.9.3"
  },
  "peerDependencies": {
    "react": ">=18.2",
    "react-dom": ">=18.2"
  },
  "dependencies": {
    "i18next": "^21.8.14",
    "npm-check-updates": "^15.3.4",
    "react": ">=18.2",
    "react-dom": ">=18.2",
    "react-i18next": "^11.18.1",
    "react-icons": "^4.4.0",
    "styled-components": "^5.3.5"
  }
```
thanks in advance

**Comment by Magin-CC** [comment]
Maybe you have babel config in webpack config file?

**Comment by alexander-akait** [comment]
Please open an issue in `babel` repo, thank you

**Comment by EHJ-52n** [comment]
@ridhwaans did you open an issue in the babel repository? If yes, please add a link here, thank you.
