### ISSUE TITLE
Invalid value used as weak map key

### ISSUE THREAD

**Issue by bkotsopoulossc** [webpack/webpack#16134]
# Bug report

**What is the current behavior?**

I have a project where I am using the webpack 5 webassembly resource loader. It works great. The webassembly binary is apart of an npm package that my project depends on.

Sometimes I want to build that webassembly library locally, and when I do, I `yarn link` the other package to my webpack project. I also build a debug version of the webassembly binary which is much bigger than the one that is used otherwise (hundreds of MBs).

In this linked mode, every time I rebuild the webassembly binary, it triggers the hot reloader, and fails with this trace:
```
<e> [webpack-dev-middleware] HookWebpackError: Invalid value used as weak map key
<e>     at makeWebpackError (<home_directory>/my_webpack_project/node_modules/webpack/lib/HookWebpackError.js:48:9)
<e>     at <home_directory>/my_webpack_project/node_modules/webpack/lib/Compilation.js:3060:12
<e>     at eval (eval at create (<home_directory>/my_webpack_project/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:20:1)
<e>     at runMicrotasks (<anonymous>)
<e>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
<e> -- inner error --
<e> TypeError: Invalid value used as weak map key
<e>     at WeakMap.set (<anonymous>)
<e>     at toCachedSource (<home_directory>/my_webpack_project/node_modules/webpack/lib/optimize/RealContentHashPlugin.js:70:18)
<e>     at <home_directory>/my_webpack_project/node_modules/webpack/lib/optimize/RealContentHashPlugin.js:148:28
<e>     at fn (<home_directory>/my_webpack_project/node_modules/webpack/lib/Compilation.js:536:19)
<e>     at _next8 (eval at create (<home_directory>/my_webpack_project/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:12:17)
<e>     at eval (eval at create (<home_directory>/my_webpack_project/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:29:1)
<e>     at eval (eval at create (<home_directory>/my_webpack_project/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
<e>     at <home_directory>/my_webpack_project/node_modules/webpack/lib/SourceMapDevToolPlugin.js:549:10
<e>     at <home_directory>/my_webpack_project/node_modules/neo-async/async.js:2830:7
<e>     at Object.each (<home_directory>/my_webpack_project/node_modules/neo-async/async.js:2857:9)
<e> caused by plugins in Compilation.hooks.processAssets
<e> TypeError: Invalid value used as weak map key
<e>     at WeakMap.set (<anonymous>)
<e>     at toCachedSource (<home_directory>/my_webpack_project/node_modules/webpack/lib/optimize/RealContentHashPlugin.js:70:18)
<e>     at <home_directory>/my_webpack_project/node_modules/webpack/lib/optimize/RealContentHashPlugin.js:148:28
<e>     at fn (<home_directory>/my_webpack_project/node_modules/webpack/lib/Compilation.js:536:19)
<e>     at _next8 (eval at create (<home_directory>/my_webpack_project/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:12:17)
<e>     at eval (eval at create (<home_directory>/my_webpack_project/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:29:1)
<e>     at eval (eval at create (<home_directory>/my_webpack_project/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
<e>     at <home_directory>/my_webpack_project/node_modules/webpack/lib/SourceMapDevToolPlugin.js:549:10
<e>     at <home_directory>/my_webpack_project/node_modules/neo-async/async.js:2830:7
<e>     at Object.each (<home_directory>/my_webpack_project/node_modules/neo-async/async.js:2857:9)
```

**If the current behavior is a bug, please provide the steps to reproduce.**

I don't have a good way to reproduce this just yet. I'm happy to try and debug this, any idea where to start? Is there somewhere in this stack that may have an issue with large files?

**What is the expected behavior?**

The hot-reloader picks up the change to the webassembly binary, builds and the devserver reloads the app with the new files.

**Other relevant information:**
webpack version:  5.74.0
Node.js version: 17.8
Operating System: MacOS 12.5
Additional tools:

**Comment by vankop** [comment]
please create reproducible repo

**Comment by vankop** [comment]
> webpack 5 webassembly resource loader

I didn't get this.. could you link github if this loader?

**Comment by alexander-akait** [comment]
Closing due to inactivity. Please test with latest version and feel free to reopen if still regressions. Thanks!
