### ISSUE TITLE
Can not resolve UglifyJS error

### ISSUE THREAD

**Issue by IngwiePhoenix** [webpack/webpack#1615]
This:

```
ERROR in 790e10db00a27b6dd6c9-upload.js from UglifyJs
TypeError: Cannot read property 'indexOf' of undefined
    at AST_Node.eval [as has_directive] (eval at <anonymous> (/Users/Ingwie/Work/BIRD3/node_modules/webpack/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:3281:28)
    at Object.TreeWalker.has_directive (eval at <anonymous> (/Users/Ingwie/Work/BIRD3/node_modules/webpack/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:1277:44)
    at AST_Node.eval [as hoist_declarations] (eval at <anonymous> (/Users/Ingwie/Work/BIRD3/node_modules/webpack/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:6203:24)
    at Object.merge.before (eval at <anonymous> (/Users/Ingwie/Work/BIRD3/node_modules/webpack/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:5086:25)
    at AST_Node.eval [as transform] (eval at <anonymous> (/Users/Ingwie/Work/BIRD3/node_modules/webpack/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2877:35)
    at AST_Node.eval [as optimize] (eval at <anonymous> (/Users/Ingwie/Work/BIRD3/node_modules/webpack/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:5110:24)
    at Object.merge.before (eval at <anonymous> (/Users/Ingwie/Work/BIRD3/node_modules/webpack/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:5090:21)
    at AST_Node.eval [as transform] (eval at <anonymous> (/Users/Ingwie/Work/BIRD3/node_modules/webpack/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2877:35)
    at eval (eval at <anonymous> (/Users/Ingwie/Work/BIRD3/node_modules/webpack/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:6897:60)
    at AST_Node.eval [as optimize] (eval at <anonymous> (/Users/Ingwie/Work/BIRD3/node_modules/webpack/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:5107:23)
    at Object.merge.before (eval at <anonymous> (/Users/Ingwie/Work/BIRD3/node_modules/webpack/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:5090:21)
    at AST_Node.eval [as transform] (eval at <anonymous> (/Users/Ingwie/Work/BIRD3/node_modules/webpack/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2877:35)
    at eval (eval at <anonymous> (/Users/Ingwie/Work/BIRD3/node_modules/webpack/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:3031:33)
    at Object.merge.before (eval at <anonymous> (/Users/Ingwie/Work/BIRD3/node_modules/webpack/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:5089:9)
    at AST_Node.eval [as transform] (eval at <anonymous> (/Users/Ingwie/Work/BIRD3/node_modules/webpack/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2877:35)
    at eval (eval at <anonymous> (/Users/Ingwie/Work/BIRD3/node_modules/webpack/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2896:25)
    at doit (eval at <anonymous> (/Users/Ingwie/Work/BIRD3/node_modules/webpack/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:125:23)
    at MAP (eval at <anonymous> (/Users/Ingwie/Work/BIRD3/node_modules/webpack/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:151:52)
    at do_list (eval at <anonymous> (/Users/Ingwie/Work/BIRD3/node_modules/webpack/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2895:16)
    at eval (eval at <anonymous> (/Users/Ingwie/Work/BIRD3/node_modules/webpack/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:3027:27)
    at Object.merge.before (eval at <anonymous> (/Users/Ingwie/Work/BIRD3/node_modules/webpack/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:5089:9)
    at AST_Node.eval [as transform] (eval at <anonymous> (/Users/Ingwie/Work/BIRD3/node_modules/webpack/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2877:35)
    at eval (eval at <anonymous> (/Users/Ingwie/Work/BIRD3/node_modules/webpack/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2896:25)
    at doit (eval at <anonymous> (/Users/Ingwie/Work/BIRD3/node_modules/webpack/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:125:23)
    at MAP (eval at <anonymous> (/Users/Ingwie/Work/BIRD3/node_modules/webpack/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:151:52)
    at do_list (eval at <anonymous> (/Users/Ingwie/Work/BIRD3/node_modules/webpack/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2895:16)
    at eval (eval at <anonymous> (/Users/Ingwie/Work/BIRD3/node_modules/webpack/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2990:21)
    at Object.merge.before (eval at <anonymous> (/Users/Ingwie/Work/BIRD3/node_modules/webpack/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:5089:9)
    at AST_Node.eval [as transform] (eval at <anonymous> (/Users/Ingwie/Work/BIRD3/node_modules/webpack/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2877:35)
    at eval (eval at <anonymous> (/Users/Ingwie/Work/BIRD3/node_modules/webpack/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2908:31)
```

happens as long as this

```javascript
var filedrop = require("legacy!filedrop").fd;
```

exists. Commenting it out silences the error.

What exactly is Uglify's problem?

**Comment by bebraw** [comment]
Can you reproduce this in isolation directly through Uglify? If so, please push this issue upstream and link here.

**Comment by sokra** [comment]
Looks like a UglifyJs error to me.

**Comment by IngwiePhoenix** [comment]
I forgot to close this. 2.6.0 actually fixed that.
