### ISSUE TITLE
Require.resolve not resolving for target:node bundles

### ISSUE THREAD

**Issue by iyibu** [webpack/webpack#16161]
# Bug report

**What is the current behavior?**
My goal is create a standalone bundle. (Optimization, tree shaking whatever doesn't matter)
Source code has non-standard/unusual coding (for ex. require(require.resolve) instead of require)
I think that this require minimum config of webpack. 
Expected scenario: a commonjs script that need any node_modules package and run as portable (without any install, npm or etc.)

Here is my example code and config for target:node bundle.

index.js
```
const f = require.resolve("./import.js")

require(f)()
```

import.js
```
const lodash = require("lodash")

const f = () => {
    console.log(lodash.add(6, 4))
}

module.exports = f
```

webpack.config.js
```
/** @type {import('webpack').Configuration} */
module.exports = {
    devtool: "inline-source-map",
    mode: "development",
    entry: "./index.js",
    target: "node",
    output: {
        chunkFilename: '[id].js',
        globalObject: 'this',
    },
    optimization: {
        minimize: false,
        splitChunks: {
            chunks: "all",
            minSize: 0
        },
    }
}
```

**If the current behavior is a bug, please provide the steps to reproduce.**
```
webpack build --stats-error-details
```
```
node dist/main.js
```
here is the console output
```
D:\lab\bundle\dist\main.js:41
        throw e;
        ^

Error: Cannot find module './import.js'
    at webpackEmptyContext (D:\lab\bundle\dist\main.js:39:10)
    at Object../index.js (D:\lab\bundle\dist\main.js:28:42)
    at __webpack_require__ (D:\lab\bundle\dist\main.js:70:42)
    at D:\lab\bundle\dist\main.js:86:121
    at Function.__webpack_require__.O (D:\lab\bundle\dist\main.js:116:23)
    at __webpack_require__.x (D:\lab\bundle\dist\main.js:87:54)
    at Function.__webpack_require__.x (D:\lab\bundle\dist\main.js:207:20)
    at D:\lab\bundle\dist\main.js:214:57
    at Object.<anonymous> (D:\lab\bundle\dist\main.js:216:12)
    at Module._compile (node:internal/modules/cjs/loader:1101:14) {
  code: 'MODULE_NOT_FOUND'
}
```

**What is the expected behavior?**
When i run as unbundled version like this
```
node ./index.js
```
I get this output
```
PS D:\lab\bundle> node .\index.js
10
```

**Here is the interesting point**
When i look at the dist/main.js, i see import.js's source code 
```
/***/ "./import.js":
/*!*******************!*\
  !*** ./import.js ***!
  \*******************/
/***/ ((module, __unused_webpack_exports, __webpack_require__) => {

const lodash = __webpack_require__(/*! lodash */ "./node_modules/lodash/lodash.js")

const f = () => {
    console.log(lodash.add(6, 4))
}

module.exports = f
```

**Other relevant information:**
webpack version:  5.74.0
Node.js version:  16.13.0
Operating System: Windows 10
Additional tools: no

**Comment by alexander-akait** [comment]
Do you have `index.js`?

**Comment by iyibu** [comment]
-

**Comment by iyibu** [comment]
@alexander-akait yes. i wrote my example source code under **Here is my example code and config for target:node bundle.**

**Comment by alexander-akait** [comment]
Try this `const f = require.resolve("./import")`

**Comment by iyibu** [comment]
@alexander-akait  If i dont bundle with webpack and run source code with `node ./index.js` everything ok.
But bundled version has a problem.
Imagine that i can NOT change source code. 
index.js is an example (source code is more complicated), main.js is bundled version.

**Comment by alexander-akait** [comment]
`require(f)()` is not staticailly analizable, so sorry, it is impossible

**Comment by vankop** [comment]
you should get an error for `require(f)()` btw

**Comment by iyibu** [comment]
> you should get an error for `require(f)()` btw

No. Try it with node index.js

**Comment by iyibu** [comment]
I am trying with @percel/ncc's elevator. but a little bit weak.

**Comment by alexander-akait** [comment]
```
const f = require.resolve("./import.js")

require(f)()
```

is not statical analizable, we don't know how you can change `f`, so we keep `require` as is, but after bundling you don't have `import.js` anymore and get this error, so sorry

**Comment by Magin-CC** [comment]
How about give a warning when using dynamic require ?

**Comment by alexander-akait** [comment]
You can setup linter and catch these cases on CI or during lint step
