### ISSUE TITLE
Using Webpack Module Federation breaks Workers

### ISSUE THREAD

**Issue by edusperoni** [webpack/webpack#16173]
# Bug report

**What is the current behavior?**

When using shared modules with Webpack Module Federations, the worker chunk will contain references to shared contexts, but the worker runtime does not contain any information on how to load these contexts.

**If the current behavior is a bug, please provide the steps to reproduce.**

Simple reproduction repo: https://github.com/edusperoni/wmf-worker-bug

**What is the expected behavior?**

Worker runtime should contain the relevant information to load the modules, even if they're limited to eagerly loaded dependencies.

This "fixes" the issue by getting the needed information from the main chunk and adding them in the worker chunk 'consume-shared' section:

```
// lib/sharing/ConsumeSharedRuntimeModule.js
                 // Here we grab the "main" chunk, which contains all the needed information about eagerly shared modules
                 const extraChunk = [Array.from(compilation.chunks)[0]];
		// const extraChunk = [];
		for (const chunk of [...this.chunk.getAllAsyncChunks(),...extraChunk]) {
			const modules = chunkGraph.getChunkModulesIterableBySourceType(
				chunk,
				"consume-shared"
			);
			if (!modules) continue;
			addModules(modules, chunk, (chunkToModuleMapping[chunk.id] = []));
		}
		for (const chunk of [...this.chunk.getAllInitialChunks(),...extraChunk]) {
			const modules = chunkGraph.getChunkModulesIterableBySourceType(
				chunk,
				"consume-shared"
			);
			if (!modules) continue;
			addModules(modules, chunk, initialConsumes);
		}
```

I'm unfortunately not that well versed in the webpack source code, but it seems like we should be able to resolve this by passing the parent information related to shared modules to the worker to solve this issue.

Note: the above fix doesn't work if you have other chunks, as it only gets the information from the "main" chunk

**Other relevant information:**
webpack version:  5.74.0
Node.js version:  v16.13.2
Operating System: macOS 12.5

**Comment by edusperoni** [comment]
After digging quite a lot more, I found that, in `lib/sharing/ConsumeSharedRuntimeModule.js`, replacing:

```
for (const chunk of this.chunk.getAllInitialChunks()) {
```

With:

```
for (const chunk of this.chunk.getAllReferencedChunks()) {
```

Fixed the issue in the workers (both the test scenario and real world scenario). I'm sure this might not be the correct approach, but maybe those get functions are not properly picking up the required information on a worker context (where most likely everything should be an "initial chunk"), most likely due to the unique way worker entrypoints are generated.

**Comment by edusperoni** [comment]
Ok, I think I found the final issue, but i'm not sure if this is something that we should handle in WMF or the "rest" of webpack.

1. Worker is created in lib/dependencies/WorkerPlugin.js as an `AsyncDependenciesBlock`  https://github.com/webpack/webpack/blob/9fcaa243573005d6fdece9a3f8d89a0e8b399613/lib/dependencies/WorkerPlugin.js#L290
2. lib/buildChunkGraph.js will then call `addAsyncEntrypoint` and `connectBlockAndChunkGroup` https://github.com/webpack/webpack/blob/9fcaa243573005d6fdece9a3f8d89a0e8b399613/lib/buildChunkGraph.js#L412 https://github.com/webpack/webpack/blob/9fcaa243573005d6fdece9a3f8d89a0e8b399613/lib/buildChunkGraph.js#L443
3. this entrypoint is created with `initial: false` https://github.com/webpack/webpack/blob/9fcaa243573005d6fdece9a3f8d89a0e8b399613/lib/Compilation.js#L3626
4. the worker is not considered an initial entrypoint, so no WMF sharing information is added to it's runtime.

So the solution might be: add another flag to the `AsyncDependenciesBlock` that either makes it a initial entrypoint (affects webpack as a whole), or adds another flag to the `Entrypoint` that WMF can query when gathering what should/shouldn't be included in the Runtime.

**Comment by ScriptedAlchemy** [comment]
What about setting runtime: false on module federation plugin?

If you have runtimeChunk: single - it can cause some issues - I've seen similar problems with webpack ESM output when there's multiple entry points and a single runtime chunk

**Comment by edusperoni** [comment]
@ScriptedAlchemy setting runtime false makes no difference in the output. The worker will always have it's own runtime regardless of setting, but WMF will not add the needed information in it due to the things in my previous comment

**Comment by ScriptedAlchemy** [comment]
@vankop  @sokra any ideas here? this looks like a bug in webpack for making worker runtime be an initial chunk

**Comment by edusperoni** [comment]
I managed to find a workaround. Thanks so much to @ScriptedAlchemy for the help on this.

Essentially I'm finding chunks that are both entrypoints and runtimes of a group and I mark them as initial.

```
class MarkWorkerAsInitialPlugin {
    constructor() { }
    /**
     * Apply the plugin
     * @param {import('webpack').Compiler} compiler the compiler instance
     * @returns {void}
     */
    apply(compiler) {
        compiler.hooks.compilation.tap('MarkWorkerAsInitialPlugin', (compilation) => {
            compilation.hooks.optimizeChunks.tap('MarkWorkerAsInitialPlugin', (chunks) => {
                for (const chunk of chunks) {
                    for (const chunkGroup of chunk.groupsIterable) {
                        if (chunkGroup._entrypointChunk === chunkGroup._runtimeChunk) {
                            chunkGroup._initial = true;
                        }
                    }
                }
            });
        });
    }
}
```

I'm interested in finding out a way to do this inside webpack's code, so we can mark these entrypoints as initial if we're using module federation (or maybe this is another condition we might have to check when generating the module federation runtime)

**Comment by ScriptedAlchemy** [comment]
This does seem like a legitimate bug, entry flag should check runtime requirements for runtime globals related to module federation (init, get, share, consume) or chunk loading or if chunk includes references to remote-module or provide-module

**Comment by alexander-akait** [comment]
Makred as bug, feel free to send a fix

**Comment by alexander-akait** [comment]
bump

**Comment by Zelinsky-Vladimir** [comment]
bump

**Comment by MR-BH** [comment]
bump

**Comment by alexander-akait** [comment]
bump

**Comment by MatejFacko** [comment]
bump

**Comment by israeligal** [comment]
bump

**Comment by krassowski** [comment]
Oh come on.. can s a human reopen it please?

**Comment by wndffs** [comment]
bump

**Comment by unadlib** [comment]
Any update？

**Comment by ScriptedAlchemy** [comment]
Okay I've run into this. It's related to runtime chunks etc. Just change get all async chunks to get all referenced chunks.  Allows tracking of split chunks then as well. 
Can send pr it's a 2 line change in 2 files. 
This is what I do in the v2 plugin, but worker has other issues

**Comment by unadlib** [comment]
> Okay I've run into this. It's related to runtime chunks etc. Just change get all async chunks to get all referenced chunks. Allows tracking of split chunks then as well. Can send pr it's a 2 line change in 2 files. This is what I do in the v2 plugin, but worker has other issues

So this issue won't be addressed anytime soon? Or any more specific details? Maybe I can try to fix it.

**Comment by ScriptedAlchemy** [comment]
You can open a pr if you want. Otherwise I will. 
I even mention this change is needed to also remove need for async import. 

https://github.com/webpack/webpack/issues/18812

It's the last section of my issue. Where get all referenced chunks is. Even mentions the files. It's night here and I have flights this week. But if you send a PR for just that update, it needed to be done anyways. But in my body of work it might take longer. So send a PR just with the referenced chunks, if you can. 

Otherwise I'll try to send one before I leave.

**Comment by ScriptedAlchemy** [comment]
Ill send the PR as i do not see one mentions here yet.

**Comment by ScriptedAlchemy** [comment]
PR here: https://github.com/webpack/webpack/pull/18859

@unadlib wanna check if it fixes your issue?

**Comment by unadlib** [comment]
@ScriptedAlchemy 

Thanks for your PR.

It fixed part of it, but now there's an error involving the use of `document` in the worker.

<img width="1062" alt="image" src="https://github.com/user-attachments/assets/a2f341c6-748f-4826-8c9f-2011654fbc9a">

**Comment by alexander-akait** [comment]
@unadlib Can you show a code at the stack trace? Maybe you use a package which use `document`

**Comment by unadlib** [comment]
> @unadlib Can you show a code at the stack trace? Maybe you use a package which use `document`

Based on the repo https://github.com/grzesiek-ds/webpack-mf-workers, I modified the webpack fix PR code in `node_modules/webpack/lib`, and it can reproduce this error.

```
Uncaught (in promise) ReferenceError: document is not defined
while loading "./testValue" from webpack/container/reference/myModule
    at __webpack_require__.l (host-chunk-host_src_worker_js-webpack_container_reference_myModule.js:189:28)
    at host-chunk-host_src_worker_js-webpack_container_reference_myModule.js:32:22
    at new Promise (<anonymous>)
    at webpack/container/reference/myModule (host-chunk-host_src_worker_js-webpack_container_reference_myModule.js:30:18)
    at __webpack_require__ (host-chunk-host_src_worker_js-webpack_container_reference_myModule.js:66:41)
    at handleFunction (host-chunk-host_src_worker_js-webpack_container_reference_myModule.js:271:31)
    at host-chunk-host_src_worker_js-webpack_container_reference_myModule.js:290:15
    at Array.forEach (<anonymous>)
    at __webpack_require__.f.remotes (host-chunk-host_src_worker_js-webpack_container_reference_myModule.js:253:36)
    at host-chunk-host_src_worker_js-webpack_container_reference_myModule.js:148:40
```

**Comment by ScriptedAlchemy** [comment]
Container references are still using the normal require.l

In v2 I know how to fix this. But not sure in v1

**Comment by unadlib** [comment]
> Container references are still using the normal require.l
> 
> In v2 I know how to fix this. But not sure in v1

How did you solve this in v2? Perhaps you could let me try it? :)

**Comment by ScriptedAlchemy** [comment]
I use runtime plugins.
We have a loadEntry hook,
so we do not use any of webpack's built-in loading mechanisms for scripts.
We support a few out of the box.
And for React Native or Node, we just use a runtime plugin.

**Comment by unadlib** [comment]
I have successfully used MF in SharedWorker without relying on the fix PR https://github.com/webpack/webpack/pull/18859.

https://github.com/unadlib/webpack-mf-workers

### How to fix

1. Use SharedWorker instead of Worker in host application
2. Dynamically import bootstrap file in worker thread
3. Use promise based dynamic remotes `host/webpack.host-config.js`
4. Use multiple entry points in webpack config `module/webpack.module-config.js`

**Comment by ScriptedAlchemy** [comment]
> I have successfully used MF in SharedWorker without relying on the fix PR https://github.com/webpack/webpack/pull/18859.
> 
> https://github.com/unadlib/webpack-mf-workers
> 
> ### How to fix
> 
> 1. Use SharedWorker instead of Worker in host application
> 2. Dynamically import bootstrap file in worker thread
> 3. Use promise based dynamic remotes `host/webpack.host-config.js`
> 4. Use multiple entry points in webpack config `module/webpack.module-config.js`

Send a pr to federation examples repo please
