### ISSUE TITLE
Unable to require a css file

### ISSUE THREAD

**Issue by jpeg729** [webpack/webpack#1629]
As described on https://webpack.github.io/docs/stylesheets.html, and demonstrated on http://bensmithett.com/smarter-css-builds-with-webpack/

I am using the following versions, among others...
```
"css-loader": "^0.22.0",
"node-sass": "^3.4.1",
"sass-loader": "^3.1.1",
"style-loader": "^0.13.0",
"webpack": "^1.12.4",
```

If I do ```require("styles/file.css")``` I get ```Cannot resolve module ...```.
If I do ```require("./file.css")``` I get ```Cannot resolve 'file' or 'directory' ...```
If I do ```require("./styles/file.css")``` I get the following
```
/projdir/node_modules/webpack-core/lib/LoadersList.js:81
		r.forEach(function(r) {
		  ^

TypeError: r.forEach is not a function
    at /projdir/node_modules/webpack-core/lib/LoadersList.js:81:5
    at Array.reduce (native)
    at LoadersList.match (/projdir/node_modules/webpack-core/lib/LoadersList.js:80:27)
    at /projdir/node_modules/webpack/lib/NormalModuleFactory.js:111:68
    at /projdir/node_modules/webpack/node_modules/async/lib/async.js:721:13
    at /projdir/node_modules/webpack/node_modules/async/lib/async.js:52:16
    at done (/projdir/node_modules/webpack/node_modules/async/lib/async.js:246:17)
    at /projdir/node_modules/webpack/node_modules/async/lib/async.js:44:16
    at /projdir/node_modules/webpack/node_modules/async/lib/async.js:718:17
    at /projdir/node_modules/webpack/node_modules/async/lib/async.js:167:37
    at /projdir/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:29:4
    at onResolved (/projdir/node_modules/enhanced-resolve/lib/Resolver.js:39:10)
    at /projdir/node_modules/enhanced-resolve/lib/Resolver.js:123:21
    at /projdir/node_modules/enhanced-resolve/lib/Resolver.js:191:15
    at applyPluginsParallelBailResult.createInnerCallback.log (/projdir/node_modules/enhanced-resolve/lib/Resolver.js:104:30)
    at loggingCallbackWrapper (/projdir/node_modules/enhanced-resolve/lib/createInnerCallback.js:21:19)
    at /projdir/node_modules/tapable/lib/Tapable.js:134:6
    at innerCallback (/projdir/node_modules/enhanced-resolve/lib/Resolver.js:90:37)
    at loggingCallbackWrapper (/projdir/node_modules/enhanced-resolve/lib/createInnerCallback.js:21:19)
    at /projdir/node_modules/tapable/lib/Tapable.js:134:6
    at Tapable.<anonymous> (/projdir/node_modules/enhanced-resolve/lib/ResultSymlinkPlugin.js:39:32)
    at /projdir/node_modules/enhanced-resolve/lib/Resolver.js:191:15
    at /projdir/node_modules/enhanced-resolve/lib/ResultSymlinkPlugin.js:36:5
    at Storage.finished (/projdir/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at FSReqWrap.oncomplete (fs.js:82:15)
```

Css files defined by entry points do get treated as expected by webpack. I just can't require them from my .js files.

**Comment by jpeg729** [comment]
Requiring a .js file via ```require("./styles/file.js")``` works perfectly.

**Comment by jpeg729** [comment]
If I explicitly add the loaders to use, it works ```require("!style!css!./styles/file.css")```. But it doesn't seem right that I should need to given that I have told webpack how to load css files in ```webpack.config.js```

**Comment by bebraw** [comment]
Can you post your webpack configuration? It's hard to say anything concrete without.

**Comment by jpeg729** [comment]
```js
'use strict';
var path = require('path');
var HtmlWebpackPlugin = require('html-webpack-plugin');
var webpack = require('webpack');
var merge = require('webpack-merge');
var ExtractTextPlugin = require('extract-text-webpack-plugin');

var TARGET = process.env.npm_lifecycle_event;
var ROOT_PATH = path.resolve(__dirname);
var APP_PATH = path.resolve(ROOT_PATH, 'src');
var BUILD_PATH = path.resolve(ROOT_PATH, 'site');

var common = {
  entry:  {'app':APP_PATH+'/App.jsx'};
  module: {
    loaders: [
      {
        test: /\.css$/,
        loaders: [ 'style-loader', 'css-loader?sourceMap'],
        include: APP_PATH,
      },
      {
        test: /\.jsx?$/,
        loaders: ['babel'],
        include: APP_PATH,
      },
    ]
  },
  output: {
    path: BUILD_PATH,
    filename: '[name].js'
  },
  plugins: [
    new HtmlWebpackPlugin({
      title: 'Site title'
    }),
    new ExtractTextPlugin('[name].css'),
  ],
};

if(TARGET === 'start' || !TARGET) {
  module.exports = merge(common, {
    devtool: 'eval-source-map',
    devServer: {
      contentBase: BUILD_PATH,
      historyApiFallback: true,
      hot: true,
      inline: true,
      progress: true
    },
    plugins: [
      new webpack.HotModuleReplacementPlugin(),
      new OpenBrowserPlugin({ url: 'http://localhost:8080' }),
    ],
  });
}
else if(TARGET === 'build') {
  module.exports = merge(common, {
    // TODO static build stuff, uglify etc.
  });
}
```

**Comment by bebraw** [comment]
The problem might be that it doesn't look for CSS at your style directory.

Instead of

```javascript
      {
        test: /\.css$/,
        loaders: [ 'style-loader', 'css-loader?sourceMap'],
        include: APP_PATH,
      },
```

you'll want something like

```javascript
      {
        test: /\.css$/,
        loaders: [ 'style-loader', 'css-loader?sourceMap'],
        include: [APP_PATH, STYLE_PATH],
      },
```

where `STYLE_PATH` points at `./styles`.

If styles are below `APP_PATH`, the current configuration should be enough, though.

**Comment by jpeg729** [comment]
I found a solution. Adding this to the config makes it work.
```js
resolve: {
    modulesDirectories: ['src', 'node_modules']
}
```
Webpack does not search for modules in subdirectories of the entry point dir, (maybe it doesn't even search in the entry point dir either - I haven't tested). This is either a design decision or an oversight. If it is a design decision, maybe it should be more clearly documented.

I'm still getting pretty much the same error when I try adding the `ExtractTextPlugin` into the mix, but I guess this isn't the right place for that bug.

**Comment by bebraw** [comment]
@jpeg729 If you can set up a project at GitHub, I can have a closer look.

**Comment by IngwiePhoenix** [comment]
@jpeg729 Files are always resolved **relative** to the current. Adding the `src` key actually makes me believe that you may have to `require("./src/styles/file.css")`.

As @bebraw said, it would be nice if we could reproduce your issue via a github repo, or a gist.

**Comment by regiondavid** [comment]
I use `import style from "./dirs/style.css"` successfully at last.
