### ISSUE TITLE
Digital envelope routines not working on react

### ISSUE THREAD

**Issue by prabhuteja985** [webpack/webpack#16349]
# Bug report

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (C:\Users\admin\Downloads\new\examination-management-system\client\esm-client\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\admin\Downloads\new\examination-management-system\client\esm-client\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (C:\Users\admin\Downloads\new\examination-management-system\client\esm-client\node_modules\webpack\lib\NormalModule.js:471:10)
    at C:\Users\admin\Downloads\new\examination-management-system\client\esm-client\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\Users\admin\Downloads\new\examination-management-system\client\esm-client\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\Users\admin\Downloads\new\examination-management-system\client\esm-client\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\Users\admin\Downloads\new\examination-management-system\client\esm-client\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (C:\Users\admin\Downloads\new\examination-management-system\client\esm-client\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
C:\Users\admin\Downloads\new\examination-management-system\client\esm-client\node_modules\react-scripts\scripts\start.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (C:\Users\admin\Downloads\new\examination-management-system\client\esm-client\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\admin\Downloads\new\examination-management-system\client\esm-client\node_modules\webpack\lib\NormalModule.js:417:16)
    at C:\Users\admin\Downloads\new\examination-management-system\client\esm-client\node_modules\webpack\lib\NormalModule.js:452:10
    at C:\Users\admin\Downloads\new\examination-management-system\client\esm-client\node_modules\webpack\lib\NormalModule.js:323:13
    at C:\Users\admin\Downloads\new\examination-management-system\client\esm-client\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at C:\Users\admin\Downloads\new\examination-management-system\client\esm-client\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (C:\Users\admin\Downloads\new\examination-management-system\client\esm-client\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at C:\Users\admin\Downloads\new\examination-management-system\client\esm-client\node_modules\babel-loader\lib\index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Other relevant information:**
webpack version:  
Node.js version: 18.10.0
Operating System: windows 10 64bit
Additional tools:

**Comment by alexander-akait** [comment]
Duplocate https://github.com/webpack/webpack/issues/14532, please update webpack to v5
