### ISSUE TITLE
CommonsChunkPlugin error: Invalid chunkNames argument

### ISSUE THREAD

**Issue by bertez** [webpack/webpack#1656]
After updating to the latest version of webpack (1.12.8) I'm getting this error:

```
/Users/berto/Projects/www/my_project/node_modules/webpack/lib/optimize/CommonsChunkPlugin.js:65
                throw new Error("Invalid chunkNames argument");
                ^

Error: Invalid chunkNames argument
    at Compilation.<anonymous> (/Users/berto/Projects/www/my_project/node_modules/webpack/lib/optimize/CommonsChunkPlugin.js:65:11)
    at Compilation.applyPlugins (/Users/berto/Projects/www/my_project/node_modules/tapable/lib/Tapable.js:26:37)
    at Compilation.seal (/Users/berto/Projects/www/my_project/node_modules/webpack/lib/Compilation.js:522:7)
    at Compiler.<anonymous> (/Users/berto/Projects/www/my_project/node_modules/webpack/lib/Compiler.js:397:15)
    at /Users/berto/Projects/www/my_project/node_modules/tapable/lib/Tapable.js:103:11
    at Compilation.<anonymous> (/Users/berto/Projects/www/my_project/node_modules/webpack/lib/Compilation.js:445:10)
    at /Users/berto/Projects/www/my_project/node_modules/webpack/lib/Compilation.js:417:12
    at /Users/berto/Projects/www/my_project/node_modules/webpack/lib/Compilation.js:332:10
    at /Users/berto/Projects/www/my_project/node_modules/async/lib/async.js:52:16
    at done (/Users/berto/Projects/www/my_project/node_modules/async/lib/async.js:246:17)
```

I'm instantiating the plugin this way:

```js
const commonsPlugin = new webpack.optimize.CommonsChunkPlugin({
    filename: 'common.[hash].js',
    minChunks: 2
});
```

This code was working with version 1.12.4.

Any help would be appreciated. Thanks!

**Comment by bebraw** [comment]
Looks like it's triggered [here](https://github.com/webpack/webpack/compare/v1.12.4...v1.12.8#diff-1f5e5440c51d8accc603eb6f399cf08bR65). Perhaps that helps you to understand why it's throwing.

**Comment by sokra** [comment]
The `CommonsChunkPlugin` has a non-optional `name` parameter, as noted in the documentation. It was a bug that it worked before.

**Comment by bertez** [comment]
Thanks @sokra, it works perfect with the name parameter. 

```js
const commonsPlugin = new webpack.optimize.CommonsChunkPlugin({
    name: 'common',
    filename: 'common.[hash].js',
    minChunks: 2
});
```

Closing issue.
