### ISSUE TITLE
UglifyJsPlugin reports error with babel core

### ISSUE THREAD

**Issue by jma7889** [webpack/webpack#1669]
webpack 1.12.9, babel core 6.2.1

build fine without UglifyJsPlugin, when add it. It produces error

    `WARNING in bundle.js from UglifyJs
    Side effects in initialization of unused variable invokeReturn [./~/babel-polyfill/~/babel-regenerator-    runtime/runtime.js:167,0]
    ERROR in ./js/app.js
    Module build failed: Error: /myApp/js/app.js: Invalid mapping: {"generated":{"line":null,"column":null,"lastColumn":null},"source":"/myApp/js/app.js","original":{"line":10,"column":0},"name":null}
    at SourceMapGenerator_validateMapping [as _validateMapping] (/myApp/node_modules/babel-core/node_modules/source-map/lib/source-map-generator.js:271:15)
    at SourceMapGenerator_addMapping [as addMapping] (/myApp/node_modules/babel-core/node_modules/source-map/lib/source-map-generator.js:101:14)
    at /myApp/node_modules/babel-core/lib/transformation/file/index.js:440:27
    at Array.forEach (native)
    at SourceMapConsumer_eachMapping [as eachMapping] (/myApp/node_modules/babel-core/node_modules/source-map/lib/source-map-consumer.js:155:16)
    at /myApp/node_modules/babel-core/lib/transformation/file/index.js:439:26
    at File.mergeSourceMap (/myApp/node_modules/babel-core/lib/transformation/file/index.js:461:9)
    at File.generate (/myApp/node_modules/babel-core/lib/transformation/file/index.js:655:25)
    at File.transform (/myApp/node_modules/babel-core/lib/transformation/file/index.js:502:17)
    at /myApp/node_modules/babel-core/lib/transformation/pipeline.js:46:19
    at File.wrap (/myApp/node_modules/babel-core/lib/transformation/file/index.js:512:16)
    at Pipeline.transform (/myApp/node_modules/babel-core/lib/transformation/pipeline.js:43:17)
    at transpile (/myApp/node_modules/babel-loader/index.js:14:22)
    at Object.module.exports (/myApp/node_modules/babel-loader/index.js:87:14)
 @ multi main`

**Comment by sokra** [comment]
Report it to babel.

**Comment by bebraw** [comment]
Yup. Looks like an upstream issue. There's not much webpack can do about it.

**Comment by mainiak** [comment]
@sokra, @bebraw - Can you, please, past link to upstream issue here?

**Comment by bebraw** [comment]
@mainiak If you can still see the issue, can you re-open it with enough detail? There's a nice issue template these days to make sure we get enough info. Given the original one is so old, likely quite a bit has changed in between.

**Comment by mainiak** [comment]
@bebraw honestly I didn't try it again. If it the issue still happens I will re-open with more details. I kinda hoped you would knew upstream issue - if exists - so I could check it and try again. Thank you anyway.

**Comment by bebraw** [comment]
Ok, no worries. The error message is too vague to give a useful query for Babel tracker. I tried a few obvious ones without any luck. But yeah, if it comes up, re-open and we'll see.
