### ISSUE TITLE
Support import.meta.resolve

### ISSUE THREAD

**Issue by latin-1** [webpack/webpack#16693]
## Feature request

**What is the expected behavior?**
```js
const url = import.meta.resolve("...");
```
Note: This differs from the Node.js' experimental version, which is asynchronous.[^1][^2]

I'm not sure whether it should act like `require.resolve` or `new URL`.

**What is motivation or use case for adding/changing the behavior?**
https://html.spec.whatwg.org/#hostgetimportmetaproperties
https://chromestatus.com/feature/5086507990777856

**How should this be implemented in your opinion?**
.

**Are you willing to work on this yourself?**
no

[^1]: https://github.com/nodejs/modules/issues/550#issuecomment-685146852
[^2]: https://github.com/whatwg/html/pull/5572#issuecomment-1041876685

**Comment by TheLarkInn** [comment]
@devongovett @lukastaegert lets try to align on this picking which way to go on this is a freaking mess

**Comment by lukastaegert** [comment]
While Rollup has facilities to let plugins add any implementation that they fancy, a `require.resolve` based
implementation will likely never make it into Rollup core. After all, Rollup does not even support require, and it feels less standard than the browser implementation. So I would definitely lean towards the new URL implementation, with the option for plugins to override this.

**Comment by devongovett** [comment]
As I mentioned in the above parcel issue, I think it is weird that `import.meta.resolve` would _influence_ the resolution rather than only resolving to what is already there.`new URL('...', import.meta.url)` creates a dependency, therefore moving the target module or asset to a separate file/bundle, and it would be weird if `import.meta.resolve` did that IMO. That would mean using `import.meta.resolve` would change the file structure of the output vs not using it. Maybe providing a URL reference to the resolved module within whatever bundle it ends up in via other dependencies would be more expected?

**Comment by latin-1** [comment]
not stale

**Comment by alexander-akait** [comment]
Also we need to implement `import.meta.resolveWeak`, ref https://github.com/webpack/webpack/issues/18633

**Comment by latin-1** [comment]
bump @alexander-akait

**Comment by RReverser** [comment]
> `new URL('...', import.meta.url)` creates a dependency, therefore moving the target module or asset to a separate file/bundle, and it would be weird if `import.meta.resolve` did that IMO.

I don't see why that would be weird or why they should behave differently. In my view, `import.meta.resolve` is a direct replacement for `new URL('...', import.meta.url)`, just with a proper "meta" API instead of pattern-matching a somewhat brittle JS expression that is matched across tooling only by convention.

**Comment by lgarron** [comment]
> > `new URL('...', import.meta.url)` creates a dependency, therefore moving the target module or asset to a separate file/bundle, and it would be weird if `import.meta.resolve` did that IMO.
> 
> I don't see why that would be weird or why they should behave differently. In my view, `import.meta.resolve` is a direct replacement for `new URL('...', import.meta.url)`, just with a proper "meta" API instead of pattern-matching a somewhat brittle JS expression that is matched across tooling only by convention.

I strongly agree with this. `import.meta.resolve(…)` was designed as a standardized way to do what some bundlers have been doing by detecting `new URL(…, import.meta.url)`. It also comes with clear semantics for bare module names (i.e. resolving a package rather than a relative path):
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import.meta/resolve#comparison_with_new_url

Having a standardized way to do this is absolutely crucial for those of us who maintain packages that include web workers or WASM.

**Comment by jnields** [comment]
bump

**Comment by lgarron** [comment]
I'm able to confirm that `v5.109.0` handles `import.meta.resolve(…)` correctly resolves and includes paths in the import graph for local project code:

```js
const workerURL = import.meta.resolve("./relative.js"); // Assuming `./relative.js` exists.
const importSrc = `import "${workerURL}";`;
const blob = new Blob([importSrc], {
  type: "text/javascript",
});
new Worker(URL.createObjectURL(blob), { type: "module" });
```

That is very exciting!

However, I'm unable to confirm whether this works with a library (`cubing.js`), because:

- `npx create-webpack-app` creates a projects that crashes for me.
- Trying to compile the following simple project crashes:

```shell
# bash

mkdir ./test/ && cd ./test/

mkdir -p ./src && cat <<HEREDOC > ./src/index.js
import { randomScrambleForEvent } from "cubing/scramble";
(await randomScrambleForEvent("333")).log();
HEREDOC

cat <<HEREDOC > package.json
{
  "type": "module",
  "devDependencies": {
    "webpack": "5.109.0",
    "webpack-cli": "7.2.1"
  },
  "dependencies": {
    "cubing": "0.63.3"
  }
}
HEREDOC

npm install
npx webpack
```

Output:

```
ERROR in 8b18a8cf57ffbfd052a4.js
8b18a8cf57ffbfd052a4.js from Terser plugin
Unexpected token: name (import) [8b18a8cf57ffbfd052a4.js:7,undefined]
    at js_error (/private/tmp/test/test/node_modules/terser/dist/bundle.min.js:577:11)
    at croak (/private/tmp/test/test/node_modules/terser/dist/bundle.min.js:1377:9)
    at token_error (/private/tmp/test/test/node_modules/terser/dist/bundle.min.js:1385:9)
    at unexpected (/private/tmp/test/test/node_modules/terser/dist/bundle.min.js:1391:9)
    at semicolon (/private/tmp/test/test/node_modules/terser/dist/bundle.min.js:1429:56)
    at simple_statement (/private/tmp/test/test/node_modules/terser/dist/bundle.min.js:1707:73)
    at statement (/private/tmp/test/test/node_modules/terser/dist/bundle.min.js:1515:19)
    at _embed_tokens_wrapper (/private/tmp/test/test/node_modules/terser/dist/bundle.min.js:1442:26)
    at block_ (/private/tmp/test/test/node_modules/terser/dist/bundle.min.js:2295:20)
    at statement (/private/tmp/test/test/node_modules/terser/dist/bundle.min.js:1527:29)

webpack 5.109.0 compiled with 1 error and 1 warning in 1989 ms
```
