### ISSUE TITLE
Cannot access '__WEBPACK_DEFAULT_EXPORT__' before initialization 

### ISSUE THREAD

**Issue by TruecoderSri** [webpack/webpack#16762]
The dev server is not running due to this error and all I'm getting is a white blank page 
The  detailed error is:
Cannot access '__WEBPACK_DEFAULT_EXPORT__' before initialization
at Module.default (userSlice.js:24:1)
    at ./src/firebase.js (firebase.js:12:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./src/screens/Signupscreen.js (Profile.js:40:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./src/screens/Login.js (Homescreen.js:7:1)

webpack version:  4.11.1
Node.js version: 16
Operating System: Windows 11
React-version:18.2.2

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

But I think you have circular dependencies, without extra infromation we can't help, please open a new issue and provide more infromation and we will try to help you, thank you
