### ISSUE TITLE
UglifyJS with source maps problem

### ISSUE THREAD

**Issue by DmitriyD** [webpack/webpack#1689]
I have webpack config with devtool option set to "cheap-module-source-map". When I build with uglify-js (webpack -p), my source map files are almost empty (270 bytes). Without uglify all ok.

**Comment by jonboiser** [comment]
I'm seeing something similar. With uglifyjs+sourcemaps, I cannot access my sources or see the `webpack:///` path in Chrome Dev Tools.

However, I can still access the unminified sources within Firefox Dev Tools.

**Comment by karol-f** [comment]
For me it stopped generating sourcemaps at all +1

**Comment by Keats** [comment]
Any news on that? we are having the same issue

**Comment by shaunwarman** [comment]
Bump... current error during build:

Also, using typescript, but not sure if that is related.

```
ERROR in app.js from UglifyJs
    TypeError: Cannot read property '1' of null
        at Function.uglify.AST_Node.warn_function (/Users/node_modules/webpack/lib/optimize/UglifyJsPlugin.js:65:25)
        at Function.AST_Node.warn (eval at <anonymous> (/Users/node_modules/webpack/node_modules/uglify-js/tools/node.js:24:4), <anonymous>:424:18)
        at Object.OutputStream.add_mapping (eval at <anonymous> (/Users/node_modules/webpack/node_modules/uglify-js/tools/node.js:24:4), <anonymous>:4015:22)
        at options.defaults.sequences (eval at <anonymous> (/Users/node_modules/webpack/node_modules/uglify-js/tools/node.js:24:4), <anonymous>:5066:16)
        at AST_Node.eval [as add_source_map] (eval at <anonymous> (/Users/node_modules/webpack/node_modules/uglify-js/tools/node.js:24:4), <anonymous>:5027:13)
        at doit (eval at <anonymous> (/Users/node_modules/webpack/node_modules/uglify-js/tools/node.js:24:4), <anonymous>:4092:18)
        at AST_Node.eval [as print] (eval at <anonymous> (/Users/node_modules/webpack/node_modules/uglify-js/tools/node.js:24:4), <anonymous>:4099:13)
        at eval (eval at <anonymous> (/Users/node_modules/webpack/node_modules/uglify-js/tools/node.js:24:4), <anonymous>:4819:22)
        at Array.forEach (native)
        at eval (eval at <anonymous> (/Users/node_modules/webpack/node_modules/uglify-js/tools/node.js:24:4), <anonymous>:4813:29)
```

**Comment by wenbochang** [comment]
Anyone have a working config for this yet?

We're able to get Uglify and source maps to work only with `eval` inside `devtool` option (say `cheap-module-eval-source-map`. However that blows up the filesize, so it be great to be able to use `cheap-module-source-map` in prod

**Comment by RobertoUa** [comment]
any updates on this?

**Comment by sompylasar** [comment]
RE: https://github.com/webpack/webpack/issues/1689#issuecomment-214428823

The `TypeError: Cannot read property '1' of null` in `Function.uglify.AST_Node.warn_function` is caused by an UglifyJs warning without a line and character number.

The UglifyJs warning that triggered that bug for me was: "Output exceeds 200 characters".

The code below does not check the return value of a `RegExp` `exec` which may be `null`:
https://github.com/webpack/webpack/blob/416e5beeb4bad32460fb40d64e527ff21cdef446/lib/optimize/UglifyJsPlugin.js#L64
```js
uglify.AST_Node.warn_function = (warning) => { // eslint-disable-line camelcase
  const match = /\[.+:([0-9]+),([0-9]+)\]/.exec(warning);
  const line = +match[1];
  const column = +match[2];
```

The bug originally appeared here: https://github.com/webpack/webpack/commit/672fc9ba0f1ec5ece16eacac06251df5f4b3b36d#diff-648358660be8f8d8c72d0d8d667d3430R47

**Comment by onigoetz** [comment]
Hi,

I had similar issues and the solution is in the documentation : https://webpack.js.org/plugins/uglifyjs-webpack-plugin/#sourcemap

`cheap-*` source maps options don't work with uglify.
You should use an option from the [devtool list of options](https://webpack.js.org/configuration/devtool/) that is adapted for production.

I personally recommend to use `source-map` as it is the most precise and creates separate files. thus it doesn't blow up your bundle sizes and isn't loaded in production unless an inspector is opened.
