### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'call')

### ISSUE THREAD

**Issue by bmarti44** [webpack/webpack#17059]
# Bug report

When building an application for production in complex dependency chains some dependencies that are required by the application can be accidentally tree shaken causing the application to not load. 

**What is the current behavior?**

Webpack will tree shake a file/dependency accidentally causing the application to not load with the error ->

``` 
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'call')
    at u (bootstrap:19:32)
    at 75282 (reservationRuleUtil.js:39:5)
    at u (bootstrap:19:32)
    at 87962 (profileParseUtil.js:64:5)
    at u (bootstrap:19:32)
    at 8407 (availabilityFilterChips.js:3:109)
    at u (bootstrap:19:32)
    at 93439 (914.ede21470d6d91f13d1b5.js:1:220)
    at Function.u (bootstrap:19:32)
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Clone the repro git repository (I have made the repo private as this project contains some code that I do not want to publicly share. This is a high priority issue for us at my company though, so we are willing to share the code with individuals that are looking to debug the problem).

I have created three branches with a different version of webpack installed in each and committed the node_modules folder (sorry about the size of the clone)... This was necessary due to some of the libraries required to debug being only on a private npm registry.

The first branch has the last working version of webpack that this project works on ->

https://github.com/bmarti44/webpack-tree-shaking-issue/tree/version/5.24.0 

Then the version of webpack where things started braking ->

https://github.com/bmarti44/webpack-tree-shaking-issue/tree/version/5.24.1

Finally the latest version (things are still broken with the very latest) ->

https://github.com/bmarti44/webpack-tree-shaking-issue/tree/version/5.80.0

**What is the expected behavior?**

The application should build in production mode with all default optimizations without issue.

**Other relevant information:**
webpack versions: 524.1-5.80.0  
Node.js version: 16.15.1
Operating System: macOS Monterey
Additional tools:

It looks like there has been another report of this issue here  -> https://github.com/webpack/webpack/discussions/15369 

Diff of changes that I've been looking over (I've been trying to nail it down to the exact commit) -> https://github.com/webpack/webpack/compare/v5.24.0...v5.24.1

**Comment by bmarti44** [comment]
A few more notes - the `npm start` command caches like crazy. Make sure you clear caches in between each build (or have your devtools opened with caching turned off) otherwise you won't see changes.

Also, the error appears in this bit of code ->

```
// The require function
function __webpack_require__(moduleId) {
	// Check if module is in cache
	var cachedModule = __webpack_module_cache__[moduleId];
	if (cachedModule !== undefined) {
		return cachedModule.exports;
	}
	// Create a new module (and put it into the cache)
	var module = __webpack_module_cache__[moduleId] = {
		id: moduleId,
		// no module.loaded needed
		exports: {}
	};

	// Execute the module function
	__webpack_modules__[moduleId].call(module.exports, module, module.exports, __webpack_require__); // THIS LINE

	// Return the exports of the module
	return module.exports;
}
```

So, `__webpack_modules__[moduleId]` is undefined (which should probably not be the case).

**Comment by alexander-akait** [comment]
This code is webpack `import` code, how many entrypoints do you have and how many  chunks your generate (check you import all of them on page)

**Comment by bmarti44** [comment]
One entry point `./src/index.ts` but the number of chunks generated from webpack 5.24.0 to 5.24.1 changed quite a bit (looking at my local web folder and network traffic).

In webpack 5.24.0 ->
main.sha.js
611.sha.js
578.sha.js
914.sha.js
549.sha.js
787.sha.js

In webpack 5.24.1 ->
main.sha.js
578.sha.js
539.sha.js
914.sha.js

My entrypoint `index.ts` ->

```
if (process.env.NODE_ENV === 'development') {
  require('preact/debug');
}

import 'raw-loader!./index.html';
import './components/app';
```

`./components/app` ->

```
/* eslint-disable @typescript-eslint/no-explicit-any */
import { FunctionalComponent, render } from 'preact';
import { Suspense, lazy } from 'preact/compat';
import { HashRouter, Navigate, Route, Routes } from 'react-router-dom';
import { whenDocumentReady } from 'ojs/ojbootstrap';

// Custom pages
const Availability = lazy(() => import('./pages/Availability/availability'));
const ReservationOverview = lazy(() => import('./pages/ReservationOverview/reservationOverview'));

/**
 *  Example app component for RAPID applications.
 *
 *  @returns JSX for the root of the applications.
 */
export const App: FunctionalComponent = () => {
  return (
    <div id="appContainer" class="oj-web-applayout-page">
      <Suspense fallback={<div />}>
        <Routes>
          <Route path="/" element={<Navigate to={'/advance-search'} />} />
          <Route path="/advance-search" element={<Availability />} />
          <Route path="/reservation-overview" element={<ReservationOverview />} />
        </Routes>
      </Suspense>
    </div>
  );
};

whenDocumentReady().then(() => {
  render(
    <HashRouter>
      <App />
    </HashRouter>,
    document.querySelector('#gbu-app-root') as Element
  );
});
```

and finally one of my pages ->

```
/* eslint-disable @typescript-eslint/no-unused-vars */
import type { h } from 'preact';
import { usePage, usePageHeader } from '@gbu/rapid-providers';
import { AvailabilityAdvancedSearch } from '@hgbu/rsv-components';
import { Logger } from '@hgbu/rsv-providers';
import { useNavigate } from 'react-router-dom';
import type { SalesRoomRateCriteria } from '@hgbu/rsv-models';

/**
 *  Availability Advanced Search Page for customer contact center.
 *
 *  @returns JSX for the Availability advanced search page.
 */
export const AdvanceSearch = (): h.JSX.Element => {
  usePageHeader({
    pageTitle: 'New Reservation',
    displayOptions: {
      goToParent: false,
    },
    showHeader: false,
  });

  usePage({
    parentId: 'advance-search',
    layout: 'edgeToEdge',
  });

  const navigate = useNavigate();

  function onClickSelectRoomRateForBooking(route?: string, salesRoomRateCriteria?: SalesRoomRateCriteria): void {
    Logger.info(`Clicked on the select room rate for booking so navigation to ::  ${route}`);
    if (route) navigate(route, { state: { criteria: salesRoomRateCriteria as SalesRoomRateCriteria } });
  }

  return <AvailabilityAdvancedSearch dummy="" onSelectRoomRateForBooking={onClickSelectRoomRateForBooking} />;
};

export default AdvanceSearch;
```

**Comment by bmarti44** [comment]
No issues in dev mode/with optimizations turned off. As mentioned https://github.com/webpack/webpack/discussions/15369 is probably the same issue I'm facing. Also [this](https://stackoverflow.com/questions/58073626/uncaught-typeerror-cannot-read-property-call-of-undefined-at-webpack-requir) SO issue seems very similar as well.

**Comment by alexander-akait** [comment]
You can try to enable `runtime` chunk or disable optimization to undestand where is a bug, I will look at this late

**Comment by bmarti44** [comment]
Okay will give the `runtime` chunk a try and also try disabling the optimizations one at a time

**Comment by bmarti44** [comment]
Tried runtime chunk on webpack 5.24.1 and am getting the same error. New chunk order is ->

runtime.sha.js
main.sha.js
539.sha.js
578.sha.js
914.sha.js

I will continue disabling optimizations and let you know the results.

**Comment by bmarti44** [comment]
Went through each of the optimizations and set them to false one at a time, here are the results... This was on webpack 5.24.1

concatenateModules: false - resolves the issue
sideEffects: false - error persists
usedExports: false - error persists
flagIncludedChunks: false - error persists
removeEmptyChunks: false - error persists
innerGraph: false - error persists
mangleExports: false - error persists
mergeDuplicateChunks: false - error persists
minimize: false - error persists

**Comment by alexander-akait** [comment]
hm, maybe we have regression somewhere here https://github.com/webpack/webpack/commit/f96194e0f64ead3eb2cd36e93d95039a897174f1

**Comment by bmarti44** [comment]
perhaps... i just reverted `ModuleConcatenationPlugin.js` (only that one file) and reran the build - the error was resolved. 

i can go through and start reverting it line by line to see if  i can trace it down/nail it to something concrete?

**Comment by alexander-akait** [comment]
@bmarti44 yeah, feel free to do it, it will help

**Comment by bmarti44** [comment]
I'm still narrowing it down further but if I take the `_tryToAdd` method from 5.24.0 and port it to 5.24.1 then the issue is resolved. Will continue to nail it down in that method (there are quite a few changes).

**Comment by bmarti44** [comment]
Traced it down further to the changes done to incomingConnections here -> https://github.com/webpack/webpack/commit/5c42b918b438916add040531266f8d88c604427d#diff-2c41050379dc600b1a2db89ef0f270b32e7fdd8139702f36ba96f03d53e3cfd0L611

current diff of the changes i made ->

```diff
diff --git a/node_modules/webpack/lib/optimize/ModuleConcatenationPlugin.js b/node_modules/webpack/lib/optimize/ModuleConcatenationPlugin.js
index e602119f..7aeb7ee0 100644
--- a/node_modules/webpack/lib/optimize/ModuleConcatenationPlugin.js
+++ b/node_modules/webpack/lib/optimize/ModuleConcatenationPlugin.js
@@ -571,65 +571,31 @@ class ModuleConcatenationPlugin {

 		const moduleGraph = compilation.moduleGraph;

-		const incomingConnections = moduleGraph.getIncomingConnectionsByOriginModule(
-			module
-		);
-
-		const incomingConnectionsFromNonModules =
-			incomingConnections.get(null) || incomingConnections.get(undefined);
-		if (incomingConnectionsFromNonModules) {
-			const activeNonModulesConnections = incomingConnectionsFromNonModules.filter(
-				connection => {
-					// We are not interested in inactive connections
-					// or connections without dependency
-					return connection.isActive(runtime) || connection.dependency;
-				}
-			);
-			if (activeNonModulesConnections.length > 0) {
-				const problem = requestShortener => {
-					const importingExplanations = new Set(
-						activeNonModulesConnections.map(c => c.explanation).filter(Boolean)
-					);
-					const explanations = Array.from(importingExplanations).sort();
-					return `Module ${module.readableIdentifier(
-						requestShortener
-					)} is referenced ${
-						explanations.length > 0
-							? `by: ${explanations.join(", ")}`
-							: "in an unsupported way"
-					}`;
-				};
-				statistics.incorrectDependency++;
-				failureCache.set(module, problem); // cache failures for performance
-				return problem;
+		const incomingConnections = Array.from(
+			moduleGraph.getIncomingConnections(module)
+		).filter(connection => {
+			// We are not interested in inactive connections
+			if (!connection.isActive(runtime)) return false;
+
+			// Include, but do not analyse further, connections from non-modules
+			if (!connection.originModule) return true;
+
+			// Ignore connection from orphan modules
+			if (chunkGraph.getNumberOfModuleChunks(connection.originModule) === 0)
+				return false;
+
+			// We don't care for connections from other runtimes
+			let originRuntime = undefined;
+			for (const r of chunkGraph.getModuleRuntimes(connection.originModule)) {
+				originRuntime = mergeRuntimeOwned(originRuntime, r);
 			}
-		}

-		/** @type {Map<Module, readonly ModuleGraph.ModuleGraphConnection[]>} */
-		const incomingConnectionsFromModules = new Map();
-		for (const [originModule, connections] of incomingConnections) {
-			if (originModule) {
-				// Ignore connection from orphan modules
-				if (chunkGraph.getNumberOfModuleChunks(originModule) === 0) continue;
-
-				// We don't care for connections from other runtimes
-				let originRuntime = undefined;
-				for (const r of chunkGraph.getModuleRuntimes(originModule)) {
-					originRuntime = mergeRuntimeOwned(originRuntime, r);
-				}
-
-				if (!intersectRuntime(runtime, originRuntime)) continue;
-
-				// We are not interested in inactive connections
-				const activeConnections = connections.filter(connection =>
-					connection.isActive(runtime)
-				);
-				if (activeConnections.length > 0)
-					incomingConnectionsFromModules.set(originModule, activeConnections);
-			}
-		}
+			return intersectRuntime(runtime, originRuntime);
+		});

-		const incomingModules = Array.from(incomingConnectionsFromModules.keys());
+		const incomingModules = Array.from(
+				new Set(incomingConnections.map(c => c.originModule))
+			).sort(compareModulesByIdentifier);

 		// Module must be in the same chunks like the referencing module
 		const otherChunkModules = incomingModules.filter(originModule => {
@@ -659,40 +625,67 @@ class ModuleConcatenationPlugin {
 		}

 		/** @type {Map<Module, readonly ModuleGraph.ModuleGraphConnection[]>} */
-		const nonHarmonyConnections = new Map();
-		for (const [originModule, connections] of incomingConnectionsFromModules) {
-			const selected = connections.filter(
-				connection =>
-					!connection.dependency ||
-					!(connection.dependency instanceof HarmonyImportDependency)
-			);
-			if (selected.length > 0)
-				nonHarmonyConnections.set(originModule, connections);
-		}
-		if (nonHarmonyConnections.size > 0) {
+		const nonHarmonyConnections = incomingConnections.filter(
+			connection =>
+				!connection.originModule ||
+				!connection.dependency ||
+				!(connection.dependency instanceof HarmonyImportDependency)
+		);
+		if (nonHarmonyConnections.length > 0) {
 			const problem = requestShortener => {
-				const names = Array.from(nonHarmonyConnections)
-					.map(([originModule, connections]) => {
-						return `${originModule.readableIdentifier(
-							requestShortener
-						)} (referenced with ${Array.from(
+				const importingModules = new Set(
+					nonHarmonyConnections.map(c => c.originModule).filter(Boolean)
+				);
+				const importingExplanations = new Set(
+					nonHarmonyConnections.map(c => c.explanation).filter(Boolean)
+				);
+				const importingModuleTypes = new Map(
+					Array.from(importingModules).map(
+						m =>
+							/** @type {[Module, Set<string>]} */ ([
+							m,
 							new Set(
-								connections
-									.map(c => c.dependency && c.dependency.type)
-									.filter(Boolean)
+								nonHarmonyConnections
+									.filter(c => c.originModule === m)
+									.map(c => c.dependency.type)
+									.sort()
 							)
-						)
-							.sort()
-							.join(", ")})`;
-					})
+						])
+					)
+				);
+				const names = Array.from(importingModules)
+					.map(
+						m =>
+							`${m.readableIdentifier(
+								requestShortener
+							)} (referenced with ${Array.from(
+								importingModuleTypes.get(m)
+							).join(", ")})`
+					)
 					.sort();
-				return `Module ${module.readableIdentifier(
-					requestShortener
-				)} is referenced from these modules with unsupported syntax: ${names.join(
-					", "
-				)}`;
+				const explanations = Array.from(importingExplanations).sort();
+				if (names.length > 0 && explanations.length === 0) {
+					return `Module ${module.readableIdentifier(
+						requestShortener
+					)} is referenced from these modules with unsupported syntax: ${names.join(
+						", "
+					)}`;
+				} else if (names.length === 0 && explanations.length > 0) {
+					return `Module ${module.readableIdentifier(
+						requestShortener
+					)} is referenced by: ${explanations.join(", ")}`;
+				} else if (names.length > 0 && explanations.length > 0) {
+					return `Module ${module.readableIdentifier(
+						requestShortener
+					)} is referenced from these modules with unsupported syntax: ${names.join(
+						", "
+					)} and by: ${explanations.join(", ")}`;
+				} else {
+					return `Module ${module.readableIdentifier(
+						requestShortener
+					)} is referenced in a unsupported way`;
+				}
 			};
-			statistics.incorrectModuleDependency++;
 			failureCache.set(module, problem); // cache failures for performance
 			return problem;
 		}
```

**Comment by alexander-akait** [comment]
Yeah, PR welcome

**Comment by alexander-akait** [comment]
@bmarti44 Hello, any news? Maybe you can find a code which leads to the problem?

**Comment by bmarti44** [comment]
hey @alexander-akait! PR -> https://github.com/webpack/webpack/pull/17103

I am triple checking the changes on my local but the diff there appears to resolve my issue (it is at least easier to read).

**Comment by bmarti44** [comment]
Ugh, I need to fix the email address in my key... Lemme fix up a few things and continue to test and will finalize for Monday.

**Comment by bmarti44** [comment]
closing per https://github.com/webpack/webpack/pull/17103 duplicate ModuleConcatenationPlugins defined...

**Comment by ogenodisho** [comment]
Just a note that I'm having the exact same error as this, I do not have any ModuleConcatenationPlugins defined, yet `
concatenateModules: false` resolves my issue.
