### ISSUE TITLE
Errors in preLoaders are not caught, breaking build process

### ISSUE THREAD

**Issue by brianchirls** [webpack/webpack#1719]
I have both `jshint-loader` and `jscs-loader` configured as preLoaders to check my code. If there's a problem, webpack reports the error in lovely red text and exits gracefully. As of yesterday, however, the error is uncaught, which breaks my "watch" process.

Here's what I get if I introduce a missing semicolon error:

```
/Users/brianchirls/www/VR/webpack-vr-template/node_modules/webpack-core/lib/NormalModuleMixin.js:151
                throw e;
                ^
Error: ModuleError: jshint results in errors
  Missing semicolon. @ line 158 char 31
        }, { normalizeRGB: true }),ModuleBuildError: Module build failed: Error: Module failed in cause of jshint error.
    at Object.jsHint (/Users/brianchirls/www/VR/webpack-vr-template/node_modules/jshint-loader/index.js:127:9)
    at Object.<anonymous> (/Users/brianchirls/www/VR/webpack-vr-template/node_modules/jshint-loader/index.js:146:11)
    at Object.<anonymous> (/Users/brianchirls/www/VR/webpack-vr-template/node_modules/jshint-loader/index.js:37:12)
    at respond (/Users/brianchirls/www/VR/webpack-vr-template/node_modules/rcloader/index.js:68:7)
    at respond (/Users/brianchirls/www/VR/webpack-vr-template/node_modules/rcfinder/index.js:140:7)
    at next (/Users/brianchirls/www/VR/webpack-vr-template/node_modules/rcfinder/index.js:167:16)
    at doNTCallback0 (node.js:430:9)
    at process._tickCallback (node.js:359:13)
```

I'm pretty sure the problem is not with jscs, jshint or either of their loaders, since I get a similar error if I put the semicolon back and change to mixed tabs/spaces, which bugs jscs but not jshint. And the problem isn't with my own code or configuration, since I still see the same error if I roll my own code back to several days ago. I notice there hasn't been an update to webpack, webpack-core or gulp (which I'm using) in the last couple days, so maybe there's another dependency buried in there somewhere that changed?

**Comment by bebraw** [comment]
Is this relevant still?
