### ISSUE TITLE
TypeError: module.identifier is not a function

### ISSUE THREAD

**Issue by nianxiongdi** [webpack/webpack#17477]
# Bug report

```js
getKey: module => module.identifier(),
                                                 ^

TypeError: module.identifier is not a function
    at AsyncQueue.getKey [as _getKey] (E:\learn\fore-end\webpack\plugin\node_modules\?[4mwebpack?[24m\lib\Compilation.js:951:29)
    at E:\learn\fore-end\webpack\plugin\node_modules\?[4mwebpack?[24m\lib\util\AsyncQueue.js:118:21
    at Hook.eval [as callAsync] (eval at create (E:\learn\fore-end\webpack\plugin\node_modules\?[4mtapable?[24m\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (E:\learn\fore-end\webpack\plugin\node_modules\?[4mtapable?[24m\lib\Hook.js:18:14)
    at AsyncQueue.add (E:\learn\fore-end\webpack\plugin\node_modules\?[4mwebpack?[24m\lib\util\AsyncQueue.js:111:24)
    at Compilation.addModule (E:\learn\fore-end\webpack\plugin\node_modules\?[4mwebpack?[24m\lib\Compilation.js:1266:23)
    at E:\learn\fore-end\webpack\plugin\node_modules\?[4mwebpack?[24m\lib\Compilation.js:1816:10
    at E:\learn\fore-end\webpack\plugin\node_modules\?[4mwebpack?[24m\lib\util\AsyncQueue.js:354:5
    at Hook.eval [as callAsync] (eval at create (E:\learn\fore-end\webpack\plugin\node_modules\?[4mtapable?[24m\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (E:\learn\fore-end\webpack\plugin\node_modules\?[4mtapable?[24m\lib\Hook.js:18:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! loader@1.0.0 dev: `webpack --mode development`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the loader@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2023-07-08T03_25_29_770Z-debug.log
```

 

**Other relevant information:**
webpack version:  5.88.1
Node.js version: 12.13.1
Operating System: win7
Additional tools: no

**Comment by TheLarkInn** [comment]
Can you please provide a reproducible repo that we can clone and test?
