### ISSUE TITLE
[webpack-cli] HookWebpackError: RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by mai1x9** [webpack/webpack#17525]
### Discussed in https://github.com/webpack/webpack/discussions/17524

<div type='discussions-op-text'>

<sup>Originally posted by **mai1x9** July 24, 2023</sup>
Hello there, i am getting the erorr: **[webpack-cli] HookWebpackError: RangeError: Maximum call stack size exceeded** when the modules outside the root directory are imported.

The project structure is,
```
project
    | api
          app.js
          
          .... otherfiles

    | db
      ... js files for db interaction
    | core
       .. some js iles
    webpack.config.js
    package.json
```
app.js uses the js files from  `db` and `core`. When webpack is run from `project` foolder which is the parent dir, it throws below error. However if `app.js` and `webpack.config.js` are present in root dir `project` instead of `api` folder, then everything works. 

------
### Error details
```
ns_vm05@lnsvm05:~/Desktop/SuperAdmin_beta_v0.1.8/master$ export WEBPACK=test && npm run build

> single@1.0.0 build
> webpack --config ./webpack.config.js

[webpack-cli] HookWebpackError: RangeError: Maximum call stack size exceeded
    at makeWebpackError (/home/lns_vm05/Desktop/SuperAdmin_beta_v0.1.8/node_modules/webpack/lib/HookWebpackError.js:48:9)
    at /home/lns_vm05/Desktop/SuperAdmin_beta_v0.1.8/node_modules/webpack/lib/Compilation.js:3068:12
    at eval (eval at create (/home/lns_vm05/Desktop/SuperAdmin_beta_v0.1.8/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
    at fn (/home/lns_vm05/Desktop/SuperAdmin_beta_v0.1.8/node_modules/webpack/lib/Compilation.js:481:17)
    at _next1 (eval at create (/home/lns_vm05/Desktop/SuperAdmin_beta_v0.1.8/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
    at eval (eval at create (/home/lns_vm05/Desktop/SuperAdmin_beta_v0.1.8/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:25:1)
    at Hook.eval [as callAsync] (eval at create (/home/lns_vm05/Desktop/SuperAdmin_beta_v0.1.8/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at /home/lns_vm05/Desktop/SuperAdmin_beta_v0.1.8/node_modules/webpack/lib/Compilation.js:516:46
    at /home/lns_vm05/Desktop/SuperAdmin_beta_v0.1.8/node_modules/copy-webpack-plugin/dist/index.js:613:9
    at runMicrotasks (<anonymous>)
-- inner error --
Error: RangeError: Maximum call stack size exceeded
    at o.analyze (/home/lns_vm05/Desktop/SuperAdmin_beta_v0.1.8/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/analyzers/scope-analyzer/ScopeAnalyzer.ts:71:23)
    at o.traverseScopeIdentifiers (/home/lns_vm05/Desktop/SuperAdmin_beta_v0.1.8/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/node/ScopeIdentifiersTraverser.ts:26:28)
    at h.transformNode (/home/lns_vm05/Desktop/SuperAdmin_beta_v0.1.8/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/node-transformers/preparing-transformers/VariablePreserveTransformer.ts:54:40)
    at visitorFunction (/home/lns_vm05/Desktop/SuperAdmin_beta_v0.1.8/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/node-transformers/preparing-transformers/VariablePreserveTransformer.ts:45:41)
    at Controller.<anonymous> (/home/lns_vm05/Desktop/SuperAdmin_beta_v0.1.8/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/node-transformers/NodeTransformersRunner.ts:108:39)
    at Controller.__execute (/home/lns_vm05/Desktop/SuperAdmin_beta_v0.1.8/node_modules/@javascript-obfuscator/estraverse/estraverse.js:336:31)
    at Controller.replace (/home/lns_vm05/Desktop/SuperAdmin_beta_v0.1.8/node_modules/@javascript-obfuscator/estraverse/estraverse.js:594:27)
    at Object.replace (/home/lns_vm05/Desktop/SuperAdmin_beta_v0.1.8/node_modules/@javascript-obfuscator/estraverse/estraverse.js:675:27)
    at _.transform (/home/lns_vm05/Desktop/SuperAdmin_beta_v0.1.8/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/node-transformers/NodeTransformersRunner.ts:74:24)
    at o.runNodeTransformationStage (/home/lns_vm05/Desktop/SuperAdmin_beta_v0.1.8/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/JavaScriptObfuscator.ts:138:44)
caused by plugins in Compilation.hooks.processAssets
Error: RangeError: Maximum call stack size exceeded
    at o.analyze (/home/lns_vm05/Desktop/SuperAdmin_beta_v0.1.8/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/analyzers/scope-analyzer/ScopeAnalyzer.ts:71:23)
    at o.traverseScopeIdentifiers (/home/lns_vm05/Desktop/SuperAdmin_beta_v0.1.8/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/node/ScopeIdentifiersTraverser.ts:26:28)
    at h.transformNode (/home/lns_vm05/Desktop/SuperAdmin_beta_v0.1.8/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/node-transformers/preparing-transformers/VariablePreserveTransformer.ts:54:40)
    at visitorFunction (/home/lns_vm05/Desktop/SuperAdmin_beta_v0.1.8/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/node-transformers/preparing-transformers/VariablePreserveTransformer.ts:45:41)
    at Controller.<anonymous> (/home/lns_vm05/Desktop/SuperAdmin_beta_v0.1.8/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/node-transformers/NodeTransformersRunner.ts:108:39)
    at Controller.__execute (/home/lns_vm05/Desktop/SuperAdmin_beta_v0.1.8/node_modules/@javascript-obfuscator/estraverse/estraverse.js:336:31)
    at Controller.replace (/home/lns_vm05/Desktop/SuperAdmin_beta_v0.1.8/node_modules/@javascript-obfuscator/estraverse/estraverse.js:594:27)
    at Object.replace (/home/lns_vm05/Desktop/SuperAdmin_beta_v0.1.8/node_modules/@javascript-obfuscator/estraverse/estraverse.js:675:27)
    at _.transform (/home/lns_vm05/Desktop/SuperAdmin_beta_v0.1.8/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/node-transformers/NodeTransformersRunner.ts:74:24)
    at o.runNodeTransformationStage (/home/lns_vm05/Desktop/SuperAdmin_beta_v0.1.8/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/JavaScriptObfuscator.ts:138:44)
```
----
### webpack config file
```
const path = require('path')
const nodeExternals = require('webpack-node-externals')
const CopyPlugin = require("copy-webpack-plugin");
const JavaScriptObfuscator = require("webpack-obfuscator");

  
  module.exports = {
      name: 'authserver',
      entry: './api/app.js', // Ensure to begin with ./ else it throws module not found
      output: {
          filename: 'app.js',
          path: path.resolve(__dirname, './dist')
      },
      target: 'node',
      externals: [nodeExternals()],
      module: {
        rules: [
          {
            test: /\.js?$/,
            include: [
             
              path.join(__dirname),
              path.join(__dirname, "./core"),
              path.join(__dirname, "./db"),
            ],
          }
        ]
      },
      plugins: [

        new CopyPlugin({
          patterns: ["package.json"],
        }),
        new JavaScriptObfuscator(
          {
            // obfuscate code first
            unicodeEscapeSequence: true,
            rotateUnicodeArray: true,
          },
          ["excluded_bundle_name.js"]
        ),
      ]
  }

}
```

----

**Webpack version:** `5.88.2`
node: 16.16.0
OS: ubuntu 18.04

package.json file details for webpack,
```
    "webpack": "^5.88.2",
    "webpack-cli": "^5.1.4",
    "webpack-encrypt-nodejs-module": "^1.0.3",
    "webpack-node-externals": "^3.0.0",
    "webpack-obfuscator": "^3.5.1"
```

**Comment by snitin315** [comment]
We appreciate your effort in raising this issue. To ensure clarity in understanding your situation, we kindly request you recreate the issue using one of our provided templates. 

Your collaboration will assist us in providing you with effective assistance.
