### ISSUE TITLE
Bundles generated with `output.library.type = 'module'` don't bind exported symbols correctly

### ISSUE THREAD

**Issue by izaera** [webpack/webpack#17694]
# Bug report

**What is the current behavior?**

When using `output.library.type = 'module'` the bundles webpack is generating contain code like this:

```javascript
var __webpack_exports__event = __webpack_exports__.event;
var __webpack_exports__setEvent = __webpack_exports__.setEvent;
export { __webpack_exports__event as event, __webpack_exports__setEvent as setEvent };
```

The declarations of `var`s which are then exported with the proper name is unbinding the exported symbols from the webpack exports table, which contains synthetic objects that mimic the underlying symbol by means of getters and setters.

In other words if `event` is declared like this in the webpacked source code:

```javascript
export var event = null;
```

Internally, `__webpack_exports__.event` is evaluating the actual value of the `event` variable every time it is accessed, whereas the exported symbol `__webpack_exports__event` only evaluates it once at the time the module is defined, but it never gets updated for the rest of run time.

**If the current behavior is a bug, please provide the steps to reproduce.**

I'm attaching a ZIP file with a sample project that contains two simple modules:

**the_event.mjs**
```javascript
export var event = null;

export function setEvent(x) {
	event = x;
}
```

and

**test.mjs**
```javascript
console.log('==================================================================================');
import {event, setEvent} from './the_event.mjs';

console.log('>>>', event);

try {
	event = 7;
}
catch(err) {
	console.log('>>>', err);
}

setEvent(42);

console.log('>>>', event);

console.log('==================================================================================');
import {event as event2, setEvent as setEvent2} from './dist/the_event.mjs';

console.log('>>>', event2);

try {
	event2 = 7;
}
catch(err) {
	console.log('>>>', err);
}

setEvent2(42);

console.log('>>>', event2);
```

In the `test.mjs` module the same code retrieving the value of `event`, setting it and retrieving it again, is executed twice. The first time it uses the `the_event.mjs` module directly, the second it uses a webpacked version of that module that has been built with `output.library.type = 'module'`. Both should show the same output, but that doesn't happen:

```bash
$ npm run test

> webpack-exports-issue@1.0.0 test
> webpack && node test.mjs

asset the_event.mjs 1.99 KiB [compared for emit] [javascript module] (name: the_event) 1 related asset
runtime modules 670 bytes 3 modules
./the_event.mjs 70 bytes [built] [code generated]
webpack 5.88.2 compiled successfully in 87 ms
==================================================================================
>>> null
>>> TypeError: Assignment to constant variable.
    at file:///home/ivan/Temporal/webpack-exports-issue/test.mjs:7:8
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async loadESM (node:internal/process/esm_loader:91:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)
>>> 42
==================================================================================
>>> null
>>> TypeError: Assignment to constant variable.
    at file:///home/ivan/Temporal/webpack-exports-issue/test.mjs:23:9
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async loadESM (node:internal/process/esm_loader:91:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)
>>> null
```

The same behaviour is shown if the code is executed in a browser (in my tests I used Firefox).

**What is the expected behavior?**

Both the native import and the webpacked import should work the same. In particular, when `event` is imported through the webpacked version of the `the_event.mjs` module, the binding should be maintained and `42` should be returned, instead of `null`, which was the initial value of the underlying `event` variable.

**Other relevant information:**
webpack version:  5.88.2
Node.js version: 16.19.1
Operating System: Arch Linux (`6.4.13-200.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC`)
Additional tools: none

**Comment by izaera** [comment]
This is the sample project :point_right: [webpack-exports-issue.tar.gz](https://github.com/webpack/webpack/files/12673838/webpack-exports-issue.tar.gz)

**Comment by izaera** [comment]
I'm going to investigate how this could be fixed, but any hint from the maintainers would be very much appreciated.

I thought one way to fix it could probably be using `Proxy` or pseudo proxies (like webpack does internally, using getters) instead of `var`s. Like this:

```javascript
var __webpack_exports__event = new Proxy(__webpack_exports__.event);
var __webpack_exports__setEvent = new Proxy(__webpack_exports__.setEvent);
export { __webpack_exports__event as event, __webpack_exports__setEvent as setEvent };
```

But I would like to hear opinions on this approach, since it could have side effects that I don't foresee.

**Comment by izaera** [comment]
I've been doing some experiments in [ModuleLibraryPlugin](https://github.com/webpack/webpack/blob/1f13ff9fe587e094df59d660b4611b1bd19aed4c/lib/library/ModuleLibraryPlugin.js) trying to fix this issue and have realized that it is impossible :-/ (unless someone else comes with better ideas than mine, of course).

What I've tried is using `Proxy` in the hope to defer the evaluation of exports until the very point where they are used. In other words, webpack defines dynamic getters for all its internal exports, like this:

```javascript
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   event: () => (/* binding */ event),
/* harmony export */   setEvent: () => (/* binding */ setEvent)
/* harmony export */ });
```
(where `__webpack_require__.d` is akin to doing `Object.defineProperty(name, getter)`)

So whenever the code accesses `event` in a module that imports it, the getter is being executed. This makes possible exporting module internal variable as bindings that are "updated" every time the internal variable changes its value (like `var event` in the example).

However, the ESM export code breaks this binding, as said above:

```javascript
var __webpack_exports__event = __webpack_exports__.event;
var __webpack_exports__setEvent = __webpack_exports__.setEvent;
export { __webpack_exports__event as event, __webpack_exports__setEvent as setEvent };
```

The first line is invoking the getter to assign the resulted value to `__webpack_exports__event` but once it is assigned, the binding is broken and the exports is no longer bound to the exported `var event`. Thus it will remain `null` forever.

What I tried first is exporting proxies, like this:

```javascript
var __webpack_exports__event = new Proxy(__webpack_exports__.event, {});
var __webpack_exports__setEvent = new Proxy(__webpack_exports__.setEvent, {});
export { __webpack_exports__event as event, __webpack_exports__setEvent as setEvent };
```

However, that fails, because line 1 invokes the getter to create the `Proxy` and, since it returns `null` on first place, the `Proxy` constructor complains.

So, I tried this:

```javascript
var __webpack_exports__event = new Proxy(
	{}, 
	{
		apply() {return Reflect.apply(__webpack_exports__.event, ...arguments.slice(1));},
		construct() {return Reflect.construct(__webpack_exports__.event, ...arguments.slice(1));},
		defineProperty() {return Reflect.defineProperty(__webpack_exports__.event, ...arguments.slice(1));},
		deleteProperty() {return Reflect.deleteProperty(__webpack_exports__.event, ...arguments.slice(1));},
		get() {return Reflect.get(__webpack_exports__.event, ...arguments.slice(1));},
		getOwnPropertyDescriptor() {return Reflect.getOwnPropertyDescriptor(__webpack_exports__.event, ...arguments.slice(1));},
		getPrototypeOf() {return Reflect.getPrototypeOf(__webpack_exports__.event, ...arguments.slice(1));},
		has() {return Reflect.has(__webpack_exports__.event, ...arguments.slice(1));},
		isExtensible() {return Reflect.isExtensible(__webpack_exports__.event, ...arguments.slice(1));},
		ownKeys() {return Reflect.ownKeys(__webpack_exports__.event, ...arguments.slice(1));},
		preventExtensions() {return Reflect.preventExtensions(__webpack_exports__.event, ...arguments.slice(1));},
		set() {return Reflect.set(__webpack_exports__.event, ...arguments.slice(1));},
		setPrototypeOf() {return Reflect.setPrototypeOf(__webpack_exports__.event, ...arguments.slice(1));},
	}
);
```

Which would have worked and (maybe) led us to a disaster thinking that I had fixed it. However, I was lucky and it failed because `event`'s initial value was `null` (again). Had it been other thing like `{}`, for example, it would have seemed to work.

Why is that?

Well, it turns out that when you use a proxy, you can intercept/substitute every access to the proxied object except for the evaluation of the value of the object itself. This is because `null` is special in the sense that `null` is not an object that has null value, but `null` itself.

In other words, if you export a proxy as `event`, it will never be `null` when imported, because it's in fact an object. Conversely, if you export `null` as `event` it will be null forever, there's no way you can change its value then.

Conclusion: we cannot fix webpack to make the example I provided behave like pure ECMAScript due to limitations in the language, which means that if we wanted to make the example work under a webpack scenario we would have to modify the example, not webpack :-(. 

As this problem arose using [d3](https://github.com/d3) I'm going to check if the latest version still shows the error and, if it does, will file an issue there pointing to this one to see what the authors want to do (fixing their library or stating that it is not compatible with webpack in `library.type = module` mode)

**Comment by izaera** [comment]
For the record (even though it's not related to webpack itself but to the last comment I made): apparently `d3.event` existed in version `1.4.1` but was removed in version `2.0.0` (see https://github.com/d3/d3-selection/tree/v1.4.1#handling-events vs https://github.com/d3/d3-selection/tree/v2.0.0#handling-events).

I'm closing this issue as it cannot be fixed.
