### ISSUE TITLE
Incorrect absolute source map paths on Windows

### ISSUE THREAD

**Issue by antigremlin** [webpack/webpack#1770]
The logic producing relative request paths in source maps is broken on Windows because it converts backslashes to forward slashes not in all cases. This leads to absolute paths in source maps which prevents debugging from IntelliJ WebStorm (as an example of a problem).

EDIT: There are no real failures. The problem is caused by babel-loader See comments below.
(This manifests as test failures in the ConfigTestCases suite. Example of a failure:)

```
AssertionError: expected Array [
  'dummy:///webpack/bootstrap c6577ccbfbeb94c1e520',
  'dummy:///D:/src/webpack/webpack/test/configCases/filename-template/module-filename-template/test.js',
  'dummy:///D:/src/webpack/webpack/test/configCases/filename-template/module-filename-template/index.js'
] to contain 'dummy:///./test.js'
    at Assertion.fail (D:\src\webpack\webpack\test\js\config\extract-text\issue-14\bundle0.js:1018:18)
    at Assertion.prop.value (D:\src\webpack\webpack\test\js\config\extract-text\issue-14\bundle0.js:903:18)
    at Context.<anonymous> (D:\src\webpack\webpack\test\js\config\filename-template\module-filename-template\bundle0.js:65:22)
```

List of failing test cases:

- ConfigTestCases:filename-template-module-filename-template
- ConfigTestCases:source-map:exclude-chunks-source-map
- ConfigTestCases:source-map:line-to-line
- ConfigTestCases:source-map:sources-array-production
- ConfigTestCases:source-map:sources-array-production-cheap-map

Cause of the problem is code in RequestShortener.js. Pull request will follow.

**Comment by antigremlin** [comment]
I'm sorry to say the tests mentioned above were failing after modifying the code. I'm now extending some tests to expose the problem without changes in the project code.

**Comment by antigremlin** [comment]
It appears the problem is caused by babel-core converting backslashes to forward slashes prematurely. I don't know how to reproduce this easily in webpack. In theory we could use a psuedo-loader which spoils the source filenames. Then the problem in RequestShortener will be exposed.

**Comment by antigremlin** [comment]
The test failure in AppVeyor is caused by an older version of Webpack being used by `i18n-webpack-plugin` when running the example. It can be fixed by replacing the node_modules/webpack directory by a symlink from the project directory.
