### ISSUE TITLE
How to make dev server serve both http and https

### ISSUE THREAD

**Issue by zdm** [webpack/webpack#17801]
Hi.

I need to make webpack dev server listen both http and https.

I am using following code:
```
const compiler = webpack( webpackConfigs );

const http = new WebpackDevServer(
    {
        "port": 80,
    },
    compiler
);

const https = new WebpackDevServer(
    {
        "port": 443,
        "https": true,
    },
    compiler
);

await http.start();
await https.start();
```

Errors:
```
(node:24836) [DEP_WEBPACK_DEV_SERVER_HTTPS] DeprecationWarning: 'https' option is deprecated. Please use the 'server' option.
(Use `node --trace-deprecation ...` to show where the warning was created)
d:\projects\zdm\playground\frontend\node_modules\webpack\lib\ProgressPlugin.js:398
                        return /** @type {Promise<CountsData>} */ (cacheGetPromise).then(
                                                                                    ^

TypeError: Cannot read properties of undefined (reading 'then')
    at d:\projects\zdm\playground\frontend\node_modules\webpack\lib\ProgressPlugin.js:398:64
    at _next0 (eval at create (d:\projects\zdm\playground\frontend\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:9:17)
    at eval (eval at create (d:\projects\zdm\playground\frontend\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:27:1)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by zdm** [comment]
Does this a correct way at all - run two servers, which are uses same sompiler?

Unable to find docs for this case/

**Comment by zdm** [comment]
this is not possiblle
