### ISSUE TITLE
error:03000086:digital envelope routines::initialization error

### ISSUE THREAD

**Issue by aardrasystems** [webpack/webpack#17985]
Hi
I have recently updated my Angular Ionic 6 project to use Node JS 20.11.00. And I am getting the following error. Can you advice what needs to be done to solve this issue?

```
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:68:19)
    at Object.createHash (node:crypto:138:10)
    at BulkUpdateDecorator.hashFactory (G:\AVR_Project\Ionic Projects\App0001-AC\node_modules\webpack\lib\util\createHash.js:145:18)    
    at BulkUpdateDecorator.update (G:\AVR_Project\Ionic Projects\App0001-AC\node_modules\webpack\lib\util\createHash.js:46:50)
    at RawSource.updateHash (G:\AVR_Project\Ionic Projects\App0001-AC\node_modules\webpack\node_modules\webpack-sources\lib\RawSource.js:77:8)
    at NormalModule._initBuildHash (G:\AVR_Project\Ionic Projects\App0001-AC\node_modules\webpack\lib\NormalModule.js:880:17)
    at handleParseResult (G:\AVR_Project\Ionic Projects\App0001-AC\node_modules\webpack\lib\NormalModule.js:946:10)
    at G:\AVR_Project\Ionic Projects\App0001-AC\node_modules\webpack\lib\NormalModule.js:1040:4
    at processResult (G:\AVR_Project\Ionic Projects\App0001-AC\node_modules\webpack\lib\NormalModule.js:755:11)
    at G:\AVR_Project\Ionic Projects\App0001-AC\node_modules\webpack\lib\NormalModule.js:819:5 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

```

**Comment by alexander-akait** [comment]
Please read https://github.com/webpack/webpack/issues/14532#issuecomment-947525539

**Comment by devsheva** [comment]
i keep getting the same problem with webpack v5
