### ISSUE TITLE
Local tests failing

### ISSUE THREAD

**Issue by pavellishin** [webpack/webpack#1819]
Not sure what's going on. I'm on OS X 10.10.5.

This happens both on the master branch (1f58c55) as well as the v1.12.9 tag.

```
# npm --version
3.3.12

# node --version
v5.2.0

# npm test

... tests tests tests ...

  4436 passing (1m)
  32 pending
  6 failing

  1) ConfigTestCases extract-text issue-14 should compile:
     Error: Cannot find module 'webpack/lib/ConcatSource'
      at Function.Module._resolveFilename (module.js:327:15)
      at Function.Module._load (module.js:278:25)
      at Module.require (module.js:355:17)
      at require (internal/module.js:13:17)
      at Object.<anonymous> (/Users/pavel.lishin/projects/webpack/node_modules/extract-text-webpack-plugin/index.js:5:20)
      at Module._compile (module.js:399:26)
      at Object.Module._extensions..js (module.js:406:10)
      at Module.load (module.js:345:32)
      at Function.Module._load (module.js:302:12)
      at Module.require (module.js:355:17)
      at require (internal/module.js:13:17)
      at Object.<anonymous> (/Users/pavel.lishin/projects/webpack/test/configCases/extract-text/issue-14/webpack.config.js:1:11)
      at Module._compile (module.js:399:26)
      at Object.Module._extensions..js (module.js:406:10)
      at Module.load (module.js:345:32)
      at Function.Module._load (module.js:302:12)
      at Module.require (module.js:355:17)
      at require (internal/module.js:13:17)
      at Context.<anonymous> (/Users/pavel.lishin/projects/webpack/test/ConfigTestCases.test.js:29:20)
      at Test.Runnable.run (/Users/pavel.lishin/projects/webpack/node_modules/mocha/lib/runnable.js:233:15)
      at Runner.runTest (/Users/pavel.lishin/projects/webpack/node_modules/mocha/lib/runner.js:390:10)
      at /Users/pavel.lishin/projects/webpack/node_modules/mocha/lib/runner.js:473:12
      at next (/Users/pavel.lishin/projects/webpack/node_modules/mocha/lib/runner.js:315:14)
      at /Users/pavel.lishin/projects/webpack/node_modules/mocha/lib/runner.js:325:7
      at next (/Users/pavel.lishin/projects/webpack/node_modules/mocha/lib/runner.js:260:23)
      at Immediate._onImmediate (/Users/pavel.lishin/projects/webpack/node_modules/mocha/lib/runner.js:292:5)
      at processImmediate [as _immediateCallback] (timers.js:384:17)

  2) Examples should compile code-splitted-css-bundle:
     Error: Cannot find module 'webpack/lib/ConcatSource'
      at Function.Module._resolveFilename (module.js:327:15)
      at Function.Module._load (module.js:278:25)
      at Module.require (module.js:355:17)
      at require (internal/module.js:13:17)
      at Object.<anonymous> (/Users/pavel.lishin/projects/webpack/node_modules/extract-text-webpack-plugin/index.js:5:20)
      at Module._compile (module.js:399:26)
      at Object.Module._extensions..js (module.js:406:10)
      at Module.load (module.js:345:32)
      at Function.Module._load (module.js:302:12)
      at Module.require (module.js:355:17)
      at require (internal/module.js:13:17)
      at Object.<anonymous> (/Users/pavel.lishin/projects/webpack/examples/code-splitted-css-bundle/webpack.config.js:1:25)
      at Module._compile (module.js:399:26)
      at Object.Module._extensions..js (module.js:406:10)
      at Module.load (module.js:345:32)
      at Function.Module._load (module.js:302:12)
      at Module.require (module.js:355:17)
      at require (internal/module.js:13:17)
      at Context.<anonymous> (/Users/pavel.lishin/projects/webpack/test/Examples.test.js:20:15)
      at Test.Runnable.run (/Users/pavel.lishin/projects/webpack/node_modules/mocha/lib/runnable.js:233:15)
      at Runner.runTest (/Users/pavel.lishin/projects/webpack/node_modules/mocha/lib/runner.js:390:10)
      at /Users/pavel.lishin/projects/webpack/node_modules/mocha/lib/runner.js:473:12
      at next (/Users/pavel.lishin/projects/webpack/node_modules/mocha/lib/runner.js:315:14)
      at /Users/pavel.lishin/projects/webpack/node_modules/mocha/lib/runner.js:325:7
      at next (/Users/pavel.lishin/projects/webpack/node_modules/mocha/lib/runner.js:260:23)
      at Immediate._onImmediate (/Users/pavel.lishin/projects/webpack/node_modules/mocha/lib/runner.js:292:5)
      at processImmediate [as _immediateCallback] (timers.js:384:17)

  3) Examples should compile css-bundle:
     Error: Cannot find module 'webpack/lib/ConcatSource'
    at Function.Module._resolveFilename (module.js:327:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at Object.<anonymous> (/Users/pavel.lishin/projects/webpack/node_modules/extract-text-webpack-plugin/index.js:5:20)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at Object.<anonymous> (/Users/pavel.lishin/projects/webpack/examples/css-bundle/webpack.config.js:1:25)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at Context.<anonymous> (/Users/pavel.lishin/projects/webpack/test/Examples.test.js:20:15)
    at Test.Runnable.run (/Users/pavel.lishin/projects/webpack/node_modules/mocha/lib/runnable.js:233:15)
    at Runner.runTest (/Users/pavel.lishin/projects/webpack/node_modules/mocha/lib/runner.js:390:10)
    at /Users/pavel.lishin/projects/webpack/node_modules/mocha/lib/runner.js:473:12
    at next (/Users/pavel.lishin/projects/webpack/node_modules/mocha/lib/runner.js:315:14)
    at /Users/pavel.lishin/projects/webpack/node_modules/mocha/lib/runner.js:325:7
    at next (/Users/pavel.lishin/projects/webpack/node_modules/mocha/lib/runner.js:260:23)
    at Immediate._onImmediate (/Users/pavel.lishin/projects/webpack/node_modules/mocha/lib/runner.js:292:5)
    at processImmediate [as _immediateCallback] (timers.js:384:17)


  4) Examples should compile i18n:
     Error: Cannot find module 'webpack/lib/dependencies/ConstDependency'
    at Function.Module._resolveFilename (module.js:327:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at Object.<anonymous> (/Users/pavel.lishin/projects/webpack/node_modules/i18n-webpack-plugin/index.js:5:23)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at Object.<anonymous> (/Users/pavel.lishin/projects/webpack/examples/i18n/webpack.config.js:2:18)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at Context.<anonymous> (/Users/pavel.lishin/projects/webpack/test/Examples.test.js:20:15)
    at Test.Runnable.run (/Users/pavel.lishin/projects/webpack/node_modules/mocha/lib/runnable.js:233:15)
    at Runner.runTest (/Users/pavel.lishin/projects/webpack/node_modules/mocha/lib/runner.js:390:10)
    at /Users/pavel.lishin/projects/webpack/node_modules/mocha/lib/runner.js:473:12
    at next (/Users/pavel.lishin/projects/webpack/node_modules/mocha/lib/runner.js:315:14)
    at /Users/pavel.lishin/projects/webpack/node_modules/mocha/lib/runner.js:325:7
    at next (/Users/pavel.lishin/projects/webpack/node_modules/mocha/lib/runner.js:260:23)
    at Immediate._onImmediate (/Users/pavel.lishin/projects/webpack/node_modules/mocha/lib/runner.js:292:5)
    at processImmediate [as _immediateCallback] (timers.js:384:17)


  5) Examples should compile multiple-entry-points-commons-chunk-css-bundle:
     Error: Cannot find module 'webpack/lib/ConcatSource'
    at Function.Module._resolveFilename (module.js:327:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at Object.<anonymous> (/Users/pavel.lishin/projects/webpack/node_modules/extract-text-webpack-plugin/index.js:5:20)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at Object.<anonymous> (/Users/pavel.lishin/projects/webpack/examples/multiple-entry-points-commons-chunk-css-bundle/webpack.config.js:3:25)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at Context.<anonymous> (/Users/pavel.lishin/projects/webpack/test/Examples.test.js:20:15)
    at Test.Runnable.run (/Users/pavel.lishin/projects/webpack/node_modules/mocha/lib/runnable.js:233:15)
    at Runner.runTest (/Users/pavel.lishin/projects/webpack/node_modules/mocha/lib/runner.js:390:10)
    at /Users/pavel.lishin/projects/webpack/node_modules/mocha/lib/runner.js:473:12
    at next (/Users/pavel.lishin/projects/webpack/node_modules/mocha/lib/runner.js:315:14)
    at /Users/pavel.lishin/projects/webpack/node_modules/mocha/lib/runner.js:325:7
    at next (/Users/pavel.lishin/projects/webpack/node_modules/mocha/lib/runner.js:260:23)
    at Immediate._onImmediate (/Users/pavel.lishin/projects/webpack/node_modules/mocha/lib/runner.js:292:5)
    at processImmediate [as _immediateCallback] (timers.js:384:17)


  6) Examples should compile web-worker:
     Error: Cannot find module 'webpack/lib/webworker/WebWorkerTemplatePlugin'
 @ (webpack)/examples/web-worker/example.js 1:13-39
    at /Users/pavel.lishin/projects/webpack/test/Examples.test.js:44:18
    at Compiler.<anonymous> (/Users/pavel.lishin/projects/webpack/lib/Compiler.js:223:14)
    at Compiler.emitRecords (/Users/pavel.lishin/projects/webpack/lib/Compiler.js:311:37)
    at Compiler.<anonymous> (/Users/pavel.lishin/projects/webpack/lib/Compiler.js:216:11)
    at /Users/pavel.lishin/projects/webpack/lib/Compiler.js:304:11
    at Compiler.applyPluginsAsync (/Users/pavel.lishin/projects/webpack/node_modules/tapable/lib/Tapable.js:60:69)
    at Compiler.afterEmit (/Users/pavel.lishin/projects/webpack/lib/Compiler.js:301:8)
    at Compiler.<anonymous> (/Users/pavel.lishin/projects/webpack/lib/Compiler.js:296:14)
    at /Users/pavel.lishin/projects/webpack/node_modules/async/lib/async.js:52:16
    at done (/Users/pavel.lishin/projects/webpack/node_modules/async/lib/async.js:246:17)
    at /Users/pavel.lishin/projects/webpack/node_modules/async/lib/async.js:44:16
    at /Users/pavel.lishin/projects/webpack/node_modules/graceful-fs/graceful-fs.js:42:10
    at /Users/pavel.lishin/projects/webpack/node_modules/mocha/node_modules/graceful-fs/graceful-fs.js:104:5
    at FSReqWrap.oncomplete (fs.js:83:15)

```

One of the browser tests is failing as well:

```
library2
✓ should run after common
✖ should load stuff with require.ensure asynchron
AssertionError: expected true === false
    at Context.<anonymous> (file:///Users/pavel.lishin/projects/webpack/test/browsertest/js/library2.js:70:11)
    at Test.Runnable.run (file:///Users/pavel.lishin/projects/webpack/test/browsertest/mocha.js:3659:32)
    at Runner.runTest (file:///Users/pavel.lishin/projects/webpack/test/browsertest/mocha.js:3978:10)
    at file:///Users/pavel.lishin/projects/webpack/test/browsertest/mocha.js:4024:12
    at next (file:///Users/pavel.lishin/projects/webpack/test/browsertest/mocha.js:3906:14)
    at file:///Users/pavel.lishin/projects/webpack/test/browsertest/mocha.js:3915:7
    at next (file:///Users/pavel.lishin/projects/webpack/test/browsertest/mocha.js:3863:23)
    at file:///Users/pavel.lishin/projects/webpack/test/browsertest/mocha.js:3883:5
    at file:///Users/pavel.lishin/projects/webpack/test/browsertest/mocha.js:4828:44
```

![image](https://cloud.githubusercontent.com/assets/296084/12042469/65d65b5c-ae49-11e5-874f-de864e27d8f9.png)

**Comment by bebraw** [comment]
Is this for webpack 1 or webpack 2?

**Comment by pavellishin** [comment]
This happens both on the master branch (which I believe is 2), and on the v1.12.9 release tag.

I'm on OS X 10.10.5, if that helps.

**Comment by pavellishin** [comment]
Switching to node 4.2.4 with `nvm` fixes the above issue, but there's still a failing test:


```
# npm --version
2.14.12

# node --version
v4.2.4

# npm test

... tests tests tests ...

  1) Examples should compile i18n:
     Uncaught TypeError: dep.getReference is not a function
    at processDependency (/Users/pavel.lishin/projects/webpack/lib/FlagDependencyUsagePlugin.js:55:24)
    at /Users/pavel.lishin/projects/webpack/lib/FlagDependencyUsagePlugin.js:42:5
    at Array.forEach (native)
    at processDependenciesBlock (/Users/pavel.lishin/projects/webpack/lib/FlagDependencyUsagePlugin.js:41:26)
    at processModule (/Users/pavel.lishin/projects/webpack/lib/FlagDependencyUsagePlugin.js:37:4)
    at /Users/pavel.lishin/projects/webpack/lib/FlagDependencyUsagePlugin.js:20:6
    at Array.forEach (native)
    at Compilation.<anonymous> (/Users/pavel.lishin/projects/webpack/lib/FlagDependencyUsagePlugin.js:18:23)
    at Compilation.applyPluginsBailResult (/Users/pavel.lishin/projects/webpack/node_modules/tapable/lib/Tapable.js:48:50)
    at Compilation.seal (/Users/pavel.lishin/projects/webpack/lib/Compilation.js:513:8)
    at Compiler.<anonymous> (/Users/pavel.lishin/projects/webpack/lib/Compiler.js:426:15)
    at /Users/pavel.lishin/projects/webpack/node_modules/tapable/lib/Tapable.js:103:11
    at Compilation.<anonymous> (/Users/pavel.lishin/projects/webpack/lib/Compilation.js:436:10)
    at /Users/pavel.lishin/projects/webpack/lib/Compilation.js:411:12
    at /Users/pavel.lishin/projects/webpack/lib/Compilation.js:326:10
    at /Users/pavel.lishin/projects/webpack/node_modules/async/lib/async.js:52:16
    at done (/Users/pavel.lishin/projects/webpack/node_modules/async/lib/async.js:246:17)
    at /Users/pavel.lishin/projects/webpack/node_modules/async/lib/async.js:44:16
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
```

**Comment by IngwiePhoenix** [comment]
I too get the i18n issue, plus another about labeled modules. Node 5.3.0 here, OS X 10.11.2

**Comment by SimenB** [comment]
https://github.com/webpack/webpack/pull/2087#issuecomment-187431875

**Comment by bebraw** [comment]
Can you try again?

**Comment by pavellishin** [comment]
Getting different errors now in master. Cloned repo, ran `npm install`, and then what you see below.

OS X Yosemite, 10.10.5

```
[2016-12-24 10:03:29] pavel.lishin@plishin:~/Temp/webpack
# npm --version
3.10.9
[2016-12-24 10:03:32] pavel.lishin@plishin:~/Temp/webpack
# node --version
v7.1.0
[2016-12-24 10:03:33] pavel.lishin@plishin:~/Temp/webpack
# npm test

> webpack@2.2.0-rc.2 pretest /Users/pavel.lishin/Temp/webpack
> npm run lint-files


> webpack@2.2.0-rc.2 lint-files /Users/pavel.lishin/Temp/webpack
> npm run lint && npm run beautify-lint


> webpack@2.2.0-rc.2 lint /Users/pavel.lishin/Temp/webpack
> eslint lib bin hot


/Users/pavel.lishin/Temp/webpack/lib/Compilation.js
  803:28  warning  Don't make functions within a loop  no-loop-func

✖ 1 problem (0 errors, 1 warning)


> webpack@2.2.0-rc.2 beautify-lint /Users/pavel.lishin/Temp/webpack
> beautify-lint 'lib/**/*.js' 'hot/**/*.js' 'bin/**/*.js' 'benchmark/*.js' 'test/*.js'

Fine. (267 files checked)

> webpack@2.2.0-rc.2 test /Users/pavel.lishin/Temp/webpack
> mocha --harmony --check-leaks

module.js:474
    throw err;
    ^

Error: Cannot find module 'webpack/lib/removeAndDo'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/pavel.lishin/Temp/webpack/node_modules/extract-text-webpack-plugin/ExtractedModule.js:30:42)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/pavel.lishin/Temp/webpack/node_modules/extract-text-webpack-plugin/index.js:8:23)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/pavel.lishin/Temp/webpack/test/HotTestCases.test.js:6:25)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at require (internal/module.js:20:19)
    at /Users/pavel.lishin/Temp/webpack/node_modules/mocha/lib/mocha.js:222:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/pavel.lishin/Temp/webpack/node_modules/mocha/lib/mocha.js:219:14)
    at Mocha.run (/Users/pavel.lishin/Temp/webpack/node_modules/mocha/lib/mocha.js:487:10)
    at Object.<anonymous> (/Users/pavel.lishin/Temp/webpack/node_modules/mocha/bin/_mocha:459:18)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.runMain (module.js:607:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3
npm ERR! Test failed.  See above for more details.
[2016-12-24 10:03:42] pavel.lishin@plishin:~/Temp/webpack
#
```

**Comment by TheLarkInn** [comment]
Run `npm link && npm link webpack` Then run tests!!!

**Comment by pavellishin** [comment]
With that,

```
  6220 passing (3m)
  73 pending
```

👍
