### ISSUE TITLE
Webpack2: undefined `meta` in HarmonyImportDependency and HarmonyImportSpecifierDependency

### ISSUE THREAD

**Issue by RickWong** [webpack/webpack#1833]
I'm using webpack 2.0.2-beta. In short, webpack2 attempts to access `dep.module.meta.harmonyModule` and `dep.importDependency.module.meta.harmonyModule` which causes an error reading from `undefined`, which points to the `.meta` part. Here's the full build output of one of the source files, the other is mostly similar:

```
ERROR in chunk main [entry]
server.js
Cannot read property 'harmonyModule' of undefined
TypeError: Cannot read property 'harmonyModule' of undefined
    at Function.HarmonyImportDependency.makeStatement (/Users/rick/Sites/react-isomorphic-starterkit/node_modules/webpack/lib/dependencies/HarmonyImportDependency.js:35:22)
    at HarmonyImportDependencyTemplate.HarmonyImportDependency.Template.apply (/Users/rick/Sites/react-isomorphic-starterkit/node_modules/webpack/lib/dependencies/HarmonyImportDependency.js:48:40)
```

I stumbled on this error while using this config: https://github.com/RickWong/react-isomorphic-starterkit/blob/534c2542701c4db966ef0679bd8de0236fcadd65/configs/webpack.server.js Note that this config marks all node_modules as externals because its result should run in a node server.

By checking the `.meta`s in both files first, I'm able to complete the build successfully. It would be nice if 2.0.3-beta would include this fix. 

Should I make a Pull Request?

**Comment by RickWong** [comment]
Thanks!
