### ISSUE TITLE
runtime.js cannot find bundles to require when code splitting among multiple bundles is enabled

### ISSUE THREAD

**Issue by Arandhras** [webpack/webpack#18409]
# Bug report

I have encountered a bug while trying to split code into multiple bundles, while preventing 
duplication of said code. In other words, I want to create a "main" bundle which is the "true" 
entry point of the application, and one or more auxiliary bundles. To this end, I have followed
the documentation [present at this page](https://webpack.js.org/guides/code-splitting/#prevent-duplication).

**What is the current behavior?**
The following is the config object contained in my `webpack.config.js` file:
```
const config = {
    entry: {
        lib: {
            import: './src/foo.js',
        },
        main: {
            import: './src/index.js',
            dependOn: ['lib']
        }
    },
    output: {
        path: path.resolve(__dirname, 'dist'),
        filename: '[name].js',
    },
    target: 'node',
    optimization: {
        runtimeChunk: 'single',
    },
};
```

After launching the `npx webpack` command and executing `node .\dist\main.js`, node throws the following `Error`:
```
Error: Cannot find module './undefined'
Require stack:
- d:\svi\webpack-codesplit-test\dist\runtime.js
- d:\svi\webpack-codesplit-test\dist\main.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at __webpack_require__.f.require (d:\svi\webpack-codesplit-test\dist\runtime.js:110:28)
    at d:\svi\webpack-codesplit-test\dist\runtime.js:48:40
    at Array.reduce (<anonymous>)
    at __webpack_require__.e (d:\svi\webpack-codesplit-test\dist\runtime.js:47:67)
    at Array.map (<anonymous>)
    at __webpack_require__.X (d:\svi\webpack-codesplit-test\dist\runtime.js:74:22) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'd:\\svi\\webpack-codesplit-test\\dist\\runtime.js',
    'd:\\svi\\webpack-codesplit-test\\dist\\main.js'
  ]
}
```

**If the current behavior is a bug, please provide the steps to reproduce.**

I have written a simple test project that is [available at this GitHub repository](https://github.com/Arandhras/webpack-codesplit-test).
After downloading the project simply run `npm run dev` to get the required node_modules
(webpack, webpack-cli and their dependencies) and then automatically execute `node .\dist\main.js`.

**What is the expected behavior?**

It seems that `.\dist\runtime.js` is broken, specifically in two points.

```
/******/ 	/* webpack/runtime/get javascript chunk filename */
/******/ 	(() => {
/******/ 		// This function allow to reference async chunks and sibling chunks for the entrypoint
/******/ 		__webpack_require__.u = (chunkId) => {
/******/ 			// return url for filenames based on template
/******/ 			return undefined;
/******/ 		};
/******/ 	})();
```
Why is this function returning `undefined` regardless of the `chunkId` being passed?
In development mode, if I change the return line into
```
return `${chunkId}.js`
```
the `require()` that is immediately called after, is working.

Another issue I've identified, lies within this function:
```
/******/ 		var installChunk = (chunk) => {
/******/ 			var moreModules = chunk.modules, chunkIds = chunk.ids, runtime = chunk.runtime;
/******/ 			for(var moduleId in moreModules) {
/******/ 				if(__webpack_require__.o(moreModules, moduleId)) {
/******/ 					__webpack_require__.m[moduleId] = moreModules[moduleId];
/******/ 				}
/******/ 			}
/******/ 			if(runtime) runtime(__webpack_require__);
/******/ 			for(var i = 0; i < chunkIds.length; i++)
/******/ 				installedChunks[chunkIds[i]] = 1;
/******/ 		
/******/ 		};
```
Sometimes the `chunk` argument being passed is an empty object `{}`, therefore `chunkIds` is `undefined`.
In this case when the for loop is reached, accessing `chunkIds.length` results in an `Error` being thrown.

**Other relevant information:**
webpack version: 5.91.0
Node.js version: v18.18.0
Operating System: Windows 10 Enterprise 22H2
Additional tools: none

**Comment by alexander-akait** [comment]
Do you build application or library? What is your target - `node` or `web`?

**Comment by Arandhras** [comment]
> Do you build application or library? What is your target - `node` or `web`?

My target is node.

**Comment by alexander-akait** [comment]
Why do you need `runtimeChunk` for node?

**Comment by alexander-akait** [comment]
Yeah, it is a bug, something wrong with `dependOn` and `optimization.runtimeChunk` with node target

Feel free to send a fix

**Comment by Arandhras** [comment]
We are developing a server architecture where you have a "core bundle" (where the actual entry point of the application is) and several "client" ones, and we want to be able to split this code so that we can deploy the application with zero, one or just a few client bundles instead of all of them.

The rationale is twofold:
1) since we can have different on-premise deployments at different clients, and we do not wish to expose client-specific business logic to someone who isn't the intended user;
2) when updating our application deployments without altering the underlying node_modules, we would like to install only the core or client bundle(s) that actually got modified instead of the entirety of the codebase reduced to a single, monolithic bundle.

**Comment by alexander-akait** [comment]
bump

**Comment by alexander-akait** [comment]
@arpit10128 I think we have a bug with runtime merging somewhere

I can look at the problem deeply but i need a reproducible repository

**Comment by arpit10128** [comment]
[available at this GitHub repository](https://github.com/Arandhras/webpack-codesplit-test).

**Comment by alexander-akait** [comment]
@arpit10128 What about:

```
entry: {
        lib: {
            import: './src/foo.js',
            runtime: false
        },
        main: {
            import: './src/index.js',
            dependOn: ['lib']
        }
    },
```

The problem is that you want to build both the application and the library together, but at the same time share one runtime between them. `runtimeChunk` is more for the application than libraries, an alternative solution is to use multi compiler mode. Technically, this can be solved, but it will all have some limitations, especially regarding HMR.

**Comment by Raghavg18** [comment]
Hey, I would like to solve this problem i can fix the runtimechunk which is not build correctly and giving problems during code-splitting.

**Comment by Mr-Raza-Alam** [comment]
hello sir, please assign me a bug. i want to work on it

**Comment by pranjalisr** [comment]
The issue occurs when you have:

1. Multiple entry points (in this case 'lib' and 'main')
2. Dependencies between entry points ('main' depends on 'lib')
3. Code splitting enabled with `runtimeChunk: 'single'`
The error `Cannot find module './undefined'` happens because webpack's runtime is unable to correctly resolve the bundle paths.
Make sure webpack.config.js has following paths:
const path = require("path")

module.exports = {
  entry: {
    lib: "./src/foo.js",
    main: {
      import: "./src/index.js",
      dependOn: ["lib"],
    },
  },
  output: {
    path: path.resolve(__dirname, "dist"),
    filename: "[name].js",
    // Add this to fix the issue
    chunkLoadingGlobal: "webpackChunkWebpack",
    // Ensure unique names for runtime chunks
    uniqueName: "myapp",
  },
  target: "node",
  optimization: {
    runtimeChunk: "single",
    // Add this to ensure proper chunk loading
    chunkIds: "deterministic",
  },
}

1. Add `chunkLoadingGlobal`: This ensures a unique global variable is used for chunk loading, preventing conflicts.
2. Add `uniqueName`: This helps webpack generate unique identifiers for your chunks, which is crucial when using code splitting with multiple entry points.
3. Use `chunkIds: 'deterministic'`: This ensures consistent and predictable chunk IDs, which helps with proper chunk resolution.


These changes help webpack's runtime correctly identify and load the chunks, resolving the "Cannot find module './undefined'" error.

Do let me know, if this works or do you need an alternate solution.

**Comment by xiaoxiaojx** [comment]
I’ve run into the same issue. I’ll take a look and send a fix PR.
