### ISSUE TITLE
angular 18: registerQuery in layout.mjs crashes in Production bundles.

### ISSUE THREAD

**Issue by fahadash** [webpack/webpack#18550]
# Bug report

**What is the current behavior?**
My angular app using angular 18 and angular Material is crashing with the following error in release/prod bundles.

```
TypeError: Cannot read properties of undefined (reading 'U')
    at T._registerQuery (layout.mjs:168:33)
    at layout.mjs:133:55
    at Array.map (<anonymous>)
    at T.observe (layout.mjs:133:37)
    at new xe (a11y.mjs:2333:14)
    at Object.xe_Factory [as factory] (ɵfac.js:1:1)
    at Cr.hydrate (core.mjs:3239:43)
    at Cr.get (core.mjs:3096:33)
    at qn (core.mjs:1107:40)
    at Zn (core.mjs:1113:42)
```

**If the current behavior is a bug, please provide the steps to reproduce.**
I tried reproducing this behavior by creating a test app but I couldn't get it to happen, however I discovered the following facts along the way

It occurs because my app is using angular material
My app uses only one component of material called popups
Material has some built-in high contrast mode detector which is causing this
The real underlying issue is that _webpack_require is unable to fulfill 'map' of rxjs/operators which is required by HighContrastModeDetector.ts
This is not happening for development bundles.

**What is the expected behavior?**

The 'map' symbol must not be missing and must be fulfilled by _webpack_require()

**Other relevant information:**
webpack version:  5.1.4
Node.js version: 20.x
Operating System: Windows 10
Additional tools: terser 5.3.10, zone 0.14.7, typescript 5.4.2, ts-loader 9.5.1

**Comment by fahadash** [comment]
I solved this issue by setting sideEffects property of optimization object to false in the config.
