### ISSUE TITLE
Issue while bundling library type "module" in entries

### ISSUE THREAD

**Issue by Sivaganesh-Akula** [webpack/webpack#18594]
# Bug report

**What is the current behavior?**

```
const path = require("path");

module.exports = {
  entry: {
    dateUtils: "./src/dateUtils.js",
    stringUtils: "./src/stringUtils.js",
    main: {
      import: "./src/main.js",
      runtime: "main-runtime",
    },
    admin: {
      import: "./src/admin.js",
      dependOn: ["dateUtils", "stringUtils"],
      library: { name: "AdminLibrary", type: "module" },
    },
  },
  mode: "development",
  devtool: false,
  output: {
    filename: "[name].bundle.js",

    path: path.resolve(__dirname, "dist"),
    clean: true,
  },
  experiments: {
    outputModule: true,
  },
};
```

**Got the below error while bundling the project with the above config**

`Error: Library name must be unset. Common configuration options that specific library names are 'output.library[.name]', 'entry.xyz.library[.name]', 'ModuleFederationPlugin.name' and 'ModuleFederationPlugin.library[.name]'.
    at ModuleLibraryPlugin.parseOptions (/Users/admin/workspace/configurations/node_modules/webpack/lib/library/ModuleLibraryPlugin.js:57:10)
    at ModuleLibraryPlugin._parseOptionsCached (/Users/admin/workspace/configurations/node_modules/webpack/lib/library/AbstractLibraryPlugin.js:209:23)
    at /Users/admin/workspace/configurations/node_modules/webpack/lib/library/AbstractLibraryPlugin.js:68:28
    at _next2 (eval at create (/Users/admin/workspace/configurations/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:19:1)
    at eval (eval at create (/Users/admin/workspace/configurations/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:52:1)
    at /Users/admin/workspace/configurations/node_modules/webpack/lib/FlagDependencyExportsPlugin.js:394:10
    at /Users/admin/workspace/configurations/node_modules/neo-async/async.js:2830:7
    at Object.each (/Users/admin/workspace/configurations/node_modules/neo-async/async.js:2850:39)
    at /Users/admin/workspace/configurations/node_modules/webpack/lib/FlagDependencyExportsPlugin.js:365:17
    at /Users/admin/workspace/configurations/node_modules/neo-async/async.js:2830:7`

**What is the expected behavior?**
Successfully bundle the files

**Other relevant information:**
webpack version:  5.93.0
Node.js version: 20.11.1
Operating System: Mac (Intel)
Additional tools:

**Comment by alexander-akait** [comment]
Please remove `name: "AdminLibrary"`, you already set `admin` as a name
