### ISSUE TITLE
Give error as hexoid is not a function

### ISSUE THREAD

**Issue by Khushboo1806** [webpack/webpack#18600]
TypeError: hexoid is not a function
    at __webpack_require__ (D:\react\login-module\.next\server\webpack-runtime.js:33:42)
    at __webpack_require__ (D:\react\login-module\.next\server\webpack-runtime.js:33:42)
    at eval (./src/app/api/LoginApi.ts:8:68)
    at (ssr)/./src/app/api/LoginApi.ts (D:\react\login-module\.next\server\app\page.js:393:1)
    at __webpack_require__ (D:\react\login-module\.next\server\webpack-runtime.js:33:42)
    at eval (./src/app/context/AuthContext.tsx:10:71)
    at (ssr)/./src/app/context/AuthContext.tsx (D:\react\login-module\.next\server\app\page.js:415:1)
    at __webpack_require__ (D:\react\login-module\.next\server\webpack-runtime.js:33:42)
    at eval (./src/app/layout.tsx:11:78)
    at (ssr)/./src/app/layout.tsx (D:\react\login-module\.next\server\app\page.js:426:1)
    at Object.__webpack_require__ [as require] (D:\react\login-module\.next\server\webpack-runtime.js:33:42)
digest: "394638102"

I Havent used hexoid anywhere'

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

**Comment by vladaman** [comment]
Same issue here, probably used by some dependency and therefore failing.

**Comment by alexander-akait** [comment]
Sounds like a bug/misconfuration in `next.js`, we can't fix it here

that's interesting that in the error message we have `digest: "394638102" , sounds like your Node.js is old, recommend to check it
