### ISSUE TITLE
[BUG] alias causes Webpack to erroneously look for babel plugin in aliased location.

### ISSUE THREAD

**Issue by trusktr** [webpack/webpack#1870]
I've set an alias to some location outside of the project

```js
    "alias": {
        "infamous": "/home/trusktr/src/infamous+infamous"
    }
```

 (it so happens to be an NPM package) which causes errors similar to #1866.

```
   Module build failed: ReferenceError: Unknown plugin "transform-es2015-arrow-functions" specified in "base" at 0, attempted to resolve relative to "/home/trusktr/src/infamous+infamous"
   at /home/trusktr/src/trusktr+portfolio/.meteor/local/rocket-module/platform-builds/web.browser/node_modules/babel-core/lib/transformation/file/options/option-manager.js:193:17
```

This time I've included the whole output (don't know why I didn't last time). Is

```
babel-core/lib/transformation/file/options/option-manager.js:193:17
```

provide any clue?

This might be a dupe of #1866.

**Comment by trusktr** [comment]
I was hoping an alias would've been a workaround for #1866, so that I can develop a local NPM package while I develop a project. 

For now I'll have to add the package's dependencies to my project and move the package's source into the project. Any alternatives to that approach?

**Comment by trusktr** [comment]
Doh, I suppose the whole stack trace relating to babel would help:

```
   at ./node_modules/babel-core/lib/transformation/file/options/option-manager.js:193:17
   at Array.map (native)
   at Function.normalisePlugins (./node_modules/babel-core/lib/transformation/file/options/option-manager.js:173:20)
   at OptionManager.mergeOptions (./node_modules/babel-core/lib/transformation/file/options/option-manager.js:271:36)
   at OptionManager.init (./node_modules/babel-core/lib/transformation/file/options/option-manager.js:416:10)
   at File.initOptions (./node_modules/babel-core/lib/transformation/file/index.js:191:75)
   at new File (./node_modules/babel-core/lib/transformation/file/index.js:122:22)
   at Pipeline.transform (./node_modules/babel-core/lib/transformation/pipeline.js:42:16)
   at transpile (./node_modules/babel-loader/index.js:14:22)
   at ./node_modules/babel-loader/lib/fs-cache.js:145:18
   at ./node_modules/babel-loader/lib/fs-cache.js:28:23
```

**Comment by trusktr** [comment]
I'm not sure if maybe this is a Babel issue, so I posted a new issue over there too: https://phabricator.babeljs.io/T6942

**Comment by trusktr** [comment]
duplicate of #1866
