### ISSUE TITLE
Node 23.2 breaks webpack build when used with some packages

### ISSUE THREAD

**Issue by ThomasAunvik** [webpack/webpack#18963]
# Bug report

Related Issue: https://github.com/nodejs/node/issues/55826

Build breaks on build when using a package like date-fns.

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

When using a package like date-fns with node version 23.2, the build fails.

Minimal reproducible: https://github.com/ThomasAunvik/node232-err-json

```js
import { format } from "date-fns";
import { nb } from "date-fns/locale";

console.log(format(Date.now(), "d. LLLL y", { locale: nb }))
```

Error Recieved:

```
> node23err@1.0.0 build
> webpack

assets by status 0 bytes [cached] 1 asset
orphan modules 1.53 MiB [orphan] 826 modules
./src/index.js + 42 modules 107 KiB [built] [code generated]

WARNING in configuration
The 'mode' option has not been set, webpack will fallback to 'production' for this value.
Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/configuration/mode/

ERROR in ./src/index.js + 42 modules
Unexpected end of JSON input
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at ConcatenationScope.matchModuleReference (/home/thaun/Documents/Projects/node23err/node_modules/webpack/lib/ConcatenationScope.js:132:13)
    at ConcatenatedModule.codeGeneration (/home/thaun/Documents/Projects/node23err/node_modules/webpack/lib/optimize/ConcatenatedModule.js:1192:41)
    at /home/thaun/Documents/Projects/node23err/node_modules/webpack/lib/Compilation.js:3505:22
    at /home/thaun/Documents/Projects/node23err/node_modules/webpack/lib/Cache.js:97:5
    at Hook.eval [as callAsync] (eval at create (/home/thaun/Documents/Projects/node23err/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Cache.get (/home/thaun/Documents/Projects/node23err/node_modules/webpack/lib/Cache.js:79:18)
    at ItemCacheFacade.get (/home/thaun/Documents/Projects/node23err/node_modules/webpack/lib/CacheFacade.js:115:15)
    at Compilation._codeGenerationModule (/home/thaun/Documents/Projects/node23err/node_modules/webpack/lib/Compilation.js:3498:9)
    at /home/thaun/Documents/Projects/node23err/node_modules/webpack/lib/Compilation.js:3403:11

webpack 5.96.1 compiled with 1 error and 1 warning in 1098 ms
```

Node v23.0 and v23.1 works.

**What is the expected behavior?**

Should build with no error.

**Other relevant information:**
webpack version:  `5.96.1`
Node.js version: v23.2.0
Operating System: `Linux arch 6.11.6-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Fri, 01 Nov 2024 03:30:35 +0000 x86_64 GNU/Linux`
Additional tools:

**Comment by alexander-akait** [comment]
Confirmed regression - https://github.com/nodejs/node/issues/55826

**Comment by rgzlv** [comment]
I see this labeled "won't fix", why is that?
I've got the same issue while trying to bundle some (but not all) javascript files for [material web components](https://www.npmjs.com/package/@material/web).
Trying to bundle the `all.js` file brings up the issue since it includes some other files that cause it.
If I make the change below, it builds fine but I have no idea why.
I assume it corrects the input somehow, unlike `.toString()`, so it can be correctly parsed by `JSON.parse` or at least not cause an error.
```
--- node_modules/webpack/lib/ConcatenationScope.js	2024-11-15 11:25:38
+++ -	2024-11-15 12:45:33
@@ -122,21 +122,21 @@
 	static matchModuleReference(name) {
 		const match = MODULE_REFERENCE_REGEXP.exec(name);
 		if (!match) return null;
 		const index = Number(match[1]);
 		const asiSafe = match[5];
 		return {
 			index,
 			ids:
 				match[2] === "ns"
 					? []
-					: JSON.parse(Buffer.from(match[2], "hex").toString("utf-8")),
+					: JSON.parse(JSON.stringify(Buffer.from(match[2], "hex"))),
 			call: Boolean(match[3]),
 			directImport: Boolean(match[4]),
 			asiSafe: asiSafe ? asiSafe === "1" : undefined
 		};
 	}
 }
 ```

**Comment by AYColumbia** [comment]
Am having the same issue with packages like yup, react-tooltip, bootstrap, etc.  I added a link to my test project in [this issue](https://github.com/nodejs/node/issues/55826#issuecomment-2483169251).  For now, I'll go back to node 23.1 as suggested.

**Comment by alexander-akait** [comment]
Fixed in Node.js `23.3.0`, closed
