### ISSUE TITLE
webpack+typescript+electron-forge+zeromq === bizarre

### ISSUE THREAD

**Issue by devzzzero** [webpack/webpack#18987]
[test-ui.zip](https://github.com/user-attachments/files/17788309/test-ui.zip)

# webpack complains of `The "path" argument must be of type string. Received undefined`

**What is the current behavior?**
Webpack fails to load with 
```
App threw an error during load
Error: Failed to load zeromq.js addon.node: TypeError: The "path" argument must be of type string. Received undefined
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at Object.join (node:path:1244:7)
    at findAddon (/home/work/test-app/test-ui/.webpack/main/index.js:2182:70)
    at ./node_modules/zeromq/lib/load-addon.js (/home/work/test-app/test-ui/.webpack/main/index.js:2211:15)
    at __webpack_require__ (/home/work/test-app/test-ui/.webpack/main/index.js:2286:42)
    at ./node_modules/zeromq/lib/native.js (/home/work/test-app/test-ui/.webpack/main/index.js:2231:38)
    at __webpack_require__ (/home/work/test-app/test-ui/.webpack/main/index.js:2286:42)
    at ./node_modules/zeromq/lib/index.js (/home/work/test-app/test-ui/.webpack/main/index.js:1550:16)
    at __webpack_require__ (/home/work/test-app/test-ui/.webpack/main/index.js:2286:42)
    at ./src/core/LogWatcher.ts (/home/work/test-app/test-ui/.webpack/main/index.js:1140:26)
    at __webpack_require__ (/home/work/test-app/test-ui/.webpack/main/index.js:2286:42)
    at findAddon (/home/work/test-app/test-ui/.webpack/main/index.js:2204:15)
    at ./node_modules/zeromq/lib/load-addon.js (/home/work/test-app/test-ui/.webpack/main/index.js:2211:15)
    at __webpack_require__ (/home/work/test-app/test-ui/.webpack/main/index.js:2286:42)
    at ./node_modules/zeromq/lib/native.js (/home/work/test-app/test-ui/.webpack/main/index.js:2231:38)
    at __webpack_require__ (/home/work/test-app/test-ui/.webpack/main/index.js:2286:42)
    at ./node_modules/zeromq/lib/index.js (/home/work/test-app/test-ui/.webpack/main/index.js:1550:16)
    at __webpack_require__ (/home/work/test-app/test-ui/.webpack/main/index.js:2286:42)
    at ./src/core/LogWatcher.ts (/home/work/test-app/test-ui/.webpack/main/index.js:1140:26)
    at __webpack_require__ (/home/work/test-app/test-ui/.webpack/main/index.js:2286:42)
    at ./src/index.ts (/home/work/test-app/test-ui/.webpack/main/index.js:1318:22)
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Please see https://github.com/zeromq/zeromq.js/issues/676

1. `npm init electron-app@latest test-ui -- --template=webpack-typescript`
2. `npm i preact --save-dev` (https://preactjs.com/guide/v10/getting-started and followed `Aliasing in Webpack`
3. `npm i zeromq --save-dev`
I then played around a simple zeromq.Subscriber socket and got it to work (in a single .ts file)
I then tried importing the working code into the main process (index.ts) and that's where the problem began:

**What is the expected behavior?**

I expected it to just work. (Seriously!)

Please see project configuration (tsconfig.ts, package.json and webpack.*.ts) in test-ui.zip

**Other relevant information:**
webpack version:  webpack@5.96.1 | MIT | deps: 23 | versions: 839
Node.js version: node@18.20.5 | ISC | deps: 1 | versions: 730
Operating System: Opensuse 15.5
Additional tools:

**Comment by devzzzero** [comment]
Please help! I'm tearing my hair out here!

**Comment by devzzzero** [comment]
So it looks like the immediate culprit is that the polyfills for `process` is not providing `arch` and `platform` (and has bitrotted since 2016 or so). I am at a loss for how to solve this. Does any kind soul have any suggestions?

thank you.

**Comment by devzzzero** [comment]
issue: https://github.com/Richienb/node-polyfill-webpack-plugin/issues/58

**Comment by devzzzero** [comment]
Please refer to https://github.com/niksy/node-stdlib-browser/issues/33

Thank you.
