### ISSUE TITLE
Cannot extern scoped packages

### ISSUE THREAD

**Issue by Trinovantes** [webpack/webpack#19026]
# Bug report

**What is the current behavior?**

It is not possible to extern a scoped package (e.g. `@sentry/node`)

```js
// webpack.config.js
const path = require('path')

module.exports = {
    mode: 'production',
    target: 'node',

    entry: './src/index.js',

    output: {
        path: path.resolve('./dist'),
    },

    externals: [
        '@sentry/node',
    ],
}
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Using the above config and these files:

`src/index.js`:
```js
import * as Sentry from '@sentry/node'

function main() {
    Sentry.startSpan({
        op: 'My Transaction',
        name: 'Do Stuff',
    }, () => {
        console.log('Hello World')
    })
}

main()
```

`package.json`:
```json
{
  "dependencies": {
    "@sentry/node": "^8.41.0",
    "webpack": "^5.96.1",
    "webpack-cli": "^5.1.4"
  }
}
```

Results in this error message when running `webpack`:

```
ERROR in ./src/index.js + 1 modules
Unexpected character '@' (1:37)
| const __WEBPACK_NAMESPACE_OBJECT__ = @sentry/node;
while analyzing module external var "@sentry/node" for concatenation
SyntaxError: Unexpected character '@' (1:37)
| const __WEBPACK_NAMESPACE_OBJECT__ = @sentry/node;
while analyzing module external var "@sentry/node" for concatenation
    at pp$4.raise (/home/stephen/External/webpack-username/node_modules/acorn/dist/acorn.js:3646:15)
    at pp.getTokenFromCode (/home/stephen/External/webpack-username/node_modules/acorn/dist/acorn.js:5676:10)
    at pp.readToken (/home/stephen/External/webpack-username/node_modules/acorn/dist/acorn.js:5363:17)
    at pp.nextToken (/home/stephen/External/webpack-username/node_modules/acorn/dist/acorn.js:5354:17)
    at pp.next (/home/stephen/External/webpack-username/node_modules/acorn/dist/acorn.js:5315:10)
    at pp$9.eat (/home/stephen/External/webpack-username/node_modules/acorn/dist/acorn.js:702:12)
    at pp$8.parseVar (/home/stephen/External/webpack-username/node_modules/acorn/dist/acorn.js:1326:16)
    at pp$8.parseVarStatement (/home/stephen/External/webpack-username/node_modules/acorn/dist/acorn.js:1191:10)
    at pp$8.parseStatement (/home/stephen/External/webpack-username/node_modules/acorn/dist/acorn.js:927:19)
    at pp$8.parseTopLevel (/home/stephen/External/webpack-username/node_modules/acorn/dist/acorn.js:829:23)

webpack 5.96.1 compiled with 1 error in 181 ms
```

**What is the expected behavior?**

No errors and do not include `@sentry/vue` package in final bundle

**Other relevant information:**
webpack version:  5.96.1
Node.js version: 22.11.0
Operating System: Linux
Additional tools:

**Comment by ayush-0513** [comment]
I think the way Webpack manages externalized scoped packages like @sentry/node is the cause of this problem. Because scoped packages utilize the @ character, which can cause parsing problems, they need to be handled differently in Webpack setups.

Can i solve this problem?

**Comment by AliyanA1** [comment]
we need to modify the externals configuration to specify how Webpack should handle scoped packages. This can be done by providing a function or an object instead of an array.  can i solve this problem?

**Comment by alexander-akait** [comment]
Because using `@sentry/node` is wrong syntax, use:
```
externals: { 
    '@sentry/node': '  @sentry/node',
},
``` 

Please take a look - https://webpack.js.org/configuration/externals/
