### ISSUE TITLE
Ignore shebang line for node scripts?

### ISSUE THREAD

**Issue by blink1073** [webpack/webpack#1952]
I am trying to use an npm package (`requirejs`) that has a shebang line at the top of the script and am getting this error.  Is there a way to ignore a line starting with `#!`?

```
> webpack --config example/webpack.conf.js && node scripts/copythemecss.js

ModuleParseError: Module parse failed: /Users/ssilvester/workspace/jupyter/plugins/node_modules/requirejs/bin/r.js Line 1: Unexpected token ILLEGAL
You may need an appropriate loader to handle this file type.
| #!/usr/bin/env node
| /**
|  * @license r.js 2.1.22 Copyright (c) 2010-2015, The Dojo Foundation All Rights Reserved.
    at DependenciesBlock.<anonymous> (/Users/ssilvester/workspace/jupyter/plugins/node_modules/webpack/lib/NormalModule.js:113:20)
    at DependenciesBlock.onModuleBuild (/Users/ssilvester/workspace/jupyter/plugins/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
    at nextLoader (/Users/ssilvester/workspace/jupyter/plugins/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
    at /Users/ssilvester/workspace/jupyter/plugins/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.finished (/Users/ssilvester/workspace/jupyter/plugins/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at /Users/ssilvester/workspace/jupyter/plugins/node_modules/graceful-fs/graceful-fs.js:76:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:404:3)
```

**Comment by blink1073** [comment]
FWIW, Browserify ignores the shebang line and consumes the file properly.

**Comment by sokra** [comment]
Files with shebang are executables and propably not suited to be consumed as library.

So if you try to consume a file with shebang you are (propably) doing something wrong. i. e. instead of requirejs/**bin**/r.js you should better consume requirejs/**lib**/r.js. (Ignoring the fact that loading `r.js` in a webpack bundle does look wrong)

**Comment by blink1073** [comment]
Thanks @sokra.  I agree that assuming a global RequireJS is the right way to go (this bundle will be part of an existing application that uses RequireJS).
