### ISSUE TITLE
Error in code-splitted-require.context-amd example

### ISSUE THREAD

**Issue by designeng** [webpack/webpack#1966]
```
node build.js
```

Error:

```
code-splitted-require.context-amd (master) $ node build.js
fs.js:584
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '.../webpack/examples/code-splitted-require.context-amd/js/1.output.js'
```

**Comment by leebenson** [comment]
similar:

```
node dist/server.js 
fs.js:584
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/types/mime.types'
    at Error (native)
```

**Comment by leebenson** [comment]
Actually in my case, this could be solved by using the `externals` property in a webpack config, to avoid bundling `node_modules` packages.

```
  const fs = require('fs');

  var nodeModules = {};
  fs.readdirSync('node_modules')
    .filter(function(x) {
      return ['.bin'].indexOf(x) === -1;
    })
    .forEach(function(mod) {
      nodeModules[mod] = 'commonjs ' + mod;
    });

  module.exports = {
    target: 'node',
    externals: nodeModules,
    ....
  }
```

**Comment by afedyk-softserve** [comment]
I've tried *node build.jd* in multiple-entry-points-commons-chunk-css-bundle example folder:

```
module.js:339
    throw err;
    ^

Error: Cannot find module 'webpack/lib/removeAndDo'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)

/Users/.../webpack/examples/build-common.js:23
			throw e;
			^

Error: ENOENT: no such file or directory, open '/Users/.../webpack/examples/multiple-entry-points-commons-chunk-css-bundle/js/B.css'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at /Users/.../webpack/examples/template-common.js:32:13
```

**Comment by bebraw** [comment]
Can you check with webpack 2?

**Comment by arturparkhisenko** [comment]
@bebraw maybe it's connected, I can't run `npm test` on master because of this issue: `Error: Cannot find module 'webpack/lib/removeAndDo'`, I found a description here https://github.com/webpack/webpack/issues/3081#issuecomment-251356860
Webpack@2.2.0-rc.8
