### ISSUE TITLE
Error: Cannot find module 'esprima'

### ISSUE THREAD

**Issue by eiriklv** [webpack/webpack#2015]
I keep getting this error when doing a clean install (`rm -r node_modules/ && npm install`) and then running `webpack` or `./node_modules/webpack/bin/webpack.js`

```
Error: Cannot find module 'esprima'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/eirik/Development/sol/aurora-frontend/node_modules/webpack/lib/Parser.js:5:15)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
```

It doesn't matter if I include `esprima` as an explicit dependency in `package.json` either (which I shouldn't have to do anyway)

The only way I'm able to recover/install successfully is by doing `npm install` twice
 - `rm -r node_modules/ && npm install && npm install`

Any clues..?

It happens both on my local computer and in CI (Codeship)

Edit: I'm using node.js 5.5.0, npm 3.3.12 and webpack 1.12.13

**Comment by eiriklv** [comment]
I also noticed now that `esprima` is listed in `package.json` of webpack, but is not installed on the initial npm install.

**Comment by eiriklv** [comment]
Seems to be related to [this npm issue](https://github.com/npm/npm/issues/10727)

**Comment by bebraw** [comment]
Not much we can do about that here given it's a npm issue. Thanks for bringing this up, though.
