### ISSUE TITLE
module build error with crafted HTML input and UglifyJS

### ISSUE THREAD

**Issue by graingert** [webpack/webpack#2020]
```
ModuleBuildError: Module build failed: 
    at DependenciesBlock.onModuleBuildFailed (/app/fe/webpack-html-fail/node_modules/webpack-core/lib/NormalModuleMixin.js:315:19)
    at nextLoader (/app/fe/webpack-html-fail/node_modules/webpack-core/lib/NormalModuleMixin.js:270:31)
    at /app/fe/webpack-html-fail/node_modules/webpack-core/lib/NormalModuleMixin.js:292:15
    at runSyncOrAsync (/app/fe/webpack-html-fail/node_modules/webpack-core/lib/NormalModuleMixin.js:173:4)
    at nextLoader (/app/fe/webpack-html-fail/node_modules/webpack-core/lib/NormalModuleMixin.js:290:3)
    at /app/fe/webpack-html-fail/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.finished (/app/fe/webpack-html-fail/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at /app/fe/webpack-html-fail/node_modules/enhanced-resolve/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:404:3)
```

Here's the minimal input:
https://github.com/graingert/webpack-html-fail

**Comment by bebraw** [comment]
Can you see this in webpack 2?

**Comment by anchengjian** [comment]
I also had a similar problem
```
Error
    at NormalModule.onModuleBuildFailed (/app/node_modules/webpack-core/lib/NormalModuleMixin.js:315:19)
    at nextLoader (/app/node_modules/webpack-core/lib/NormalModuleMixin.js:270:31)
    at /app/node_modules/webpack-core/lib/NormalModuleMixin.js:292:15
    at runSyncOrAsync (/app/node_modules/webpack-core/lib/NormalModuleMixin.js:173:4)
    at nextLoader (/app/node_modules/webpack-core/lib/NormalModuleMixin.js:290:3)
    at /app/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.finished (/app/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at /app/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:503:3)
```

**Comment by evilebottnawi** [comment]
Not related to `UglifyJS`, just upgrade `html-loader` to latest version (better update `webpack` and other `webpack` stuff too). If you still have a problem please open problem in `html-loader`, thank you! Also you test repo don't reproduce problem.
