### ISSUE TITLE
TypeError: directories.map is not a function

### ISSUE THREAD

**Issue by fsworld009** [webpack/webpack#2242]
Hello, I keep getting this message when trying to test my webpack config:

```
$  webpack
/Users/fsworld009/Program/JTChat2/node_modules/webpack/node_modules/enhanced-resolve/lib/ModulesInDirectoriesPlugin.js:28
			return directories.map(function(d) {
			                   ^

TypeError: directories.map is not a function
    at Tapable.<anonymous> (/Users/fsworld009/Program/JTChat2/node_modules/webpack/node_modules/enhanced-resolve/lib/ModulesInDirectoriesPlugin.js:28:23)
    at Array.map (native)
    at Tapable.<anonymous> (/Users/fsworld009/Program/JTChat2/node_modules/webpack/node_modules/enhanced-resolve/lib/ModulesInDirectoriesPlugin.js:27:21)
    at Tapable.applyPluginsParallelBailResult (/Users/fsworld009/Program/JTChat2/node_modules/webpack/node_modules/tapable/lib/Tapable.js:139:14)
    at Tapable.doResolve (/Users/fsworld009/Program/JTChat2/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:83:15)
    at Tapable.resolve (/Users/fsworld009/Program/JTChat2/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:43:33)
    at Tapable.resolve (/Users/fsworld009/Program/JTChat2/node_modules/webpack/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:23:14)
    at /Users/fsworld009/Program/JTChat2/node_modules/webpack/lib/NormalModuleFactory.js:169:12
    at /Users/fsworld009/Program/JTChat2/node_modules/webpack/node_modules/async/lib/async.js:356:13
    at async.forEachOf.async.eachOf (/Users/fsworld009/Program/JTChat2/node_modules/webpack/node_modules/async/lib/async.js:233:13)
    at _asyncMap (/Users/fsworld009/Program/JTChat2/node_modules/webpack/node_modules/async/lib/async.js:355:9)
    at Object.map (/Users/fsworld009/Program/JTChat2/node_modules/webpack/node_modules/async/lib/async.js:337:20)
    at NormalModuleFactory.resolveRequestArray (/Users/fsworld009/Program/JTChat2/node_modules/webpack/lib/NormalModuleFactory.js:166:8)
    at /Users/fsworld009/Program/JTChat2/node_modules/webpack/node_modules/async/lib/async.js:718:13
    at async.forEachOf.async.eachOf (/Users/fsworld009/Program/JTChat2/node_modules/webpack/node_modules/async/lib/async.js:233:13)
    at _parallel (/Users/fsworld009/Program/JTChat2/node_modules/webpack/node_modules/async/lib/async.js:717:9)
    at Object.async.parallel (/Users/fsworld009/Program/JTChat2/node_modules/webpack/node_modules/async/lib/async.js:731:9)
    at /Users/fsworld009/Program/JTChat2/node_modules/webpack/lib/NormalModuleFactory.js:109:12
    at /Users/fsworld009/Program/JTChat2/node_modules/webpack/node_modules/async/lib/async.js:726:13
    at /Users/fsworld009/Program/JTChat2/node_modules/webpack/node_modules/async/lib/async.js:52:16
    at done (/Users/fsworld009/Program/JTChat2/node_modules/webpack/node_modules/async/lib/async.js:246:17)
    at /Users/fsworld009/Program/JTChat2/node_modules/webpack/node_modules/async/lib/async.js:44:16
    at /Users/fsworld009/Program/JTChat2/node_modules/webpack/node_modules/async/lib/async.js:723:17
    at /Users/fsworld009/Program/JTChat2/node_modules/webpack/node_modules/async/lib/async.js:167:37
    at /Users/fsworld009/Program/JTChat2/node_modules/webpack/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:29:4
    at onResolved (/Users/fsworld009/Program/JTChat2/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:39:10)
    at /Users/fsworld009/Program/JTChat2/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:123:21
    at /Users/fsworld009/Program/JTChat2/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:191:15
    at applyPluginsParallelBailResult.createInnerCallback.log (/Users/fsworld009/Program/JTChat2/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:104:30)
    at loggingCallbackWrapper (/Users/fsworld009/Program/JTChat2/node_modules/webpack/node_modules/enhanced-resolve/lib/createInnerCallback.js:21:19)
```
I've found out 2 cases to get this error: 
1. require semantic.css in my index.jsx:
`require(".css/semantic.css");`
If I remove this line then I don't get this error.
Here's the link to my [semantic.css](https://github.com/fsworld009/JTChat2/blob/fae9a69a92dde3043008f38f9717e0ef6e46195f/web/css/semantic.css)
2. Have babel-loader in webpack.config.js
This is weird, as I don't see I'm doing anything different from most tutorials.

This is my current webpack.config.js:
```
var path = require('path');

var config = {
    entry: ['webpack/hot/dev-server', path.resolve(__dirname, 'web/index.jsx')],
    output: {
        path: path.resolve(__dirname, 'web/build'),
        publicPath: "web_build/",
        filename: 'bundle.js'
    },
    module: {
        loaders: [
              {
                test: /\.jsx$/,
                loader: 'babel-loader',
                exclude: path.join(__dirname, 'node_modules'),
                query: {
                  presets: ['es2015', 'react']
                }
            },
            { test: /\.css$/, loader: 'style-loader!css-loader' },
            { test: /\.(png|jpg)$/, loader: 'url-loader?limit=8192' } // inline base64 URLs for <=8k images, direct URLs for the rest
        ]
    },
    resolveLoader: {
        modulesDirectories: path.join(__dirname, 'node_modules')
    }
};

module.exports=config;
```
If I comment out babel-loader and not requiring semantic.css, then I don't get the error. Any response will be appreciated, thanks!

**Comment by fsworld009** [comment]
Manually upgrading enhanced-resolve package to the latest (2.2.2) doesn't solve the issue.

**Comment by fsworld009** [comment]
Manually upgrading enhanced-resolve will producing module not found error, so I assume webpack needs older versions (0.9.x) of enhanced-resolve.

I went to ModulesInDirectoriesPlugin.js and put a console.log there, it shows "directories" is a string
"/Users/fsworld009/Program/JTChat2/node_modules" not an Array.

Then I found out that resolveLoader.modulesDirectories should be an array, so it is resolved after I changed the resolveLoader part:

```
resolveLoader: {
        modulesDirectories: [path.join(__dirname, 'node_modules')]
    }
```

There is no bug, it's just my config error. But maybe you could consider to do a type check before processing the config files so that newbies like me can get a clue.
