### ISSUE TITLE
When use UglifyJS/CSS-loader: ERROR in missing path

### ISSUE THREAD

**Issue by jjalonso** [webpack/webpack#2252]
(Similar https://github.com/webpack/css-loader/issues/245)

Hello guys, I think that this is a bug or maybe is my ignorance, but I cannot found even the error message in Google.

basically my problem is with UglifyJS and CSS/SASS, If I take out the CSS/SASS is bundling and minifying fine but impossible to do it with CSS.

This is my Bundle. (I tried to reduce max possible)
```

var webpack = require('webpack');
var HtmlWebpackPlugin = require('html-webpack-plugin');
var ExtractTextPlugin = require('extract-text-webpack-plugin');
var path = require('path');

module.exports = {
  context: __dirname,
  resolve: {
    modulesDirectories: ['node_modules', 'bower_components']
  },
  entry: {
    'all': [
      './app/global-all.js',
      // './app/scss/global-all.scss'
    ],
  },
  output: {
    path: path.join(__dirname, 'dist'),
    filename: 'js/global.[name].js',
  },
  module: {
    loaders: [
      {
        test: /\.scss$/,
        loader: ExtractTextPlugin.extract('css?sourceMap!sass?sourceMap!')
      },
    ],
  },
  plugins: [
    new ExtractTextPlugin('css/global.[name].css'),
    new webpack.optimize.UglifyJsPlugin(),
	]
};
```

The error is: 
```

Hash: a5d1b7ea70835eafc4e5
Version: webpack 1.12.14
Time: 3351ms
           Asset    Size  Chunks             Chunk Names
js/global.all.js  144 kB       0  [emitted]  all
   [0] multi all 28 bytes {0} [built]
   [1] ./app/global-all.js 1.21 kB {0} [built] [1 error]
  [15] ./app/js/global-header.js 31.7 kB {0} [built]
  [16] ./app/js/global-footer.js 12.5 kB {0} [built]
  [17] ./app/js/plugins.js 4.62 kB {0} [built]
    + 15 hidden modules

WARNING in js/global.all.js from UglifyJs
Condition always true [./~/magnific-popup/dist/jquery.magnific-popup.js:5,0]
...
...
Dropping unused function clear [./app/js/global-header.js:825,0]
Dropping unused variable timer [./app/js/global-header.js:976,0]
Condition always true [./bower_components/ef-mobile-menu/assets/js/main.js:21,5]
Dropping unreachable code [./bower_components/ef-mobile-menu/assets/js/main.js:31,0]
Dropping unused variable name [./bower_components/ef-mobile-menu/assets/js/main.js:40,0]

**ERROR in missing path
 @ ./app/global-all.js 25:0-33**
```

Now my global-all is like this: (And is working when css disabled, and when I changed the entry url to another that doesnt exist return a different error because cannot found it, then IS THERE!)

```
require('magnific-popup');
require('centralefcom-js-library/lib/Polyfills/MixedPolyfills.js');
require('centralefcom-js-library/lib/Polyfills/jQuery.XDomainRequest.js');
require('centralefcom-js-library/lib/Events/PubSub.js');
require('centralefcom-js-library/lib/Utils/AJAXUtils.js');
require('centralefcom-js-library/lib/Utils/CookieUtils.js');
require('centralefcom-js-library/lib/Utils/JSONUtils.js');
require('centralefcom-js-library/lib/Utils/URLUtils.js');
require('centralefcom-js-library/lib/Utils/EFUtils.js');
require('centralefcom-js-library/lib/Geolocation/LatLong.js');
require('centralefcom-js-library/lib/Geolocation/PersonaAPI.js');

require('./js/global-header.js');
require('./js/global-footer.js');
require('./js/plugins.js');
require('../bower_components/ef-mobile-menu/assets/js/main.js');
require('./scss/global-all.scss');
```

I tried also to take out the require .CSS from there and add it to the entry array and output the same. (Really was my first setup).

**Comment by sokra** [comment]
Try `--display-error-details`

**Comment by jjalonso** [comment]
Is returning exactly same output and data, I also add it to stat object in webpack.config and is the same, same amount of details.

By the way I just discovered one thing, nothing better because is also failing but if I pass a first argument to extract() method is returning two differents errors:

Normally if I use:

```
      {
        test: /\.scss$/,
        loader: extractCss.extract('style', 'css!sass!')
      },
```

The error is:

```
...
...
...
Dropping unreachable code [./~/extract-text-webpack-plugin/loader.js?{"omit":1,"extract":true,"remove":true,"id":1}!./~/style-loader!./~/css-loader!./~/sass-loader!!./app/scss/global-header.scss:12,0]
Side effects in initialization of unused variable update [./~/extract-text-webpack-plugin/loader.js?{"omit":1,"extract":true,"remove":true,"id":1}!./~/style-loader!./~/css-loader!./~/sass-loader!!./app/scss/global-header.scss:7,0]

WARNING in js/global.header.nodeps.js from UglifyJs
Side effects in initialization of unused variable isDev [./app/js/global-header.js:36,0]
Side effects in initialization of unused variable logoWidth [./app/js/global-header.js:702,0]
Dropping unused function clear [./app/js/global-header.js:895,0]
Dropping unused variable timer [./app/js/global-header.js:1055,0]
Condition always false [./~/style-loader/addStyles.js:24,0]
Dropping unreachable code [./~/style-loader/addStyles.js:25,0]
Condition always false [./~/extract-text-webpack-plugin/loader.js?{"omit":1,"extract":true,"remove":true,"id":1}!./~/style-loader!./~/css-loader!./~/sass-loader!!./app/scss/global-header-nodeps.scss:10,0]
Dropping unreachable code [./~/extract-text-webpack-plugin/loader.js?{"omit":1,"extract":true,"remove":true,"id":1}!./~/style-loader!./~/css-loader!./~/sass-loader!!./app/scss/global-header-nodeps.scss:12,0]
Side effects in initialization of unused variable update [./~/extract-text-webpack-plugin/loader.js?{"omit":1,"extract":true,"remove":true,"id":1}!./~/style-loader!./~/css-loader!./~/sass-loader!!./app/scss/global-header-nodeps.scss:7,0]


Child extract-text-webpack-plugin:
        + 1 hidden modules
    
    ERROR in ./~/css-loader!./~/sass-loader!./app/scss/global-header.scss
    Module build failed: TypeError: Cannot read property '4' of undefined
        at reduce (/Users/contractor/centralefcom-global-components/node_modules/postcss-reduce-transforms/dist/index.js:121:23)
        at walk (/Users/contractor/centralefcom-global-components/node_modules/postcss-value-parser/lib/walk.js:7:22)
        at ValueParser.walk (/Users/contractor/centralefcom-global-components/node_modules/postcss-value-parser/lib/index.js:18:5)
        at /Users/contractor/centralefcom-global-components/node_modules/postcss-reduce-transforms/dist/index.js:131:75
        at /Users/contractor/centralefcom-global-components/node_modules/postcss/lib/container.js:92:28
        at /Users/contractor/centralefcom-global-components/node_modules/postcss/lib/container.js:73:26
        at Rule.each (/Users/contractor/centralefcom-global-components/node_modules/postcss/lib/container.js:60:22)
        at Rule.walk (/Users/contractor/centralefcom-global-components/node_modules/postcss/lib/container.js:72:21)
        at /Users/contractor/centralefcom-global-components/node_modules/postcss/lib/container.js:75:32
        at Root.each (/Users/contractor/centralefcom-global-components/node_modules/postcss/lib/container.js:60:22)
        at Root.walk (/Users/contractor/centralefcom-global-components/node_modules/postcss/lib/container.js:72:21)
        at Root.walkDecls (/Users/contractor/centralefcom-global-components/node_modules/postcss/lib/container.js:90:25)
        at /Users/contractor/centralefcom-global-components/node_modules/postcss-reduce-transforms/dist/index.js:130:13
        at LazyResult.run (/Users/contractor/centralefcom-global-components/node_modules/postcss/lib/lazy-result.js:206:20)
        at /Users/contractor/centralefcom-global-components/node_modules/postcss/lib/lazy-result.js:120:37
        at LazyResult.asyncTick (/Users/contractor/centralefcom-global-components/node_modules/postcss/lib/lazy-result.js:134:15)
        at /Users/contractor/centralefcom-global-components/node_modules/postcss/lib/lazy-result.js:125:31
```


But if I use only:

```
      {
        test: /\.scss$/,
        loader: extractCss.extract('css!sass!')
      },
```

I get the previus errors:
```
...
...
...
Condition always true [./bower_components/centralefcom-js-library/lib/Utils/EFUtils.js:17,5]
Dropping unreachable code [./bower_components/centralefcom-js-library/lib/Utils/EFUtils.js:27,0]
Condition always true [./bower_components/centralefcom-js-library/lib/Geolocation/LatLong.js:24,5]
Dropping unreachable code [./bower_components/centralefcom-js-library/lib/Geolocation/LatLong.js:34,0]
Condition always true [./bower_components/centralefcom-js-library/lib/Geolocation/PersonaAPI.js:25,5]
Dropping unreachable code [./bower_components/centralefcom-js-library/lib/Geolocation/PersonaAPI.js:35,0]
Boolean expression always true [./bower_components/centralefcom-js-library/lib/Geolocation/PersonaAPI.js:343,0]
Boolean && always false [./bower_components/centralefcom-js-library/lib/Geolocation/PersonaAPI.js:343,0]
Dropping unused variable distances [./bower_components/centralefcom-js-library/lib/Geolocation/PersonaAPI.js:350,0]
Side effects in initialization of unused variable isDev [./app/js/global-header.js:36,0]
Side effects in initialization of unused variable logoWidth [./app/js/global-header.js:702,0]
Dropping unused function clear [./app/js/global-header.js:895,0]
Dropping unused variable timer [./app/js/global-header.js:1055,0]

WARNING in js/global.header.nodeps.js from UglifyJs
Side effects in initialization of unused variable isDev [./app/js/global-header.js:36,0]
Side effects in initialization of unused variable logoWidth [./app/js/global-header.js:702,0]
Dropping unused function clear [./app/js/global-header.js:895,0]
Dropping unused variable timer [./app/js/global-header.js:1055,0]

ERROR in missing path
 @ multi all

ERROR in missing path
 @ multi footer

ERROR in missing path
 @ multi header

ERROR in missing path
 @ multi footer.nodeps

ERROR in missing path
 @ multi header.nodeps
```

**Comment by marvinhagemeister** [comment]
I'd love to have a go at this. Do you have a small sample repository where this behaviour can be reproduced?

**Comment by bebraw** [comment]
Closing as there is not enough info (code) to debug.
