### ISSUE TITLE
"Invalid chunkNames argument" in CommonsChunkPlugin, when using UglifyJsPlugin

### ISSUE THREAD

**Issue by smithkl42** [webpack/webpack#2331]
I'm getting an "Invalid chunkNames argument" in my gulp/webpack build task.

```
Error: Invalid chunkNames argument
    at Compilation.<anonymous> (C:\source\swyfft\swyf-website\Swyfft.Web\node_modules\webpack\lib\optimize\CommonsChunkPlugin.js:65:11)
    at Compilation.applyPlugins (C:\source\swyfft\swyf-website\Swyfft.Web\node_modules\tapable\lib\Tapable.js:26:37)
    at Compilation.seal (C:\source\swyfft\swyf-website\Swyfft.Web\node_modules\webpack\lib\Compilation.js:522:7)
    at Compiler.<anonymous> (C:\source\swyfft\swyf-website\Swyfft.Web\node_modules\webpack\lib\Compiler.js:397:15)
    at C:\source\swyfft\swyf-website\Swyfft.Web\node_modules\tapable\lib\Tapable.js:103:11
    at Compilation.<anonymous> (C:\source\swyfft\swyf-website\Swyfft.Web\node_modules\webpack\lib\Compilation.js:445:10)
    at C:\source\swyfft\swyf-website\Swyfft.Web\node_modules\webpack\lib\Compilation.js:417:12
Process terminated with code 8.
    at C:\source\swyfft\swyf-website\Swyfft.Web\node_modules\webpack\lib\Compilation.js:332:10
    at C:\source\swyfft\swyf-website\Swyfft.Web\node_modules\async\lib\async.js:52:16
    at done (C:\source\swyfft\swyf-website\Swyfft.Web\node_modules\async\lib\async.js:246:17)
```

Here's the actual task:

```
gulp.task("min:js", function () {
    gulp.src('./App/App.ts')
        .pipe(webpack({
            entry: {
                address: './App/Address.ts',
                confirmation: './App/Confirmation.ts',
                contact: './App/Contact.ts',
                crm: './App/Crm.ts',
                error: './App/Error.ts',
                history: './App/History.ts',
                login: './App/Login.ts',
                map: './App/Map.ts',
                purchase: './App/Purchase.ts',
                scratch: './App/Scratch.ts',
                quote: './App/Quote.ts',
                agentPage: './App/AgentPage.tsx',
                imsQueuePage: './App/ImsQueuePage.tsx'
            },
            output: {
                filename: '[name].bundle.js'
            },
            resolve: {
                // Add `.ts` and `.tsx` as resolvable extensions.
                extensions: ['', '.webpack.js', '.web.js', '.ts', '.tsx', '.js']
            },
            module: {
                loaders: [
                  // all files with a `.ts` or `.tsx` extension will be handled by `ts-loader`
                  { test: /\.tsx?$/, loader: 'ts-loader' }
                ]
            },
            plugins: [
                new UglifyJsPlugin({
                    sourceMap:true
                }),
                new CommonsChunkPlugin({
                    name: "commons",
                    minChunks: 2
                })
            ],
            devtool: 'source-map'
        }))
        .pipe(gulp.dest("./App/"));
});
```

What's odd is that the error is clearly in the CommonsChunkPlugin, but it goes away if I remove the UglifyJsPlugin:

```
                // new UglifyJsPlugin({
                //    sourceMap:true
                // }),
```

Any ideas? (I should note that it also happens if I run webpack directly, without gulp, using the equivalent webpack.config.js file.)

**Comment by marvinhagemeister** [comment]
Did you try switching the order of the plugins? I'd guess that since plugins are defined as an array that webpack executes them in the order they were defined. Perhaps the CommonsChunkPlugin has trouble dealing with minified code. This is just I wild guess though (I haven't checked with webpacks source code).

If that's not the case I'd imagine that devs can better help you when you set up a quick sample repository where the bug can be reproduced easily.

**Comment by smithkl42** [comment]
Yeah, I tried them in both orders. The problem showed up whether the UglifyJsPlugin() was listed first or second.
