### ISSUE TITLE
Webpack 2 default object export with object constructing shortcuts fails to compile

### ISSUE THREAD

**Issue by calebmer** [webpack/webpack#2380]
It looks like webpack 2 fails to compile exports in the following format: `export { a, b, c }` correctly. Here are some steps to reproduce this error:

## Dependencies

```bash
$ npm install --save-dev webpack@2.1.0-beta.5 lodash-es@4.11.1
```

## `webpack.config.js`

```js
module.exports = {
  entry: './index.js',
  output: {
    path: process.cwd(),
    filename: './index.output.js',
  },
}
```

## `index.js`

```js
import { camelCase } from 'lodash-es'

console.log(camelCase('hello world'))
```

## Test

```bash
$ webpack
$ node index.output.js
```

## Error

```
/~/index.output.js:23873
	  /* harmony import */__WEBPACK_IMPORTED_MODULE_0__chunk__["a"], /* harmony import */__WEBPACK_IMPORTED_MODULE_1__compact__["a"], /* harmony import */__WEBPACK_IMPORTED_MODULE_2__concat__["a"], /* harmony import */__WEBPACK_IMPORTED_MODULE_3__difference__["a"], /* harmony import */__WEBPACK_IMPORTED_MODULE_4__differenceBy__["a"],
	                                                          ^

SyntaxError: Unexpected token [
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:136:18)
    at node.js:972:3
```

* * *

Why does this happen? The compiled code shown in the stack trace comes from `lodash-es/array.default.js`, that code looks like the following:

```js
import chunk from './chunk';
import compact from './compact';
import concat from './concat';
import difference from './difference';
…

export default {
  chunk, compact, concat, difference, …
};
```

Webpack builds this to roughly the following (removing some of the `__WEBPACK_IMPORTED_MOUDLE__`… cruft):

```js
exports["a"] = {
  chunk["a"], compact["a"], concat["a"], difference["a"], …
};
```

**Comment by calebmer** [comment]
This might actually be a babel error…

**Comment by calebmer** [comment]
Nevermind, this is a misunderstanding on my part of how `lodash-es` works.
