### ISSUE TITLE
WebPacked node.js MDNS app missing module after packing.

### ISSUE THREAD

**Issue by TekSiDoT** [webpack/webpack#2406]
_From @TekSiDoT on April 27, 2016 12:20_

The (very basic) app follows the local tutorial and works fine after transpiling from Typescript to .js as standalone app.

Source:
```
/// <reference path='../typings/node.d.ts' />
/// <reference path='../typings/browser/ambient/mdns/index.d.ts' />

import mdns = require('mdns');

export default function main():void {
let ad = mdns.createAdvertisement(mdns.tcp('http'), 4322)
ad.start();    

let browser = mdns.createBrowser(mdns.tcp('http'));

browser.on('serviceUp', function(service) {
  console.log("service up: ", service);
});
browser.on('serviceDown', function(service) {
  console.log("service down: ", service);
});
browser.start();
}
main();
```

Webpack config:

```
var CopyWebpackPlugin = require('copy-webpack-plugin');
var CleanWebpackPlugin = require('clean-webpack-plugin');
const webpack = require('webpack');

module.exports = {
  entry: './src/app.ts',
  output: {
    filename: './dist/lib/PAKvhc.js'
  },
  target: "node",
  resolve: {
    extensions: ['', '.webpack.js', '.web.js', '.ts', '.js', '.node']
  },
  module: {
    loaders: [
      { test: /\.ts$/, loader: 'ts-loader' },
      { test: /\.node$/, loader: 'node-loader' }
    ]
  },
  node: {
      tls: 'empty',
      fs: 'empty'
    },
    plugins: [
        new CleanWebpackPlugin(['dist'], {
            verbose: true, 
            dry: false
        }),
        new webpack.optimize.UglifyJsPlugin({
            compress: {
                warnings: false
            },
            comments: false,
            sourceMap: false
        }),                
        new CopyWebpackPlugin([
            { from: 'src/dist', to: 'dist' },
        ])
    ]    
}
```

Node-mdns succesfully compiles using node-gyp, webpack itself throws a warning during its run:

```
clean-webpack-plugin: D:\git\PAKmagellan\dist has been removed.
ts-loader: Using typescript@1.8.10 and D:\git\PAKmagellan\tsconfig.json
Hash: ebcb42357b35fff3155d
Version: webpack 1.13.0
Time: 1397ms
                            Asset       Size  Chunks             Chunk Names
             ./dist/lib/PAKvhc.js    13.6 kB       0  [emitted]  main
                 dist\config.json  130 bytes          [emitted]
               dist\node\node.exe    14.3 MB          [emitted]
               dist\node\node.lib     625 kB          [emitted]
dist\licenses\node.js\LICENSE.txt    54.6 kB          [emitted]
         dist\licenses\ws\license    1.36 kB          [emitted]
     dist\licenses\xmldom\LICENSE  143 bytes          [emitted]
    + 17 hidden modules

WARNING in ./~/mdns/lib/dns_sd.js
Critical dependencies:
24:19-46 the request of a dependency is an expression
32:21-50 the request of a dependency is an expression
 @ ./~/mdns/lib/dns_sd.js 24:19-46 32:21-50
```

Running the bundled causes the following error:
```
.\node\node .\lib\PAKvhc.js
D:\git\PAKmagellan\dist\lib\PAKvhc.js:187
                return map[req] || (function() { throw new Error("Cannot find module '" + req + "'.") }());
                                                 ^

Error: Cannot find module '..\build\Release\dns_sd_bindings'.
    at D:\git\PAKmagellan\dist\lib\PAKvhc.js:187:42
    at webpackContextResolve (D:\git\PAKmagellan\dist\lib\PAKvhc.js:187:90)
    at webpackContext (D:\git\PAKmagellan\dist\lib\PAKvhc.js:184:30)
    at Object.<anonymous> (D:\git\PAKmagellan\dist\lib\PAKvhc.js:143:45)
    at __webpack_require__ (D:\git\PAKmagellan\dist\lib\PAKvhc.js:20:30)
    at Object.<anonymous> (D:\git\PAKmagellan\dist\lib\PAKvhc.js:74:16)
    at __webpack_require__ (D:\git\PAKmagellan\dist\lib\PAKvhc.js:20:30)
    at Object.<anonymous> (D:\git\PAKmagellan\dist\lib\PAKvhc.js:52:13)
    at __webpack_require__ (D:\git\PAKmagellan\dist\lib\PAKvhc.js:20:30)
    at D:\git\PAKmagellan\dist\lib\PAKvhc.js:40:18
```

I've unsuccesfully tried numerous combinations of combining webpack and the built version with different folder structures.

_Copied from original issue: agnat/node_mdns#162_

**Comment by TekSiDoT** [comment]
_From @agnat on April 27, 2016 21:23_

Since mdns works fine in a vanilla node environment I suspect this is a webpack issue. I don't know webpack, so I'm not much help in debugging this... I'm afraid.

**Comment by sokra** [comment]
`mdns` is a native module. You need to use the `externals` option to exclude it from the bundle provide the npm installed module in the target environment
