### ISSUE TITLE
NaN error in Tappable#applyPluginsAsync

### ISSUE THREAD

**Issue by zkat** [webpack/webpack#243]
I'm not entirely sure what exactly triggered this in a project. I'm using `optimize-chunks-assets` and sometimes I get the following error:

```
/Users/stancarrico/WebstormProjects/piano/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:149
                throw e;
                      ^
TypeError: Cannot call method 'apply' of undefined
    at Tapable.next (/Users/stancarrico/WebstormProjects/piano/node_modules/webpack/node_modules/tapable/lib/Tapable.js:59:37)
    at /Users/stancarrico/WebstormProjects/piano/node_modules/webpack-less-asset-plugin/index.js:38:7
    at /Users/stancarrico/WebstormProjects/piano/node_modules/less/lib/less/index.js:29:17
    at Object.finish [as _finish] (/Users/stancarrico/WebstormProjects/piano/node_modules/less/lib/less/parser.js:669:28)
    at Object.tree.importVisitor.run (/Users/stancarrico/WebstormProjects/piano/node_modules/less/lib/less/import-visitor.js:34:22)
    at Object.Parser.parser.parse (/Users/stancarrico/WebstormProjects/piano/node_modules/less/lib/less/parser.js:675:22)
    at Object.less.render (/Users/stancarrico/WebstormProjects/piano/node_modules/less/lib/less/index.js:22:20)
    at /Users/stancarrico/WebstormProjects/piano/node_modules/webpack-less-asset-plugin/index.js:33:10
    at Array.forEach (native)
    at Tapable.<anonymous> (/Users/stancarrico/WebstormProjects/piano/node_modules/webpack-less-asset-plugin/index.js:23:11)
```

It looks like there's some issue where `this._currentPluginApply` is undefined when `this.currentPluginApply++` is called.

**Comment by andreypopp** [comment]
This is an issue for me with the following plugin:
```
import fs from 'fs';
import path from 'path';
import debug from 'debug';
import webpack from 'webpack';
import Promise from 'bluebird';
import findParentDir from 'find-parent-dir';
import escapeRegexp from 'escape-regexp';
import nodeCallbackAdapter from './node-callback-adapter';

let findParentDirPromise = Promise.promisify(findParentDir);
let readFilePromise = Promise.promisify(fs.readFile);

let log = debug('webpack-package-loaders-plugin');

/**
 * Coerce a string into a regexp.
 */
function asRegExp(maybeRegexp) {
  if (typeof maybeRegexp === 'string') {
    let src = escapeRegexp(maybeRegexp) + '$';
    if (src[0] !== '.') {
      src = '.' + src;
    }
    return new RegExp(src);
  } else {
    return maybeRegexp;
  }
}

function parsePackageData(src) {
  let data = JSON.parse(src);
  if (data.webpack && data.webpack.loaders) {
    data.webpack.loaders.forEach(loader => {
      if (typeof loader.loader === 'string') {
        loader.test = asRegExp(loader.test);
      }
    });
  }
  return data;
}

export default class PackageLoadersPlugin {

  constructor(packageFilename = 'package.json') {
    this.packageFilename = packageFilename;
    this._packagesByDirectory = {};
    this._packageDirectoriesByDirectory = {};
  }

  apply(compiler) {
    compiler.plugin('normal-module-factory', factory =>
      factory.plugin('after-resolve', (data, callback) =>
        this.onAfterResolve(compiler, factory, data, callback)));
  }

  @nodeCallbackAdapter
  async onAfterResolve(compiler, factory, data) {
    log(`processing ${data.resource} resource`);
    let resolveLoader = Promise.promisify(compiler.resolvers.loader.resolve);
    let packageData = await this.findPackageForResource(data.resource);
    if (packageData && packageData.webpack && packageData.webpack.loaders) {
      let loaders = await Promise.all(packageData.webpack.loaders
        .filter(loader => loader.test.test(data.resource))
        .map(loader => resolveLoader(path.dirname(data.resource), loader.loader)));
      log(`adding ${loaders} loaders for ${data.resource} resource`);
      data = {...data, loaders: data.loaders.concat(loaders)};
    }
    return data;
  }

  /**
   * Find a package metadata for a specified resource.
   */
  async findPackageForResource(resource) {
    let dirname = path.dirname(resource);
    if (this._packageDirectoriesByDirectory[dirname] === undefined) {
      log(`finding package directory for ${dirname}`);
      // TODO: We are not using caching fs here.
      this._packageDirectoriesByDirectory[dirname] = findParentDirPromise(dirname, this.packageFilename);
    }
    let packageDirname = await this._packageDirectoriesByDirectory[dirname];
    if (!packageDirname) {
      log(`no package metadata found for ${resource} resource`);
      return null;
    }
    if (this._packagesByDirectory[packageDirname] === undefined) {
      this._packagesByDirectory[packageDirname] = Promise.try(async () => {
        log(`reading package data for ${packageDirname}`);
        let packageFilename = path.join(packageDirname, this.packageFilename);
        // TODO: We are not using caching fs here.
        let packageSource = await readFilePromise(packageFilename, 'utf8');
        return parsePackageData(packageSource);
      });
    }
    let packageData = await this._packagesByDirectory[packageDirname];
    return packageData;
  }
}
```

**Comment by andreypopp** [comment]
It seems that when `Compilation` calls `moduleFactory.create` it doesn't wait for completion before calling the same method with different arguments. That way I get race condition because in case I have plugins on `after-resolve` it will interleave increments to `this._currentPluginApply`.

The relevant logging from tappable:
```
start "after-resolve" for /Users/andreypopp/Workspace/webpack-package-loaders-plugin/example/index.js
return from plugin 0 null /Users/andreypopp/Workspace/webpack-package-loaders-plugin/example/index.js
return from plugin pipeline 1 undefined
start "after-resolve" for /Users/andreypopp/Workspace/webpack-package-loaders-plugin/example/node_modules/dep/index.js
start "after-resolve" for /Users/andreypopp/Workspace/webpack-package-loaders-plugin/example/node_modules/dep/same.js
return from plugin 0 null /Users/andreypopp/Workspace/webpack-package-loaders-plugin/example/node_modules/dep/index.js
return from plugin pipeline 1 undefined
return from plugin undefined null /Users/andreypopp/Workspace/webpack-package-loaders-plugin/example/node_modules/dep/same.js
/Users/andreypopp/Workspace/webpack-package-loaders-plugin/node_modules/bluebird/js/main/async.js:43
        fn = function () { throw arg; };
                                 ^
TypeError: Cannot read property 'call' of undefined
    at Tapable.<anonymous> (/Users/andreypopp/Workspace/webpack-package-loaders-plugin/node_modules/webpack/node_modules/tapable/lib/Tapable.js:91:36)
    at tryCatcher (/Users/andreypopp/Workspace/webpack-package-loaders-plugin/node_modules/bluebird/js/main/util.js:24:31)
    at Promise.successAdapter (/Users/andreypopp/Workspace/webpack-package-loaders-plugin/node_modules/bluebird/js/main/nodeify.js:22:30)
    at Promise._settlePromiseAt (/Users/andreypopp/Workspace/webpack-package-loaders-plugin/node_modules/bluebird/js/main/promise.js:528:21)
    at Promise._settlePromises (/Users/andreypopp/Workspace/webpack-package-loaders-plugin/node_modules/bluebird/js/main/promise.js:646:14)
    at Async._drainQueue (/Users/andreypopp/Workspace/webpack-package-loaders-plugin/node_modules/bluebird/js/main/async.js:175:16)
    at Async._drainQueues (/Users/andreypopp/Workspace/webpack-package-loaders-plugin/node_modules/bluebird/js/main/async.js:185:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/andreypopp/Workspace/webpack-package-loaders-plugin/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:358:17)
```
