### ISSUE TITLE
webpack@2 and --env.dev: TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by MoOx** [webpack/webpack#2458]
I am trying to use this new feature (found here https://gist.github.com/sokra/27b24881210b56bbaff7#configuration)

```
$ webpack-dev-server --inline --open --hot --env.dev

.../webpack.config.babel.js:29
function _toConsumableArray(arr) { if (Array.isArray(arr)) { for (var i = 0, arr2 = Array(arr.length); i < arr.length; i++) { arr2[i] = arr[i]; } return arr2; } else { return Array.from(arr); } }
                                                                                                                                                                                     ^

TypeError: Cannot convert undefined or null to object
    at Function.from (native)
    at _toConsumableArray (webpack.config.babel.js:7:1)
    at _default (webpack.config.babel.js:64:3)
    at module.exports (.../node_modules/webpack/bin/convert-argv.js:103:13)
    at Object.<anonymous> (.../node_modules/webpack-dev-server/bin/webpack-dev-server.js:115:48)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:148:18)
    at node.js:405:3
```

**Comment by sokra** [comment]
Could you add your configuration file. At least the `export default function ...` part.

**Comment by MoOx** [comment]
Here is my full webpack config

```js
import { join, resolve } from "path"
import { readdirSync } from "fs"

import { HotModuleReplacementPlugin } from "webpack"
import WebpackNotifierPlugin from "webpack-notifier"

import uiKitWebpackConfig from "XXXX-ui-kit/app/webpack.config.js"
import HtmlWebpackPlugin from "html-webpack-plugin"

const UIKit = resolve(__dirname, "node_modules/XXXX-ui-kit")
const UIKitOrigin = resolve(__dirname, "../../uikit.react.web")
const include = [
  // UIKit,
  // resolve(UIKitOrigin, "app/web_modules"),
  resolve(__dirname, "web_modules"),
  resolve(__dirname, "package.json"),
]

import pkg from "./package.json"

const defaultEnv = {
  dev: true,
  production: false,
}

const entriesDir = join("web_modules", "_entries")
const entries = readdirSync(entriesDir)

export default (env = defaultEnv) => ({
  resolve: {
    alias: {
      // react-native-web
      "react-native": resolve(__dirname, "node_modules/react-native-web"),

      // force local deps
      "react": resolve(__dirname, "node_modules/react"),
      "react-router": resolve(__dirname, "node_modules/react-router"),
    },
  },
  module: {
    loaders: [
      // add XXXX-ui-kit
      // and allows XXXX-ui-kit to be linked
      ...uiKitWebpackConfig.module.loaders.map((loader) => ({ ...loader,
        include: Array.isArray(loader.include)
          ? [ ...loader.include, ...loader.include.map((path) =>
            path.replace(UIKit, UIKitOrigin)
          ) ]
          : [ loader.include, loader.include.replace(UIKit, UIKitOrigin) ],
      })),

      { test: /\.json$/, loader: "json-loader" },
      {
        test: /\.js$/,
        loaders: [
          {
            loader: "babel-loader",
            query: {
              cacheDirectory: true,
              babelrc: false,
              ...pkg.babel,
              presets: pkg.babel.presets.map((p) => p.replace(
                "babel-preset-es2015", "babel-preset-es2015-native-modules"
              )),
            },
          },
          "eslint-loader?emitWarning=true",
        ],
        include,
      },
      {
        test: /\.svg$/,
        loader: "raw-loader",
        include,
      },
    ],
  },

  plugins: [
    // generate a html for each entries
    ...entries.map((entry) => new HtmlWebpackPlugin({
      template: join(__dirname, entriesDir, entry, "index.html"),
      // chunks: [ entry ],
      // exlude entires, so we can use common chunks
      excludeChunks: entries.filter((e) => e !== entry),
    })),

    ...env.dev && [
      new WebpackNotifierPlugin(),
      new HotModuleReplacementPlugin(),
    ],

    ...env.production && [
      // @todo ?
    ],
  ],

  ...env.dev && {
    devtool: "#cheap-module-eval-source-map",
  },

  devServer: {
    hot: env.dev,

    historyApiFallback: true,

    // hide all chunk dependencies because it's unreadable
    stats: { chunkModules: false, assets: false },
  },

  output: {
    // publicPath has to be defined so HtmlWebpackPlugin serve correct js
    // in script tags
    // (because historyApiFallback will root things like /a/b to the index.html,
    // and script tag need a absolute url for the script)
    publicPath: "/",

    path: "dist",
    filename: "[name].[hash].js",
  },

  entry: {
    ...entries.reduce((list, entry) => ({
      ...list, [entry]: [
        ...env.dev
          ? [
            // "webpack-dev-server/client?http://localhost:8080/",
            "webpack/hot/dev-server",
          ] : [],
        join(__dirname, entriesDir, entry, "index.js"),
      ],
    }), {}),
  },
})
```

**Comment by MoOx** [comment]
So my bad, it's because of trying to use this `...env.production && [` to merge plugins.

**Comment by sokra** [comment]
I checked the spec and it's correct that this is not supported. But you could do this:

``` js
...env.production && [
  // ...
] || []
// or
...env.production ? [
  // ...
] : []
```

**Comment by MoOx** [comment]
Indeed, that's what I am doing! Thanks.
