### ISSUE TITLE
Module build failed: SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by jwaldrip** [webpack/webpack#2480]
I am getting the following error when trying to run webpack via the command line. It works fine when using the development middleware.

```
ERROR in ./app/app.jsx
Module build failed: SyntaxError: Unexpected token import
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at /Users/jwaldrip/dev/src/github.com/brandfolder/RiNo/node_modules/babel-core/lib/transformation/file/options/option-manager.js:191:20
    at Array.map (native)
    at Function.normalisePlugins (/Users/jwaldrip/dev/src/github.com/brandfolder/RiNo/node_modules/babel-core/lib/transformation/file/options/option-manager.js:173:20)
    at OptionManager.mergeOptions (/Users/jwaldrip/dev/src/github.com/brandfolder/RiNo/node_modules/babel-core/lib/transformation/file/options/option-manager.js:271:36)
    at OptionManager.addConfig (/Users/jwaldrip/dev/src/github.com/brandfolder/RiNo/node_modules/babel-core/lib/transformation/file/options/option-manager.js:221:10)
    at OptionManager.findConfigs (/Users/jwaldrip/dev/src/github.com/brandfolder/RiNo/node_modules/babel-core/lib/transformation/file/options/option-manager.js:364:16)
    at OptionManager.init (/Users/jwaldrip/dev/src/github.com/brandfolder/RiNo/node_modules/babel-core/lib/transformation/file/options/option-manager.js:412:12)
    at File.initOptions (/Users/jwaldrip/dev/src/github.com/brandfolder/RiNo/node_modules/babel-core/lib/transformation/file/index.js:191:75)
    at new File (/Users/jwaldrip/dev/src/github.com/brandfolder/RiNo/node_modules/babel-core/lib/transformation/file/index.js:122:22)
    at Pipeline.transform (/Users/jwaldrip/dev/src/github.com/brandfolder/RiNo/node_modules/babel-core/lib/transformation/pipeline.js:42:16)
    at transpile (/Users/jwaldrip/dev/src/github.com/brandfolder/RiNo/node_modules/babel-loader/index.js:14:22)
    at Object.module.exports (/Users/jwaldrip/dev/src/github.com/brandfolder/RiNo/node_modules/babel-loader/index.js:88:12)
 @ multi main
```

My web-pack config looks like:

```es6
'use strict';
const autoprefixer = require('autoprefixer');
const path = require('path');

module.exports = {
  context: __dirname,
  cache: false,
  entry: [
    'bootstrap-loader',
    './app/assets/main.scss',
    './app/app.jsx'
  ],
  devtool: 'source-map',
  output: {
    publicPath: '/',
    path: path.join(__dirname, './public/assets'),
    filename: 'app.js',
  },
  resolve: {
    extensions: [ '', '.js', '.jsx', '.es6' ]
  },
  postcss: [ autoprefixer({ browsers: [ 'last 2 versions' ] }) ],
  sassLoader: {
    includePaths: [ path.resolve(__dirname, './node_modules') ]
  },
  module: {
    loaders: [
      {
        test: /\.(js|jsx|es6)$/,
        exclude: /node_modules/,
        loader: 'babel',
      },
      {
        test: /\.(scss|css)$/,
        loader: `style!css!sass!import-glob!postcss`
      },
      {
        test: /\.pattern$/,
        loader: 'glob'
      },
      {
        test: /\.(gif|jpe?g|png)/,
        loader: 'url?limit=1000&mimetype=image/gif'
      },
      {
        test: /\.woff2?(\?v=[0-9]\.[0-9]\.[0-9])?$/,
        loader: 'url?limit=10000'
      },
      {
        test: /\.(ttf|eot|svg)(\?[\s\S]+)?$/,
        loader: 'file'
      },
      { test: /bootstrap-sass\/assets\/javascripts\//, loader: 'imports?jQuery=jquery' }
    ]
  }
};
```

And my .babelrc

```json
{
    "sourceMaps": true,
    "presets": ["es2015", "react", "stage-0"],
    "plugins": [
      "transform-react-jsx",
      "./build/babelRelayPlugin",
      "transform-inline-environment-variables"
    ]
}
```

**Comment by jwaldrip** [comment]
This had to do with my babel plugin being in es6.
