### ISSUE TITLE
Weird behaviour with webpack with npm3

### ISSUE THREAD

**Issue by nixgadget** [webpack/webpack#2508]
Using npm@3.8.6, node@v6.1.0

I have multiple projects that is dependent on one on the other.

For example,
`projectA` dependant on the `projectB`

`projectB` has a webpack.config as below.

```
var path = require('path'),
    nodeExternals = require('webpack-node-externals'),
    process = require('process'),
    webpack = require('webpack'),
    fs = require('fs'),
    externals = [],
    plugins = [];

// Setup the plugins
// Plugin to optimize the ordering of modules in the bundled script.
plugins.push(new webpack.optimize.OccurrenceOrderPlugin(false));

// Plugin to uglify the code.
if (!process.env.NODE_ENV || process.env.NODE_ENV !== 'development') {
  plugins.push(new webpack.optimize.UglifyJsPlugin({}));
}

plugins.push(new webpack.NoErrorsPlugin());

// Setup the externals
// All node_modules
externals.push(nodeExternals());
module.exports = {
  name: 'Build Server side scripts',
  target: 'node',
  bail: true,
  node: {
    // The following is needed to retain the original behaviour of the __dirname
    // and __filename variables in the compiled scripts. Otherwise, they will
    // become blank as seen from the compiled scripts
    __dirname: false,
    __filename: false
  },
  externals: externals,
  devtool: 'source-map',
  output: {
    libraryTarget: 'commonjs2'
  },
  module: {
    loaders: [{
      test: /\.js$/,
      cacheDirectory: true,
      exclude: /node_modules/,
      loader: 'babel',
      query: {
        presets: ['es2015']
      }
    },
    {
      test: /\.json$/,
      loader: "json-loader"
    }]
  },
  plugins: plugins
};
```

To build `projectB` i use `gulp`

If I now do `npm install projectB` in `projectA`, the problem is I can see that the bundled js contains the `node_modules` from `projectB`. Is there any reason why `externals` isnt working ??

**Comment by nixgadget** [comment]
So doing a bit more investigation on this, If i print out the `context` and `request` with the following,
```
externals: function(context, request, callback) {
  console.log('context = ' + context + ' request = ' + request);
  callback();
}
```

An excerpt of the output is,
```
context = /Volumes/STORAGE/Projects/ProjectA/Core/node_modules/ProjectB/src/middleware request = locale
context = /Volumes/STORAGE/Projects/ProjectA/Core/node_modules/ProjectB/src/middleware request = ./app
context = /Volumes/STORAGE/Projects/ProjectA/Core/node_modules/ProjectB/src/middleware request = ./app.js
context = /Volumes/STORAGE/Projects/ProjectA/Core/node_modules/ProjectB/src/middleware request = ./clientcontext
context = /Volumes/STORAGE/Projects/ProjectA/Core/node_modules/ProjectB/src/middleware request = ./clientcontext.js
context = /Volumes/STORAGE/Projects/ProjectA/Core/node_modules/ProjectB/src/middleware request = ./enforcessl
context = /Volumes/STORAGE/Projects/ProjectA/Core/node_modules/ProjectB/src/middleware request = ./enforcessl.js
context = /Volumes/STORAGE/Projects/ProjectA/Core/node_modules/ProjectB/src/middleware request = ./requestlogger
context = /Volumes/STORAGE/Projects/ProjectA/Core/node_modules/ProjectB/src/middleware request = ./requestlogger.js
context = /Volumes/STORAGE/Projects/ProjectA/Core/node_modules/express request = ./lib/express
context = /Volumes/STORAGE/Projects/ProjectA/Core/node_modules/helmet request = connect
context = /Volumes/STORAGE/Projects/ProjectA/Core/node_modules/helmet request = ./config
context = /Volumes/STORAGE/Projects/ProjectA/Core/node_modules/helmet request = ./lib/values
context = /Volumes/STORAGE/Projects/ProjectA/Core/node_modules/compression request = accepts
context = /Volumes/STORAGE/Projects/ProjectA/Core/node_modules/compression request = bytes
context = /Volumes/STORAGE/Projects/ProjectA/Core/node_modules/compression request = compressible
```

But `webpack-node-externals` uses `request` to figure out if the path has `node_modules` or not as given in [webpack-node-externals#L60](https://github.com/liady/webpack-node-externals/blob/master/index.js#L60). To me this looks like a bug. Any thoughts ?

**Comment by nixgadget** [comment]
Having `var node_modules = fs.readdirSync('node_modules');` within the `webpack.config.js` throws the following error which probably explains why `webpack-node-externals` doesnt work. It doesnt seem to find `node_modules`.

```
[19:22:41] Error: ENOENT: no such file or directory, scandir 'node_modules'
    at Error (native)
    at Object.fs.readdirSync (fs.js:945:18)
    at Object.<anonymous> (/Volumes/STORAGE/Projects/ProjectA/Core/node_modules/ProjectB/webpack.config.js:46:23)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
```

Any help would be appreciated

**Comment by nixgadget** [comment]
Doesnt work as mentioned in issues/839

**Comment by jewetnitg** [comment]
I was able to work around this issue by providing the "modulesDir" option to webpack-node-externals.

The relevant parts from my webpack configuration file:
```
const nodeModulesPath = existsSync("node_modules") 
    ? join(__dirname, "node_modules") 
    : join(__dirname, "..");

module.exports = {
    ...
    externals: [nodeExternals({modulesDir: nodeModulesPath})]
}
```

**Comment by cjo2** [comment]
@jewetnitg  Where are existsSync and join coming from?
