### ISSUE TITLE
The tag table was unable to be supported build for vuejs

### ISSUE THREAD

**Issue by xinshouke** [webpack/webpack#2567]
I plan to build vue demo into my project, but I get the below error while use vue demo component.

------------------------------------------the error--------------------------------------------------------
ERROR in ./~/babel-loader?presets[]=es2015&plugins[]=transform-runtime&comments=false!./~/vue-loader/lib/selector.js?type=script&index=0!./src/components/pms/dashboard.vue
Module build failed: SyntaxError: D:/WorkSpace/YongTai/src/components/pms/dashboard.vue: Unexpected token (2:0)
 script type="text/x-template" id="grid-template">
> 2 | `table>
    | ^
  3 |     <thead>
  4 |     <tr>
  5 |         <th v-for="key in columns"
    at Parser.pp.raise (D:\WorkSpace\YongTai\node_modules\babylon\lib\parser\location.js:22:13)
    at Parser.pp.unexpected (D:\WorkSpace\YongTai\node_modules\babylon\lib\parser\util.js:89:8)
    at Parser.pp.parseExprAtom (D:\WorkSpace\YongTai\node_modules\babylon\lib\parser\expression.js:517:12)
    at Parser.pp.parseExprSubscripts (D:\WorkSpace\YongTai\node_modules\babylon\lib\parser\expression.js:272:19)
    at Parser.pp.parseMaybeUnary (D:\WorkSpace\YongTai\node_modules\babylon\lib\parser\expression.js:252:19)
    at Parser.pp.parseExprOps (D:\WorkSpace\YongTai\node_modules\babylon\lib\parser\expression.js:183:19)
    at Parser.pp.parseMaybeConditional (D:\WorkSpace\YongTai\node_modules\babylon\lib\parser\expression.js:165:19)
    at Parser.pp.parseMaybeAssign (D:\WorkSpace\YongTai\node_modules\babylon\lib\parser\expression.js:128:19)
    at Parser.pp.parseExpression (D:\WorkSpace\YongTai\node_modules\babylon\lib\parser\expression.js:92:19)
    at Parser.pp.parseStatement (D:\WorkSpace\YongTai\node_modules\babylon\lib\parser\statement.js:163:19)
    at Parser.pp.parseBlockBody (D:\WorkSpace\YongTai\node_modules\babylon\lib\parser\statement.js:529:21)
    at Parser.pp.parseTopLevel (D:\WorkSpace\YongTai\node_modules\babylon\lib\parser\statement.js:36:8)
    at Parser.parse (D:\WorkSpace\YongTai\node_modules\babylon\lib\parser\index.js:129:19)
    at parse (D:\WorkSpace\YongTai\node_modules\babylon\lib\index.js:47:47)
    at File.parse (D:\WorkSpace\YongTai\node_modules\babel-core\lib\transformation\file\index.js:540:58)
    at File.parseCode (D:\WorkSpace\YongTai\node_modules\babel-core\lib\transformation\file\index.js:626:20)
    at D:\WorkSpace\YongTai\node_modules\babel-core\lib\transformation\pipeline.js:52:12
    at File.wrap (D:\WorkSpace\YongTai\node_modules\babel-core\lib\transformation\file\index.js:586:16)
    at Pipeline.transform (D:\WorkSpace\YongTai\node_modules\babel-core\lib\transformation\pipeline.js:50:17)
    at transpile (D:\WorkSpace\YongTai\node_modules\babel-loader\index.js:14:22)
    at Object.module.exports (D:\WorkSpace\YongTai\node_modules\babel-loader\index.js:88:12)
 @ ./src/components/pms/dashboard.vue 2:17-189

`
  
----------------------------------------------------------
my webpack config and vue source code were in the attachment

**Comment by bebraw** [comment]
Is this relevant still? Did you try poking the vue folks?
