### ISSUE TITLE
devtool:source-map error webpack - 2

### ISSUE THREAD

**Issue by arshtepe** [webpack/webpack#2679]
**I'm submitting a bug report**

**Webpack version:**
2.1.0-beta.13

**Please tell us about your environment:**
Linux

**Current behavior:**

I have this error only when i use devtool:source-map  and babel 6 together.

<details> 
  <summary>

stack trace</summary>

```
usr/lib/node_modules/webpack/node_modules/source-map/lib/source-map-consumer.js:704
      throw new Error('"' + aSource + '" is not in the SourceMap.');
      ^

Error: "/usr/lib/node_modules/webpack/buildin/module.js" is not in the SourceMap.
    at SourceMapConsumer_sourceContentFor [as sourceContentFor] (/usr/lib/node_modules/webpack/node_modules/source-map/lib/source-map-consumer.js:704:13)
    at /usr/lib/node_modules/webpack/node_modules/source-map/lib/source-node.js:133:40
    at Array.forEach (native)
    at Function.SourceNode_fromStringWithSourceMap [as fromStringWithSourceMap] (/usr/lib/node_modules/webpack/node_modules/source-map/lib/source-node.js:132:32)
    at SourceMapSource.node (/usr/lib/node_modules/webpack/node_modules/webpack-sources/lib/SourceMapSource.js:42:20)
    at ReplaceSource.node (/usr/lib/node_modules/webpack/node_modules/webpack-sources/lib/ReplaceSource.js:66:29)
    at CachedSource.node (/usr/lib/node_modules/webpack/node_modules/webpack-sources/lib/CachedSource.js:12:23)
    at PrefixSource.node (/usr/lib/node_modules/webpack/node_modules/webpack-sources/lib/PrefixSource.js:27:26)
    at /usr/lib/node_modules/webpack/node_modules/webpack-sources/lib/ConcatSource.js:40:49
    at Array.map (native)
    at ConcatSource.node (/usr/lib/node_modules/webpack/node_modules/webpack-sources/lib/ConcatSource.js:39:60)
    at /usr/lib/node_modules/webpack/node_modules/webpack-sources/lib/ConcatSource.js:40:49
    at Array.map (native)
    at ConcatSource.node (/usr/lib/node_modules/webpack/node_modules/webpack-sources/lib/ConcatSource.js:39:60)
    at /usr/lib/node_modules/webpack/node_modules/webpack-sources/lib/ConcatSource.js:40:49
    at Array.map (native)
    at ConcatSource.node (/usr/lib/node_modules/webpack/node_modules/webpack-sources/lib/ConcatSource.js:39:60)
    at /usr/lib/node_modules/webpack/node_modules/webpack-sources/lib/ConcatSource.js:40:49
    at Array.map (native)
    at ConcatSource.node (/usr/lib/node_modules/webpack/node_modules/webpack-sources/lib/ConcatSource.js:39:60)
    at ConcatSource.proto.sourceAndMap (/usr/lib/node_modules/webpack/node_modules/webpack-sources/lib/SourceAndMapMixin.js:28:18)
    at CachedSource.sourceAndMap (/usr/lib/node_modules/webpack/node_modules/webpack-sources/lib/CachedSource.js:51:28)
    at Compilation.<anonymous> (/usr/lib/node_modules/webpack/lib/SourceMapDevToolPlugin.js:57:32)
    at Array.map (native)
    at Compilation.<anonymous> (/usr/lib/node_modules/webpack/lib/SourceMapDevToolPlugin.js:43:84)
    at Array.forEach (native)
    at Compilation.<anonymous> (/usr/lib/node_modules/webpack/lib/SourceMapDevToolPlugin.js:42:11)
    at Compilation.applyPlugins (/usr/lib/node_modules/webpack/node_modules/tapable/lib/Tapable.js:25:14)
    at Compilation.<anonymous> (/usr/lib/node_modules/webpack/lib/Compilation.js:571:10)
    at next (/usr/lib/node_modules/webpack/node_modules/tapable/lib/Tapable.js:81:11)

```

</details> 

``` js
module.exports = {
    entry: {index:"index.js"},
    context: __dirname,
    devtool:"source-map",
    output: {
        filename: distDir
    },
    resolve: {
        descriptionFiles: ["bower.json"],
        mainFields: ["main"],
        extensions: [".js"],
        modules: [
            "bower_components",
            "node_modules",
            path.resolve('.')
        ]
    },
    module: {
        loaders: loaders
    },
    devServer: {
        host: "localhost",
        port: 3001,
        contentBase: "../../scripts-dist"
    }

}
```

.babelrc

``` json
{
  "presets": ["es2015-native-modules"],
  "plugins": ["transform-runtime"],
  "ignore": [
    "node_modules"
  ]
}
```

dependency

``` json
 "babel-core": "^6.9.1",
    "babel-loader": "^6.2.4",
    "babel-preset-es2015-native-modules": "^6.6.0",
    "babel-runtime": "^6.9.2",
"webpack": "2.1.0-beta.13",
```

**Comment by TheLarkInn** [comment]
@hansl came across this while working on angular-cli:  (in webpack@2.1.0-beta.19-21) 

<details>
  <summary>Here is a similar stack trace. It appears if its related to really long file paths in this case.</summary>
```/Users/hans/Sources/angular-cli/node_modules/webpack-sources/node_modules/source-map/lib/source-map-consumer.js:704
      throw new Error('"' + aSource + '" is not in the SourceMap.');
            ^
Error: "/Users/hans/Sources/angular-cli/node_modules/angular2-template-loader/index.js!/private/var/folders/2b/6zp92bqj0fxdm02s1t_ys0_00000gn/T/angular-cli-e2e11685-8883-726dcg.d1adz08uxr/test-project/src/app/app.component.ts" is not in the SourceMap.
    at SourceMapConsumer_sourceContentFor [as sourceContentFor] (/Users/hans/Sources/angular-cli/node_modules/webpack-sources/node_modules/source-map/lib/source-map-consumer.js:704:13)
    at /Users/hans/Sources/angular-cli/node_modules/webpack-sources/node_modules/source-map/lib/source-node.js:133:40
    at Array.forEach (native)
    at Function.SourceNode_fromStringWithSourceMap [as fromStringWithSourceMap] (/Users/hans/Sources/angular-cli/node_modules/webpack-sources/node_modules/source-map/lib/source-node.js:132:32)
    at SourceMapSource.node (/Users/hans/Sources/angular-cli/node_modules/webpack-sources/lib/SourceMapSource.js:42:20)
    at ReplaceSource.node (/Users/hans/Sources/angular-cli/node_modules/webpack-sources/lib/ReplaceSource.js:66:29)
    at CachedSource.node (/Users/hans/Sources/angular-cli/node_modules/webpack-sources/lib/CachedSource.js:12:23)
    at /Users/hans/Sources/angular-cli/node_modules/webpack-sources/lib/ConcatSource.js:40:49
    at Array.map (native)
    at ConcatSource.node (/Users/hans/Sources/angular-cli/node_modules/webpack-sources/lib/ConcatSource.js:39:60)
    at /Users/hans/Sources/angular-cli/node_modules/webpack-sources/lib/ConcatSource.js:40:49
    at Array.map (native)
    at ConcatSource.node (/Users/hans/Sources/angular-cli/node_modules/webpack-sources/lib/ConcatSource.js:39:60)
    at /Users/hans/Sources/angular-cli/node_modules/webpack-sources/lib/ConcatSource.js:40:49
    at Array.map (native)
    at ConcatSource.node (/Users/hans/Sources/angular-cli/node_modules/webpack-sources/lib/ConcatSource.js:39:60)
    at /Users/hans/Sources/angular-cli/node_modules/webpack-sources/lib/ConcatSource.js:40:49
    at Array.map (native)
    at ConcatSource.node (/Users/hans/Sources/angular-cli/node_modules/webpack-sources/lib/ConcatSource.js:39:60)
    at ConcatSource.proto.sourceAndMap (/Users/hans/Sources/angular-cli/node_modules/webpack-sources/lib/SourceAndMapMixin.js:28:18)
    at CachedSource.sourceAndMap (/Users/hans/Sources/angular-cli/node_modules/webpack-sources/lib/CachedSource.js:51:28)
    at Compilation.<anonymous> (/Users/hans/Sources/angular-cli/node_modules/webpack/lib/SourceMapDevToolPlugin.js:57:32)
```</details>

Should we redirect this to mozilla@source-map @sokra ?

**Comment by janusch** [comment]
Hey,
I am experiencing the same error with a symlinked node_modules dir.
I tried some different options and ended up disabling source-maps of the uglifyjsplugin.

Note:
disabling source-maps of webpack and keeping the ones of the uglifyjsplugin would make webpack output files that were huge. e.g. commons.js grows from ~590kb with webpack devtool source-map to 5.87MB is that because it doesn't shake the tree, or how can it be such a difference?

Woould be really nice to get this fixed, now I am without source-maps. In development it works fine though!
