### ISSUE TITLE
I am sure this has been reported, but I am stumped on this one

### ISSUE THREAD

**Issue by mikeerickson** [webpack/webpack#2778]
Receive following error when running Webpack.  This has been working forever, but for some reason, it is now a problem

````
ERROR in ./index.js
Module build failed: Error: Final loader didn't return a Buffer or String
    at DependenciesBlock.onModuleBuild (/Users/mikee/Documents/Projects/dev/angular/angular-sandbox/node_modules/webpack-core/lib/NormalModuleMixin.js:299:42)
    at nextLoader (/Users/mikee/Documents/Projects/dev/angular/angular-sandbox/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
    at /Users/mikee/Documents/Projects/dev/angular/angular-sandbox/node_modules/webpack-core/lib/NormalModuleMixin.js:292:15
    at runSyncOrAsync (/Users/mikee/Documents/Projects/dev/angular/angular-sandbox/node_modules/webpack-core/lib/NormalModuleMixin.js:160:12)
    at nextLoader (/Users/mikee/Documents/Projects/dev/angular/angular-sandbox/node_modules/webpack-core/lib/NormalModuleMixin.js:290:3)
    at /Users/mikee/Documents/Projects/dev/angular/angular-sandbox/node_modules/webpack-core/lib/NormalModuleMixin.js:292:15
    at Object.context.callback (/Users/mikee/Documents/Projects/dev/angular/angular-sandbox/node_modules/webpack-core/lib/NormalModuleMixin.js:148:14)
    at Object.module.exports (/Users/mikee/Documents/Projects/dev/angular/angular-sandbox/node_modules/babel-loader/index.js:89:8)
````

**Comment by mikeerickson** [comment]
Followup with the ./index.js file

````
/**
 * index.js
 * Created: 5/10/2016 2:24 PM (merickson)
 * =============================================================================
 */

// Initialize angular module and require any dependencies and global css (less)
import app  from './app.module'
import '!style!css!less!./app.less'

// all components are constructors `component` suppress from filename
// adopting React class filename convention
// all components filename's are singular (ie `Compliment` vs `Compliments`)

import Complient from './components/compliments'
import User      from './components/users'

````

**Comment by mikeerickson** [comment]
And webpack.config.js

````
/**
 * webpack.config.js
 * Mike Erickson <codedungeon@gmail.com>
 * 2016.06.06 18:40 (mikee)
 * =============================================================================
 */


var path                = require('path')
var ProgressBarPlugin   = require('progress-bar-webpack-plugin')
var CopyWebpackPlugin   = require('copy-webpack-plugin');
var BuildNotifierPlugin = require('webpack-build-notifier')
var ESLintWebpackPlugin = require('eslint-loader')
var msg                 = require('gulp-messenger')
var webpack             = require('webpack')

var outputPath     = path.join(__dirname, '/dist')
var outputFilename = 'bundle.js'
var publicPath     = outputPath

var webpackConfig = {
  context: __dirname + '/src',
  devtool: 'eval', // source-map
  entry:   './index.js',
  output: {
    path:       outputPath,
    filename:   outputFilename,
    publicPath: publicPath
  },
  // devServer: {
  //   contentBase: outputPath,
  //   hot: true
  // },
  module: {
    preLoaders: [
      {test: /\.(less|css)$/, loader: 'stylelint' },
      {test: /\.js$/, loader: "eslint-loader", exclude: /node_modules/}
    ],
    loaders: [
      {test: /\.js?$/, loaders: ['ng-annotate','babel'], exclude: /node_modules/},
      {test: /\.html?$/, loaders: ['raw']},
      {test: /\.less?$/, loaders: ['style!css!less?strictMath&noIeCompat']},
      {
        test: /\.css$/,
        loaders: [
          'style',
          'css?sourceMap&modules&localIdentName=[name]__[local]___[hash:base64:5]'
        ]
      },
    ]
  },
  stylelint: {
    configFile: path.join(__dirname, './.stylelintrc'),
    configOverrides: {
      rules: {
        // Your rule overrides here
      }
    }
  },
  plugins: [

    // Display notification when build completed
    new BuildNotifierPlugin(),

    // Removes duplicate modules from the build
    new webpack.optimize.DedupePlugin(),

    // Configure ProgressBar
    new ProgressBarPlugin({
      format: msg.chalk.yellow.bold('  Building [:bar] ') + msg.chalk.green.bold(':percent') + msg.chalk.bold(' (:elapsed seconds)'),
      clear:   false,
      summary: true
    }),
    
    // Copy assets not part of bundle
    new CopyWebpackPlugin([
      { from: './index.html', to: './index.html' },
      { from: './fonts',      to: './fonts' },
      { from: './css',        to: './css' },
      { from: './data',       to: './data' },
    ]),
    
    // Compress build
    new webpack.optimize.UglifyJsPlugin({
      compress: {
        warnings: false
      }
    }),

  ]
};

module.exports = webpackConfig;

````

**Comment by ojacobson** [comment]
> `import '!style!css!less!./app.less'`

Two observations:

1. The leading `!` in the module name shouldn't be there: the syntax is `'loader!module'`.
2. As you have a section in `webpack.config.js` that sets up a loader chain for `.less` files, you don't need to specify the loaders when `import`ing Less stylesheets.

I believe you should be able to replace this line with

```js
import './app.less'
```

**Comment by bebraw** [comment]
@mikeerickson Did that help?
