### ISSUE TITLE
Module build failed: Error: Couldn't find preset "stage-0" relative to directory

### ISSUE THREAD

**Issue by Rolandisimo** [webpack/webpack#2785]
I encountered a really strange issue: 

when I start my webpack-dev-server with a **jasmine-es6** module installed, webpack bundles successfully, however, if I remove that module from package.json, I have the error stated in the title.

Here's my package JSON:

```
{
  "name": "minimal-react-starter",
  "version": "0.0.1",
  "description": "React Gallery",
  "main": "js/index.js",
  "scripts": {
    "start": "webpack-dev-server --content-base=www --hot --inline --watch --config=webpack.config.js"
  },
  "author": "Roland Yegorov",
  "license": "",
  "repository": {
    "type": "git",
    "url": ""
  },
  "dependencies": {
    "babel-runtime": "^6.9.2",
    "react": "^15.2.0",
    "react-addons-shallow-compare": "^15.2.1",
    "react-dom": "^15.2.0"
  },
  "devDependencies": {
    "babel-cli": "^6.10.1",
    "babel-core": "^6.10.4",
    "babel-loader": "^6.2.4",
    "babel-plugin-transform-runtime": "^6.9.0",
    "babel-polyfill": "^6.9.1",
    "babel-preset-es2015": "^6.9.0",
    "babel-preset-react": "^6.11.1",
    "babel-register": "^6.9.0",
    "css-loader": "^0.23.1",

    "jasmine-es6": "^0.1.10",  <--- removing this fails the bundler

    "node-sass": "^3.8.0",
    "sass-loader": "^4.0.0",
    "style-loader": "^0.13.1",
    "webpack": "^1.12.2",
    "webpack-dev-server": "^1.12.1"
  }
}
```

So I wonder if there is something being installed along the jasmine-es6 module that other packages are **NOW** missing? 

Any ideas? Cause this has already taken a few hours to find...

**Comment by sokra** [comment]
maybe it's missing `babel-preset-stage-0`? But that's a babel related issue.

**Comment by Rolandisimo** [comment]
@sokra Thanks! Didn't even know about such package before. Now it works perfectly. Still though, strange that some modules seem to have stage-0 in them.

**Comment by astericky** [comment]
What was the fix? I have a similar issue but the module has stage-0 in it.

**Comment by Rolandisimo** [comment]
@astericky Sorry for the late reply, but the fix was simply adding babel-preset-stage-0 to your package.json and adding it to webpack loaders.
```
    module: {
        loaders: [
            {
                test: /\.jsx?$/,
                exclude: /node_modules/,
                loader: 'babel-loader',
                query: {
                    plugins: ['transform-runtime'],
                    presets: ['es2015', 'react', 'stage-0'] // <--- here
                }
            }, {
                test: /\.[s]?css$/,
                loader: 'style!css!sass'
            }
        ]
    },
```

**Comment by Losses** [comment]
@Rolandisimo what...if... the error of stage-0 and stage-2 appeared at the same time...?

**Comment by xgqfrms-gildata** [comment]
### what's wrong with this, anybody can do me a favor?

>  webpack.config.js (partly)

```js

    module: {
        // 引用的 loader
        rules: [
            {
                test: /\.js$/,// test: /\.(js|jsx)$/,
                exclude: /node_modules/,// exclude: /(node_modules|bower_components)/,
                use: 'babel-loader',
                // options: {
                //     presets: ['@babel/preset-env']
                // }
                use: {
                    loader: 'babel-loader',
                    options: {
                        // presets: ['es2015'],
                        presets: ['preset-env'],
                    }
                }
            }
        ]
    },
```
> .babelrc

```js

{
    "presets": ["preset-env"]
}

```
### error 
> screen shortcut


![image](https://user-images.githubusercontent.com/29531779/32885379-4fd3e0e0-caf8-11e7-943c-a1c4ade16ddd.png)



```txt

0 info it worked if it ends with ok
1 verbose cli [ 'H:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\xiagq\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'app' ]
2 info using npm@5.5.1
3 info using node@v8.9.1
4 verbose run-script [ 'preapp', 'app', 'postapp' ]
5 info lifecycle webpack_test@1.1.1~preapp: webpack_test@1.1.1
6 info lifecycle webpack_test@1.1.1~app: webpack_test@1.1.1
7 verbose lifecycle webpack_test@1.1.1~app: unsafe-perm in lifecycle true
8 verbose lifecycle webpack_test@1.1.1~app: PATH: C:\Users\xiagq\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;e:\github\RAIO\Webpack_Test\node_modules\.bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;H:\Program Files\TortoiseSVN\bin;H:\Program Files\nodejs\;C:\Users\xiagq\AppData\Local\Microsoft\WindowsApps;H:\Microsoft VS Code\bin;C:\Users\xiagq\AppData\Local\GitHubDesktop\bin;C:\Users\xiagq\AppData\Roaming\npm
9 verbose lifecycle webpack_test@1.1.1~app: CWD: e:\github\RAIO\Webpack_Test
10 silly lifecycle webpack_test@1.1.1~app: Args: [ '/d /s /c', 'webpack' ]
11 silly lifecycle webpack_test@1.1.1~app: Returned: code: 2  signal: null
12 info lifecycle webpack_test@1.1.1~app: Failed to exec app script
13 verbose stack Error: webpack_test@1.1.1 app: `webpack`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\xiagq\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:280:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\xiagq\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid webpack_test@1.1.1
15 verbose cwd e:\github\RAIO\Webpack_Test
16 verbose Windows_NT 10.0.15063
17 verbose argv "H:\\Program Files\\nodejs\\node.exe" "C:\\Users\\xiagq\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "app"
18 verbose node v8.9.1
19 verbose npm  v5.5.1
20 error code ELIFECYCLE
21 error errno 2
22 error webpack_test@1.1.1 app: `webpack`
22 error Exit status 2
23 error Failed at the webpack_test@1.1.1 app script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]

```

**Comment by xgqfrms-gildata** [comment]
# package.json

```json

{
    "name": "webpack_test",
    "version": "1.1.1",
    "description": "ES6/7/8 to ES5",
    "main": "webpack.config.js",
    "scripts": {
        "app": "webpack",
        "hot_modules_loader": "??? webpack hot HMR ???",
        "dev": "webpack -w",
        "test": "echo \"Error: no test specified\" && exit 1"
    },
    "repository": {
        "type": "git",
        "url": "git+https://github.com/gildata/RAIO.git"
    },
    "keywords": [
        "webapck",
        "auto_transpile",
        "es6/7/8",
        "es5"
    ],
    "author": "xgqfrms, gildata",
    "license": "MIT",
    "bugs": {
        "url": "https://github.com/gildata/RAIO/issues"
    },
    "homepage": "https://github.com/gildata/RAIO#readme",
    "dependencies": {
        "browserify": "^14.5.0",
        "requirejs": "^2.3.5",
        "systemjs": "^0.20.19",
        "webpack": "^3.8.1"
    },
    "devDependencies": {
        "babel": "^6.23.0",
        "babel-cli": "^6.26.0",
        "babel-core": "^6.26.0",
        "babel-loader": "^7.1.2",
        "babel-polyfill": "^6.26.0",
        "babel-preset-env": "^1.6.1",
        "babel-preset-react": "^6.24.1",
        "clean-webpack-plugin": "^0.1.17",
        "css-loader": "^0.28.7",
        "es-module-loader": "^2.2.8",
        "html-webpack-plugin": "^2.30.1",
        "sass-loader": "^6.0.6",
        "style-loader": "^0.19.0",
        "uglifyjs-webpack-plugin": "^1.0.1"
    }
}
```

**Comment by xgqfrms-GitHub** [comment]
# it's OK, now!

> `presets: ['env']`

![image](https://user-images.githubusercontent.com/18028768/32886369-6ba31ee6-cafb-11e7-8efc-2a96c971b896.png)

**Comment by b3none** [comment]
If you're here and you still have no clue...

``` yarn add babel-preset-stage-0 ```

or

``` npm install babel-preset-stage-0 ```

and refer to comment number 5.
