### ISSUE TITLE
how to use webpack dll plugin in server-side rendering

### ISSUE THREAD

**Issue by simonchan2013** [webpack/webpack#2875]
I have submit this in stackoverflow, but it seems no response, so I wanner to know is that it does not support this usage?

I am trying to use webpack's dllPlugin to get my chunk small, and I made it work well in client-side but something wrong in server-side rendering.

**Webpack version:**
1.13.1

**environment:**
OSX 10.11.6

I used [this](https://github.com/webpack/webpack/tree/master/examples/dll) as an example, and make it simpler, here is my demo code:

webpack.config.dll.js

```
// webpack.config.dll.js
const path = require('path');
const webpack = require('webpack');

module.exports = {
  entry: {
    a: ['./a']
  },
  output: {
    path: path.join(__dirname, 'dist'),
    filename: '[name].js',
    library: '[name]'
  },
  plugins: [
    new webpack.DllPlugin({
      path: path.join(__dirname, 'dist', 'manifest.json'),
      name: '[name]'
    })
  ]
}
```

webpack.config.js

```
// webpack.config.js
const path = require('path');
const webpack = require('webpack');

module.exports = {
  entry: './example',
  output: {
    path: path.join(__dirname, 'dist'),
    filename: 'output.js'
  },
  plugins: [
    new webpack.DllReferencePlugin({
      context: __dirname,
      manifest: require('./dist/manifest.json')
    })
  ]
};
```

other js code and html code is

```
// a.js
module.exports = 'a';

// example.js
console.log(require("./a"));

// index.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
</head>
<body>
  <script src="dist/a.js"></script>
  <script src="dist/output.js"></script>
</body>
</html>
```

if I open the index.html in browser, it work well and output 'a' in console. But if I excute `node dist/output.js`, it will get error:

```
/WorkSpace/code/webpack/005_dllPluginDemo_20160813/dist/output.js:64
    module.exports = a;
                     ^

ReferenceError: a is not defined
    at Object.<anonymous> (/WorkSpace/code/webpack/005_dllPluginDemo_20160813/dist/output.js:64:19)
    at __webpack_require__ (/WorkSpace/code/webpack/005_dllPluginDemo_20160813/dist/output.js:20:30)
    at Object.module.exports (/WorkSpace/code/webpack/005_dllPluginDemo_20160813/dist/output.js:58:20)
    at __webpack_require__ (/WorkSpace/code/webpack/005_dllPluginDemo_20160813/dist/output.js:20:30)
    at Object.<anonymous> (/WorkSpace/code/webpack/005_dllPluginDemo_20160813/dist/output.js:48:14)
    at __webpack_require__ (/WorkSpace/code/webpack/005_dllPluginDemo_20160813/dist/output.js:20:30)
    at /WorkSpace/code/webpack/005_dllPluginDemo_20160813/dist/output.js:40:18
    at Object.<anonymous> (/WorkSpace/code/webpack/005_dllPluginDemo_20160813/dist/output.js:43:10)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
```

so it means that I can't require output.js in my code. Unfortunately, I need do that when I try to render in server, just like [this boilerplates](https://github.com/reactGo/reactGo/blob/master/server/index.js#L8)

and I think the problem is that the module a had been deal twice by webpack

So is there anybody met this problem? And how did you solve it, wish your answer, thanks

**Comment by sokra** [comment]
`output.libraryTarget = "commonjs2"` in the dll

**Comment by simonchan2013** [comment]
@sokra  I had try `commonjs`, `commonjs2`, `umd`, but it still threw that error,  and I output the module `a` and module `dist/a`, they print defferent content

```js
console.log(require('./a'));      // => a

console.log(require('./dist/a'));
/*
=>
{ [Function: __webpack_require__]
  m: [ [Function], [Function] ],
  c: { '0': { exports: [Circular], id: 0, loaded: true } },
  p: '' }
*/
```

**Comment by sokra** [comment]
Looks correct. The dll file doesn't export the module, it exports the require function to access all modules inside the dll.

**Comment by vtabary** [comment]
Hi,

In fact, I may have a similar issue with DllPlugin and umd as libraryTarget.

The problem is that the DllPlugin prevent webpack to build a valid package (as umd or commonjs) since it forces the bundle to export a function used by DllReferencePlugin instead of the main module, and so can not be used even if the libraryTarget has the same value.

This prevents us to use a DllPlugin bundle as an normal umd (or commonjs) bundle to, for me, require it dynamically, or to use it as an external dependencies into an other webpack configuration.

You can find a simple example here : https://github.com/vtabary/webpack-externals-dllplugin

The solution could be to not export the local ```__webpack_require__``` by default but to add a property to the main module so it won't be overriden

**Comment by simonchan2013** [comment]
do you mean that we should make those module(which will be bundle as dll) to export a function? @vtabary

**Comment by vtabary** [comment]
When the bundle is built as a Dll, it already export a function (```__webpack_require__```). 

I think the Dll bundle should export, by default, the same object than the umd bundle, and add to this object the function ___webpack_require__.

So if I load the module, I should get something like 

```
System.import('../dist/main.umd')
            .then(function (module) {
              console.log(module); // Show : function test(name) {...
              console.log(module.__webpack__require__); // Show function __webpack_require__(...
            });
```

And so, the DllReferencePlugin could directly use the function ```module.__webpack_require__``` instead of the ```module``` directly

**Comment by davidfraser** [comment]
The problem seems to be that the browser solution involves loading the DLL Javascript using a `<script>` tag, before the main module. There is no obvious way to do the equivalent with server-side node...

**Comment by jasonxia23** [comment]
Agree with @davidfraser . One way to fix the problem is combine a.js and output.js like this:
```shell
cat dist/a.js dist/output.js > dist/build.js
node dist/build.js
# a
```
In project, you can use something like Gulp to do this.

**Comment by gingur** [comment]
A bit hackish, but if you export your DLL as UMD (`libraryTarget: "umd"`) you can do the following at the start of your server:
```
const Module = require('module');
const dll = require('./dist/main.dll');
const manifest = require('./dist/main.dll.manifest.json');

const paths = Object.keys(manifest.content);
const _resolveFilename = Module._resolveFilename;

Module._resolveFilename = function _dllResolveFilename(request, parent) {
  if (request in paths) {
    return request; // bypass default resolve behavior
  }
  return _resolveFilename(request, parent);
};
paths.forEach(function (key) {
  require.cache[key] = {
    id: key,
    filename: key,
    loaded: true,
    exports: dll(manifest.content[key].id)
  };
});
```
Now, the fun part is if you want to remove your `node_module` dependencies you would need to pre-define what these dependencies map to.  Example, `react` resolves to `./react/index.js`.  You can do this via a webpack plugin or post webpack script and use that as your mapping to DLL assets.

I can take a crack at writing a plugin, if this approach works for anyone?

**Comment by evilebottnawi** [comment]
Closing due to inactivity. Please test with latest version and feel free to reopen if still regressions. Thanks!

**Comment by Hideer** [comment]
@simonchan2013 Did you finally solve this problem? I have the same idea and encountered a problem

**Comment by Hideer** [comment]
@sokra Hello, do I use `output.libraryTarget = "commonjs2"` or not
