### ISSUE TITLE
Uncaught ReferenceError: System is not defined, when importing `tslib` (Runtime library for TypeScript helpers)

### ISSUE THREAD

**Issue by unlight** [webpack/webpack#2942]
**I'm submitting a bug report**
Error when importing `tslib` https://github.com/Microsoft/tslib (Runtime library for TypeScript helpers)

**Webpack version:**
webpack 2.1.0-beta.21

**Please tell us about your environment:**
Windows 8.1

**Current behavior:**
Source:
```js
    if (typeof System === "object" && typeof System.register === "function") {
        System.register("tslib", [], function (exporter) {
            factory(createExporter(root, exporter));
            return { setters: [], execute: function() { } };
        });
    }
```
Result:
```js
    if ("object" === "object" && typeof System.register === "function") {
        System.register("tslib", [], function (exporter) {
            factory(createExporter(root, exporter));
            return { setters: [], execute: function() { } };
        });
    }
```
Error:
```
polyfills.bundle.js:13392 Uncaught ReferenceError: System is not defined
    at http://localhost:3000/polyfills.bundle.js:13392:41
    at Object.<anonymous> (http://localhost:3000/polyfills.bundle.js:13412:1)
    at Object../node_modules/tslib/tslib.js (http://localhost:3000/polyfills.bundle.js:13458:30)
    at __webpack_require__ (http://localhost:3000/polyfills.bundle.js:54:30)
    at Object../src/polyfills.ts (http://localhost:3000/polyfills.bundle.js:16346:1)
    at __webpack_require__ (http://localhost:3000/polyfills.bundle.js:54:30)
    at Object.1 (http://localhost:3000/polyfills.bundle.js:16363:18)
    at __webpack_require__ (http://localhost:3000/polyfills.bundle.js:54:30)
    at ac_polyfills../node_modules/ansi-regex/index.js (http://localhost:3000/polyfills.bundle.js:139:18)
    at http://localhost:3000/polyfills.bundle.js:142:10
```

**Expected/desired behavior:**
No error

**Browser:**
 Chrome 55.0.2844.0

**Comment by Kovensky** [comment]
This is probably caused by the `System.import` support...

A potential workaround is requiring tslib with `imports-loader?System=>System!tslib` instead, hoping that decoupling reading the `System` value from the `typeof` statement makes it not convert the `typeof System` to `"object"`.

**Comment by Tragetaschen** [comment]
#2817
