### ISSUE TITLE
The generated JS overwrites a valid export with an invalid one

### ISSUE THREAD

**Issue by Tragetaschen** [webpack/webpack#2970]
**I'm submitting a bug report**

**Webpack version:**
2.1.0-beta.21

**Please tell us about your environment:**
Windows 10

**Current behavior:**
In the reproduction (see below), instead of just the (re-)export of the `ViewEncapsulation` member from `metadata`, webpack also generates an entirely invalid export with the same property name `a` from `di`.

**Expected/desired behavior:**
There shouldn't be a breaking, overwriting property definition.

* **What is the expected behavior?**
*sigh*

* **What is the motivation / use case for changing the behavior?**
So there isn't a bug.
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 
* **Language:** [ES6]

**Comment by Tragetaschen** [comment]
Repro: https://github.com/Tragetaschen/angular-core-export-overwrite

Steps to reproduce:
```
$ npm install
$ webpack
$ node dist/main.js
```
Expected: An output of `0`.
Actual:
```
C:\Users\kairu\Source\Repos\angular-core-webpack-export-overwrite\dist\main.js:41
/******/                Object.defineProperty(exports, name, {
                               ^

TypeError: Cannot redefine property: a
    at Function.defineProperty (native)
    at Function.__webpack_require__.d (C:\Users\kairu\Source\Repos\angular-core-webpack-export-overwrite\dist\main.js:41:19)
    at Object.<anonymous> (C:\Users\kairu\Source\Repos\angular-core-webpack-export-overwrite\dist\main.js:12855:54)
    at __webpack_require__ (C:\Users\kairu\Source\Repos\angular-core-webpack-export-overwrite\dist\main.js:20:30)
    at Object.AnimationKeyframe.AnimationKeyframe.styles.offset (C:\Users\kairu\Source\Repos\angular-core-webpack-export-overwrite\dist\main.js:12351:68)
    at __webpack_require__ (C:\Users\kairu\Source\Repos\angular-core-webpack-export-overwrite\dist\main.js:20:30)
    at Object.<anonymous> (C:\Users\kairu\Source\Repos\angular-core-webpack-export-overwrite\dist\main.js:15334:72)
    at __webpack_require__ (C:\Users\kairu\Source\Repos\angular-core-webpack-export-overwrite\dist\main.js:20:30)
    at exports.s (C:\Users\kairu\Source\Repos\angular-core-webpack-export-overwrite\dist\main.js:64:18)
    at Object.<anonymous> (C:\Users\kairu\Source\Repos\angular-core-webpack-export-overwrite\dist\main.js:67:10)
```

Reason:
```
12853: /* harmony namespace reexport */ __webpack_require__.d(exports, "a", function() { return __WEBPACK_IMPORTED_MODULE_0__metadata__["b"]; });
12854: /* unused harmony namespace reexport */
12855: /* harmony namespace reexport */ __webpack_require__.d(exports, "a", function() { return __WEBPACK_IMPORTED_MODULE_2__di__["j"]; });
```

Instead of just generating the export for `ViewEncapsulation` in line 12853, for some reason webpack also creates line 12855. The property `j` doesn't even exist in the `di` export.

**Comment by TheLarkInn** [comment]
Fixed in beta.22 https://github.com/webpack/webpack/commit/6d1f3e3fa3904f68844cf0e7633864e55a33e625
