### ISSUE TITLE
Error: Callback was already called

### ISSUE THREAD

**Issue by andreypopp** [webpack/webpack#298]
I get the following error when one of my module contains a syntax error (which is gets caught by jsx-loader):

```
/Users/andreypopp/Workspace/-/lib/node_modules/webpack/node_modules/async/lib/async.js:30
            if (called) throw new Error("Callback was already called.");
                              ^
Error: Callback was already called.
    at /Users/andreypopp/Workspace/-/forms/lib/node_modules/webpack/node_modules/async/lib/async.js:30:31
    at /Users/andreypopp/Workspace/-/forms/lib/node_modules/webpack/lib/Compilation.js:303:10
    at done (/Users/andreypopp/Workspace/-/forms/lib/node_modules/webpack/node_modules/async/lib/async.js:129:15)
    at /Users/andreypopp/Workspace/-/forms/lib/node_modules/webpack/node_modules/async/lib/async.js:32:16
    at /Users/andreypopp/Workspace/-/forms/lib/node_modules/webpack/lib/Compilation.js:300:4
    at done (/Users/andreypopp/Workspace/-/forms/lib/node_modules/webpack/node_modules/async/lib/async.js:129:15)
    at /Users/andreypopp/Workspace/-/forms/lib/node_modules/webpack/node_modules/async/lib/async.js:32:16
    at /Users/andreypopp/Workspace/-/forms/lib/node_modules/webpack/lib/Compilation.js:300:4
    at done (/Users/andreypopp/Workspace/-/forms/lib/node_modules/webpack/node_modules/async/lib/async.js:129:15)
    at /Users/andreypopp/Workspace/-/forms/lib/node_modules/webpack/node_modules/async/lib/async.js:32:16
```

I don't receive the filename of the file with syntax error also.

**Comment by Legends** [comment]
In my case it was a dynamic `require `call pointing to a folder where I keep my templates.
I put my app entry scripts (for my multi-page-app) into a respective subfolder of my templates folder and I guess the dynamic `require` bundles all modules (also the entry scripts, which is obviously not desired) it finds beneath the templates folder and that was causing the issue above.

**Comment by dmnsgn** [comment]
@Legends would you mind sharing how you have solved the problem in your use case?
I am facing a similar issue.

**Comment by Legends** [comment]
@dmnsgn I guess I changed the folder structure to circumvent this issue.

**Comment by dmnsgn** [comment]
Thanks, that was it.
