### ISSUE TITLE
Sequences of "undefined" in webpack output

### ISSUE THREAD

**Issue by paralin** [webpack/webpack#3063]
**I'm submitting a bug report**

**Webpack version:**

2.1.0-beta.22

**Please tell us about your environment:**

Linux

**Current behavior:**

The output bundle looks something like this:

```
// mixin the deprecation features.
Object.assign(core, require('./deprecation'));

// Always export pixi globally.
global.PIXI = core;

}).call(this,typeof global !== "undefined" ? global : typeof self !== "undefined" ? self : typeof window !== "undefined" ? window : {})

},{"./accessibility":76,"./core":97,"./deprecation":154,"./extract":156,"./extras":164,"./filters":175,"./interaction":180,"./loaders":183,"./mesh":191,"./particles":194,"./polyfill":200,"./prepare":203}]},{},[205])(205)
});


u
/* WEBPACK VAR INJECTION */}.call(exports, __webpack_require__(33)))ndefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefined

/***/ },
/* 220 */
/***/ function(module, exports, __webpack_require__) {

"use strict";
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_0__src_location__ = __webpack_require__(385);
```

The output bundle is produced by the Karma webpack.test.js bundle from angular2-webpack-starter: https://github.com/AngularClass/angular2-webpack-starter - I've just added some code that references Pixi.JS.

A probably related error in the cli:

```
Chrome 53.0.2785 (Linux 0.0.0) ERROR
  Uncaught SyntaxError: Unexpected identifier
  at webpack:///source/src/prepare/webgl/WebGLPrepare.js:277:0 <- config/spec-bundle.js:58543
Chrome 53.0.2785 (Linux 0.0.0) ERROR
  Uncaught SyntaxError: Unexpected identifier
  at webpack:///source/src/prepare/webgl/WebGLPrepare.js:277:0 <- config/spec-bundle.js:58543
```

I checked that line in the source code: https://github.com/pixijs/pixi.js/blob/master/src/prepare/webgl/WebGLPrepare.js#L277

Seems fine.

**Expected/desired behavior:**

Not having the long sequences of `undefined`

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.** 

See the angular2-webpack-starter repo.

* **Browser:** Chrome
 
* **Language:** TypeScript 2.0.3

**Comment by paralin** [comment]
After ignoring the source maps for pixi it's fixed, I think it's a pixi issue.
