### ISSUE TITLE
Improve test coverage of NodeStuffPlugin.js, NormalModuleFactory.js, and NodeSourcePlugin.js

### ISSUE THREAD

**Issue by MarkusKramer** [webpack/webpack#3081]
Tests need to be written for the mentioned modules.

**Comment by pksjce** [comment]
@MarkusKramer @bebraw  - Tried to run npm test on master. Throws an error at 
`Error: Cannot find module 'webpack/lib/removeAndDo'`
Any idea if I'm missing something.

**Comment by zhaoshengjun** [comment]
I ran into this issue before. That time is because I run `npm link` before I ran the tests. The issue is `npm link` will create the system link into other places where webpack are used. But it forget to create a system link in the current directory.

You may try to create/copy a system link in current webpack source code directory and see how it goes.

**Comment by pksjce** [comment]
Solved this by linking.
My understanding of the issue is that, this [line in extract-text-webpack-plugin](https://github.com/webpack/extract-text-webpack-plugin/blob/master/ExtractedModule.js#L30) breaks because the plugin has dependency back on webpack.

**Comment by pksjce** [comment]
Anyway thanks for your help. The tests are working now. I will try and open a PR for this.

**Comment by arturparkhisenko** [comment]
@pksjce how it's going? tried to make another PR, but got [this](https://github.com/webpack/webpack/issues/3081#issuecomment-251356860) issue too. If you're busy, pls explain a little bit about it, I could make that PR for you.

**Comment by pksjce** [comment]
Oh! I have forgotten about this issue. Let me check with latest webpack how it goes. There has been a bunch of changes in webpack regarding testing. I havent caught up with that yet.

**Comment by scottdj92** [comment]
Got the same issue. Running `npm link` resolves the issue with the `lib/removeAndDo` file, but now I get an error regarding `lib/ConcatSource`. Doesn't look like ConcatSource exists in the webpack repo. I wonder if the two issues are related, and if there's a fallback for webpack to resolve missing dependencies.

```Error: Cannot find module 'webpack/lib/ConcatSource'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/sjone4/Desktop/funsies/webpack/node_modules/extract-text-webpack-plugin/index.js:5:20)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/sjone4/Desktop/funsies/webpack/test/HotTestCases.test.js:6:25)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at require (internal/module.js:20:19)
    at /Users/sjone4/Desktop/funsies/webpack/node_modules/mocha/lib/mocha.js:222:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/sjone4/Desktop/funsies/webpack/node_modules/mocha/lib/mocha.js:219:14)
    at Mocha.run (/Users/sjone4/Desktop/funsies/webpack/node_modules/mocha/lib/mocha.js:487:10)
    at Object.<anonymous> (/Users/sjone4/Desktop/funsies/webpack/node_modules/mocha/bin/_mocha:459:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3```

**Comment by scottdj92** [comment]
Fixed the issue thanks to @timse's suggestion: run `yarn/npm link && yarn/npm link webpack`
