### ISSUE TITLE
Problem running webpack in a symlink

### ISSUE THREAD

**Issue by Eccenux** [webpack/webpack#3148]
**I'm submitting a bug report**

**Webpack version:**
1.13.2

**Please tell us about your environment:**
Windows 10

**Current behavior:**
Build doesn't run in a folder that is a Junction.

**Expected/desired behavior:**
Build should run normally.

**Steps to reproduce:** 
Step. 1. Setup directories:
```dos
mkdir \test\webpack\abc
cd \test\webpack\
mklink /J abc_link abc
cd abc_link
```
Step. 2. Create example file
```
echo console.log('foo bar') > entry.js
```
Step. 3. Run basic build:
```
webpack ./entry.js bundle.js
```

**What is the motivation / use case for changing the behavior?**

Would e.g. allow to create a build to an actual directory and workaround the issue #2258

**Comment by SerjCh** [comment]
confirmed if junction on same drive, if drive differ - works fine

**Comment by rogersillito** [comment]
I just ran into this myself (junction is on same drive as target):  I'm on Windows 10 x64, webpack v2.5.1, node 4.3.2

**Comment by octaharon** [comment]
Issue still persists, 
Windows 10 x64, Webpack 3.5.5, tried both Node 6.3.2 and 8.4.0

Running a build inside the linked folder works

Running a build inside a junction results in process freezing at "10%" mark, while continuosly consuming memory. At some point the process interrupts because it can't allocate any more memory. Whatever the reason is, seems it's not handled at all

reinstalling npm modules from linked folder doesn't help

**Comment by jcadiba** [comment]
Yes there is an issue about symlink junction in the same drive. 

system : Windows 10x64, 
WebPack : 3.4.1
node : 6.10.3
npm : 3.10.10

when i moved module in an other drive it works fine. but if the symlink is in the save drive webpack compiles the project but failed to load with this error.

`compiler.es5.js:1690 Uncaught Error: Unexpected value 'SharedModule' imported by the module 'AppModule'. Please add a @NgModule annotation.
at syntaxError (compiler.es5.js:1690)
at compiler.es5.js:15382
at Array.forEach (<anonymous>)
at CompileMetadataResolver.webpackJsonp.../../../compiler/@angular/compiler.es5.js.CompileMetadataResolver.getNgModuleMetadata (compiler.es5.js:15365)
at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._loadModules (compiler.es5.js:26795)
at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileModuleAndComponents (compiler.es5.js:26768)
at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler.compileModuleAsync (compiler.es5.js:26697)
at PlatformRef_.webpackJsonp.../../../core/@angular/core.es5.js.PlatformRef_._bootstrapModuleWithZone (core.es5.js:4536)
at PlatformRef_.webpackJsonp.../../../core/@angular/core.es5.js.PlatformRef_.bootstrapModule (core.es5.js:4522)
at Object.../../../../../src/main.ts (main.ts:11)`

**Comment by julienje** [comment]
any news about it?

**Comment by bascott** [comment]
I can build fine with a symlink to a different drive, but watch crashes on file changes.

`ERROR in ./D:/Users/Brian/projects/react-vis-example/src/index.tsx
Module build failed: Error: Cannot find module 'C:\Users\Brian\projects\react-vis-example\D:\Users\Brian\projects\react-vis-example\node_modules\ts-loader\index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (D:\Users\Brian\projects\react-vis-example\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at loadLoader (D:\Users\Brian\projects\react-vis-example\node_modules\loader-runner\lib\loadLoader.js:13:17)
    at iteratePitchingLoaders (D:\Users\Brian\projects\react-vis-example\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at runLoaders (D:\Users\Brian\projects\react-vis-example\node_modules\loader-runner\lib\LoaderRunner.js:362:2)
    at NormalModule.doBuild (D:\Users\Brian\projects\react-vis-example\node_modules\webpack\lib\NormalModule.js:235:3)
    at NormalModule.build (D:\Users\Brian\projects\react-vis-example\node_modules\webpack\lib\NormalModule.js:365:15)
    at Compilation.buildModule (D:\Users\Brian\projects\react-vis-example\node_modules\webpack\lib\Compilation.js:362:10)
    at moduleFactory.create (D:\Users\Brian\projects\react-vis-example\node_modules\webpack\lib\Compilation.js:711:12)
    at factory (D:\Users\Brian\projects\react-vis-example\node_modules\webpack\lib\NormalModuleFactory.js:366:6)
    at hooks.afterResolve.callAsync (D:\Users\Brian\projects\react-vis-example\node_modules\webpack\lib\NormalModuleFactory.js:143:13)
    at AsyncSeriesWaterfallHook.eval [as callAsync] (eval at create (D:\Users\Brian\projects\react-vis-example\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesWaterfallHook.lazyCompileHook [as _callAsync] (D:\Users\Brian\projects\react-vis-example\node_modules\tapable\lib\Hook.js:35:21)
    at resolver (D:\Users\Brian\projects\react-vis-example\node_modules\webpack\lib\NormalModuleFactory.js:126:29)
    at D:\Users\Brian\projects\react-vis-example\node_modules\hard-source-webpack-plugin\index.js:1176:16
    at process.nextTick (D:\Users\Brian\projects\react-vis-example\node_modules\webpack\lib\NormalModuleFactory.js:304:9)
    at process._tickCallback (internal/process/next_tick.js:61:11)`

**Comment by mansouryaacoubi** [comment]
This issue still persists and I cannot confirm that this is just an issue working on the same drive.
My drives differ and the correct path cannot be resolved.
Here you can find out what I mean: https://github.com/nuxt/create-nuxt-app/issues/217
