### ISSUE TITLE
Webpack (css-loader) fails when using minimizer

### ISSUE THREAD

**Issue by adamsiwiec** [webpack/webpack#3188]
**I'm submitting a bug report**

**Webpack version:**
1.13.2

**Please tell us about your environment:**
OSX 10.12

**Current behavior:**

webpack fails with `webpack --optimize-minimize` or `new webpack.optimize.UglifyJsPlugin()` with error:  
```
ERROR in ./~/css-loader!./src/css/main.css
Module build failed: Error: ENOENT: no such file or directory, open '/Users/adamsiwiec/Desktop/personal/node_modules/svgo/lib/svgo/../../.svgo.yml'
    at Object.fs.openSync (fs.js:557:18)
    at Object.fs.readFileSync (fs.js:467:33)
    at module.exports (/Users/adamsiwiec/Desktop/personal/node_modules/svgo/lib/svgo/config.js:31:48)
    at new module.exports (/Users/adamsiwiec/Desktop/personal/node_modules/svgo/lib/svgo.js:21:19)
    at /Users/adamsiwiec/Desktop/personal/node_modules/postcss-svgo/dist/index.js:91:16
    at Object.creator [as postcssSvgo] (/Users/adamsiwiec/Desktop/personal/node_modules/postcss/lib/postcss.js:150:35)
    at /Users/adamsiwiec/Desktop/personal/node_modules/cssnano/dist/index.js:283:40
    at Array.forEach (native)
    at /Users/adamsiwiec/Desktop/personal/node_modules/cssnano/dist/index.js:270:29
    at creator (/Users/adamsiwiec/Desktop/personal/node_modules/postcss/lib/postcss.js:150:35)
    at processCss (/Users/adamsiwiec/Desktop/personal/node_modules/css-loader/lib/processCss.js:186:16)
    at Object.module.exports (/Users/adamsiwiec/Desktop/personal/node_modules/css-loader/lib/loader.js:24:2)
 @ ./src/css/main.css 4:14-78
```

**Expected/desired behavior:**

Should not have any errors 😀   and minimize my scripts.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.** 

webpack config:

```
var path = require("path");
var webpack = require("webpack");

var SRC = path.join(__dirname, 'src/');

module.exports = {
    entry: SRC,
    output: {
        publicPath: "dist/",
        path: './dist',
        filename: 'app.bundle.js'
    },
    module: {
        loaders: [{
            test: /\.css$/,
            loaders: ['style', 'css']
        }, {
            test: /\.(jpg|png)$/,
            loader: 'file',
            query: {
                name: 'img/[name].[ext]'
            }

        }, {
            test: /\.woff(2)?(\?v=[0-9]\.[0-9]\.[0-9])?$/,
            loader: "url-loader?limit=10000&minetype=application/font-woff"
        }, {
            test: /\.(ttf|eot|svg)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
            loader: "file-loader"
        }]
    },

    plugins: [
        new webpack.ProvidePlugin({
            $: "jquery",
            jQuery: "jquery",
            "window.jQuery": "jquery"
        }),

        new webpack.optimize.UglifyJsPlugin({
    compress: {
        warnings: false
    }
})
    ]
};
```

**Comment by adamsiwiec** [comment]
I solved it by I don't know how 🤔 I reinstalled my node_modules with npm instead of yarn, but it might of been from using `yarn clean`. I'll need to research this more.

**Comment by bebraw** [comment]
If you can reproduce this with webpack 2, please re-open.
