### ISSUE TITLE
Upgrading from 1.13.0 to 1.13.2 causes Template Error

### ISSUE THREAD

**Issue by raybooysen** [webpack/webpack#3225]
**I'm submitting a bug report**

**Webpack version:**
1.13.2

**Please tell us about your environment:**
OSX 10.x / Linux / Windows 10
Ubuntu 16.10

**Current behavior:**
When compiling, I see the following exception:
```
RROR in chunk main [entry]
projectFoo.js
No template for dependency: TemplateArgumentDependency
Error: No template for dependency: TemplateArgumentDependency
    at doDep (/home/ray/source/projectFoo/node_modules/webpack/lib/NormalModule.js:137:23)
    at Array.forEach (native)
    at doBlock (/home/ray/source/projectFoo/node_modules/webpack/lib/NormalModule.js:151:22)
    at DependenciesBlock.NormalModule.source (/home/ray/source/projectFoo/node_modules/webpack/lib/NormalModule.js:186:2)
    at Template.ModuleTemplate.render (/home/ray/source/projectFoo/node_modules/webpack/lib/ModuleTemplate.js:14:28)
    at Template.renderChunkModules (/home/ray/source/projectFoo/node_modules/webpack/lib/Template.js:103:31)
    at Template.<anonymous> (/home/ray/source/projectFoo/node_modules/webpack/lib/MainTemplate.js:30:22)
    at Template.applyPlugins [as applyPluginsWaterfall] (/home/ray/source/projectFoo/node_modules/webpack/node_modules/tapable/lib/Tapable.js:37:47)
    at Template.MainTemplate.render (/home/ray/source/projectFoo/node_modules/webpack/lib/MainTemplate.js:113:20)
    at Compilation.createChunkAssets (/home/ray/source/projectFoo/node_modules/webpack/lib/Compilation.js:843:33)
    at Compilation.<anonymous> (/home/ray/source/projectFoo/node_modules/webpack/lib/Compilation.js:557:8)
    at Compilation.applyPluginsAsync (/home/ray/source/projectFoo/node_modules/webpack/node_modules/tapable/lib/Tapable.js:60:69)
    at Compilation.seal (/home/ray/source/projectFoo/node_modules/webpack/lib/Compilation.js:525:7)
    at Compiler.<anonymous> (/home/ray/source/projectFoo/node_modules/webpack/lib/Compiler.js:397:15)
    at /home/ray/source/projectFoo/node_modules/webpack/node_modules/tapable/lib/Tapable.js:103:11
    at Compilation.<anonymous> (/home/ray/source/projectFoo/node_modules/webpack/lib/Compilation.js:445:10)
    at /home/ray/source/projectFoo/node_modules/webpack/lib/Compilation.js:417:12
    at /home/ray/source/projectFoo/node_modules/webpack/lib/Compilation.js:332:10
    at /home/ray/source/projectFoo/node_modules/webpack/node_modules/async/lib/async.js:52:16
    at done (/home/ray/source/projectFoo/node_modules/webpack/node_modules/async/lib/async.js:246:17)
    at /home/ray/source/projectFoo/node_modules/webpack/node_modules/async/lib/async.js:44:16
    at /home/ray/source/projectFoo/node_modules/webpack/lib/Compilation.js:332:10
    at /home/ray/source/projectFoo/node_modules/webpack/node_modules/async/lib/async.js:52:16
    at done (/home/ray/source/projectFoo/node_modules/webpack/node_modules/async/lib/async.js:246:17)
    at /home/ray/source/projectFoo/node_modules/webpack/node_modules/async/lib/async.js:44:16
    at /home/ray/source/projectFoo/node_modules/webpack/lib/Compilation.js:332:10
    at /home/ray/source/projectFoo/node_modules/webpack/node_modules/async/lib/async.js:52:16
    at done (/home/ray/source/projectFoo/node_modules/webpack/node_modules/async/lib/async.js:246:17)
    at /home/ray/source/projectFoo/node_modules/webpack/node_modules/async/lib/async.js:44:16
    at /home/ray/source/projectFoo/node_modules/webpack/lib/Compilation.js:332:10

```

This works fine in 1.13.0 but upgrading to 1.13.2 causes webpack to fail.

**Comment by bebraw** [comment]
Can you provide a project to test against? I wonder what changed in between.

**Comment by SpaceK33z** [comment]
@raybooysen ping ^

**Comment by TheLarkInn** [comment]
I'm going to close this as this was from webpack 1. 
If this is still an issue, please resubmit a new issue with the information listed in our issue template (version, repro repo, etc.)
