### ISSUE TITLE
provide better errors for plugins

### ISSUE THREAD

**Issue by gdi2290** [webpack/webpack#3310]
**I'm submitting a feature request**

**Webpack version:**
2.0.0-beta.27

**Please tell us about your environment:**
OSX 10.x

**Current behavior:**
```
/Users/patrickjs/Code/angular/universal-starter/node_modules/tapable/lib/Tapable.js:233
		arguments[i].apply(this);
               ^
TypeError: arguments[i].apply is not a function
    at Compiler.apply (/Users/patrickjs/Code/angular/universal-starter/node_modules/tapable/lib/Tapable.js:233:16)
    at WebpackOptionsApply.process (/Users/patrickjs/Code/angular/universal-starter/node_modules/webpack/lib/WebpackOptionsApply.js:59:18)
    at webpack (/Users/patrickjs/Code/angular/universal-starter/node_modules/webpack/lib/webpack.js:29:48)
    at /Users/patrickjs/Code/angular/universal-starter/node_modules/webpack/lib/webpack.js:22:11
    at Array.map (native)
    at webpack (/Users/patrickjs/Code/angular/universal-starter/node_modules/webpack/lib/webpack.js:21:40)
    at processOptions (/Users/patrickjs/Code/angular/universal-starter/node_modules/webpack/bin/webpack.js:275:14)
    at Object.<anonymous> (/Users/patrickjs/Code/angular/universal-starter/node_modules/webpack/bin/webpack.js:339:1)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

**Expected/desired behavior:**
there should be a type check to ensure plugins is an flatten array

* **Browser:** [Chrome] 
 
* **Language:** [TypeScript 2.X]

**Comment by TheLarkInn** [comment]
@gdi2290 was this while attempting to use a webpack core plugin or a custom one? If custom could you link to src?

**Comment by gdi2290** [comment]
This was just creating a prod config by requiring the original config and not realizing I didn't merge the two plugin arrays correctly which resulting in a nested array.

https://github.com/angular/universal-starter/blob/master/webpack.prod.config.ts

**Comment by aem** [comment]
Was going to try and tackle this. Is the correct behavior to error out or should we attempt to flatten the array and then apply all plugins contained in child arrays?
