### ISSUE TITLE
TypeError: Cannot read property 'errors' of null

### ISSUE THREAD

**Issue by renarsvilnis** [webpack/webpack#3324]
**I'm submitting a bug report**

**Webpack version:**
2.1.0-beta.27

**Please tell us about your environment:**
OSX 10.11.6

**Current behavior:**
Setting up extract-text-webpack-plugin (*v2.0.0-beta.4*) I came accross a webpack runtime error while using an incorrectly configured `extract-text-webpack-plugin`.

```javascript
TypeError: Cannot read property 'errors' of null
    at errorAndCallback (/path/to/project/node_modules/webpack/lib/Compilation.js:198:12)
    at errorOrWarningAndCallback (/path/to/project/node_modules/webpack/lib/Compilation.js:229:18)
    at /path/to/project/node_modules/webpack/lib/Compilation.js:233:16
    at onDoneResolving (/path/to/project/node_modules/webpack/lib/NormalModuleFactory.js:40:20)
    at /path/to/project/node_modules/webpack/lib/NormalModuleFactory.js:117:20
    at /path/to/project/node_modules/webpack/node_modules/async/dist/async.js:3853:9
    at /path/to/project/node_modules/webpack/node_modules/async/dist/async.js:484:16
    at iteratorCallback (/path/to/project/node_modules/webpack/node_modules/async/dist/async.js:1082:13)
    at /path/to/project/node_modules/webpack/node_modules/async/dist/async.js:988:16
    at /path/to/project/node_modules/webpack/node_modules/async/dist/async.js:3850:13
    at apply (/path/to/project/node_modules/webpack/node_modules/async/dist/async.js:41:25)
    at /path/to/project/node_modules/webpack/node_modules/async/dist/async.js:76:12
    at /path/to/project/node_modules/webpack/lib/NormalModuleFactory.js:112:22
    at onResolved (/path/to/project/node_modules/enhanced-resolve/lib/Resolver.js:70:11)
    at loggingCallbackWrapper (/path/to/project/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at afterInnerCallback (/path/to/project/node_modules/enhanced-resolve/lib/Resolver.js:138:10)
    at loggingCallbackWrapper (/path/to/project/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at Resolver.applyPluginsAsyncSeriesBailResult1 (/path/to/project/node_modules/tapable/lib/Tapable.js:108:46)
    at innerCallback (/path/to/project/node_modules/enhanced-resolve/lib/Resolver.js:125:19)
    at loggingCallbackWrapper (/path/to/project/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at /path/to/project/node_modules/tapable/lib/Tapable.js:210:15
    at /path/to/project/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:39:4
    at loggingCallbackWrapper (/path/to/project/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at afterInnerCallback (/path/to/project/node_modules/enhanced-resolve/lib/Resolver.js:138:10)
    at loggingCallbackWrapper (/path/to/project/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at Resolver.applyPluginsAsyncSeriesBailResult1 (/path/to/project/node_modules/tapable/lib/Tapable.js:108:46)
    at innerCallback (/path/to/project/node_modules/enhanced-resolve/lib/Resolver.js:125:19)
    at loggingCallbackWrapper (/path/to/project/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at /path/to/project/node_modules/tapable/lib/Tapable.js:210:15
    at innerCallback (/path/to/project/node_modules/enhanced-resolve/lib/Resolver.js:123:11)
``` 

**Reproducing:** 

To reproduce error you need to use:
- webpack v2.1.0-beta.27
- extract-text-webpack-plugin (*v2.0.0-beta.4*)

And incorrect extract-text-webpack-plugin configuration.

> [source](https://github.com/webpack/extract-text-webpack-plugin#api)
> *Note:* Correct extract-text-webpack-plugin configuration uses: `{loader: String, query: Object}` not {loader: String, options: Object} format for loaders

```javascript
{
  test: /\.(scss)$/i,
  loader: ExtractTextPlugin.extract({
    loader: [
      {
        loader: 'css-loader',
        options: {
          importLoaders: 3,
          minimize: true,
          sourceMap: false
        }
      },
      {loader: 'postcss-loader'},
      {loader: 'resolve-url-loader'},
      {
        loader: 'sass-loader',
        options: {
          // Enable sourcemaps for resolve-url-loader to work properly
          sourceMap: true
        }
      }
    ]
  })
}
```

**Fix?**

By debugging code, found the source of the issue to be here:
https://github.com/webpack/webpack/blob/master/lib/Compilation.js#L329

```javascript
// In V8, the Error objects keep a reference to the functions on the stack. These warnings &
// errors are created inside closures that keep a reference to the Compilation, so errors are
// leaking the Compilation object. Setting _this to null workarounds the following issue in V8.
// https://bugs.chromium.org/p/chromium/issues/detail?id=612191
_this = null;
```

I think that the problem occurs because a non-trailing iteratee of `async.forEach` throws an error, which stops `async.forEach` iteration and calls the  error callback where `_this = null` is called. As `async.forEach` runs in parallel by running `_this = null` we destroy context for the parallel still running iteratees, which creates a runtime error.

**I fixed it by commenting the destruction of `_this`,**

```javascript
// In V8, the Error objects keep a reference to the functions on the stack. These warnings &
// errors are created inside closures that keep a reference to the Compilation, so errors are
// leaking the Compilation object. Setting _this to null workarounds the following issue in V8.
// https://bugs.chromium.org/p/chromium/issues/detail?id=612191
// _this = null;
```

Another way to fix it might be running [`async.eachSeries`](http://caolan.github.io/async/docs.html#eachSeries) instead of current [`async.forEach`](http://caolan.github.io/async/docs.html#each). But I'm not familiar with the codebase, so I don't know the performance consequences of running it in series

**Comment by samkuhn** [comment]
I have the same issue - commenting out the _this = null  "fixed" the problem for me too.

**Comment by sokra** [comment]
> webpack v2.0.0-beta.4

Could you use the most recent beta version? (v2.1.0-beta.27)

**Comment by renarsvilnis** [comment]
@sokra Sry that was a typo there, I am using beta 27.

> **Webpack version:**
> 2.1.0-beta.27

**Comment by begincalendar** [comment]
I'm on v2.1.0-beta.27 and commenting out that line does remove two of the three errors I am getting, but it still leaves this one:

```
TypeError: Cannot read property 'addChunk' of null                               
    at Compilation.<anonymous> (/path_to_project/node_modules/webpack/lib/Compilation.js:532:9)
    at Array.forEach (native)                                                    
    at Compilation.seal (/path_to_project/node_modules/webpack/lib/Compilation.js:525:22)
    at /path_to_project/node_modules/webpack/lib/Compiler.js:473:16              
    at /path_to_project/node_modules/tapable/lib/Tapable.js:152:11               
    at done (/path_to_project/node_modules/karma-webpack/node_modules/async/lib/async.js:132:19)
    at /path_to_project/node_modules/karma-webpack/node_modules/async/lib/async.js:32:16
    at Plugin.<anonymous> (/path_to_project/node_modules/karma-webpack/lib/karma-webpack.js:175:7)
    at Compilation.<anonymous> (/path_to_project/node_modules/webpack/lib/Compilation.js:443:11)
    at /path_to_project/node_modules/webpack/lib/Compilation.js:420:13           
    at /path_to_project/node_modules/webpack/lib/Compilation.js:332:11           
    at /path_to_project/node_modules/async/dist/async.js:356:16                  
    at iteratorCallback (/path_to_project/node_modules/async/dist/async.js:934:13)
    at /path_to_project/node_modules/async/dist/async.js:840:16                  
    at /path_to_project/node_modules/webpack/lib/Compilation.js:332:11           
    at /path_to_project/node_modules/async/dist/async.js:356:16
```

The file that is causing these errors to occur is a test file, which gets invoked via karma and karma-webpack.
If I strip the file down to just this line:
```
import 'enzyme';
```
...the errors still occur.

So for me personally, these errors are getting invoked when I try to import enzyme.

**Comment by TheLarkInn** [comment]
Alright just to make sure, mind checking this in RC?

**Comment by begincalendar** [comment]
@TheLarkInn  I just checked v2.2.0-rc.2 and the problems that I personally had (relating to this issue), have disappeared.

**Comment by TheLarkInn** [comment]
👏🏼😍🙇 awesome thank you for checking.

**Comment by madaz** [comment]
I'm still experiencing this error with the following config, if i comment out `enzyme` it works

webpack@2.2.1
enzyme@2.6.0
karma@1.5.0
karma-webpack@2.0.2

![image](https://cloud.githubusercontent.com/assets/1139901/23885891/402b4384-08c2-11e7-90e1-44f38e51c00d.png)

**Comment by lechu1985** [comment]
I was experiencing the same problem as @madaz. In my case issue with my code was covered by an issue in karma-webpack. 

I got it fixed by removing `bail: true` in the webpack config for tests (as suggested by @gringocl in https://github.com/webpack-contrib/karma-webpack/issues/214). This allowed for better investigation of the root cause. 

Currently it works in setup:
webpack@2.3.2
karma@1.5.0
karma-webpack@2.0.3
