### ISSUE TITLE
Webpack output generates call stack error when templateUrl used in Angular 2 component.

### ISSUE THREAD

**Issue by sqlsolver** [webpack/webpack#3334]
Webpack 2.1.0-beta.27
**Do you want to request a *feature* or report a *bug*?**
Report a bug.

Asked both places while trying to resolve - no suggestions.
**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

Use Angular's templateUrl syntax inside a component definition like:
````
@Component ({
    selector: 'my-component',
    templateUrl: './view/myview.html'
})
````
 Problem is resolved by loading HTML inline using just 'template' like:
````
@Component ({
    selector: 'my-component',
    template: `
<p>content</>
`
})
````
Typical error in Chrome console:
````
Navigated to http://www.angularsolver.com/
Loading AppModuleRoot
XHR finished loading: GET "http://www.angularsolver.com/view/appTemplate.html".
XHR finished loading: GET "http://www.angularsolver.com/view/appEntry.a871525a7d84b5bc0430.css".
EXCEPTION: Error in view/appTemplate.html:12:8 caused by: Maximum call stack size exceeded
ORIGINAL EXCEPTION: Maximum call stack size exceeded
ORIGINAL STACKTRACE:
RangeError: Maximum call stack size exceeded
    at new ViewWrappedError (http://www.angularsolver.com/appEntry.js:45117:16)
    at _View_AppComponent0.DebugAppView._rethrowWithContext (http://www.angularsolver.com/appEntry.js:61176:23)
    at _View_AppComponent0.DebugAppView.create (http://www.angularsolver.com/appEntry.js:61122:18)
    at _View_AppComponent0.createInternal (/AppModuleRoot/AppComponent/component.ngfactory.js:70:15)
    at _View_AppComponent0.AppView.create (http://www.angularsolver.com/appEntry.js:60919:21)
    at _View_AppComponent0.DebugAppView.create (http://www.angularsolver.com/appEntry.js:61119:44)
    at _View_AppComponent0.createInternal (/AppModuleRoot/AppComponent/component.ngfactory.js:70:15)

24k lines so truncated!!!

    at ComponentFactory.create (http://www.angularsolver.com/appEntry.js:44866:36)
    at ApplicationRef_.bootstrap (http://www.angularsolver.com/appEntry.js:28595:40)
    at http://www.angularsolver.com/appEntry.js:28504:89
    at Array.forEach (native)
    at PlatformRef_._moduleDoBootstrap (http://www.angularsolver.com/appEntry.js:28504:42)
    at http://www.angularsolver.com/appEntry.js:28472:27
    at ZoneDelegate.invoke (http://www.angularsolver.com/appEntry.js:91969:26)
    at Object.onInvoke (http://www.angularsolver.com/appEntry.js:30745:37)
    at ZoneDelegate.invoke (http://www.angularsolver.com/appEntry.js:91968:32)
    at Zone.run (http://www.angularsolver.com/appEntry.js:91851:43)
    at http://www.angularsolver.com/appEntry.js:92239:57
    at ZoneDelegate.invokeTask (http://www.angularsolver.com/appEntry.js:92002:35)
    at Object.onInvokeTask (http://www.angularsolver.com/appEntry.js:30736:37)
    at ZoneDelegate.invokeTask (http://www.angularsolver.com/appEntry.js:92001:40)
    at Zone.runTask (http://www.angularsolver.com/appEntry.js:91891:47)
    at drainMicroTaskQueue (http://www.angularsolver.com/appEntry.js:92138:35)
    at XMLHttpRequest.ZoneTask.invoke (http://www.angularsolver.com/appEntry.js:92076:25)
ERROR CONTEXT:
DebugContext {_view: _View_AppComponent0, _nodeIndex: 22, _tplRow: 12, _tplCol: 8}
ViewWrappedError {_nativeError: Error: Error in view/appTemplate.html:12:8 caused by: Maximum call stack size exceeded
    at ViewWr…, originalError: RangeError: Maximum call stack size exceeded
    at new ViewWrappedError (http://www.angularsolver.c…, context: DebugContext}
````
Typical error in Firefox console:
````
EXCEPTION: too much recursionappEntry.js:44828:9
ErrorHandler.prototype.handleError()appEntry.js:44828
_callAndReportToErrorHandler/<()appEntry.js:29030
ZoneDelegate.prototype.invoke()appEntry.js:92119
NgZone</NgZone.prototype.forkInnerZoneWithAngularBehavior/this.inner<.onInvoke()appEntry.js:31402
ZoneDelegate.prototype.invoke()appEntry.js:92118
Zone.prototype.run()appEntry.js:92001
scheduleResolveOrReject/<()appEntry.js:92389
ZoneDelegate.prototype.invokeTask()appEntry.js:92152
NgZone</NgZone.prototype.forkInnerZoneWithAngularBehavior/this.inner<.onInvokeTask()appEntry.js:31393
ZoneDelegate.prototype.invokeTask()appEntry.js:92151
Zone.prototype.runTask()appEntry.js:92041
drainMicroTaskQueue()appEntry.js:92288
ZoneTask/this.invoke()appEntry.js:92226

21:10:07.397 ORIGINAL STACKTRACE:appEntry.js:44833:13
ErrorHandler.prototype.handleError()appEntry.js:44833
_callAndReportToErrorHandler/<()appEntry.js:29030
ZoneDelegate.prototype.invoke()appEntry.js:92119
NgZone</NgZone.prototype.forkInnerZoneWithAngularBehavior/this.inner<.onInvoke()appEntry.js:31402
ZoneDelegate.prototype.invoke()appEntry.js:92118
Zone.prototype.run()appEntry.js:92001
scheduleResolveOrReject/<()appEntry.js:92389
ZoneDelegate.prototype.invokeTask()appEntry.js:92152
NgZone</NgZone.prototype.forkInnerZoneWithAngularBehavior/this.inner<.onInvokeTask()appEntry.js:31393
ZoneDelegate.prototype.invokeTask()appEntry.js:92151
Zone.prototype.runTask()appEntry.js:92041
drainMicroTaskQueue()appEntry.js:92288
ZoneTask/this.invoke()appEntry.js:92226
````
Webpack builds completed without error, but browser console errors were thrown by the output file - which for this app is appEntry.js.

**What is the expected behavior?**
Expect to write HTML in partials and load them using Angular's templateUrl syntax inside a component definition.

See full discussion at https://github.com/angular/angular/issues/7930. This thread attributes the problem solely to Angular, however the same configuration doesn't fail with SystemJS build therefore I'm opening the issue here.

**If this is a feature request, what is motivation or use case for changing the behavior?**
Bug - but motivation would be to assure that webpack successfully builds an Angular 2 project.

**Please mention other relevant information such as the browser version, Node.js version, Operating System and programming language.**
Typescript@2.0.3 and Node@7.0.0

Build in Windows/Visual Studio 2015 and push to GitHub from within IDE. Pull from GitHub to shared hosting directory on Apache host. All builds done on host with command:
./node_modules/webpack/bin/webpack.js --config ./config/webpack.common.js --progress --profile --colors --cache false --devtool source-map

Note: Cannot use rimraf on shared hosting (no root).

**Comment by jhnns** [comment]
Sorry, this does not look like a problem with webpack itself. It's probably a problem with the webpack integration into the angular 2 toolchain (aka the angular-cli I suppose). Maybe @TheLarkInn can give us insights here.

Until it's clear that this is webpack's fault, I will close this one.

**Comment by sqlsolver** [comment]
Nope, not using the CLI and I think it's a mistake to close - don't you folks work together with the A2 people? :-) This is strictly around the processing of that one tag, templateUrl, to call the template from a partial vs. writing it inline. I think webpack owns it because packaging with SystemJs or not packaging at all doesn't fail, and the error is _coming directly from code generated by the webpack build_.

Here's my webpack config:
````
var webpack = require('webpack');
var HtmlWebpackPlugin = require('html-webpack-plugin');
var ExtractTextPlugin = require('extract-text-webpack-plugin');
var helpers = require('./helpers');
const path = require("path");
const ENV = process.env.NODE_ENV = process.env.ENV = 'production';

module.exports = {
    entry: {
        'appEntry': ['./app/polyfills.js', './config/vendor.ts', './app/appModule.ts', './node_modules/office-ui-fabric/dist/css/fabric.components.css', './node_modules/office-ui-fabric/dist/css/fabric.css']        
    },
    output: {
        path: './',
        filename: '[name].js'
    },
    resolve: {
        modules: [path.resolve(__dirname, "app"), "node_modules"],
        alias: {
            jquery: './node_modules/jquery/src/jquery.js'
        }
    },

    module: {
        loaders: [
          {
              test: /\.ts$/,
              loaders: ['awesome-typescript-loader', 'angular2-template-loader']
          },
          {
              test: /\.html$/,
              loader: 'html'
          },
          {
              test: /\.(png|jpe?g|gif|svg|woff|woff2|ttf|eot|ico)$/,
              loader: 'file?name=media/[name].[hash].[ext]'
          },
          {
              test: /\.css$/,
              loader: ExtractTextPlugin.extract({ fallbackLoader: 'style-loader', loader: 'css-loader' })
          }
        ]
    },
    plugins: [
      new webpack.optimize.CommonsChunkPlugin({
          name: ['appEntry'],
          minChunks: Infinity
      }),
      new ExtractTextPlugin({
          filename: "[name].css",
          disable: false,
          allChunks: true
      }),
      new HtmlWebpackPlugin({
          title: 'AngularSolver Entry Template',
          template: './app/view/index.ejs',
          filename: 'index.html',
          inject: 'body'
      }),
      new webpack.ContextReplacementPlugin(
          // The (\\|\/) piece accounts for path separators in *nix and Windows
          /angular(\\|\/)core(\\|\/)(esm(\\|\/)src|src)(\\|\/)linker/,
          root('./app') // location of your src
        )
    ]
}

function root(__path) {
    return path.join(__dirname, __path);
}
````
Somehow webpack is having trouble building the view when the template is in a partial vs. inline.

**Comment by Kovensky** [comment]
It seems that System.js is willing to load files from "outside", but webpack can only load files it knows about beforehand. The solution at https://github.com/angular/angular/issues/7930#issuecomment-252481653 would make both System and webpack happy, as the explicit import tells webpack about the resource.

**Comment by sqlsolver** [comment]
@Kovensky that makes sense, however trying to import as shown in [Donohue's comment](https://github.com/angular/angular/issues/7930#issuecomment-252481653) I get a typescript error that it cannot import the html partial since it's not a module. Since templateUrl is an accepted convention within Angular 2, webpack should know how to build it.

**Comment by Zigzauer** [comment]
just use:  template: require('./templatet.html') instead of templateUrl: require('./items.component.html')
