### ISSUE TITLE
Webpack Duplicate identifier 'PropertyKey'

### ISSUE THREAD

**Issue by CristianBarragan** [webpack/webpack#3344]
While trying to deploy my angular 2 app using VS2015. There are two errors, at the moment of running webpack, but none errors at the moment of doing a building in vs2015

```
C:\Users\asus\Desktop\C# Web\Core\AngularAPI\ApiAngWebPack\WebApp> cmd /c SET NODE_ENV=development&& webpack -d --color
@@@@@@@@@ USING DEVELOPMENT @@@@@@@@@@@@@@@
clean-webpack-plugin: C:\Users\asus\Desktop\C# Web\Core\AngularAPI\ApiAngWebPack\WebApp\wwwroot\dist has been removed.
clean-webpack-plugin: C:\Users\asus\Desktop\C# Web\Core\AngularAPI\ApiAngWebPack\WebApp\wwwroot\fonts has been removed.
clean-webpack-plugin: C:\Users\asus\Desktop\C# Web\Core\AngularAPI\ApiAngWebPack\WebApp\wwwroot\assets has been removed.
Hash: ab986b13a96ef5707853
Version: webpack 2.1.0-beta.25
Time: 18114ms
                                           Asset       Size  Chunks             Chunk Names
  assets/glyphicons-halflings-regular-f4769f.eot    20.1 kB          [emitted]  
  assets/glyphicons-halflings-regular-f72146.svg     109 kB          [emitted]  
  assets/glyphicons-halflings-regular-e18bbf.ttf    45.4 kB          [emitted]  
 assets/glyphicons-halflings-regular-fa2772.woff    23.4 kB          [emitted]  
assets/glyphicons-halflings-regular-448c34.woff2      18 kB          [emitted]  
                              dist/app.bundle.js     8.8 MB       0  [emitted]  app
                                      index.html  426 bytes          [emitted]  
                            assets/damienbod.jpg    4.85 kB          [emitted]  
    + 805 hidden modules
ERROR in [default] C:\Users\asus\Desktop\C# Web\Core\AngularAPI\ApiAngWebPack\WebApp\node_modules\typescript\lib\lib.es2015.core.d.ts:17:13 
Duplicate identifier 'PropertyKey'.
ERROR in [default] C:\Users\asus\Desktop\C# Web\Core\AngularAPI\ApiAngWebPack\node_modules\@types\core-js\index.d.ts:21:13 
Duplicate identifier 'PropertyKey'.
Child html-webpack-plugin for "index.html":
        + 1 hidden modules
Process terminated with code 2.
```
This issues are not allowing to generate a new build. This is the result showed from the browser side

```
Uncaught Error: Module build failed: Error: EPERM: operation not permitted, open 'C:\Users\asus\Desktop\C# Web\Core\AngularAPI\ApiAngWebPack\WebApi\node_modules\webpack\buildin\global.js'
    at Error (native)
    at Error (native)
    at eval (eval at <anonymous> (http://localhost:18678/dist/app.bundle.js:530:1), <anonymous>:1:7)
    at Object.<anonymous> (http://localhost:18678/dist/app.bundle.js:530:1)
    at __webpack_require__ (http://localhost:18678/dist/app.bundle.js:20:30)
    at eval (eval at <anonymous> (http://localhost:18678/dist/app.bundle.js:7659:1), <anonymous>:182:44)
    at Object.<anonymous> (http://localhost:18678/dist/app.bundle.js:7659:1)
    at __webpack_require__ (http://localhost:18678/dist/app.bundle.js:20:30)
    at Object.eval (eval at <anonymous> (http://localhost:18678/dist/app.bundle.js:4799:1), <anonymous>:1:113)
    at eval (eval at <anonymous> (http://localhost:18678/dist/app.bundle.js:4799:1), <anonymous>:71:30)
    at Object.<anonymous> (http://localhost:18678/dist/app.bundle.js:4799:1)
    at __webpack_require__ (http://localhost:18678/dist/app.bundle.js:20:30)

```

Checking within the solution explorer, there is no such buildin/global folder at node_modules/webpack. I open a [SO question](http://stackoverflow.com/questions/40731616/webpack-duplicate-identifier-propertykey) but since it is something very specific to webpack, I will add it here too. Not sure if its a sum of errors or it is just one. I do not believe webpack creates buildings in node_modules folder @vs2015.

Edit, to add versions:

package.json

"webpack": "2.1.0-beta.27",
"webpack-dev-server": "^1.16.2"

Found some issues related with vs2015 about this, but in my case there is no problems from vs2015 side [Similar SO question](http://stackoverflow.com/questions/31322525/typescript-confusing-duplicate-identifier-error-message)

**Comment by Kovensky** [comment]
The ERRORs look like typescript configuration issue, rather than a webpack issue. Anyway, don't use `@types/core-js`. It's severely outdated, and almost everything in it is contained in the standard typescript libraries that you specify with the `"lib"` option in `tsconfig.json`.

You're using a version of webpack-dev-server that is possibly incompatible with webpack 2; try using `^2.1.0-beta.11`.

Also, `buildin/global.js` should be [this file](https://github.com/webpack/webpack/blob/2ff9a24/buildin/global.js), which is included in the npm distribution.

**Comment by CristianBarragan** [comment]
First of all, thank you for your reply, Indeed I was not using the latest webpack-dev-server. I updated to the version provided above and I am still having the same issues:

I am not using @types/core-js,  as far as I know. I was having several errors due to an old typescript version, I update to the last typescript version and all errors went away. I am using ES6 at this moment, please have a look to my tsconfig.json and my webpack.dev.js

tsconfig.json

```
{
  "compilerOptions": {
    "target": "es6",
    "module": "es2015",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": true,
    "noImplicitAny": true,
    "skipLibCheck": true,
    "lib": [
      "es6",
      "dom"
    ],
    "types": [
      "node"
    ]
  },
  "files": [
    "angular2App/app/app.module.ts",
    "angular2App/main.ts"
  ],
  "awesomeTypescriptLoaderOptions": {
    "useWebpackText": true
  },
  "compileOnSave": false,
  "buildOnSave": false
}
```
webpack.dev.js

```
var path = require('path');

var webpack = require('webpack');

var HtmlWebpackPlugin = require('html-webpack-plugin');
var CopyWebpackPlugin = require('copy-webpack-plugin');
var CleanWebpackPlugin = require('clean-webpack-plugin');

console.log("@@@@@@@@@ USING DEVELOPMENT @@@@@@@@@@@@@@@");

module.exports = {

    devtool: 'source-map',

    entry: {
        'app': './angular2App/main.ts' // JiT compilation
    },

    output: {
        path: "./wwwroot/",
        filename: 'dist/[name].bundle.js',
        publicPath: "/"
    },

    resolve: {
        extensions: ['.ts', '.js', '.json', '.css', '.scss', '.html']
    },

    devServer: {
        historyApiFallback: true,
        stats: 'minimal',
        outputPath: path.join(__dirname, 'wwwroot/')
    },

    module: {
        rules: [
            {
                test: /\.ts$/,
                loaders: [
                    'awesome-typescript-loader',
                    'angular2-template-loader',
                    'source-map-loader'
                ]
            },
            {
                test: /\.(png|jpg|gif|ico|woff|woff2|ttf|svg|eot)$/,
                exclude: /node_modules/,
                loader: "file-loader?name=assets/[name]-[hash:6].[ext]",
            },
            {
                test: /\.css$/,
                exclude: /node_modules/,
                loader: "style-loader!css-loader"
            },
            {
                test: /\.scss$/,
                exclude: /node_modules/,
                loaders: ["style-loader", "css-loader", "sass-loader"]
            },
            {
                test: /\.html$/,
                loader: 'raw-loader'
            }
        ],
        exprContextCritical: false
    },

    plugins: [
        new CleanWebpackPlugin(
            [
                './wwwroot/dist',
                './wwwroot/fonts',
                './wwwroot/assets'
            ]
        ),

        new HtmlWebpackPlugin({
            filename: 'index.html',
            inject: 'body',
            template: 'angular2App/index.html'
        }),

        new CopyWebpackPlugin([
            { from: './angular2App/images/*.*', to: "assets/", flatten: true }
        ])
    ]

};
```
package.json

```
{
  "version": "1.0.0",
  "description": "",
  "main": "wwwroot/index.html",
  "author": "",
  "license": "ISC",
  "scripts": {
    "ngc": "ngc -p ./tsconfig-aot.json",
    "start": "concurrently \"webpack-dev-server --inline --progress --port 8080\" \"dotnet run\" ",
    "webpack-dev": "set NODE_ENV=development&& webpack",
    "webpack-prod": "set NODE_ENV=production&& webpack",
    "build": "npm run webpack-dev",
    "buildProduction": "npm run ngc && npm run webpack-prod"
  },
  "dependencies": {
    "@angular/common": "~2.2.0",
    "@angular/compiler": "~2.2.0",
    "@angular/core": "~2.2.0",
    "@angular/forms": "~2.2.0",
    "@angular/http": "~2.2.0",
    "@angular/platform-browser": "~2.2.0",
    "@angular/platform-browser-dynamic": "~2.2.0",
    "@angular/router": "~3.2.0",
    "@angular/upgrade": "~2.2.0",
    "angular-in-memory-web-api": "~0.1.16",
    "core-js": "^2.4.1",
    "reflect-metadata": "^0.1.8",
    "rxjs": "5.0.0-beta.12",
    "zone.js": "^0.6.25",

    "@angular/compiler-cli": "~2.2.0",
    "@angular/platform-server": "~2.2.0",
    "bootstrap": "^3.3.7",
    "ie-shim": "^0.1.0",

    "gulp-clean": "^0.3.2",
    "gulp-concat": "^2.6.1",
    "gulp-less": "^3.3.0",
    "gulp-sourcemaps": "^2.2.0",
    "gulp-typescript": "^3.1.3",
    "gulp-uglify": "^2.0.0",
    "gulp-util": "^3.0.7",
    "gulp-load-plugins": "^1.4.0",
    "pump": "^1.0.1",
    "gutil": "^1.6.4",
    "babel-register": "^6.18.0"


  },
  "devDependencies": {
    "@types/node": "^6.0.45",
    "angular2-template-loader": "^0.5.0",
    "awesome-typescript-loader": "^2.2.4",
    "clean-webpack-plugin": "^0.1.9",
    "concurrently": "^3.1.0",
    "copy-webpack-plugin": "^2.1.3",
    "css-loader": "^0.23.0",
    "file-loader": "^0.8.4",
    "html-webpack-plugin": "^2.8.1",
    "jquery": "^2.2.0",
    "json-loader": "^0.5.3",
    "node-sass": "^3.10.1",
    "raw-loader": "^0.5.1",
    "rimraf": "^2.5.2",
    "sass-loader": "^4.0.2",
    "source-map-loader": "^0.1.5",
    "style-loader": "^0.13.0",
    "ts-helpers": "^1.1.1",
    "typescript": "^2.0.10",
    "url-loader": "^0.5.6",
    "webpack": "2.1.0-beta.27",
    "webpack-dev-server": "^2.1.0-beta.11"
  }
}
```
