### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by tjhowe** [webpack/webpack#3370]
Hi, 

Hope someone can help as I'm struggling with a build error with a very late deadline (not thinking totally clearly)!

I'm having trouble with a build script giving this npm error log. 

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'build' ]
2 info using npm@2.15.1
3 info using node@v4.4.3
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info prebuild app@1.0.0
6 verbose unsafe-perm in lifecycle true
7 info build app@1.0.0
8 verbose unsafe-perm in lifecycle true
9 info app@1.0.0 Failed to exec build script
10 verbose stack Error: app@1.0.0 build: `babel-node tools/build.js`
10 verbose stack Exit status 1
10 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:217:16)
10 verbose stack     at emitTwo (events.js:87:13)
10 verbose stack     at EventEmitter.emit (events.js:172:7)
10 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
10 verbose stack     at emitTwo (events.js:87:13)
10 verbose stack     at ChildProcess.emit (events.js:172:7)
10 verbose stack     at maybeClose (internal/child_process.js:827:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
11 verbose pkgid app@1.0.0
12 verbose cwd /Users/t.howe/obongjayar
13 error Darwin 15.6.0
14 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
15 error node v4.4.3
16 error npm  v2.15.1
17 error code ELIFECYCLE
18 error app@1.0.0 build: `babel-node tools/build.js`
18 error Exit status 1
19 error Failed at the app@1.0.0 build script 'babel-node tools/build.js'.
19 error This is most likely a problem with the app package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     babel-node tools/build.js
19 error You can get information on how to open an issue for this project with:
19 error     npm bugs app
19 error Or if that isn't available, you can get their info via:
19 error
19 error     npm owner ls app
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]

build.js file is as follows.

```
/*eslint-disable no-console */
import webpack from 'webpack';
import webpackConfig from '../webpack.config.prod';
import colors from 'colors';

process.env.NODE_ENV = 'production';

console.log('Generating build'.blue);

webpack(webpackConfig).run((err, stats) => {
  if (err) {
    console.log(err.bold.red);
    return 1;
  }

  const jsonStats = stats.toJson();

  if (jsonStats.hasErrors) {
    return jsonStats.errors.map(error => console.log(error.red));
  }

  if (jsonStats.hasWarnings) {
    console.log('Webpack has following warnings'.bold.yellow);
    jsonStats.warnings.map(warning => console.log(warning.yellow));
  }
  console.log(`webpack stats: ${stats}`);

  console.log('Your app has been compiled in prod mode and written to dist.'.green);

  return 0;
});

```
Thanks,

Tom

**Comment by tjhowe** [comment]
Solved - Was using loaders instead of loader in css config.
