### ISSUE TITLE
Code splitting not working for me, server-side

### ISSUE THREAD

**Issue by callumacrae** [webpack/webpack#3448]
This code works:

```js
//      require(['./WorldMap.vue'], (SkWorldMap) => {
//        this.loading = false;
//        this.maybeWorldMap = SkWorldMap;
//      });
```

This code does not:

```js
      if (typeof window === 'undefined') {
        return;
      }

      require(['./WorldMap.vue'], (SkWorldMap) => {
        this.loading = false;
        this.maybeWorldMap = SkWorldMap;
      });
```

Unfortunately, I don't have a proper error right now except for "window is not defined":

```
ReferenceError: window is not defined
    at e.__esModule.default (__vue_ssr_bundle__:1:478)
    at __vue_ssr_bundle__:1:1052
    at r.(anonymous function).exports (__vue_ssr_bundle__:1:146)
    at Object.<anonymous> (__vue_ssr_bundle__:1:285)
    at /Users/callumacrae/Sites/samknows/website-vue/node_modules/vue-server-renderer/build.js:6152:21
    at runInVm (/Users/callumacrae/Sites/samknows/website-vue/node_modules/vue-server-renderer/build.js:6144:10)
    at Object.renderToStream (/Users/callumacrae/Sites/samknows/website-vue/node_modules/vue-server-renderer/build.js:6175:9)
    at server.get (/Users/callumacrae/Sites/samknows/website-vue/server/index.js:29:35)
    at Layer.handle [as handle_request] (/Users/callumacrae/Sites/samknows/website-vue/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/callumacrae/Sites/samknows/website-vue/node_modules/express/lib/router/route.js:131:13)
```

I'm working on getting a proper error (Vue SSR doesn't have good errors the way I'm using it, though: https://github.com/vuejs/vue/issues/4376).

Has anyone seen this before? Nothing in WorldMap.vue uses `window`.

**Comment by callumacrae** [comment]
Here's a (slightly) better error!

```
ReferenceError: window is not defined
    at /Users/callumacrae/Sites/samknows/website-vue/dist/static/js/app.1ad61981f4d1c5789bc7.js:13:43
    at /Users/callumacrae/Sites/samknows/website-vue/dist/static/js/app.1ad61981f4d1c5789bc7.js:104:10
    at webpackUniversalModuleDefinition (/Users/callumacrae/Sites/samknows/website-vue/dist/static/js/app.1ad61981f4d1c5789bc7.js:3:20)
    at Object.<anonymous> (/Users/callumacrae/Sites/samknows/website-vue/dist/static/js/app.1ad61981f4d1c5789bc7.js:10:3)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
```

It's right at the top, `var parentJsonpFunction = window["webpackJsonp"];`.

```js
(function webpackUniversalModuleDefinition(root, factory) {
	if(typeof exports === 'object' && typeof module === 'object')
		module.exports = factory();
	else if(typeof define === 'function' && define.amd)
		define([], factory);
	else {
		var a = factory();
		for(var i in a) (typeof exports === 'object' ? exports : root)[i] = a[i];
	}
})(this, function() {
return /******/ (function(modules) { // webpackBootstrap
/******/ 	// install a JSONP callback for chunk loading
/******/ 	var parentJsonpFunction = window["webpackJsonp"];  // <-------
/******/ 	window["webpackJsonp"] = function webpackJsonpCallback(chunkIds, moreModules) {
/******/ 		// add "moreModules" to the modules object,
/******/ 		// then flag all "chunkIds" as loaded and fire callback
/******/ 		var moduleId, chunkId, i = 0, callbacks = [];
/******/ 		for(;i < chunkIds.length; i++) {
/******/ 			chunkId = chunkIds[i];
```

Given that I don't actually want this stuff to be rendered server-side, is there any way to skip this on the server?

**Comment by TheLarkInn** [comment]
What do you have for the `target` property in your config?

**Comment by callumacrae** [comment]
Nothing, so `web`. Setting it to `node` makes it work server-side, but breaks it client-side. Do I have to do a separate build for each?

**Comment by jhnns** [comment]
Yes

**Comment by callumacrae** [comment]
I'm not shipping node code to the browser, I'm shipping browser code to node. You know, server-side rendering?

Or does webpack not support server-side rendering without configuration hackyness?

**Comment by dustinsoftware** [comment]
I also ran into this problem. Generating two bundles solved the issue for me (easy to do from a single webpack config)

**Comment by g-patel** [comment]
@dustinsoftware how to do it using one webpack config? I am having the exact same issue. It works exclusively, nut not on both client side and server side.

**Comment by g-patel** [comment]
@callumacrae how did you fix it?

**Comment by dustinsoftware** [comment]
This entry in the docs was helpful: https://webpack.js.org/concepts/configuration/#multiple-targets

Return an array instead of an object when exporting your config. In your case, you may only want to use `web` and `node` as targets.

**Comment by guoyaojie** [comment]
i`m already fix it,u have to add some config like this :
target: 'node',
    node: {
        __filename: true,
        __dirname: true
    },
so that the webpack knows its a  node project.
