### ISSUE TITLE
Crash with rule.use as a function returning array

### ISSUE THREAD

**Issue by daltones** [webpack/webpack#3484]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When the property `use` of a rule is defined as a function, it only works if it returns a single loader object. If it returns an array of loaders, it will crash with this error:
```
[...]/node_modules/enhanced-resolve/lib/Resolver.js:151
    var idxQuery = identifier.indexOf("?");
                             ^

TypeError: Cannot read property 'indexOf' of undefined
    at Resolver.parse ([...]/node_modules/enhanced-resolve/lib/Resolver.js:151:27)
    at Resolver.<anonymous> ([...]/node_modules/enhanced-resolve/lib/ParsePlugin.js:16:25)
    at Resolver.applyPluginsParallelBailResult1 ([...]/node_modules/tapable/lib/Tapable.js:252:14)
    at beforeInnerCallback ([...]/node_modules/enhanced-resolve/lib/Resolver.js:112:19)
    at loggingCallbackWrapper ([...]/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at Resolver.applyPluginsAsyncSeriesBailResult1 ([...]/node_modules/tapable/lib/Tapable.js:145:46)
    at Resolver.doResolve ([...]/node_modules/enhanced-resolve/lib/Resolver.js:100:11)
    at Resolver.<anonymous> ([...]/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:36:12)
    at Resolver.applyPluginsParallelBailResult1 ([...]/node_modules/tapable/lib/Tapable.js:252:14)
    at beforeInnerCallback ([...]/node_modules/enhanced-resolve/lib/Resolver.js:112:19)
    at loggingCallbackWrapper ([...]/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at Resolver.applyPluginsAsyncSeriesBailResult1 ([...]/node_modules/tapable/lib/Tapable.js:145:46)
    at Resolver.doResolve ([...]/node_modules/enhanced-resolve/lib/Resolver.js:100:11)
    at Resolver.resolve ([...]/node_modules/enhanced-resolve/lib/Resolver.js:74:14)
    at [...]/node_modules/webpack/lib/NormalModuleFactory.js:252:12
    at [...]/node_modules/async/dist/async.js:1008:9
```

**If the current behavior is a bug, please provide the steps to reproduce.**
Just try some config with a `use` function returning array. Something like this:
```js
module.exports = {
  module: {
    rules: [
      {
        test: /\.gif$/,
        use: function (data) {
          // if it returned a single loader, it wouldn't fail
          // return {loader: 'file-loader'};

          // returning a chain of loaders: will fail
          return [
            {loader: 'file-loader'},
            {loader: 'image-webpack-loader'}
          ];
        }
      }
    ]
  }
};
```

**What is the expected behavior?**
It should work returning an array of loaders for chaining, as it works defining a plain array to `use`.

**Please mention other relevant information such as the browser version, Node.js version, Operating System and programming language.**
Node.js: v7.2.1
Webpack: v2.2.0-rc.0

**Comment by daltones** [comment]
I was looking the code and, if I understood correctly, I realized that:
* `lib/RuleSet.js` treats `use` in a way that only expects that functions return a single loader object.
* So it is still possible to make a chain by declaring an array of loaders or functions returning a loader. (https://github.com/webpack/webpack/blob/v2.2.0-rc.0/lib/RuleSet.js#L218)
* Seems okay, but now there's a problem with the schema that forbids that kind of configuration. (https://github.com/webpack/webpack/blob/v2.2.0-rc.0/schemas/webpackOptionsSchema.json#L610)

**Comment by TheLarkInn** [comment]
@daltones could I twist your arm into providing me a small reproducible example? This looks like it could be enough but just wanted to double check.
