### ISSUE TITLE
Failed compilation with v2.2.0-rc because ExternalModule.unbuild is not defined

### ISSUE THREAD

**Issue by beauroberts** [webpack/webpack#3511]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

The build fails with an exception with the stack trace below. I've been able to determine that `module.constructor.name` is "ExternalModule" and I have confirmed that `lib/ExternalModule.js` does not appear to define an `unbuild` method.

```
TypeError: module.unbuild is not a function
    at Compilation.addModule (/Users/johnroberts/workspace/git_home/shotgun-ux/shotgun-design-system/node_modules/webpack/lib/Compilation.js:99:9)
    at factoryCallback (/Users/johnroberts/workspace/git_home/shotgun-ux/shotgun-design-system/node_modules/webpack/lib/Compilation.js:248:26)
    at /Users/johnroberts/workspace/git_home/shotgun-ux/shotgun-design-system/node_modules/webpack/lib/NormalModuleFactory.js:243:4
    at /Users/johnroberts/workspace/git_home/shotgun-ux/extract-css-theme-webpack-plugin/node_modules/webpack/lib/ExternalModuleFactoryPlugin.js:84:12
    at handleExternalsAndCallback (/Users/johnroberts/workspace/git_home/shotgun-ux/extract-css-theme-webpack-plugin/node_modules/webpack/lib/ExternalModuleFactoryPlugin.js:52:8)
    at handleExternal (/Users/johnroberts/workspace/git_home/shotgun-ux/extract-css-theme-webpack-plugin/node_modules/webpack/lib/ExternalModuleFactoryPlugin.js:32:5)
    at handleExternals (/Users/johnroberts/workspace/git_home/shotgun-ux/extract-css-theme-webpack-plugin/node_modules/webpack/lib/ExternalModuleFactoryPlugin.js:38:14)
    at next (/Users/johnroberts/workspace/git_home/shotgun-ux/extract-css-theme-webpack-plugin/node_modules/webpack/lib/ExternalModuleFactoryPlugin.js:58:8)
    at handleExternals (/Users/johnroberts/workspace/git_home/shotgun-ux/extract-css-theme-webpack-plugin/node_modules/webpack/lib/ExternalModuleFactoryPlugin.js:61:7)
    at ExternalModuleFactoryPlugin.<anonymous> (/Users/johnroberts/workspace/git_home/shotgun-ux/extract-css-theme-webpack-plugin/node_modules/webpack/lib/ExternalModuleFactoryPlugin.js:81:5)
    at /Users/johnroberts/workspace/git_home/shotgun-ux/shotgun-design-system/node_modules/webpack/lib/NormalModuleFactory.js:234:3
    at /Users/johnroberts/workspace/git_home/shotgun-ux/shotgun-design-system/node_modules/tapable/lib/Tapable.js:168:11
    at NormalModuleFactory.<anonymous> (/Users/johnroberts/workspace/git_home/shotgun-ux/extract-css-theme-webpack-plugin/node_modules/webpack/lib/NormalModuleReplacementPlugin.js:26:11)
    at NormalModuleFactory.applyPluginsAsyncWaterfall (/Users/johnroberts/workspace/git_home/shotgun-ux/shotgun-design-system/node_modules/tapable/lib/Tapable.js:172:13)
    at NormalModuleFactory.create (/Users/johnroberts/workspace/git_home/shotgun-ux/shotgun-design-system/node_modules/webpack/lib/NormalModuleFactory.js:218:8)
    at iteratorFactory (/Users/johnroberts/workspace/git_home/shotgun-ux/shotgun-design-system/node_modules/webpack/lib/Compilation.js:213:11)
    at /Users/johnroberts/workspace/git_home/shotgun-ux/shotgun-design-system/node_modules/async/lib/async.js:181:20
    at Object.async.forEachOf.async.eachOf (/Users/johnroberts/workspace/git_home/shotgun-ux/shotgun-design-system/node_modules/async/lib/async.js:233:13)
    at Object.async.forEach.async.each (/Users/johnroberts/workspace/git_home/shotgun-ux/shotgun-design-system/node_modules/async/lib/async.js:209:22)
    at Compilation.addModuleDependencies (/Users/johnroberts/workspace/git_home/shotgun-ux/shotgun-design-system/node_modules/webpack/lib/Compilation.js:194:8)
    at Compilation.processModuleDependencies (/Users/johnroberts/workspace/git_home/shotgun-ux/shotgun-design-system/node_modules/webpack/lib/Compilation.js:179:7)
    at /Users/johnroberts/workspace/git_home/shotgun-ux/shotgun-design-system/node_modules/webpack/lib/Compilation.js:319:12
    at /Users/johnroberts/workspace/git_home/shotgun-ux/shotgun-design-system/node_modules/webpack/lib/Compilation.js:126:4
    at Array.forEach (native)
    at callback (/Users/johnroberts/workspace/git_home/shotgun-ux/shotgun-design-system/node_modules/webpack/lib/Compilation.js:125:12)
    at /Users/johnroberts/workspace/git_home/shotgun-ux/shotgun-design-system/node_modules/webpack/lib/Compilation.js:149:10
    at /Users/johnroberts/workspace/git_home/shotgun-ux/shotgun-design-system/node_modules/webpack/lib/NormalModule.js:211:10
    at /Users/johnroberts/workspace/git_home/shotgun-ux/shotgun-design-system/node_modules/webpack/lib/NormalModule.js:164:10
    at /Users/johnroberts/workspace/git_home/shotgun-ux/shotgun-design-system/node_modules/loader-runner/lib/LoaderRunner.js:365:3
    at iterateNormalLoaders (/Users/johnroberts/workspace/git_home/shotgun-ux/shotgun-design-system/node_modules/loader-runner/lib/LoaderRunner.js:206:10)
undefined:1
```

**If the current behavior is a bug, please provide the steps to reproduce.**

I'm sorry, I don't know enough about webpack's inner workings to provide clear repro instructions.

**What is the expected behavior?**

The compilation completes successfully.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, Operating System and programming language.**

Node v6.9.1, Mac OS Sierra

**Comment by TheLarkInn** [comment]
What version of webpack are you seeing this in? We just released RC.1 FYI.

**Comment by beauroberts** [comment]
RC.1! I updated shortly after you published the new version.

**Comment by bebraw** [comment]
@beauroberts Can you provide a minimal standalone example? That would help a lot in isolating and debugging this.

**Comment by TheLarkInn** [comment]
Also if possible would you be able to provide the source for a specific plugin I see being referenced in this:

```
TypeError: module.unbuild is not a function
    at Compilation.addModule (/Users/johnroberts/workspace/git_home/shotgun-ux/shotgun-design-system/node_modules/webpack/lib/Compilation.js:99:9)
    at factoryCallback (/Users/johnroberts/workspace/git_home/shotgun-ux/shotgun-design-system/node_modules/webpack/lib/Compilation.js:248:26)
    at /Users/johnroberts/workspace/git_home/shotgun-ux/shotgun-design-system/node_modules/webpack/lib/NormalModuleFactory.js:243:4
    at /Users/johnroberts/workspace/git_home/shotgun-ux/extract-css-theme-webpack-plugin/node_modules/webpack/lib/ExternalModuleFactoryPlugin.js:84:12
```

Looks like the name is `extract-css-theme-webpack-plugin`

**Comment by SpaceK33z** [comment]
@beauroberts can you confirm this is the case and close the issue?
