### ISSUE TITLE
"Compiler (caching) should build not keep error after fix" test flanky

### ISSUE THREAD

**Issue by sokra** [webpack/webpack#3545]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
the test is flanky
``` text
1) Compiler (caching) should build not keep error after fix:
      Uncaught AssertionError: expected 0 to equal 1
      + expected - actual
      -0
      +1
      
      at Assertion.fail (/home/travis/build/webpack/webpack/node_modules/should/cjs/should.js:231:17)
      at Assertion.value (/home/travis/build/webpack/webpack/node_modules/should/cjs/should.js:305:19)
      at /home/travis/build/webpack/webpack/test/Compiler-caching.test.js:63:36
      at /home/travis/build/webpack/webpack/lib/Compiler.js:9:18029
      at Compiler.emitRecords (/home/travis/build/webpack/webpack/lib/Compiler.js:9:24142)
      at /home/travis/build/webpack/webpack/lib/Compiler.js:9:17431
      at /home/travis/build/webpack/webpack/lib/Compiler.js:9:23827
      at next (/home/travis/build/webpack/webpack/node_modules/tapable/lib/Tapable.js:118:11)
      at Compiler.<anonymous> (/home/travis/build/webpack/webpack/lib/performance/SizeLimitsPlugin.js:9:5297)
      at Compiler.applyPluginsAsyncSeries1 (/home/travis/build/webpack/webpack/node_modules/tapable/lib/Tapable.js:122:13)
      at Compiler.afterEmit (/home/travis/build/webpack/webpack/lib/Compiler.js:9:23477)
      at Compiler.<anonymous> (/home/travis/build/webpack/webpack/lib/Compiler.js:9:23346)
      at /home/travis/build/webpack/webpack/node_modules/async/dist/async.js:356:16
      at iteratorCallback (/home/travis/build/webpack/webpack/node_modules/async/dist/async.js:936:13)
      at /home/travis/build/webpack/webpack/node_modules/async/dist/async.js:840:16
      at Compiler.writeOut (/home/travis/build/webpack/webpack/lib/Compiler.js:9:22436)
      at Compiler.<anonymous> (/home/travis/build/webpack/webpack/lib/Compiler.js:9:21758)
      at /home/travis/build/webpack/webpack/node_modules/async/dist/async.js:3025:16
      at eachOfArrayLike (/home/travis/build/webpack/webpack/node_modules/async/dist/async.js:941:9)
      at eachOf (/home/travis/build/webpack/webpack/node_modules/async/dist/async.js:991:5)
      at Object.eachLimit (/home/travis/build/webpack/webpack/node_modules/async/dist/async.js:3089:3)
      at Compiler.emitFiles (/home/travis/build/webpack/webpack/lib/Compiler.js:9:20857)
      at Object.mkdirp (/home/travis/build/webpack/webpack/test/Compiler-caching.test.js:33:5)
      at Compiler.<anonymous> (/home/travis/build/webpack/webpack/lib/Compiler.js:9:20483)
      at Compiler.applyPluginsAsyncSeries (/home/travis/build/webpack/webpack/node_modules/tapable/lib/Tapable.js:95:46)
      at Compiler.emitAssets (/home/travis/build/webpack/webpack/lib/Compiler.js:9:20043)
      at onCompiled (/home/travis/build/webpack/webpack/lib/Compiler.js:9:16105)
      at /home/travis/build/webpack/webpack/lib/Compiler.js:9:33869
      at next (/home/travis/build/webpack/webpack/node_modules/tapable/lib/Tapable.js:102:11)
      at Compiler.<anonymous> (/home/travis/build/webpack/webpack/test/Compiler-caching.test.js:87:4)
      at next (/home/travis/build/webpack/webpack/node_modules/tapable/lib/Tapable.js:104:14)
      at Compiler.<anonymous> (/home/travis/build/webpack/webpack/lib/CachePlugin.js:9:4498)
      at Compiler.applyPluginsAsyncSeries (/home/travis/build/webpack/webpack/node_modules/tapable/lib/Tapable.js:106:13)
      at /home/travis/build/webpack/webpack/lib/Compiler.js:9:33523
      at Compilation.applyPluginsAsyncSeries (/home/travis/build/webpack/webpack/node_modules/tapable/lib/Tapable.js:95:46)
      at /home/travis/build/webpack/webpack/lib/Compilation.js:9:40026
      at Compilation.applyPluginsAsyncSeries (/home/travis/build/webpack/webpack/node_modules/tapable/lib/Tapable.js:95:46)
      at /home/travis/build/webpack/webpack/lib/Compilation.js:9:39269
      at Compilation.applyPluginsAsyncSeries (/home/travis/build/webpack/webpack/node_modules/tapable/lib/Tapable.js:95:46)
      at /home/travis/build/webpack/webpack/lib/Compilation.js:9:38815
      at Compilation.applyPluginsAsyncSeries (/home/travis/build/webpack/webpack/node_modules/tapable/lib/Tapable.js:95:46)
      at sealPart2 (/home/travis/build/webpack/webpack/lib/Compilation.js:9:38479)
      at Compilation.applyPluginsAsyncSeries (/home/travis/build/webpack/webpack/node_modules/tapable/lib/Tapable.js:95:46)
      at Compilation.seal (/home/travis/build/webpack/webpack/lib/Compilation.js:9:34560)
      at /home/travis/build/webpack/webpack/lib/Compiler.js:9:33220
      at /home/travis/build/webpack/webpack/node_modules/tapable/lib/Tapable.js:189:11
      at Compilation.<anonymous> (/home/travis/build/webpack/webpack/lib/Compilation.js:9:27742)
      at /home/travis/build/webpack/webpack/lib/Compilation.js:9:26407
      at _combinedTickCallback (internal/process/next_tick.js:67:7)
      at process._tickCallback (internal/process/next_tick.js:98:9)
```

**What is the expected behavior?**
it should pass always

**Comment by sokra** [comment]
see PR
