### ISSUE TITLE
Exit status 3221225501

### ISSUE THREAD

**Issue by vijayg3584** [webpack/webpack#3573]
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@4.0.3
3 info using node@v4.6.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle insightbase-operations@0.1.0~prebuild: insightbase-operations@0.1.0
6 silly lifecycle insightbase-operations@0.1.0~prebuild: no script for prebuild, continuing
7 info lifecycle insightbase-operations@0.1.0~build: insightbase-operations@0.1.0
8 verbose lifecycle insightbase-operations@0.1.0~build: unsafe-perm in lifecycle true
9 verbose lifecycle insightbase-operations@0.1.0~build: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\Vijay\Google Drive\Development\projects\git\insightbase_operations\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files (x86)\Bitvise SSH Client;C:\Program Files\MySQL\MySQL Server 5.7\bin;C:\Program Files\Java\jdk1.8.0_51\bin;C:\Program Files\MySQL\MySQL Server 5.5\bin;D:\DevTools\apache-maven-3.3.9\bin;C:\Program Files (x86)\WinMerge;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Program Files (x86)\Brackets\command;C:\Users\Vijay\AppData\Roaming\npm;C:\Program Files (x86)\Microsoft VS Code\bin
10 verbose lifecycle insightbase-operations@0.1.0~build: CWD: C:\Users\Vijay\Google Drive\Development\projects\git\insightbase_operations
11 silly lifecycle insightbase-operations@0.1.0~build: Args: [ '/d /s /c', 'webpack --progress' ]
12 silly lifecycle insightbase-operations@0.1.0~build: Returned: code: 3221225501  signal: null
13 info lifecycle insightbase-operations@0.1.0~build: Failed to exec build script
14 verbose stack Error: insightbase-operations@0.1.0 build: `webpack --progress`
14 verbose stack Exit status 3221225501
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:829:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid insightbase-operations@0.1.0
16 verbose cwd C:\Users\Vijay\Google Drive\Development\projects\git\insightbase_operations
17 error Windows_NT 6.1.7600
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
19 error node v4.6.0
20 error npm  v4.0.3
21 error code ELIFECYCLE
22 error insightbase-operations@0.1.0 build: `webpack --progress`
22 error Exit status 3221225501
23 error Failed at the insightbase-operations@0.1.0 build script 'webpack --progress'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the insightbase-operations package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     webpack --progress
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs insightbase-operations
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls insightbase-operations
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by bebraw** [comment]
Can you see the issue template? There's not enough information to debug with.

**Comment by vijayg3584** [comment]
@bebraw , sorry about that. 

I'm on the latest version of webpack 1.14.0.
When I run the webpack --progress directly it ends without any message that should say bundle is created and without any error. When I run this as a npm script, I get an error with exit status 3221225501 as seen in the issue I have logged. 
I don't get this error when I run it in Linux.

I believe rest of the information is in the log output I have pasted as seen in the issue. Let me know if you need any specific information.

Thanks for the quick response..

**Comment by bebraw** [comment]
Can you try with webpack 2? webpack 1 won't receive fixes anymore. Ideally you should provide a standalone test case against webpack 2 so we can verify and fix.

**Comment by sokra** [comment]
I don't think this is related to webpack itself.

**Comment by vijayg3584** [comment]
I tried the setup in my colleagues machine and it worked fine. I'm assuming there might be some conflicting npm modules installed globally. 
You can go ahead and close this issue for now.

**Comment by cslg-zz** [comment]
I and you encounter the same problem，but the compiled file can run normally.
