### ISSUE TITLE
In ng-cli / webpack often you don't get reference to file causing the error

### ISSUE THREAD

**Issue by born2net** [webpack/webpack#3593]
Webpack 2

I moved to Webpack (angular-cli) from SystemJS and I must say that the one things that is really troubling to me is that with Webpack is that errors often do not have reference to the original file name as they were all bundled up. Now sometimes you will get a reference to the module name, which is good enough, but it really depends on the type of exception.

With SystemJS I always got the name of the file causing the issue, and that by itself is super helpful as normally I can track down the bug as long as I know the culprit file name.

here is a very basic example:

```
EXCEPTION: No provider for StoreService!
  ErrorHandler.handleError	
  (anonymous function)	
  ZoneDelegate.invoke	
  onInvoke	
  ZoneDelegate.invoke	
  Zone.run	
  (anonymous function)	
  ZoneDelegate.invokeTask	
  onInvokeTask	
  ZoneDelegate.invokeTask	
  Zone.runTask	
  drainMicroTaskQueue	
ORIGINAL STACKTRACE:
  ErrorHandler.handleError	
  (anonymous function)	
  ZoneDelegate.invoke	
  onInvoke	
  ZoneDelegate.invoke	
  Zone.run	
  (anonymous function)	
  ZoneDelegate.invokeTask	
  onInvokeTask	
  ZoneDelegate.invokeTask	
  Zone.runTask	
  drainMicroTaskQueue	
Error: DI Error
    at NoProviderError.BaseError [as constructor] (http://localhost:4203/main.bundle.js:13343:27) [angular]
    at NoProviderError.AbstractProviderError [as constructor] (http://localhost:4203/main.bundle.js:99293:16) [angular]
    at new NoProviderError (http://localhost:4203/main.bundle.js:99342:16) [angular]
    at ReflectiveInjector_._throwOrNull (http://localhost:4203/main.bundle.js:133066:19) [angular]
    at ReflectiveInjector_._getByKeyDefault (http://localhost:4203/main.bundle.js:133103:25) [angular]
    at ReflectiveInjector_._getByKey (http://localhost:4203/main.bundle.js:133053:25) [angular]
    at ReflectiveInjector_.get (http://localhost:4203/main.bundle.js:132815:21) [angular]
    at AppModuleInjector.get (/AppModule/module.ngfactory.js:343:154) [angular]
    at AppModuleInjector.getInternal (/AppModule/module.ngfactory.js:489:51) [angular]
    at AppModuleInjector.NgModuleInjector.get (http://localhost:4203/main.bundle.js:100195:44) [angular]
    at CompiledTemplate.proxyViewClass.AppView.injectorGet (http://localhost:4203/main.bundle.js:133824:45) [angular]
    at CompiledTemplate.proxyViewClass.DebugAppView.injectorGet (http://localhost:4203/main.bundle.js:134252:49) [angular]
    at CompiledTemplate.proxyViewClass.View_AppComponent_Host0.createInternal (/AppModule/AppComponent/host.ngfactory.js:32:159) [angular]
    at CompiledTemplate.proxyViewClass.AppView.createHostView (http://localhost:4203/main.bundle.js:133780:21) [angular]
  ErrorHandler.handleError	
  (anonymous function)	
  ZoneDelegate.invoke	
  onInvoke	
  ZoneDelegate.invoke	
  Zone.run	
  (anonymous function)	
  ZoneDelegate.invokeTask	
  onInvokeTask	
  ZoneDelegate.invokeTask	
  Zone.runTask	
  drainMicroTaskQueue	
Unhandled Promise rejection: No provider for StoreService! ; Zone: <root> ; Task: Promise.then ; Value: NoProviderError Error: DI Error
    at NoProviderError.BaseError [as constructor] (http://localhost:4203/main.bundle.js:13343:27) [angular]
    at NoProviderError.AbstractProviderError [as constructor] (http://localhost:4203/main.bundle.js:99293:16) [angular]
    at new NoProviderError (http://localhost:4203/main.bundle.js:99342:16) [angular]
    at ReflectiveInjector_._throwOrNull (http://localhost:4203/main.bundle.js:133066:19) [angular]
    at ReflectiveInjector_._getByKeyDefault (http://localhost:4203/main.bundle.js:133103:25) [angular]
    at ReflectiveInjector_._getByKey (http://localhost:4203/main.bundle.js:133053:25) [angular]
    at ReflectiveInjector_.get (http://localhost:4203/main.bundle.js:132815:21) [angular]
    at AppModuleInjector.get (/AppModule/module.ngfactory.js:343:154) [angular]
    at AppModuleInjector.getInternal (/AppModule/module.ngfactory.js:489:51) [angular]
    at AppModuleInjector.NgModuleInjector.get (http://localhost:4203/main.bundle.js:100195:44) [angular]
    at CompiledTemplate.proxyViewClass.AppView.injectorGet (http://localhost:4203/main.bundle.js:133824:45) [angular]
    at CompiledTemplate.proxyViewClass.DebugAppView.injectorGet (http://localhost:4203/main.bundle.js:134252:49) [angular]
    at CompiledTemplate.proxyViewClass.View_AppComponent_Host0.createInternal (/AppModule/AppComponent/host.ngfactory.js:32:159) [angular]
    at CompiledTemplate.proxyViewClass.AppView.createHostView (http://localhost:4203/main.bundle.js:133780:21) [angular]
  consoleError	
  _loop_1	
  drainMicroTaskQueue	
Error: Uncaught (in promise): Error: No provider for StoreService!
Error: DI Error
    at NoProviderError.BaseError [as constructor] (http://localhost:4203/main.bundle.js:13343:27) [angular]
    at NoProviderError.AbstractProviderError [as constructor] (http://localhost:4203/main.bundle.js:99293:16) [angular]
    at new NoProviderError (http://localhost:4203/main.bundle.js:99342:16) [angular]
    at ReflectiveInjector_._throwOrNull (http://localhost:4203/main.bundle.js:133066:19) [angular]
    at ReflectiveInjector_._getByKeyDefault (http://localhost:4203/main.bundle.js:133103:25) [angular]
    at ReflectiveInjector_._getByKey (http://localhost:4203/main.bundle.js:133053:25) [angular]
    at ReflectiveInjector_.get (http://localhost:4203/main.bundle.js:132815:21) [angular]
    at AppModuleInjector.get (/AppModule/module.ngfactory.js:343:154) [angular]
    at AppModuleInjector.getInternal (/AppModule/module.ngfactory.js:489:51) [angular]
    at AppModuleInjector.NgModuleInjector.get (http://localhost:4203/main.bundle.js:100195:44) [angular]
    at CompiledTemplate.proxyViewClass.AppView.injectorGet (http://localhost:4203/main.bundle.js:133824:45) [angular]
    at CompiledTemplate.proxyViewClass.DebugAppView.injectorGet (http://localhost:4203/main.bundle.js:134252:49) [angular]
    at CompiledTemplate.proxyViewClass.View_AppComponent_Host0.createInternal (/AppModule/AppComponent/host.ngfactory.js:32:159) [angular]
    at CompiledTemplate.proxyViewClass.AppView.createHostView (http://localhost:4203/main.bundle.js:133780:21) [angular]
    at NoProviderError.BaseError [as constructor] (http://localhost:4203/main.bundle.js:13343:27) [angular]
    at NoProviderError.AbstractProviderError [as constructor] (http://localhost:4203/main.bundle.js:99293:16) [angular]
    at new NoProviderError (http://localhost:4203/main.bundle.js:99342:16) [angular]
    at ReflectiveInjector_._throwOrNull (http://localhost:4203/main.bundle.js:133066:19) [angular]
    at ReflectiveInjector_._getByKeyDefault (http://localhost:4203/main.bundle.js:133103:25) [angular]
    at ReflectiveInjector_._getByKey (http://localhost:4203/main.bundle.js:133053:25) [angular]
    at ReflectiveInjector_.get (http://localhost:4203/main.bundle.js:132815:21) [angular]
    at AppModuleInjector.get (/AppModule/module.ngfactory.js:343:154) [angular]
    at AppModuleInjector.getInternal (/AppModule/module.ngfactory.js:489:51) [angular]
    at AppModuleInjector.NgModuleInjector.get (http://localhost:4203/main.bundle.js:100195:44) [angular]
    at CompiledTemplate.proxyViewClass.AppView.injectorGet (http://localhost:4203/main.bundle.js:133824:45) [angular]
    at CompiledTemplate.proxyViewClass.DebugAppView.injectorGet (http://localhost:4203/main.bundle.js:134252:49) [angular]
    at CompiledTemplate.proxyViewClass.View_AppComponent_Host0.createInternal (/AppModule/AppComponent/host.ngfactory.js:32:159) [angular]
    at CompiledTemplate.proxyViewClass.AppView.createHostView (http://localhost:4203/main.bundle.js:133780:21) [angular]
    at resolvePromise (http://localhost:4203/main.bundle.js:187610:31) [<root>]
    at http://localhost:4203/main.bundle.js:187586:13 [<root>]
    at Zone.run (http://localhost:4203/main.bundle.js:187237:43) [<root> => <root>]
    at http://localhost:4203/main.bundle.js:187644:57 [<root>]
    at Zone.runTask (http://localhost:4203/main.bundle.js:187275:47) [<root> => <root>]
    at drainMicroTaskQueue (http://localhost:4203/main.bundle.js:187542:35) [<root>]
  consoleError	
  _loop_1	
  drainMicroTaskQueue	
```

ok so I know I am missing a provider, ```EXCEPTION: No provider for StoreService!```
but I am refactoring a huge application and this provider is referenced in hundreds of places.
breakpoints won't help as this is crashing before the app runs.
So sure, I see the bundle name, but that's no help.

Am I missing something as this is a major issue for me and I just can't imagine Webpack being as popular as it is with such a critical short coming! 
do we need some extra flags in ng cli? some source maps maybe enabled?

regards

Sean.

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

**Comment by born2net** [comment]
sorry will re-do properly
regards
