### ISSUE TITLE
Webpack / Angular cli: no reference to file name on errors (bundle name instead)

### ISSUE THREAD

**Issue by born2net** [webpack/webpack#3602]
**Subject:** 
Webpack / Angular cli: no reference to file name on errors (bundle name instead)

Please adds ability to get a reference to a file name when more obscure errors occur.

**What is the current behavior?**
Often when I refactor applications I get into scenarios which I get errors from ng and the only file reference is a webpack bundle. Now, I am aware this is more of a Webpack issue but of course since we are using ng-cli, we expect as developers that ng-cli will assist in file error reporting.

**If the current behavior is a bug, please provide the steps to reproduce.**
There are many many cases that an error references a bundle name, and no evidence of a module or class name is referenced in an error stack; now I realize that in some cases due to zonejs and the compilation (ts/ng) it may be hard to report the line number or even the original JS class or module, but at least a file name would be helpful to start tracking down an issue.

**What is the expected behavior?**
I am no expert in Webpack, but some ideas come to mind.
The one thing I really miss from JSPM / SystemJS is that errors always referenced the file name. 
So maybe add a dev mode for ng-cli to support non bundled mode that's not optimized in any way, but will include all source files.

I am using Windows 10 64 latets Webpack 2 and latest ng-cli

Here are some examples of webpack errors with no ref to file:

```
EXCEPTION: No provider for StoreService!
  ErrorHandler.handleError	
  (anonymous function)	
  ZoneDelegate.invoke	
  onInvoke	
  ZoneDelegate.invoke	
  Zone.run	
  (anonymous function)	
  ZoneDelegate.invokeTask	
  onInvokeTask	
  ZoneDelegate.invokeTask	
  Zone.runTask	
  drainMicroTaskQueue	
ORIGINAL STACKTRACE:
  ErrorHandler.handleError	
  (anonymous function)	
  ZoneDelegate.invoke	
  onInvoke	
  ZoneDelegate.invoke	
  Zone.run	
  (anonymous function)	
  ZoneDelegate.invokeTask	
  onInvokeTask	
  ZoneDelegate.invokeTask	
  Zone.runTask	
  drainMicroTaskQueue	
Error: DI Error
    at NoProviderError.BaseError [as constructor] (http://localhost:4203/main.bundle.js:13343:27) [angular]
    at NoProviderError.AbstractProviderError [as constructor] (http://localhost:4203/main.bundle.js:99293:16) [angular]
    at new NoProviderError (http://localhost:4203/main.bundle.js:99342:16) [angular]
    at ReflectiveInjector_._throwOrNull (http://localhost:4203/main.bundle.js:133066:19) [angular]
    at ReflectiveInjector_._getByKeyDefault (http://localhost:4203/main.bundle.js:133103:25) [angular]
    at ReflectiveInjector_._getByKey (http://localhost:4203/main.bundle.js:133053:25) [angular]
    at ReflectiveInjector_.get (http://localhost:4203/main.bundle.js:132815:21) [angular]
    at AppModuleInjector.get (/AppModule/module.ngfactory.js:343:154) [angular]
    at AppModuleInjector.getInternal (/AppModule/module.ngfactory.js:489:51) [angular]
    at AppModuleInjector.NgModuleInjector.get (http://localhost:4203/main.bundle.js:100195:44) [angular]
    at CompiledTemplate.proxyViewClass.AppView.injectorGet (http://localhost:4203/main.bundle.js:133824:45) [angular]
    at CompiledTemplate.proxyViewClass.DebugAppView.injectorGet (http://localhost:4203/main.bundle.js:134252:49) [angular]
    at CompiledTemplate.proxyViewClass.View_AppComponent_Host0.createInternal (/AppModule/AppComponent/host.ngfactory.js:32:159) [angular]
    at CompiledTemplate.proxyViewClass.AppView.createHostView (http://localhost:4203/main.bundle.js:133780:21) [angular]
  ErrorHandler.handleError	
  (anonymous function)	
```

ok so I know I am missing a provider, ```EXCEPTION: No provider for StoreService!```
but I am refactoring a huge application and this provider is referenced in hundreds of places.
breakpoints won't help as this is crashing before the app runs.
So sure, I see the bundle name, but that's no help.

and another

here is another example:
```
Uncaught SyntaxError
  CompileMetadataResolver._reportError	
  CompileMetadataResolver._getDependenciesMetadata	
  CompileMetadataResolver._getTypeMetadata	
  CompileMetadataResolver._getInjectableMetadata	
  CompileMetadataResolver.getProviderMetadata	
  (anonymous function)	
  CompileMetadataResolver._getProvidersMetadata	
  (anonymous function)	
  CompileMetadataResolver._getProvidersMetadata	
  CompileMetadataResolver.getNgModuleMetadata	
  JitCompiler._loadModules	
  JitCompiler._compileModuleAndComponents	
  JitCompiler.compileModuleAsync	
  PlatformRef_._bootstrapModuleWithZone	
  PlatformRef_.bootstrapModule	
  bootstrap	
  (anonymous function)	
  __webpack_require__	
  (anonymous function)	
  __webpack_require__	
  webpackJsonpCallback	
  (anonymous function)	
```

also posted with no real solution at:
http://stackoverflow.com/questions/41234718/webpack-angular-cli-is-there-anyway-to-get-the-filename-that-caused-the-excep

if you need more examples of non file name ref errors let me know

regards

Sean.

**Comment by born2net** [comment]
more examples :(

```
TypeError: Cannot read property 'authenticated' of undefined
    at appDb (http://localhost:4203/main.bundle.js:140475:46)
    at combination (http://localhost:4203/main.bundle.js:106578:35)
    at computeNextEntry (http://localhost:4203/main.bundle.js:137496:21)
    at recomputeStates (http://localhost:4203/main.bundle.js:137527:13)
    at http://localhost:4203/main.bundle.js:137709:26
    at ScanSubscriber.accumulator (http://localhost:4203/main.bundle.js:106239:37)
```

**Comment by sokra** [comment]
https://webpack.js.org/configuration/devtool/#devtool
