### ISSUE TITLE
Exception while loading ejs view engine at runtime

### ISSUE THREAD

**Issue by maxmumford** [webpack/webpack#4009]
bug

**What is the current behavior?**

Exception thrown when trying to load ejs view engine:

```
Error: Cannot find module "."
   at webpackMissingModule (/Users/max/Development/test/express-webpack/dist/server.js:20669:74)
   at new View (/Users/max/Development/test/express-webpack/dist/server.js:20669:152)
   at EventEmitter.render (/Users/max/Development/test/express-webpack/dist/server.js:18776:12)
   at ServerResponse.render (/Users/max/Development/test/express-webpack/dist/server.js:20479:7)
   at /Users/max/Development/test/express-webpack/dist/server.js:25508:7
   at Layer.handle [as handle_request] (/Users/max/Development/test/express-webpack/dist/server.js:4524:5)
   at next (/Users/max/Development/test/express-webpack/dist/server.js:4743:13)
   at Route.dispatch (/Users/max/Development/test/express-webpack/dist/server.js:4724:3)
   at Layer.handle [as handle_request] (/Users/max/Development/test/express-webpack/dist/server.js:4524:5)
   at /Users/max/Development/test/express-webpack/dist/server.js:4054:22

```

**If the current behavior is a bug, please provide the steps to reproduce.**

Bug is reproducible with the following repository - repro steps available in the readme:

https://github.com/maxmumford/express-webpack-ejs-bug

**What is the expected behavior?**

Load the ejs template

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

webpack v2.2.0-rc.3

A workaround was found by Cleiton at SO - please see question here:

http://stackoverflow.com/questions/41707662/webpack-express-ejs-error-cannot-find-module/41709158#41709158

Workaround works fine for me but I thought you'd appreciate an issue report :)

**Comment by dominic-p** [comment]
+1, this one bit me recently as well. As I'm really new to webpack it took me a while to track it down. The workaround on SO works for me as well. Thanks.

**Comment by ShocKwav3** [comment]
+1, aaaannndd it is still not looked up yet and i just pulled a lot of my hair.

**Comment by dominic-p** [comment]
Can anyone confirm if this is resolved?

**Comment by aartek** [comment]
I'm also stuck with this problem. Unfortunately workaround doesn't work for me. I'm using webpack v3.8.1

```js
import * as express from 'express';
import * as path from 'path';

const app = express();
app.set("port", process.env.PORT || 3000);
app.set("views", path.join(__dirname, 'server', 'views'));
app.set('view engine', 'ejs');

app.get('/', (req: express.Request, res: express.Response) => {
 res.render('index')
})

app.listen(app.get("port"), () => {
    console.log(("  App is running at http://localhost:%d"), app.get("port"));
    console.log("  Press CTRL-C to stop\n");
});

module.exports = app;
```

Error:
```
  Error: Cannot find module "."
  at webpackMissingModule (/Users/me/HomeProjects/express-webpack-ts/build/server.js:14507:58)
  at new View (/Users/me/HomeProjects/express-webpack-ts/build/server.js:14507:136)
  at EventEmitter.render (/Users/me/HomeProjects/express-webpack-ts/build/server.js:13839:12)
  at ServerResponse.render (/Users/me/HomeProjects/express-webpack-ts/build/server.js:18391:7)
  at /Users/me/HomeProjects/express-webpack-ts/build/server.js:7671:9
  at Layer.handle [as handle_request] (/Users/me/HomeProjects/express-webpack-ts/build/server.js:6206:5)
  at next (/Users/me/HomeProjects/express-webpack-ts/build/server.js:6025:13)
  at Route.dispatch (/Users/me/HomeProjects/express-webpack-ts/build/server.js:6000:3)
  at Layer.handle [as handle_request] (/Users/me/HomeProjects/express-webpack-ts/build/server.js:6206:5)
  at /Users/me/HomeProjects/express-webpack-ts/build/server.js:5500:22
```

**Comment by dominic-p** [comment]
Can anyone confirm if this has been resolved? Maybe in v4?

**Comment by dominic-p** [comment]
My ad hoc testing after upgrading to Webpack v4 has been positive. This issue may have been resolved.

**Comment by evilebottnawi** [comment]
Closing because resolved https://github.com/webpack/webpack/issues/4009#issuecomment-391897123. Feel free create new issue if you still have problems. Thanks
