### ISSUE TITLE
Webpack's tests are broken in v 2.2

### ISSUE THREAD

**Issue by jharris4** [webpack/webpack#4066]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

tests are broken when cloning webpack from latest

```
> webpack@2.2.0 test /Users/jonharris/temp/webpack
> mocha test/*.test.js --harmony --check-leaks

module.js:472
    throw err;
    ^

Error: Cannot find module 'webpack/lib/removeAndDo'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/jonharris/temp/webpack/node_modules/extract-text-webpack-plugin/ExtractedModule.js:30:42)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/jonharris/temp/webpack/node_modules/extract-text-webpack-plugin/index.js:8:23)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/jonharris/temp/webpack/test/HotTestCases.test.js:6:25)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at require (internal/module.js:20:19)
    at /Users/jonharris/temp/webpack/node_modules/mocha/lib/mocha.js:222:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/jonharris/temp/webpack/node_modules/mocha/lib/mocha.js:219:14)
    at Mocha.run (/Users/jonharris/temp/webpack/node_modules/mocha/lib/mocha.js:487:10)
    at Object.<anonymous> (/Users/jonharris/temp/webpack/node_modules/mocha/bin/_mocha:459:18)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3
```

**If the current behavior is a bug, please provide the steps to reproduce.**

1) clone webpack from github
2) npm install
3) npm run test

**What is the expected behavior?**

Tests should pass, so I can sanity check the PR I was about to make :-)

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Node v7.4.0
Webpack 2.2.0
MacOS 10.12.2

**Comment by TheLarkInn** [comment]
It looks like you overlooked an important step in our CONTRIBUTING.md file. 😅

**Comment by jharris4** [comment]
I had a feeling I was probably doing something stupid. Apologies for raising the issue, I'll take a look now. Thanks

**Comment by jharris4** [comment]
Ah yarn... Interesting, I've been dabbling with migrating from npm. I installed via `brew install yarn` as installing globally via npm gave me a warning.

**Comment by TheLarkInn** [comment]
No need to apologize at all. Infact yarn isn't the really important piece although your installs will be 30% of the normal time. Really it's the 'x link && x link webpack'

**Comment by jharris4** [comment]
Oof, the struggle is real trying to add tests for my PR... I made some changes to the RequireEnsurePlugin to fix https://github.com/webpack/webpack/issues/758.

I'm trying to add test cases under `test/cases/parsing/issue-758` to mirror what was done in `test/cases/parsing/issue-2641`.

Firstly, I can't figure out how to only run that test so I have to go run laps around the block waiting for the test run to complete. Then, the tests fail with a spew of errors that overflows the limits of my console.

I realize this issue's comments are not the right place to get some help, but... help!

Is there a good forum I can use to ask questions about this?

**Comment by ranglang** [comment]
same problem

**Comment by TheLarkInn** [comment]
@jharris4 Mocha lets you use the `--grep` feature. 

So to only run tests from `ConfigTestCases.test.js`, I check to see the name of the test suite:

```js
describe("ConfigTestCases", function(){};
```

And I run in the command line: `$(npm bin)/mocha --grep ConfigTestCases`

**Comment by TheLarkInn** [comment]
Also, I documented this entire process. 

https://github.com/webpack/webpack/blob/master/test/README.md#tldr

Is there any way I can make this README more noticeable. Would you say its hidden and unreachable?

**Comment by TheLarkInn** [comment]
@ranglang this error:
```
Error: Cannot find module 'webpack/lib/removeAndDo'
```
always means you forgot to link the package and then self link the package with the repo: 


```bash
npm install
npm link && npm link webpack
```

**Comment by jharris4** [comment]
@TheLarkInn I appreciate the time you've put into the docs. In this case, I had read the test/README.md file though! :-)

I wanted to only run the test related to a specific issue under `test/cases/parsing` which from the README, I assumed meant I should try `./node_modules/.bin/mocha --grep TestCases` as the README tells me that this is where tests related to `test/cases` go.

Interestingly, I think the grep is doing some pattern matching so `TestCases` is also matching `BinTestCases`, `ConfigTestCases` and `WatchTestCases`.

So maybe `TestCases` could be renamed to something a little easier to distinguish/target?

**Comment by jharris4** [comment]
Also, I'm having a bit of trouble figuring out what the process is for adding a test under `test/cases/`. I tried just copy the contents from `test/cases/parsing/issue-2641` into `test/cases/parsing/issue-758` but then running the whole test suite fails with some hard to decipher torrent of error messages.

Webpack seems to be searching for node_modules or web_modules directories that it cannot find...

If it's helpful you can see my fork here: https://github.com/jharris4/webpack

**Comment by jharris4** [comment]
Oh, regex FTW `.node_modules/.bin/mocha --grep '^TestCases'`

**Comment by TheLarkInn** [comment]
Yes!!! Let me know if you have any other issues.
