### ISSUE TITLE
Vague error message when importing misspelled module

### ISSUE THREAD

**Issue by gringocl** [webpack/webpack#4090]
**Do you want to request a *feature* or report a *bug*?**
Possible Bug

**What is the current behavior?**
When a mis-spelled module is imported, this stacktrace is reported:
```
23 01 2017 07:27:18.606:ERROR [karma]: TypeError: Cannot read property 'addChunk' of null
  at self.preparedChunks.forEach.preparedChunk (/Path/to/code/node_modules/webpack/lib/Compilation.js:526:10)
  at Array.forEach (native)
  at Compilation.seal (/Path/to/code/node_modules/webpack/lib/Compilation.js:519:23)
  at /Path/to/code/node_modules/webpack/lib/Compiler.js:474:16
  at /Path/to/code/node_modules/tapable/lib/Tapable.js:225:11
  at done (/Path/to/code/node_modules/karma-webpack/node_modules/async/lib/async.js:132:19)
  at /Path/to/code/node_modules/karma-webpack/node_modules/async/lib/async.js:32:16
  at Plugin.<anonymous> (/Path/to/code/node_modules/karma-webpack/lib/karma-webpack.js:175:7)
  at _addModuleChain (/Path/to/code/node_modules/webpack/lib/Compilation.js:443:12)
  at processModuleDependencies.err (/Path/to/code/node_modules/webpack/lib/Compilation.js:420:14)
  at finalCallbackAddModuleDependencies (/Path/to/code/node_modules/webpack/lib/Compilation.js:330:12)
  at /Path/to/code/node_modules/async/dist/async.js:356:16
  at iteratorCallback (/Path/to/code/node_modules/async/dist/async.js:934:13)
  at /Path/to/code/node_modules/async/dist/async.js:840:16
  at finalCallbackAddModuleDependencies (/Path/to/code/node_modules/webpack/lib/Compilation.js:330:12)
  at /Path/to/code/node_modules/async/dist/async.js:356:16
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Import a module that is misspelled.  This will crash webpack / karma. 

**What is the expected behavior?**

Some type of module missing error message.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

webpack `v2.2.0`
webpack-dev-server `v2.2.0`
karma `v1.4.0`
karma-webpack `v2.0.1`

**Comment by gringocl** [comment]
This was happening in `karma-webpack` closing this!
