### ISSUE TITLE
[WebPack2]when use import() in code, get a error: Module build failed: ReferenceError: ....../src/main.js: unknown node of type "Import" with constructor "Node"

### ISSUE THREAD

**Issue by XuJinNet** [webpack/webpack#4091]
This is a demo repository: https://github.com/XuJinNet/webpack-test

Code
main.js
```javascript
import('./b')
	.then(b => {
		b.default.test();
	});

class A {
	constructor() {

	}

	func1() {
		console.log('money 💰😊');
	}
}

const a = new A();
a.func1();
```

b.js
```javascript
export default {
	test() {
		console.log('OK 👌 ☀️ 😊 ❤️');
	}
};
```

.babelrc
```json
......
"plugins": [
		"syntax-flow",
		"transform-decorators-legacy",
		"transform-flow-strip-types",
		"transform-class-properties",
		"transform-function-bind",
    	"syntax-dynamic-import"
      ]
......
```
The error:
```
./src/main.js
Module build failed: ReferenceError: /Users/xujin/My_Projects/NodeJS/test/webpack-test/src/main.js: unknown node of type "Import" with constructor "Node"
    at Generator.print (/Users/xujin/My_Projects/NodeJS/test/webpack-test/node_modules/babel-generator/lib/printer.js:279:13)
    at Generator.CallExpression (/Users/xujin/My_Projects/NodeJS/test/webpack-test/node_modules/babel-generator/lib/generators/expressions.js:122:8)
    at /Users/xujin/My_Projects/NodeJS/test/webpack-test/node_modules/babel-generator/lib/printer.js:298:23
    at Buffer.withSource (/Users/xujin/My_Projects/NodeJS/test/webpack-test/node_modules/babel-generator/lib/buffer.js:151:5)
    at Generator.withSource (/Users/xujin/My_Projects/NodeJS/test/webpack-test/node_modules/babel-generator/lib/printer.js:189:15)
    at Generator.print (/Users/xujin/My_Projects/NodeJS/test/webpack-test/node_modules/babel-generator/lib/printer.js:297:10)
    at Generator.MemberExpression (/Users/xujin/My_Projects/NodeJS/test/webpack-test/node_modules/babel-generator/lib/generators/expressions.js:215:8)
    at /Users/xujin/My_Projects/NodeJS/test/webpack-test/node_modules/babel-generator/lib/printer.js:298:23
    at Buffer.withSource (/Users/xujin/My_Projects/NodeJS/test/webpack-test/node_modules/babel-generator/lib/buffer.js:151:5)
    at Generator.withSource (/Users/xujin/My_Projects/NodeJS/test/webpack-test/node_modules/babel-generator/lib/printer.js:189:15)
    at Generator.print (/Users/xujin/My_Projects/NodeJS/test/webpack-test/node_modules/babel-generator/lib/printer.js:297:10)
    at Generator.CallExpression (/Users/xujin/My_Projects/NodeJS/test/webpack-test/node_modules/babel-generator/lib/generators/expressions.js:122:8)
    at /Users/xujin/My_Projects/NodeJS/test/webpack-test/node_modules/babel-generator/lib/printer.js:298:23
    at Buffer.withSource (/Users/xujin/My_Projects/NodeJS/test/webpack-test/node_modules/babel-generator/lib/buffer.js:151:5)
    at Generator.withSource (/Users/xujin/My_Projects/NodeJS/test/webpack-test/node_modules/babel-generator/lib/printer.js:189:15)
    at Generator.print (/Users/xujin/My_Projects/NodeJS/test/webpack-test/node_modules/babel-generator/lib/printer.js:297:10)
 @ multi (webpack)-dev-server/client?http://0.0.0.0:9000 ./src/main.js
```

webpack: 2.2.0
webpack-dev-server: 2.2.0
Browser: All
Node: 6.9.4
OS: macOS 10.12.2

**Comment by TheLarkInn** [comment]
@hzoo This looks like a babel error. Are we thinking its just deps related?

**Comment by hzoo** [comment]
Yes probably out of date babel-generator since you yourself made the PR 😄. Just make sure all deps are up to date.

**Comment by TheLarkInn** [comment]
Heh just wanted to make sure. It looked _awefully_ familiar.

**Comment by TongDaDa** [comment]
What is your problem solved, I encountered a similar problem with you

**Comment by XuJinNet** [comment]
@TogDaDa update the dep "babel-generator".

**Comment by TongDaDa** [comment]
@XuJinNet Import () the grammar cannot use balbe compilation, I don't want to use the Babel compiler module, should be how to configure? l

**Comment by wzup** [comment]
@XuJinNet @hzoo 

What `babel-generator` are you talking about? There is NO and has NEVER been any `babel-generator` in my `package.json`. I have never either used or even heard about it. Everything worked just fine all the time. Suddenly boom! _update `babel-generator`_. No info about this thing in docs, tutorials, nothing. Just update it. Why do I have to bother about package internals, I'm not a maintainer. I just want to use the package.

Could you please elaborate what you mean by saying _update the dep "babel-generator"._. Provide links in [documentation ](https://webpack.js.org/guides/) about use cases for exactly `babel-generator`.

Thanks

**Comment by XuJinNet** [comment]
Add tow deps(babel-core, babel-generator) to package.json.
My demo repository: https://github.com/XuJinNet/webpack-test
