### ISSUE TITLE
Webpack 2.2.0 throws error complaining about url module

### ISSUE THREAD

**Issue by grahamb** [webpack/webpack#4108]
**Do you want to request a *feature* or report a *bug*?**
Probably a bug

**What is the current behavior?**
When upgrading from 2.1.0-beta.21 to 2.2.0, I'm getting an error referencing the [url](https://www.npmjs.com/package/url) module.

```
> NODE_ENV=production webpack --env.prod

/Users/grahamb/code/sfu/snap/node_modules/loader-runner/lib/loadLoader.js:35
			throw new Error("Module '" + loader.path + "' is not a loader (must have normal or pitch function)");
			^

Error: Module '/Users/grahamb/code/sfu/snap/node_modules/url/url.js' is not a loader (must have normal or pitch function)
    at loadLoader (/Users/grahamb/code/sfu/snap/node_modules/loader-runner/lib/loadLoader.js:35:10)
    at iteratePitchingLoaders (/Users/grahamb/code/sfu/snap/node_modules/loader-runner/lib/LoaderRunner.js:164:2)
    at runLoaders (/Users/grahamb/code/sfu/snap/node_modules/loader-runner/lib/LoaderRunner.js:357:2)
    at NormalModule.doBuild (/Users/grahamb/code/sfu/snap/node_modules/webpack/lib/NormalModule.js:129:2)
    at NormalModule.build (/Users/grahamb/code/sfu/snap/node_modules/webpack/lib/NormalModule.js:180:15)
    at Compilation.buildModule (/Users/grahamb/code/sfu/snap/node_modules/webpack/lib/Compilation.js:127:10)
    at factoryCallback (/Users/grahamb/code/sfu/snap/node_modules/webpack/lib/Compilation.js:304:11)
    at /Users/grahamb/code/sfu/snap/node_modules/webpack/lib/NormalModuleFactory.js:242:4
    at /Users/grahamb/code/sfu/snap/node_modules/webpack/lib/NormalModuleFactory.js:93:13
    at /Users/grahamb/code/sfu/snap/node_modules/tapable/lib/Tapable.js:204:11
    at NormalModuleFactory.<anonymous> (/Users/grahamb/code/sfu/snap/node_modules/webpack/lib/CompatibilityPlugin.js:51:4)
    at NormalModuleFactory.applyPluginsAsyncWaterfall (/Users/grahamb/code/sfu/snap/node_modules/tapable/lib/Tapable.js:208:13)
    at onDoneResolving (/Users/grahamb/code/sfu/snap/node_modules/webpack/lib/NormalModuleFactory.js:68:11)
    at onDoneResolving (/Users/grahamb/code/sfu/snap/node_modules/webpack/lib/NormalModuleFactory.js:189:6)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

I am using the `url` module in code bundled by webpack. I've tried replacing it with the [url-parse](https://www.npmjs.com/package/url-parse) module to no effect.

I have updated the loaders in my webpack config to use the full name (e.g. `url-loader`).

The only way I've found around this is to add

```
    resolveLoader: {
      moduleExtensions: ['-loader']
    },
```

to my webpack config, per https://webpack.js.org/guides/migrating/#automatic-loader-module-name-extension-removed.

**If the current behavior is a bug, please provide the steps to reproduce.**

Current webpack config, package.json and the error are at https://gist.github.com/grahamb/0fb48f42a871d6b2fff4ddd62aceb8a5.

**What is the expected behavior?**
My bundle should build and not throw an error.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Browser: any
Node.js: v6.9.2
Webpack: 2.2.0
OS: Mac OS X 10.11.6

**Comment by sokra** [comment]
replace `url` with `url-loader` as noted in the migration guide.

**Comment by grahamb** [comment]
Hi @sokra,

As I noted above: 

> I have updated the loaders in my webpack config to use the full name (e.g. url-loader).

You can see this by looking at the webpack config in the linked gist. https://gist.github.com/grahamb/0fb48f42a871d6b2fff4ddd62aceb8a5

@TheLarkInn [suggested opening an issue](https://twitter.com/TheLarkInn/status/824376735550554112), so here we are. Please re-open this.

**Comment by miracle2k** [comment]
Could you solve this? I have the same problem. All my loaders use the "-loader" prefix. In fact, I get this error if I disable all loaders except the babel-loader in it's default config that they recommend.

**Comment by miracle2k** [comment]
This took me a while. Turns out I was using the `url!` syntax dynamically in a `require()` instruction in my code.

**Comment by pkuczynski** [comment]
@grahamb have you fixed your issue?

**Comment by vittvolt** [comment]
@miracle2k That was so helpful! It solved my issue!
