### ISSUE TITLE
eval-cheap-module-source-map + UglifyJsPlugin = TypeError

### ISSUE THREAD

**Issue by rexave** [webpack/webpack#4154]
Hi,

This issue may be related to #1385 .

When i set `devtool: "eval-cheap-module-source-map"`, `UglifyJsPlugin` doesn't apply.
So i try to force it with `webpack --verbose -p`

and got this error 
```
ERROR in bundle.js from UglifyJs
TypeError: Cannot read property 'sections' of null
    at new SourceMapConsumer (D:\workspaces\myProject\node_modules\source-map\lib\source-map-consumer.js:20:19)
    at files.forEach (D:\workspaces\myProject\node_modules\webpack\lib\optimize\UglifyJsPlugin.js:59:20)
    at Array.forEach (native)
    at Compilation.compilation.plugin (D:\workspaces\myProject\node_modules\webpack\lib\optimize\UglifyJsPlugin.js:38:11)
    at next (D:\workspaces\myProject\node_modules\tapable\lib\Tapable.js:140:14)
    at Compilation.compilation.plugin (D:\workspaces\myProject\node_modules\webpack\lib\optimize\UglifyJsPlugin.js:140:5)
    at Compilation.applyPluginsAsyncSeries (D:\workspaces\myProject\node_modules\tapable\lib\Tapable.js:142:13)
    at self.applyPluginsAsync.err (D:\workspaces\myProject\node_modules\webpack\lib\Compilation.js:601:10)
    at Compilation.applyPluginsAsyncSeries (D:\workspaces\myProject\node_modules\tapable\lib\Tapable.js:131:46)
    at sealPart2 (D:\workspaces\myProject\node_modules\webpack\lib\Compilation.js:597:9)
    at Compilation.applyPluginsAsyncSeries (D:\workspaces\myProject\node_modules\tapable\lib\Tapable.js:131:46)
    at Compilation.seal (D:\workspaces\myProject\node_modules\webpack\lib\Compilation.js:545:8)
    at D:\workspaces\myProject\node_modules\webpack\lib\Compiler.js:474:16
    at D:\workspaces\myProject\node_modules\tapable\lib\Tapable.js:225:11
    at _addModuleChain (D:\workspaces\myProject\node_modules\webpack\lib\Compilation.js:452:11)
    at processModuleDependencies.err (D:\workspaces\myProject\node_modules\webpack\lib\Compilation.js:423:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

If i remove `devtool` parameter from the config file, no error is triggered and the js is well minified.
```
    Asset    Size  Chunks             Chunk Names
bundle.js  202 kB       0  [emitted]  main
Entrypoint main = bundle.js
```

By the way, if i force with `-p` and without `devtool` parameter, the js is more minified
```
   Asset    Size  Chunks             Chunk Names
bundle.js  176 kB       0  [emitted]  main
Entrypoint main = bundle.js
```

Here is my webpack.config.js 
``` js
const path = require('path');
const webpack = require('webpack');
const UglifyJSPlugin = require('uglifyjs-webpack-plugin');

module.exports = {
  devtool: "eval-cheap-module-source-map",

  entry: "./modules/index.js",
  output: {
    path: '/build',
    publicPath: '/public/assets/js/',
    filename: "bundle.js"
  },

  devServer: {
    contentBase: 'html'
  },

  module: {
    rules: [
      {
        test: /\.html$/,
        exclude: /node_modules/,
        loader: "raw-loader"
      }
    ]
  },

  resolve: {
    modules: ["js", "node_modules/js-commons", "node_modules"],
    extensions: ['.js']
  },
  plugins: [
    new webpack.optimize.UglifyJsPlugin({
            beautify: false,
            comments: false,
            compress: {
                warnings: false,
                drop_console: true,
                screw_ie8: true
            },
            mangle: {
                except: [
                    '$', 'webpackJsonp'
                ],
                screw_ie8: true,
                keep_fnames: true
            },
            output: {
                comments: false,
                screw_ie8: true
            }
        }),
  ]
};
```

Version: webpack 2.2.0

Can you please help my with this issue ? Do i miss something or do something wrong ?

**Comment by bebraw** [comment]
I would recommend against using `eval` options for production usage. It will write the sourcemap within your bundle and that's far from optimal. The regular `source-map` option is often enough. This would work around the issue.

**Comment by li-kai** [comment]
Enable `sourcemap: true` option in your UglifyJsPlugin config. https://webpack.js.org/guides/migrating/#uglifyjsplugin-sourcemap

**Comment by rexave** [comment]
Thanks for your answers !
changing `devtool: "source-map"` fixed the problem, but is slower to generate.
the presence of `sourcemap: true` is not required to avoid the error.

**Comment by rexave** [comment]
Here is a working example : 

``` javascript
const path = require('path');
const webpack = require('webpack');

module.exports = {
  devtool: "source-map",

  entry: "./modules/index.js",
  output: {
    path: '/build',
    publicPath: '/public/assets/js/',
    filename: "bundle.js"
  },

  devServer: {
    contentBase: 'html'
  },

  module: {
    rules: [
      {
        test: /\.html$/,
        exclude: /node_modules/,
        loader: "raw-loader"
      }
    ]
  },

  resolve: {
    modules: ["js", "node_modules/js-commons", "node_modules"],
    extensions: ['.js']
  },
  plugins: [
    new webpack.optimize.UglifyJsPlugin({
      sourcemap: true,
      beautify: false,
      comments: false,
      compress: {
        warnings: false,
        drop_console: true,
        screw_ie8: true
      },
      mangle: {
        except: [
          '$', 'webpackJsonp'
        ],
        screw_ie8: true,
        keep_fnames: true
      },
      output: {
        comments: false,
        screw_ie8: true
      }
    }),
  ]
};
```

**Comment by pak11273** [comment]
this property is case-sensitive. use sourceMap instead of sourcemap:

```
new webpack.optimize.UglifyJsPlugin({
      sourceMap: true
})
```

**Comment by doomsbuster** [comment]
Yep, setting `dev-tool:"source-map"` and `sourceMap: true` in the `UglifyJsPlugin()` fixed the error.

**Comment by willdavidow** [comment]
Just making sure `sourceMap: true` was set in my `UglifyJS` config object worked for me, and allowed me to use `cheap-module-source-map` without issue.
