### ISSUE TITLE
[bug?] Missing TypeScript declaration file crashes Webpack with unhelpful error.

### ISSUE THREAD

**Issue by trusktr** [webpack/webpack#4155]
**Do you want to request a *feature* or report a *bug*?**

This may possibly be a bug.

**What is the current behavior?**

I have an `index.d.ts` that re-exports a bunch of stuff. When I add import and export from a file that doesn't exist, Webpack crashes with a completely irrelevant error:

```
 92% chunk asset optimization/home/cit/imvu/website-project/website/unicorns_sections/sticker_creator/node_modules/webpack/node_modules/source-map/lib/array-set.js:92
  throw new Error('No element indexed by ' + aIdx);
  ^

Error: No element indexed by 1
    at ArraySet_at [as at] (/home/cit/imvu/website-project/website/unicorns_sections/sticker_creator/node_modules/webpack/node_modules/source-map/lib/array-set.js:92:9)
    at SourceMapConsumer.<anonymous> (/home/cit/imvu/website-project/website/unicorns_sections/sticker_creator/node_modules/webpack/node_modules/source-map/lib/source-map-consumer.js:143:67)
    at Array.map (native)
    at SourceMapConsumer_eachMapping [as eachMapping] (/home/cit/imvu/website-project/website/unicorns_sections/sticker_creator/node_modules/webpack/node_modules/source-map/lib/source-map-consumer.js:142:14)
    at Function.SourceNode_fromStringWithSourceMap [as fromStringWithSourceMap] (/home/cit/imvu/website-project/website/unicorns_sections/sticker_creator/node_modules/webpack/node_modules/source-map/lib/source-node.js:80:24)
    at SourceMapSource.node (/home/cit/imvu/website-project/website/unicorns_sections/sticker_creator/node_modules/webpack/node_modules/webpack-sources/lib/SourceMapSource.js:42:20)
    at ReplaceSource.node (/home/cit/imvu/website-project/website/unicorns_sections/sticker_creator/node_modules/webpack/node_modules/webpack-sources/lib/ReplaceSource.js:69:29)
    at CachedSource.node (/home/cit/imvu/website-project/website/unicorns_sections/sticker_creator/node_modules/webpack/node_modules/webpack-sources/lib/CachedSource.js:12:23)
    at /home/cit/imvu/website-project/website/unicorns_sections/sticker_creator/node_modules/webpack/node_modules/webpack-sources/lib/ConcatSource.js:40:49
    at Array.map (native)
    at ConcatSource.node (/home/cit/imvu/website-project/website/unicorns_sections/sticker_creator/node_modules/webpack/node_modules/webpack-sources/lib/ConcatSource.js:39:60)
    at /home/cit/imvu/website-project/website/unicorns_sections/sticker_creator/node_modules/webpack/node_modules/webpack-sources/lib/ConcatSource.js:40:49
    at Array.map (native)
    at ConcatSource.node (/home/cit/imvu/website-project/website/unicorns_sections/sticker_creator/node_modules/webpack/node_modules/webpack-sources/lib/ConcatSource.js:39:60)
    at /home/cit/imvu/website-project/website/unicorns_sections/sticker_creator/node_modules/webpack/node_modules/webpack-sources/lib/ConcatSource.js:40:49
    at Array.map (native)
    at ConcatSource.node (/home/cit/imvu/website-project/website/unicorns_sections/sticker_creator/node_modules/webpack/node_modules/webpack-sources/lib/ConcatSource.js:39:60)
    at /home/cit/imvu/website-project/website/unicorns_sections/sticker_creator/node_modules/webpack/node_modules/webpack-sources/lib/ConcatSource.js:40:49
    at Array.map (native)
    at ConcatSource.node (/home/cit/imvu/website-project/website/unicorns_sections/sticker_creator/node_modules/webpack/node_modules/webpack-sources/lib/ConcatSource.js:39:60)
    at /home/cit/imvu/website-project/website/unicorns_sections/sticker_creator/node_modules/webpack/node_modules/webpack-sources/lib/ConcatSource.js:40:49
    at Array.map (native)
    at ConcatSource.node (/home/cit/imvu/website-project/website/unicorns_sections/sticker_creator/node_modules/webpack/node_modules/webpack-sources/lib/ConcatSource.js:39:60)
    at ConcatSource.proto.sourceAndMap (/home/cit/imvu/website-project/website/unicorns_sections/sticker_creator/node_modules/webpack/node_modules/webpack-sources/lib/SourceAndMapMixin.js:28:18)
    at CachedSource.sourceAndMap (/home/cit/imvu/website-project/website/unicorns_sections/sticker_creator/node_modules/webpack/node_modules/webpack-sources/lib/CachedSource.js:51:28)
    at Compilation.<anonymous> (/home/cit/imvu/website-project/website/unicorns_sections/sticker_creator/node_modules/webpack/lib/SourceMapDevToolPlugin.js:57:32)
    at Array.map (native)
    at Compilation.<anonymous> (/home/cit/imvu/website-project/website/unicorns_sections/sticker_creator/node_modules/webpack/lib/SourceMapDevToolPlugin.js:43:84)
    at Array.forEach (native)
    at Compilation.<anonymous> (/home/cit/imvu/website-project/website/unicorns_sections/sticker_creator/node_modules/webpack/lib/SourceMapDevToolPlugin.js:42:11)
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Just use `ts-loader`, then make an `index.d.ts` that imports a sibling `.d.ts` file that doesn't exist, f.e.:

```ts
import Exists from './Exists'
import DoesNotExist from './DoesNotExist'

export {
    Exists,
    DoesNotExist,
}
```

Then in the entry point just import the module that the `index.d.ts` file represents, f.e.

```js
// app.ts - typescript entry point
import * as Foo from '/path/to/somewhere/' // index.d.ts is a sibling file to index.js.
console.log(Foo)
```

**What is the expected behavior?**

Webpack should perhaps say that it could not resolve the file. I was scratching my head because I thought the file existed, but I was actually writing from my text editor to the wrong file. Eventually I discovered this.

**If this is a feature request, what is motivation or use case for changing the behavior?**

Helpful errors save time.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
 
Ubuntu Precise, node v6.3.1, npm v2.11.3, webpack v2.2.1

**Comment by trusktr** [comment]
Unfortunately, no repro since it is a complicated private repo, wish I had the time to trim it down. :{
