### ISSUE TITLE
webpack is unexpected identifier

### ISSUE THREAD

**Issue by yuwanlin** [webpack/webpack#4187]
I search some, but not the same question.
**the version of webpack is 2.2.1**
```
E:\project\test\webpack.config.js:32
                new webpack.LoaderOptionsPlugin({
                    ^^^^^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at requireConfig (E:\project\test\node_modules\.2.2.1@webpack\bin\convert-ar
gv.js:96:18)
    at E:\project\test\node_modules\.2.2.1@webpack\bin\convert-argv.js:109:17
```

**and the `webpack.config.js`**
```
module.exports = {
	entry: __dirname + '/app/main.js',
	output: {
		path: __dirname + '/public',
		filename: 'bundle.js'
	},
	devtool: 'eval-source-map',
	devServer: {
		contentBase: './public',
		colors: true,
		historyApiFallback: true,
		inline: true
	},
	module: {
		loaders: [
			{
				test: /\.json$/,
				loader: 'json-loader'
			},
			{
				test: /\.js$/,
				exclude: '/node_modules/',
				loader: 'babel-loader'
			},
			{
				test: /\.css$/,
				loader: 'style-loader!css-loader?modules!postcss-loader'
			}
		]
	},
	plugins: {
		new webpack.LoaderOptionsPlugin({
			options: {
				postcss: function() {
					return [require('autoprefixer')];
				},
			}
		})
	}
}
```

what I ignore? I am a beginner :).

**Comment by sokra** [comment]
Please submit support requests and questions to StackOverflow using the tag [[webpack]](http://stackoverflow.com/tags/webpack). StackOverflow is better suited for this kind of support. The issue tracker is for bug reports and feature discussions. See also [our CONTRIBUTING guidelines](https://github.com/webpack/webpack/blob/master/CONTRIBUTING.md).

**Comment by q640202047** [comment]
you lost this code:

var webpack = require('webpack');

**Comment by morewry** [comment]
```
const webpack = require('webpack');
                                 ^

SyntaxError: Identifier 'webpack' has already been declared
```
