### ISSUE TITLE
validate pass but cannot run

### ISSUE THREAD

**Issue by willin** [webpack/webpack#4215]
**Do you want to request a *feature* or report a *bug*?**

Question

**What is the current behavior?**

```
node src/app/server.js


/Users/willin/Desktop/test/electronvue/node_modules/webpack/lib/webpack.js:19
                throw new WebpackOptionsValidationError(webpackOptionsValidationErrors);
                ^

Error
    at webpack (/Users/willin/Desktop/test/electronvue/node_modules/webpack/lib/webpack.js:19:9)
    at Object.<anonymous> (/Users/willin/Desktop/test/electronvue/src/app/server.js:7:18)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3
```

**If the current behavior is a bug, please provide the steps to reproduce.**

webpack-config:

base.js

```js
const path = require('path');

module.exports = {
  module: {
    loaders: [{
      test: /\.vue?$/,
      loader: 'vue-loader',
      exclude: /node_modules/
    }, {
      test: /\.js$/,
      loader: 'babel-loader',
      query: {
        presets: ['latest'],
        plugins: [
          'transform-runtime'
        ]
      }
    }, {
      test: /\.(jpe?g|png|gif|svg)$/i,
      loaders: [
        'file?hash=sha512&digest=hex&name=[hash].[ext]',
        'image-webpack?bypassOnDebug&optimizationLevel=7&interlaced=false'
      ]
    }]
  },
  output: {
    path: path.join(__dirname, '../../build'),
    filename: 'app.js',
    publicPath: '/'
  },
  resolve: {
    root: path.join(__dirname, '../../'),
    extensions: ['', '.js', '.vue'],
    modulesDirectories: ['node_modules', 'src'],
    packageMains: ['webpack', 'browser', 'web', 'browserify', ['jam', 'main'], 'main'],
    alias: {}
  },
  plugins: [

  ],
  externals: [
  ]
};
```

development.js:

```js
const webpack = require('webpack');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const baseConfig = require('./base');
const path = require('path');

const config = Object.create(baseConfig);

config.debug = true;

config.devtool = 'cheap-module-eval-source-map';

config.entry = [
  'webpack-hot-middleware/client?noInfo=true&reload=true',
  './src/app/app.js'
];

config.output.publicPath = 'http://localhost:3000/build/';

config.module.loaders.push({
  test: /^((?!\.module).)*\.css$/,
  loaders: [
    'style-loader',
    'css-loader'
  ]
}, {
  test: /\.module\.css$/,
  loaders: [
    'style-loader',
    'css-loader?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!'
  ]
});

// config.resolve.alias.config = path.join(__dirname, '../config/development.js');

config.plugins.push(
  new webpack.HotModuleReplacementPlugin(),
  new webpack.NoErrorsPlugin(),
  new webpack.DefinePlugin({
    __DEV__: true,
    'process.env': {
      NODE_ENV: JSON.stringify('development')
    }
  }),
  new HtmlWebpackPlugin({
    filename: 'app.html',
    template: 'src/app/app.html'
  })
);

config.target = 'electron';

module.exports = config;
```

**What is the expected behavior?**

run properly

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

```json
{
    "webpack": "^2.2.1",
    "webpack-dev-middleware": "^1.10.0",
    "webpack-hot-middleware": "^2.16.1",
    "webpack-validator": "^2.3.0"
}
```

https://github.com/js-dxtools/webpack-validator/issues/153

```
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration has an unknown property 'debug'. These properties are valid:
   object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry, externals?, loader?, module?, name?, node?, outp
ut?, performance?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, stats?, target?,
watch?, watchOptions? }
   The 'debug' property was removed in webpack 2.
   Loaders should be updated to allow passing this option via loader options in module.rules.
   Until loaders are updated one can use the LoaderOptionsPlugin to switch loaders into debug mode:
   plugins: [
     new webpack.LoaderOptionsPlugin({
       debug: true
     })
   ]
 - configuration.resolve has an unknown property 'packageMains'. These properties are valid:
   object { alias?, aliasFields?, cachePredicate?, descriptionFiles?, enforceExtension?, enforceModuleExtension?, extensions?, fileSyst
em?, mainFields?, mainFiles?, moduleExtensions?, modules?, plugins?, resolver?, symlinks?, unsafeCache?, useSyncFileSystemCalls? }
 - configuration.resolve.extensions[0] should not be empty.
```

**Comment by bebraw** [comment]
`debug` and `resolve.packageMains` aren't supported as the error message implies. `resolve.extensions` is not allowed to contain empty entries either.

See [the migration guide](https://webpack.js.org/guides/migrating/).
