### ISSUE TITLE
Cannot configure webpack 2.2.1 correctly, keep throwing WebpackOptionsValidationError

### ISSUE THREAD

**Issue by XidongHuang** [webpack/webpack#4222]
**Do you want to request a *feature* or report a *bug*?**
a bug

**What is the current behavior?**
I used **webpack@2.1.0-beta.22** and **webpack-dev-server@2.1.0-beta.10** before, and it worked fine. The configuration is: 
```
//webpack.config.js

var path = require('path');
var webpack = require('webpack');

module.exports = {
     entry: ['redux-exercise.js',
               'webpack/hot/dev-server', 
               'webpack-dev-server/client?http://localhost:9090/'],
     output: {
                path: path.join(__dirname, './dist'),
                filename: 'bundle.js'
               },
      module: {
                  loaders: [
                      {
                         test: /\.jsx?$/,
                         exclude: /node_modules/,
                         loaders: ['react-hot']
                       },
                       {
                         test: /\.jsx?$/,
                         loaders: ['babel-loader'],
                         exclude: /node-modules/,
                         query: {
                             presets: ['react', 'es2015', 'stage-0']
                            }

                          }

                   ],
                   resolve: {
                           extensions: ['', '.js', '.jsx', '.css'],
                           modulesDirectories: [
                           'node_modules'
                   ]

                    }
},
plugins: [new webpack.HotModuleReplacementPlugin(), new webpack.NoErrorsPlugin()]

}

```
and I also used dev-server:
```
//dev-server.js

var WebpackDevServer = require('webpack-dev-server');
var webpack = require('webpack');
var config = require('./webpack.config.js');
var path = require('path');

var compiler = webpack(config);
var server = new WebpackDevServer(compiler, {
    hot: true,
    filename: config.output.filename,
    publicPath: config.output.publicPath,
    stats: {
        colors: true
    }
});

server.listen(9090, 'localhost', function() {});

```
so the files above are what I used before.

However, I try to update my webpack to 2.2, my new configuration like this:
```
var path = require('path');
var webpack = require('webpack');


module.exports = {
    entry: ['redux-exercise.js',
                'webpack/hot/dev-server', 
                'webpack-dev-server/client?http://localhost:9090/'],
    output: {
        path: path.join(__dirname, './dist'),
        filename: 'bundle.js'
    },
    module: 
    {
            rules: [
            {
                test:/\.jsx?$/,
                exclude: /node_modules/,
                use: ['react-hot']
            },
            {
                test: /\.jsx?$/,
                loaders: ['babel-loader'],
                exclude: /node_modules/,
                options: {
                    presets: ['react', 'es2015', 'stage-0',{"modules": false}]
                }
            }
            
        ],
        resolve: {
            extensions: ['', '.js', '.jsx'],
            modules: [
                'node_modules'
            ]
        }
    },
    plugins: [new webpack.HotModuleReplacementPlugin(), new webpack.NoErrorsPlugin()]
}

```
the **dev-server.js** is the same, but when I do **npm run dev** , it keeps throwing **new WebpackOptionsValidationError**. 

**What is the expected behavior?**
I expect to run the **dev-server** for my react program, and run with **hot-rolader**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
My Environment: 
```
Node.js: 7.5
system: unbuntu 14.04
```
package.json: 
```
{
  "name": "exercise-react-redux",
  "version": "0.1.0",
  "description": "",
  "main": "app.js",
  "scripts": {
    "dev": "node dev-server.js"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "react": "15.4.2",
    "react-dom": "15.4.2",
    "react-redux": "5.0.2",
    "redux": "3.6.0",
    "redux-thunk": "2.2.0"
  },
  "devDependencies": {
    "babel-core": "^6.22.1",
    "babel-loader": "^6.2.10",
    "babel-preset-es2015": "^6.22.0",
    "babel-preset-react": "^6.22.0",
    "babel-preset-stage-0": "^6.22.0",
    "jsx-loader": "^0.13.2",
    "react-hot-loader": "^1.3.1",
    "webpack": "^2.2.1",
    "webpack-dev-server": "^2.3.0"
  }
}

```

**Comment by bebraw** [comment]
Can you include the entire error?

**Comment by XidongHuang** [comment]
@bebraw Yep,
```
/home/tony/Documents/React/ReactNRedux/node_modules/webpack/lib/webpack.js:19
                throw new WebpackOptionsValidationError(webpackOptionsValidationErrors);
                ^

Error
    at webpack (/home/tony/Documents/React/ReactNRedux/node_modules/webpack/lib/webpack.js:19:9)
    at Object.<anonymous> (/home/tony/Documents/React/ReactNRedux/dev-server.js:6:16)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:418:7)
    at startup (bootstrap_node.js:139:9)

```

**Comment by bebraw** [comment]
`loaders: ['babel-loader'],` could become `loader: 'babel-loader'`, but apart from that I don't see anything obvious. A little project to run would be ideal.

**Comment by XidongHuang** [comment]
@bebraw I tried `loader: 'babel-loader'`, but it still does not work.
I will try more later, thanks for your quick response.

**Comment by sokra** [comment]
`resolve.extensions` should not have an empty string as item.

But I wonder why the validation error has no message it it...

**Comment by XidongHuang** [comment]
Thanks @sokra , besides need to fix ```resolve: { extensions: ['.js', '.jsx'], modules: ['node_modules']}```, I also need to put the whole **resolve** part out of **module**. So the correct configuration for it should be:
```
var path = require('path');
var webpack = require('webpack');


module.exports = {
    entry: ['redux-exercise.js',
                'webpack/hot/dev-server', 
                'webpack-dev-server/client?http://localhost:9090/'],
    output: {
        path: path.join(__dirname, './dist'),
        filename: 'bundle.js'
    },
    module: 
    {
            rules: [
            {
                test:/\.jsx?$/,
                exclude: /node_modules/,
                use: ['react-hot']
            },
            {
                test: /\.jsx?$/,
                loaders: ['babel-loader'],
                exclude: /node_modules/,
                options: {
                    presets: ['react', 'es2015', 'stage-0'] //**Change
                }
            }
            
        ]
    },
  //**Change
    resolve: {
            extensions: ['.js', '.jsx'], //**Change
            modules: [
                'node_modules'
            ]
        },
    plugins: [new webpack.HotModuleReplacementPlugin(), new webpack.NoErrorsPlugin()]
}

```

Thanks for you guys hard working and patient again!

**Comment by kauhal** [comment]
C:\Users\kaushal\AwesomeProject\react-todos>webpack-dev-server
Configuration file found but no entry configured.
Use --help to display the CLI options.

I have this problem please give me a better solution for conectting to the local host:8080

**Comment by XidongHuang** [comment]
@kauhal more details for your webpack.config.js?

**Comment by immanoj16** [comment]
`var debug = process.env.NODE_ENV !== "production";
var webpack = require('webpack');

module.exports = {
    context: __dirname + "/src",
    devtool: debug ? "inline-sourcemap" : false,
    module: {
        loaders: [
            {
                test: /\.js?$/,
                exclude: /(node_modules|bower_components)/,
                loader: 'babel-loader',
                query: {
                    presets: ['react', 'es2015', 'stage-0'],
                    plugins: ['react-html-attrs', 'transform-class-properties', 'tranform-decorators-legacy']
                }
            }
        ]
    },
    output: {
        path: __dirname + "/src",
        filename: "client.min.js"
    },
    plugins: debug ? [] : [
        new webpack.optimize.DedupePlugin(),
        new webpack.optimize.OccurrenceOrderPlugin(),
        new webpack.optimize.UglifyJsPlugin({ mangle: false, sourcemap: false }),
    ],
};
`
And I have some problem written

Configuration file found but no entry configured.
Use --help to display the CLI options.

Please give me the solution for this.
