### ISSUE TITLE
Incorrect errors (webpackOptionsValidationErrors)

### ISSUE THREAD

**Issue by monolithed** [webpack/webpack#4262]
### Config

```js
{
       debug: true,
       .....
}
```

### Actual

```
/node_modules/webpack/lib/webpack.js:19
		throw new WebpackOptionsValidationError(webpackOptionsValidationErrors);
        ^
Error
    at webpack (/node_modules/webpack/lib/webpack.js:19:9)
    at Object.<anonymous> (debug/server.js:11:12)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
```

### Expected

```
should NOT have additional properties: debug
....
```

The problem [here](https://github.com/webpack/webpack/blob/master/lib/webpack.js#L19)

**Comment by bebraw** [comment]
`debug: true` is disallowed. See https://webpack.js.org/guides/migrating/#debug .

**Comment by monolithed** [comment]
@bebraw, It seems you didn't see what I mean. Allowed or disallowed — it does not matter to me. I want to see the expected error or waring from `webpackOptionsValidationErrors.message`:

```
should NOT have additional properties: debug
```

**Comment by bebraw** [comment]
Ok, tagged. Let's see if someone does a PR.

**Comment by sokra** [comment]
see #4257
