### ISSUE TITLE
Webpack tries to use less module as less-loader

### ISSUE THREAD

**Issue by larsbs** [webpack/webpack#4315]
**Do you want to request a *feature* or report a *bug*?**

Report a bug

**What is the current behavior?**

I'm trying to use `less-loader` in a webpack configuration but when running webpack, it's trying to use the `less` module. So it's giving me the following error: `Error: Module '/path/to/project/node_modules/less/index.js' is not a loader (must have normal or pitch function)`. This is suppose to happen if a configure `less` as loader instead of `less-loader`, but I have it configured correctly.

**If the current behavior is a bug, please provide the steps to reproduce.**

Add **less** and **less-loader** and try to compile. This is my full config: 

```
const path = require('path');
const webpack = require('webpack');
const autoprefixer = require('autoprefixer');
const cssnano = require('cssnano');
const packageJson = require('./package.json');


const rootDirs = [
  path.resolve(__dirname, 'app'),
  path.resolve(__dirname, 'test'),
  path.resolve(__dirname, 'vendor'),
];


module.exports = {
  resolve: {
    modules: [
      ...rootDirs,
      path.resolve(__dirname, 'public'),
      'node_modules',
    ],
    extensions: ['.js', '.jsx', '.less'],
  },
  entry: {
    frontoffice: [ './app/app.jsx' ],
  },
  output: {
    path: path.resolve(__dirname, '../builds'),
    publicPath: '/',
    filename: '[name].entry.js'
  },
  plugins: [
    //new webpack.DefinePlugin({
      //'process.env': { APP_VERSION: JSON.stringify(packageJson.version) },
    //}),
  ],
  module: {
    rules: [
      {
        test: /\.jsx?$/,
        include: rootDirs,
        use: [
          {
            loader: 'babel-loader',
            options: {
              presets: [ ['es2015', { modules: false }], 'stage-0', 'react' ],
            },
          }
        ],
      },
      {
        test: /\.css$/,
        use: [
          {
            loader: 'style-loader',
          },
          {
            loader: 'css-loader',
            options: {
              sourceMap: true,
              localIndentName: '[name]__[local]--[hash:base64:5]',
            },
          },
          {
            loader: 'postcss-loader',
            options: {
              sourceMap: true,
              plugins: () => [ autoprefixer, cssnano({ safe: true}) ],
            },
          },
        ]
      },
      {
        test: /\.less$/,
        use: [
          {
            loader: 'style-loader',
          },
          {
            loader: 'css-loader',
            options: {
              sourceMap: true,
              localIndentName: '[name]__[local]--[hash:base64:5]',
            },
          },
          {
            loader: 'postcss-loader',
            options: {
              sourceMap: true,
              plugins: () => [ autoprefixer, cssnano({ safe: true}) ],
            },
          },
          {
            loader: 'less-loader',
            options: {
              sourceMap: true,
            },
          }
        ]
      },
      {
        test: /\.woff([^2].*)?$/,
        use: [
          {
            loader: 'file-loader',
            options: {
              name: '/[name].[ext]',
            },
          },
        ]
      },
      {
        test: /\.woff2(.*)?$/,
        use: [
          {
            loader: 'file-loader',
          }
        ],
      },
      {
        test: /\.ttf(.*)?$/,
        use: [
          {
            loader: 'url-loader',
            options: {
              limit: 10000,
              mimetype: 'application/octet-stream',
            },
          },
        ],
      },
      {
        test: /\.eot(.*)?$/,
        use: [
          {
            loader: 'file-loader',
          }
        ],
      },
      {
        test: /\.otf$/,
        use: [
          {
            loader: 'url-loader',
            options: {
              limit: 10000,
              mimetype: 'application/octet-stream',
            },
          },
        ],
      },
      {
        test: /\.svg(.*)?$/,
        use: [
          {
            loader: 'url-loader',
            options: {
              limit: 10000,
              mimetype: 'image/svg+xml',
            },
          },
        ],
      },
      {
        test: /\.jpg$/,
        use: [
          {
            loader: 'url-loader',
            options: {
              limit: 10000,
              mimetype: 'image/jpg',
            },
          },
        ],
      },
      {
        test: /\.png$/,
        use: [
          {
            loader: 'url-loader',
            options: {
              limit: 10000,
              mimetype: 'image/png',
            },
          },
        ],
      },
    ],
  },
};
```

And these are the versions of the relevant packages: 

```
 "less": "^2.7.2",
 "less-loader": "^2.2.3",
 "webpack": "^2.2.1",
 "webpack-dev-server": "^2.3.0"
```

**What is the expected behavior?**

It should compile the bundle.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by sokra** [comment]
Could you add the full error message?

**Comment by larsbs** [comment]
Sure, this is the full error message: 

```
 68% building modules 1262/1300 modules 38 active ...ds/order/styles/containers/order.less/Users/lars/Development/Ruby/platform/app/assets/javascripts/frontoffice/node_modules/loader-runner/lib/loadLoader.js:35
                        throw new Error("Module '" + loader.path + "' is not a loader (must have normal or pitch function)");
                        ^

Error: Module '/Users/lars/Development/Ruby/platform/app/assets/javascripts/frontoffice/node_modules/less/index.js' is not a loader (must have normal or pitch function)
    at loadLoader (/Users/lars/Development/Ruby/platform/app/assets/javascripts/frontoffice/node_modules/loader-runner/lib/loadLoader.js:35:10)
    at iteratePitchingLoaders (/Users/lars/Development/Ruby/platform/app/assets/javascripts/frontoffice/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/Users/lars/Development/Ruby/platform/app/assets/javascripts/frontoffice/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /Users/lars/Development/Ruby/platform/app/assets/javascripts/frontoffice/node_modules/loader-runner/lib/LoaderRunner.js:173:18
    at loadLoader (/Users/lars/Development/Ruby/platform/app/assets/javascripts/frontoffice/node_modules/loader-runner/lib/loadLoader.js:36:3)
    at iteratePitchingLoaders (/Users/lars/Development/Ruby/platform/app/assets/javascripts/frontoffice/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at runLoaders (/Users/lars/Development/Ruby/platform/app/assets/javascripts/frontoffice/node_modules/loader-runner/lib/LoaderRunner.js:362:2)
    at NormalModule.doBuild (/Users/lars/Development/Ruby/platform/app/assets/javascripts/frontoffice/node_modules/webpack/lib/NormalModule.js:129:2)
    at NormalModule.build (/Users/lars/Development/Ruby/platform/app/assets/javascripts/frontoffice/node_modules/webpack/lib/NormalModule.js:180:15)
    at Compilation.buildModule (/Users/lars/Development/Ruby/platform/app/assets/javascripts/frontoffice/node_modules/webpack/lib/Compilation.js:142:10)
    at factoryCallback (/Users/lars/Development/Ruby/platform/app/assets/javascripts/frontoffice/node_modules/webpack/lib/Compilation.js:324:11)
    at /Users/lars/Development/Ruby/platform/app/assets/javascripts/frontoffice/node_modules/webpack/lib/NormalModuleFactory.js:242:4
    at /Users/lars/Development/Ruby/platform/app/assets/javascripts/frontoffice/node_modules/webpack/lib/NormalModuleFactory.js:93:13
    at /Users/lars/Development/Ruby/platform/app/assets/javascripts/frontoffice/node_modules/tapable/lib/Tapable.js:204:11
    at NormalModuleFactory.params.normalModuleFactory.plugin (/Users/lars/Development/Ruby/platform/app/assets/javascripts/frontoffice/node_modules/webpack/lib/CompatibilityPlugin.js:52:5)
    at NormalModuleFactory.applyPluginsAsyncWaterfall (/Users/lars/Development/Ruby/platform/app/assets/javascripts/frontoffice/node_modules/tapable/lib/Tapable.js:208:13)
    at onDoneResolving (/Users/lars/Development/Ruby/platform/app/assets/javascripts/frontoffice/node_modules/webpack/lib/NormalModuleFactory.js:68:11)
    at onDoneResolving (/Users/lars/Development/Ruby/platform/app/assets/javascripts/frontoffice/node_modules/webpack/lib/NormalModuleFactory.js:189:6)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
error Command failed with exit code 1.
```

**Comment by larsbs** [comment]
Ok, my bad. The problem was that somewhere deep in the code, there were some calls to `less-loader` directly when importing some files, but those calls were written without the `-loader` part.
