### ISSUE TITLE
less-loader not being read when building and .less files always return error 'Module build failed: Unknown word'

### ISSUE THREAD

**Issue by Dean-Christian-Armada** [webpack/webpack#4369]
I always get this error when I try to **npm run build** on my vue.js app:

```
ERROR in ./~/css-loader?sourceMap!./~/vux/src/styles/1px.less
Module build failed: Unknown word (23:5)

  21 | .vux-1px {
  22 |   &:before {
> 23 |     .setLine();
     |     ^
  24 |   }
  25 | }
  26 | 

 @ ./~/css-loader?sourceMap!./~/vue-loader/lib/style-rewriter.js?id=data-v-3645c0bf!./~/vux-loader/src/style-loader.js!./~/vue-loader/lib/selector.js?type=styles&index=0!./src/App.vue 4:10-92
 @ ./~/extract-text-webpack-plugin/loader.js?{"omit":1,"remove":true}!./~/vue-style-loader!./~/css-loader?sourceMap!./~/vue-loader/lib/style-rewriter.js?id=data-v-3645c0bf!./~/vux-loader/src/style-loader.js!./~/vue-loader/lib/selector.js?type=styles&index=0!./src/App.vue
 @ ./src/App.vue
 @ ./src/main.js

ERROR in ./~/css-loader?sourceMap!./~/vux/src/styles/weui/base/reset.less
Module build failed: Unknown word (24:5)

  22 | a {
  23 |     text-decoration: none;
> 24 |     .setTapColor();
     |     ^
  25 | }

 @ ./~/css-loader?sourceMap!./~/vux/src/styles/reset.less 3:10-84
 @ ./~/css-loader?sourceMap!./~/vue-loader/lib/style-rewriter.js?id=data-v-3645c0bf!./~/vux-loader/src/style-loader.js!./~/vue-loader/lib/selector.js?type=styles&index=0!./src/App.vue
 @ ./~/extract-text-webpack-plugin/loader.js?{"omit":1,"remove":true}!./~/vue-style-loader!./~/css-loader?sourceMap!./~/vue-loader/lib/style-rewriter.js?id=data-v-3645c0bf!./~/vux-loader/src/style-loader.js!./~/vue-loader/lib/selector.js?type=styles&index=0!./src/App.vue
 @ ./src/App.vue
 @ ./src/main.js

ERROR in ./~/extract-text-webpack-plugin/loader.js?{"omit":1,"remove":true}!./~/vue-style-loader!./~/css-loader?sourceMap!./~/vue-loader/lib/style-rewriter.js?id=data-v-3645c0bf!./~/vux-loader/src/style-loader.js!./~/vue-loader/lib/selector.js?type=styles&index=0!./src/App.vue
Module build failed: Error
    at /Users/deanchristianarmada/Desktop/projects/ci/lion2/node_modules/webpack/lib/NormalModule.js:141:35
    at /Users/deanchristianarmada/Desktop/projects/ci/lion2/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /Users/deanchristianarmada/Desktop/projects/ci/lion2/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at context.callback (/Users/deanchristianarmada/Desktop/projects/ci/lion2/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.<anonymous> (/Users/deanchristianarmada/Desktop/projects/ci/lion2/node_modules/css-loader/lib/loader.js:32:18)
    at /Users/deanchristianarmada/Desktop/projects/ci/lion2/node_modules/css-loader/lib/processCss.js:222:4
    at runMicrotasksCallback (internal/process/next_tick.js:58:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

ERROR in /Users/deanchristianarmada/Desktop/projects/ci/lion2/node_modules/extract-text-webpack-plugin/loader.js?{"omit":1,"remove":true}!/Users/deanchristianarmada/Desktop/projects/ci/lion2/node_modules/vue-style-loader/index.js!/Users/deanchristianarmada/Desktop/projects/ci/lion2/node_modules/css-loader/index.js?sourceMap!/Users/deanchristianarmada/Desktop/projects/ci/lion2/node_modules/vue-loader/lib/style-rewriter.js?id=data-v-3645c0bf!/Users/deanchristianarmada/Desktop/projects/ci/lion2/node_modules/vux-loader/src/style-loader.js!/Users/deanchristianarmada/Desktop/projects/ci/lion2/node_modules/vue-loader/lib/selector.js?type=styles&index=0!/Users/deanchristianarmada/Desktop/projects/ci/lion2/src/App.vue doesn't export content
```

my **package.json** is:

```
{
  "name": "lion",
  "version": "1.0.0",
  "description": "A Vue.js project",
  "author": "Snow <snow@unnotech.com>",
  "private": true,
  "scripts": {
    "dev": "node build/dev-server.js",
    "build": "node build/build.js",
    "lint": "eslint --ext .js,.vue src"
  },
  "dependencies": {
    "vue": "^2.1.10",
    "vue-router": "^2.2.0",
    "vux": "^2.1.0-rc.48"
  },
  "devDependencies": {
    "autoprefixer": "^6.7.2",
    "babel-core": "^6.22.1",
    "babel-eslint": "^7.1.1",
    "babel-loader": "^6.2.10",
    "babel-plugin-transform-runtime": "^6.22.0",
    "babel-preset-es2015": "^6.22.0",
    "babel-preset-stage-2": "^6.22.0",
    "babel-register": "^6.22.0",
    "chalk": "^1.1.3",
    "connect-history-api-fallback": "^1.3.0",
    "css-loader": "^0.26.1",
    "eslint": "^3.14.1",
    "eslint-config-standard": "^6.2.1",
    "eslint-friendly-formatter": "^2.0.7",
    "eslint-loader": "^1.6.1",
    "eslint-plugin-html": "^2.0.0",
    "eslint-plugin-promise": "^3.4.0",
    "eslint-plugin-standard": "^2.0.1",
    "eventsource-polyfill": "^0.9.6",
    "express": "^4.14.1",
    "extract-text-webpack-plugin": "^2.0.0-rc.2",
    "file-loader": "^0.10.0",
    "friendly-errors-webpack-plugin": "^1.1.3",
    "function-bind": "^1.1.0",
    "html-webpack-plugin": "^2.28.0",
    "http-proxy-middleware": "^0.17.3",
    "less": "^2.7.2",
    "less-loader": "^2.2.3",
    "moment": "^2.17.1",
    "opn": "^4.0.2",
    "ora": "^1.1.0",
    "semver": "^5.3.0",
    "shelljs": "^0.7.6",
    "url-loader": "^0.5.7",
    "vue-cookie": "^1.1.3",
    "vue-i18n": "^5.0.0",
    "vue-loader": "^10.3.0",
    "vue-moment": "^2.0.2",
    "vue-resource": "^1.2.0",
    "vue-style-loader": "^2.0.0",
    "vue-swipe": "^2.0.2",
    "vue-template-compiler": "^2.1.10",
    "vue2-filters": "^0.1.6",
    "vuex": "^2.1.2",
    "vuex-router-sync": "^4.1.2",
    "vux": "^2.1.0-rc.28",
    "vux-loader": "^1.0.35",
    "webpack": "^2.2.1",
    "webpack-bundle-analyzer": "^2.2.1",
    "webpack-dev-middleware": "^1.10.0",
    "webpack-hot-middleware": "^2.16.1",
    "webpack-merge": "^2.6.1"
  },
  "engines": {
    "node": ">= 4.0.0",
    "npm": ">= 3.0.0"
  }
}
```

my **webpack.base.conf.js**:

```
var path = require('path')
var utils = require('./utils')
var config = require('../config')
var vueLoaderConfig = require('./vue-loader.conf')
var ExtractTextPlugin = require('extract-text-webpack-plugin');

function resolve (dir) {
  return path.join(__dirname, '..', dir)
}

let webpackConfig = {
  entry: {
    app: './src/main.js'
  },
  output: {
    path: config.build.assetsRoot,
    filename: '[name].js',
    publicPath: process.env.NODE_ENV === 'production'
      ? config.build.assetsPublicPath
      : config.dev.assetsPublicPath
  },
  resolve: {
    extensions: ['.js', '.vue', '.json'],
    modules: [
      resolve('src'),
      resolve('node_modules')
    ],
    alias: {
      'vue$': 'vue/dist/vue.common.js',
      'src': resolve('src'),
      'assets': resolve('src/assets'),
      'components': resolve('src/components')
    }
  },
  module: {
    rules: [
      {
        test: /\.(js|vue)$/,
        loader: 'eslint-loader',
        enforce: "pre",
        include: [resolve('src'), resolve('test')],
        options: {
          formatter: require('eslint-friendly-formatter')
        }
      },
      {
        test: /\.vue$/,
        loader: 'vue-loader',
        options: vueLoaderConfig
      },
      {
        test: /\.js$/,
        loader: 'babel-loader',
        include: [resolve('src'), resolve('test')]
      },
      {
        test: /\.(png|jpe?g|gif|svg)(\?.*)?$/,
        loader: 'url-loader',
        query: {
          limit: 10000,
          name: utils.assetsPath('img/[name].[hash:7].[ext]')
        }
      },
      {
        test: /\.(woff2?|eot|ttf|otf)(\?.*)?$/,
        loader: 'url-loader',
        query: {
          limit: 10000,
          name: utils.assetsPath('fonts/[name].[hash:7].[ext]')
        }
      },
      {
        test: /\.less$/,
        loader: ExtractTextPlugin.extract({
          fallback: 'vue-style-loader',
          use: ['css', 'less']
        })
      }
    ]
  }
}

const vuxLoader = require('vux-loader')
module.exports = vuxLoader.merge(webpackConfig, {
  options: {},
  plugins: [
    {
      name: 'vux-ui'
    }
  ]
})
```

my **webpack.prod.conf.js**

```
var path = require('path')
var utils = require('./utils')
var webpack = require('webpack')
var config = require('../config')
var merge = require('webpack-merge')
var baseWebpackConfig = require('./webpack.base.conf')
var HtmlWebpackPlugin = require('html-webpack-plugin')
var ExtractTextPlugin = require('extract-text-webpack-plugin')
var env = config.build.env

var webpackConfig = merge(baseWebpackConfig, {
  module: {
    rules: utils.styleLoaders({
      sourceMap: config.build.productionSourceMap,
      extract: true
    })
  },
  devtool: config.build.productionSourceMap ? '#source-map' : false,
  output: {
    path: config.build.assetsRoot,
    filename: utils.assetsPath('js/[name].[chunkhash].js'),
    chunkFilename: utils.assetsPath('js/[id].[chunkhash].js')
  },
  plugins: [
    // http://vuejs.github.io/vue-loader/en/workflow/production.html
    new webpack.DefinePlugin({
      'process.env': env
    }),
    new webpack.optimize.UglifyJsPlugin({
      compress: {
        warnings: false
      }
    }),
    // extract css into its own file
    new ExtractTextPlugin({
      filename: utils.assetsPath('css/[name].[contenthash].css')
    }),
    // generate dist index.html with correct asset hash for caching.
    // you can customize output by editing /index.html
    // see https://github.com/ampedandwired/html-webpack-plugin
    new HtmlWebpackPlugin({
      filename: config.build.index,
      template: 'index.html',
      inject: true,
      minify: {
        removeComments: true,
        collapseWhitespace: true,
        removeAttributeQuotes: true
        // more options:
        // https://github.com/kangax/html-minifier#options-quick-reference
      },
      // necessary to consistently work with multiple chunks via CommonsChunkPlugin
      chunksSortMode: 'dependency'
    }),
    // split vendor js into its own file
    new webpack.optimize.CommonsChunkPlugin({
      name: 'vendor',
      minChunks: function (module, count) {
        // any required modules inside node_modules are extracted to vendor
        return (
          module.resource &&
          /\.js$/.test(module.resource) &&
          module.resource.indexOf(
            path.join(__dirname, '../node_modules')
          ) === 0
        )
      }
    }),
    // extract webpack runtime and module manifest to its own file in order to
    // prevent vendor hash from being updated whenever app bundle is updated
    new webpack.optimize.CommonsChunkPlugin({
      name: 'manifest',
      chunks: ['vendor']
    })
  ]
})

if (config.build.productionGzip) {
  var CompressionWebpackPlugin = require('compression-webpack-plugin')

  webpackConfig.plugins.push(
    new CompressionWebpackPlugin({
      asset: '[path].gz[query]',
      algorithm: 'gzip',
      test: new RegExp(
        '\\.(' +
        config.build.productionGzipExtensions.join('|') +
        ')$'
      ),
      threshold: 10240,
      minRatio: 0.8
    })
  )
}

if (config.build.bundleAnalyzerReport) {
  var BundleAnalyzerPlugin = require('webpack-bundle-analyzer').BundleAnalyzerPlugin
  webpackConfig.plugins.push(new BundleAnalyzerPlugin())
}

module.exports = webpackConfig
```

It's weird because I already included the less-loader. Then I tried doing research and seems like less files currently has an issue in webpacks and would like to inform this error. Is the one I'm encountering also an issue in webpack?

**Comment by timse** [comment]
can you create a repository to recreate that bug?

**Comment by Dean-Christian-Armada** [comment]
Here you go, https://github.com/Dean-Christian-Armada/vue-project-issue

**Comment by timse** [comment]
It would be nice to give a decent sized reproducible repo. I dont feel like reading your complete project to figure out whats happening.

This is the resulting config your project produces, which has little to do with what you mentioned.
Please make this sane and give a proper reproducible project if that problem persists.

```
{
  module:
  {
    rules:
    [{
      test: /\.(js|vue)$/,
      loader: 'eslint-loader',
      enforce: 'pre',
      include:
      ['/vue-project-issue/src',
        '/vue-project-issue/test'],
      options: { formatter: [Function] }
    },
    {
      test: /\.vue$/,
      use:
      ['vux-loader',
        {
          loader: 'vue-loader',
          options:
          {
            loaders:
            {
              css:
              [{
                loader: '/vue-project-issue/node_modules/extract-text-webpack-plugin/loader.js',
                options: { omit: 1, remove: true }
              },
              { loader: 'vue-style-loader' },
              { loader: 'css-loader?sourceMap' }],
              postcss:
              [{
                loader: '/vue-project-issue/node_modules/extract-text-webpack-plugin/loader.js',
                options: { omit: 1, remove: true }
              },
              { loader: 'vue-style-loader' },
              { loader: 'css-loader?sourceMap' }],
              less:
              [{
                loader: '/vue-project-issue/node_modules/extract-text-webpack-plugin/loader.js',
                options: { omit: 1, remove: true }
              },
              { loader: 'vue-style-loader' },
              { loader: 'css-loader?sourceMap' },
              { loader: 'less-loader?sourceMap' }],
              sass:
              [{
                loader: '/vue-project-issue/node_modules/extract-text-webpack-plugin/loader.js',
                options: { omit: 1, remove: true }
              },
              { loader: 'vue-style-loader' },
              { loader: 'css-loader?sourceMap' },
              { loader: 'sass-loader?indentedSyntax&sourceMap' }],
              scss:
              [{
                loader: '/vue-project-issue/node_modules/extract-text-webpack-plugin/loader.js',
                options: { omit: 1, remove: true }
              },
              { loader: 'vue-style-loader' },
              { loader: 'css-loader?sourceMap' },
              { loader: 'sass-loader?sourceMap' }],
              stylus:
              [{
                loader: '/vue-project-issue/node_modules/extract-text-webpack-plugin/loader.js',
                options: { omit: 1, remove: true }
              },
              { loader: 'vue-style-loader' },
              { loader: 'css-loader?sourceMap' },
              { loader: 'stylus-loader?sourceMap' }],
              styl:
              [{
                loader: '/vue-project-issue/node_modules/extract-text-webpack-plugin/loader.js',
                options: { omit: 1, remove: true }
              },
              { loader: 'vue-style-loader' },
              { loader: 'css-loader?sourceMap' },
              { loader: 'stylus-loader?sourceMap' }]
            },
            postcss:
            [{
              "[Function: plugin]  options": { browsers: ['last 2 versions'] },
              info: [Function],
              postcssPlugin: 'autoprefixer',
              postcssVersion: '5.2.15'
            }]
          }
        }]
    },
    {
      test: /\.js$/,
      loader: 'babel-loader!/vue-project-issue/node_modules/vux-loader/src/js-loader.js',
      include:
      ['/vue-project-issue/src',
        '/vue-project-issue/test']
    },
    {
      test: /\.(png|jpe?g|gif|svg)(\?.*)?$/,
      loader: 'url-loader',
      query: { limit: 10000, name: 'static/img/[name].[hash:7].[ext]' }
    },
    {
      test: /\.(woff2?|eot|ttf|otf)(\?.*)?$/,
      loader: 'url-loader',
      query: { limit: 10000, name: 'static/fonts/[name].[hash:7].[ext]' }
    },
    {
      test: /node_modules.*vux.src.*?js$/,
      loader: 'babel-loader',
      include: '/vue-project-issue/node_modules/vux'
    },
    {
      test: /\.css$/,
      loader:
      [{
        loader: '/vue-project-issue/node_modules/extract-text-webpack-plugin/loader.js',
        options: { omit: 1, remove: true }
      },
      { loader: 'vue-style-loader' },
      { loader: 'css-loader?sourceMap' }]
    },
    {
      test: /\.postcss$/,
      loader:
      [{
        loader: '/vue-project-issue/node_modules/extract-text-webpack-plugin/loader.js',
        options: { omit: 1, remove: true }
      },
      { loader: 'vue-style-loader' },
      { loader: 'css-loader?sourceMap' }]
    },
    {
      test: /\.less$/,
      loader:
      [{
        loader: '/vue-project-issue/node_modules/extract-text-webpack-plugin/loader.js',
        options: { omit: 1, remove: true }
      },
      { loader: 'vue-style-loader' },
      { loader: 'css-loader?sourceMap' },
      { loader: 'less-loader?sourceMap' }]
    },
    {
      test: /\.sass$/,
      loader:
      [{
        loader: '/vue-project-issue/node_modules/extract-text-webpack-plugin/loader.js',
        options: { omit: 1, remove: true }
      },
      { loader: 'vue-style-loader' },
      { loader: 'css-loader?sourceMap' },
      { loader: 'sass-loader?indentedSyntax&sourceMap' }]
    },
    {
      test: /\.scss$/,
      loader:
      [{
        loader: '/vue-project-issue/node_modules/extract-text-webpack-plugin/loader.js',
        options: { omit: 1, remove: true }
      },
      { loader: 'vue-style-loader' },
      { loader: 'css-loader?sourceMap' },
      { loader: 'sass-loader?sourceMap' }]
    },
    {
      test: /\.stylus$/,
      loader:
      [{
        loader: '/vue-project-issue/node_modules/extract-text-webpack-plugin/loader.js',
        options: { omit: 1, remove: true }
      },
      { loader: 'vue-style-loader' },
      { loader: 'css-loader?sourceMap' },
      { loader: 'stylus-loader?sourceMap' }]
    },
    {
      test: /\.styl$/,
      loader:
      [{
        loader: '/vue-project-issue/node_modules/extract-text-webpack-plugin/loader.js',
        options: { omit: 1, remove: true }
      },
      { loader: 'vue-style-loader' },
      { loader: 'css-loader?sourceMap' },
      { loader: 'stylus-loader?sourceMap' }]
    }]
  },
}
```
