### ISSUE TITLE
[I18nPlugin] Using compiler.parser is deprecated

### ISSUE THREAD

**Issue by wzup** [webpack/webpack#4385]
This wp config
```
new I18nPlugin({'en': {hello: 'hello'}, 'de': {hello: 'hello'}}, {functionName: 'i18n'}),
```
leads to this warning
```
webpack: Using compiler.parser is deprecated.
Use compiler.plugin("compilation", function(compilation, data) {
  data.normalModuleFactory.plugin("parser", function(parser, options) { parser.plugin(/* ... */); });
}); instead. It was called at I18nPlugin.apply (C:\Users\user\app\node_modules\i18n-webpack-plugin\index.js:43:18).
webpack: Using compiler.parser is deprecated.
Use compiler.plugin("compilation", function(compilation, data) {
  data.normalModuleFactory.plugin("parser", function(parser, options) { parser.plugin(/* ... */); });
}); instead. It was called at I18nPlugin.apply (C:\Users\user\app\node_modules\i18n-webpack-plugin\index.js:43:18).
```

And plugin doesn't work either
```
ReferenceError: i18n is not defined
```

**Comment by bebraw** [comment]
Can you track https://github.com/webpack-contrib/i18n-webpack-plugin/pull/23 ? It's better to push issues to that repo in this case.
