### ISSUE TITLE
TypeError: pair[2].integrate is not a function

### ISSUE THREAD

**Issue by zhouce** [webpack/webpack#4534]
**report a *bug***
I think it's a bug.

**current behavior & the steps to reproduce**
I add the plugin:
`plugins: [
         /**/
        new webpack.optimize.MinChunkSizePlugin({
            minChunkSize: 10000
        }),
        /**/
    ]`
in webpack.config.js.
When I bundle my application, I got:

> /**/*/node_modules/webpack/lib/optimize/MinChunkSizePlugin.js:59
                                pair[2].integrate(pair[3], "min-size");
                                        ^

> TypeError: pair[2].integrate is not a function
at Compilation.compilation.plugin (/**/*/node_modules/webpack/lib/optimize/MinChunkSizePlugin.js:59:13)
at Compilation.applyPluginsBailResult1 (/**/*/node_modules/tapable/lib/Tapable.js:120:27)
at Compilation.seal (/**/*/node_modules/webpack/lib/Compilation.js:572:9)
at /**/*/node_modules/webpack/lib/Compiler.js:488:16
at /**/*/node_modules/tapable/lib/Tapable.js:225:11
at _addModuleChain (/**/*/node_modules/webpack/lib/Compilation.js:477:11)
at processModuleDependencies.err (/**/*/node_modules/webpack/lib/Compilation.js:448:13)
at _combinedTickCallback (internal/process/next_tick.js:67:7)
at process._tickCallback (internal/process/next_tick.js:98:9)

But if I remove the MinChunkSizePlugin, the bundle will be succeeded.

**other relevant information**

1. "webpack": "^2.3.0"
2. bundle cli: cross-env NODE_ENV=production webpack --display-modules --sort-modules-by size

**Comment by TheLarkInn** [comment]
Thank you for reporting, I'm going to close this as a duplicate but would it be possible to create a reproducible example in the open issue? https://github.com/webpack/webpack/issues/4532
