### ISSUE TITLE
MinChunkSizePlugin throws error

### ISSUE THREAD

**Issue by eldh** [webpack/webpack#4540]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Webpack crashes when using `MinChunkSizePlugin` with the following error:

```
pair[2].integrate(pair[3], "min-size");
                                        ^

TypeError: pair[2].integrate is not a function
    at Compilation.compilation.plugin (/Users/eldh/Code/marketplace/node_modules/webpack/lib/optimize/MinChunkSizePlugin.js:59:13)
    at Compilation.applyPluginsBailResult1 (/Users/eldh/Code/marketplace/node_modules/webpack/node_modules/tapable/lib/Tapable.js:120:27)
    at Compilation.seal (/Users/eldh/Code/marketplace/node_modules/webpack/lib/Compilation.js:572:9)
    at /Users/eldh/Code/marketplace/node_modules/webpack/lib/Compiler.js:488:16
    at /Users/eldh/Code/marketplace/node_modules/webpack/node_modules/tapable/lib/Tapable.js:225:11
    at _addModuleChain (/Users/eldh/Code/marketplace/node_modules/webpack/lib/Compilation.js:477:11)
    at processModuleDependencies.err (/Users/eldh/Code/marketplace/node_modules/webpack/lib/Compilation.js:448:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

Using the following options: `new webpack.optimize.MinChunkSizePlugin({minChunkSize: 40000}),`

**If the current behavior is a bug, please provide the steps to reproduce.**
As this seems to have been fixed in master (https://github.com/webpack/webpack/commit/915c150f3afa8a96f0d33be7c10e40fd54896faa), I'm not going to spend time on creating a repro. Still think it might be good to create this issue for other people running into this.

**What is the expected behavior?**
No crash.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
n/a

**Comment by eldh** [comment]
duplicate of https://github.com/webpack/webpack/issues/4532
