### ISSUE TITLE
Cannot export an anonymous function as `default`

### ISSUE THREAD

**Issue by shinnn** [webpack/webpack#4590]
**Do you want to request a *feature* or report a *bug*?**

A bug.

**What is the current behavior?**

Webpack cannot export an anonymous non-arrow function as `default`.

**If the current behavior is a bug, please provide the steps to reproduce.**

### Environment

```
$ node --version
7.7.4

$ npm ls webpack
webpack-test@ /Users/shinnn/github/webpack-test
└── webpack@2.3.2 
```

No `webpack.config.js` and loaders are needed.

### Step to reproduce

1. Create a JavaScript file `src.js`: `export default function() {};`
2. Run `webpack src.js bundle.js` then you can see the following error:

```
Hash: e019117daa3ee39a98e9
Version: webpack 2.3.2
Time: 74ms
    Asset     Size  Chunks             Chunk Names
bnudle.js  4.54 kB       0  [emitted]  main
   [0] ./src.js 1.8 kB {0} [built] [failed] [1 error]

ERROR in ./src.js
Module parse failed: /Users/shinnn/github/webpack-test/src.js Cannot read property 'name' of null
You may need an appropriate loader to handle this file type.
TypeError: Cannot read property 'name' of null
    at Parser.walkFunctionDeclaration (/Users/shinnn/github/webpack-test/node_modules/webpack/lib/Parser.js:539:39)
    at Parser.walkStatement (/Users/shinnn/github/webpack-test/node_modules/webpack/lib/Parser.js:436:32)
    at Parser.walkExportDefaultDeclaration (/Users/shinnn/github/webpack-test/node_modules/webpack/lib/Parser.js:613:9)
    at Parser.walkStatement (/Users/shinnn/github/webpack-test/node_modules/webpack/lib/Parser.js:436:32)
    at Parser.walkStatements (/Users/shinnn/github/webpack-test/node_modules/webpack/lib/Parser.js:419:9)
    at Parser.parse (/Users/shinnn/github/webpack-test/node_modules/webpack/lib/Parser.js:1193:8)
    at doBuild (/Users/shinnn/github/webpack-test/node_modules/webpack/lib/NormalModule.js:288:17)
    at runLoaders (/Users/shinnn/github/webpack-test/node_modules/webpack/lib/NormalModule.js:206:11)
    at /Users/shinnn/github/webpack-test/node_modules/loader-runner/lib/LoaderRunner.js:370:3
    at iterateNormalLoaders (/Users/shinnn/github/webpack-test/node_modules/loader-runner/lib/LoaderRunner.js:211:10)
    at Array.<anonymous> (/Users/shinnn/github/webpack-test/node_modules/loader-runner/lib/LoaderRunner.js:202:4)
    at Storage.finished (/Users/shinnn/github/webpack-test/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:15)
    at /Users/shinnn/github/webpack-test/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:69:9
    at /Users/shinnn/github/webpack-test/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:439:3)
```

**What is the expected behavior?**

It should create `bundle.js` which exports `function() {}` as `default`, such as:

```javascript
// ...

"use strict";
Object.defineProperty(__webpack_exports__, "__esModule", { value: true });
/* harmony default export */ __webpack_exports__["default"] = function() {};

// ...
```

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

### Other test cases

As opposed to `function() {}`, Webpack can export the following as `default`:

1. Named non-arrow function. `export default function thisFunctionHasFunctionName() {};`
2. Arrow function. `export default () => {}`

### Webpack versions

I can reproduce the error with Webpack v2.2.1 but can't with v2.2.0. I guess some regression has been introduced in [`v2.2.0...v2.2.1`](https://github.com/webpack/webpack/compare/v2.2.0...v2.2.1).

###

**Comment by Rendalf** [comment]
Seems like you have reported about this bug https://github.com/ternjs/acorn/issues/527

**Comment by shinnn** [comment]
@Rendalf Thanks for pointing to the relevant issue. Reinstalling modules fixed this problem.
