### ISSUE TITLE
Not compiling linked packages

### ISSUE THREAD

**Issue by vTripes** [webpack/webpack#4760]
### Environment

- App env: Laravel 5.4
- Node version: 7.4.0
- Npm version: 4.1.2
- Webpack version: 2.3.3
- OS: Ubtuntu 16.04 LTS

### Behavior

When adding a link to a local package to an application (`npm link <pckg>`), webpack isn't able to compile the package thus throwing this error:
```
Module build failed: Error: Couldn't find preset "env" relative to directory "/usr/share/nginx/user/noderegistries/utilsjs"
    at /usr/share/nginx/user/site/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (native)
    at OptionManager.resolvePresets (/usr/share/nginx/user/site/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/usr/share/nginx/user/site/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/usr/share/nginx/user/site/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/usr/share/nginx/user/site/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/usr/share/nginx/user/site/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/usr/share/nginx/user/site/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/usr/share/nginx/user/site/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/usr/share/nginx/user/site/node_modules/babel-loader/lib/index.js:46:20)
    at /usr/share/nginx/user/site/node_modules/babel-loader/lib/fs-cache.js:79:18
    at ReadFileContext.callback (/usr/share/nginx/user/site/node_modules/babel-loader/lib/fs-cache.js:15:14)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:336:13)
```

### Steps to reproduce

- Create a node module (`npm init`) and (optional) set it to private in `package.json` (even the single line `module.exports = {}` is enough)
- Once done, run `npm link` in the folder of this module
- In your application folder, run `npm link <pckgname>`
- Try to compile the application

**Comment by sokra** [comment]
@webpack-bot move to babel/babel-loader
