### ISSUE TITLE
Absolute path error when running 'ng test' webpack@2.4.1

### ISSUE THREAD

**Issue by Ezeon** [webpack/webpack#4832]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**

Running 'ng test' fails with the following error:

07 05 2017 02:23:04.825:ERROR [preprocess]: Can not load "webpack"!
  WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.context: The provided value "C:/dev/ndd" is not an absolute path!
    at webpack (C:\dev\ndd\node_modules\webpack\lib\webpack.js:19:9)
    at new Plugin (C:\dev\ndd\node_modules\karma-webpack\lib\karma-webpack.js:63:18)
    at invoke (C:\dev\ndd\node_modules\di\lib\injector.js:75:15)
    at Array.instantiate (C:\dev\ndd\node_modules\di\lib\injector.js:59:20)
    at get (C:\dev\ndd\node_modules\di\lib\injector.js:48:43)
    at C:\dev\ndd\node_modules\di\lib\injector.js:71:14
    at Array.map (native)
    at Array.invoke (C:\dev\ndd\node_modules\di\lib\injector.js:70:31)
    at Injector.get (C:\dev\ndd\node_modules\di\lib\injector.js:48:43)
    at instantiatePreprocessor (C:\dev\ndd\node_modules\karma\lib\preprocessor.js:55:20)
    at C:\dev\ndd\node_modules\karma\lib\preprocessor.js:106:17
    at Array.forEach (native)
    at C:\dev\ndd\node_modules\karma\lib\preprocessor.js:103:27
    at module.exports (C:\dev\ndd\node_modules\karma\node_modules\isbinaryfile\index.js:28:12)
    at C:\dev\ndd\node_modules\karma\lib\preprocessor.js:84:7
    at C:\dev\ndd\node_modules\graceful-fs\graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)
07 05 2017 02:23:04.839:WARN [karma]: No captured browser, open http://localhost:9876/
07 05 2017 02:23:04.852:INFO [karma]: Karma v1.7.0 server started at http://0.0.0.0:9876/
07 05 2017 02:23:04.853:INFO [launcher]: Launching browser Chrome with unlimited concurrency
07 05 2017 02:23:04.855:ERROR [karma]: Found 1 load error

BTW, 'ng serve' and 'ng build' is working fine. The issue is only happening with 'ng test'.

**If the current behavior is a bug, please provide the steps to reproduce.**
Windows 7
Git Bash
Node v6.9.4
NPM 4.5.0
Webpack 2.41
Angular 4.1.0
Karma 1.7.0

**What is the expected behavior?**
No validation error shoud occur.

**Comment by sokra** [comment]
The slashes are incorrect

**Comment by Ezeon** [comment]
Thanks. That seems to be the logical explanation. This path however is passed in from 'karma-webpack.js' (as seen in the trace), which is probably why this only happens with 'ng test'. I'll try to pursue this issue with Karma.
