### ISSUE TITLE
the script: 'npm run test' does not work

### ISSUE THREAD

**Issue by nicholaslee119** [webpack/webpack#4864]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
the script: 'npm run test' does not work 

**If the current behavior is a bug, please provide the steps to reproduce.**
npm run test

**What is the expected behavior?**
apply test

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

```
$ sudo npm run test

> webpack@2.5.1 pretest /Users/XXX/IdeaProjects/webpack
> npm run lint-files


> webpack@2.5.1 lint-files /Users/XXX/IdeaProjects/webpack
> npm run lint && npm run beautify-lint


> webpack@2.5.1 lint /Users/XXX/IdeaProjects/webpack
> eslint lib bin hot buildin "test/**/webpack.config.js" "test/binCases/**/test.js" "examples/**/webpack.config.js"


> webpack@2.5.1 beautify-lint /Users/XXX/IdeaProjects/webpack
> beautify-lint "lib/**/*.js" "hot/**/*.js" "bin/**/*.js" "benchmark/*.js" "test/*.js"

Fine. (317 files checked)

> webpack@2.5.1 test /Users/XXX/IdeaProjects/webpack
> mocha test/*.test.js --harmony --check-leaks

module.js:471
    throw err;
    ^

Error: Cannot find module 'webpack/lib/removeAndDo'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/xxx/IdeaProjects/webpack/node_modules/extract-text-webpack-plugin/ExtractedModule.js:30:42)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/xxx/IdeaProjects/webpack/node_modules/extract-text-webpack-plugin/index.js:8:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/xxx/IdeaProjects/webpack/test/HotTestCases.test.js:8:27)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at require (internal/module.js:20:19)
    at /Users/xxx/IdeaProjects/webpack/node_modules/mocha/lib/mocha.js:222:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/xxx/IdeaProjects/webpack/node_modules/mocha/lib/mocha.js:219:14)
    at Mocha.run (/Users/xxx/IdeaProjects/webpack/node_modules/mocha/lib/mocha.js:487:10)
    at Object.<anonymous> (/Users/xxx/IdeaProjects/webpack/node_modules/mocha/bin/_mocha:459:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webpack@2.5.1 test: `mocha test/*.test.js --harmony --check-leaks`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the webpack@2.5.1 test script 'mocha test/*.test.js --harmony --check-leaks'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the webpack package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     mocha test/*.test.js --harmony --check-leaks
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs webpack
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls webpack
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xxx/.npm/_logs/2017-05-12T04_24_02_877Z-debug.log

```

**Comment by nicholaslee119** [comment]
my node js 6.9.1 and npm is 4.6.1

**Comment by nicholaslee119** [comment]
fix it
