### ISSUE TITLE
Documentation appears to have a code error

### ISSUE THREAD

**Issue by ksnyder** [webpack/webpack#4971]
**Do you want to request a *feature* or report a *bug*?**

Bug in documentation

**What is the current behavior?**

In this doc section: https://webpack.js.org/guides/code-splitting-async/#usage-with-babel
there is a sample config file with:
```javascript
use: [{
        loader: 'babel-loader',
        options: {
          presets: [['es2015', {modules: false}]],
          plugins: ['syntax-dynamic-import']
        }
      }]
```
But using this config produces an error that 'modules' is not an option for this preset:

> webpack --config ./webpack.client-config.js

```javascript
loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
Hash: eace64f3e159c1584e0a
Version: webpack 2.6.1
Time: 519ms
    Asset     Size  Chunks             Chunk Names
bundle.js  4.21 kB       0  [emitted]  main
   [0] ./src/client/index.es6 1.58 kB {0} [built] [failed] [1 error]

ERROR in ./src/client/index.es6
Module build failed: Error: Options {"modules":false} passed to /Users/byofuel/code/tonicmart/node_modules/babel-preset-es2015/index.js which does not accept options. (While processing preset: "/Users/byofuel/code/tonicmart/node_modules/babel-preset-es2015/index.js")
    at /Users/byofuel/code/tonicmart/node_modules/babel-core/lib/transformation/file/options/option-manager.js:314:17
    at Array.map (native)
    at OptionManager.resolvePresets (/Users/byofuel/code/tonicmart/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/Users/byofuel/code/tonicmart/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/Users/byofuel/code/tonicmart/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/Users/byofuel/code/tonicmart/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/byofuel/code/tonicmart/node_modules/babel-core/lib/transformation/file/index.js:216:65)
    at new File (/Users/byofuel/code/tonicmart/node_modules/babel-core/lib/transformation/file/index.js:139:24)
    at Pipeline.transform (/Users/byofuel/code/tonicmart/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/byofuel/code/tonicmart/node_modules/babel-loader/lib/index.js:36:20)
    at Object.module.exports (/Users/byofuel/code/tonicmart/node_modules/babel-loader/lib/index.js:128:12)
```

**If the current behavior is a bug, please provide the steps to reproduce.**

See above

**What is the expected behavior?**
I would expect the docs to show working code

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Webpack 2.6.1 on Mac 10.12.5

**Comment by bebraw** [comment]
@webpack-bot move to webpack/webpack.js.org
