### ISSUE TITLE
Compiler.run gives an error

### ISSUE THREAD

**Issue by Krizzu** [webpack/webpack#5037]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**
Running `compiler.run(callback)` gives `Error: Must give hashtype string as argument`

**If the current behavior is a bug, please provide the steps to reproduce.**

Using code from [Webpack docs](https://webpack.js.org/api/plugins/compiler/) gives an error while running

**What is the expected behavior?**

Run without error

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Node: v7.10.0
Webpack: v2.6.1
OS: MacOS Sierra 10.12

**Comment by sokra** [comment]
Stack Trace?

**Comment by Krizzu** [comment]
Hey,

Sorry for uncompleted issue. More informations: 

I run `index.js` with node (v7.10.0):
```
const Compiler = require('webpack').Compiler;
const compiler = new Compiler();

compiler.options = {
  entry: './png.js',
  output: {
    path: `${__dirname}/dist`,
    filename: 'bundle.js',
  },
};

compiler.run(() => {});
```
Here's the stack trace:
```
Error: Must give hashtype string as argument
    at new Hash (crypto.js:58:18)
    at Object.Hash (crypto.js:57:12)
    at Compilation.createHash (/Users/krzysztofborowy/Documents/projects/flow_tutorial/node_modules/webpack/lib/Compilation.js:1096:23)
    at sealPart2 (/Users/krzysztofborowy/Documents/projects/flow_tutorial/node_modules/webpack/lib/Compilation.js:610:9)
    at Compilation.applyPluginsAsyncSeries (/Users/krzysztofborowy/Documents/projects/flow_tutorial/node_modules/tapable/lib/Tapable.js:131:46)
    at Compilation.seal (/Users/krzysztofborowy/Documents/projects/flow_tutorial/node_modules/webpack/lib/Compilation.js:575:8)
    at /Users/krzysztofborowy/Documents/projects/flow_tutorial/node_modules/webpack/lib/Compiler.js:488:16
    at Compiler.applyPluginsParallel (/Users/krzysztofborowy/Documents/projects/flow_tutorial/node_modules/tapable/lib/Tapable.js:214:70)
    at /Users/krzysztofborowy/Documents/projects/flow_tutorial/node_modules/webpack/lib/Compiler.js:483:8
    at Compiler.applyPluginsAsyncSeries (/Users/krzysztofborowy/Documents/projects/flow_tutorial/node_modules/tapable/lib/Tapable.js:131:46)
```

Also, runninng without `compiler.options = {...}`, produces this stack trace:

```
TypeError: Cannot read property 'hashFunction' of undefined
    at Compilation.createHash (/Users/krzysztofborowy/Documents/projects/flow_tutorial/node_modules/webpack/lib/Compilation.js:1093:37)
    at sealPart2 (/Users/krzysztofborowy/Documents/projects/flow_tutorial/node_modules/webpack/lib/Compilation.js:610:9)
    at Compilation.applyPluginsAsyncSeries (/Users/krzysztofborowy/Documents/projects/flow_tutorial/node_modules/tapable/lib/Tapable.js:131:46)
    at Compilation.seal (/Users/krzysztofborowy/Documents/projects/flow_tutorial/node_modules/webpack/lib/Compilation.js:575:8)
    at /Users/krzysztofborowy/Documents/projects/flow_tutorial/node_modules/webpack/lib/Compiler.js:488:16
    at Compiler.applyPluginsParallel (/Users/krzysztofborowy/Documents/projects/flow_tutorial/node_modules/tapable/lib/Tapable.js:214:70)
    at /Users/krzysztofborowy/Documents/projects/flow_tutorial/node_modules/webpack/lib/Compiler.js:483:8
    at Compiler.applyPluginsAsyncSeries (/Users/krzysztofborowy/Documents/projects/flow_tutorial/node_modules/tapable/lib/Tapable.js:131:46)
    at Compiler.compile (/Users/krzysztofborowy/Documents/projects/flow_tutorial/node_modules/webpack/lib/Compiler.js:476:7)
    at /Users/krzysztofborowy/Documents/projects/flow_tutorial/node_modules/webpack/lib/Compiler.js:231:10
```

**Comment by corps** [comment]
Also experiencing this.  Reproduction is easy: construct a compiler instance with no arguments, and set the options property by hand before calling run.  It seems to always fail the same way no matter the configuration.

**Comment by corps** [comment]
Additional context:  My machine is a Linux PC, so I believe this is not platform issue.

**Comment by corps** [comment]
So it looks like the problem is that the `WebpackOptionsDefaulter` is not applied to options that are handed to the compiler instance.  That may be reasonable behavior, but I believe that a warning that setting the options by hand requires you to either explicitly set all options or pass it through the options defaulter would  help against confusion around this.

As it stands, it is unexpected behavior that passing options via `webpack(opts)` is different from `var c = webpack.Compiler(); c.options = opts;`.

**Comment by corps** [comment]
@Krizzu 

workaround:

```javascript
var WebpackOptionsDefaulter = require("webpack/lib/WebpackOptionsDefaulter");

var opts = { .... };
new WebpackOptionsDefaulter().process(opts);
compiler.options = opts;
compiler.run(() => {})
```
