### ISSUE TITLE
webpack 3 is missing uglify v2.x dependency which breaks the build

### ISSUE THREAD

**Issue by jharris4** [webpack/webpack#5092]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
I'm getting the following error:
```
ERROR in bundle-main.js from UglifyJs
TypeError: Cannot read property 'reset' of undefined
    at /Users/user/project/node_modules/uglifyjs-webpack-plugin/dist/index.js:96:21
    at Array.forEach (native)
    at Compilation.<anonymous> (/Users/user/project/node_modules/uglifyjs-webpack-plugin/dist/index.js:54:20)
    at Compilation.applyPluginsAsyncSeries (/Users/user/project/node_modules/tapable/lib/Tapable.js:142:13)
    at self.applyPluginsAsync.err (/Users/user/project/node_modules/webpack/lib/Compilation.js:641:10)
    at next (/Users/user/project/node_modules/tapable/lib/Tapable.js:138:11)
    at ExtractTextPlugin.<anonymous> (/Users/user/project/node_modules/extract-text-webpack-plugin/index.js:345:4)
    at Compilation.applyPluginsAsyncSeries (/Users/user/project/node_modules/tapable/lib/Tapable.js:142:13)
    at sealPart2 (/Users/user/project/node_modules/webpack/lib/Compilation.js:637:9)
    at next (/Users/user/project/node_modules/tapable/lib/Tapable.js:138:11)
    at ExtractTextPlugin.<anonymous> (/Users/user/project/node_modules/extract-text-webpack-plugin/index.js:317:5)
    at /Users/user/project/node_modules/async/dist/async.js:421:16
    at iteratorCallback (/Users/user/project/node_modules/async/dist/async.js:998:13)
    at /Users/user/project/node_modules/async/dist/async.js:906:16
    at /Users/user/project/node_modules/extract-text-webpack-plugin/index.js:301:6
    at /Users/user/project/node_modules/async/dist/async.js:421:16
    at iteratorCallback (/Users/user/project/node_modules/async/dist/async.js:998:13)
    at /Users/user/project/node_modules/async/dist/async.js:906:16
    at /Users/user/project/node_modules/extract-text-webpack-plugin/index.js:298:13
    at /Users/user/project/node_modules/async/dist/async.js:3060:16
    at eachOfArrayLike (/Users/user/project/node_modules/async/dist/async.js:1003:9)
    at eachOf (/Users/user/project/node_modules/async/dist/async.js:1051:5)
    at Object.eachLimit (/Users/user/project/node_modules/async/dist/async.js:3122:5)
```

I'm pretty sure this is because webpack 2.6 had `"uglify-js": "^2.8.27"` as a dependency, but webpack 3.0 has only `"uglifyjs-webpack-plugin": "^0.4.4"` as a dependency (which does NOT pull in uglify-js v2!)

**If the current behavior is a bug, please provide the steps to reproduce.**

It seems to be occurring whenever I use the `-p` option from the CLI.

**What is the expected behavior?**
Errors should not occur when using minification via uglify js.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Webpack 3.0
Node 8.1.2
MacOS 10.12.5

**Comment by kingdaro** [comment]
Confirmed, installing uglify-js version 2 manually seems to fix the bug.

**Comment by sabbyjiang** [comment]
Fix by kingdaro worked for me. Installing v3 doesn't, though.

**Comment by FranciscoG** [comment]
confirmed  `npm i uglify-js@2 -D` worked for me.  Annoying that it's not in the documentation

**Comment by jharris4** [comment]
Looks like an oversight to me.

I'd file a PR to add the dependency, but I suspect the dependency should be placed under `uglifyjs-webpack-plugin`

**Comment by chicoxyzzy** [comment]
You can create PR therehttps://github.com/webpack-contrib/uglifyjs-webpack-plugin

**Comment by jharris4** [comment]
I could, if I knew where the dependency should go. Better to let the webpack core team decide.

**Comment by sokra** [comment]
@webpack-bot move to webpack-contrib/uglifyjs-webpack-plugin

uglifyjs-webpack-plugin should have uglify-js as dependency

**Comment by interglobalmedia** [comment]
Hi,

I am also still getting an error after trying out `npm i uglify-js@2 -D`:

```
ERROR in vendor.cd145239390431b90653.js from UglifyJs
DefaultsError: `sourcemap` is not a supported option
    at DefaultsError.get (eval at <anonymous> (/Users/mariacam/Development/react-timeline-app/node_modules/uglifyjs-webpack-plugin/node_modules/uglify-js/tools/node.js:27:1), <anonymous>:86:23)
    at /Users/mariacam/Development/react-timeline-app/node_modules/uglifyjs-webpack-plugin/dist/index.js:239:80
    at Array.forEach (native)
    at Compilation.<anonymous> (/Users/mariacam/Development/react-timeline-app/node_modules/uglifyjs-webpack-plugin/dist/index.js:54:20)
    at next (/Users/mariacam/Development/react-timeline-app/node_modules/tapable/lib/Tapable.js:204:14)
    at LastCallWebpackPlugin.process (/Users/mariacam/Development/react-timeline-app/node_modules/last-call-webpack-plugin/index.js:126:12)
    at Compilation.<anonymous> (/Users/mariacam/Development/react-timeline-app/node_modules/last-call-webpack-plugin/index.js:194:12)
    at Compilation.applyPluginsAsyncSeries (/Users/mariacam/Development/react-timeline-app/node_modules/tapable/lib/Tapable.js:206:13)
    at self.applyPluginsAsync.err (/Users/mariacam/Development/react-timeline-app/node_modules/webpack/lib/Compilation.js:657:10)
    at next (/Users/mariacam/Development/react-timeline-app/node_modules/tapable/lib/Tapable.js:202:11)
    at Compilation.<anonymous> (/Users/mariacam/Development/react-timeline-app/node_modules/extract-text-webpack-plugin/dist/index.js:272:11)
    at Compilation.applyPluginsAsyncSeries (/Users/mariacam/Development/react-timeline-app/node_modules/tapable/lib/Tapable.js:206:13)
    at sealPart2 (/Users/mariacam/Development/react-timeline-app/node_modules/webpack/lib/Compilation.js:653:9)
    at next (/Users/mariacam/Development/react-timeline-app/node_modules/tapable/lib/Tapable.js:202:11)
    at /Users/mariacam/Development/react-timeline-app/node_modules/extract-text-webpack-plugin/dist/index.js:241:13
    at /Users/mariacam/Development/react-timeline-app/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:421:16
    at iteratorCallback (/Users/mariacam/Development/react-timeline-app/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:998:13)
    at /Users/mariacam/Development/react-timeline-app/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:906:16
    at /Users/mariacam/Development/react-timeline-app/node_modules/extract-text-webpack-plugin/dist/index.js:224:15
    at /Users/mariacam/Development/react-timeline-app/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:421:16
    at iteratorCallback (/Users/mariacam/Development/react-timeline-app/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:998:13)
    at /Users/mariacam/Development/react-timeline-app/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:906:16
    at /Users/mariacam/Development/react-timeline-app/node_modules/extract-text-webpack-plugin/dist/index.js:213:21
    at rebuilding.forEach.cb (/Users/mariacam/Development/react-timeline-app/node_modules/webpack/lib/Compilation.js:521:29)
    at Array.forEach (native)
    at callback (/Users/mariacam/Development/react-timeline-app/node_modules/webpack/lib/Compilation.js:521:15)
    at processModuleDependencies (/Users/mariacam/Development/react-timeline-app/node_modules/webpack/lib/Compilation.js:540:5)
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickCallback (internal/process/next_tick.js:161:9)

ERROR in bundle.be92fc799b3579e9fc7e.js from UglifyJs
DefaultsError: `sourcemap` is not a supported option
    at DefaultsError.get (eval at <anonymous> (/Users/mariacam/Development/react-timeline-app/node_modules/uglifyjs-webpack-plugin/node_modules/uglify-js/tools/node.js:27:1), <anonymous>:86:23)
    at /Users/mariacam/Development/react-timeline-app/node_modules/uglifyjs-webpack-plugin/dist/index.js:239:80
    at Array.forEach (native)
    at Compilation.<anonymous> (/Users/mariacam/Development/react-timeline-app/node_modules/uglifyjs-webpack-plugin/dist/index.js:54:20)
    at next (/Users/mariacam/Development/react-timeline-app/node_modules/tapable/lib/Tapable.js:204:14)
    at LastCallWebpackPlugin.process (/Users/mariacam/Development/react-timeline-app/node_modules/last-call-webpack-plugin/index.js:126:12)
    at Compilation.<anonymous> (/Users/mariacam/Development/react-timeline-app/node_modules/last-call-webpack-plugin/index.js:194:12)
    at Compilation.applyPluginsAsyncSeries (/Users/mariacam/Development/react-timeline-app/node_modules/tapable/lib/Tapable.js:206:13)
    at self.applyPluginsAsync.err (/Users/mariacam/Development/react-timeline-app/node_modules/webpack/lib/Compilation.js:657:10)
    at next (/Users/mariacam/Development/react-timeline-app/node_modules/tapable/lib/Tapable.js:202:11)
    at Compilation.<anonymous> (/Users/mariacam/Development/react-timeline-app/node_modules/extract-text-webpack-plugin/dist/index.js:272:11)
    at Compilation.applyPluginsAsyncSeries (/Users/mariacam/Development/react-timeline-app/node_modules/tapable/lib/Tapable.js:206:13)
    at sealPart2 (/Users/mariacam/Development/react-timeline-app/node_modules/webpack/lib/Compilation.js:653:9)
    at next (/Users/mariacam/Development/react-timeline-app/node_modules/tapable/lib/Tapable.js:202:11)
    at /Users/mariacam/Development/react-timeline-app/node_modules/extract-text-webpack-plugin/dist/index.js:241:13
    at /Users/mariacam/Development/react-timeline-app/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:421:16
    at iteratorCallback (/Users/mariacam/Development/react-timeline-app/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:998:13)
    at /Users/mariacam/Development/react-timeline-app/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:906:16
    at /Users/mariacam/Development/react-timeline-app/node_modules/extract-text-webpack-plugin/dist/index.js:224:15
    at /Users/mariacam/Development/react-timeline-app/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:421:16
    at iteratorCallback (/Users/mariacam/Development/react-timeline-app/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:998:13)
    at /Users/mariacam/Development/react-timeline-app/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:906:16
    at /Users/mariacam/Development/react-timeline-app/node_modules/extract-text-webpack-plugin/dist/index.js:213:21
    at rebuilding.forEach.cb (/Users/mariacam/Development/react-timeline-app/node_modules/webpack/lib/Compilation.js:521:29)
    at Array.forEach (native)
    at callback (/Users/mariacam/Development/react-timeline-app/node_modules/webpack/lib/Compilation.js:521:15)
    at processModuleDependencies (/Users/mariacam/Development/react-timeline-app/node_modules/webpack/lib/Compilation.js:540:5)
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickCallback (internal/process/next_tick.js:161:9)

ERROR in manifest.8c6c4bc37562079e998e.js from UglifyJs
DefaultsError: `sourcemap` is not a supported option
    at DefaultsError.get (eval at <anonymous> (/Users/mariacam/Development/react-timeline-app/node_modules/uglifyjs-webpack-plugin/node_modules/uglify-js/tools/node.js:27:1), <anonymous>:86:23)
    at /Users/mariacam/Development/react-timeline-app/node_modules/uglifyjs-webpack-plugin/dist/index.js:239:80
    at Array.forEach (native)
    at Compilation.<anonymous> (/Users/mariacam/Development/react-timeline-app/node_modules/uglifyjs-webpack-plugin/dist/index.js:54:20)
    at next (/Users/mariacam/Development/react-timeline-app/node_modules/tapable/lib/Tapable.js:204:14)
    at LastCallWebpackPlugin.process (/Users/mariacam/Development/react-timeline-app/node_modules/last-call-webpack-plugin/index.js:126:12)
    at Compilation.<anonymous> (/Users/mariacam/Development/react-timeline-app/node_modules/last-call-webpack-plugin/index.js:194:12)
    at Compilation.applyPluginsAsyncSeries (/Users/mariacam/Development/react-timeline-app/node_modules/tapable/lib/Tapable.js:206:13)
    at self.applyPluginsAsync.err (/Users/mariacam/Development/react-timeline-app/node_modules/webpack/lib/Compilation.js:657:10)
    at next (/Users/mariacam/Development/react-timeline-app/node_modules/tapable/lib/Tapable.js:202:11)
    at Compilation.<anonymous> (/Users/mariacam/Development/react-timeline-app/node_modules/extract-text-webpack-plugin/dist/index.js:272:11)
    at Compilation.applyPluginsAsyncSeries (/Users/mariacam/Development/react-timeline-app/node_modules/tapable/lib/Tapable.js:206:13)
    at sealPart2 (/Users/mariacam/Development/react-timeline-app/node_modules/webpack/lib/Compilation.js:653:9)
    at next (/Users/mariacam/Development/react-timeline-app/node_modules/tapable/lib/Tapable.js:202:11)
    at /Users/mariacam/Development/react-timeline-app/node_modules/extract-text-webpack-plugin/dist/index.js:241:13
    at /Users/mariacam/Development/react-timeline-app/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:421:16
    at iteratorCallback (/Users/mariacam/Development/react-timeline-app/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:998:13)
    at /Users/mariacam/Development/react-timeline-app/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:906:16
    at /Users/mariacam/Development/react-timeline-app/node_modules/extract-text-webpack-plugin/dist/index.js:224:15
    at /Users/mariacam/Development/react-timeline-app/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:421:16
    at iteratorCallback (/Users/mariacam/Development/react-timeline-app/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:998:13)
    at /Users/mariacam/Development/react-timeline-app/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:906:16
    at /Users/mariacam/Development/react-timeline-app/node_modules/extract-text-webpack-plugin/dist/index.js:213:21
    at rebuilding.forEach.cb (/Users/mariacam/Development/react-timeline-app/node_modules/webpack/lib/Compilation.js:521:29)
    at Array.forEach (native)
    at callback (/Users/mariacam/Development/react-timeline-app/node_modules/webpack/lib/Compilation.js:521:15)
    at processModuleDependencies (/Users/mariacam/Development/react-timeline-app/node_modules/webpack/lib/Compilation.js:540:5)
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickCallback (internal/process/next_tick.js:161:9)
```
And this is what I did in webpack.config.js:

```
new webpack.optimize.UglifyJsPlugin({
			compress: {
				warnings: true
			}
		})
```
