### ISSUE TITLE
resolve.root is not valid with webpack 3

### ISSUE THREAD

**Issue by rhan-mentad** [webpack/webpack#5201]
I'm reporting a bug. Webpack 3 trying to migrate an existing webpack 2 project over. It's complaining resolve.root is not a valid option to be put into webpack. The documentation for webpack says it's still valid. https://webpack.github.io/docs/configuration.html#resolve-root

node v6, webpack 3.0

```
WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.resolve has an unknown property 'root'. These properties are valid:
   object { alias?, aliasFields?, cachePredicate?, descriptionFiles?, enforceExtension?, enforceModuleExtension?, extensions?, fileSystem?, mainFields?, mainFiles?, moduleExtensions?, modules?, plugins?, resolver?, symlinks?, unsafeCache?, useSyncFileSystemCalls? }
 - configuration.resolve.extensions[0] should not be empty.
    at webpack (/home/limith/valuelink-course/node_modules/webpack/lib/webpack.js:19:9)
    at startServer (/home/limith/valuelink-course/index.js:57:24)
    at nextTask (/home/limith/valuelink-course/node_modules/async/dist/async.js:5297:14)
    at next (/home/limith/valuelink-course/node_modules/async/dist/async.js:5304:9)
    at /home/limith/valuelink-course/node_modules/async/dist/async.js:906:16
    at Server.<anonymous> (/home/limith/valuelink-course/index.js:82:5)
    at Server.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Server.emit (events.js:185:7)
    at emitListeningNT (net.js:1284:10)

```

**Comment by rhan-mentad** [comment]
Nvm I see I was referring to the old webpack documentation by accident.
