### ISSUE TITLE
Some examples failing when running `yarn run build:examples`

### ISSUE THREAD

**Issue by ismail-syed** [webpack/webpack#5332]
**Do you want to request a *feature* or report a *bug*?**
Bug, not in the webpack library though. 
 
**What is the current behavior?**
 Exploring the webpack code base to hopefully learn more about how webpack works and contribute back.

- Cloned webpack 
- ran `yarn install`
- ran `yarn run build:examples`

Then I got a number of broken examples with something like

<img width="1063" alt="screen shot 2017-07-20 at 7 43 13 pm" src="https://user-images.githubusercontent.com/6130700/28443819-9d636ab2-6d86-11e7-9849-7660d391c609.png">

Deleted the `examples/chunkhash` directory and re-ran `yarn run build:examples`
Came across the same error for a different failing example. 
Did this until the `build:examples` script would pass. 

All the following examples had issues and had to be deleted for `yarn run build:examples` to run smoothly. 
```
- chunkhash
- code-splitting
- harmony-unused
- i18nv
- scope-hoisting
- web-worker
```

**What is the expected behavior?**
`yarn run build:examples` should run smooth without any issues?

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Node: `v6.11.1`
webpack: latest on master: `4c6eb6f3`
OS: OSX 10.12.5

**Comment by awesomenaz** [comment]
@ismail-syed Hi there. Just a question, when you do run the script yarn run build:examples, what are you trying to achieve or make webpack do?

**Comment by brandondoran** [comment]
I wanted to build the examples too and running into the same problems as above. The reason I wanted to build the examples is because some things in my own build are working differently in v3 vs v2 and I wanted to see if the same thing happens with the examples.

```
brandon:webpack/ (master✗) $ yarn build:examples                                                            
yarn build:examples v0.23.3
$ cd examples && node buildAll.js
cd aggressive-merging && node build.js
cd chunkhash && node build.js
{ Error: Command failed: cd chunkhash && node build.js
/Users/brandon/projects/webpack/examples/build-common.js:22
		throw e;
		^

Error: ENOENT: no such file or directory, open '/Users/brandon/projects/webpack/examples/chunkhash/js/manifest.chunkhash.js'
    at Object.fs.openSync (fs.js:651:18)
    at Object.fs.readFileSync (fs.js:553:33)
    at /Users/brandon/projects/webpack/examples/template-common.js:53:13
    at String.replace (<anonymous>)
    at Object.replaceResults (/Users/brandon/projects/webpack/examples/template-common.js:49:18)
    at /Users/brandon/projects/webpack/examples/build-common.js:19:19
    at ChildProcess.exithandler (child_process.js:277:5)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:897:16)

    at ChildProcess.exithandler (child_process.js:270:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:897:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'cd chunkhash && node build.js' }
✨  Done in 1.31s.
```

Out of curiosity I decided to try an run the test suite locally but that is failing too with similar errors:
```
brandon:webpack/ (master✗) $ yarn test                                                                                                                                 yarn test v0.23.3
$ npm run lint-files

> webpack@3.3.0 lint-files /Users/brandon/projects/webpack
> npm run lint && npm run beautify-lint


> webpack@3.3.0 lint /Users/brandon/projects/webpack
> eslint lib bin hot buildin "test/**/webpack.config.js" "test/binCases/**/test.js" "examples/**/webpack.config.js"


> webpack@3.3.0 beautify-lint /Users/brandon/projects/webpack
> beautify-lint "lib/**/*.js" "hot/**/*.js" "bin/**/*.js" "benchmark/*.js" "test/*.js"

Fine. (326 files checked)
$ mocha test/*.test.js --max-old-space-size=4096 --harmony --check-leaks
module.js:487
    throw err;
    ^

Error: Cannot find module 'webpack/lib/Chunk'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/brandon/projects/webpack/node_modules/extract-text-webpack-plugin/dist/index.js:17:14)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/brandon/projects/webpack/node_modules/extract-text-webpack-plugin/dist/cjs.js:3:18)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/brandon/projects/webpack/test/HotTestCases.test.js:8:27)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at /Users/brandon/projects/webpack/node_modules/mocha/lib/mocha.js:230:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/brandon/projects/webpack/node_modules/mocha/lib/mocha.js:227:14)
    at Mocha.run (/Users/brandon/projects/webpack/node_modules/mocha/lib/mocha.js:495:10)
    at Object.<anonymous> (/Users/brandon/projects/webpack/node_modules/mocha/bin/_mocha:469:18)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
error Command failed with exit code 1.
```
What am I doing wrong?

**Comment by sokra** [comment]
Did you read the CONTRIBUTING.md file?

**Comment by ismail-syed** [comment]
Ah, thanks @sokra. 

Forgot to run 
```
$ yarn link && yarn link webpack
```
