### ISSUE TITLE
webpack.DllPlugin  error

### ISSUE THREAD

**Issue by fukai007** [webpack/webpack#5336]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
I  want to make dll   but  is failed 
**If the current behavior is a bug, please provide the steps to reproduce.**
this  is my DIR
![image](https://user-images.githubusercontent.com/19289374/28458998-50e0a566-6e3e-11e7-960f-e0e6a2c1d3b1.png)

this is my webapack.config.js
```
var path = require("path");
var webpack = require("webpack");
console.log('__dirname---------------------->', __dirname);
module.exports = {
  context: __dirname,
	resolve: {
		extensions: [".js", ".jsx"]
	},
	entry: {
		a:["./a/aa","./a/ab"],
		b:["./b/ba","./b/bb"],
	},
	output: {
		path: path.join(__dirname, "js"),
		filename: "MyDll.[name].js",
		library: "[name]_[hash]"
	},
	plugins: [
		new webpack.DllPlugin({
			path: path.join(__dirname, "js", "[name]-manifest.json"),
			name: "[name]_[hash]"
		})
	]
};
```
this is error
```
miles-fk:dll fukai$ webpack
__dirname----------------------> /Users/fukai/testWebpack/wp/dll
/Users/fukai/testWebpack/wp/node_modules/webpack/lib/DllModuleFactory.js:15
                const dependency = data.dependencies[0];
                                                    ^

TypeError: Cannot read property '0' of undefined
    at DllModuleFactory.create (/Users/fukai/testWebpack/wp/node_modules/webpack/lib/DllModuleFactory.js:15:39)

    at Compilation.process [as _addModuleChain] (/usr/local/lib/node_modules/webpack/lib/Compilation.js:356:16)
    at Compilation.process [as addEntry] (/usr/local/lib/node_modules/webpack/lib/Compilation.js:424:7)
    at Compiler.compiler.plugin (/Users/fukai/testWebpack/wp/node_modules/webpack/lib/DllEntryPlugin.js:28:16)
    at Compiler.applyPluginsParallel (/usr/local/lib/node_modules/webpack/node_modules/tapable/lib/Tapable.js:107:14)
    at Compiler.compile (/usr/local/lib/node_modules/webpack/lib/Compiler.js:394:7)
    at Compiler.<anonymous> (/usr/local/lib/node_modules/webpack/lib/Compiler.js:173:9)
    at Compiler.readRecords (/usr/local/lib/node_modules/webpack/lib/Compiler.js:302:10)
    at Compiler.<anonymous> (/usr/local/lib/node_modules/webpack/lib/Compiler.js:170:8)
    at Compiler.next (/usr/local/lib/node_modules/webpack/node_modules/tapable/lib/Tapable.js:67:11)
    at Compiler.<anonymous> (/usr/local/lib/node_modules/webpack/lib/node/NodeEnvironmentPlugin.js:23:3)
    at Compiler.next (/usr/local/lib/node_modules/webpack/node_modules/tapable/lib/Tapable.js:69:14)
    at Compiler.<anonymous> (/usr/local/lib/node_modules/webpack/lib/CachePlugin.js:22:58)
    at Compiler.applyPluginsAsync (/usr/local/lib/node_modules/webpack/node_modules/tapable/lib/Tapable.js:71:13)
    at Compiler.run (/usr/local/lib/node_modules/webpack/lib/Compiler.js:167:7)
    at processOptions (/usr/local/lib/node_modules/webpack/bin/webpack.js:188:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/webpack/bin/webpack.js:192:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:422:7)
    at startup (bootstrap_node.js:143:9)
    at bootstrap_node.js:537:3
```

**What is the expected behavior?**
make a   dll and manifest.json
**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
webpack  2.5^
nodeJS : 7.6

**Comment by sokra** [comment]
You mixed up two different versions of webpack:

```
/Users/fukai/testWebpack/wp/node_modules/webpack
/usr/local/lib/node_modules/webpack
```

**Comment by fukai007** [comment]
thank you

**Comment by imakan** [comment]
how do you resolved? please help me
