### ISSUE TITLE
WebPack fails to bundle libraryTarget: 'amd'

### ISSUE THREAD

**Issue by vladikoff** [webpack/webpack#5342]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

with `libraryTarget: 'amd'` webpack fails with:

```
crypto.js:70
  this._handle.update(data, encoding);
               ^

TypeError: Not a string or buffer
    at TypeError (native)
    at Hash.update (crypto.js:70:16)
    at MainTemplate.<anonymous> (/Users/vladikoff/dev/bug-webpack-FR783/node_modules/webpack/lib/AmdMainTemplatePlugin.js:51:9)
    at MainTemplate.applyPlugins (/Users/vladikoff/dev/bug-webpack-FR783/node_modules/webpack/node_modules/tapable/lib/Tapable.js:61:14)
    at MainTemplate.updateHash (/Users/vladikoff/dev/bug-webpack-FR783/node_modules/webpack/lib/MainTemplate.js:219:8)
    at Compilation.createHash (/Users/vladikoff/dev/bug-webpack-FR783/node_modules/webpack/lib/Compilation.js:1168:21)
    at sealPart2 (/Users/vladikoff/dev/bug-webpack-FR783/node_modules/webpack/lib/Compilation.js:619:9)
    at Compilation.applyPluginsAsyncSeries (/Users/vladikoff/dev/bug-webpack-FR783/node_modules/webpack/node_modules/tapable/lib/Tapable.js:177:46)
    at Compilation.seal (/Users/vladikoff/dev/bug-webpack-FR783/node_modules/webpack/lib/Compilation.js:579:8)
    at /Users/vladikoff/dev/bug-webpack-FR783/node_modules/webpack/lib/Compiler.js:514:17
    at /Users/vladikoff/dev/bug-webpack-FR783/node_modules/webpack/node_modules/tapable/lib/Tapable.js:271:11
    at /Users/vladikoff/dev/bug-webpack-FR783/node_modules/webpack/lib/Compilation.js:481:11
    at /Users/vladikoff/dev/bug-webpack-FR783/node_modules/webpack/lib/Compilation.js:452:13
    at nextTickCallbackWith0Args (node.js:489:9)
    at process._tickCallback (node.js:418:13)
```

**If the current behavior is a bug, please provide the steps to reproduce.**

```
git clone git@github.com:vladikoff/bug-webpack-fr783.git
cd bug-webpack-fr783
```

```
➜  bug-webpack-FR783 git:(master) ✗ node_modules/.bin/webpack --config webpack.config.amd.js
crypto.js:70
  this._handle.update(data, encoding);
               ^

TypeError: Not a string or buffer
    at TypeError (native)
    at Hash.update (crypto.js:70:16)
    at MainTemplate.<anonymous> (/Users/vladikoff/dev/bug-webpack-FR783/node_modules/webpack/lib/AmdMainTemplatePlugin.js:51:9)
    at MainTemplate.applyPlugins (/Users/vladikoff/dev/bug-webpack-FR783/node_modules/webpack/node_modules/tapable/lib/Tapable.js:61:14)
    at MainTemplate.updateHash (/Users/vladikoff/dev/bug-webpack-FR783/node_modules/webpack/lib/MainTemplate.js:219:8)
    at Compilation.createHash (/Users/vladikoff/dev/bug-webpack-FR783/node_modules/webpack/lib/Compilation.js:1169:21)
    at sealPart2 (/Users/vladikoff/dev/bug-webpack-FR783/node_modules/webpack/lib/Compilation.js:620:9)
    at Compilation.applyPluginsAsyncSeries (/Users/vladikoff/dev/bug-webpack-FR783/node_modules/webpack/node_modules/tapable/lib/Tapable.js:177:46)
    at Compilation.seal (/Users/vladikoff/dev/bug-webpack-FR783/node_modules/webpack/lib/Compilation.js:580:8)
    at /Users/vladikoff/dev/bug-webpack-FR783/node_modules/webpack/lib/Compiler.js:510:16
    at /Users/vladikoff/dev/bug-webpack-FR783/node_modules/webpack/node_modules/tapable/lib/Tapable.js:271:11
    at /Users/vladikoff/dev/bug-webpack-FR783/node_modules/webpack/lib/Compilation.js:482:11
    at /Users/vladikoff/dev/bug-webpack-FR783/node_modules/webpack/lib/Compilation.js:453:13
    at nextTickCallbackWith0Args (node.js:489:9)
    at process._tickCallback (node.js:418:13)
```

**What is the expected behavior?**

```
➜  bug-webpack-FR783 git:(master) ✗ node_modules/.bin/webpack --config webpack.config.umd.js
Hash: 485bff494b2eb9fe637f
Version: webpack 3.0.0-rc.2
Time: 1111ms
    Asset     Size  Chunks                    Chunk Names
bundle.js  1.68 MB       0  [emitted]  [big]  thing
   [4] (webpack)/buildin/global.js 509 bytes {0} [built]
  [61] (webpack)/buildin/module.js 517 bytes {0} [built]
  [85] ./src/index.js 56 bytes {0} [built]
    + 151 hidden modules

```

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

```
➜  bug-webpack-FR783 git:(master) ✗ node --version
v4.8.3
➜  bug-webpack-FR783 git:(master) ✗ npm --version
2.15.11
```

Does the same in Node 6 and 8

**Comment by vladikoff** [comment]
Node 8 stack:

```
➜  bug-webpack-FR783 git:(master) ✗ nvm use 8
Now using node v8.0.0-rc.0 (npm v4.5.0)
➜  bug-webpack-FR783 git:(master) ✗ node_modules/.bin/webpack --config webpack.config.amd.js
crypto.js:97
  this._handle.update(data, encoding);
               ^

TypeError: Data must be a string or a buffer
    at Hash.update (crypto.js:97:16)
    at MainTemplate.mainTemplate.plugin (/Users/vladikoff/dev/bug-webpack-FR783/node_modules/webpack/lib/AmdMainTemplatePlugin.js:51:9)
    at MainTemplate.applyPlugins (/Users/vladikoff/dev/bug-webpack-FR783/node_modules/webpack/node_modules/tapable/lib/Tapable.js:61:14)
    at MainTemplate.updateHash (/Users/vladikoff/dev/bug-webpack-FR783/node_modules/webpack/lib/MainTemplate.js:219:8)
    at Compilation.createHash (/Users/vladikoff/dev/bug-webpack-FR783/node_modules/webpack/lib/Compilation.js:1169:21)
    at sealPart2 (/Users/vladikoff/dev/bug-webpack-FR783/node_modules/webpack/lib/Compilation.js:620:9)
    at Compilation.applyPluginsAsyncSeries (/Users/vladikoff/dev/bug-webpack-FR783/node_modules/webpack/node_modules/tapable/lib/Tapable.js:177:46)
    at Compilation.seal (/Users/vladikoff/dev/bug-webpack-FR783/node_modules/webpack/lib/Compilation.js:580:8)
    at /Users/vladikoff/dev/bug-webpack-FR783/node_modules/webpack/lib/Compiler.js:510:16
    at /Users/vladikoff/dev/bug-webpack-FR783/node_modules/webpack/node_modules/tapable/lib/Tapable.js:271:11
    at _addModuleChain (/Users/vladikoff/dev/bug-webpack-FR783/node_modules/webpack/lib/Compilation.js:482:11)
    at processModuleDependencies.err (/Users/vladikoff/dev/bug-webpack-FR783/node_modules/webpack/lib/Compilation.js:453:13)
    at _combinedTickCallback (internal/process/next_tick.js:74:7)
    at process._tickCallback (internal/process/next_tick.js:105:9)
```

**Comment by sokra** [comment]
This is a bug.

This line need to be changed:

https://github.com/webpack/webpack/blob/master/lib/AmdMainTemplatePlugin.js#L51

``` diff
 		mainTemplate.plugin("hash", (hash) => {
 			hash.update("exports amd");
-			hash.update(this.name);
+			if(this.name) hash.update(this.name);
 		});
```

Do you want to send a PR?

**Comment by vladikoff** [comment]
Sure, give me a few

**Comment by vladikoff** [comment]
@sokra Hm the suggested fix is not good. 

I think the cause of the problem is using an array here: https://github.com/vladikoff/bug-webpack-fr783/blob/master/webpack.config.amd.js#L10 . The `output.library` property.

In my case I use `      library: ['MyCoolLibrary', '[name]'],` where name gets generated from multiple `entries`
