### ISSUE TITLE
Unable to clone and run tests

### ISSUE THREAD

**Issue by esbenp** [webpack/webpack#5343]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

I am trying to clone the webpack repo, install dependencies and run the tests.

**If the current behavior is a bug, please provide the steps to reproduce.**

```
git clone https://github.com/webpack/webpack && cd webpack && npm install && npm run test
```

I get this message

```
> mocha test/*.test.js --max-old-space-size=4096 --harmony --check-leaks

module.js:471
    throw err;
    ^

Error: Cannot find module 'webpack/lib/Chunk'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/esben/code/webpack/node_modules/extract-text-webpack-plugin/index.js:9:13)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/esben/code/webpack/test/HotTestCases.test.js:8:27)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at require (internal/module.js:20:19)
    at /Users/esben/code/webpack/node_modules/mocha/lib/mocha.js:230:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/esben/code/webpack/node_modules/mocha/lib/mocha.js:227:14)
    at Mocha.run (/Users/esben/code/webpack/node_modules/mocha/lib/mocha.js:495:10)
    at Object.<anonymous> (/Users/esben/code/webpack/node_modules/mocha/bin/_mocha:469:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

I tried upgrading `extract-text-webpack-plugin` to the new `3.0.0` version but I did not help.

**What is the expected behavior?**

I am assuming all tests should pass :-)

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

npm: 5.2.0
node: 6.9.1
osx: 10.12.5

I am unsure if I am missing a step to get the tests to run correctly. I was unable to find a "How to clone and get tests to run"-guide :-) Apologies if I am missing some obvious build-step here.

**Comment by esbenp** [comment]
Turns out there was a "get the tests to run"-guide right here https://github.com/webpack/webpack/blob/master/test/README.md :-)
