### ISSUE TITLE
help-output test fails on OSX

### ISSUE THREAD

**Issue by esbenp** [webpack/webpack#5345]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

`$(npm bin)/mocha --grep help-output` fails

```
AssertionError: expected Array [
  'webpack 3.3.0',
  'Usage: https://webpack.js.org/api/cli/',
  'Usage without config file: webpack <entry> [<entry>] <output>',
  'Usage with config file: webpack',
  '',
  'Config options:',
  '  --config       Path to the config file',
  '                         [string] [default: webpack.config.js or webpackfile.js]',
  '  --config-name  Name of the config to use                              [string]',
  '  --env          Environment passed to the config, when it is a function',
  '',
  'Basic options:',
  '  --context    The root directory for resolving entry point and stats',
  '                                       [string] [default: The current directory]',
  '  --entry      The entry point                                          [string]',
  '  --watch, -w  Watch the filesystem for changes                        [boolean]',
  '  --debug      Switch loaders to debug mode                            [boolean]',
  '  --devtool    Enable devtool for better debugging experience (Example:',
  '               --devtool eval-cheap-module-source-map)                  [string]',
  '  -d           shortcut for --debug --devtool eval-cheap-module-source-map',
  '               --output-pathinfo                                       [boolean]',
  '  -p           shortcut for --optimize-minimize --define',
  '               process.env.NODE_ENV="production"                       [boolean]',
  '  --progress   Print compilation progress in percentage                [boolean]',
  '',
  'Module options:',
  '  --module-bind       Bind an extension to a loader                     [string]',
  '  --module-bind-post                                                    [string]',
  '  --module-bind-pre                                                     [string]',
  '',
  'Output options:',
  '  --output-path                 The output path for compilation assets',
  '                                       [string] [default: The current directory]',
  '  --output-filename             The output filename of the bundle',
  '                                                   [string] [default: [name].js]',
  '  --output-chunk-filename       The output filename for additional chunks',
  '       [string] [default: filename with [id] instead of [name] or [id] prefixed]',
  '  --output-source-map-filename  The output filename for the SourceMap   [string]',
  '  --output-public-path          The public path for the assets          [string]',
  '  --output-jsonp-function       The name of the jsonp function used for chunk',
  '                                loading                                 [string]',
  '  --output-pathinfo             Include a comment with the request for every',
  '                                dependency (require, import, etc.)     [boolean]',
  '  --output-library              Expose the exports of the entry point as library',
  '                                                                        [string]',
  '  --output-library-target       The type for exposing the exports of the entry',
  '                                point as library                        [string]',
  '',
  'Advanced options:',
  '  --records-input-path       Path to the records file (reading)         [string]',
  '  --records-output-path      Path to the records file (writing)         [string]',
  '  --records-path             Path to the records file                   [string]',
  '  --define                   Define any free var in the bundle          [string]',
  '  --target                   The targeted execution environment         [string]',
  '  --cache                    Enable in memory caching',
  '                      [boolean] [default: It\'s enabled by default when watching]',
  '  --watch-stdin, --stdin     Exit the process when stdin is closed     [boolean]',
  '  --watch-aggregate-timeout  Timeout for gathering changes while watching',
  '  --watch-poll               The polling interval for watching (also enable',
  '                             polling)                                  [boolean]',
  '  --hot                      Enables Hot Module Replacement            [boolean]',
  '  --prefetch                 Prefetch this request (Example: --prefetch',
  '                             ./file.js)                                 [string]',
  '  --provide                  Provide these modules as free vars in all modules',
  '                             (Example: --provide jQuery=jquery)         [string]',
  '  --labeled-modules          Enables labeled modules                   [boolean]',
  '  --plugin                   Load this plugin                           [string]',
  '  --bail                     Abort the compilation on first error      [boolean]',
  '  --profile                  Profile the compilation and include information in',
  '                             stats                                     [boolean]',
  '',
  'Resolving options:',
  '  --resolve-alias         Setup a module alias for resolving (Example:',
  '                          jquery-plugin=jquery.plugin)                  [string]',
  '  --resolve-extensions    Setup extensions that should be used to resolve',
  '                          modules (Example: --resolve-extensions .es6 .js)',
  '                                                                         [array]',
  '  --resolve-loader-alias  Setup a loader alias for resolving            [string]',
  '',
  'Optimizing options:',
  '  --optimize-max-chunks      Try to keep the chunk count below a limit',
  '  --optimize-min-chunk-size  Try to keep the chunk size above a limit',
  '  --optimize-minimize        Minimize javascript and switches loaders to',
  '                             minimizing                                [boolean]',
  '',
  'Stats options:',
  '  --color, --colors               Enables/Disables colors on the console',
  '                                           [boolean] [default: (supports-color)]',
  '  --sort-modules-by               Sorts the modules list by property in module',
  '                                                                        [string]',
  '  --sort-chunks-by                Sorts the chunks list by property in chunk',
  '                                                                        [string]',
  '  --sort-assets-by                Sorts the assets list by property in asset',
  '                                                                        [string]',
  '  --hide-modules                  Hides info about modules             [boolean]',
  '  --display-exclude               Exclude modules in the output         [string]',
  '  --display-modules               Display even excluded modules in the output',
  '                                                                       [boolean]',
  '  --display-max-modules           Sets the maximum number of visible modules in',
  '                                  output                                [number]',
  '  --display-chunks                Display chunks in the output         [boolean]',
  '  --display-entrypoints           Display entry points in the output   [boolean]',
  '  --display-origins               Display origins of chunks in the output',
  '                                                                       [boolean]',
  '  --display-cached                Display also cached modules in the output',
  '                                                                       [boolean]',
  '  --display-cached-assets         Display also cached assets in the output',
  '                                                                       [boolean]',
  '  --display-reasons               Display reasons about module inclusion in the',
  '                                  output                               [boolean]',
  '  --display-depth                 Display distance from entry point for each',
  '                                  module                               [boolean]',
  '  --display-used-exports          Display information about used exports in',
  '                                  modules (Tree Shaking)               [boolean]',
  '  --display-provided-exports      Display information about exports provided',
  '                                  from modules                         [boolean]',
  '  --display-optimization-bailout  Display information about why optimization',
  '                                  bailed out for modules               [boolean]',
  '  --display-error-details         Display details about errors         [boolean]',
  '  --display                       Select display preset (verbose, detailed,',
  '                                  normal, minimal, errors-only, none)   [string]',
  '  --verbose               '
] to contain 'Options:'
```

It was introduced in #5331 . The tests will pass if this entry https://github.com/webpack/webpack/pull/5331/files#diff-86ffe53e663ae3f143b8e2219c8ded35R23 is removed. I am guessing that since it only happens on my machine (the CI tests seems to pass) it is somehow due to some OSX/Node configuration (is there a limit to the length of stdout?).

**If the current behavior is a bug, please provide the steps to reproduce.**

`$(npm bin)/mocha --grep help-output`

**What is the expected behavior?**

Test should pass

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

npm: 5.2.0
node: 6.9.1
OSX: 10.12.5

**Comment by sokra** [comment]
Maybe an timeout between process close and assertions helps here: https://github.com/webpack/webpack/blob/master/test/BinTestCases.test.js#L115

**Comment by esbenp** [comment]
I tried something like this

```
child.on("close", function(code) {
	env.code = code;
	setTimeout(() => {
		done();
	}, 10000)
});
```

It did not work. I think it is related to https://github.com/nodejs/node/issues/12921 since `console.log(stdout.join(' ').length)` will return exactly 8192.

**Comment by sokra** [comment]
from https://github.com/nodejs/node/wiki/API-changes-between-v0.10-and-v4#process

![image](https://user-images.githubusercontent.com/1365881/28530408-00eff144-7094-11e7-89e0-7d917022888a.png)

yargs does call:

``` js
console.log(usage);
process.exit(0);
```

This is not recommended since node 4, because writing is chunked and stdout is not flushed on process exit.

I think this can be disabled with `.exitProcess(false)` in the yargs API. We can do a normal exit (no process.exit, but doing no further stuff to let the process exit itself after all I/O is done).

Do you want to do a PR to change this. Actually the OSX CI tests are also broken with this problem, so tests are already written ;).

**Comment by esbenp** [comment]
I am checking it out :-) thanks for pointers.

**Comment by esbenp** [comment]
What do you think about something like https://github.com/esbenp/webpack/commit/0c5725423d1190f983a2544d0e80e9ec8d2e86ec ?

Using `exitProcess(false)` works, however webpack CLI will try to parse inputs afterwards which causes validation errors (no config file or no output file given) in `convert-argv` and `ProcessOptions`. Also, we cannot just exit the process manually on `{exitByHelpOrVersion:true}` since that will also cause the output to be cut short.

The one issue I have with this solution is that `.exitProcess(false);` also causes `yargs` to keep running on failed validation. This causes yargs validation errors to include stack trace like so

```
Options:
  --help, -h     Show help                                             [boolean]
  --version, -v  Show version number                                   [boolean]
  --json, -j     Prints the result as JSON.                            [boolean]

Missing argument value: config-name

/Users/esben/code/webpack-esben/node_modules/yargs/lib/usage.js:60
        throw err
        ^
YError: Missing argument value: config-name
    at Object.self.fail (/Users/esben/code/webpack-esben/node_modules/yargs/lib/usage.js:54:20)
    at Object.self.missingArgumentValue (/Users/esben/code/webpack-esben/node_modules/yargs/lib/validation.js:77:15)
    at Object.Yargs.self._runValidation (/Users/esben/code/webpack-esben/node_modules/yargs/yargs.js:1088:16)
    at Object.Yargs.self._parseArgs (/Users/esben/code/webpack-esben/node_modules/yargs/yargs.js:1074:16)
    at Object.get [as argv] (/Users/esben/code/webpack-esben/node_modules/yargs/yargs.js:927:19)
    at Object.<anonymous> (/Users/esben/code/webpack-esben/bin/webpack.js:149:17)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
```

instead of simply

```
Options:
  --help, -h     Show help                                             [boolean]
  --version, -v  Show version number                                   [boolean]
  --json, -j     Prints the result as JSON.                            [boolean]

Missing argument value: config-name
```

I do not have an immediate great idea for how prevent this - do you? @sokra 

Also what is you generelt preference in regards to commenting in the code? i.e. https://github.com/esbenp/webpack/commit/0c5725423d1190f983a2544d0e80e9ec8d2e86ec#diff-877a99a662829398e8136ee938cf1c93R373

**Comment by sokra** [comment]
I guess we can catch the error...

**Comment by esbenp** [comment]
Added the catch https://github.com/esbenp/webpack/commit/1daa844d567d544dc898f84f4f150c1bc19f70b6

Imo it is not a super pretty solution but it does seem to work. Another solution is to simply remove the help-output test. It does cause a lot of trouble and might not be the most necessary test.

**Comment by esbenp** [comment]
Any ideas for this line?
```
var YError = require("yargs/lib/yerror");
if(e instanceof YError) {
```
probably not a great idea to rely on a file inside yargs. Is there another way to catch this?

**Comment by esbenp** [comment]
@sokra do you want me to open this as a pull request, or do you want to leave the issue for now?

**Comment by sokra** [comment]
Please open a PR
