### ISSUE TITLE
ERROR in chunk manifest [entry] with webpack v3.1.0

### ISSUE THREAD

**Issue by GoDotDotDot** [webpack/webpack#5368]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
When I run `npm run dev` with my `webpack.config.js`, the terminal show me some error info follwing:
```javascript
ERROR in chunk manifest [entry]
js/[name].bundle.js
Chunk.entry was removed. Use hasRuntime()
```

I had put code on github,[click here](https://github.com/MeteDesign/Webpack)

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
node:v7.9
webpack:v3.1.0

**Comment by ematipico** [comment]
You should update `extract-text-webpack-plugin` to v3.0.0. Previous versions are not webpack 3 compatible

**Comment by GoDotDotDot** [comment]
@ematipico I has updated extract-text-webpack-plugin to v3.0.0 ,However,the error appear again.

**Comment by sokra** [comment]
It's cause by an incompatible plugin. `--display-error-details` to see stack trace.

**Comment by GoDotDotDot** [comment]
@sokra the stack trace:
```javascript
ERROR in chunk manifest [entry]
js/[name]-[chunkhash].bundle.js
Chunk.entry was removed. Use hasRuntime()
Error: Chunk.entry was removed. Use hasRuntime()
    at Chunk.get entry [as entry] (D:\CHUKUI\WORK\PROJECTS\MD-PRO02\node_modules\webpack\lib\Chunk.js:49:9)
    at registerChunk (D:\CHUKUI\WORK\PROJECTS\MD-PRO02\node_modules\chunk-manifest-webpack-plugin\lib\ChunkManifestPlugin.js:28:73)
    at Array.reduce (native)
    at registerChunk (D:\CHUKUI\WORK\PROJECTS\MD-PRO02\node_modules\chunk-manifest-webpack-plugin\lib\ChunkManifestPlugin.js:36:27)
    at Array.reduce (native)
    at MainTemplate.<anonymous> (D:\CHUKUI\WORK\PROJECTS\MD-PRO02\node_modules\chunk-manifest-webpack-plugin\lib\ChunkManifestPlugin.js:25:33)
    at MainTemplate.applyPluginsWaterfall (D:\CHUKUI\WORK\PROJECTS\MD-PRO02\node_modules\tapable\lib\Tapable.js:92:24)
    at MainTemplate.plugin (D:\CHUKUI\WORK\PROJECTS\MD-PRO02\node_modules\webpack\lib\MainTemplate.js:106:31)
    at MainTemplate.applyPluginsWaterfall (D:\CHUKUI\WORK\PROJECTS\MD-PRO02\node_modules\tapable\lib\Tapable.js:92:24)
    at MainTemplate.render (D:\CHUKUI\WORK\PROJECTS\MD-PRO02\node_modules\webpack\lib\MainTemplate.js:175:31)
    at Compilation.createChunkAssets (D:\CHUKUI\WORK\PROJECTS\MD-PRO02\node_modules\webpack\lib\Compilation.js:1254:34)
    at sealPart2 (D:\CHUKUI\WORK\PROJECTS\MD-PRO02\node_modules\webpack\lib\Compilation.js:629:10)
    at next (D:\CHUKUI\WORK\PROJECTS\MD-PRO02\node_modules\tapable\lib\Tapable.js:184:11)
    at D:\CHUKUI\WORK\PROJECTS\MD-PRO02\node_modules\extract-text-webpack-plugin\dist\index.js:241:13
    at D:\CHUKUI\WORK\PROJECTS\MD-PRO02\node_modules\async\dist\async.js:421:16
    at iteratorCallback (D:\CHUKUI\WORK\PROJECTS\MD-PRO02\node_modules\async\dist\async.js:998:13)
    at D:\CHUKUI\WORK\PROJECTS\MD-PRO02\node_modules\async\dist\async.js:906:16
    at D:\CHUKUI\WORK\PROJECTS\MD-PRO02\node_modules\extract-text-webpack-plugin\dist\index.js:224:15
    at D:\CHUKUI\WORK\PROJECTS\MD-PRO02\node_modules\async\dist\async.js:421:16
    at eachOfArrayLike (D:\CHUKUI\WORK\PROJECTS\MD-PRO02\node_modules\async\dist\async.js:991:9)
    at eachOf (D:\CHUKUI\WORK\PROJECTS\MD-PRO02\node_modules\async\dist\async.js:1051:5)
    at Object.eachLimit (D:\CHUKUI\WORK\PROJECTS\MD-PRO02\node_modules\async\dist\async.js:3145:5)
    at D:\CHUKUI\WORK\PROJECTS\MD-PRO02\node_modules\extract-text-webpack-plugin\dist\index.js:189:29
    at D:\CHUKUI\WORK\PROJECTS\MD-PRO02\node_modules\async\dist\async.js:3083:16
    at eachOfArrayLike (D:\CHUKUI\WORK\PROJECTS\MD-PRO02\node_modules\async\dist\async.js:1003:9)
    at eachOf (D:\CHUKUI\WORK\PROJECTS\MD-PRO02\node_modules\async\dist\async.js:1051:5)
    at Object.eachLimit (D:\CHUKUI\WORK\PROJECTS\MD-PRO02\node_modules\async\dist\async.js:3145:5)
    at Compilation.<anonymous> (D:\CHUKUI\WORK\PROJECTS\MD-PRO02\node_modules\extract-text-webpack-plugin\dist\index.js:184:27)
    at Compilation.applyPluginsAsyncSeries (D:\CHUKUI\WORK\PROJECTS\MD-PRO02\node_modules\tapable\lib\Tapable.js:188:13)
    at Compilation.seal (D:\CHUKUI\WORK\PROJECTS\MD-PRO02\node_modules\webpack\lib\Compilation.js:579:8)
```
All is normal before I reinstall packages, the error info appear just when I reinstall and I did nothing.
could you help me check it?

**Comment by sokra** [comment]
Looks like `chunk-manifest-webpack-plugin` is not webpack 2 compatible

**Comment by GoDotDotDot** [comment]
@sokra But before  I reinstall packages all is fine. So I'm confused.
