### ISSUE TITLE
Error: Didn't get a result from child compiler

### ISSUE THREAD

**Issue by lqzerogg** [webpack/webpack#5413]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
When I am developing, webpack compile success at the first run. But if I modify any of my style, it throw error. This behavior really drives me crazy.
I use many plugin, like extract-text-plugin, sass-loader, url-loader and so on.

**If the current behavior is a bug, please provide the steps to reproduce.**
1 run webpack. 2 modify style file. 3 save. 4 throw error
ERROR in ./v2SRC/view/pages/app/index.scss
Module build failed: Error: Didn't get a result from child compiler
    at /Users/Zero/projects/livebet-client-mobile/node_modules/extract-text-webpack-plugin/dist/loader.js:124:25
    at compile (/Users/Zero/projects/livebet-client-mobile/node_modules/webpack/lib/Compiler.js:304:11)
    at applyPluginsAsync.err (/Users/Zero/projects/livebet-client-mobile/node_modules/webpack/lib/Compiler.js:520:14)
    at next (/Users/Zero/projects/livebet-client-mobile/node_modules/webpack/node_modules/tapable/lib/Tapable.js:184:11)
    at Compiler.<anonymous> (/Users/Zero/projects/livebet-client-mobile/node_modules/extract-text-webpack-plugin/dist/loader.js:108:7)
    at next (/Users/Zero/projects/livebet-client-mobile/node_modules/webpack/node_modules/tapable/lib/Tapable.js:186:14)
    at Compiler.<anonymous> (/Users/Zero/projects/livebet-client-mobile/node_modules/webpack/lib/CachePlugin.js:62:5)
    at Compiler.applyPluginsAsyncSeries (/Users/Zero/projects/livebet-client-mobile/node_modules/webpack/node_modules/tapable/lib/Tapable.js:188:13)
    at compilation.seal.err (/Users/Zero/projects/livebet-client-mobile/node_modules/webpack/lib/Compiler.js:517:11)
    at Compilation.applyPluginsAsyncSeries (/Users/Zero/projects/livebet-client-mobile/node_modules/webpack/node_modules/tapable/lib/Tapable.js:177:46)
    at self.applyPluginsAsync.err (/Users/Zero/projects/livebet-client-mobile/node_modules/webpack/lib/Compilation.js:654:19)
    at Compilation.applyPluginsAsyncSeries (/Users/Zero/projects/livebet-client-mobile/node_modules/webpack/node_modules/tapable/lib/Tapable.js:177:46)
    at self.applyPluginsAsync.err (/Users/Zero/projects/livebet-client-mobile/node_modules/webpack/lib/Compilation.js:645:11)
    at Compilation.applyPluginsAsyncSeries (/Users/Zero/projects/livebet-client-mobile/node_modules/webpack/node_modules/tapable/lib/Tapable.js:177:46)
    at self.applyPluginsAsync.err (/Users/Zero/projects/livebet-client-mobile/node_modules/webpack/lib/Compilation.js:640:10)
    at Compilation.applyPluginsAsyncSeries (/Users/Zero/projects/livebet-client-mobile/node_modules/webpack/node_modules/tapable/lib/Tapable.js:177:46)
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js??ref--5-2!node_modules/postcss-loader/lib/index.js!node_modules/sass-loader/lib/loader.js!v2SRC/view/pages/app/index.scss:
                                                  Asset      Size  Chunks  Chunk Names
    ./img/smile@2x.6b270e1e610a2cea2d8fc38f578ae7f8.png    5.8 kB          
                   d8f37c1da21de7620c89.hot-update.json  44 bytes          
       [0] ./node_modules/css-loader?{"importLoaders":1}!./node_modules/postcss-loader/lib!./node_modules/sass-loader/lib/loader.js!./v2SRC/view/pages/app/index.scss 1.25 kB {0} [built]
       [1] ./node_modules/css-loader/lib/css-base.js 2.26 kB {0}
       [2] ./v2SRC/img/smile@2x.png 97 bytes {0}

**What is the expected behavior?**
It should compile successfully even if I modify style files.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
webpack: 3.0
OS: MacOS 10.12.5
node: 7.0.0

**Comment by sokra** [comment]
> If the current behavior is a bug, please provide the steps to reproduce.
> 1 run webpack. 2 modify style file. 3 save. 4 throw error

It's not possible to reproduce the issue with these instructions.
