### ISSUE TITLE
`this` is undefined within function in Node

### ISSUE THREAD

**Issue by tgoldenberg** [webpack/webpack#5434]
**Do you want to request a *feature* or report a *bug*?** A bug

**What is the current behavior?**

I am using latest Webpack for a server-side library. `webpack.config.js` is as follows, below, followed with `package.json`, and sample file:

```
var webpack = require('webpack');
var path = require('path');
var outputFile = 'tpt.js';
var fs = require('fs');

var UglifyJsPlugin = webpack.optimize.UglifyJsPlugin;
var env = process.env.WEBPACK_ENV;
var libraryName = 'tpt-api';

var outputFile;
var plugins = [ ];

if (env === 'build') {
  plugins.push(new UglifyJsPlugin({ minimize: true }));
  outputFile = libraryName + '.min.js';
} else {
  outputFile = libraryName + '.js';
}

var nodeModules = fs.readdirSync("node_modules")
  .reduce(function(acc, mod) {
    if (mod === ".bin") {
      return acc
    }

    acc[mod] = "commonjs " + mod
    return acc
  }, {})

var config = {
  entry: __dirname + '/src/index.js',
  devtool: 'sourcemap',
  target: 'node',
  output: {
    path: __dirname + '/build',
    filename: outputFile,
    library: 'Tpt',
    libraryTarget: 'umd'
  },
  externals: nodeModules,
  module: {
    loaders: [
      {
        test: /(\.js)$/,
        loader: 'babel-loader',
        exclude: /(node_modules|build)/
      }
    ]
  },
  resolve: {
    extensions: [".js" ]
  },
};

module.exports = config;
```

```
/* package.json */
  "name": "@scoped/name",
  "version": "1.0.4",
  "description": "",
  "main": "build/tpt-api.min.js",
  "scripts": {
    "start": "babel-node index.js",
    "build": "WEBPACK_ENV=build webpack",
    "dev": "WEBPACK_ENV=dev webpack --progress --colors --watch",
    "test": "jest"
  },
 /* ... */
```

```
import axios from 'axios';
import flatfile from 'flat-file-db';

if (process.env.NODE_ENV !== 'production') {
  require('dotenv').config();
}

const db = flatfile.sync('/tmp/token.db');
const MINUTE = 1000 * 60;

const request = axios.create({
  validateStatus: (status) => true,
  headers: {
    'Content-Type': 'application/json',
  }
});

function Tpt(apiKey, apiSecret, endpoint) {
  this.apiKey = apiKey;
  this.apiSecret = apiSecret;
  this.endpoint = endpoint;

  this.fetchToken = async function() {
    try {
      let url = `${this.endpoint}/oauth/token`;
      let credentials = {
        client_id: this.apiKey,
        client_secret: this.apiSecret,
        grant_type: 'client_credentials',
      };
      let response = await request.post(url, credentials);
      return response.data;
    } catch (e) {
      console.warn(e);
    }
  };
}
```

I would expect that the build would work. But when I try to initialize the function, I get an error stating that `this` is undefined.

```
> var t = require('./index.js')
undefined
> t
[Function: Tpt]
> t()
TypeError: Cannot set property 'apiKey' of undefined
    at Tpt (/Users/thomasgoldenberg/Desktop/name/name/build/name.min.js:118:15)
    at repl:1:1
    at ContextifyScript.Script.runInThisContext (vm.js:44:33)
    at REPLServer.defaultEval (repl.js:239:29)
    at bound (domain.js:301:14)
    at REPLServer.runBound [as eval] (domain.js:314:12)
    at REPLServer.onLine (repl.js:433:10)
    at emitOne (events.js:120:20)
    at REPLServer.emit (events.js:210:7)
    at REPLServer.Interface._onLine (readline.js:278:10)
```

Would appreciate any help here. Thank you.

**Comment by hkrutzer** [comment]
In Javascript strict mode, `this` has no value if you call a function like that. See [this](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this#Function_context).

**Comment by sokra** [comment]
You probably intended to write `new t()` instead of `t()`

**Comment by tgoldenberg** [comment]
@sokra thank you. I am new to configuring Webpack and I was unable to see what was in front of me. I have a lot to learn :)
