### ISSUE TITLE
[bug] build dll-user example error : Cannot find module '../dll/js/alpha-manifest.json'

### ISSUE THREAD

**Issue by p2227** [webpack/webpack#5438]
**Do you want to request a *feature* or report a *bug*?**
 report a *bug*

**What is the current behavior?**
```
module.js:487
    throw err;
    ^

Error: Cannot find module '../dll/js/alpha-manifest.json'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/p2227/Program/git/webpackjs/webpack/examples/dll-user/webpack.config.js:7:14)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
```
**If the current behavior is a bug, please provide the steps to reproduce.**
OS: mac 10.12.5
node: 8.1.1
clone this repository
npm i
npm link && npm link webpack
cd examples/dll-user
node build.js

**What is the expected behavior?**
no error , build success
**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by sokra** [comment]
Build the `dll` example before this example.
