### ISSUE TITLE
3.5.1 with ModuleConcatenationPlugin yeilds "Maximum call stack size exceeded"

### ISSUE THREAD

**Issue by jsg2021** [webpack/webpack#5462]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**
```
/Users/Shared/Jenkins/---/node_modules/webpack/lib/optimize/ConcatenatedModule.js:224
		return this._orderedConcatenationList.map(info => info.module.identifier()).join(" ");
		                                                      ^

RangeError: Maximum call stack size exceeded
    at _orderedConcatenationList.map.info (/Users/Shared/Jenkins/---/node_modules/webpack/lib/optimize/ConcatenatedModule.js:224:57)
    at Array.map (native)
    at ConcatenatedModule.identifier (/Users/Shared/Jenkins/---/node_modules/webpack/lib/optimize/ConcatenatedModule.js:224:41)
    at _orderedConcatenationList.map.info (/Users/Shared/Jenkins/---/node_modules/webpack/lib/optimize/ConcatenatedModule.js:224:65)
    at Array.map (native)
    at ConcatenatedModule.identifier (/Users/Shared/Jenkins/---/node_modules/webpack/lib/optimize/ConcatenatedModule.js:224:41)
    at _orderedConcatenationList.map.info (/Users/Shared/Jenkins/---/node_modules/webpack/lib/optimize/ConcatenatedModule.js:224:65)
    at Array.map (native)
    at ConcatenatedModule.identifier (/Users/Shared/Jenkins/---/node_modules/webpack/lib/optimize/ConcatenatedModule.js:224:41)
    at _orderedConcatenationList.map.info (/Users/Shared/Jenkins/---/node_modules/webpack/lib/optimize/ConcatenatedModule.js:224:65)
```

**If the current behavior is a bug, please provide the steps to reproduce.**
I just enabled the plugin.

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
webpack: 3.5.1,
npm 5.3
node 8.2.1 && 6.10.3

**Comment by ljqx** [comment]
webpack config and sample code?

**Comment by jsg2021** [comment]
I'm trying to extract an example config/code... but I can say this project compiled with the plugin yesterday.

It looks like a circular dependency issue... I'm still digging.

**Comment by jsg2021** [comment]
I'm stepping through, and there is def a loop... in a call to identifier(), three calls later the exact same instance is called again. I'm not sure how to setup this example outside my app :/

**Comment by ninjascience** [comment]
I've got this too (and can't provide sample code).  Using webpack 3.4.1 doesn't cause the issue.  We do have some circular deps, but not any new ones.

**Comment by jsg2021** [comment]
I've been trying to create a simple reproduction... but a simple refactor in one of my apps removed a circular dependency and got past it. I still have another app (also closed source) suffering from this, but worst case we can disable the plugin to get by.

**Comment by sokra** [comment]
I think I know whats causing this issue.
