### ISSUE TITLE
3.5.1: Cannot find module 'ajv'

### ISSUE THREAD

**Issue by kromit** [webpack/webpack#5469]
**bug**

**What is the current behavior?**

```
module.js:487
    throw err;
    ^

Error: Cannot find module 'ajv'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/user/GIT/project/node_modules/webpack/lib/validateSchema.js:7:13)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

**If the current behavior is a bug, please provide the steps to reproduce.**

run `npm upgrade` -> `+ webpack@3.5.1`

try to build

**What is the expected behavior?**

build completes without error

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

linux arch
webpack: 3.5.1
node : v8.2.1
npm: 5.2.0 (since 5.3.0 is buggy)

**Comment by kromit** [comment]
workaround: 
delete `node_modules` in the project
`npm cache verify`
`npm install`

**Comment by motarek1999** [comment]
thank you man after an hour your instructions helped me out.
