### ISSUE TITLE
Cannot get final name for export "CompositeFilterDescriptor" in "somemodule"

### ISSUE THREAD

**Issue by deepakshrma** [webpack/webpack#5508]
We are building tools based on angular 4 api. It was working fine with old angular version. We are trying to migrate our source to angular cli generate boilerplate. Now it breaking everywhere. i tried to debug. however not able to find a solution. As per my understanding it breaking with new webpack configuration. I m not able to trace what is the issue. And for what reason this issue stand for. do have to make any typescript config change ? please help me!!

Please refer to below given details.

Error trace:
```
Cannot get final name for export "CompositeFilterDescriptor" in "/Users/user/Projects/my-ui-components/dist/my-data-query/filtering/filter-descriptor.interface.ts" (known exports: isCompositeFilterDescriptor true, known reexports: )
Error: Cannot get final name for export "CompositeFilterDescriptor" in "/Users/user/Projects/my-ui-components/dist/my-data-query/filtering/filter-descriptor.interface.ts" (known exports: isCompositeFilterDescriptor true, known reexports: )
    at getFinalName (/Users/user/Projects/my-ui-seed-next/node_modules/@angular/cli/node_modules/webpack/lib/optimize/ConcatenatedModule.js:52:8)
    at getFinalName (/Users/user/Projects/my-ui-seed-next/node_modules/@angular/cli/node_modules/webpack/lib/optimize/ConcatenatedModule.js:37:11)
    at info.globalScope.through.forEach.reference (/Users/user/Projects/my-ui-seed-next/node_modules/@angular/cli/node_modules/webpack/lib/optimize/ConcatenatedModule.js:405:24)
    at Array.forEach (native)
    at modulesWithInfo.forEach.info (/Users/user/Projects/my-ui-seed-next/node_modules/@angular/cli/node_modules/webpack/lib/optimize/ConcatenatedModule.js:393:29)
    at Array.forEach (native)
    at ConcatenatedModule.source (/Users/user/Projects/my-ui-seed-next/node_modules/@angular/cli/node_modules/webpack/lib/optimize/ConcatenatedModule.js:392:19)
    at ModuleTemplate.render (/Users/user/Projects/my-ui-seed-next/node_modules/@angular/cli/node_modules/webpack/lib/ModuleTemplate.js:14:31)
    at /Users/user/Projects/my-ui-seed-next/node_modules/@angular/cli/node_modules/webpack/lib/Template.js:110:28
    at Function.from (native)
    at Chunk.mapModules (/Users/user/Projects/my-ui-seed-next/node_modules/@angular/cli/node_modules/webpack/lib/Chunk.js:163:16)
    at ChunkTemplate.renderChunkModules (/Users/user/Projects/my-ui-seed-next/node_modules/@angular/cli/node_modules/webpack/lib/Template.js:107:26)
    at ChunkTemplate.render (/Users/user/Projects/my-ui-seed-next/node_modules/@angular/cli/node_modules/webpack/lib/ChunkTemplate.js:16:30)
    at Compilation.createChunkAssets (/Users/user/Projects/my-ui-seed-next/node_modules/@angular/cli/node_modules/webpack/lib/Compilation.js:1256:35)
    at sealPart2 (/Users/user/Projects/my-ui-seed-next/node_modules/@angular/cli/node_modules/webpack/lib/Compilation.js:629:10)
    at next (/Users/user/Projects/my-ui-seed-next/node_modules/tapable/lib/Tapable.js:202:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-ui-seed-next@0.0.0 build:prod: `ng build --prod --env=prod --aot=false`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the my-ui-seed-next@0.0.0 build:prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     
```
**ng -v:**
```
@angular/cli: 1.3.0
node: 6.10.1
os: darwin x64
@angular/animations: 4.2.4
@angular/common: 4.2.4
@angular/compiler: 4.2.4
@angular/core: 4.2.4
@angular/forms: 4.2.4
@angular/http: 4.2.4
@angular/platform-browser: 4.2.4
@angular/platform-browser-dynamic: 4.2.4
@angular/router: 4.2.4
@angular/cli: 1.3.0
@angular/compiler-cli: 4.2.4
@angular/language-service: 4.2.4
```
**Webpack src:**
https://github.com/webpack/webpack/blob/287d587867bc50699d3604931424c7fb55f2bdf1/lib/optimize/ConcatenatedModule.js#L71

**Comment by deepakshrma** [comment]
I looked at the issue more. I found, There are some major changes (concate module) which break the build. It is fixed in updated version. Angular need to update their webpack. So closing issue.
