### ISSUE TITLE
Webpack 3 TypeError: chunk.hasRuntime is not a function

### ISSUE THREAD

**Issue by bschmitz9** [webpack/webpack#5616]
I now can not run my npm start without getting this error:

```
TypeError: chunk.hasRuntime is not a function
    at allChunks.filter (C:\Users\schmitzb\Projects\test3\bantor\resortPlatform\node_modules\webpack\lib\optimize\CommonsChunkPlugin.js:258:17)
    at Array.filter (native)
    at CommonsChunkPlugin.getAffectedChunks (C:\Users\schmitzb\Projects\test3\bantor\resortPlatform\node_modules\webpack\lib\optimize\CommonsChunkPlugin.js:255:20)
    at targetChunks.forEach (C:\Users\schmitzb\Projects\test3\bantor\resortPlatform\node_modules\webpack\lib\optimize\CommonsChunkPlugin.js:107:34)
    at Array.forEach (native)
    at Compilation.compilation.plugin (C:\Users\schmitzb\Projects\test3\bantor\resortPlatform\node_modules\webpack\lib\optimize\CommonsChunkPlugin.js:102:18)
    at Compilation.applyPlugins (C:\Users\schmitzb\AppData\Roaming\npm\node_modules\webpack-dev-server\node_modules\webpack\node_modules\tapable\lib\Tapable.js:26:37)
    at Compilation.seal (C:\Users\schmitzb\AppData\Roaming\npm\node_modules\webpack-dev-server\node_modules\webpack\lib\Compilation.js:522:7)
    at Compiler.<anonymous> (C:\Users\schmitzb\AppData\Roaming\npm\node_modules\webpack-dev-server\node_modules\webpack\lib\Compiler.js:397:15)
    at C:\Users\schmitzb\AppData\Roaming\npm\node_modules\webpack-dev-server\node_modules\webpack\node_modules\tapable\lib\Tapable.js:103:11
    at Compilation.<anonymous> (C:\Users\schmitzb\AppData\Roaming\npm\node_modules\webpack-dev-server\node_modules\webpack\lib\Compilation.js:445:10)
    at C:\Users\schmitzb\AppData\Roaming\npm\node_modules\webpack-dev-server\node_modules\webpack\lib\Compilation.js:417:12
    at C:\Users\schmitzb\AppData\Roaming\npm\node_modules\webpack-dev-server\node_modules\webpack\lib\Compilation.js:332:10
    at C:\Users\schmitzb\AppData\Roaming\npm\node_modules\webpack-dev-server\node_modules\webpack\node_modules\async\lib\async.js:52:16
    at done (C:\Users\schmitzb\AppData\Roaming\npm\node_modules\webpack-dev-server\node_modules\webpack\node_modules\async\lib\async.js:246:17)
    at C:\Users\schmitzb\AppData\Roaming\npm\node_modules\webpack-dev-server\node_modules\webpack\node_modules\async\lib\async.js:44:16

```
**It errors out on this line in my package.json:**
` webpack-dev-server --inline --progress --port 4200`

**Here is my package.json:** 
```
{
  "name": "bantor",
  "version": "1.0.0",
  "description": "Designed to help resorts",
  "scripts": {
    "start": "webpack-dev-server --inline --progress --port 4200",
    "test": "karma start",
    "build": "rimraf dist && webpack --config webpack/webpack.prod.js --progress --profile --bail"
  },
  "license": "MIT",
  "dependencies": {
    "@angular/common": "~4.3.3",
    "@angular/compiler": "~4.3.3",
    "@angular/core": "~4.3.3",
    "@angular/forms": "~4.3.3",
    "@angular/http": "~4.3.3",
    "@angular/platform-browser": "~4.3.3",
    "@angular/platform-browser-dynamic": "~4.3.3",
    "@angular/router": "~4.3.3",
    "angular2-jwt": "0.2.3",
    "angular-2-local-storage": "1.0.1",
    "bootstrap": "4.0.0-alpha.6",
    "tether": "1.4.0",
    "core-js": "^2.4.1",
    "font-awesome": "^4.7.0",
    "rxjs": "5.4.2",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@types/jasmine": "2.5.53",
    "@types/node": "^8.0.19",
    "@types/jquery": "3.2.11",
    "angular2-template-loader": "^0.6.2",
    "awesome-typescript-loader": "^3.2.2",
    "css-loader": "^0.28.4",
    "extract-text-webpack-plugin": "3.0.0",
    "file-loader": "^0.11.2",
    "html-loader": "^0.5.0",
    "html-webpack-plugin": "^2.30.1",
    "node-sass": "^4.5.3",
    "null-loader": "^0.1.1",
    "raw-loader": "^0.5.1",
    "rimraf": "^2.6.1",
    "sass-loader": "^6.0.6",
    "style-loader": "^0.18.2",
    "typescript": "~2.4.2",
    "webpack": "3.4.1",
    "webpack-dev-server": "2.6.1",
    "webpack-merge": "^4.1.0"
  }
}

```
**Here is my webpack-common.js:**
```
var webpack = require('webpack');
var HtmlWebpackPlugin = require('html-webpack-plugin');
var ExtractTextPlugin = require('extract-text-webpack-plugin');
var helpers = require('./helpers');

module.exports = {
  entry: {
    'polyfills': './webcontent/polyfills.ts',
    'vendor': './webcontent/vendor.ts',
    'app': './webcontent/main.ts'
  },

  resolve: {
    extensions: ['.ts', '.js']
  },

  module: {
    rules: [{
        test: /\.ts$/,
        loaders: ['awesome-typescript-loader', 'angular2-template-loader']
      },
      {
        test: /\.html$/,
        loader: 'html-loader'
      },
      {
        test: /\.(png|jpe?g|gif|svg|woff|woff2|ttf|eot|ico)$/,
        loader: 'file-loader?name=assets/[name].[hash].[ext]'
      },
      {
        test: /\.css$/,
        exclude: helpers.root('webcontent', 'app'),
        loader: ExtractTextPlugin.extract({
          fallback: 'style-loader',
          use: 'css-loader?sourceMap'
        })
      },
      {
        test: /\.css$/,
        include: helpers.root('webcontent', 'app'),
        loader: 'raw-loader'
      },
      {
        test: /\.scss$/,
        loader: ExtractTextPlugin.extract({
          fallback: "style-loader",
          use: "css-loader?sourceMap!sass-loader?sourceMap"
        })
      },
      {
        test: /bootstrap\/dist\/js\/umd\//,
        use: 'imports?jQuery=jquery'
      }
    ]
  },

  plugins: [
    // Workaround for angular/angular#11580
    new webpack.ContextReplacementPlugin(
      // The (\\|\/) piece accounts for path separators in *nix and Windows
      /angular(\\|\/)core(\\|\/)@angular/,
      helpers.root('./webcontent'), // location of your webcontent
      {} // a map of your routes
    ),

    new webpack.optimize.CommonsChunkPlugin({
      name: ['app', 'vendor', 'polyfills']
    }),

    new webpack.ProvidePlugin({
      $: "jquery",
      jQuery: "jquery",
      "window.jQuery": "jquery",
      "Tether": 'tether'
    }),

    new HtmlWebpackPlugin({
      template: 'webcontent/index.html'
    })
  ]
};
```

**And my webpack-dev.js:**
```
var webpackMerge = require('webpack-merge');
var ExtractTextPlugin = require('extract-text-webpack-plugin');
var commonConfig = require('./webpack.common.js');
var helpers = require('./helpers');

module.exports = webpackMerge(commonConfig, {
  devtool: 'cheap-module-eval-source-map',

  output: {
    path: helpers.root('dist'),
    publicPath: '/',
    filename: '[name].js',
    chunkFilename: '[id].chunk.js'
  },

  plugins: [
    new ExtractTextPlugin('[name].css')
  ],

  devServer: {
    historyApiFallback: true,
    stats: 'minimal'
  }
});
```

If you can let me know that issue that would be great. Thanks

**Comment by TheLarkInn** [comment]
Hi thanks for reporting. Would it be possible that you can upgrade to webpack/webpack-dev-server to `@latest` tag? 

This way we can verify if this is an isolated issue in that version or not.

**Comment by sokra** [comment]
sounds like an old extract-text-webpack-plugin dependency.

**Comment by bschmitz9** [comment]
I was able to resolve this by running "npm cache clean". Then I deleted my node modules, and ran "npm install"

So there was something getting hung up there but exactly what I'm not sure.
