### ISSUE TITLE
Webpack fails to compile after a second run through tests, the error object that should contain the error only has an empty string

### ISSUE THREAD

**Issue by alonewarrior** [webpack/webpack#5629]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
Currently, whenever I run a my tests (for Angular), the first time around succeeds in running the tests but the second time it encounters some sort of error and fails. The error is:
```
[../../../../../app recursive \.spec\.ts$] ./app \.spec\.ts$ 160 bytes {main} [built]
[../../../../../app/test.ts] ./app/test.ts 4.66 kB {main}
[../../../../../demo/polyfills.ts] ./demo/polyfills.ts 8.16 kB {polyfills}
[../../../../core-js/es6/parse-float.js] ./node_modules/core-js/es6/parse-float.js 96 bytes {polyfills}
[../../../../core-js/es6/parse-int.js] ./node_modules/core-js/es6/parse-int.js 92 bytes {polyfills}
[../../../../core-js/es6/reflect.js] ./node_modules/core-js/es6/reflect.js 718 bytes {polyfills}
[../../../../zone.js/dist/async-test.js] ./node_modules/zone.js/dist/async-test.js 3.23 kB {vendor}
[../../../../zone.js/dist/fake-async-test.js] ./node_modules/zone.js/dist/fake-async-test.js 17 kB {vendor}
[../../../../zone.js/dist/jasmine-patch.js] ./node_modules/zone.js/dist/jasmine-patch.js 6.36 kB {vendor}
   [0] multi ./demo/polyfills.ts 28 bytes {polyfills}
[../../../../zone.js/dist/long-stack-trace-zone.js] ./node_modules/zone.js/dist/long-stack-trace-zone.js 6.22 kB {vendor}
[../../../../zone.js/dist/proxy.js] ./node_modules/zone.js/dist/proxy.js 5.6 kB {vendor}
[../../../../zone.js/dist/sync-test.js] ./node_modules/zone.js/dist/sync-test.js 1.41 kB {vendor}
[../../../core/@angular/core/testing.es5.js] ./node_modules/@angular/core/@angular/core/testing.es5.js 40 kB {vendor}
[../../../platform-browser-dynamic/@angular/platform-browser-dynamic/testing.es5.js] ./node_modules/@angular/platform-browser-dynamic/@angular/platform-browser-dynamic/testing.es5.js 3.6 kB {vendor}
    + 298 hidden modules

ERROR in 
```

Nothing more is outputted. I checked to see if for some reason the error wasn't being logged to the console but it turns out that it's just an empty string in this scenario. If I make another change and the tests attempt to run again I get the error:
```
WARNING in ./app/components/graph-line/graph-line.component.spec.ts
Module build failed: TypeError: Cannot read property 'flags' of undefined
      at resolveAlias (DIR/node_modules/typescript/lib/typescript.js:23972:36)
      at checkAliasSymbol (DIR/node_modules/typescript/lib/typescript.js:42658:26)
      at checkImportBinding (DIR/node_modules/typescript/lib/typescript.js:42688:13)
      at Object.forEach (DIR/node_modules/typescript/lib/typescript.js:1499:30)
      at checkImportDeclaration (DIR/node_modules/typescript/lib/typescript.js:42709:32)
      at checkSourceElement (DIR/node_modules/typescript/lib/typescript.js:43018:28)
      at Object.forEach (DIR/node_modules/typescript/lib/typescript.js:1499:30)
      at checkSourceFileWorker (DIR/node_modules/typescript/lib/typescript.js:43091:20)
      at checkSourceFile (DIR/node_modules/typescript/lib/typescript.js:43071:13)
      at getDiagnosticsWorker (DIR/node_modules/typescript/lib/typescript.js:43135:17)
      at getDiagnostics (DIR/node_modules/typescript/lib/typescript.js:43121:24)
      at Object.getEmitResolver (DIR/node_modules/typescript/lib/typescript.js:23049:13)
      at DIR/node_modules/typescript/lib/typescript.js:70489:69
      at runWithCancellationToken (DIR/node_modules/typescript/lib/typescript.js:70245:24)
      at getDeclarationDiagnosticsForFileNoCache (DIR/node_modules/typescript/lib/typescript.js:70488:20)
      at getAndCacheDiagnostics (DIR/node_modules/typescript/lib/typescript.js:70501:26)
 @ ./app \.spec\.ts$
 @ ./app/test.ts
Firefox 55.0.0 (Mac OS X 10.12.0) ERROR
  Error: Module build failed: TypeError: Cannot read property 'flags' of undefined
      at resolveAlias (DIR/node_modules/typescript/lib/typescript.js:23972:36)
      at checkAliasSymbol (DIR/node_modules/typescript/lib/typescript.js:42658:26)
      at checkImportBinding (DIR/node_modules/typescript/lib/typescript.js:42688:13)
      at Object.forEach (DIR/node_modules/typescript/lib/typescript.js:1499:30)
      at checkImportDeclaration (DIR/node_modules/typescript/lib/typescript.js:42709:32)
      at checkSourceElement (DIR/node_modules/typescript/lib/typescript.js:43018:28)
      at Object.forEach (DIR/node_modules/typescript/lib/typescript.js:1499:30)
      at checkSourceFileWorker (DIR/node_modules/typescript/lib/typescript.js:43091:20)
      at checkSourceFile (DIR/node_modules/typescript/lib/typescript.js:43071:13)
      at getDiagnosticsWorker (DIR/node_modules/typescript/lib/typescript.js:43135:17)
      at getDiagnostics (DIR/node_modules/typescript/lib/typescript.js:43121:24)
      at Object.getEmitResolver (DIR/node_modules/typescript/lib/typescript.js:23049:13)
      at DIR/node_modules/typescript/lib/typescript.js:70489:69
      at runWithCancellationToken (DIR/node_modules/typescript/lib/typescript.js:70245:24)
      at getDeclarationDiagnosticsForFileNoCache (DIR/node_modules/typescript/lib/typescript.js:70488:20)
      at getAndCacheDiagnostics (DIR/node_modules/typescript/lib/typescript.js:70501:26)
  at http://localhost:9876/_karma_webpack_/main.bundle.js line 36 > eval:1
```

I have researched this as best as I can and have tried whatever suggestions were provided but no luck has come from it. The issue has been getting worse and worse, which is baffling me.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
The expected behavior is that it would output an error to indicate what's wrong or to continue compiling and run the tests. As of right now I cannot determine what the issue is.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

`
npm: 5.0.3
Node: 7.4.0
webpack: 3.4.1
OS: Mac OS Sierra
`

**Comment by sokra** [comment]
Could you try `--display-error-details`?

**Comment by alonewarrior** [comment]
@sokra I am not able to due to it being run through Angular. But I do believe I made a discovery. This issue seems to happen whenever I am updating .spec.ts files. If I update a regular file, this is what appears during the build: 

```
  0% compiling
 10% building modules 0/1 modules 1 active ...o-waveform-graphing\app /\.spec\.ts$/
 30% building modules 1/2 modules 1 active ...o-waveform-graphing\app /\.spec\.ts$/
 50% building modules 2/3 modules 1 active ...ts\graph-line\graph-line.component.ts
 70% building modules 3/3 modules 0 active
 71% sealing
 75% advanced module optimization
 76% basic chunk optimization pass 2
 76% basic chunk optimization pass 3
 83% module order optimization
 84% module id optimization
 86% chunk order optimization
 87% chunk id optimization
 88% hashing
 90% chunk assets processing
 91% additional chunk assets processing
 92% chunk asset optimization
 94% asset optimization
 95% emitting
```

But when I update a spec file, this is what it outputs before having an error:

```
  0% compiling
 10% building modules 0/1 modules 1 active ...o-waveform-graphing\app /\.spec\.ts$/
 30% building modules 1/2 modules 1 active ...o-waveform-graphing\app /\.spec\.ts$/
 70% building modules 3/3 modules 0 active
 71% sealing
 75% advanced module optimization
 76% basic chunk optimization pass 2
 76% basic chunk optimization pass 3
 83% module order optimization
 84% module id optimization
 87% chunk id optimization
 88% hashing
 90% chunk assets processing
 91% additional chunk assets processing
 92% chunk asset optimization
 94% asset optimization
 95% emitting
```

I can force this to happen by just making a change and saving. If I change it and save it again, the whole application recompiles and the test runs just fine. It seems to be an every other type situation, unless I make changes too quickly in the spec file. Some times if I give it awhile it might work after a change, other times it'll break back-to-back before finally working again. So, maybe there's an issue with it trying to build/find the spec files?

Here's the angular file that pulls it all in, which should look familiar to the output red text:
```
// This file is required by karma.conf.js and loads recursively all the .spec and framework files

import 'zone.js/dist/long-stack-trace-zone';
import 'zone.js/dist/proxy.js';
import 'zone.js/dist/sync-test';
import 'zone.js/dist/jasmine-patch';
import 'zone.js/dist/async-test';
import 'zone.js/dist/fake-async-test';
import { getTestBed } from '@angular/core/testing';
import {
  BrowserDynamicTestingModule,
  platformBrowserDynamicTesting
} from '@angular/platform-browser-dynamic/testing';

// Unfortunately there's no typing for the `__karma__` variable. Just declare it as any.
declare let __karma__: any;
declare let require: any;

// Prevent Karma from running prematurely.
__karma__.loaded = function () {};

// First, initialize the Angular testing environment.
getTestBed().initTestEnvironment(
  BrowserDynamicTestingModule,
  platformBrowserDynamicTesting()
);
// Then we find all the tests.
const context = require.context('./', true, /\.spec\.ts$/);
// And load the modules.
context.keys().map(context);
// Finally, start Karma to run the tests.
__karma__.start();
```

Hopefully this provides some more insight into the issue at hand. I'm not sure if it's directly a webpack issue or if there's an error elsewhere that causes webpack to fail. I've tried both including and excluding spec files from building and linting in the hopes of seeing some sort of change, but it hasn't had any effect.

**Comment by AshMcConnell** [comment]
I'm having the same issue, I get: - 
![image](https://user-images.githubusercontent.com/497941/34114598-1a3b8f88-e40b-11e7-9bae-07dc9502dbe8.png)

**Comment by mattfors** [comment]
I've gotten the same issue and --display-error-details doesn't show any more info still just 'ERROR in'
