### ISSUE TITLE
dynamic require all bundled in

### ISSUE THREAD

**Issue by willin** [webpack/webpack#5639]
**Do you want to request a *feature* or report a *bug*?**

question

**What is the current behavior?**

https://github.com/AirDwing/webpack-server-bundle

```js
const ENV = process.env.API_ENV || 'development';
// eslint-disable-next-line import/no-dynamic-require
const options = require(`./_${ENV}`);

module.exports = options;
```

if there are several config files like `_development.js` , `_.production.js`

when i build, i specify `ENV` to one, but other files are also bundled in. like:
```js
(function(a){function b(d){if(c[d])return c[d].exports;var e=c[d]={i:d,l:!1,exports:{}};return a[d].call(e.exports,e,e.exports,b),e.l=!0,e.exports}var c={};return b.m=a,b.c=c,b.d=function(a,c,d){b.o(a,c)||Object.defineProperty(a,c,{configurable:!1,enumerable:!0,get:d})},b.n=function(a){var c=a&&a.__esModule?function(){return a['default']}:function(){return a};return b.d(c,'a',c),c},b.o=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)},b.p='/',b(b.s=3)})([function(a,b,c){const d=c(4)(`./_${'development'}`);a.exports=d},function(a,b){b.enabledModules=['demo'],b.mysq={connectionLimit:10,host:'127.0.0.1',user:'root',password:'root'},b.redis={host:'127.0.0.1',port:6379,db:1,ttl:3600},b.server={port:3300,hostname:'127.0.0.1'}},function(a,b){b.enabledModules=['demo2'],b.mysq={connectionLimit:10,host:'127.0.0.1',user:'root',password:'root'},b.redis={host:'127.0.0.1',port:6379,db:1,ttl:3600},b.server={port:3300,hostname:'127.0.0.1'}},function(a,b,c){const{server:d}=c(0),e=c(5);e.listen(d),console.log(new Date)},function(a,b,c){function d(a){return c(e(a))}function e(a){var b=f[a];if(!(b+1))throw new Error('Cannot find module \''+a+'\'.');return b}var f={"./_development":1,"./_development.js":1,"./_production":2,"./_production.js":2};d.keys=function(){return Object.keys(f)},d.resolve=e,a.exports=d,d.id=4},function(a,b,c){const d=c(6),e=c(7),{enabledModules:f}=c(0),g=new d;g.use(e()),f.forEach((a)=>{const b=c(8)(`./${a}/route`);g.use(b.middleware())}),a.exports=g},function(a){a.exports=require('koa')},function(a){a.exports=require('koa-api-logger')},function(a,b,c){function d(a){return c(e(a))}function e(a){var b=f[a];if(!(b+1))throw new Error('Cannot find module \''+a+'\'.');return b}var f={"./demo/route":9};d.keys=function(){return Object.keys(f)},d.resolve=e,a.exports=d,d.id=8},function(a,b,c){const d=c(10),e=c(11),f=d();f.prefix('/demo'),f.route(e),a.exports=f},function(a){a.exports=require('koa-joi-router')},function(a,b,c){const d=c(12),e=[{method:'get',path:'/test',validate:{query:{name:d.string().max(100).description('new user name')}},handler:async(a)=>{a.status=200,a.body={status:1,msg:'hello world'}},swagger:{tags:['demo'],responses:{200:{description:'\u67E5\u8BE2\u57DF\u540D',schema:d.object({status:d.number().integer().default(1),server:d.string().default('js.cool')}).label('serverSuccess')}}}}];a.exports=e},function(a){a.exports=require('joi')}]);
//# sourceMappingURL=app.js.map
```

```js
{"./_development":1,"./_development.js":1,"./_production":2,"./_production.js":2};
```

**What is the expected behavior?**

only one config file (dynamic required) should be bundled in

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

webpack latest version

**Comment by sokra** [comment]
webpack is a static bundler. It doesn't know which values variable will have at runtime. It does its best to don't break your code by bundling all possible files.

It's able to evaluate **some** expressions at build time. So you could try this:

``` js
const options = require(`./_${process.env.API_ENV || 'development'}`);
```

**Comment by willin** [comment]
but still other dynamic modules.

like config

```js
exports.enabledModules = ['demo1','demo2'];
```

https://github.com/AirDwing/webpack-server-bundle/blob/master/src/server.js#L9-L13

```js
enabledModules.forEach((mod) => {
  /* eslint-disable global-require,import/no-dynamic-require */
  const routes = require(`./${mod}/route`);
  routes.middleware() |> app.use;
});
```

**Comment by sokra** [comment]
This will have the same issue.

**Comment by willin** [comment]
i've tried. config files now only bundle the correct one in.

but modules `const routes = require(`./${mod}/route`);` required like this are still all bundled in.

**Comment by willin** [comment]
i found a method on stackoverflow: 

```js
const context = require('./', false);
enabledModules.forEach((mod) => {
  /* eslint-disable global-require,import/no-dynamic-require */
  const routes = context(`./${mod}/route`);
  routes.middleware() |> app.use;
});
```

```
Hash: 323977bff1d31ad445b0
Version: webpack 3.5.6
Time: 557ms
     Asset     Size  Chunks             Chunk Names
    app.js  1.41 kB       0  [emitted]  app
app.js.map  4.48 kB       0  [emitted]  app

ERROR in ./src/server.js
Cannot statically analyse 'require(..., ...)' in line 22
 @ ./src/index.js 5:14-33
error Command failed with exit code 2.
```

**Comment by willin** [comment]
trial 2:

```js
// not change 
enabledModules.forEach((mod) => {
  /* eslint-disable global-require,import/no-dynamic-require */
  const routes = require(`./${mod}/route`);
  routes.middleware() |> app.use;
});
```

webpack:

```js
const config = require('../config');

const entry = [
  path.resolve(__dirname, '../src/index.js'),
  ...config.enabledModules.map(x => path.resolve(__dirname, `../src/${x}/route/index.js`))
];
```

```
ERROR in multi ../webpack-server-bundle/src/index.js ../webpack-server-bundle/src/demo/route/index.js
Module not found: Error: Can't resolve 'babel-loader' in '/Users/willin/Documents/dwing/others/src'
 @ multi ../webpack-server-bundle/src/index.js ../webpack-server-bundle/src/demo/route/index.js

ERROR in multi ../webpack-server-bundle/src/index.js ../webpack-server-bundle/src/demo/route/index.js
Module not found: Error: Can't resolve 'babel-loader' in '/Users/willin/Documents/dwing/others/src'
 @ multi ../webpack-server-bundle/src/index.js ../webpack-server-bundle/src/demo/route/index.js
```

**Comment by willin** [comment]
trial 3:

webpack resolve alias:

```js
{
 alias: config.enabledModules.reduce((obj, mod) => {
      // eslint-disable-next-line no-param-reassign
      obj[mod] = path.resolve(__dirname, `../src/${mod}/route/index.js`);
      return obj;
    }, {})
}
```

```js
enabledModules.forEach((mod) => {
  /* eslint-disable global-require,import/no-dynamic-require */
  const routes = require(mod);
  routes.middleware() |> app.use;
});
```

```
enabledModules.forEach((mod) => {
  /* eslint-disable global-require,import/no-dynamic-require */
  const routes = require(mod);
  routes.middleware() |> app.use;
});
```
```
/Users/willin/Documents/dwing/others/webpack-server-bundle/dist/app.js:1
(function (exports, require, module, __filename, __dirname) { (function(a){function b(d){if(c[d])return c[d].exports;var e=c[d]={i:d,l:!1,exports:{}};return a[d].call(e.exports,e,e.exports,b),e.l=!0,e.exports}var c={};return b.m=a,b.c=c,b.d=function(a,c,d){b.o(a,c)||Object.defineProperty(a,c,{configurable:!1,enumerable:!0,get:d})},b.n=function(a){var c=a&&a.__esModule?function(){return a['default']}:function(){return a};return b.d(c,'a',c),c},b.o=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)},b.p='/',b(b.s=1)})([function(a,b,c){const d=c(2);a.exports=d},function(a,b,c){'use strict';var d=c(0),e=c(3),f=function(a){return a&&a.__esModule?a:{default:a}}(e);f.default.listen(d.server),console.log(new Date)},function(a,b){b.enabledModules=['demo'],b.mysq={connectionLimit:10,host:'127.0.0.1',user:'root',password:'root'},b.redis={host:'127.0.0.1',port:6379,db:1,ttl:3600},b.server={port:3300,hostname:'127.0.0.1'}},function(a,b,

Error: Cannot find module "."
    at /Users/willin/Documents/dwing/others/webpack-server-bundle/dist/app.js:1:1206
    at i.enabledModules.forEach (/Users/willin/Documents/dwing/others/webpack-server-bundle/dist/app.js:1:1276)
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/Users/willin/Documents/dwing/others/webpack-server-bundle/dist/app.js:1:1167)
    at b (/Users/willin/Documents/dwing/others/webpack-server-bundle/dist/app.js:1:163)
    at Object.b.enabledModules (/Users/willin/Documents/dwing/others/webpack-server-bundle/dist/app.js:1:620)
    at b (/Users/willin/Documents/dwing/others/webpack-server-bundle/dist/app.js:1:163)
    at /Users/willin/Documents/dwing/others/webpack-server-bundle/dist/app.js:1:524
    at Object.<anonymous> (/Users/willin/Documents/dwing/others/webpack-server-bundle/dist/app.js:1:534)
    at Module._compile (module.js:573:30)
```

**Comment by willin** [comment]
```
PublicPath: /
     Asset     Size  Chunks             Chunk Names
    app.js   2.7 kB       0  [emitted]  app
app.js.map  8.26 kB       0  [emitted]  app
Entrypoint app = app.js app.js.map
chunk    {0} app.js, app.js.map (app) 3.36 kB [entry] [rendered]
    > app [3] ./src/index.js
    [0] ./config/index.js 152 bytes {0} [depth 1] [built]
        cjs require ../config [3] ./src/index.js 3:14-34
        cjs require ../config [5] ./src/server.js 15:14-34
    [3] ./src/index.js 300 bytes {0} [depth 0] [built]
    [4] ./config/_development.js 274 bytes {0} [depth 2] [built]
        cjs require ./_development [0] ./config/index.js 2:16-69
    [5] ./src/server.js 674 bytes {0} [depth 1] [built]
        cjs require ./server [3] ./src/index.js 5:14-33
    [8] ./src ^\.\/.*\/route$ 194 bytes {0} [depth 2] [built]
        cjs require context . [5] ./src/server.js 23:78-103
    [9] ./src/demo/route/index.js 184 bytes {0} [depth 3] [optional] [built]
        context element ./demo/route [8] ./src ^\.\/.*\/route$ ./demo/route
   [10] ./src/demo/route/test.js 616 bytes {0} [depth 4] [built]
        cjs require ./test [9] ./src/demo/route/index.js 5:13-30
   [11] ./src/test/route/index.js 184 bytes {0} [depth 3] [optional] [built]
        context element ./test/route [8] ./src ^\.\/.*\/route$ ./test/route
   [12] ./src/test/route/test.js 616 bytes {0} [depth 4] [built]
        cjs require ./test [11] ./src/test/route/index.js 5:13-30
     + 4 hidden modules
```

optional regexp match

**Comment by willin** [comment]
https://doc.webpack-china.org/plugins/context-replacement-plugin perhaps may help

**Comment by willin** [comment]
https://doc.webpack-china.org/plugins/context-replacement-plugin perhaps may help

```js
new webpack.ContextReplacementPlugin(
  /\.src\/.*\/route$/,
  context=>{}
)
```

or

```
new webpack.ContextReplacementPlugin(
  /\.\/.*\/route$/,
 context=>{}
)
```

all cannot match

only `/\.src/.*/` can, but i have no idea how to replace

```js
new webpack.ContextReplacementPlugin(/\.\/src\/.*/, (context) => {
  if ( !/\/.\/.*\/route/.test(context.context) ) return;

  Object.assign(context, {
    regExp: new RegExp(enabledModules.join('|')),
    request: context.context
  });
})
```

**Comment by sokra** [comment]
Yes `ContextReplacementPlugin` can help in this scenario.

**Comment by willin** [comment]
how to use this plugin? 

documents use `moment` for example but it's too simple

```js
// source folder `src`
// dynamic require  like  `enabledModules[].forEach(mod=> require(./${mod}/route)`, regexp: ` /^\.\/.*\/route$/`
// recursive true
// new RegExp ` /^\.\/(enabledA|enabledB)\/route$/`
new webpack.ContextReplacementPlugin(/src/, /^\.\/.*\/route$/, true, new RegExp(`^./(${enabledModules.join('|')})/route$`));
```

- [ ]

**Comment by willin** [comment]
gotcha

```js
new webpack.ContextReplacementPlugin(/src/, new RegExp(`^./(lib|hook|${enabledModules.join('|')})/.*$`)),
```
