### ISSUE TITLE
When webpack cannot resolve a path it fails to prompt the error

### ISSUE THREAD

**Issue by JSteunou** [webpack/webpack#5787]
**Do you want to request a *feature* or report a *bug*?**

a bug

**What is the current behavior?**

Webpack exit with an internal error instead of logging the actual error when it cannot resolve a path

```
node_modules/webpack/lib/Compilation.js:268
                        _this.semaphore.release();
                             ^

TypeError: Cannot read property 'semaphore' of null
    at factoryCallback (/home/jerome/fooproject/node_modules/webpack/lib/Compilation.js:268:12)
    at factory (/home/jerome/fooproject/node_modules/webpack/lib/NormalModuleFactory.js:235:20)
    at resolver (/home/jerome/fooproject/node_modules/webpack/lib/NormalModuleFactory.js:60:20)
    at asyncLib.parallel (/home/jerome/fooproject/node_modules/webpack/lib/NormalModuleFactory.js:127:20)
    at /home/jerome/fooproject/node_modules/webpack/node_modules/async/dist/async.js:3861:9
    at /home/jerome/fooproject/node_modules/webpack/node_modules/async/dist/async.js:421:16
    at iteratorCallback (/home/jerome/fooproject/node_modules/webpack/node_modules/async/dist/async.js:996:13)
    at /home/jerome/fooproject/node_modules/webpack/node_modules/async/dist/async.js:906:16

```

**If the current behavior is a bug, please provide the steps to reproduce.**

Write a file with a import with a wrong path, build with production options.

**What is the expected behavior?**

Webpack should not crash and show the error

**Comment by JSteunou** [comment]
thank you @sokra :+1:
