### ISSUE TITLE
WatchIgnorePlugin useless for files inside a watched directory #2156

### ISSUE THREAD

**Issue by umeboshi2** [webpack/webpack#5789]
**Do you want to request a *feature* or report a *bug*?**

I want to open an issue that was previously closed due to inactivity.

**What is the current behavior?**

Unknown.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

Being informed that an issue is resolved through activity.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Here is the workaround that I have been using.  Is it still necessary?

https://github.com/umeboshi2/dotfiles/blob/master/emacs#L189

**Comment by evilebottnawi** [comment]
@umeboshi2 problem still exists?

**Comment by umeboshi2** [comment]
I will adjust my emacs config and get right back to you.  Thanks! :)

**Comment by umeboshi2** [comment]
@evilebottnawi 
Yes, the problem still exists.  When an auto save file under a ```system.import``` directory is created the dev server rebuilds everything.  The original bug was autoclosed for no activity, which is why I opened this, but I didn't test.  After testing, the autosave file still triggers a rebuild.

**Comment by ChrisSG** [comment]
Try using a RegExp which exactly matches the directory, as a string as exclusion is also partially matched...

**Comment by evilebottnawi** [comment]
bump, need investigate, maybe problem in dev server

**Comment by aspiers** [comment]
As far as I can see, this is still an issue.

Please consider removing this auto-closer webpack-bot: https://www.reddit.com/r/emacs/comments/j9hi9x/an_example_of_why_bug_reports_and_feature/

It is very unhelpful and demotivating for users to have to resubmit a fresh issue for the same bug every few months.  In this case it appears that the bug has been around since 2016 or earlier: #2156.

**Comment by alexander-akait** [comment]
@aspiers Can you provide reproducible example?

**Comment by aspiers** [comment]
Unfortunately way too busy right now, but it's trivial to reproduce, simply set up `WatchIgnorePlugin` to ignore all files of the format `.#*`, then create `.#foo` and observe how it's not ignored.

**Comment by alexander-akait** [comment]
@aspiers Weird, I can't reproduce, my configuration - `new webpack.WatchIgnorePlugin({ paths: [/\.#*/] })`, what is webpack verison?

**Comment by aspiers** [comment]
That regexp looks wrong - shouldn't it be `/\.#.*/`?  But does it need to match the whole path, or is it a substring match?  If substring, it would need to contain a `/` just before the `\.#`.

**Comment by aspiers** [comment]
I'm running openSUSE Linux (Tumbleweed) with 5.64.2.

**Comment by alexander-akait** [comment]
> That regexp looks wrong - shouldn't it be /\.#.*/?

Based on this you want to ignore, if you have `.#foo`, `/\.#*/` is valid regexp, using `/\.#.*/` should ignore `.#foo.` (`.#foo.other-characters`), it is just regexp applied on whole path

**Comment by aspiers** [comment]
`/\.#*/` is not valid because the `*` only applies to the `#` character, therefore it will match `'.'`. We're dealing with regexps here, not globs - right? So we need `.*` rather than `*`.

**Comment by aspiers** [comment]
BTW with those plugin options (i.e. `paths`) I get:

```
yarn dev
yarn run v1.22.15
$ webpack --mode development --watch
Watch Ignore Plugin Invalid Options

options should be array

ValidationError: Watch Ignore Plugin Invalid Options
    at validateOptions (/home/adam/.GIT/3rd-party/reactime/node_modules/schema-utils/src/validateOptions.js:32:11)
    at new WatchIgnorePlugin (/home/adam/.GIT/3rd-party/reactime/node_modules/webpack/lib/WatchIgnorePlugin.js:92:3)
    at module.exports (/home/adam/.GIT/3rd-party/reactime/webpack.config.js:87:7)
    at handleFunction (/home/adam/.GIT/3rd-party/reactime/node_modules/webpack-cli/bin/utils/prepareOptions.js:21:13)
    at prepareOptions (/home/adam/.GIT/3rd-party/reactime/node_modules/webpack-cli/bin/utils/prepareOptions.js:9:5)
    at requireConfig (/home/adam/.GIT/3rd-party/reactime/node_modules/webpack-cli/bin/utils/convert-argv.js:117:14)
    at /home/adam/.GIT/3rd-party/reactime/node_modules/webpack-cli/bin/utils/convert-argv.js:123:17
    at Array.forEach (<anonymous>)
    at module.exports (/home/adam/.GIT/3rd-party/reactime/node_modules/webpack-cli/bin/utils/convert-argv.js:121:15)
    at /home/adam/.GIT/3rd-party/reactime/node_modules/webpack-cli/bin/cli.js:71:45
    at Object.parse (/home/adam/.GIT/3rd-party/reactime/node_modules/webpack-cli/node_modules/yargs/yargs.js:576:18)
    at /home/adam/.GIT/3rd-party/reactime/node_modules/webpack-cli/bin/cli.js:49:8
    at Object.<anonymous> (/home/adam/.GIT/3rd-party/reactime/node_modules/webpack-cli/bin/cli.js:366:3)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/adam/.GIT/3rd-party/reactime/node_modules/webpack/bin/webpack.js:156:2)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by aspiers** [comment]
You can reproduce with this tree: https://github.com/aspiers/reactime/commit/5adc4668de4dfb6cc1a4568dfdcb1a32f5758a46

Just run `yarn` and `yarn dev`, then create any file beginning with `.#` in the repo and you will see stuff like:

    Error: ENOENT: no such file or directory, stat '/home/adam/.GIT/3rd-party/reactime/src/backend/.#linkFiber.ts'

**Comment by aspiers** [comment]
I'm guessing it might be due to the old webpack version.

**Comment by alexander-akait** [comment]
> /\.#*/ is not valid because the * only applies to the # character, therefore it will match '.'. We're dealing with regexps here, not globs - right? So we need .* rather than *.

Oh, yes, my mistake, anyway `/\.#*/` is working, because it matches on `.#` (from `.#foo`)

Yes, you are using webpack v4, for webpack v5 we fixed the problem with `#` character and I can't reproduce it locally using the latest stable version

**Comment by aspiers** [comment]
Got it, thanks a lot!
