### ISSUE TITLE
Large amount of aliases causing "Maximum call stack size exceeded"

### ISSUE THREAD

**Issue by tomasAlabes** [webpack/webpack#5791]
**Do you want to request a *feature* or report a *bug*?**
Performance Bug

**What is the current behavior?**
When running webpack with 2050 aliases, I get this error:

```
>> /Volumes/Repositories/myProject/node_modules/tapable/lib/Tapable.js:257
>> 		plugins[i].call(_this, param, innerCallback);
>> 		           ^
>>
>> RangeError: Maximum call stack size exceeded
>>     at next (/Volumes/Repositories/myProject/node_modules/tapable/lib/Tapable.js:257:14)
>>     at Resolver.<anonymous> (/Volumes/Repositories/myProject/node_modules/enhanced-resolve/lib/ConcordModulesPlugin.js:23:28)
>>     at next (/Volumes/Repositories/myProject/node_modules/tapable/lib/Tapable.js:257:14)
>>     at Resolver.<anonymous> (/Volumes/Repositories/myProject/node_modules/enhanced-resolve/lib/AliasPlugin.js:55:10)
>>     at next (/Volumes/Repositories/myProject/node_modules/tapable/lib/Tapable.js:257:14)
>>     at Resolver.<anonymous> (/Volumes/Repositories/myProject/node_modules/enhanced-resolve/lib/AliasPlugin.js:55:10)
>>     at next (/Volumes/Repositories/myProject/node_modules/tapable/lib/Tapable.js:257:14)
>>     at Resolver.<anonymous> (/Volumes/Repositories/myProject/node_modules/enhanced-resolve/lib/AliasPlugin.js:55:10)
>>     at next (/Volumes/Repositories/myProject/node_modules/tapable/lib/Tapable.js:257:14)
>>     at Resolver.<anonymous> (/Volumes/Repositories/myProject/node_modules/enhanced-resolve/lib/AliasPlugin.js:55:10)
>>     at next (/Volumes/Repositories/myProject/node_modules/tapable/lib/Tapable.js:257:14)
>>     at Resolver.<anonymous> (/Volumes/Repositories/myProject/node_modules/enhanced-resolve/lib/AliasPlugin.js:55:10)
>>     at next (/Volumes/Repositories/myProject/node_modules/tapable/lib/Tapable.js:257:14)
>>     at Resolver.<anonymous> (/Volumes/Repositories/myProject/node_modules/enhanced-resolve/lib/AliasPlugin.js:55:10)
>>     at next (/Volumes/Repositories/myProject/node_modules/tapable/lib/Tapable.js:257:14)
>>     at Resolver.<anonymous> (/Volumes/Repositories/myProject/node_modules/enhanced-resolve/lib/AliasPlugin.js:55:10)
>>     at next (/Volumes/Repositories/myProject/node_modules/tapable/lib/Tapable.js:257:14)
>>     at Resolver.<anonymous> (/Volumes/Repositories/myProject/node_modules/enhanced-resolve/lib/AliasPlugin.js:55:10)
>>     at next (/Volumes/Repositories/myProject/node_modules/tapable/lib/Tapable.js:257:14)
>>     at Resolver.<anonymous> (/Volumes/Repositories/myProject/node_modules/enhanced-resolve/lib/AliasPlugin.js:55:10)
>>     at next (/Volumes/Repositories/myProject/node_modules/tapable/lib/Tapable.js:257:14)
>>     at Resolver.<anonymous> (/Volumes/Repositories/myProject/node_modules/enhanced-resolve/lib/AliasPlugin.js:55:10)
>>     at next (/Volumes/Repositories/myProject/node_modules/tapable/lib/Tapable.js:257:14)
>>     at Resolver.<anonymous> (/Volumes/Repositories/myProject/node_modules/enhanced-resolve/lib/AliasPlugin.js:55:10)
>>     at next (/Volumes/Repositories/myProject/node_modules/tapable/lib/Tapable.js:257:14)
>>     at Resolver.<anonymous> (/Volumes/Repositories/myProject/node_modules/enhanced-resolve/lib/AliasPlugin.js:55:10)
>>     at next (/Volumes/Repositories/myProject/node_modules/tapable/lib/Tapable.js:257:14)
>>     at Resolver.<anonymous> (/Volumes/Repositories/myProject/node_modules/enhanced-resolve/lib/AliasPlugin.js:55:10)
>>     at next (/Volumes/Repositories/myProject/node_modules/tapable/lib/Tapable.js:257:14)
>>     at Resolver.<anonymous> (/Volumes/Repositories/myProject/node_modules/enhanced-resolve/lib/AliasPlugin.js:55:10)
>> Exited with code: 1.
>> Error executing child process: Error: Process exited with code 1.
```

**If the current behavior is a bug, please provide the steps to reproduce.**
I can't provide the actual project but using that amount of aliases causes the error.

**What is the expected behavior?**
For the aliases to be analyzed in a way that doesn't make the process fail?

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
node 8.6.0
webpack 2.6.0
yarn 1.2.0
mac 10.12.6

**Comment by sokra** [comment]
@webpack-bot move to webpack/enhanced-resolve
