### ISSUE TITLE
webpack 3.8.0 reports WebpackOptionsValidationError on configuration.stats.errors

### ISSUE THREAD

**Issue by doberkofler** [webpack/webpack#5841]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
webpack 3.8.0 reports WebpackOptionsValidationError on `configuration.stats`when using the property `errors`

**If the current behavior is a bug, please provide the steps to reproduce.**
create a stats object containing the property `errors`

**What is the expected behavior?**
According to the documentation `errors` is still a valid option

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

CLI OUTPUT:
```
WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.stats should be one of these:
   object { context?, hash?, version?, timings?, assets?, env?, colors?, maxModules?, chunks?, chunkModules?, modules?, children?, cached?, cachedAssets?, reaso
ns?, source?, warningsFilter?, excludeAssets?, excludeModules?, exclude?, entrypoints?, errorDetails?, chunkOrigins?, modulesSort?, moduleTrace?, chunksSort?, a
ssetsSort?, publicPath?, providedExports?, usedExports?, optimizationBailout? } | boolean | "none" | "errors-only" | "minimal" | "normal" | "detailed" | "verbos
e"
   Used by the webpack CLI program to pass stats options.
   Details:
    * configuration.stats has an unknown property 'errors'. These properties are valid:
      object { context?, hash?, version?, timings?, assets?, env?, colors?, maxModules?, chunks?, chunkModules?, modules?, children?, cached?, cachedAssets?, re
asons?, source?, warningsFilter?, excludeAssets?, excludeModules?, exclude?, entrypoints?, errorDetails?, chunkOrigins?, modulesSort?, moduleTrace?, chunksSort?
, assetsSort?, publicPath?, providedExports?, usedExports?, optimizationBailout? }
    * configuration.stats has an unknown property 'warnings'. These properties are valid:
      object { context?, hash?, version?, timings?, assets?, env?, colors?, maxModules?, chunks?, chunkModules?, modules?, children?, cached?, cachedAssets?, re
asons?, source?, warningsFilter?, excludeAssets?, excludeModules?, exclude?, entrypoints?, errorDetails?, chunkOrigins?, modulesSort?, moduleTrace?, chunksSort?
, assetsSort?, publicPath?, providedExports?, usedExports?, optimizationBailout? }
    * configuration.stats should be a boolean.
    * configuration.stats should be one of these:
      "none" | "errors-only" | "minimal" | "normal" | "detailed" | "verbose"
    at webpack (D:\MyDev\ljs_app\trunk\periscope\build\node_modules\webpack\lib\webpack.js:19:9)
    at runWebPack (D:\MyDev\ljs_app\trunk\periscope\build\scripts\runWebpack.js:48:19)
    at buildCore (D:\MyDev\ljs_app\trunk\periscope\build\scripts\runWebpack.js:110:9)
    at D:\MyDev\ljs_app\trunk\periscope\build\scripts\runSequencially.js:51:11
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:667:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
Failed execution of command "build" after 40s
```

CONFIGURATION:
```
const WEBPACK_STATS = {
	// Add asset Information
	assets: true,
	// Sort assets by a field
	assetsSort: 'field',
	// Add information about cached (not built) modules
	cached: false,
	// Add children information
	children: false,
	// Add chunk information (setting this to `false` allows for a less verbose output)
	chunks: false,
	// Add built modules information to chunk information
	chunkModules: false,
	// Add the origins of chunks and chunk merging info
	chunkOrigins: false,
	// Sort the chunks by a field
	chunksSort: 'field',
	// Context directory for request shortening
	//context: '../src/',
	// `webpack --colors` equivalent
	colors: true,
	// Add errors
	errors: true,
	// Add details to errors (like resolving log)
	errorDetails: true,
	// Add the hash of the compilation
	hash: false,
	// Add built modules information
	modules: false,
	// Sort the modules by a field
	modulesSort: 'field',
	// Add public path information
	publicPath: false,
	// Add information about the reasons why modules are included
	reasons: false,
	// Add the source code of modules
	source: false,
	// Add timing information
	timings: true,
	// Add webpack version information
	version: true,
	// Add warnings
	warnings: true
};
```

**Comment by sokra** [comment]
update to 3.8.1

**Comment by doberkofler** [comment]
@sokra Wow that was fast. Thank you for all the good work!
