### ISSUE TITLE
ReferenceError: window is not defined     at Object.module.exports.t.__esModule 

### ISSUE THREAD

**Issue by avinashdvv** [webpack/webpack#5974]
ReferenceError: window is not defined at Object.module.exports.t.__esModule while making server side rendering react app 

**Do you want to request a *feature* or report a *bug*?**
neither of them just need help

**What is the current behavior?**
```
function r(e,t){if(!o.canUseDOM||t&&!("addEventListener"in document))return!1;var n="on"+e,r=n in document;if(!r){var i=document.createElement("div");i.setAttribute(n,"return;"),r="function"==typeof i[n]}return!r&&a&&"wheel"===e&&(r=document.implementation.hasFeature("Events.wheel","3.0")),r}var a,o=n(14);o.canUseDOM&&(a=document.implementation&&document.implementation.hasFeature&&!0!==document.implementation.hasFeature("","")),e.exports=r},function(e,t,n){"use strict";function r(e){var t=this,n=t.nativeEvent;if(n.getModifierState)return n.getModifierState(e);var r=o[e];return!!r&&!!n[r]}function a(e){return r}var o={Alt:"altKey",Control:"ctrlKey",Meta:"metaKey",Shift:"shiftKey"};e.exports=a},function(e,t,n){"use strict";function r(e,t){return Array.isArray(t)&&(t=t[1]),t?t.nextSibling:e.firstChild}function a(e,t,n){u.insertTreeBefore(e,t,n)}function o(e,t,n){Array.isArray(t)?s(e,t[0],t[1],n):h(e,t,n)}function i(e,t){if(Array.isArray(t)){var n=t[1];t=t[0

ReferenceError: window is not defined
    at Object.module.exports.t.__esModule (/home/nanohealth/Desktop/SEO_Nanohealth/server.js:106:24999)
    at t (/home/nanohealth/Desktop/SEO_Nanohealth/server.js:1:177)
    at Object.module.exports.Object.defi
```
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
build completing and serving server-side rendered HTML

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
node: 7.10
os: ubuntu 16.04
webpack: 3.8.1

webpack config: 
```
const webpack = require("webpack");
const ExtractTextPlugin = require("extract-text-webpack-plugin");
const autoprefixer = require("autoprefixer");

const browserConfig = {
  entry: "./src/server/index.js",
  output: {
    path: __dirname,
    filename: "./public/bundle.js"
  },
  devtool: "cheap-module-source-map",
  module: {
    rules: [
      {
        test: [/\.svg$/, /\.gif$/, /\.jpe?g$/, /\.png$/],
        loader: "file-loader",
        options: {
          name: "public/media/[name].[ext]",
          publicPath: url => url.replace(/public/, "")
        }
      },
      { 
        test: /\.(woff|woff2|eot|ttf)?$/,
        loader: 'url-loader?limit=100000',
        options: {
          name: "public/media/[name].[ext]",
          publicPath: url => url.replace(/public/, "")
        }
      },
      {
        test: /\.css$/,
        use: ExtractTextPlugin.extract({
          use: [
            {
              loader: "css-loader",
              options: { importLoaders: 1 }
            },
            {
              loader: "postcss-loader",
              options: { plugins: [autoprefixer()] }
            }
          ]
        })
      },
      {
        test: /\.scss$/,
        loader: 'style-loader!css-loader!sass-loader'
      },
      {
        test: /js$/,
        exclude: /(node_modules)/,
        loader: "babel-loader",
        query: { presets: ["react-app"] }
      }
    ]
  },
  plugins: [
    new ExtractTextPlugin({
      filename: "public/css/[name].css"
    })
  ]
};

const serverConfig = {
  entry: "./src/server/index.js",
  target: "node",
  node: {
    __filename: true,
    __dirname: true
  },
  output: {
    path: __dirname,
    filename: "server.js",
    libraryTarget: "commonjs2"
  },
  devtool: "cheap-module-source-map",
  module: {
    rules: [
      {
        test: [/\.svg$/, /\.gif$/, /\.jpe?g$/, /\.png$/],
        loader: "file-loader",
        options: {
          name: "public/media/[name].[ext]",
          publicPath: url => url.replace(/public/, ""),
          emit: false
        }
      },
      {
        test: /\.css$/,
        use: [
          {
            loader: "css-loader/locals"
          }
        ]
      },
      {
        test: /\.scss$/,
        loader: 'style-loader!css-loader!sass-loader'
      },
      {
        test: /js$/,
        exclude: /(node_modules)/,
        loader: "babel-loader",
        query: { presets: ["react-app"] }
      }
    ]
  }
};


module.exports = [browserConfig,serverConfig]
```

**Comment by sokra** [comment]
`window is not defined` in a server bundle. There is no window object when doing serverside rendering. You need to write your code to be aware of this.

Please submit support requests and questions to StackOverflow using the tag [[webpack]](http://stackoverflow.com/tags/webpack). StackOverflow is better suited for this kind of support. The issue tracker is for bug reports and feature discussions. See also [our CONTRIBUTING guidelines](https://github.com/webpack/webpack/blob/master/CONTRIBUTING.md).
