### ISSUE TITLE
Error when run de server

### ISSUE THREAD

**Issue by LuisBonsembiante** [webpack/webpack#6066]
**Do you want to request a *feature* or report a *bug*?**
is a bug

**What is the current behavior?**
ive ...odules/@angular/common/esm5/common.jsError: No module factory available for dependency type: ContextElementDependency
    at Compilation.addModuleDependencies (/home/luis/Proyectos/aconcagua/Folder/aconcagua-ui/node_modules/@angular/cli/node_modules/webpack/lib/Compilation.js:215:21)
    at Compilation.processModuleDependencies (/home/luis/Proyectos/aconcagua/Folder/aconcagua-ui/node_modules/@angular/cli/node_modules/webpack/lib/Compilation.js:204:8)
    at _this.buildModule.err (/home/luis/Proyectos/aconcagua/Folder/aconcagua-ui/node_modules/@angular/cli/node_modules/webpack/lib/Compilation.js:359:14)
    at building.forEach.cb (/home/luis/Proyectos/aconcagua/Folder/aconcagua-ui/node_modules/@angular/cli/node_modules/webpack/lib/Compilation.js:149:27)
    at Array.forEach (native)

**If the current behavior is a bug, please provide the steps to reproduce.**
execute npm start

**Comment by sokra** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by EugeneHlushko** [comment]
Hi @LuisBonsembiante if you do set up a reproduction repo pls ping me i might look into it this weekend.

**Comment by Philip-Sultanescu** [comment]
Problem appears from 3.9.0+, it doesn't appear in 3.8.1

Here is my package.json
  "dependencies": {
    "@angular/animations": "5.0.5",
    "@angular/cdk": "5.0.0-rc.2",
    "@angular/common": "5.0.5",
    "@angular/compiler": "5.0.5",
    "@angular/core": "5.0.5",
    "@angular/flex-layout": "2.0.0-beta.10-4905443",
    "@angular/forms": "5.0.5",
    "@angular/http": "5.0.5",
    "@angular/material": "5.0.0-rc.2",
    "@angular/platform-browser": "5.0.5",
    "@angular/platform-browser-dynamic": "5.0.5",
    "@angular/router": "5.0.5",
    "@ngx-translate/core": "9.0.1",
    "@ngx-translate/http-loader": "2.0.0",
    "@types/google-maps": "3.2.0",
    "angular-2-local-storage": "1.0.1",
    "bootstrap-sass": "3.3.7",
    "bootstrap-select": "1.12.4",
    "bootstrap-slider": "10.0.0",
    "core-js": "2.5.1",
    "country-data": "0.0.31",
    "jquery": "3.2.1",
    "moment": "2.19.3",
    "ng2-file-upload": "1.3.0",
    "ngmap": "1.18.4",
    "ngx-bootstrap": "2.0.0-beta.9",
    "ngx-chips": "1.5.11",
    "ramda": "0.25.0",
    "rxjs": "5.5.3",
    "stylelint": "8.3.1",
    "ts-helpers": "1.1.2",
    "uploadcare-widget": "3.2.1",
    "zone.js": "0.8.18"
  },
  "devDependencies": {
    "@angular/cli": "1.5.5",
    "@angular/compiler-cli": "5.0.5",
    "@reactivex/rxjs": "5.5.3",
    "@types/jasmine": "2.8.2",
    "@types/node": "8.0.54",
    "@types/ramda": "0.25.6",
    "codelyzer": "4.0.1",
    "jasmine-core": "2.8.0",
    "jasmine-spec-reporter": "4.2.1",
    "karma": "1.7.1",
    "karma-chrome-launcher": "2.2.0",
    "karma-cli": "1.0.1",
    "karma-coverage-istanbul-reporter": "1.3.0",
    "karma-jasmine": "1.1.1",
    "karma-jasmine-html-reporter": "0.2.2",
    "karma-remap-istanbul": "0.6.0",
    "protractor": "5.2.0",
    "ts-node": "3.3.0",
    "tslint": "5.8.0",
    "typescript": "2.4.2",
    "webpack": "3.9.0"
  }
