### ISSUE TITLE
TypeError: Cannot read property 'message' of undefined

### ISSUE THREAD

**Issue by markgoho-EDT** [webpack/webpack#6303]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I'm using the Angular CLI to build a project. When I `ng serve` the build starts to compile and then stops abruptly with this error:

``` bash
C:\Users\Nella\Documents\EDT\app-copa\node_modules\webpack\lib\Compilation.js:1313
                        hash.update(`${error.message}`);
                                             ^

TypeError: Cannot read property 'message' of undefined
    at C:\Users\Nella\Documents\EDT\app-copa\node_modules\webpack\lib\Compilation.js:1313:25
    at Array.forEach (<anonymous>)
    at Compilation.createHash (C:\Users\Nella\Documents\EDT\app-copa\node_modules\webpack\lib\Compilation.js:1312:15)
    at sealPart2 (C:\Users\Nella\Documents\EDT\app-copa\node_modules\webpack\lib\Compilation.js:645:9)
    at next (C:\Users\Nella\Documents\EDT\app-copa\node_modules\tapable\lib\Tapable.js:202:11)
    at Compilation.compilation.plugin (C:\Users\Nella\Documents\EDT\app-copa\node_modules\webpack\lib\ProgressPlugin.js:111:6)
    at Compilation.applyPluginsAsyncSeries (C:\Users\Nella\Documents\EDT\app-copa\node_modules\tapable\lib\Tapable.js:206:13)
    at Compilation.seal (C:\Users\Nella\Documents\EDT\app-copa\node_modules\webpack\lib\Compilation.js:605:8)
    at applyPluginsParallel.err (C:\Users\Nella\Documents\EDT\app-copa\node_modules\webpack\lib\Compiler.js:504:17)
    at C:\Users\Nella\Documents\EDT\app-copa\node_modules\tapable\lib\Tapable.js:289:11
    at _addModuleChain (C:\Users\Nella\Documents\EDT\app-copa\node_modules\webpack\lib\Compilation.js:507:11)
    at processModuleDependencies.err (C:\Users\Nella\Documents\EDT\app-copa\node_modules\webpack\lib\Compilation.js:477:14)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
I would expect the build to complete and show errors at the end.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Angular CLI v. 1.6.4
Webpack 3.10.0

**Comment by nechita** [comment]
hey @markgoho-EDT I'm getting the same error. Did you manage to find a fix?

**Comment by evilebottnawi** [comment]
@markgoho-EDT @nechita Can you create minimum reproducible test repo?

**Comment by nechita** [comment]
@evilebottnawi unfortunately, it's been such a long time I don't even remember what was the issue. You can ignore my comment. I probably upgraded to a new angular cli version and that issue was gone.
