### ISSUE TITLE
npm build fails

### ISSUE THREAD

**Issue by JulienDemarque** [webpack/webpack#6323]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**
npm build sends an error

![screen shot 2018-01-16 at 12 33 20](https://user-images.githubusercontent.com/27313954/34984401-87639e92-fab9-11e7-996e-9618c92108d0.png)
**If the current behavior is a bug, please provide the steps to reproduce.**

followed the getting started tutorial until npm script
Here is the github repo: https://github.com/JulienDemarque/webpack-demo

**What is the expected behavior?**
building the bundle again

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
node v6.11.1
webpack@3.10.0 
os sierra 10.12.6

**Comment by sokra** [comment]
Did you run `npm install`?

**Comment by JulienDemarque** [comment]
Yes. 
Here is what the node_modules folder look like:
 
![screen shot 2018-01-16 at 17 13 17](https://user-images.githubusercontent.com/27313954/34995902-9902513a-fae0-11e7-87a7-7225854d8326.png)

![screen shot 2018-01-16 at 17 12 03](https://user-images.githubusercontent.com/27313954/34995874-7b75b260-fae0-11e7-9167-a024e0212300.png)

**Comment by evilebottnawi** [comment]
@JulienDemarque `ls -l node_modules/.bin/`?

**Comment by JulienDemarque** [comment]
Here it is:

![screen shot 2018-01-16 at 17 19 34](https://user-images.githubusercontent.com/27313954/34996177-7c82c296-fae1-11e7-846d-2d19f94e0012.png)

**Comment by evilebottnawi** [comment]
@JulienDemarque don't reproducible locally using you repo, seems you have problem in you shell (`sh`)

**Comment by JulienDemarque** [comment]
npx webpack --config webpack.config.js works fine. Only the npm scripts tags fails...

**Comment by JulienDemarque** [comment]
I had a similar issue with create-react-app. Any idea how to fix the problem? (except changing computer... :) )

**Comment by JulienDemarque** [comment]
I just tried with bash, sh and zsh. Still got the same result... :/

**Comment by evilebottnawi** [comment]
@JulienDemarque try to reinstall node and npm

**Comment by JulienDemarque** [comment]
I reinstalled node and npm. Still not helping...

**Comment by ooflorent** [comment]
@JulienDemarque could you include the **NPM log** and the output of the following commands:

```sh
node -v
npm -v

**Comment by JulienDemarque** [comment]
[2018-01-17T15_49_02_075Z-debug.log](https://github.com/webpack/webpack/files/1639629/2018-01-17T15_49_02_075Z-debug.log)

node v8.9.4
npm v5.6.0

I tried previously with node v6.11.1. It wasn't working either.

**Comment by stormpat** [comment]
I have the same issue. I think this behaviour was introduced with upgrading my osx deps (via homebrew)

I have a npm script i use for a alias like so:
```"compress": "./node_modules/.bin/webpack -p --env=production"``` 

The same command CAN successfully be run from the terminal, but when running it via npm i get errors:

``` 
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/9.4.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'compress' ]
2 info using npm@5.6.0
3 info using node@v9.4.0
4 verbose run-script [ 'precompress', 'compress', 'postcompress' ]
5 info lifecycle myproject@1.0.0~precompress: myproject@1.0.0
6 info lifecycle myproject@1.0.0~compress: myproject@1.0.0
7 verbose lifecycle myproject@1.0.0~compress: unsafe-perm in lifecycle true
8 verbose lifecycle myproject@1.0.0~compress: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/pat/Vagrant/myproject/node_modules/.bin:/usr/local/opt/node@8/bin:/Users/pat/Flutter/flutter/bin:/Users/pat/.composer/vendor/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:~/.pub-cache/bin
9 verbose lifecycle myproject@1.0.0~compress: CWD: /Users/pat/Vagrant/myproject
10 silly lifecycle myproject@1.0.0~compress: Args: [ '-c', 'webpack -p --env=production' ]
11 silly lifecycle myproject@1.0.0~compress: Returned: code: 2  signal: null
12 info lifecycle myproject@1.0.0~compress: Failed to exec compress script
13 verbose stack Error: myproject@1.0.0 compress: `webpack -p --env=production`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at EventEmitter.emit (events.js:160:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:160:13)
13 verbose stack     at maybeClose (internal/child_process.js:943:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid myproject@1.0.0
15 verbose cwd /Users/pat/Vagrant/myproject
16 verbose Darwin 17.3.0
17 verbose argv "/usr/local/Cellar/node/9.4.0/bin/node" "/usr/local/bin/npm" "run" "compress"
18 verbose node v9.4.0
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 2
22 error myproject@1.0.0 compress: `webpack -p --env=production`
22 error Exit status 2
23 error Failed at the myproject@1.0.0 compress script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]
``` 

``` 
> npm --version => 5.6.0
> node --version => v9.4.0
``` 
To make things more weird, i CAN run other npm script successfully. It seems webpack related script are the only ones that does not work.

I have re-installed npm/node and removed node_modules a few times without success.

**Comment by ThomasLeveque** [comment]
up

**Comment by czelusniakdawid** [comment]
Hi,

Unfortunately, I am getting the same error when running Webpack on Node 9.5.0 on Debian 9 stretch. Could you help me with debugging this issue?

Webpack: **3.7.1**
npm: **5.6.0**
Node: **9.5.0**
Debian: **9.3.0**

My command:
```
./node_modules/webpack/bin/webpack.js -p --progress
```

**Error:**
```
Error: write EPIPE
    at _errnoException (util.js:1003:13)
    at WriteWrap.afterWrite [as oncomplete] (net.js:866:14)
```

**Logs:**
```
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at EventEmitter.emit (events.js:160:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:160:13)
13 verbose stack     at maybeClose (internal/child_process.js:943:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
```

Thank you in advance :smiley:

**Comment by ooflorent** [comment]
@JulienDemarque @czelusniakdawid It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by ccmcbeck** [comment]
FWIW, I had a similar issue in that I got the same log messages from `npm run build`.  My issue was a "failure to minify" the `query-string` NPM module becuase it was not ES5 compatible.  Once we swiched to the `qs` module, the error went away.  Here is a link explaining https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify

**Comment by trkaplan** [comment]
You can try updating the system variables mentioned in these answers:
https://github.com/react-community/create-react-native-app/issues/533#issuecomment-410956284 https://github.com/react-community/create-react-native-app/issues/533#issuecomment-417245119
