### ISSUE TITLE
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.

### ISSUE THREAD

**Issue by ThomasLeveque** [webpack/webpack#6469]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
npm run prod sens an error
![capture](https://user-images.githubusercontent.com/29226450/36051989-38fb421e-0dec-11e8-9d87-f20a9df4d214.PNG)

**If the current behavior is a bug, please provide the steps to reproduce.**
i have followed the next french tutorial : https://www.grafikart.fr/formations/webpack/configuration
 but the bug might comes from something i have made after it because at the end of the tutorial everything was ok

**What is the expected behavior?**
clean the dist folder and generate manifest.json contains js, css and all my pictures with an hash

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Node v8.9.1
Webpack ^3.10.0
npm 5.5.1

Webpack debug file : 
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'prod' ]
2 info using npm@5.5.1
3 info using node@v8.9.1
4 verbose run-script [ 'preprod', 'prod', 'postprod' ]
5 info lifecycle demo@1.0.0~preprod: demo@1.0.0
6 info lifecycle demo@1.0.0~prod: demo@1.0.0
7 verbose lifecycle demo@1.0.0~prod: unsafe-perm in lifecycle true
8 verbose lifecycle demo@1.0.0~prod: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\leveque\Documents\www\Twig\node_modules\.bin;C:\Users\leveque\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\leveque\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\Sennheiser\SoftphoneSDK;C:\Program Files\Google\Google Apps Sync;C:\Program Files\Google\Google Apps Migration;C:\Program Files\Git\cmd;C:\xampp\php;C:\Users\leveque;C:\ProgramData\ComposerSetup\bin;C:\Program Files\nodejs;C:\Ruby24-x64\bin;C:\Users\leveque\AppData\Local\Microsoft\WindowsApps;C:\Users\leveque\AppData\Roaming\Composer\vendor\bin;C:\Users\leveque\AppData\Roaming\npm;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
9 verbose lifecycle demo@1.0.0~prod: CWD: C:\Users\leveque\Documents\www\Twig
10 silly lifecycle demo@1.0.0~prod: Args: [ '/d /s /c', 'webpack' ]
11 silly lifecycle demo@1.0.0~prod: Returned: code: 1  signal: null
12 info lifecycle demo@1.0.0~prod: Failed to exec prod script
13 verbose stack Error: demo@1.0.0 prod: `webpack`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:280:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid demo@1.0.0
15 verbose cwd C:\Users\leveque\Documents\www\Twig
16 verbose Windows_NT 10.0.15063
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "prod"
18 verbose node v8.9.1
19 verbose npm  v5.5.1
20 error code ELIFECYCLE
21 error errno 1
22 error demo@1.0.0 prod: `webpack`
22 error Exit status 1
23 error Failed at the demo@1.0.0 prod script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

Thx a lot guys !!!

**Comment by EugeneHlushko** [comment]
Did you check possible misconfiguration as the error states? What do you pass to `devtool` in the faulty configuration?

**Comment by codetheorist** [comment]
@ThomasLeveque Would you be able to post a gist to your actual config file please?
