### ISSUE TITLE
Webpack 4 - Plugin could not be registered at 'html-webpack-plugin-alter-asset-tags'. Hook was not found.

### ISSUE THREAD

**Issue by danshmidt77** [webpack/webpack#6481]
No, bug report.

version 4

**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

C:\workspace\ProovFE_V2\node_modules\tapable\lib\Tapable.js:63
                throw new Error(`Plugin could not be registered at '${name}'. Hook was not found.\n` +
                ^

Error: Plugin could not be registered at 'html-webpack-plugin-alter-asset-tags'. Hook was not found.
BREAKING CHANGE: There need to exist a hook at 'this.hooks'. To create a compatiblity layer for this hook, hook into 'this._pluginCompat'.
    at Compilation.plugin (C:\workspace\ProovFE_V2\node_modules\tapable\lib\Tapable.js:63:9)
    at Compilation.deprecated [as plugin] (internal/util.js:47:15)
    at compiler.plugin.compilation (C:\workspace\ProovFE_V2\node_modules\inline-chunk-manifest-html-webpack-plugin\src\index.js:63:19)
    at SyncHook.eval (eval at create (C:\workspace\ProovFE_V2\node_modules\tapable\lib\HookCodeFactory.js:17:12), <anonymous>:21:1)
    at SyncHook.lazyCompileHook [as _call] (C:\workspace\ProovFE_V2\node_modules\tapable\lib\Hook.js:35:21)
    at Compiler.newCompilation (C:\workspace\ProovFE_V2\node_modules\webpack\lib\Compiler.js:407:26)
    at hooks.beforeCompile.callAsync.err (C:\workspace\ProovFE_V2\node_modules\webpack\lib\Compiler.js:439:29)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\workspace\ProovFE_V2\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (C:\workspace\ProovFE_V2\node_modules\tapable\lib\Hook.js:35:21)
    at Compiler.compile (C:\workspace\ProovFE_V2\node_modules\webpack\lib\Compiler.js:434:28)
    at compiler.hooks.watchRun.callAsync.err (C:\workspace\ProovFE_V2\node_modules\webpack\lib\Watching.js:76:18)
    at _err0 (eval at create (C:\workspace\ProovFE_V2\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:11:1)
    at compilerInvalid (C:\workspace\ProovFE_V2\node_modules\webpack-dev-middleware\lib\Shared.js:161:5)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\workspace\ProovFE_V2\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:7:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (C:\workspace\ProovFE_V2\node_modules\tapable\lib\Hook.js:35:21)
    at Watching._go (C:\workspace\ProovFE_V2\node_modules\webpack\lib\Watching.js:39:32)
    at Watching.compiler.readRecords.err (C:\workspace\ProovFE_V2\node_modules\webpack\lib\Watching.js:31:9)
    at Compiler.readRecords (C:\workspace\ProovFE_V2\node_modules\webpack\lib\Compiler.js:331:11)
    at new Watching (C:\workspace\ProovFE_V2\node_modules\webpack\lib\Watching.js:28:17)
    at Compiler.watch (C:\workspace\ProovFE_V2\node_modules\webpack\lib\Compiler.js:161:10)
    at Object.startWatch (C:\workspace\ProovFE_V2\node_modules\webpack-dev-middleware\lib\Shared.js:176:29)
    at Shared (C:\workspace\ProovFE_V2\node_modules\webpack-dev-middleware\lib\Shared.js:238:8)

**Comment by niieani** [comment]
As you can see from the 3rd line of your stacktrace:

```
at compiler.plugin.compilation (...\node_modules\inline-chunk-manifest-html-webpack-plugin\src\index.js:63:19)
```

this is not a Webpack issue. Please open an issue at https://github.com/jouni-kantola/inline-chunk-manifest-html-webpack-plugin so the plugin can be upgraded.

**Comment by michael-ciniawsky** [comment]
https://github.com/jantimon/html-webpack-plugin/pull/823 `webpack >= v4.0.0` support is pending atm

**Comment by ooflorent** [comment]
As @niieani said, the issue is related to a 3rd party plugin.
You can follow the resolution progress on https://github.com/jouni-kantola/inline-chunk-manifest-html-webpack-plugin/issues/23

**Comment by juanmendes** [comment]
Similar problem, caused by webpack-concat-plugin, upgrading to latest fixes it.

**Comment by Hongbo-Miao** [comment]
My case is caused by an old plugin `html-webpack-inline-chunk-plugin` which does not support Webpack 4. Once removing it, the error is gone.
