### ISSUE TITLE
Bug: "DeprecationWarning: Tapable.apply is deprecated. Call apply on the plugin directly instead" for ProgressPlugin

### ISSUE THREAD

**Issue by osya** [webpack/webpack#6643]
**Do you want to request a *feature* or report a *bug*?**
I suppose it is a Bug

Asks in https://gitter.im/webpack/webpack, https://gitter.im/webpack/webpack/dev, https://stackoverflow.com/questions/49049432/webpack-deprecationwarning-tapable-apply-is-deprecated-for-internal-webpack-p

**What is the current behavior?**
```
webpack --progress

 10% building modules 2/2 modules 0 active(node:18628) DeprecationWarning: Tapable.apply is deprecated. Call apply on the Hash: 31a5c2e9ae4b0e57dc59Version: webpack 4.0.1
```
**If the current behavior is a bug, please provide the steps to reproduce.**
This issue is just about deprecation warning appears when `webpack --progress` launched. It concerns to internal Webpack plugin ProgressPlugin

This warnings appears without any webpack configuration. Just run `webpack --progress`

As I understand, this issue concerns ProgressPlugin, which is located in the Webpack repo

**What is the expected behavior?**
I expected no any deprecation warnings for internal Webpack plugins

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
Chrome 64.0
Node.js: 8.9.4
Webpack: 4.0.1
Windows 10 x64 Pro

**Comment by ooflorent** [comment]
@webpack-bot move to webpack/webpack-cli

**Comment by ndiyansah** [comment]
not solve

**Comment by ueeieiie** [comment]
@ndiyansah 

Do you have `--progress` in your running script? if so, try to remove it.

**Comment by sergey-shpak** [comment]
@ndiyansah solved for me with "webpack-cli": "^2.0.11"

**Comment by osya** [comment]
Yes, upgrading "webpack-cli" to "^2.0.11" solves it

**Comment by tsaiDavid** [comment]
I'm seeing this issue with the following:

* `"webpack": "^4.2.0"`
* `"webpack-cli": "^2.0.13"`
* `"webpack-dev-server": "^3.1.1"`

**Comment by Bezilon** [comment]
This is what I get when I run into the same issue:

`DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
 10% building modules 4/12 modules 8 active ...talokuntoon/src/stylesheets/main.scss(node:63668) DeprecationWarning: Tapable.apply is deprecated. Call apply on the plugin directly instead
 77% module and chunk tree optimization unnamed compat plugin
/Users/bezilon/talokuntoon/node_modules/webpack/lib/Chunk.js:468
		throw new Error(
        ^
Error: Chunk.entrypoints: Use Chunks.groupsIterable and filter by instanceof Entrypoint instead
    at Chunk.get (/Users/bezilon/talokuntoon/node_modules/webpack/lib/Chunk.js:468:9)
    at /Users/bezilon/talokuntoon/node_modules/extract-text-webpack-plugin/dist/index.js:176:47
    at Array.forEach (native)
    at /Users/bezilon/talokuntoon/node_modules/extract-text-webpack-plugin/dist/index.js:171:18
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/bezilon/talokuntoon/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:12:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/Users/bezilon/talokuntoon/node_modules/webpack/node_modules/tapable/lib/Hook.js:35:21)
    at Compilation.seal (/Users/bezilon/talokuntoon/node_modules/webpack/lib/Compilation.js:884:27)
    at hooks.make.callAsync.err (/Users/bezilon/talokuntoon/node_modules/webpack/lib/Compiler.js:482:17)
    at _done (eval at create (/Users/bezilon/talokuntoon/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:9:1)
    at _err1 (eval at create (/Users/bezilon/talokuntoon/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:32:22)
    at _addModuleChain (/Users/bezilon/talokuntoon/node_modules/webpack/lib/Compilation.js:752:12)
    at processModuleDependencies.err (/Users/bezilon/talokuntoon/node_modules/webpack/lib/Compilation.js:691:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)`

**Comment by ooflorent** [comment]
@Bezilon `extract-text-webpack-plugin` is deprecated for handling CSS in webpack 4. That's why you got the deprecation warning. Try using `mini-css-extract-plugin` instead.

**Comment by Bezilon** [comment]
Great, would be awesome if it was mentioned somehow here I guess or in some other migration notes:
https://webpack.js.org/guides/migrating/#extracttextplugin-extract

**Comment by montogeek** [comment]
@Bezilon Create an issue on https://github.com/webpack/webpack.js.org please
