### ISSUE TITLE
TypeError: Cannot read property 'outputOptions' of undefined

### ISSUE THREAD

**Issue by wojtekmaj** [webpack/webpack#6792]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Build fails. 

```shell
$ webpack --env.app=pdf
(node:7276) DeprecationWarning: Tapable.apply is deprecated. Call apply on the plugin directly instead
(node:7276) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
C:\Users\wojte\Projekty\react-pdf\node_modules\webpack\lib\webworker\WebWorkerMainTemplatePlugin.js:97
                        hash.update(`${this.outputOptions.publicPath}`);
                                            ^

TypeError: Cannot read property 'outputOptions' of undefined
    at C:\Users\wojte\Projekty\react-pdf\node_modules\webpack\lib\webworker\WebWorkerMainTemplatePlugin.js:97:24
    at SyncHook.eval [as call] (eval at create (C:\Users\wojte\Projekty\Project showcase\node_modules\tapable\lib\HookCodeFactory.js:17:12), <anonymous>:7:1)
    at SyncHook.lazyCompileHook [as _call] (C:\Users\wojte\Projekty\Project showcase\node_modules\tapable\lib\Hook.js:35:21)
    at MainTemplate.updateHash (C:\Users\wojte\Projekty\Project showcase\node_modules\webpack\lib\MainTemplate.js:390:19)
    at Compilation.createHash (C:\Users\wojte\Projekty\Project showcase\node_modules\webpack\lib\Compilation.js:1647:21)
    at hooks.optimizeTree.callAsync.err (C:\Users\wojte\Projekty\Project showcase\node_modules\webpack\lib\Compilation.js:924:9)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\wojte\Projekty\Project showcase\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (C:\Users\wojte\Projekty\Project showcase\node_modules\tapable\lib\Hook.js:35:21)
    at Compilation.seal (C:\Users\wojte\Projekty\Project showcase\node_modules\webpack\lib\Compilation.js:881:27)
    at hooks.make.callAsync.err (C:\Users\wojte\Projekty\Project showcase\node_modules\webpack\lib\Compiler.js:464:17)
    at _err0 (eval at create (C:\Users\wojte\Projekty\Project showcase\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:11:1)
    at _addModuleChain (C:\Users\wojte\Projekty\Project showcase\node_modules\webpack\lib\Compilation.js:749:12)
    at processModuleDependencies.err (C:\Users\wojte\Projekty\Project showcase\node_modules\webpack\lib\Compilation.js:688:9)
    at process._tickCallback (internal/process/next_tick.js:150:11)
error An unexpected error occurred: "Command failed.
Exit code: 1
Command: C:\\WINDOWS\\system32\\cmd.exe
Arguments: /d /s /c webpack --env.app=pdf
```

As you can see, I actually build several "apps" with one config, and app is an env variable. Interestingly, only one of these variables fail. The only difference I can see is that pdf app uses [this file](https://github.com/mozilla/pdf.js/blob/99060e2485cacb8513e7bc50d88b70101069b1c9/external/dist/webpack.js). This makes me wonder if that should be filed against worker-loader, but it is nowhere mentioned in this particular error stack.

The first two lines of call stack are the most interesting ones - as you can see, it actually seemed to jump from one webpack to another, and indeed react-pdf has webpack 3.x in its dependencies. Interestingly, this caused another error:

```shell
$ webpack --env.app=pdf
Hash: 9d98738b1866ccee2b7a
Version: webpack 4.1.1
Time: 28419ms
Built at: 2018-3-19 01:43:36
 8 assets
Entrypoint main = bundle.js
  [12] C:/Users/wojte/Projekty/react-pdf/dist/shared/utils.js 7.84 KiB {2} [built]
 [109] ./pdf/config.json 174 bytes {2} [built]
(truncated)
 [178] ./style.less 1.2 KiB {2} [built]
 [373] C:/Users/wojte/Projekty/react-pdf/dist/entry.webpack.js 1.2 KiB {2} [built]
 [384] ./pdf/index.jsx 4.97 KiB {2} [built]
    + 411 hidden modules

ERROR in C:/Users/wojte/Projekty/react-pdf/node_modules/worker-loader/dist/cjs.js!C:/Users/wojte/Projekty/react-pdf/node_modules/pdfjs-dist/build/pdf.worker.js
Module build failed: Error: Cannot find module 'webpack/lib/node/NodeTargetPlugin'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (C:\Users\wojte\Projekty\Project showcase\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (C:\Users\wojte\Projekty\react-pdf\node_modules\worker-loader\dist\index.js:21:25)
    at Module._compile (C:\Users\wojte\Projekty\Project showcase\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (C:\Users\wojte\Projekty\Project showcase\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (C:\Users\wojte\Projekty\react-pdf\node_modules\worker-loader\dist\cjs.js:3:14)
    at Module._compile (C:\Users\wojte\Projekty\Project showcase\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (C:\Users\wojte\Projekty\Project showcase\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at loadLoader (C:\Users\wojte\Projekty\Project showcase\node_modules\loader-runner\lib\loadLoader.js:13:17)
    at iteratePitchingLoaders (C:\Users\wojte\Projekty\Project showcase\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at runLoaders (C:\Users\wojte\Projekty\Project showcase\node_modules\loader-runner\lib\LoaderRunner.js:362:2)
    at NormalModule.doBuild (C:\Users\wojte\Projekty\Project showcase\node_modules\webpack\lib\NormalModule.js:219:3)
    at NormalModule.build (C:\Users\wojte\Projekty\Project showcase\node_modules\webpack\lib\NormalModule.js:337:15)
    at Compilation.buildModule (C:\Users\wojte\Projekty\Project showcase\node_modules\webpack\lib\Compilation.js:346:10)
    at factory.create (C:\Users\wojte\Projekty\Project showcase\node_modules\webpack\lib\Compilation.js:572:15)
    at factory (C:\Users\wojte\Projekty\Project showcase\node_modules\webpack\lib\NormalModuleFactory.js:366:6)
    at hooks.afterResolve.callAsync (C:\Users\wojte\Projekty\Project showcase\node_modules\webpack\lib\NormalModuleFactory.js:143:13)
    at AsyncSeriesWaterfallHook.eval [as callAsync] (eval at create (C:\Users\wojte\Projekty\Project showcase\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:18:1)
    at resolver (C:\Users\wojte\Projekty\Project showcase\node_modules\webpack\lib\NormalModuleFactory.js:126:29)
    at process.nextTick (C:\Users\wojte\Projekty\Project showcase\node_modules\webpack\lib\NormalModuleFactory.js:304:9)
    at process._tickCallback (internal/process/next_tick.js:150:11)
 @ C:/Users/wojte/Projekty/react-pdf/node_modules/pdfjs-dist/webpack.js 18:18-64
 @ C:/Users/wojte/Projekty/react-pdf/dist/entry.webpack.js
 @ ./pdf/index.jsx
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
       [3] ../node_modules/html-webpack-plugin/lib/loader.js!./index.html 1.15 KiB {0} [built]
        + 3 hidden modules
error An unexpected error occurred: "Command failed.
Exit code: 2
Command: C:\\WINDOWS\\system32\\cmd.exe
Arguments: /d /s /c webpack --env.app=pdf
```

Now we have a problem in worker-loader instead. Double checked the version and it's the newest 1.1.1 that should be supporting Webpack 4.x. What's going on?

**What is the expected behavior?**

* Webpack should not jump to another copies of itself if found somewhere else in the directory tree (perhaps the issue here is with using symlinks).
* worker-loader should be working okay with Webpack 4.x

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

Node.js: 9.x
Webpack: 
affected: 4.1.1
not affected: 3.11.0
OS: Windows 10 Spring Creators Update

**Comment by ooflorent** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by fredley** [comment]
I have an example of this which I originally [logged](https://github.com/webpack-contrib/worker-loader/issues/129) on the worker-loader contrib package, but it seems it should actually be here:

[TS 2.6.2, webpack 4.0.0, worker-loader 1.1.1]

**App.ts**

```import WorkerOne = require("worker-loader?inline!./workers/WorkerOne")```

**Elsewhere.ts**

```import WorkerTwo = require("worker-loader?inline!./workers/WorkerTwo")```

**custom.d.ts**

```
declare module "worker-loader?inline!*" {
  export class WorkerOne extends Worker {
    constructor();
  }

  export class WorkerTwo extends Worker {
    constructor();
  }
}
```

I have nothing related to `worker-loader` in `webpack.config.json`. My worker files are simply called WorkerOne.ts and WorkerTwo.ts. 

When I try and build:

```
(node:4566) DeprecationWarning: Tapable.apply is deprecated. Call apply on the plugin directly instead
(node:4566) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
/Users/fredley/dev/frontend/node_modules/webpack/lib/webworker/WebWorkerMainTemplatePlugin.js:100
			hash.update(`${this.outputOptions.publicPath}`);
			                    ^

TypeError: Cannot read property 'outputOptions' of undefined
    at /Users/fredley/dev/frontend/node_modules/webpack/lib/webworker/WebWorkerMainTemplatePlugin.js:100:24
    at SyncHook.eval [as call] (eval at create (/usr/local/lib/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:17:12), <anonymous>:7:1)
    at SyncHook.lazyCompileHook [as _call] (/usr/local/lib/node_modules/webpack/node_modules/tapable/lib/Hook.js:35:21)
    at MainTemplate.updateHash (/usr/local/lib/node_modules/webpack/lib/MainTemplate.js:390:19)
    at Compilation.createHash (/usr/local/lib/node_modules/webpack/lib/Compilation.js:1647:21)
    at hooks.optimizeTree.callAsync.err (/usr/local/lib/node_modules/webpack/lib/Compilation.js:924:9)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/usr/local/lib/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/usr/local/lib/node_modules/webpack/node_modules/tapable/lib/Hook.js:35:21)
    at Compilation.seal (/usr/local/lib/node_modules/webpack/lib/Compilation.js:881:27)
    at hooks.make.callAsync.err (/usr/local/lib/node_modules/webpack/lib/Compiler.js:464:17)
    at _err0 (eval at create (/usr/local/lib/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:11:1)
    at _addModuleChain (/usr/local/lib/node_modules/webpack/lib/Compilation.js:749:12)
    at processModuleDependencies.err (/usr/local/lib/node_modules/webpack/lib/Compilation.js:688:9)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by ooflorent** [comment]
Please use the latest version of webpack 4.

**Comment by maclockard** [comment]
@ooflorent I am getting this error as well using webpack `4.12.0`

**Comment by niieani** [comment]
Easy reproduction: for me it started to happen when I added `MiniCssExtractPlugin` (and its loader) in combination with `thread-loader`.

**Comment by evilebottnawi** [comment]
Looks it is bug

**Comment by niieani** [comment]
More context from error (on my side):

```
    at Object.pitch (~/node_modules/mini-css-extract-plugin/dist/loader.js:72:98)
[Compilation] ~/node_modules/thread-loader/dist/cjs.js??ref--18-0!~/node_modules/mini-css-extract-plugin/dist/loader.js!~/node_modules/css-loader/index.js??ref--18-2!~/node_modules/postcss-loader/lib/index.js??ref--18-3!~/node_modules/sass-loader/lib/loader.js??ref--18-4!~/lib/webpack/loaders/sassnamespace-loader.js!~/packages/@base-legacy/common/styles/bootstrap.sass
Module build failed (from ./node_modules/thread-loader/dist/cjs.js):
Thread Loader (Worker 5)
Cannot read property 'outputOptions' of undefined
```

**Comment by bluishoul** [comment]
@niieani Try put MiniCssExtractPlugin.loader before thread-loader, it works for me.

**Comment by Sunshine168** [comment]
I also have this issues when using MiniCssExtractPlugin with HappyPack

**Comment by shiro** [comment]
Also using MiniCssExtractPlugin with HappyPack, can relate

**Comment by tanweijiu** [comment]
I solved the same problem for the two version webpack , which is in the subfolder. maybe the same for this:

**Comment by BengBu-YueZhang** [comment]
> 将MiniCssExtractPlugin与HappyPack一起使用时，我也遇到了这个问题

me too

**Comment by xingxiangchao** [comment]
```
loader: [MiniCssExtractPlugin.loader,
            'happypack/loader?id=style'
          ]
```
尝试使用这种方式解决了

**Comment by hojas** [comment]
How to solve this problem in Nuxt?

**Comment by nahidakbar** [comment]
Bump! We recently updated our CRA/webpack and now we have this =(

**Comment by 282159468** [comment]
same issues

**Comment by evilebottnawi** [comment]
bump, need investigate

**Comment by richjava** [comment]
> Easy reproduction: for me it started to happen when I added `MiniCssExtractPlugin` (and its loader) in combination with `thread-loader`.

Exactly the same for me:
`use: [
            "thread-loader",
            MiniCssExtractPlugin.loader, "css-loader", "postcss-loader"
          ]`

**Comment by lyandzao** [comment]
same question in use happypack and miniCssExtractPlugin

**Comment by evilebottnawi** [comment]
@webpack-bot move to webpack-contrib/worker-loader

**Comment by alireza-mh** [comment]
Why this has been closed?
I have the same issue and how worker loader can help with `thread-loader` issue?

**Comment by evilebottnawi** [comment]
Because it is problem of `thread-loader`

**Comment by evilebottnawi** [comment]
Please open a new issue in `thread-loader` repo with reproducible test repo

**Comment by alireza-mh** [comment]
sure thanks

**Comment by tianshaochuan** [comment]
npm install webpack-dev-server
