### ISSUE TITLE
Cirulcar dependency issue

### ISSUE THREAD

**Issue by lab4quant** [webpack/webpack#6842]
**Do you want to request a *feature* or report a *bug*?**
report bug

**What is the current behavior?**
cicular dependency doesn't work
**If the current behavior is a bug, please provide the steps to reproduce.**
I created a [sample project](https://github.com/lab4quant/Circular), it can be used to demo and reproduce issue

```
git clone https://github.com/lab4quant/Circular
cd Circular
npm install
npm run build
```

there 2 js files requires each other: `uniformrng.js` and `seedgenerator.js`

the test file `rng.js` is trying to use `uniformrng.js` to generate random number

- from node console:

```
Circular>node boundle/rng
webpack:///./dist/seedgenerator.js?:12
        var first = new uniformrng_1.UniformRng(firstSeed);
                    ^

TypeError: uniformrng_1.UniformRng is not a constructor
    at Object.initialize (webpack:///./dist/seedgenerator.js?:12:21)
    at eval (webpack:///./dist/seedgenerator.js?:28:15)
    at Object../dist/seedgenerator.js (Circular\boundle\rn
g.js:82:1)
    at __webpack_require__ (Circular\boundle\rng.js:20:30)

    at eval (webpack:///./dist/uniformrng.js?:3:23)
    at Object../dist/uniformrng.js (Circular\boundle\rng.j
s:106:1)
    at __webpack_require__ (Circular\boundle\rng.js:20:30)

    at eval (webpack:///./dist/test/rng.js?:3:20)
    at Object../dist/test/rng.js (Circular\boundle\rng.js:
94:1)
    at __webpack_require__ (Circular\boundle\rng.js:20:30)

```

- from browser:

just use modern browser like chrome or firefox to open boundle/index.html, you'll see the same error browser console

```
Uncaught TypeError: uniformrng_1.UniformRng is not a constructor
    at Object.initialize (seedgenerator.js:12)
    at eval (seedgenerator.js:28)
    at Object../dist/seedgenerator.js (rng.js:82)
    at __webpack_require__ (rng.js:20)
    at eval (uniformrng.js:3)
    at Object../dist/uniformrng.js (rng.js:106)
    at __webpack_require__ (rng.js:20)
    at eval (rng.js:3)
    at Object../dist/test/rng.js (rng.js:94)
    at __webpack_require__ (rng.js:20)
```

**What is the expected behavior?**
typescript with circular import should work
**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
browser: chrome 65.0.3325.181 32-bit, windows 7
node.js: 6.9.4 32-bit windows
webpack: 4.2.0
operating system: windows 7 32 bit

**Comment by lab4quant** [comment]
update error detail

**Comment by sokra** [comment]
This is working as expected. Your code has a circular dependency.

Note that `class` is not hoisted by spec (only functions are).

**Comment by lab4quant** [comment]
@sokra, thanks for the update
I thought webpack 4+ supports circular dependency ...

How can I make my code work?

**Comment by lab4quant** [comment]
@sokra , the other day you mentioned `class` is not hoisted by spec (only functions are).
Does it mean I should use ES5 target?
I tried changing target to ES5, but still got the same error

**Comment by sokra** [comment]
You can't fix it with configuration changes. Your code is wrong. It doesn't work.

I. e. fix it by calling `initialize` once in `get`

**Comment by lab4quant** [comment]
@sokra , thanks, looks like i have no choice but to change code to remove circular import

**Comment by RusinovAnton** [comment]
@sokra is it possible to have a build-time error message in case of circular dependency rather than silently put `undefined` for the imported stuff?
