### ISSUE TITLE
webpack omits payload of error from memory-fs

### ISSUE THREAD

**Issue by shifteee** [webpack/webpack#6937]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
When fs error occurred webpack output only stacktrace
```bash
Error
    at MemoryFileSystem.mkdirpSync (/Users/dreamworker/www/dll-exp/node_modules/memory-fs/lib/MemoryFileSystem.js:144:10)
    at MemoryFileSystem.(anonymous function) [as mkdirp] (/Users/dreamworker/www/dll-exp/node_modules/memory-fs/lib/MemoryFileSystem.js:279:34)
    at hooks.emit.callAsync.err (/Users/dreamworker/www/dll-exp/node_modules/webpack/lib/Compiler.js:308:26)
    at _err0 (eval at create (/Users/dreamworker/www/dll-exp/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:18:1)
    at done (/Users/dreamworker/www/dll-exp/node_modules/neo-async/async.js:2809:11)
    at /Users/dreamworker/www/dll-exp/node_modules/neo-async/async.js:2760:7
    at MemoryFileSystem.writeFile (/Users/dreamworker/www/dll-exp/node_modules/memory-fs/lib/MemoryFileSystem.js:328:9)
    at compiler.outputFileSystem.mkdirp.err (/Users/dreamworker/www/dll-exp/node_modules/webpack/lib/LibManifestPlugin.js:64:34)
    at Immediate.<anonymous> (/Users/dreamworker/www/dll-exp/node_modules/memory-fs/lib/MemoryFileSystem.js:288:4)
    at runCallback (timers.js:781:20)
```
webpack config https://gist.github.com/shifteee/b53d52ece4247272305b2b7f83f63bb3

**What is the expected behavior?**
memory-fs provide error details: message, code, path . It really helpful. Expected behavior is something like this
```bash
{ Error
    at MemoryFileSystem.mkdirpSync (/Users/dreamworker/www/dll-exp/node_modules/memory-fs/lib/MemoryFileSystem.js:144:10)
    at MemoryFileSystem.(anonymous function) [as mkdirp] (/Users/dreamworker/www/dll-exp/node_modules/memory-fs/lib/MemoryFileSystem.js:279:34)
    at hooks.emit.callAsync.err (/Users/dreamworker/www/dll-exp/node_modules/webpack/lib/Compiler.js:308:26)
    at _err0 (eval at create (/Users/dreamworker/www/dll-exp/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:18:1)
    at done (/Users/dreamworker/www/dll-exp/node_modules/neo-async/async.js:2809:11)
    at /Users/dreamworker/www/dll-exp/node_modules/neo-async/async.js:2760:7
    at MemoryFileSystem.writeFile (/Users/dreamworker/www/dll-exp/node_modules/memory-fs/lib/MemoryFileSystem.js:329:9)
    at compiler.outputFileSystem.mkdirp.err (/Users/dreamworker/www/dll-exp/node_modules/webpack/lib/LibManifestPlugin.js:64:34)
    at Immediate.<anonymous> (/Users/dreamworker/www/dll-exp/node_modules/memory-fs/lib/MemoryFileSystem.js:289:4)
    at runCallback (timers.js:781:20)
  code: 'ENOTDIR',
  errno: 27,
  message: 'not a directory',
  path: '/Users/dreamworker/www/dist' }
```

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
* Operating System: MacOS X .13
* Node Version: 8.4
* NPM Version: 5.7.1
* webpack Version: 4.4.1

**Comment by sokra** [comment]
this issue is related to webpack/memory-fs. It happens when captureStackTrace is called before this.message is set.
