### ISSUE TITLE
TypeError: Cannot read property 'outputOptions' of undefined

### ISSUE THREAD

**Issue by menduz** [webpack/webpack#7021]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

It fails and I don't know how to isolate and reproduce it since my project has 300+ files. 
It only uses `ts-loader` and `url-loader`. I hope this stack trace helps.

Also, following the stack trace we can clearly see that the function being called is not being called with `apply` or `call`, ergo the `this.outputOptions` will be null

**If the current behavior is a bug, please provide the steps to reproduce.**

```
/Users/menduz/code/client/node_modules/webpack/lib/webworker/WebWorkerMainTemplatePlugin.js:97
                        hash.update(`${this.outputOptions.publicPath}`);
                                            ^

TypeError: Cannot read property 'outputOptions' of undefined
    at /Users/menduz/code/client/node_modules/webpack/lib/webworker/WebWorkerMainTemplatePlugin.js:97:24
    at SyncHook.eval [as call] (eval at create (/Users/menduz/code/script/node_modules/tapable/lib/HookCodeFactory.js:17:12), <anonymous>:7:1)
    at SyncHook.lazyCompileHook [as _call] (/Users/menduz/code/script/node_modules/tapable/lib/Hook.js:35:21)
    at MainTemplate.updateHash (/Users/menduz/code/script/node_modules/webpack/lib/MainTemplate.js:394:19)
    at Compilation.createHash (/Users/menduz/code/script/node_modules/webpack/lib/Compilation.js:1663:21)
    at hooks.optimizeTree.callAsync.err (/Users/menduz/code/script/node_modules/webpack/lib/Compilation.js:939:9)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/menduz/code/script/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/Users/menduz/code/script/node_modules/tapable/lib/Hook.js:35:21)
    at Compilation.seal (/Users/menduz/code/script/node_modules/webpack/lib/Compilation.js:896:27)
    at hooks.make.callAsync.err (/Users/menduz/code/script/node_modules/webpack/lib/Compiler.js:479:17)
    at _err0 (eval at create (/Users/menduz/code/script/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:11:1)
    at _addModuleChain (/Users/menduz/code/script/node_modules/webpack/lib/Compilation.js:764:12)
    at processModuleDependencies.err (/Users/menduz/code/script/node_modules/webpack/lib/Compilation.js:703:9)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by montogeek** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by sokra** [comment]
Looks like you have mixed up multiple installations of webpack

* /Users/menduz/code/client/node_modules/webpack
* /Users/menduz/code/script/node_modules/webpack

**Comment by evilebottnawi** [comment]
@menduz https://github.com/webpack/webpack/issues/7021#issuecomment-380793893 help you?

**Comment by menduz** [comment]
Yes, deleting the second version solved the issue

**Comment by tanweijiu** [comment]
@sokra  thks...i solved this problem as the same reason.
