### ISSUE TITLE
webpack/hot/poll?1000 doesn't work correctly in webpack v4 [electron]

### ISSUE THREAD

**Issue by juncaixinchi** [webpack/webpack#7098]
### Do you want to request a feature or report a bug?

Bug

### What is the current behavior?

`webpack/hot/poll?1000` in the `entry` doesn't work correctly in webpack v4.

When the first pack finished, there are no new updates. However, webpack try to load the the hot-update manifest file (`c29b4da1bbf40db96232.hot-update.json`) and return with `ERR_FILE_NOT_FOUND`

After something changed in the `src/app.jsx`, `c29b4da1bbf40db96232.hot-update.json` is created. But after the electron freshed , webpack try to load another hot-update manifest file(`c1f5f7e4a22b756ebdc9.hot-update.json `)

I guess there is something wrong when checking the latest hot-update manifest file.

+ logs of `webpack --watch`
```
Webpack is watching the files…

Hash: c29b4da1bbf40db96232
Version: webpack 4.6.0
Time: 1308ms
Built at: 2018-04-23 21:55:38
    Asset      Size  Chunks             Chunk Names
bundle.js  1.72 MiB    main  [emitted]  main
Entrypoint main = bundle.js
[./node_modules/_webpack@4.6.0@webpack/hot/log-apply-result.js] (webpack)/hot/log-apply-result.js 1.31 KiB {main} [built]
[./node_modules/_webpack@4.6.0@webpack/hot/log.js] (webpack)/hot/log.js 1.03 KiB {main} [built]
[./node_modules/_webpack@4.6.0@webpack/hot/poll.js?1000] (webpack)/hot/poll.js?1000 1.16 KiB {main} [built]
[./src/app.jsx] 544 bytes {main} [built]
[0] multi webpack/hot/poll?1000 ./src/app.jsx 40 bytes {main} [built]
    + 21 hidden modules
Hash: c1f5f7e4a22b756ebdc9
Version: webpack 4.6.0
Time: 237ms
Built at: 2018-04-23 22:18:03
                                  Asset      Size  Chunks             Chunk Names
                              bundle.js  1.72 MiB    main  [emitted]  main
main.c29b4da1bbf40db96232.hot-update.js  1.97 KiB    main  [emitted]  main
   c29b4da1bbf40db96232.hot-update.json  46 bytes          [emitted]
Entrypoint main = bundle.js main.c29b4da1bbf40db96232.hot-update.js
[./src/app.jsx] 545 bytes {main} [built]
    + 25 hidden modules

```

+ log of electron console in first pack
```
GET file:///D:/GitHub/WX-App/public/c29b4da1bbf40db96232.hot-update.json net::ERR_FILE_NOT_FOUND

[HMR] Update failed: Error: Manifest request to c29b4da1bbf40db96232.hot-update.json timed out.
    at XMLHttpRequest.request.onreadystatechange (file:///D:/GitHub/WX-App/public/bundle.js:42:16)
module.exports @ log.js?1afd:26
(anonymous) @ poll.js?10ba:29
```
+ change something in `src` and refresh the electron
```
GET file:///D:/GitHub/WX-App/public/c1f5f7e4a22b756ebdc9.hot-update.json net::ERR_FILE_NOT_FOUND
(anonymous) @ bundle.js:33
hotDownloadManifest @ bundle.js:25
hotCheck @ bundle.js:231
checkForUpdate @ poll.js?10ba:13
log.js?1afd:26 [HMR] Update failed: Error: Manifest request to c1f5f7e4a22b756ebdc9.hot-update.json timed out.
    at XMLHttpRequest.request.onreadystatechange (file:///D:/GitHub/WX-App/public/bundle.js:42:16)
```

### webpack.config.js:

```js
const path = require('path')
const webpack = require('webpack')

module.exports = {
  mode: 'development',
  output: {
    path: path.join(__dirname, 'public'),
    filename: 'bundle.js'
  },
  target: 'electron-renderer',
  devtool: 'eval-source-map',
  entry: [
    'webpack/hot/poll?1000',
    './src/app.jsx'
  ],
  resolve: { extensions: ['.js', '.jsx'] },
  module: {
    rules: [
      {
        test: /\.(js|jsx)$/,
        exclude: /node_modules/,
        use: ['babel-loader']
      }
    ]
  },
  plugins: [
    new webpack.HotModuleReplacementPlugin(),
    new webpack.NamedModulesPlugin(),
  ]
}
```

### reproduceable repo:

https://github.com/juncaixinchi/WX-App

script to run:

```bash
git clone https://github.com/juncaixinchi/WX-App.git
cd WX-App
git checkout webpack
npm i
npm run webpack
npm start // another terminal
```

### What is the expected behavior?

HMR update successfully

### Environments:

electron: v1.7.8

Node.js: v8.2.1

webpack: v4.6.0

Operating System: ubuntu 16.10

**Comment by gregbenner** [comment]
me too

**Comment by evilebottnawi** [comment]
Somebody can create reproducible test repo?

**Comment by Luckz** [comment]
Silly bot.

**Comment by evilebottnawi** [comment]
@Luckz Can you create reproducible test repo?

**Comment by Eckountld** [comment]
Hi, please try and remove your dist folder, your main folder in the package.json - "main": "dist/index.js",
and then just restart your process, that worked for me.
