### ISSUE TITLE
Webpack: Error in window is not defined during deploy with "window" used in necessary node modules

### ISSUE THREAD

**Issue by MrSantaCloud** [webpack/webpack#7112]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
"Error in window is not defined" in main.js file during deploy. 
I am not using "window" in my code and node_modules using it are all necessary so i have to use them.

**If the current behavior is a bug, please provide the steps to reproduce.**
There aren't much steps to describe. I simply get this error, but this doesn't provide me more infos...
Error blinks up during execution of "node node_modules/webpack/bin/webpack.js --mode=production --env.prod" command.

**What is the expected behavior?**
It should execute the command without any problem.
What can I do if window is used inside some necessary node_modules?

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

Related to every other issue about this problem, which solutions haven't been helpful, unluckily...
_______________________________________________
Webpack version: 4.6.0
Node version: 5.6.0
Operating system: windows 10.
_______________________________________________
**webpack.config content:**
```
const path = require('path');
const webpack = require('webpack');
const merge = require('webpack-merge');
const AngularCompilerPlugin = require('@ngtools/webpack').AngularCompilerPlugin;
const CheckerPlugin = require('awesome-typescript-loader').CheckerPlugin;
var nodeExternals = require('webpack-node-externals');
const UglifyJsPlugin = require('uglifyjs-webpack-plugin');

module.exports = (env) => {
    // Configuration in common to both client-side and server-side bundles
    const isDevBuild = !(env && env.prod);
    //mode: isDevBuild ? 'development' : 'production';
    const sharedConfig = {
        stats: { modules: false },
        context: __dirname,
        resolve: { extensions: ['.js', '.ts'] },
        output: {
            filename: '[name].js',
            publicPath: 'dist/' // Webpack dev middleware, if enabled, handles requests for this URL prefix
        },
        module: {
            rules: [
                { test: /\.ts$/, include: /ClientApp/, use: isDevBuild ? ['awesome-typescript-loader?silent=true', 'angular2-template-loader', 'angular2-router-loader'] : '@ngtools/webpack' },
                { test: /\.html$/, use: 'html-loader?minimize=false' },
                { test: /\.css$/, use: ['to-string-loader', 'style-loader', isDevBuild ? 'css-loader' : 'css-loader?minimize'] },
                { test: /\.(png|jpg|jpeg|gif|svg)$/, use: 'url-loader?limit=25000' },
                //font management
                {
                    test: /\.(svg|eot|ttf|woff|woff2)$/,
                    use: [{
                        loader: 'file-loader',
                        options: {
                            name: 'images/[name].[hash].[ext]'
                        }
                    }]
                }
            ]
        },
        plugins: [new CheckerPlugin()]
    };

    // Configuration for client-side bundle suitable for running in browsers
    const clientBundleOutputDir = './wwwroot/dist';
    const clientBundleConfig = merge(sharedConfig, {
        entry: { 'main-client': './ClientApp/boot.browser.ts' },
        output: { path: path.join(__dirname, clientBundleOutputDir) },
        optimization: {
            minimizer: [
                // specify a custom UglifyJsPlugin here to get source maps in production
                new UglifyJsPlugin({
                    cache: true,
                    parallel: true,
                    uglifyOptions: {
                        compress: false,
                        ecma: 6,
                        mangle: true
                    },
                    sourceMap: true
                })
            ]
        },
        plugins: [
            new webpack.DllReferencePlugin({
                context: __dirname,
                manifest: require('./wwwroot/dist/vendor-manifest.json')
            })
        ].concat(isDevBuild ? [
            // Plugins that apply in development builds only
            new webpack.SourceMapDevToolPlugin({
                filename: '[file].map', // Remove this line if you prefer inline source maps
                moduleFilenameTemplate: path.relative(clientBundleOutputDir, '[resourcePath]') // Point sourcemap entries to the original file locations on disk
            })
        ] : [
                // Plugins that apply in production builds only
                new AngularCompilerPlugin({
                    tsConfigPath: './tsconfig.json',
                    entryModule: path.join(__dirname, 'ClientApp/app/app.browser.module#AppModule'),
                    exclude: ['./**/*.server.ts']
                })
            ])
    });

    // Configuration for server-side (prerendering) bundle suitable for running in Node
    const serverBundleConfig = merge(sharedConfig, {
        resolve: { mainFields: ['main'] },
        entry: { 'main-server': './ClientApp/boot.server.ts' },
        plugins: [
            new webpack.DllReferencePlugin({
                context: __dirname,
                manifest: require('./ClientApp/dist/vendor-manifest.json'),
                sourceType: 'commonjs2',
                name: './vendor'
            })
        ].concat(isDevBuild ? [] : [
            new AngularCompilerPlugin({
                tsConfigPath: './tsconfig.json',
                entryModule: path.join(__dirname, 'ClientApp/app/app.server.module#AppModule'),
                exclude: ['./**/*.browser.ts']
            })
        ]),
        output: {
            libraryTarget: 'commonjs',
            path: path.join(__dirname, './ClientApp/dist')
        },

        //exclude node modules
        target: 'node',
        externals: [nodeExternals()], // in order to ignore all modules in node_modules folder

        devtool: 'inline-source-map'
    });

    return [clientBundleConfig, serverBundleConfig];
};
```
_______________________________________________________________________________
**Package.json**
```
{
  "name": "AngularHeroes",
  "private": true,
  "version": "0.0.0",
  "scripts": {
    "test": "karma start ClientApp/test/karma.conf.js",
    "postinstall": "npm run webpack:vendor",
    "webpack": "webpack --mode=development --config webpack.config.js",
    "webpack:vendor": "webpack --mode=development --config webpack.config.vendor.js"
  },
  "devDependencies": {
    "@angular/animations": "^5.2.10",
    "@angular/cdk": "^5.2.5",
    "@angular/common": "^5.2.10",
    "@angular/compiler": "^5.2.10",
    "@angular/compiler-cli": "^5.2.10",
    "@angular/core": "^5.2.10",
    "@angular/forms": "^5.2.10",
    "@angular/http": "^5.2.10",
    "@angular/material": "^5.2.5",
    "@angular/platform-browser": "^5.2.10",
    "@angular/platform-browser-dynamic": "^5.2.10",
    "@angular/platform-server": "^5.2.10",
    "@angular/router": "^5.2.10",
    "@ngtools/webpack": "^1.10.2",
    "@types/chai": "^4.1.3",
    "@types/jasmine": "^2.8.6",
    "@types/webpack-env": "^1.13.6",
    "angular-jwt": "^0.1.9",
    "angular2-router-loader": "0.3.5",
    "angular2-template-loader": "0.6.2",
    "aspnet-prerendering": "^3.0.1",
    "aspnet-webpack": "^2.0.3",
    "awesome-typescript-loader": "^5.0.0",
    "cdk": "0.0.0",
    "chai": "^4.1.2",
    "css": "2.2.1",
    "css-loader": "^0.28.11",
    "devextreme": "^17.2.7",
    "devextreme-angular": "^17.2.7",
    "es6-shim": "0.35.3",
    "event-source-polyfill": "0.0.12",
    "expose-loader": "^0.7.5",
    "extract-text-webpack-plugin": "^4.0.0-beta.0",
    "file-loader": "^1.1.11",
    "file-saver": "^1.3.8",
    "html-loader": "^0.5.5",
    "isomorphic-fetch": "2.2.1",
    "jasmine-core": "^3.1.0",
    "json-loader": "^0.5.7",
    "jsonwebtoken": "^8.2.1",
    "karma": "^2.0.2",
    "karma-chai": "0.1.0",
    "karma-chrome-launcher": "2.2.0",
    "karma-cli": "1.0.1",
    "karma-jasmine": "^1.1.1",
    "karma-webpack": "^3.0.0",
    "popper.js": "^1.14.3",
    "preboot": "^6.0.0-beta.3",
    "raw-loader": "0.5.1",
    "reflect-metadata": "0.1.12",
    "requirejs": "^2.3.5",
    "rxjs": "^5.5.10",
    "style-loader": "^0.21.0",
    "to-string-loader": "1.1.5",
    "typescript": "^2.8.3",
    "url-loader": "^1.0.1",
    "webpack": "^4.6.0",
    "webpack-cli": "^2.0.15",
    "webpack-hot-middleware": "^2.22.1",
    "webpack-merge": "^4.1.2",
    "webpack-node-externals": "^1.7.2",
    "zone.js": "^0.8.26"
  },
  "dependencies": {
    "@angular/animations": "^5.2.10",
    "@angular/cdk": "^5.2.5",
    "@angular/common": "^5.2.10",
    "@angular/compiler": "^5.2.10",
    "@angular/compiler-cli": "^5.2.10",
    "@angular/core": "^5.2.10",
    "@angular/forms": "^5.2.10",
    "@angular/http": "^5.2.10",
    "@angular/material": "^5.2.5",
    "@angular/platform-browser": "^5.2.10",
    "@angular/platform-browser-dynamic": "^5.2.10",
    "@angular/platform-server": "^5.2.10",
    "@angular/router": "^5.2.10",
    "@ng-bootstrap/ng-bootstrap": "^1.1.2",
    "@ngtools/webpack": "^1.10.2",
    "angular-jwt": "^0.1.9",
    "angular2-router-loader": "0.3.5",
    "angular2-template-loader": "0.6.2",
    "aspnet-prerendering": "^3.0.1",
    "aspnet-webpack": "^2.0.3",
    "awesome-typescript-loader": "^5.0.0",
    "cdk": "0.0.0",
    "chai": "^4.1.2",
    "css": "2.2.1",
    "css-loader": "^0.28.11",
    "devextreme-angular": "^17.2.7",
    "es6-shim": "0.35.3",
    "event-source-polyfill": "0.0.12",
    "expose-loader": "^0.7.5",
    "file-loader": "^1.1.11",
    "file-saver": "^1.3.8",
    "html-loader": "^0.5.5",
    "isomorphic-fetch": "2.2.1",
    "jasmine-core": "^3.1.0",
    "json-loader": "^0.5.7",
    "jsonwebtoken": "^8.2.1",
    "karma": "^2.0.2",
    "karma-chai": "0.1.0",
    "karma-chrome-launcher": "2.2.0",
    "karma-cli": "1.0.1",
    "karma-jasmine": "^1.1.1",
    "karma-webpack": "^3.0.0",
    "popper.js": "^1.14.3",
    "preboot": "^6.0.0-beta.3",
    "raw-loader": "0.5.1",
    "reflect-metadata": "0.1.12",
    "requirejs": "^2.3.5",
    "rxjs": "^5.5.10",
    "style-loader": "^0.21.0",
    "to-string-loader": "1.1.5",
    "uglifyjs-webpack-plugin": "^1.2.5",
    "url-loader": "^1.0.1",
    "zone.js": "^0.8.26"
  }
}

```

**Comment by montogeek** [comment]
webpack runs in a Node environment, if some of your dependencies rely on `window` object, enclose them in a check:
```js
const isClient = typeof window !== 'undefined'
```

or when loading dependencies
```js
let particles
if (typeof window !== 'undefined') {
  particles = require('particles.js')
}
```

**Comment by montogeek** [comment]
It looks like some paths are misconfigured. I encourage you to ask your question on StackOverflow instead. We try to use the issue tracker for bug reports and feature requests, as well as some discussions, but this appears to be a very localized question.

I’m closing for these reasons.

**Comment by MrSantaCloud** [comment]
@montogeek I want to try with your suggested solution, but since I'm a newbie to webpack i really need to ask you: **where should I put these code snippets exactly?** In webpack.config.js, in my angular app entry point,...?

Thanks in advance!

( I've asked it on stackoverflow before but I didn't have a real working solution, looks like no one has a real workaround for this and looking on other related issues on github I've never found some pratical examples as solutions... )

**Comment by montogeek** [comment]
You should put them whatever you need to use `window` or you need to import a library that uses `window` object as you see on my examples.

Read more about globals in different environment here: https://www.hacksparrow.com/global-variables-in-node-js.html

There is ton of articles about how globals differ on Browser and Node.JS environment but in a nutshell:
1. Browsers have `window` global object.
2. Node.JS global object is `global` and it doesn't have `window` object.
3. Commands that run on your terminal are running on a Node environment, therefore any reference to `window` would result in an error.

**Comment by MrSantaCloud** [comment]
🎉 🍻   **SOLVED ✔️ ** 🍻  🎉 

Changed this:
` { test: /\.ts$/, include: /ClientApp/, use: isDevBuild ? ['awesome-typescript-loader?silent=true', 'angular2-template-loader', 'angular2-router-loader'] : '@ngtools/webpack' },`

In this:
` { test: /\.ts$/, include: /ClientApp/, use: ['awesome-typescript-loader?silent=true', 'angular2-template-loader', 'angular2-router-loader'] },`

So I've actually:
✔️ ▶️  **removed `'@ngtools/webpack' ` from typescript module rules loaders** since it was causing this issue

I don't know why it was causing errors in libraries but I've seen that with other loaders it works pretty fine.
Website is now deployed and fully-working 😃

**Comment by montogeek** [comment]
Congrats!

**Comment by stevemarksd** [comment]
@montogeek 

Actually I need a part of the library, but the library is bloated and imports another file that depends on window. I can't use your solution.

For example I need PIXI.Point, which works fine on node.js, but importing pixi.js it will import the whole file which has a window reference.

**Comment by pundoo** [comment]
[Shimming](https://webpack.js.org/guides/shimming/#shimming-globals) did the trick for me...

```
...
plugins: [
   new webpack.ProvidePlugin({
      window: 'global/window',
   }),
]
...
```

requires [global](https://www.npmjs.com/package/global) package

**Comment by justintoth** [comment]
@pundoo's webpack config update suggestion to use ProvidePlugin just changed the error to:

```
NativeScript encountered a fatal error: Uncaught ReferenceError: Zone is not defined
at
(file: src/webpack:/housters/node_modules/zone.js/dist/zone.js:703:0)
at (file: src/webpack:/housters/node_modules/zone.js/dist/zone.js:8:63)
at ./node_modules/zone.js/dist/zone.js(file: src/webpack:/housters/node_modules/zone.js/dist/zone.js:10:1)
at __webpack_require__(file: src/webpack:/housters/webpack/bootstrap:24:0)
at fn(file: src/webpack:/housters/webpack/runtime/hot module replacement:61:0)
at ./src/polyfills.ts(file:///app/bundle.js:26385:75)
at __webpack_require__(file: src/webpack:/housters/webpack/bootstrap:24:0)
at __webpack_exec__(file:///app/bundle.js:33452:39)
at (file:///app/bundle.js:33453:71)
at __webpack_require__.X(file: src/webpack:/housters/webpack/runtime/startup entrypoint:6:0)
at (file:///app/bundle.js:33453:47)
at (file:///app/bundle.js:33458:3)
at require(:1:137)
```
