### ISSUE TITLE
Defaults are not getting set properly

### ISSUE THREAD

**Issue by thepian** [webpack/webpack#712]
I'm trying to use web pack for a plugin that renders JS files on the fly in an Express web server. The plugin reads a single file and renders to a string using sample code. It seems that the options I use are somehow broken because it blows up in the OptionsDefaulter.process

I tried to debug it, but couldn't find any obvious cause.

```
TypeError: Cannot set property 'unknownContextRequest' of undefined
    at setProperty (/Users/Shared/Projects/Websites/libs/ss-build/node_modules/webpack/node_modules/webpack-core/lib/OptionsDefaulter.js:26:18)
    at WebpackOptionsDefaulter.OptionsDefaulter.process (/Users/Shared/Projects/Websites/libs/ss-build/node_modules/webpack/node_modules/webpack-core/lib/OptionsDefaulter.js:43:5)
    at WebpackOptionsDefaulter.process (/Users/Shared/Projects/Websites/libs/ss-build/node_modules/webpack/lib/WebpackOptionsDefaulter.js:64:37)
    at webpack (/Users/Shared/Projects/Websites/libs/ss-build/node_modules/webpack/lib/webpack.js:18:33)
    at Object.compile (/Users/Shared/Projects/Websites/libs/ss-build/lib/formatters/ecma.js:97:13)
    at loadFile (/Users/Shared/Projects/Websites/libs/socketstream/lib/client/bundler/asset.js:42:22)
    at Object.js (/Users/Shared/Projects/Websites/libs/socketstream/lib/client/bundler/asset.js:48:14)
    at EventEmitter.<anonymous> (/Users/Shared/Projects/Websites/libs/socketstream/lib/client/serve/dev.js:34:49)
    at EventEmitter.emit (/Users/Shared/Projects/Websites/libs/socketstream/node_modules/eventemitter2/lib/eventemitter2.js:339:22)
    at Router.exports.Router.Router.route (/Users/Shared/Projects/Websites/libs/socketstream/lib/http/router.js:44:15)
Packing /Users/Shared/Projects/Websites/fluentapi/client/code/lessons/tmp2.js
```

I am using     "webpack": "^1.4.15"

The web pack call looks like:

```
            function handleFatalError(err) {
                console.error('webpack issue with',path,err);
                cb('// Failed to compile, see log.')
            }
            function handleSoftErrors(errors) {
                console.log('Errors:', errors.join('\n'));
                cb('// Failed to compile, hasErrors.');
            }
            function handleWarnings(warnings) {
                console.log('Errors:', warnings.join('\n'));
            }
            var basePath = config.basePath || process.cwd(), //TODO project dir
                relPath = pathlib.relative(basePath, path).replace('.js','').replace('.es6','');

            var self = this,
                packOptions = {
                    //This key must be created for storing special information needed by socketstream
                    socketstream: {},

                    //context: basePath,

                    //module: {
                    //    unknownContextRequest: '.'
                    //},
                    output: {
                        path: "there.will.be.no.output.js"
                    },
                    noWrite: true, //disables outputing in a file
                    emitFile: function (filename, content) {
                        console.log('after packing',basePath, relPath);
                        bundle = content;
                    }
                    /*,

                    resolve: {
                        loaders: []
                    }
                    */
                },
                bundle;

            console.info('Packing',path);

            webpack(path, packOptions, function onWebpackFinished(err, stats) {

                if (err) {
                    return handleFatalError(err);
                    throw err;
                }

                var jsonStats = stats.toJson();
                if(jsonStats.errors.length > 0)
                    return handleSoftErrors(jsonStats.errors, stats.errors[0]);
                if(jsonStats.warnings.length > 0)
                    handleWarnings(jsonStats.warnings);

                cb(bundle);
            });
```

**Comment by sokra** [comment]
The `webpack` function has only two arguments...

**Comment by thepian** [comment]
Strange, I guess the example I found doesn't work.
