### ISSUE TITLE
TypeError: Cannot read property 'compilation' of undefined     at ModuleConcatenationPlugin.apply

### ISSUE THREAD

**Issue by trusktr** [webpack/webpack#7148]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

After updating from Webpack 3 to 4, I get an error:

```
/home/trusktr/Downloads/src/trusktr+infamous/node_modules/webpack/bin/webpack.js:348
                        throw err;
                        ^

TypeError: Cannot read property 'compilation' of undefined
    at ModuleConcatenationPlugin.apply (/home/trusktr/Downloads/src/trusktr+builder-js-package/node_modules/webpack/lib/optimize/ModuleConcatena
tionPlugin.js:25:18)
    at Compiler.apply (/home/trusktr/Downloads/src/trusktr+infamous/node_modules/tapable/lib/Tapable.js:375:16)
    at webpack (/home/trusktr/Downloads/src/trusktr+infamous/node_modules/webpack/lib/webpack.js:33:19)
    at processOptions (/home/trusktr/Downloads/src/trusktr+infamous/node_modules/webpack/bin/webpack.js:335:15)
    at yargs.parse (/home/trusktr/Downloads/src/trusktr+infamous/node_modules/webpack/bin/webpack.js:397:2)
    at Object.Yargs.self.parse (/home/trusktr/Downloads/src/trusktr+infamous/node_modules/webpack/node_modules/yargs/yargs.js:533:18)
    at Object.<anonymous> (/home/trusktr/Downloads/src/trusktr+infamous/node_modules/webpack/bin/webpack.js:152:7)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Function.Module.runMain (module.js:690:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:666:3
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Reproduction: https://github.com/trusktr/lowclass/tree/webpack-issue-7148

To get the error:

```
npm i
./node_modules/.bin/builder run build:global
```

which triggers Webpack with Babel 7 loader and Buble loader.

Once dependencies are installed, you can see relevant configuration files at

- `node_modules/builder-js-package/config/webpack.config.js`
- `node_modules/builder-js-package/config/babel.config.js`
- `node_modules/builder-js-package/config/buble.config.js`

Note, the red error messages (`[builder:config:load-archetype-scripts]`) from the `builder` output are harmelss, you can ignore those.

To run `webpack` manually, run

```
./node_modules/.bin/webpack --config ./node_modules/builder-js-package/config/webpack.config.js
```

which gives you the purest output without any other output from `builder`, just Webpack output.

**What is the expected behavior?**

No error

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

Ubuntu inside Chrome OS (via Crouton)
Node 9.9.0
Webpack 4.6.0

**Comment by trusktr** [comment]
Reproduction: https://github.com/trusktr/lowclass/tree/webpack-issue-7148

To get the error:

```
npm i
./node_modules/.bin/builder run build:global
```

which triggers Webpack with Babel 7 loader and Buble loader.

Once dependencies are installed, you can see relevant configuration files at

- node_modules/builder-js-package/config/webpack.config.js
- node_modules/builder-js-package/config/babel.config.js
- node_modules/builder-js-package/config/buble.config.js


Note, the red error messages (`[builder:config:load-archetype-scripts]`) from the `builder` output are harmelss, you can ignore those.

To run `webpack` manually, run

```
./node_modules/.bin/webpack --config ./node_modules/builder-js-package/config/webpack.config.js
```

which gives you the purest output without any other output from `builder`, just Webpack output.

**Comment by trusktr** [comment]
If you disable the line with `new ModuleConcatenationPlugin`, the error goes away, obviously.

**Comment by trusktr** [comment]
Seems `Compiler.hooks` does not exist. Does this need to be listed in the breaking changes of the release notes, and does Webpack need to update it's own plugin? Or is ModuleConcatenationPlugin deprecated? Or something?

**Comment by trusktr** [comment]
The release notes (https://github.com/webpack/webpack/releases/tag/v4.0.0) say that 

> Plugins should use `Compiler.hooks.xxx.tap(<plugin name>, fn)` now

But when I inspect both `Compiler` and an instance of `Compiler` in devtools, neither of them have a `hooks` property.

**Comment by trusktr** [comment]
Ah, I see, this plugin does not need to be used anymore.

> `ModuleConcatenationPlugin` -> `optimization.concatenateModules` (on by default in production mode)

Perhaps, it should've been completely removed, that would've been much more helpful (I would've gotten an error trying to call `new undefined`) in my `webpack.config.js`.

**Comment by trusktr** [comment]
I should've read the _whole_ release note, not just the section with "breaking" in it. It helps if _all_ breaking changes are in a section with "breaking" in the title. :)

**Comment by trusktr** [comment]
The release note says

> removed plugins now give a useful error message

which doesn't seem to have been true in this case.
