### ISSUE TITLE
Webpack 4: devtool: 'source-map' makes an error

### ISSUE THREAD

**Issue by trusktr** [webpack/webpack#7149]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Adding `devtool: 'source-map'` to my config causes the error

```
ERROR in ./src/index.js
Module build failed: Error: Cannot find module 'source-map'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:470:25)
    at Module.require (module.js:593:17)
    at require (/home/trusktr/Downloads/src/trusktr+infamous/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at _sourceMap (/home/trusktr/Downloads/src/trusktr+builder-js-package/node_modules/@babel/generator/lib/source-map.js:9:37)
    at SourceMap.get (/home/trusktr/Downloads/src/trusktr+builder-js-package/node_modules/@babel/generator/lib/source-map.js:32:40)
    at Object.get [as map] (/home/trusktr/Downloads/src/trusktr+builder-js-package/node_modules/@babel/generator/lib/buffer.js:58:33)
    at generateCode (/home/trusktr/Downloads/src/trusktr+builder-js-package/node_modules/@babel/core/lib/transformation/file/generate.js:101:27)
    at runSync (/home/trusktr/Downloads/src/trusktr+builder-js-package/node_modules/@babel/core/lib/transformation/index.js:48:58)
    at runAsync (/home/trusktr/Downloads/src/trusktr+builder-js-package/node_modules/@babel/core/lib/transformation/index.js:35:14)
    at /home/trusktr/Downloads/src/trusktr+builder-js-package/node_modules/@babel/core/lib/transform.js:34:34
    at process._tickCallback (internal/process/next_tick.js:112:11)
```

**If the current behavior is a bug, please provide the steps to reproduce.**

https://github.com/trusktr/lowclass/tree/webpack-issue-7149

Check out that branch and run

```sh
npm i
./node_modules/.bin/webpack --config ./node_modules/builder-js-package/config/webpack.config.js
```

**What is the expected behavior?**

No error, with source map emitted.

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

Webpack 4.6.0
Node 9.9.0

**Comment by trusktr** [comment]
Okay, it's working now in the reproduction, not sure what changed.
