### ISSUE TITLE
Contenthash doesn't work with splitchunks: 'all'

### ISSUE THREAD

**Issue by marcofugaro** [webpack/webpack#7185]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
Webpack throws a `Cannot convert undefined or null to object` error when `contenthash` is used for `output.filename` and `splitChunks.chunks: 'all' is enabled`.

<img width="381" alt="screen shot 2018-05-03 at 14 33 44" src="https://user-images.githubusercontent.com/7217420/39576915-178896f6-4ee0-11e8-8431-3737978b36eb.png">

This is the webpack.config, [link to reproducible repo](https://github.com/marcofugaro/webpack-issue-repo):

```js
  output: {
    filename: 'app.[contenthash:8].js',
    chunkFilename: '[name].[contenthash:8].chunk.js',
  },
  mode: 'production',
  optimization: {
    splitChunks: {
      chunks: 'all',
      name: 'vendors',
    },
  },
```

**If the current behavior is a bug, please provide the steps to reproduce.**
`git clone git@github.com:marcofugaro/webpack-issue-repo.git`
`yarn`
`yarn build`

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
node v9.6.1 - webpack v4.6.0 - OSX

PS: I took the suggestion from a sokra comment from [this pr in create-react-app](https://github.com/facebook/create-react-app/pull/4077)
![screen shot 2018-05-03 at 12 55 19](https://user-images.githubusercontent.com/7217420/39577079-9bae5862-4ee0-11e8-925a-a830175a1719.png)

**Comment by philipp-spiess** [comment]
I'm seeing a similar issue when limiting the max number of chunks to 1 using the following plugin:

```js
new webpack.optimize.LimitChunkCountPlugin({
   maxChunks: 1,
})
```

The build will fail with the same error message and enabling verbose mode also shows a stack-trace:

```
ERROR in chunk pspdfkit [entry]
pspdfkit-lib/pspdfkit.css
Cannot convert undefined or null to object
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at javascript (/Users/philipp/dev/node_modules/webpack/lib/web/JsonpMainTemplatePlugin.js:91:37)
    at fn (/Users/philipp/dev/node_modules/webpack/lib/TemplatedPathPlugin.js:29:11)
    at String.replace (<anonymous>)
    at replacePathVariables (/Users/philipp/dev/node_modules/webpack/lib/TemplatedPathPlugin.js:98:5)
    at SyncWaterfallHook.eval [as call] (eval at create (/Users/philipp/dev/node_modules/tapable/lib/HookCodeFactory.js:17:12), <anonymous>:7:16)
    at MainTemplate.getAssetPath (/Users/philipp/dev/node_modules/webpack/lib/MainTemplate.js:387:31)
    at getScriptSrcPath (/Users/philipp/dev/node_modules/webpack/lib/web/JsonpMainTemplatePlugin.js:57:24)
    at mainTemplate.hooks.localVars.tap (/Users/philipp/dev/node_modules/webpack/lib/web/JsonpMainTemplatePlugin.js:127:48)
    at SyncWaterfallHook.eval [as call] (eval at create (/Users/philipp/dev/node_modules/tapable/lib/HookCodeFactory.js:17:12), <anonymous>:17:16)
    at SyncWaterfallHook.lazyCompileHook [as _call] (/Users/philipp/dev/node_modules/tapable/lib/Hook.js:35:21)
    at MainTemplate.render (/Users/philipp/dev/node_modules/webpack/lib/MainTemplate.js:318:33)
    at Object.render (/Users/philipp/dev/node_modules/webpack/lib/JavascriptModulesPlugin.js:67:34)
    at Compilation.createChunkAssets (/Users/philipp/dev/node_modules/webpack/lib/Compilation.js:1772:29)
    at hooks.optimizeTree.callAsync.err (/Users/philipp/dev/node_modules/webpack/lib/Compilation.js:942:10)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/philipp/dev/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/Users/philipp/dev/node_modules/tapable/lib/Hook.js:35:21)
    at Compilation.seal (/Users/philipp/dev/node_modules/webpack/lib/Compilation.js:890:27)
    at hooks.make.callAsync.err (/Users/philipp/dev/node_modules/webpack/lib/Compiler.js:481:17)
    at _done (eval at create (/Users/philipp/dev/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:9:1)
    at _err1 (eval at create (/Users/philipp/dev/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:32:22)
    at _addModuleChain (/Users/philipp/dev/node_modules/webpack/lib/Compilation.js:758:12)
    at processModuleDependencies.err (/Users/philipp/dev/node_modules/webpack/lib/Compilation.js:697:9)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

Setting `maxChunks: 2` will make the script work again (as does no `LimitChunkCountPlugin` setting) but will emit an additional chunk, even when used in combination with a high `minChunkSize`. 

I'm not sure if that is related or if I should file another issue? 

@marcofugaro Does the `stats: "verbose"` give you a similar stack-trace? See: https://webpack.js.org/configuration/stats/#stats

**Comment by philipp-spiess** [comment]
Yes! Same stack-trace when I use your example repo, @marcofugaro.

```
yarn run v1.3.2
$ webpack
Hash: 79e2ded25d5795c76af3
Version: webpack 4.6.0
Time: 1265ms
Built at: 2018-05-04 11:07:42
 1 asset
Entrypoint main = vendors.a48faf74.chunk.js
chunk    {0} vendors.a48faf74.chunk.js (vendors) 151 KiB ={1}= [initial] [rendered] split chunk (cache group: vendors) (name: vendors)
    > ./src main
    14 modules
chunk    {1}  (main) 168 bytes ={0}= [entry]
    > ./src main
 [14] ./src/index.js 168 bytes {1} [depth 0] [built]
      [no exports]
      ModuleConcatenation bailout: Module is an entry point
      single entry ./src  main

ERROR in chunk main [entry]
app.[contenthash:8].js
Cannot convert undefined or null to object
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at javascript (/Users/philipp/dev/webpack-issue-repo/node_modules/webpack/lib/web/JsonpMainTemplatePlugin.js:91:37)
    at fn (/Users/philipp/dev/webpack-issue-repo/node_modules/webpack/lib/TemplatedPathPlugin.js:29:11)
    at String.replace (<anonymous>)
    at replacePathVariables (/Users/philipp/dev/webpack-issue-repo/node_modules/webpack/lib/TemplatedPathPlugin.js:98:5)
    at SyncWaterfallHook.eval [as call] (eval at create (/Users/philipp/dev/webpack-issue-repo/node_modules/tapable/lib/HookCodeFactory.js:17:12), <anonymous>:7:16)
    at MainTemplate.getAssetPath (/Users/philipp/dev/webpack-issue-repo/node_modules/webpack/lib/MainTemplate.js:387:31)
    at getScriptSrcPath (/Users/philipp/dev/webpack-issue-repo/node_modules/webpack/lib/web/JsonpMainTemplatePlugin.js:57:24)
    at mainTemplate.hooks.localVars.tap (/Users/philipp/dev/webpack-issue-repo/node_modules/webpack/lib/web/JsonpMainTemplatePlugin.js:127:48)
    at SyncWaterfallHook.eval [as call] (eval at create (/Users/philipp/dev/webpack-issue-repo/node_modules/tapable/lib/HookCodeFactory.js:17:12), <anonymous>:12:16)
    at SyncWaterfallHook.lazyCompileHook [as _call] (/Users/philipp/dev/webpack-issue-repo/node_modules/tapable/lib/Hook.js:35:21)
    at MainTemplate.render (/Users/philipp/dev/webpack-issue-repo/node_modules/webpack/lib/MainTemplate.js:318:33)
    at Object.render (/Users/philipp/dev/webpack-issue-repo/node_modules/webpack/lib/JavascriptModulesPlugin.js:67:34)
    at Compilation.createChunkAssets (/Users/philipp/dev/webpack-issue-repo/node_modules/webpack/lib/Compilation.js:1772:29)
    at hooks.optimizeTree.callAsync.err (/Users/philipp/dev/webpack-issue-repo/node_modules/webpack/lib/Compilation.js:942:10)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/philipp/dev/webpack-issue-repo/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/Users/philipp/dev/webpack-issue-repo/node_modules/tapable/lib/Hook.js:35:21)
    at Compilation.seal (/Users/philipp/dev/webpack-issue-repo/node_modules/webpack/lib/Compilation.js:890:27)
    at hooks.make.callAsync.err (/Users/philipp/dev/webpack-issue-repo/node_modules/webpack/lib/Compiler.js:481:17)
    at _err0 (eval at create (/Users/philipp/dev/webpack-issue-repo/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:11:1)
    at _addModuleChain (/Users/philipp/dev/webpack-issue-repo/node_modules/webpack/lib/Compilation.js:758:12)
    at processModuleDependencies.err (/Users/philipp/dev/webpack-issue-repo/node_modules/webpack/lib/Compilation.js:697:9)
    at process._tickCallback (internal/process/next_tick.js:112:11)
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by samuelcastro** [comment]
I'm still facing the same issue with `new webpack.optimize.LimitChunkCountPlugin({ maxChunks: 1 })`.

**Comment by evilebottnawi** [comment]
@samuelcastro please open new issue with reproducible test repo, thanks

**Comment by ToonvanStrijp** [comment]
@evilebottnawi I'm having the same problem when using `monaco-webpack-plugin` the plugin internally uses `new webpack.optimize.LimitChunkCountPlugin({ maxChunks: 1 })` I created a small repo with this issue, just run `npm run build` and you'll see the error.

The `monaco-webpack-plugin` is added on line `674` inside the `./config/webpack.config.js` file. If you disable this line the build works.

[my-app.zip](https://github.com/webpack/webpack/files/3864414/my-app.zip)

**Comment by evilebottnawi** [comment]
@ToonvanStrijp please open new issue and use issue template, thanks!
