### ISSUE TITLE
Importing CSS deps?

### ISSUE THREAD

**Issue by jasonkuhrt** [webpack/webpack#722]
I can't figure this out. None of these work:

```css
@import '~littlebits-ui/lib/index.css';

@import './lib/base';
@import './lib/view-app';
...
```

```css
@import '~littlebits-ui/lib/index';

@import './lib/base';
@import './lib/view-app';
...
```

```css
@import '~littlebits-ui/lib';

@import './lib/base';
@import './lib/view-app';
...
```

```css
@import 'littlebits-ui';

@import './lib/base';
@import './lib/view-app';
...
```

All end with an error along the lines of:

```
ERROR in ./~/css-loader?importLoaders=1!./~/cssnext!./lib/index.css
Module build failed: Error: <css input>:1:1: Failed to find '~littlebits-ui/lib/index.css' from /Users/jasonkuhrt/projects/cloud-app-cloud-control
    in [
        /Users/jasonkuhrt/projects/cloud-app-cloud-control
    ]
    at <css input>:1:1
    at resolveFilename (/Users/jasonkuhrt/projects/cloud-app-cloud-control/node_modules/cssnext/node_modules/postcss-import/index.js:271:11)
    at readAtImport (/Users/jasonkuhrt/projects/cloud-app-cloud-control/node_modules/cssnext/node_modules/postcss-import/index.js:139:26)
    at transformAtImport (/Users/jasonkuhrt/projects/cloud-app-cloud-control/node_modules/cssnext/node_modules/postcss-import/index.js:86:7)
    at Object.tryCatch [as try] (/Users/jasonkuhrt/projects/cloud-app-cloud-control/node_modules/cssnext/node_modules/postcss-import/node_modules/postcss-message-helpers/index.js:53:12)
    at checkAtRule (/Users/jasonkuhrt/projects/cloud-app-cloud-control/node_modules/cssnext/node_modules/postcss-import/index.js:85:16)
    at /Users/jasonkuhrt/projects/cloud-app-cloud-control/node_modules/cssnext/node_modules/postcss/lib/container.js:138:22
    at /Users/jasonkuhrt/projects/cloud-app-cloud-control/node_modules/cssnext/node_modules/postcss/lib/container.js:107:20
    at Root.Container.each (/Users/jasonkuhrt/projects/cloud-app-cloud-control/node_modules/cssnext/node_modules/postcss/lib/container.js:94:16)
    at Root.Container.eachInside (/Users/jasonkuhrt/projects/cloud-app-cloud-control/node_modules/cssnext/node_modules/postcss/lib/container.js:106:17)
    at Root.Container.eachAtRule (/Users/jasonkuhrt/projects/cloud-app-cloud-control/node_modules/cssnext/node_modules/postcss/lib/container.js:136:17)
 @ ./lib/index.css 4:14-272
```

**Comment by DanielApt** [comment]
Looks like an invalid path to me. Add a `/` after `~`:
 `@import '~/littlebits-ui/lib/index.css';`

Once you've got that sorted it will point to `/Users/jasonkuhrt/littlebits-ui/lib/index.css`. Is that the correct path?

**Comment by jasonkuhrt** [comment]
@DanielApt The problem was this: https://github.com/webpack/webpack/issues/725#issuecomment-71663236
