### ISSUE TITLE
Cannot import local CSS file into another

### ISSUE THREAD

**Issue by jasonkuhrt** [webpack/webpack#725]
I've been trying to fix this error without avail:
```
@import 'littlebits-ui';

@import './base';
```
```
ERROR in ./~/css-loader?root=./lib/!./~/cssnext!./lib/index.css
Module build failed: Error: <css input>:3:1: Failed to find './base' from /Users/jasonkuhrt/projects/cloud-app-cloud-control
    in [
        /Users/jasonkuhrt/projects/cloud-app-cloud-control
    ]
    at <css input>:3:1
    at resolveFilename (/Users/jasonkuhrt/projects/cloud-app-cloud-control/node_modules/cssnext/node_modules/postcss-import/index.js:271:11)
    at readAtImport (/Users/jasonkuhrt/projects/cloud-app-cloud-control/node_modules/cssnext/node_modules/postcss-import/index.js:139:26)
    at transformAtImport (/Users/jasonkuhrt/projects/cloud-app-cloud-control/node_modules/cssnext/node_modules/postcss-import/index.js:86:7)
    at Object.tryCatch [as try] (/Users/jasonkuhrt/projects/cloud-app-cloud-control/node_modules/cssnext/node_modules/postcss-import/node_modules/postcss-message-helpers/index.js:53:12)
    at checkAtRule (/Users/jasonkuhrt/projects/cloud-app-cloud-control/node_modules/cssnext/node_modules/postcss-import/index.js:85:16)
    at /Users/jasonkuhrt/projects/cloud-app-cloud-control/node_modules/cssnext/node_modules/postcss/lib/container.js:138:22
    at /Users/jasonkuhrt/projects/cloud-app-cloud-control/node_modules/cssnext/node_modules/postcss/lib/container.js:107:20
    at Root.Container.each (/Users/jasonkuhrt/projects/cloud-app-cloud-control/node_modules/cssnext/node_modules/postcss/lib/container.js:94:16)
    at Root.Container.eachInside (/Users/jasonkuhrt/projects/cloud-app-cloud-control/node_modules/cssnext/node_modules/postcss/lib/container.js:106:17)
    at Root.Container.eachAtRule (/Users/jasonkuhrt/projects/cloud-app-cloud-control/node_modules/cssnext/node_modules/postcss/lib/container.js:136:17)
 @ ./lib/index.css 4:14-268
```
```
/* Webpack Config Proper */

module.exports = {
  entry: {
    index: indexEntry
  },
  output: {
    path: outputDir,
    filename: '[name].js'
  },
  resolve: {
    root: [sourceDir]
  },
  packageMains: ['webpack', 'browser', 'web', 'browserify', ['jam', 'main'], 'style', 'main'],
  module: {
    loaders: [
    { test: /\.js$/, loaders: jsLoaders },
    { test: /\.woff$/, loaders: ['url'] },
    { test: /\.css$/, loaders: ['style', 'css?root=./lib/', 'cssnext'] },
    { test: /\.json$/, loaders: ['json'] },
    { test: /\.svg$/, loaders: ['raw'] }
    ]
  },
  devtool: devtool,
  devServer: {
    contentBase: outputDir
  },
  cssnext: {
    features: {
      import: {
        path: ['./lib']
      }
    }
  }
}
```
![screen shot 2015-01-26 at 11 25 30 pm](https://cloud.githubusercontent.com/assets/284476/5913463/b7a14802-a5b2-11e4-92d6-d14cde574614.png)

Hm, I really don't understand what's going on.

**Comment by sokra** [comment]
Report this to the cssnext-loader...

**Comment by jasonkuhrt** [comment]
@sokra @bloodyowl the issue is that I was using the `cssnext-loader` (I thought I was) like so:

```
    { test: /\.css$/, loaders: ['style', 'css', 'cssnext'] },

```

But it turns out that I didn't have `cssnext-loader` installed so `webpack` was, as far as I can tell, using `cssnext`! I wish a big-fat-error had shown up long ago.

**Comment by MoOx** [comment]
lol. We should do something about that so people don't get this again.

**Comment by jasonkuhrt** [comment]
@MoOx Yes please haha.
