### ISSUE TITLE
Unhandled rejection TypeError: Cannot read property 'modules' of undefined

### ISSUE THREAD

**Issue by Kovensky** [webpack/webpack#7262]
# Bug report

**What is the current behavior?**

```
 72% after dependencies optimization
Unhandled rejection TypeError: Cannot read property 'modules' of undefined
    at Compilation.processDependenciesBlocksForChunkGroups (.../node_modules/webpack/lib/Compilation.js:1298:38)
    at Compilation.seal (.../node_modules/webpack/lib/Compilation.js:868:8)
    at hooks.optimizeAssets.callAsync.err (.../node_modules/webpack/lib/Compilation.js:964:20)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (.../node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:9:1)
    at hooks.optimizeChunkAssets.callAsync.err (.../node_modules/webpack/lib/Compilation.js:957:32)
    at _err0 (eval at create (.../node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:16:1)
    at .../node_modules/uglifyjs-webpack-plugin/dist/index.js:334:11
    at step (.../node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:90:11)
    at done (.../node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:99:22)
    at tryCatcher (.../node_modules/cacache/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (.../node_modules/cacache/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (.../node_modules/cacache/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (.../node_modules/cacache/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (.../node_modules/cacache/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (.../node_modules/cacache/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (.../node_modules/cacache/node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler (.../node_modules/cacache/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (.../node_modules/cacache/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (.../node_modules/cacache/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (.../node_modules/cacache/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (.../node_modules/cacache/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (.../node_modules/cacache/node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler (.../node_modules/cacache/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (.../node_modules/cacache/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (.../node_modules/cacache/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (.../node_modules/cacache/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (.../node_modules/cacache/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._settlePromise (.../node_modules/cacache/node_modules/bluebird/js/release/promise.js:582:21)
    at Promise._settlePromise0 (.../node_modules/cacache/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (.../node_modules/cacache/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (.../node_modules/cacache/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (.../node_modules/cacache/node_modules/bluebird/js/release/promise.js:454:14)
    at Promise._settlePromiseFromHandler (.../node_modules/cacache/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (.../node_modules/cacache/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (.../node_modules/cacache/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (.../node_modules/cacache/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (.../node_modules/cacache/node_modules/bluebird/js/release/promise.js:638:18)
    at .../node_modules/cacache/node_modules/bluebird/js/release/nodeback.js:42:21
    at .../node_modules/graceful-fs/graceful-fs.js:121:16
    at .../node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:136:20)
```

As this is an unhandled promise rejection, the build just hangs because it's waiting for the promise to be fulfilled.

**If the current behavior is a bug, please provide the steps to reproduce.**

It seems that adding `AggressiveSplittingPlugin` to my pre-existing config causes this crash whenever a build is done with pre-existing records (`recordsPath`). Removing the records, or not enabling `recordsPath`, or building with an older records file from before the plugin was added seems to prevent the crash.

**What is the expected behavior?**

No crash.

**Other relevant information:**
webpack version:  4.8.1
Node.js version: 10.0.0
Operating System: macOS

The uglify plugin is in the stack trace, but I don't think it's involved in the crash itself. This seems to just be tracing the sequence of promise fulfilments.

Another possibly relevant plugin being used is `MiniCssExtractPlugin`.

**Comment by AMDvsTMD** [comment]
same problem
