### ISSUE TITLE
BannerPlugin: Accept a Function in addition to String/Object

### ISSUE THREAD

**Issue by ScottRudiger** [webpack/webpack#7269]
## Feature request

**What is the expected behavior?**

I'd like to see the BannerPlugin accept a function in addition to a string or an options object, similar to [`config.output.filename`](https://webpack.js.org/configuration/output/#output-filename). The function would have access to a `chunk` variable or anything else necessary for an actual reference to `'[hash]'`, `'[chunkhash]'`, `'[name]'`, `'[filebase]'`, `'[query]'`, and `'[file]'`.

**What is the motivation or use case for adding/changing the behavior?**

With references to information about each chunk being processed, the banner can be programmatically customized; for example:

```js
// webpack.config.hypothetical.js

import {BannerPlugin} from 'webpack';

// other variables declared in outer scope (libName, etc.)
const banner = new BannerPlugin(({ name }) => ({

  banner: `${libName} (${description})

${name.includes('something') ? doSomething() : elseDoSomethingElse()} v${version}

Copyright (c) 2018-present, ${author}

This source code is licensed under the ${license} license found in this library's GitHub repository (${licenseUrl}).`,

  entryOnly: true,

  // ... etc.
}));
```

**How should this be implemented in your opinion?**

I took a look at the BannerPlugin codebase and it looks doable, but there were some parts where I'm not sure what's going on. Sorry I can't be more specific at this time.

**Are you willing to work on this yourself?**

Yes, but...
- I won't have time to work on it for at least 3-4 weeks
- I'm not yet familiar with Webpack's codebase

**Comment by ooflorent** [comment]
I’ve opened a PR. Does it fit your use case?

**Comment by ScottRudiger** [comment]
Yes, I believe it does. Thanks for the quick action! I'll be sure to close this once it's merged and I try it out.

**Comment by ScottRudiger** [comment]
Actually, I'm not sure I'm doing it right, but I checked out the code with npm like so:

```json
// package.json partial
{
  "devDependencies": {
    "uglifyjs-webpack-plugin": "^1.2.5",
    "webpack": "github:webpack/webpack#pull/7270/head",
    "webpack-cli": "^2.0.15"
  }
}
```

And I got an error with this as the banner:

```js
const banner = new BannerPlugin(({chunk}) => ({
  banner: `${libNameCamel} (${description})

${chunk.name} v${version}

Copyright (c) 2017-present, ${author}

This source code is licensed under the ${license} license found in this library's
GitHub repository (${licenseUrl}).`,
  entryOnly: true,
}));
```

<details><summary><code>TypeError: str.includes is not a function</code></summary

<code>    at wrapComment (/Users/scott/Desktop/personal-projects/AsyncAF/node_modules/webpack/lib/BannerPlugin.js:16:11)
    at BannerPlugin.banner.options.raw.data (/Users/scott/Desktop/personal-projects/AsyncAF/node_modules/webpack/lib/BannerPlugin.js:45:15)
    at compilation.hooks.optimizeChunkAssets.tap.chunks (/Users/scott/Desktop/personal-projects/AsyncAF/node_modules/webpack/lib/BannerPlugin.js:101:43)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/scott/Desktop/personal-projects/AsyncAF/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:9:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/Users/scott/Desktop/personal-projects/AsyncAF/node_modules/tapable/lib/Hook.js:35:21)
    at hooks.additionalAssets.callAsync.err (/Users/scott/Desktop/personal-projects/AsyncAF/node_modules/webpack/lib/Compilation.js:952:36)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/scott/Desktop/personal-projects/AsyncAF/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/Users/scott/Desktop/personal-projects/AsyncAF/node_modules/tapable/lib/Hook.js:35:21)
    at hooks.optimizeTree.callAsync.err (/Users/scott/Desktop/personal-projects/AsyncAF/node_modules/webpack/lib/Compilation.js:948:32)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/scott/Desktop/personal-projects/AsyncAF/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/Users/scott/Desktop/personal-projects/AsyncAF/node_modules/tapable/lib/Hook.js:35:21)
    at Compilation.seal (/Users/scott/Desktop/personal-projects/AsyncAF/node_modules/webpack/lib/Compilation.js:890:27)
    at hooks.make.callAsync.err (/Users/scott/Desktop/personal-projects/AsyncAF/node_modules/webpack/lib/Compiler.js:481:17)
    at _done (eval at create (/Users/scott/Desktop/personal-projects/AsyncAF/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:9:1)
    at _err0 (eval at create (/Users/scott/Desktop/personal-projects/AsyncAF/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:20:22)
    at _addModuleChain (/Users/scott/Desktop/personal-projects/AsyncAF/node_modules/webpack/lib/Compilation.js:758:12)
    at processModuleDependencies.err (/Users/scott/Desktop/personal-projects/AsyncAF/node_modules/webpack/lib/Compilation.js:697:9)
    at process._tickCallback (internal/process/next_tick.js:172:11)</code>
</details>
