### ISSUE TITLE
Webpack follows devDependencies even in production mode

### ISSUE THREAD

**Issue by pronebird** [webpack/webpack#7451]
# Bug report

When running webpack in production mode I still see it going through `devDependencies`. In my case it enters `node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js` and dies with the following error:

```
  return sourceMap.sections != null
                   ^

TypeError: Cannot read property 'sections' of null
```

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

I expect that webpack should work and should never bother about `devDependencies`. webpack and `webpack-cli` are both registered under `devDependencies`.

**Other relevant information:**
webpack version:  4.10.2
Node.js version: v8.11.2
Operating System: macOS
Additional tools:

**Comment by ooflorent** [comment]
I don’t see any issue here. Could you elaborate what’s wrong?

**Comment by montogeek** [comment]
Uglify plugin is used for webpack to mangle and optimize your dependencies, it is normal behavior.

**Comment by pronebird** [comment]
Alright, I must have misinterpreted the error log. Basically I have a crash then in uglify plugin:

```
$ /app/node_modules/.bin/webpack --verbose
/app/node_modules/uglifyjs-webpack-plugin/node_modules/source-map/lib/source-map-consumer.js:20
  return sourceMap.sections != null
                   ^

TypeError: Cannot read property 'sections' of null
    at new SourceMapConsumer (/app/node_modules/uglifyjs-webpack-plugin/node_modules/source-map/lib/source-map-consumer.js:20:20)
    at UglifyJsPlugin.buildError (/app/node_modules/uglifyjs-webpack-plugin/dist/index.js:116:23)
    at /app/node_modules/uglifyjs-webpack-plugin/dist/index.js:275:45
    at Array.forEach (<anonymous>)
    at /app/node_modules/uglifyjs-webpack-plugin/dist/index.js:259:19
    at step (/app/node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:90:11)
    at done (/app/node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:99:22)
    at /app/node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:105:15
    at /app/node_modules/worker-farm/lib/farm.js:191:19
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by evilebottnawi** [comment]
@pronebird Looks you have broken map, what version uglify you use?

**Comment by atdiff** [comment]
@pronebird I encountered a similar error and was able to fix it by adding the following line to the config:
`devtool: "source-map"`

**Comment by evilebottnawi** [comment]
@probablyup @atdiff can you create minimum reproducible test repo?

**Comment by jorisroling** [comment]
+1

**Comment by evilebottnawi** [comment]
@jorisroling Can you create minimum reproducible test repo?

**Comment by jorisroling** [comment]
Sorry, that would involve shipping our entire code...
