### ISSUE TITLE
TypeError: Cannot read property 'validateSchema' of undefined    

### ISSUE THREAD

**Issue by Rohit5890** [webpack/webpack#7464]
**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**
\node_modules\webpack-cli\bin\convert-argv.js:7
const validateSchema = process.webpackModule.validateSchema;
                                             ^

TypeError: Cannot read property 'validateSchema' of undefined
    at Object.<anonymous> (K:\web\07_Webpack_Test\node_modules\webpack-cli\bin\convert-argv.js:7:46)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (K:\web\07_Webpack_Test\node_modules\webpack-dev-server\bin\webpack-dev-server.js:234:15)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
npm ERR! code ELIFECYCLE
**If the current behavior is a bug, please provide the steps to reproduce.**
With webpack-cli 3.0.0 execute npm start script

**What is the expected behavior?**
The above operation should produce a bundle as per config file.
**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
"webpack": "v4.10.2"
"webpack-cli": "v3.0.0"
"node":"v8.9.3"
"OS": "windows"

**Comment by hermawan22** [comment]
Hi @Rohit5890, you can reference that issue in here https://github.com/webpack/webpack-cli/issues/477

They working on it.

**Comment by ev1stensberg** [comment]
Fixed now.

**Comment by IzaGz** [comment]
@ev1stensberg hello , how you fixed?

**Comment by ev1stensberg** [comment]
Upgrade to webpack-cli `v.3.0.2` or higher @IzaGz
