### ISSUE TITLE
Plugin API: `Invalid arguments to tap` when trying to access normalModuleFactory hooks

### ISSUE THREAD

**Issue by mshaaban0** [webpack/webpack#7468]
# Bug report

**What is the current behavior?**
Based on the documentation [here](https://webpack.js.org/api/parser), I'm trying to access the `parser` instance, but I'm getting the following error:
```bash
Error: Invalid arguments to tap(options: Object, fn: function)
    at SyncHook.tap (/Users/maboueltayb/Projects/webpack-extract-function-arguments/node_modules/tapable/lib/Hook.js:44:10)
    at ExtractArguments.apply (/Users/maboueltayb/Projects/webpack-extract-function-arguments/src/index.js:7:40)
    at webpack (/Users/maboueltayb/Projects/webpack-extract-function-arguments/node_modules/webpack/lib/webpack.js:37:12)
    at module.exports (/Users/maboueltayb/Projects/webpack-extract-function-arguments/node_modules/webpack-command/lib/compiler.js:84:20)
    at load.then (/Users/maboueltayb/Projects/webpack-extract-function-arguments/node_modules/webpack-command/lib/index.js:45:47)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
    at Function.Module.runMain (module.js:703:11)
    at startup (bootstrap_node.js:190:16)
    at bootstrap_node.js:662:3
```

**If the current behavior is a bug, please provide the steps to reproduce.**
Webpack.config.js
```js
const path = require('path')
const ExtractArguments = require('../src/index.js')

const config = {
  mode: 'development',
  entry: path.resolve(__dirname, 'index.es6.js'),
  output: {
    path: path.resolve(__dirname, 'dist'),
    libraryTarget: 'commonjs',
    filename: 'bundle.js'
  },
  plugins: [
    new ExtractArguments({
      functionName: 'HelloWorld'
    })
  ]
}

module.exports = config
```
plugin.js
```js
class ExtractArguments {
  constructor (options) {
    console.log(options)
  }

  apply (compiler) {
    compiler.hooks.normalModuleFactory.tap(factory => {
      factory.hooks.parser.tap((parser, options) => {
        console.log(parser)
      })
    })
  }
}

module.exports = ExtractArguments
```

**What is the expected behavior?**
Access to `parser` instance

**Other relevant information:**
webpack version:  `4.10.2`
Node.js version: `9.5.0`
Operating System: OSX

**Comment by ooflorent** [comment]
You are not using `tap` correctly. The first argument must be the _tapName_. The second is the _callback_.

```js
class ExtractArguments {
  constructor (options) {
    console.log(options)
  }

  apply (compiler) {
    compiler.hooks.normalModuleFactory.tap("ExtractArguments", factory => {
      factory.hooks.parser.tap("ExtractArguments", (parser, options) => {
        console.log(parser)
      })
    })
  }
}
```

**Comment by ooflorent** [comment]
Also thank you @mshaaban0 for pointing that the documentation is wrong!

**Comment by ooflorent** [comment]
Oops sorry. `parser` is a `HookMap`. You need to _tap_ into a parser:

```js
nmf.hooks.parser.for("javascript/auto").tap("MyPlugin", fn)
nmf.hooks.parser.for("javascript/dynamic").tap("MyPlugin", fn)
nmf.hooks.parser.for("javascript/esm").tap("MyPlugin", fn)
```

**Comment by nehz** [comment]
Also a lot of the parser hooks are also `HookMap` type, without documentation on the page, it is very hard to know what keys to listen for.

**Comment by mshaaban0** [comment]
@ooflorent I really recommend to re-open this issue, plugins are the main key of webpack, and it should be well documented.

**Comment by ooflorent** [comment]
Then a new issue must be opened on webpack.js.org repository.
