### ISSUE TITLE
Compilation fails when installed via pnpm: Error: Cannot find module '@webassemblyjs/utf8'

### ISSUE THREAD

**Issue by elliottsj** [webpack/webpack#7495]
# Bug report

**What is the current behavior?**
When webpack is installed via [pnpm](https://github.com/pnpm/pnpm), invoking webpack results in this error:

<details>
<summary>Error</summary>

```
Error: Cannot find module '@webassemblyjs/utf8'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (/Users/spencerelliott/Dev/elliottsj/pnpm-webpack-test/node_modules/.registry.npmjs.org/v8-compile-cache/2.0.0/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/Users/spencerelliott/Dev/elliottsj/pnpm-webpack-test/node_modules/.registry.npmjs.org/@webassemblyjs/wasm-parser/1.5.10/node_modules/@webassemblyjs/wasm-parser/lib/decoder.js:12:36)
    at Module._compile (/Users/spencerelliott/Dev/elliottsj/pnpm-webpack-test/node_modules/.registry.npmjs.org/v8-compile-cache/2.0.0/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (/Users/spencerelliott/Dev/elliottsj/pnpm-webpack-test/node_modules/.registry.npmjs.org/v8-compile-cache/2.0.0/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/Users/spencerelliott/Dev/elliottsj/pnpm-webpack-test/node_modules/.registry.npmjs.org/@webassemblyjs/wasm-parser/1.5.10/node_modules/@webassemblyjs/wasm-parser/lib/index.js:8:39)
    at Module._compile (/Users/spencerelliott/Dev/elliottsj/pnpm-webpack-test/node_modules/.registry.npmjs.org/v8-compile-cache/2.0.0/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (/Users/spencerelliott/Dev/elliottsj/pnpm-webpack-test/node_modules/.registry.npmjs.org/v8-compile-cache/2.0.0/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/Users/spencerelliott/Dev/elliottsj/pnpm-webpack-test/node_modules/.registry.npmjs.org/webpack/4.11.1/node_modules/webpack/lib/wasm/WebAssemblyParser.js:8:20)
    at Module._compile (/Users/spencerelliott/Dev/elliottsj/pnpm-webpack-test/node_modules/.registry.npmjs.org/v8-compile-cache/2.0.0/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (/Users/spencerelliott/Dev/elliottsj/pnpm-webpack-test/node_modules/.registry.npmjs.org/v8-compile-cache/2.0.0/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/Users/spencerelliott/Dev/elliottsj/pnpm-webpack-test/node_modules/.registry.npmjs.org/webpack/4.11.1/node_modules/webpack/lib/wasm/WebAssemblyModulesPlugin.js:8:27)
    at Module._compile (/Users/spencerelliott/Dev/elliottsj/pnpm-webpack-test/node_modules/.registry.npmjs.org/v8-compile-cache/2.0.0/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
```

</details>

**If the current behavior is a bug, please provide the steps to reproduce.**

```shell
$ npm install -g pnpm
$ mkdir pnpm-webpack-test
$ cd pnpm-webpack-test/
$ pnpm init -y
$ pnpm install -D webpack webpack-cli
$ echo "console.log('test')" > index.js
$ ./node_modules/.bin/webpack --mode none --entry ./index.js --output ./bundle.js
/Users/spencerelliott/Dev/elliottsj/pnpm-webpack-test/node_modules/.registry.npmjs.org/webpack-cli/3.0.3/node_modules/webpack-cli/bin/cli.js:244
				throw err;
				^

Error: Cannot find module '@webassemblyjs/utf8'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (/Users/spencerelliott/Dev/elliottsj/pnpm-webpack-test/node_modules/.registry.npmjs.org/v8-compile-cache/2.0.0/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
...
```

**What is the expected behavior?**

The compilation should complete successfully, e.g. with this output
```
Hash: 871da373394268d4db88
Version: webpack 4.11.1
Time: 86ms
Built at: 2018-06-06 16:39:18
    Asset      Size  Chunks             Chunk Names
bundle.js  3.59 KiB       0  [emitted]  null
[0] ./index.js 20 bytes {0} [built]
```

**Other relevant information:**
webpack version: 4.11.1
Node.js version: 8.11.2
Operating System: macOS 10.13.4
Additional tools: fish shell 2.7.1

**Comment by xtuc** [comment]
A fix is in progress, see https://github.com/xtuc/webassemblyjs/pull/388.

**Comment by elliottsj** [comment]
Awesome; glad a fix is on the way! I'll leave it up to you/the webpack maintainers whether they want to keep this issue open until the fix gets released.

**Comment by xtuc** [comment]
@elliottsj could you please try with Webpack v4.12.0?

**Comment by elliottsj** [comment]
Works now using v4.12.0. Thanks for the fix! 🎉
