### ISSUE TITLE
Support for default loader (file-loader) for unknown modules

### ISSUE THREAD

**Issue by pravdomil** [webpack/webpack#7615]
## Feature request

from https://github.com/facebook/create-react-app/issues/667#issuecomment-252262349:

> A catchall unknown-source loader feels like it would be pretty beneficial. 
> My opinion is that you want it managed by webpack in some way or another.

**What is the expected behavior?**

Non-javascript files without loader will be handled by `file-loader`, this can be configured in `module.fallbackLoader`.

**What is motivation or use case for adding/changing the behavior?**

Nowadays you need to list all of extensions yourself:
```js
{
  test: /\.(json|css|jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$/,
  loader: "file-loader",
}
```

**How should this be implemented in your opinion?**

```js
// webpack.config.js

module.exports = {
  module: {
    fallbackLoader: {
      loader: "url-loader",
    }
  }
}
```

**Are you willing to work on this yourself?**
yes

**Comment by TheLarkInn** [comment]
Should this be considered as a separate module type also? Something we may want to consider if no loaders applied.

**Comment by evilebottnawi** [comment]
@TheLarkInn looks already in maybe https://github.com/webpack/webpack/projects/5#card-10666456 for `webpack@5`

**Comment by sokra** [comment]
While I think it makes more sense to list all extensions explicitly you can do a `default` loaders with the `oneOf` construct in `module.rules`:

``` js
module.rules: [{
  oneOf: [
    { test: /\.js/, ... },
    { test: /\.ts/, ... },
    { use: "file-loader" }
  ]
}]
```

https://webpack.js.org/configuration/module/#rule-oneof

**Comment by pravdomil** [comment]
well that's clever but for some reason it doesn't work with `mini-css-extract-plugin`


```
ERROR in ./src/styles/style.scss
    Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
    TypeError: __webpack_require__(...) is not a function
        at Object.<anonymous> (./node_modules/css-loader/index.js!./node_modules/sass-loader/lib/loader
```

<details>
<summary>
webpack.config.js
</summary>

```js
module: {
  rules: [
    {
      oneOf: [
        {
          test: /\.(js|jsx)$/,
          loader: "babel-loader",
          options: {
            cacheDirectory: true,
            presets: [
              [
                "@babel/preset-env",
                {
                  modules: false,
                  shippedProposals: true,
                  targets: {
                    browsers: "> 1%",
                  },
                },
              ],
              "@babel/preset-react",
              "@babel/preset-stage-3",
            ],
          },
        },
        {
          test: /\.(scss|css)$/,
          use: [
            "mini-css-extract-plugin/dist/loader.js",
            "css-loader",
            "sass-loader",
          ],
        },
        {
          use: "file-loader",
        },
      ],
    },
  ],
},
```

</details>

**Comment by sokra** [comment]
hmm... seem like some file is loaded with the file-loader which should not be loaded with it...

Do you have the stats output of the child compilation?

**Comment by pravdomil** [comment]
Here

<details>
<summary>
stats.json
</summary>

```json
{
  "errors": [
    "./src/style.scss\nModule build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):\nTypeError: __webpack_require__(...) is not a function\n    at Object.<anonymous> (./node_modules/css-loader/index.js!./node_modules/sass-loader/lib/loader.js!./src/style.scss:98:50)\n    at __webpack_require__ (./node_modules/css-loader/index.js!./node_modules/sass-loader/lib/loader.js!./src/style.scss:21:30)\n    at module.exports.module.exports (./node_modules/css-loader/index.js!./node_modules/sass-loader/lib/loader.js!./src/style.scss:85:18)\n    at Object.<anonymous> (./node_modules/css-loader/index.js!./node_modules/sass-loader/lib/loader.js!./src/style.scss:88:10)\n    at Module._compile (./node_modules/v8-compile-cache/v8-compile-cache.js:178:30)\n    at exec (./node_modules/mini-css-extract-plugin/dist/loader.js:55:10)\n    at childCompiler.runAsChild (./node_modules/mini-css-extract-plugin/dist/loader.js:133:14)\n    at compile (./node_modules/webpack/lib/Compiler.js:243:11)\n    at hooks.afterCompile.callAsync.err (./node_modules/webpack/lib/Compiler.js:500:14)\n    at AsyncSeriesHook.eval [as callAsync] (eval at create (./node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:15:1)\n    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (./node_modules/tapable/lib/Hook.js:35:21)\n    at compilation.seal.err (./node_modules/webpack/lib/Compiler.js:497:30)\n    at AsyncSeriesHook.eval [as callAsync] (eval at create (./node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)\n    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (./node_modules/tapable/lib/Hook.js:35:21)\n    at hooks.optimizeAssets.callAsync.err (./node_modules/webpack/lib/Compilation.js:995:35)\n    at AsyncSeriesHook.eval [as callAsync] (eval at create (./node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)\n    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (./node_modules/tapable/lib/Hook.js:35:21)\n    at hooks.optimizeChunkAssets.callAsync.err (./node_modules/webpack/lib/Compilation.js:986:32)\n    at _err0 (eval at create (./node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:11:1)\n    at ./node_modules/uglifyjs-webpack-plugin/dist/index.js:282:11\n    at _class.runTasks (./node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:63:9)\n    at UglifyJsPlugin.optimizeFn (./node_modules/uglifyjs-webpack-plugin/dist/index.js:195:16)\n    at AsyncSeriesHook.eval [as callAsync] (eval at create (./node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:7:1)\n    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (./node_modules/tapable/lib/Hook.js:35:21)\n    at hooks.additionalAssets.callAsync.err (./node_modules/webpack/lib/Compilation.js:981:36)\n    at AsyncSeriesHook.eval [as callAsync] (eval at create (./node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)\n    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (./node_modules/tapable/lib/Hook.js:35:21)\n    at hooks.optimizeTree.callAsync.err (./node_modules/webpack/lib/Compilation.js:977:32)\n    at AsyncSeriesHook.eval [as callAsync] (eval at create (./node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)\n    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (./node_modules/tapable/lib/Hook.js:35:21)\n    at Compilation.seal (./node_modules/webpack/lib/Compilation.js:914:27)\n    at hooks.make.callAsync.err (./node_modules/webpack/lib/Compiler.js:494:17)\n    at _err0 (eval at create (./node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:11:1)\n    at _addModuleChain (./node_modules/webpack/lib/Compilation.js:783:12)\n    at processModuleDependencies.err (./node_modules/webpack/lib/Compilation.js:722:9)\n    at process._tickCallback (internal/process/next_tick.js:61:11)\n @ ./src/index.js 1:0-22"
  ],
  "warnings": [
    "configuration\nThe 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or 'production' to enable defaults for each environment.\nYou can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/concepts/mode/"
  ],
  "version": "4.14.0",
  "hash": "a55c934029de6596dc09",
  "time": 996,
  "builtAt": 1530526297737,
  "publicPath": "",
  "outputPath": "./dist",
  "assetsByChunkName": {
    "main": "main.js"
  },
  "assets": [
    {
      "name": "32634617ae3a4f18ec07bdf6e4903fe2.js",
      "size": 2260,
      "chunks": [],
      "chunkNames": []
    },
    {
      "name": "main.js",
      "size": 5829,
      "chunks": [
        0
      ],
      "chunkNames": [
        "main"
      ]
    }
  ],
  "filteredAssets": 0,
  "entrypoints": {
    "main": {
      "chunks": [
        0
      ],
      "assets": [
        "main.js"
      ],
      "children": {},
      "childAssets": {}
    }
  },
  "namedChunkGroups": {
    "main": {
      "chunks": [
        0
      ],
      "assets": [
        "main.js"
      ],
      "children": {},
      "childAssets": {}
    }
  },
  "chunks": [
    {
      "id": 0,
      "rendered": true,
      "initial": true,
      "entry": true,
      "size": 4880,
      "names": [
        "main"
      ],
      "files": [
        "main.js"
      ],
      "hash": "c069c52aa1d406b28efa",
      "siblings": [],
      "parents": [],
      "children": [],
      "childrenByOrder": {},
      "modules": [
        {
          "id": 0,
          "identifier": "./node_modules/mini-css-extract-plugin/dist/loader.js!./node_modules/css-loader/index.js!./node_modules/sass-loader/lib/loader.js!./src/style.scss",
          "name": "./src/style.scss",
          "index": 1,
          "index2": 0,
          "size": 4858,
          "cacheable": true,
          "built": true,
          "optional": false,
          "prefetched": false,
          "chunks": [
            0
          ],
          "issuer": "./node_modules/babel-loader/lib/index.js!./src/index.js",
          "issuerId": 1,
          "issuerName": "./src/index.js",
          "issuerPath": [
            {
              "id": 1,
              "identifier": "./node_modules/babel-loader/lib/index.js!./src/index.js",
              "name": "./src/index.js"
            }
          ],
          "failed": true,
          "errors": 1,
          "warnings": 0,
          "assets": [],
          "reasons": [
            {
              "moduleId": 1,
              "moduleIdentifier": "./node_modules/babel-loader/lib/index.js!./src/index.js",
              "module": "./src/index.js",
              "moduleName": "./src/index.js",
              "type": "harmony side effect evaluation",
              "userRequest": "./style.scss",
              "loc": "1:0-22"
            }
          ],
          "usedExports": false,
          "providedExports": null,
          "optimizationBailout": [
            "ModuleConcatenation bailout: Module is not an ECMAScript module"
          ],
          "depth": 1,
          "source": "throw new Error(\"Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):\\nTypeError: __webpack_require__(...) is not a function\\n    at Object.<anonymous> (./node_modules/css-loader/index.js!./node_modules/sass-loader/lib/loader.js!./src/style.scss:98:50)\\n    at __webpack_require__ (./node_modules/css-loader/index.js!./node_modules/sass-loader/lib/loader.js!./src/style.scss:21:30)\\n    at module.exports.module.exports (./node_modules/css-loader/index.js!./node_modules/sass-loader/lib/loader.js!./src/style.scss:85:18)\\n    at Object.<anonymous> (./node_modules/css-loader/index.js!./node_modules/sass-loader/lib/loader.js!./src/style.scss:88:10)\\n    at Module._compile (./node_modules/v8-compile-cache/v8-compile-cache.js:178:30)\\n    at exec (./node_modules/mini-css-extract-plugin/dist/loader.js:55:10)\\n    at childCompiler.runAsChild (./node_modules/mini-css-extract-plugin/dist/loader.js:133:14)\\n    at compile (./node_modules/webpack/lib/Compiler.js:243:11)\\n    at hooks.afterCompile.callAsync.err (./node_modules/webpack/lib/Compiler.js:500:14)\\n    at AsyncSeriesHook.eval [as callAsync] (eval at create (./node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:15:1)\\n    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (./node_modules/tapable/lib/Hook.js:35:21)\\n    at compilation.seal.err (./node_modules/webpack/lib/Compiler.js:497:30)\\n    at AsyncSeriesHook.eval [as callAsync] (eval at create (./node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)\\n    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (./node_modules/tapable/lib/Hook.js:35:21)\\n    at hooks.optimizeAssets.callAsync.err (./node_modules/webpack/lib/Compilation.js:995:35)\\n    at AsyncSeriesHook.eval [as callAsync] (eval at create (./node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)\\n    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (./node_modules/tapable/lib/Hook.js:35:21)\\n    at hooks.optimizeChunkAssets.callAsync.err (./node_modules/webpack/lib/Compilation.js:986:32)\\n    at _err0 (eval at create (./node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:11:1)\\n    at ./node_modules/uglifyjs-webpack-plugin/dist/index.js:282:11\\n    at _class.runTasks (./node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:63:9)\\n    at UglifyJsPlugin.optimizeFn (./node_modules/uglifyjs-webpack-plugin/dist/index.js:195:16)\\n    at AsyncSeriesHook.eval [as callAsync] (eval at create (./node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:7:1)\\n    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (./node_modules/tapable/lib/Hook.js:35:21)\\n    at hooks.additionalAssets.callAsync.err (./node_modules/webpack/lib/Compilation.js:981:36)\\n    at AsyncSeriesHook.eval [as callAsync] (eval at create (./node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)\\n    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (./node_modules/tapable/lib/Hook.js:35:21)\\n    at hooks.optimizeTree.callAsync.err (./node_modules/webpack/lib/Compilation.js:977:32)\\n    at AsyncSeriesHook.eval [as callAsync] (eval at create (./node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)\\n    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (./node_modules/tapable/lib/Hook.js:35:21)\\n    at Compilation.seal (./node_modules/webpack/lib/Compilation.js:914:27)\\n    at hooks.make.callAsync.err (./node_modules/webpack/lib/Compiler.js:494:17)\\n    at _err0 (eval at create (./node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:11:1)\\n    at _addModuleChain (./node_modules/webpack/lib/Compilation.js:783:12)\\n    at processModuleDependencies.err (./node_modules/webpack/lib/Compilation.js:722:9)\\n    at process._tickCallback (internal/process/next_tick.js:61:11)\");"
        },
        {
          "id": 1,
          "identifier": "./node_modules/babel-loader/lib/index.js!./src/index.js",
          "name": "./src/index.js",
          "index": 0,
          "index2": 1,
          "size": 22,
          "cacheable": true,
          "built": true,
          "optional": false,
          "prefetched": false,
          "chunks": [
            0
          ],
          "issuer": null,
          "issuerId": null,
          "issuerName": null,
          "issuerPath": null,
          "failed": false,
          "errors": 0,
          "warnings": 0,
          "assets": [],
          "reasons": [
            {
              "moduleId": null,
              "moduleIdentifier": null,
              "module": null,
              "moduleName": null,
              "type": "single entry",
              "userRequest": "./src",
              "loc": "main"
            }
          ],
          "usedExports": true,
          "providedExports": [],
          "optimizationBailout": [
            "ModuleConcatenation bailout: Module is an entry point"
          ],
          "depth": 0,
          "source": "import \"./style.scss\";"
        }
      ],
      "filteredModules": 0,
      "origins": [
        {
          "module": "",
          "moduleIdentifier": "",
          "moduleName": "",
          "loc": "main",
          "request": "./src",
          "reasons": []
        }
      ]
    }
  ],
  "modules": [
    {
      "id": 0,
      "identifier": "./node_modules/mini-css-extract-plugin/dist/loader.js!./node_modules/css-loader/index.js!./node_modules/sass-loader/lib/loader.js!./src/style.scss",
      "name": "./src/style.scss",
      "index": 1,
      "index2": 0,
      "size": 4858,
      "cacheable": true,
      "built": true,
      "optional": false,
      "prefetched": false,
      "chunks": [
        0
      ],
      "issuer": "./node_modules/babel-loader/lib/index.js!./src/index.js",
      "issuerId": 1,
      "issuerName": "./src/index.js",
      "issuerPath": [
        {
          "id": 1,
          "identifier": "./node_modules/babel-loader/lib/index.js!./src/index.js",
          "name": "./src/index.js"
        }
      ],
      "failed": true,
      "errors": 1,
      "warnings": 0,
      "assets": [],
      "reasons": [
        {
          "moduleId": 1,
          "moduleIdentifier": "./node_modules/babel-loader/lib/index.js!./src/index.js",
          "module": "./src/index.js",
          "moduleName": "./src/index.js",
          "type": "harmony side effect evaluation",
          "userRequest": "./style.scss",
          "loc": "1:0-22"
        }
      ],
      "usedExports": false,
      "providedExports": null,
      "optimizationBailout": [
        "ModuleConcatenation bailout: Module is not an ECMAScript module"
      ],
      "depth": 1,
      "source": "throw new Error(\"Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):\\nTypeError: __webpack_require__(...) is not a function\\n    at Object.<anonymous> (./node_modules/css-loader/index.js!./node_modules/sass-loader/lib/loader.js!./src/style.scss:98:50)\\n    at __webpack_require__ (./node_modules/css-loader/index.js!./node_modules/sass-loader/lib/loader.js!./src/style.scss:21:30)\\n    at module.exports.module.exports (./node_modules/css-loader/index.js!./node_modules/sass-loader/lib/loader.js!./src/style.scss:85:18)\\n    at Object.<anonymous> (./node_modules/css-loader/index.js!./node_modules/sass-loader/lib/loader.js!./src/style.scss:88:10)\\n    at Module._compile (./node_modules/v8-compile-cache/v8-compile-cache.js:178:30)\\n    at exec (./node_modules/mini-css-extract-plugin/dist/loader.js:55:10)\\n    at childCompiler.runAsChild (./node_modules/mini-css-extract-plugin/dist/loader.js:133:14)\\n    at compile (./node_modules/webpack/lib/Compiler.js:243:11)\\n    at hooks.afterCompile.callAsync.err (./node_modules/webpack/lib/Compiler.js:500:14)\\n    at AsyncSeriesHook.eval [as callAsync] (eval at create (./node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:15:1)\\n    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (./node_modules/tapable/lib/Hook.js:35:21)\\n    at compilation.seal.err (./node_modules/webpack/lib/Compiler.js:497:30)\\n    at AsyncSeriesHook.eval [as callAsync] (eval at create (./node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)\\n    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (./node_modules/tapable/lib/Hook.js:35:21)\\n    at hooks.optimizeAssets.callAsync.err (./node_modules/webpack/lib/Compilation.js:995:35)\\n    at AsyncSeriesHook.eval [as callAsync] (eval at create (./node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)\\n    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (./node_modules/tapable/lib/Hook.js:35:21)\\n    at hooks.optimizeChunkAssets.callAsync.err (./node_modules/webpack/lib/Compilation.js:986:32)\\n    at _err0 (eval at create (./node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:11:1)\\n    at ./node_modules/uglifyjs-webpack-plugin/dist/index.js:282:11\\n    at _class.runTasks (./node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:63:9)\\n    at UglifyJsPlugin.optimizeFn (./node_modules/uglifyjs-webpack-plugin/dist/index.js:195:16)\\n    at AsyncSeriesHook.eval [as callAsync] (eval at create (./node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:7:1)\\n    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (./node_modules/tapable/lib/Hook.js:35:21)\\n    at hooks.additionalAssets.callAsync.err (./node_modules/webpack/lib/Compilation.js:981:36)\\n    at AsyncSeriesHook.eval [as callAsync] (eval at create (./node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)\\n    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (./node_modules/tapable/lib/Hook.js:35:21)\\n    at hooks.optimizeTree.callAsync.err (./node_modules/webpack/lib/Compilation.js:977:32)\\n    at AsyncSeriesHook.eval [as callAsync] (eval at create (./node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)\\n    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (./node_modules/tapable/lib/Hook.js:35:21)\\n    at Compilation.seal (./node_modules/webpack/lib/Compilation.js:914:27)\\n    at hooks.make.callAsync.err (./node_modules/webpack/lib/Compiler.js:494:17)\\n    at _err0 (eval at create (./node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:11:1)\\n    at _addModuleChain (./node_modules/webpack/lib/Compilation.js:783:12)\\n    at processModuleDependencies.err (./node_modules/webpack/lib/Compilation.js:722:9)\\n    at process._tickCallback (internal/process/next_tick.js:61:11)\");"
    },
    {
      "id": 1,
      "identifier": "./node_modules/babel-loader/lib/index.js!./src/index.js",
      "name": "./src/index.js",
      "index": 0,
      "index2": 1,
      "size": 22,
      "cacheable": true,
      "built": true,
      "optional": false,
      "prefetched": false,
      "chunks": [
        0
      ],
      "issuer": null,
      "issuerId": null,
      "issuerName": null,
      "issuerPath": null,
      "failed": false,
      "errors": 0,
      "warnings": 0,
      "assets": [],
      "reasons": [
        {
          "moduleId": null,
          "moduleIdentifier": null,
          "module": null,
          "moduleName": null,
          "type": "single entry",
          "userRequest": "./src",
          "loc": "main"
        }
      ],
      "usedExports": true,
      "providedExports": [],
      "optimizationBailout": [
        "ModuleConcatenation bailout: Module is an entry point"
      ],
      "depth": 0,
      "source": "import \"./style.scss\";"
    }
  ],
  "filteredModules": 0,
  "children": [
    {
      "errors": [],
      "warnings": [],
      "publicPath": "",
      "outputPath": "./dist",
      "assetsByChunkName": {},
      "assets": [
        {
          "name": "32634617ae3a4f18ec07bdf6e4903fe2.js",
          "size": 2260,
          "chunks": [],
          "chunkNames": []
        }
      ],
      "filteredAssets": 0,
      "entrypoints": {
        "mini-css-extract-plugin": {
          "chunks": [
            0
          ],
          "assets": [
            "*"
          ],
          "children": {},
          "childAssets": {}
        }
      },
      "namedChunkGroups": {
        "mini-css-extract-plugin": {
          "chunks": [
            0
          ],
          "assets": [
            "*"
          ],
          "children": {},
          "childAssets": {}
        }
      },
      "chunks": [
        {
          "id": 0,
          "rendered": true,
          "initial": true,
          "entry": true,
          "size": 269,
          "names": [
            "mini-css-extract-plugin"
          ],
          "files": [
            "*"
          ],
          "hash": "3b5bcce3eb884cb72f71",
          "siblings": [],
          "parents": [],
          "children": [],
          "childrenByOrder": {},
          "modules": [
            {
              "id": 0,
              "identifier": "./node_modules/file-loader/dist/cjs.js!./node_modules/css-loader/lib/css-base.js",
              "name": "./node_modules/css-loader/lib/css-base.js",
              "index": 1,
              "index2": 0,
              "size": 81,
              "cacheable": true,
              "built": true,
              "optional": false,
              "prefetched": false,
              "chunks": [
                0
              ],
              "issuer": "./node_modules/css-loader/index.js!./node_modules/sass-loader/lib/loader.js!./src/style.scss",
              "issuerId": 1,
              "issuerName": "./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js!./src/style.scss",
              "issuerPath": [
                {
                  "id": 1,
                  "identifier": "./node_modules/css-loader/index.js!./node_modules/sass-loader/lib/loader.js!./src/style.scss",
                  "name": "./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js!./src/style.scss"
                }
              ],
              "failed": false,
              "errors": 0,
              "warnings": 0,
              "assets": [
                "32634617ae3a4f18ec07bdf6e4903fe2.js"
              ],
              "reasons": [
                {
                  "moduleId": 1,
                  "moduleIdentifier": "./node_modules/css-loader/index.js!./node_modules/sass-loader/lib/loader.js!./src/style.scss",
                  "module": "./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js!./src/style.scss",
                  "moduleName": "./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js!./src/style.scss",
                  "type": "cjs require",
                  "userRequest": "../node_modules/css-loader/lib/css-base.js",
                  "loc": "1:27-80"
                }
              ],
              "usedExports": true,
              "providedExports": null,
              "optimizationBailout": [
                "ModuleConcatenation bailout: Module is not an ECMAScript module"
              ],
              "depth": 1,
              "source": "module.exports = __webpack_public_path__ + \"32634617ae3a4f18ec07bdf6e4903fe2.js\";"
            },
            {
              "id": 1,
              "identifier": "./node_modules/css-loader/index.js!./node_modules/sass-loader/lib/loader.js!./src/style.scss",
              "name": "./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js!./src/style.scss",
              "index": 0,
              "index2": 1,
              "size": 188,
              "cacheable": true,
              "built": true,
              "optional": false,
              "prefetched": false,
              "chunks": [
                0
              ],
              "issuer": null,
              "issuerId": null,
              "issuerName": null,
              "issuerPath": null,
              "failed": false,
              "errors": 0,
              "warnings": 0,
              "assets": [],
              "reasons": [
                {
                  "moduleId": null,
                  "moduleIdentifier": null,
                  "module": null,
                  "moduleName": null,
                  "type": "single entry",
                  "userRequest": "!!./node_modules/css-loader/index.js!./node_modules/sass-loader/lib/loader.js!./src/style.scss",
                  "loc": "mini-css-extract-plugin"
                }
              ],
              "usedExports": true,
              "providedExports": null,
              "optimizationBailout": [
                "ModuleConcatenation bailout: Module is not an ECMAScript module"
              ],
              "depth": 0,
              "source": "exports = module.exports = require(\"../node_modules/css-loader/lib/css-base.js\")(false);\n// imports\n\n\n// module\nexports.push([module.id, \"body {\\n  color: hotpink; }\\n\", \"\"]);\n\n// exports\n"
            }
          ],
          "filteredModules": 0,
          "origins": [
            {
              "module": "",
              "moduleIdentifier": "",
              "moduleName": "",
              "loc": "mini-css-extract-plugin",
              "request": "!!./node_modules/css-loader/index.js!./node_modules/sass-loader/lib/loader.js!./src/style.scss",
              "reasons": []
            }
          ]
        }
      ],
      "modules": [
        {
          "id": 0,
          "identifier": "./node_modules/file-loader/dist/cjs.js!./node_modules/css-loader/lib/css-base.js",
          "name": "./node_modules/css-loader/lib/css-base.js",
          "index": 1,
          "index2": 0,
          "size": 81,
          "cacheable": true,
          "built": true,
          "optional": false,
          "prefetched": false,
          "chunks": [
            0
          ],
          "issuer": "./node_modules/css-loader/index.js!./node_modules/sass-loader/lib/loader.js!./src/style.scss",
          "issuerId": 1,
          "issuerName": "./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js!./src/style.scss",
          "issuerPath": [
            {
              "id": 1,
              "identifier": "./node_modules/css-loader/index.js!./node_modules/sass-loader/lib/loader.js!./src/style.scss",
              "name": "./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js!./src/style.scss"
            }
          ],
          "failed": false,
          "errors": 0,
          "warnings": 0,
          "assets": [
            "32634617ae3a4f18ec07bdf6e4903fe2.js"
          ],
          "reasons": [
            {
              "moduleId": 1,
              "moduleIdentifier": "./node_modules/css-loader/index.js!./node_modules/sass-loader/lib/loader.js!./src/style.scss",
              "module": "./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js!./src/style.scss",
              "moduleName": "./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js!./src/style.scss",
              "type": "cjs require",
              "userRequest": "../node_modules/css-loader/lib/css-base.js",
              "loc": "1:27-80"
            }
          ],
          "usedExports": true,
          "providedExports": null,
          "optimizationBailout": [
            "ModuleConcatenation bailout: Module is not an ECMAScript module"
          ],
          "depth": 1,
          "source": "module.exports = __webpack_public_path__ + \"32634617ae3a4f18ec07bdf6e4903fe2.js\";"
        },
        {
          "id": 1,
          "identifier": "./node_modules/css-loader/index.js!./node_modules/sass-loader/lib/loader.js!./src/style.scss",
          "name": "./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js!./src/style.scss",
          "index": 0,
          "index2": 1,
          "size": 188,
          "cacheable": true,
          "built": true,
          "optional": false,
          "prefetched": false,
          "chunks": [
            0
          ],
          "issuer": null,
          "issuerId": null,
          "issuerName": null,
          "issuerPath": null,
          "failed": false,
          "errors": 0,
          "warnings": 0,
          "assets": [],
          "reasons": [
            {
              "moduleId": null,
              "moduleIdentifier": null,
              "module": null,
              "moduleName": null,
              "type": "single entry",
              "userRequest": "!!./node_modules/css-loader/index.js!./node_modules/sass-loader/lib/loader.js!./src/style.scss",
              "loc": "mini-css-extract-plugin"
            }
          ],
          "usedExports": true,
          "providedExports": null,
          "optimizationBailout": [
            "ModuleConcatenation bailout: Module is not an ECMAScript module"
          ],
          "depth": 0,
          "source": "exports = module.exports = require(\"../node_modules/css-loader/lib/css-base.js\")(false);\n// imports\n\n\n// module\nexports.push([module.id, \"body {\\n  color: hotpink; }\\n\", \"\"]);\n\n// exports\n"
        }
      ],
      "filteredModules": 0,
      "children": [],
      "name": "mini-css-extract-plugin node_modules/css-loader/index.js!node_modules/sass-loader/lib/loader.js!src/style.scss"
    }
  ]
}

```

</details>

**Comment by sokra** [comment]
Your config loads all `.js` files that are in `node_modules` with the `file-loader` (because of the first rule). That's wrong.

Maybe add a rule like that `{ test: /\.js$/ }` just before the fallback rule:

**Comment by pravdomil** [comment]
make sense, now it works, that solves problem for me, thanks for help, final config:

```js
const MiniCssExtractPlugin = require("mini-css-extract-plugin");

module.exports = {
  module: {
    rules: [
      {
        oneOf: [
          {
            test: /\.js$/,
            exclude: /node_modules/,
            loader: "babel-loader"
          },
          {
            test: /\.css$/,
            use: ["mini-css-extract-plugin/dist/loader.js", "css-loader"]
          },
          {
            exclude: /\.(js|mjs|json|wasm)$/,
            use: "file-loader"
          }
        ]
      }
    ]
  },
  plugins: [new MiniCssExtractPlugin()]
};
```

**Comment by evilebottnawi** [comment]
Bump

**Comment by evilebottnawi** [comment]
Bump, maybe we can do this for webpack@5
/cc @sokra

**Comment by terrylinooo** [comment]
I don't why `exclude: /node_modules/,` but it solved my problem.

**Comment by edmorley** [comment]
Unstale

**Comment by evilebottnawi** [comment]
bump
