### ISSUE TITLE
Webpack get error when build it

### ISSUE THREAD

**Issue by Thilinam93** [webpack/webpack#7729]
D:\express\test-app\node_modules\webpack-cli\bin\cli.js:244
                                throw err;
                                ^

Error: Cannot find module 'json-parse-better-errors'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (D:\express\test-app\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (C:\Users\Madushan\AppData\Roaming\npm\node_modules\webpack\lib\Compiler.js:7:19)
    at Module._compile (D:\express\test-app\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (D:\express\test-app\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (C:\Users\Madushan\AppData\Roaming\npm\node_modules\webpack\lib\webpack.js:7:18)
    at Module._compile (D:\express\test-app\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (D:\express\test-app\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (D:\express\test-app\node_modules\webpack-cli\bin\convert-argv.js:7:24)
    at Module._compile (D:\express\test-app\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at yargs.parse (D:\express\test-app\node_modules\webpack-cli\bin\cli.js:241:14)
    at Object.parse (D:\express\test-app\node_modules\webpack-cli\node_modules\yargs\yargs.js:552:18)

**Comment by wusatosi** [comment]
Did you installed the 'json-parse-better-errors' plugin in npm?

**Comment by Thilinam93** [comment]
Yes. Already installed .but same problem here

**Comment by montogeek** [comment]
@webpack-bot move to webpack/webpack-cli

**Comment by manishgkp077** [comment]
Hi,
Same problem here as:

E:\EXTRA\webpack_projects\divisima\node_modules\webpack-cli\bin\cli.js:231
                                throw err;
                                ^

false

Please suggest, how can solve?
