### ISSUE TITLE
[webpack-command] Maximum call stack size exceeded

### ISSUE THREAD

**Issue by damianobarbati** [webpack/webpack#7731]
**What happens**?
I'm building a package with ~2400 entrypoints (converted to 1 on 1 to transpiled files, an icon set).
Here what happens:
```
$ NODE_ENV=production yarn webpack --config ./webpack.config.js --mode production --progress
clean-webpack-plugin: /Users/damz/Desktop/muicons/dist has been removed.
ℹ ｢webpack｣: Starting Build
✖ ｢command｣: A webpack error occured while building: use --log-level=debug for more error detail
✖ ｢command｣: Maximum call stack size exceeded
error Command failed with exit code 1.
```

I tried giving more memory to webpack but problem persist thus I don't think that's the problem:
```
NODE_ENV=development node --max_old_space_size=8192 ./node_modules/webpack/bin/webpack.js --config ./webpack.config.js --mode development --progress --watch
```

**How to reproduce?**
```
git clone https://github.com/damianobarbati/muicons/tree/dist
git checkout dist
yarn install
yarn build:prod
```

**Side question**
Furthermore... how come the index.js is tremendously big compared to original untranspiled one (100kb vs 3mb)? :|

**Comment by sokra** [comment]
> use --log-level=debug for more error detail

A stack trace would be great

**Comment by damianobarbati** [comment]
Sorry! Here it is:
```
imac:muicons damz$ yarn build:prod
yarn run v1.7.0
$ NODE_ENV=production node --max_old_space_size=8192 ./node_modules/webpack/bin/webpack.js --config ./webpack.config.js --mode production --progress
clean-webpack-plugin: /Users/damz/Desktop/muicons/dist has been removed.
ℹ ｢webpack｣: Starting Build
✖ ｢command｣: A webpack error occured while building: use --log-level=debug for more error detail
✖ ｢command｣: Maximum call stack size exceeded
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
imac:muicons damz$ yarn build:prod --log-level=debug
yarn run v1.7.0
$ NODE_ENV=production node --max_old_space_size=8192 ./node_modules/webpack/bin/webpack.js --config ./webpack.config.js --mode production --progress --log-level=debug
clean-webpack-plugin: /Users/damz/Desktop/muicons/dist has been removed.
ℹ ｢webpack｣: Starting Build
✖ ｢command｣: A webpack error occured while building: use --log-level=debug for more error detail
✖ ｢command｣: Maximum call stack size exceeded
➤ ｢command｣: RangeError: Maximum call stack size exceeded
    at Array.join (native)
    at SyncHookCodeFactory.args (/Users/damz/Desktop/muicons/node_modules/tapable/lib/HookCodeFactory.js:323:19)
    at SyncHookCodeFactory.callTap (/Users/damz/Desktop/muicons/node_modules/tapable/lib/HookCodeFactory.js:122:37)
    at next (/Users/damz/Desktop/muicons/node_modules/tapable/lib/HookCodeFactory.js:199:16)
    at done (/Users/damz/Desktop/muicons/node_modules/tapable/lib/HookCodeFactory.js:194:23)
    at callTap.onDone.onResult (/Users/damz/Desktop/muicons/node_modules/tapable/lib/HookCodeFactory.js:205:13)
    at SyncHookCodeFactory.callTap (/Users/damz/Desktop/muicons/node_modules/tapable/lib/HookCodeFactory.js:137:14)
    at next (/Users/damz/Desktop/muicons/node_modules/tapable/lib/HookCodeFactory.js:199:16)
    at done (/Users/damz/Desktop/muicons/node_modules/tapable/lib/HookCodeFactory.js:194:23)
    at callTap.onDone.onResult (/Users/damz/Desktop/muicons/node_modules/tapable/lib/HookCodeFactory.js:205:13)
    at SyncHookCodeFactory.callTap (/Users/damz/Desktop/muicons/node_modules/tapable/lib/HookCodeFactory.js:137:14)
    at next (/Users/damz/Desktop/muicons/node_modules/tapable/lib/HookCodeFactory.js:199:16)
    at done (/Users/damz/Desktop/muicons/node_modules/tapable/lib/HookCodeFactory.js:194:23)
    at callTap.onDone.onResult (/Users/damz/Desktop/muicons/node_modules/tapable/lib/HookCodeFactory.js:205:13)
    at SyncHookCodeFactory.callTap (/Users/damz/Desktop/muicons/node_modules/tapable/lib/HookCodeFactory.js:137:14)
    at next (/Users/damz/Desktop/muicons/node_modules/tapable/lib/HookCodeFactory.js:199:16)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
imac:muicons damz$
```

**Comment by damianobarbati** [comment]
Any idea?

**Comment by sokra** [comment]
Seem to be a problem with the number of entrypoints. Should be solved in `webpack/tabable`

**Comment by damianobarbati** [comment]
Thanks @sokra!

**Comment by damianobarbati** [comment]
@sokra do I have any chance to bypass now this 2075 maximum entrypoints limit? (I made several tests and that's seem to be the limit)

**Comment by evilebottnawi** [comment]
`webpack-command` is not officially support and deprecated, please use `webpack-cli`

**Comment by damianobarbati** [comment]
@evilebottnawi same problem with webpack-cli... why closing this?

**Comment by mems** [comment]
I've got the same issue compiling JS and CSS with [webpack-fix-style-only-entries](https://www.npmjs.com/package/webpack-fix-style-only-entries). I had circular dependencies, which I removed using [circular-dependency-plugin](https://www.npmjs.com/package/circular-dependency-plugin)
