### ISSUE TITLE
webpack4: Error: Option safe was removed

### ISSUE THREAD

**Issue by PittYong** [webpack/webpack#7743]
Hi.I upgraded the webpack to 4.16.1 in the project。when i run `npm run build`, i do not know how to fix this:

```
(node:5955) UnhandledPromiseRejectionWarning: Error: Option safe was removed. Use parser: require("postcss-safe-parser")
    at parse (/Users/pengyong/Desktop/jlb/share/node_modules/cssnano/node_modules/postcss/lib/parse.js:18:15)
    at new LazyResult (/Users/pengyong/Desktop/jlb/share/node_modules/cssnano/node_modules/postcss/lib/lazy-result.js:70:24)
    at Processor.process (/Users/pengyong/Desktop/jlb/share/node_modules/cssnano/node_modules/postcss/lib/processor.js:117:12)
    at Function.creator.process (/Users/pengyong/Desktop/jlb/share/node_modules/cssnano/node_modules/postcss/lib/postcss.js:165:43)
    at OptimizeCssAssetsWebpackPlugin.processCss (/Users/pengyong/Desktop/jlb/share/node_modules/optimize-css-assets-webpack-plugin/src/index.js:62:21)
    at Object.processor (/Users/pengyong/Desktop/jlb/share/node_modules/optimize-css-assets-webpack-plugin/src/index.js:11:18)
    at each (/Users/pengyong/Desktop/jlb/share/node_modules/last-call-webpack-plugin/src/index.js:150:10)
    at arrayEach (/Users/pengyong/Desktop/jlb/share/node_modules/lodash/_arrayEach.js:15:9)
    at forEach (/Users/pengyong/Desktop/jlb/share/node_modules/lodash/forEach.js:38:10)
    at OptimizeCssAssetsWebpackPlugin.process (/Users/pengyong/Desktop/jlb/share/node_modules/last-call-webpack-plugin/src/index.js:147:5)
    at compilation.hooks.optimizeChunkAssets.tapPromise.chunks (/Users/pengyong/Desktop/jlb/share/node_modules/last-call-webpack-plugin/src/index.js:178:28)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/pengyong/Desktop/jlb/share/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:8:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/Users/pengyong/Desktop/jlb/share/node_modules/tapable/lib/Hook.js:35:21)
    at hooks.additionalAssets.callAsync.err (/Users/pengyong/Desktop/jlb/share/node_modules/webpack/lib/Compilation.js:1270:36)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/pengyong/Desktop/jlb/share/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/Users/pengyong/Desktop/jlb/share/node_modules/tapable/lib/Hook.js:35:21)
```
So, can you help me ?

**Comment by montogeek** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

**Comment by PittYong** [comment]
ok,thanks
