### ISSUE TITLE
webpack --watch --info-verbosity verbose fails when config is an array of configs

### ISSUE THREAD

**Issue by eamodio** [webpack/webpack#7906]
# Bug report

**What is the current behavior?**

```
> webpack --watch --env.development --info-verbosity verbose

C:\Users\Eric\code\vscode-gitlens\node_modules\webpack-cli\bin\cli.js:464
                                compiler.hooks.beforeCompile.tap("WebpackInfo", compilation => {
                                                             ^

TypeError: Cannot read property 'tap' of undefined
    at processOptions (C:\Users\Eric\code\vscode-gitlens\node_modules\webpack-cli\bin\cli.js:464:34)
    at yargs.parse (C:\Users\Eric\code\vscode-gitlens\node_modules\webpack-cli\bin\cli.js:528:3)
    at Object.parse (C:\Users\Eric\code\vscode-gitlens\node_modules\webpack-cli\node_modules\yargs\yargs.js:563:18)
    at C:\Users\Eric\code\vscode-gitlens\node_modules\webpack-cli\bin\cli.js:219:8
    at Object.<anonymous> (C:\Users\Eric\code\vscode-gitlens\node_modules\webpack-cli\bin\cli.js:530:3)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Eric\code\vscode-gitlens\node_modules\webpack\bin\webpack.js:165:2)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Export multiple configs. See example: https://github.com/eamodio/vscode-gitlens/blob/develop/webpack.config.js

And run with
```
webpack --watch --env.development --info-verbosity verbose
```

**What is the expected behavior?**

It should work and add `Compilation starting…` and `Compilation finished` message around the whole operation

**Other relevant information:**
webpack version:  4.16.5
Node.js version: v8.11.3
Operating System: Windows 10 x64
Additional tools:

**Comment by sokra** [comment]
@webpack-bot move to webpack/webpack-cli
