### ISSUE TITLE
Error: Cannot find module './WebAssemblyInInitialChunkError'

### ISSUE THREAD

**Issue by vamshi9666** [webpack/webpack#7958]
# Bug report

**What is the current behavior?**
i am using webpack to bundle my react app 
everything was fine until last update 

here is my `webpack.config,js`
```

internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module './WebAssemblyInInitialChunkError'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/vamshi/my-appps/react/vamshi9666.github.io/node_modules/webpack/lib/wasm/WebAssemblyModulesPlugin.js:13:40)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vamshi9666.github.io@1.0.0 start: `webpack-dev-server --mode development  --hot`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vamshi9666.github.io@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.


```
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

i bundles with babel preset and makes a `dist ` directory of final bundled html andd css.6

Here is my log : 
```
  info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.4.0
3 info using node@v10.9.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle vamshi9666.github.io@1.0.0~prestart: vamshi9666.github.io@1.0.0
6 info lifecycle vamshi9666.github.io@1.0.0~start: vamshi9666.github.io@1.0.0
7 verbose lifecycle vamshi9666.github.io@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle vamshi9666.github.io@1.0.0~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/va$
9 verbose lifecycle vamshi9666.github.io@1.0.0~start: CWD: /home/vamshi/my-appps/react/vamshi9666.github.io
10 silly lifecycle vamshi9666.github.io@1.0.0~start: Args: [ '-c', 'webpack-dev-server --mode development  --hot' ]
11 silly lifecycle vamshi9666.github.io@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle vamshi9666.github.io@1.0.0~start: Failed to exec start script
13 verbose stack Error: vamshi9666.github.io@1.0.0 start: `webpack-dev-server --mode development  --hot`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:304:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:961:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:250:5)
14 verbose pkgid vamshi9666.github.io@1.0.0
15 verbose cwd /home/vamshi/my-appps/react/vamshi9666.github.io
16 verbose Linux 4.15.0-32-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v10.9.0
19 verbose npm  v6.4.0
20 error code ELIFECYCLE
21 error errno 1
22 error vamshi9666.github.io@1.0.0 start: `webpack-dev-server --mode development  --hot`
22 error Exit status 1
23 error Failed at the vamshi9666.github.io@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]


```
**Other relevant information:**
webpack version:  4.17.1
Node.js version: 10.9..0
Operating System:  Ubuntu 16.04 LTS x64
Additional tools:

**Comment by marvinvperez** [comment]
I'm having the same problem. What's wrong with my webpack.config.js? It is working fine on windows but not on macOS machine. [Full source code](https://github.com/AccountGo/accountgo)
```
/// <binding BeforeBuild='Run - Development' />
var webpack = require('webpack');
var path = require('path');

var buildDir = path.resolve(__dirname, './wwwroot/scripts');
var scriptsDir = path.resolve(__dirname, './wwwroot/libs/tsxbuild');

var config = {
    entry: {
        index: scriptsDir + '/home' + '/index',
        "sales/salesorder": scriptsDir + '/sales/salesorder',
        "quotations/salesquotation": scriptsDir + '/quotations/salesquotation',
        "sales/salesinvoice": scriptsDir + '/sales/salesinvoice',
        "purchasing/purchaseorder": scriptsDir + '/purchasing/purchaseorder',
        "purchasing/purchaseinvoice": scriptsDir + '/purchasing/purchaseinvoice',
        "financials/journalentry": scriptsDir + '/financials/journalentry',
        vendor: ['react', 'react-dom']
    },
    output: {
        path: buildDir,
        filename: '[name].chunk.js'
    },
    optimization: {
        splitChunks: {
            cacheGroups: {
                commons: {
                    test: /[\\/]node_modules[\\/]/,
                    name: 'vendor',
                    chunks: 'all'
                }
            }
        }
    },
    resolve: {
        extensions: ['.js', '.jsx', '.tsx']
    },
    devtool: 'source-map',
    plugins: [
        new webpack.ProvidePlugin({
            $: 'jquery',
            jQuery: 'jquery',
            'window.jQuery': 'jquery',
            Popper: ['popper.js', 'default']
        })
    ],
    externals: {
        'Config': JSON.stringify(process.env.ENV === 'production' ?
            {
                apiUrl: "https://accountgoapi.azurewebsites.net/"
                //apiUrl: "http://localhost:5000/"
            } :
            {
                apiUrl: "https://accountgoapi.azurewebsites.net/"
                //apiUrl: "http://localhost:5000/"az
            })
    }
};

module.exports = config;
```

**Comment by sokra** [comment]
Does the WebAssemblyInInitialChunkError.js file exist?

**Comment by vamshi9666** [comment]
i don't know , how i resolved this ? i just reinstalled Ubuntu and started with new and updated dependencies , it was resolved now.
