### ISSUE TITLE
Major issue with bundling probably complex ESM imports/exports. Throwing ReferenceError.

### ISSUE THREAD

**Issue by swernerx** [webpack/webpack#7996]
# Bug report

**What is the current behavior?**

Somehow Webpack seems to have issues to correctly ordering imports when string constants are involved.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Check out: https://github.com/swernerx/webpack-esm-ordering-bug
2. npm install && npm test

It's a small redux-powered application extract from our main application. We are wondering what the issue might be. Interestingly it has worked with Babel v6 before - we are just about at switching to Babel v7. But as it is some bundling issue, as it seems, I figured it's more related to Webpack than to Babel.

That's what I see locally on my console:

```
> webpack-cli && node build/server/app.js

Hash: 363e57569b6074a8e284
Version: webpack 4.17.2
Time: 320ms
Built at: 05.09.2018 16:38:52
     Asset      Size  Chunks             Chunk Names
    app.js  8.58 KiB    main  [emitted]  main
app.js.map  5.43 KiB    main  [emitted]  main
Entrypoint main = app.js app.js.map
[./src/@server/index.js] 59 bytes {main} [built]
[./src/common/actions.js] 158 bytes {main} [built]
[./src/common/redux/Store.js] 208 bytes {main} [built]
[./src/common/redux/reducers/config.js] 199 bytes {main} [built]
[./src/common/redux/reducers/index.js] 117 bytes {main} [built]
[redux] external "redux" 42 bytes {main} [built]
[redux-thunk] external "redux-thunk" 42 bytes {main} [built]
[0] multi ./src/@server/index.js 28 bytes {main} [built]
/Users/swerner/webpack-bug/node_modules/redux/lib/redux.js:425
      throw shapeAssertionError;
      ^

ReferenceError: PLATFORM_CHANGED is not defined
    at Module.PLATFORM_CHANGED (/Users/swerner/webpack-bug/build/server/app.js:114:108)
    at module.exports../src/common/redux/reducers/config.js.__webpack_exports__.default (/Users/swerner/webpack-bug/build/server/app.js:170:47)
    at /Users/swerner/webpack-bug/node_modules/redux/lib/redux.js:361:24
    at Array.forEach (<anonymous>)
    at assertReducerShape (/Users/swerner/webpack-bug/node_modules/redux/lib/redux.js:359:25)
    at combineReducers (/Users/swerner/webpack-bug/node_modules/redux/lib/redux.js:415:5)
    at Module../src/common/redux/reducers/index.js (/Users/swerner/webpack-bug/build/server/app.js:194:125)
    at __webpack_require__ (/Users/swerner/webpack-bug/build/server/app.js:21:30)
    at Module../src/common/redux/Store.js (/Users/swerner/webpack-bug/build/server/app.js:141:67)
    at __webpack_require__ (/Users/swerner/webpack-bug/build/server/app.js:21:30)
```

**What is the expected behavior?**

Ordering should work correctly and the constant `PLATFORM_CHANGED` should be resolvable.

**Other relevant information:**
webpack version: 4.17.2
Node.js version: 10.9.0
Operating System: Mac OS
Additional tools: -

**Comment by evilebottnawi** [comment]
@swernerx problem still exists?

**Comment by evilebottnawi** [comment]
Closing due to inactivity. Please test with latest version and feel free to reopen if still regressions. Thanks!
