### ISSUE TITLE
Dll Reference Plugin Invalid Options after upgrade from 4.19.1

### ISSUE THREAD

**Issue by levibotelho** [webpack/webpack#8084]
# Bug report

**What is the current behavior?**
After upgrading from 4.19.1 to 4.20.(0|1) I receive a long list of validation errors (estimate over 1000) when trying to reference a DLL bundle with the DLL Reference Plugin. These errors start with

```
[my project]\node_modules\schema-utils\src\validateOptions.js:31
    throw new ValidationError(ajv.errors, name);
    ^

ValidationError: Dll Reference Plugin Invalid Options

options.manifest.content['./node_modules/@babel/runtime/helpers/interopRequireDefault.js']['meta'] is an invalid additional property
```

and end with 

```
options.manifest.content should match some schema in anyOf
options.manifest should be string
options.manifest should match exactly one schema in oneOf
options['manifest'] is an invalid additional property
options.content is a required property
options.name is a required property
options should match some schema in anyOf

    at validateOptions ([my project]\node_modules\schema-utils\src\validateOptions.js:31:11)
    [stack trace continues...]
```

The DLL bundle was created with a separate project using Webpack 3.10.0. I don't think this matters but if it does then I'm happy to not consider this a bug and make due with 4.19.1 to retain backwards compatibility.

My DLL Reference Plugin options look like this

```
    new webpack.DllReferencePlugin({
        context: __dirname,
        manifest: require('./node_modules/[path to manifest.json file]')
    }),
```

**If the current behavior is a bug, please provide the steps to reproduce.**
Create a DLL bundle with the options above and then try to reference it with the DLL Reference Plugin using Webpack 4.20.(0|1).

**What is the expected behavior?**
I expect this to build without the validation errors as it did in Webpack 4.19.1.

**Other relevant information:**
webpack version:  4.20.(0|1)
Node.js version: 10.1.0
Operating System: Windows 10
Additional tools: DLL Plugin/DLL Reference Plugin

**Comment by evilebottnawi** [comment]
@levibotelho what version `webpack-cli` you use?

**Comment by YunWuOW** [comment]
We met a similar issue after update from 4.19.1 to 4.20.0/4.20.1

```
*/node_modules/webpack-cli/bin/config-yargs.js:89
                                describe: optionsSchema.definitions.output.properties.path.description,
                                                                           ^

TypeError: Cannot read property 'properties' of undefined
    at module.exports (*/node_modules/webpack-cli/bin/config-yargs.js:89:48)
    at */node_modules/webpack-cli/bin/webpack.js:60:27
    at Object.<anonymous> (*/node_modules/webpack-cli/bin/webpack.js:515:3)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
```

**Comment by sokra** [comment]
@levibotelho Which webpack version was used to generate this manifest file? Is this an old webpack 3 dll?

@YunWuOW This is an separate error, please upgrade webpack-cli to 3.1.1 like mentioned in the changelog.

**Comment by danrot** [comment]
@sokra I have read the changelog, but it doesn't seem to fix the issue from @YunWuOW, I am running into the same issue and updating the dependencies does not help.

```
daniel@macbook ~/D/s/sulu-minimal $ npm show webpack                                                                                                                                                           HEAD
                                                                                                                                                                                                                   
webpack@4.20.2 | MIT | deps: 24 | versions: 533                                                                                                                                                                    
Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your c
ustom stuff.                                                                                                                                                                                                       
https://github.com/webpack/webpack                                                                                                                                                                                 
                                                                                                                                                                                                                   
bin: webpack                                                                                                                                                                                                       
                                                                                                                                                                                                                   
dist                                                                                                                                                                                                               
.tarball: https://registry.npmjs.org/webpack/-/webpack-4.20.2.tgz                                                                                                                                                  
.shasum: 89f6486b6bb276a91b0823453d377501fc625b5a                                                                                                                                                                  
.integrity: sha512-75WFUMblcWYcocjSLlXCb71QuGyH7egdBZu50FtBGl2Nso8CK3Ej+J7bTZz2FPFq5l6fzCisD9modB7t30ikuA==                                                                                                        
.unpackedSize: 1.3 MB                                                                                                                                                                                              
                                                                                                                                                                                                                   
dependencies:                                                                                                                                                                                                      
@webassemblyjs/ast: 1.7.8                   ajv-keywords: ^3.1.0                        loader-runner: ^2.3.0                       node-libs-browser: ^2.0.0                                                      
@webassemblyjs/helper-module-context: 1.7.8 ajv: ^6.1.0                                 loader-utils: ^1.1.0                        schema-utils: ^0.4.4                                                           
@webassemblyjs/wasm-edit: 1.7.8             chrome-trace-event: ^1.0.0                  memory-fs: ~0.4.1                           tapable: ^1.1.0                                                                
@webassemblyjs/wasm-parser: 1.7.8           enhanced-resolve: ^4.1.0                    micromatch: ^3.1.8                          uglifyjs-webpack-plugin: ^1.2.4                                                
acorn-dynamic-import: ^3.0.0                eslint-scope: ^4.0.0                        mkdirp: ~0.5.0                              watchpack: ^1.5.0                                                              
acorn: ^5.6.2                               json-parse-better-errors: ^1.0.2            neo-async: ^2.5.0                           webpack-sources: ^1.3.0                                                        
                                                                                                                                                                                                                   
maintainers:                                                                                                                                                                                                       
- jhnns <mail@johannesewald.de>                                                                                                                                                                                    
- sokra <tobias.koppers@googlemail.com>                                                                                                                                                                            
- thelarkinn <sean.larkin@cuw.edu>                                                                                                                                                                                 
                                                                                                                                                                                                                   
dist-tags:                                                                                                                                                                                                         
latest: 4.20.2      legacy: 1.15.0      next: 4.0.0-beta.3  webpack-2: 2.7.0    webpack-3: 3.12.0                                                                                                                  
                                                                                                                                                                                                                   
published 17 hours ago by sokra <tobias.koppers@googlemail.com>                                                                                                                                                    
daniel@macbook ~/D/s/sulu-minimal $ npm show webpack-cli                                                                                                                                                       HEAD
                                                                                                                                                                                                                   
webpack-cli@3.1.1 | MIT | deps: 10 | versions: 65                                                                                                                                                                  
CLI for webpack & friends                                                                                                                                                                                          
https://github.com/webpack/webpack-cli#readme                                                                                                                                                                      
                                                                                                                                                                                                                   
keywords: webpack, cli, scaffolding, module, bundler                                                                                                                                                               
                                                                                                                                                                                                                   
bin: webpack-cli

dist
.tarball: https://registry.npmjs.org/webpack-cli/-/webpack-cli-3.1.1.tgz
.shasum: 92be3e324c1788208a301172139febb476566262
.integrity: sha512-th5EUyVeGcAAVlFOcJg11fapD/xoLRE4j/eSfrmMAo3olPjvB7lgEPUtCbRP0OGmstvnQBl4VZP+zluXWDiBxg==                                                                                                       
.unpackedSize: 156.4 kB


dependencies:
chalk: ^2.4.1               enhanced-resolve: ^4.1.0    import-local: ^2.0.0        loader-utils: ^1.1.0        v8-compile-cache: ^2.0.2                                                                          
cross-spawn: ^6.0.5         global-modules-path: ^2.3.0 interpret: ^1.1.0           supports-color: ^5.5.0      yargs: ^12.0.2                                                                                    

maintainers:
- bebraw <bebraw@gmail.com>
- ematipico <my.burning@gmail.com>
- ev1stensberg <evenstensberg@gmail.com>
- sendilkumarn <sendilkumarn@live.com>

dist-tags:
latest: 3.1.1            next: 0.0.8-development

published 3 days ago by ev1stensberg <evenstensberg@gmail.com>
daniel@macbook ~/D/s/sulu-minimal $ npm run build                                                                                                                                                              HEAD

> @ build /home/daniel/Development/sulu/sulu-minimal
> npm run clean && webpack --mode production


> @ clean /home/daniel/Development/sulu/sulu-minimal
> rimraf public/admin/build

/home/daniel/Development/sulu/sulu-minimal/node_modules/webpack-cli/bin/config-yargs.js:89
                                describe: optionsSchema.definitions.output.properties.path.description,
                                                                           ^

TypeError: Cannot read property 'properties' of undefined
    at module.exports (/home/daniel/Development/sulu/sulu-minimal/node_modules/webpack-cli/bin/config-yargs.js:89:48)                                                                                             
    at /home/daniel/Development/sulu/sulu-minimal/node_modules/webpack-cli/bin/webpack.js:60:27
    at Object.<anonymous> (/home/daniel/Development/sulu/sulu-minimal/node_modules/webpack-cli/bin/webpack.js:515:3)                                                                                              
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ build: `npm run clean && webpack --mode production`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/daniel/.npm/_logs/2018-09-26T13_50_11_738Z-debug.log
```

**Comment by sokra** [comment]
@YunWuOW @danrot This is unrelated to @levibotelho issue. Please open a separate issue.

**Comment by levibotelho** [comment]
@sokra the bundle is created with the DLL plugin in WP 3.10.0, so yes it is. I assumed that the bundle format would remain the same (as this same bundle was working perfectly with WP 4.19.1) but I could test generating the bundle with WP 4.x if you think that's the cause.

**Comment by sokra** [comment]
the `meta` property was renamed to `buildMeta` in v4. So even if it doesn't break it doesn't work correctly. There are information missing the dll, i. e. this meta information includes the list of provided exports of ESM. So i. e. warnings for incorrect imports are not emitted here.

Please rebuild the DLL with webpack 4.

**Comment by levibotelho** [comment]
Appreciate the info, thank you. Will give that a go.

**Comment by eramosr18** [comment]
> the `meta` property was renamed to `buildMeta` in v4. So even if it doesn't break it doesn't work correctly. There are information missing the dll, i. e. this meta information includes the list of provided exports of ESM. So i. e. warnings for incorrect imports are not emitted here.
> 
> Please rebuild the DLL with webpack 4.

Hi, I'm facing the same issue can you point me to how I can achieve this: "..Please rebuild the DLL with webpack 4..."

**Comment by eramosr18** [comment]
First I would like to know how to do it :D. I finally end up reverting to a minor version, I spent too much time (that I don't have) in this to make it work.

**Comment by jcoutch** [comment]
Ran across this issue while trying to upgrade a .NET SPA app from Webpack 2.x to 4.x.  In my case, webpack.config.js was using the DLL Reference Plugin for the vendor libraries:

```
plugins: [
	new webpack.DllReferencePlugin({
		context: __dirname,
		manifest: require('./ClientApp/dist/vendor-manifest.json'),
		sourceType: 'commonjs2',
		name: './vendor'
	})
]
```

The `vendor-manifest.json` file was what was causing the "Dll Reference Plugin Invalid Options" error, and after looking through the .NET SPA app's webpack.config files, found that json file was being built by `webpack.config.vendor.js`.

Simply running `webpack --config webpack.config.vendor.js` with the latest `webpack-cli` rebuilt `vendor-manifest.json` (the DLL), and allowed me to get past the error.
