### ISSUE TITLE
I am having this error while trying to get started with webpack

### ISSUE THREAD

**Issue by ogb-tammy** [webpack/webpack#8103]
TypeError: Cannot read property 'properties' of undefined
    at module.exports (C:\Users\Ogurinka Benjamin\node_modules\webpack-cli\bin\config-yargs.js:89:48)
    at C:\Users\Ogurinka Benjamin\node_modules\webpack-cli\bin\webpack.js:60:27
    at Object.<anonymous> (C:\Users\Ogurinka Benjamin\node_modules\webpack-cli\bin\webpack.js:515:3)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
