### ISSUE TITLE
Webpack v4 throw new Error("Chunk.parents: Use ChunkGroup.getParents() instead")

### ISSUE THREAD

**Issue by syedumairumar** [webpack/webpack#8131]
Did a clean installation of webpack and here's what I get everytime I try to run `webpack`

````
(node:1288) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
(node:1288) DeprecationWarning: Tapable.apply is deprecated. Call apply on the plugin directly instead
C:\Users\Umair\AppData\Roaming\npm\node_modules\webpack\lib\Chunk.js:805
                throw new Error("Chunk.parents: Use ChunkGroup.getParents() instead");
                ^

Error: Chunk.parents: Use ChunkGroup.getParents() instead
    at Chunk.get (C:\Users\Umair\AppData\Roaming\npm\node_modules\webpack\lib\Chunk.js:805:9)
    at CommonsChunkPlugin.getAffectedChunks (D:\xampp\htdocs\stonenew\wp-content\themes\stoneturngroup\node_modules\webpack\lib\optimize\CommonsChunkPlugin.js:229:18)
    at targetChunks.forEach (D:\xampp\htdocs\stonenew\wp-content\themes\stoneturngroup\node_modules\webpack\lib\optimize\CommonsChunkPlugin.js:107:34)
    at Array.forEach (<anonymous>)
    at compilation.plugin (D:\xampp\htdocs\stonenew\wp-content\themes\stoneturngroup\node_modules\webpack\lib\optimize\CommonsChunkPlugin.js:102:18)
    at SyncBailHook.eval [as call] (eval at create (C:\Users\Umair\AppData\Roaming\npm\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:7:16)
    at SyncBailHook.lazyCompileHook (C:\Users\Umair\AppData\Roaming\npm\node_modules\webpack\node_modules\tapable\lib\Hook.js:154:20)
    at Compilation.seal (C:\Users\Umair\AppData\Roaming\npm\node_modules\webpack\lib\Compilation.js:1208:30)
    at hooks.make.callAsync.err (C:\Users\Umair\AppData\Roaming\npm\node_modules\webpack\lib\Compiler.js:541:17)
    at _done (eval at create (C:\Users\Umair\AppData\Roaming\npm\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:9:1)
    at _err1 (eval at create (C:\Users\Umair\AppData\Roaming\npm\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:32:22)
    at _addModuleChain (C:\Users\Umair\AppData\Roaming\npm\node_modules\webpack\lib\Compilation.js:1066:12)
    at processModuleDependencies.err (C:\Users\Umair\AppData\Roaming\npm\node_modules\webpack\lib\Compilation.js:982:9)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

``

**Comment by montogeek** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
