### ISSUE TITLE
Unable to install webpack due to @webassemblyjs / @xtuc dependencies....

### ISSUE THREAD

**Issue by dprosper** [webpack/webpack#8159]
# Bug report

**What is the current behavior?**
1. created a new project directory 
2. npm init or yarn init
3. yarn add webpack
4. get the following errors
`[1/4] Resolving packages...
error Couldn't find package "@xtuc/long@4.2.1" required by "@webassemblyjs/wast-parser@1.7.8" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
Error: Couldn't find package "@xtuc/long@4.2.1" required by "@webassemblyjs/leb128@1.7.8" on the "npm" registry.
    at MessageError.ExtendableBuiltin (C:\Program Files (x86)\Yarn\lib\cli.js:243:66)
    at new MessageError (C:\Program Files (x86)\Yarn\lib\cli.js:272:123)
    at PackageRequest.<anonymous> (C:\Program Files (x86)\Yarn\lib\cli.js:33701:17)
    at Generator.throw (<anonymous>)
    at step (C:\Program Files (x86)\Yarn\lib\cli.js:98:30)
    at C:\Program Files (x86)\Yarn\lib\cli.js:111:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
Error: Couldn't find package "@xtuc/long@4.2.1" required by "@webassemblyjs/wast-printer@1.7.8" on the "npm" registry.
    at MessageError.ExtendableBuiltin (C:\Program Files (x86)\Yarn\lib\cli.js:243:66)
    at new MessageError (C:\Program Files (x86)\Yarn\lib\cli.js:272:123)
    at PackageRequest.<anonymous> (C:\Program Files (x86)\Yarn\lib\cli.js:33701:17)
    at Generator.throw (<anonymous>)
    at step (C:\Program Files (x86)\Yarn\lib\cli.js:98:30)
    at C:\Program Files (x86)\Yarn\lib\cli.js:111:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
Error: Couldn't find package "@xtuc/ieee754@^1.2.0" required by "@webassemblyjs/ieee754@1.7.8" on the "npm" registry.
    at MessageError.ExtendableBuiltin (C:\Program Files (x86)\Yarn\lib\cli.js:243:66)
    at new MessageError (C:\Program Files (x86)\Yarn\lib\cli.js:272:123)
    at PackageRequest.<anonymous> (C:\Program Files (x86)\Yarn\lib\cli.js:33701:17)
    at Generator.throw (<anonymous>)
    at step (C:\Program Files (x86)\Yarn\lib\cli.js:98:30)
    at C:\Program Files (x86)\Yarn\lib\cli.js:111:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)`
**If the current behavior is a bug, please provide the steps to reproduce.**
Please see above

**What is the expected behavior?**
webpack gets added to my project

**Other relevant information:**
webpack version:  latest 
Node.js version:  8.12.0 (npm: 6.4.1, yarn: 1.10.1)
Operating System:  Windows 7
Additional tools:

**Comment by dprosper** [comment]
Also note that I am able to add other npm packages to my project, i.e. babel, react,..., event webpack-cli, only the webpack package is having this issue.

**Comment by xtuc** [comment]
https://www.npmjs.com/package/@xtuc/long/v/4.2.1 is available on npm.

**Comment by xtuc** [comment]
@sokra we can close this in favor of https://github.com/xtuc/webassemblyjs/issues/462.
