### ISSUE TITLE
Building production bundle with WebAssembly fails with "Cannot read property 'importedNames' of null"

### ISSUE THREAD

**Issue by ernieturner** [webpack/webpack#8261]
# Bug report

**What is the current behavior?**

I'm attempting to build a webpack bundle which is building a WebWorker script which dynamically imports a WebAssembly module in it. I've got this configured within development mode and it works as expected, but trying to generate the bundle for production is generating me an error in the `WasmFinalizeExportsPlugin.js` file. The full error I'm seeing is

```
TypeError: Cannot read property 'importedNames' of null
    at compilation.hooks.finishModules.tap.modules (/Users/ernie/Documents/workspace/ironweb/node_modules/webpack/lib/wasm/WasmFinalizeExportsPlugin.js:33:36)
    at SyncHook.eval (eval at create (/Users/ernie/Documents/workspace/ironweb/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:9:1)
    at SyncHook.lazyCompileHook (/Users/ernie/Documents/workspace/ironweb/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.finish (/Users/ernie/Documents/workspace/ironweb/node_modules/webpack/lib/Compilation.js:1150:28)
    at hooks.make.callAsync.err (/Users/ernie/Documents/workspace/ironweb/node_modules/webpack/lib/Compiler.js:539:17)
    at _err0 (eval at create (/Users/ernie/Documents/workspace/ironweb/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:11:1)
    at _addModuleChain (/Users/ernie/Documents/workspace/ironweb/node_modules/webpack/lib/Compilation.js:1082:12)
    at processModuleDependencies.err (/Users/ernie/Documents/workspace/ironweb/node_modules/webpack/lib/Compilation.js:998:9)
    at process._tickCallback (internal/process/next_tick.js:61:11)
/Users/ernie/Documents/workspace/ironweb/node_modules/shelljs/src/common.js:401
```

This line it's erring on [is here](https://github.com/webpack/webpack/blob/d5983ed62b1bcf0b5b3e8634aa243b055357b83a/lib/wasm/WasmFinalizeExportsPlugin.js#L33) because it's not checking that the result of the `const ref = compilation.getDependencyReference(reason.module, reason.dependency);` doesn't return null. From the [source of that function](https://github.com/webpack/webpack/blob/5165a90de8e7d40c495f3d3262fe32d0aef6440d/lib/Compilation.js#L1491) it looks like it returning null is a valid result. I edited the file locally to add a simple `if(!ref) return` line and everything appears to be working just fine after that.

However, it's entirely possible that I have something else configured that would cause that function to return null, I'm just not clear what that code is trying to do.

**If the current behavior is a bug, please provide the steps to reproduce.**

I don't have a quick and simple config to show as part of this since there's a number of moving parts to my WebWorker/WebAssembly stuff, but I figured I'd open this issue anyway in the hope that I'd be able to get feedback on whether it's safe to just add a simple `if(!ref) return` line to that file I linked above. I'd definitely be up for building a quick sample if needed to help reproduce this.

**What is the expected behavior?**

Checking for the return value of that function unless there is something that is causing that function to return null when it shouldn't be in this scenario.

**Other relevant information:**
webpack version: 4.22.0
Node.js version: 10.11.0
Operating System: OSX
Additional tools:

**Comment by MaxBittker** [comment]
although webpack now builds but doesn't return, I have to kill it with control+c

**Comment by ljqx** [comment]
I can send pr for this

**Comment by ernieturner** [comment]
Checked out this fix in the 4.23.0 branch and it looks good to me. Closing.

**Comment by xtuc** [comment]
Did someone open a PR already? did you fix it locally @ernieturner?

**Comment by xtuc** [comment]
Perfect, thanks!
