### ISSUE TITLE
unable to load a raw wasm file

### ISSUE THREAD

**Issue by FranckFreiburger** [webpack/webpack#8412]
# Bug report

**What is the current behavior?**

I  try to get the raw content of a wasm file through the raw-loader:
```
module.exports = function readWasm() {
  return import('raw-loader!source-map/lib/mappings.wasm'); // see https://github.com/mozilla/source-map/blob/master/lib/mappings.wasm
}
```

Then the compilation fails with:
```
 error  in ../node_modules/source-map/lib/mappings.wasm

Module parse failed: magic header not detected
You may need an appropriate loader to handle this file type.
Error: magic header not detected
    at new CompileError (C:\xxxx\node_modules\@webassemblyjs\helper-api-error\lib\index.js:40:109)
    at parseModuleHeader (C:\xxxx\node_modules\@webassemblyjs\wasm-parser\lib\decoder.js:287:13)
    at Object.decode (C:\xxxx\node_modules\@webassemblyjs\wasm-parser\lib\decoder.js:1545:3)
    at decode (C:\xxxx\node_modules\@webassemblyjs\wasm-parser\lib\index.js:240:21)
    at WebAssemblyParser.parse (C:\xxxx\node_modules\webpack\lib\wasm\WebAssemblyParser.js:74:19)
    at doBuild.err (C:\xxxx\node_modules\webpack\lib\NormalModule.js:445:32)
    at runLoaders (C:\xxxx\node_modules\webpack\lib\NormalModule.js:327:12)
    at C:\xxxx\node_modules\loader-runner\lib\LoaderRunner.js:370:3
    at iterateNormalLoaders (C:\xxxx\node_modules\loader-runner\lib\LoaderRunner.js:211:10)
    at iterateNormalLoaders (C:\xxxx\node_modules\loader-runner\lib\LoaderRunner.js:218:10)
    at C:\xxxx\node_modules\loader-runner\lib\LoaderRunner.js:233:3
    at runSyncOrAsync (C:\xxxx\node_modules\loader-runner\lib\LoaderRunner.js:130:11)
    at iterateNormalLoaders (C:\xxxx\node_modules\loader-runner\lib\LoaderRunner.js:229:2)
    at Array.<anonymous> (C:\xxxx\node_modules\loader-runner\lib\LoaderRunner.js:202:4)
    at Storage.finished (C:\xxxx\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:43:16)
    at provider (C:\xxxx\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:79:9)
    at C:\xxxx\node_modules\graceful-fs\graceful-fs.js:78:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
```

**What is the expected behavior?**

I expect to get the wasm file content in a buffer (or string).

**Other relevant information:**
node 11.1.0
webpack 4.26.0

**Comment by chrisdothtml** [comment]
I don't think there's an official (documented) way to solve this, but there is a workaround based on [this comment](https://github.com/webpack/webpack/issues/6725#issuecomment-372182505).

There's a config property called [`module.defaultRules`](https://github.com/webpack/webpack/blob/d5e26f728adb63a1fca080ef728fd627952a921d/lib/WebpackOptionsDefaulter.js#L62-L87) that works the same way as `module.rules`, but defines the default set of rules that apply regardless of your configured `module.rules`. If you set your own `module.defaultRules`, excluding [this rule for `.wasm` files](https://github.com/webpack/webpack/blob/d5e26f728adb63a1fca080ef728fd627952a921d/lib/WebpackOptionsDefaulter.js#L83-L86), that should fix your issue. For example:

```js
module: {
  // I also left out the defaultRule for .esm files
  // since it had conditional values
  defaultRules: {
    {
      type: 'javascript/auto',
      resolve: {}
    },
    {
      test: /\.json$/i,
      type: 'json'
    }
  }
}
```

**Comment by FranckFreiburger** [comment]
thanks for the tip !

**Comment by FranckFreiburger** [comment]
Yes, it is a WebAssembly module (https://github.com/mozilla/source-map/blob/master/lib/mappings.wasm)  
that is loaded here: https://github.com/mozilla/source-map/blob/master/lib/read-wasm.js

I managed to replace their `read-wasm.js` by my own reader (through an resolve.alias in the config.)
Then, finally my reader:
```
	const wasmPath = __non_webpack_require__.resolve('source-map/lib/mappings.wasm'); // see nodeExternals whitelist
	return Promise.resolve().then(() => fs.readFileSync(wasmPath).buffer);
```

**Comment by xtuc** [comment]
Ok, by the way the module could use Webpack's wasm support directly, you just need a `./env.js` which exports a `mapping_callback` function.

As far as I know the package is used in the DevTools

**Comment by AJLoveChina** [comment]
@chrisdothtml 

I tried your advice, but got error like this :
![image](https://user-images.githubusercontent.com/11222746/58676641-84031c80-838b-11e9-9029-15505df880af.png)

Is there something I am doing wrong?

**Comment by AJLoveChina** [comment]
@chrisdothtml   
haha sorry ,  I am doing wrong, I should not set wasm file as entry point.

I have solved my issue using `copy-webpack-plugin` to copy my wasm file to specific directory.
That is all I need, Thank all of you, I love you all.
