### ISSUE TITLE
ERROR from UglifyJs - TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by Slapbox** [webpack/webpack#8415]
# Bug report
**What is the current behavior?**

When building for `electron-main` target:

```
ERROR in main.prod.js from UglifyJs
TypeError: Cannot read property 'name' of undefined
```

**[Full error text in this gist](https://gist.github.com/Slapbox/b38b4e05ccd311738b647824f813cdaa)**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

No error, or at least, a clearer error.

**Other relevant information:**
webpack version:  4.19.0
Node.js version: 10.13.0 (Windows) | 10.9.x (Linux)
Operating System: Windows 7 | Linux Mint 19
Additional tools: None (?)

**Config files:**

[webpack.config.main.prod.js](https://gist.github.com/Slapbox/9677167da2f1e0bfe597ce619afcf994)
[webpack.config.base.js](https://gist.github.com/Slapbox/d037cc6643932499f32d8f3b192cbb8c)

**Additional information**

This has been working fine for me for ages, but I had to restructure how I was handling externals and I've been suffering from this ever since. Everything works perfectly in development and everything looks like it should work perfectly in production, but I can only build my Electron renderer script, not the Electron main script. 

Any ideas even just about what this error means would be greatly appreciated!

**Comment by evilebottnawi** [comment]
Bug in `uglify-js`, better use `terser` (https://github.com/webpack-contrib/terser-webpack-plugin), also last webpack version already use `terser`, sorry we can't do anything on our side

**Comment by Slapbox** [comment]
Actually, I just noticed that unlike in 4.19.0, in 4.26.0 if I run my code without the following, it works. Not ideal, but much less critical.

```js
 optimization: {
    minimizer: [
      new TerserPlugin({
        sourceMap: generateSourcemap,
    ],
  },
```

**Comment by Slapbox** [comment]
Ah okay. Seems that the key is actually to pass:

```js
minimizer: [],
```

**Comment by BrokeRU** [comment]
Get the same error with:
* webpack@4.28.2
* terser-webpack-plugin@1.2.0

**webpack.prod.js:**
```javascript
const merge = require('webpack-merge');
const common = require('./webpack.common.js');

module.exports = merge(common, {
  mode: 'production',
});
```

Output:
```
ERROR in main.bundle.js from Terser
undefined
```

**webpack.prod.js (2nd attempt):**
```javascript
const merge = require('webpack-merge');
const common = require('./webpack.common.js');
const TerserPlugin = require('terser-webpack-plugin');

module.exports = merge(common, {
  mode: 'production',
  optimization: {
    minimizer: [
      new TerserPlugin({
        sourceMap: true,
      })
    ],
  }
});
```

Output (2nd attempt):
```
ERROR in main.bundle.js from Terser
TypeError: Cannot read property 'name' of undefined
    at C.f (/home/br0ke/git/ais2/frontend/magic/node_modules/terser/dist/bundle.js:44:143429)
    at _ (/home/br0ke/git/ais2/frontend/magic/node_modules/terser/dist/bundle.js:44:2863)
    at C (/home/br0ke/git/ais2/frontend/magic/node_modules/terser/dist/bundle.js:44:143476)
    at s (/home/br0ke/git/ais2/frontend/magic/node_modules/terser/dist/bundle.js:44:144755)
    at x (/home/br0ke/git/ais2/frontend/magic/node_modules/terser/dist/bundle.js:44:144055)
    at De (/home/br0ke/git/ais2/frontend/magic/node_modules/terser/dist/bundle.js:44:130404)
    at Je (/home/br0ke/git/ais2/frontend/magic/node_modules/terser/dist/bundle.js:44:162034)
    at /home/br0ke/git/ais2/frontend/magic/node_modules/terser/dist/bundle.js:44:212026
    at AST_Arrow.optimize (/home/br0ke/git/ais2/frontend/magic/node_modules/terser/dist/bundle.js:44:118801)
    at kt.before (/home/br0ke/git/ais2/frontend/magic/node_modules/terser/dist/bundle.js:44:118558)
    at AST_Arrow.transform (/home/br0ke/git/ais2/frontend/magic/node_modules/terser/dist/bundle.js:44:78219)
    at /home/br0ke/git/ais2/frontend/magic/node_modules/terser/dist/bundle.js:44:79841
    at kt.before (/home/br0ke/git/ais2/frontend/magic/node_modules/terser/dist/bundle.js:44:118530)
    at AST_VarDef.transform (/home/br0ke/git/ais2/frontend/magic/node_modules/terser/dist/bundle.js:44:78219)
    at /home/br0ke/git/ais2/frontend/magic/node_modules/terser/dist/bundle.js:44:78355
    at f (/home/br0ke/git/ais2/frontend/magic/node_modules/terser/dist/bundle.js:44:943)
    at n (/home/br0ke/git/ais2/frontend/magic/node_modules/terser/dist/bundle.js:44:1265)
    at t (/home/br0ke/git/ais2/frontend/magic/node_modules/terser/dist/bundle.js:44:78330)
    at /home/br0ke/git/ais2/frontend/magic/node_modules/terser/dist/bundle.js:44:79748
    at kt.before (/home/br0ke/git/ais2/frontend/magic/node_modules/terser/dist/bundle.js:44:118530)
    at AST_Const.transform (/home/br0ke/git/ais2/frontend/magic/node_modules/terser/dist/bundle.js:44:78219)
    at /home/br0ke/git/ais2/frontend/magic/node_modules/terser/dist/bundle.js:44:78355
    at f (/home/br0ke/git/ais2/frontend/magic/node_modules/terser/dist/bundle.js:44:943)
    at n (/home/br0ke/git/ais2/frontend/magic/node_modules/terser/dist/bundle.js:44:1265)
    at t (/home/br0ke/git/ais2/frontend/magic/node_modules/terser/dist/bundle.js:44:78330)
    at /home/br0ke/git/ais2/frontend/magic/node_modules/terser/dist/bundle.js:44:80035
    at kt.before (/home/br0ke/git/ais2/frontend/magic/node_modules/terser/dist/bundle.js:44:118530)
    at AST_Function.transform (/home/br0ke/git/ais2/frontend/magic/node_modules/terser/dist/bundle.js:44:78219)
    at /home/br0ke/git/ais2/frontend/magic/node_modules/terser/dist/bundle.js:44:78355
    at f (/home/br0ke/git/ais2/frontend/magic/node_modules/terser/dist/bundle.js:44:943)
    at n (/home/br0ke/git/ais2/frontend/magic/node_modules/terser/dist/bundle.js:44:1265)
    at t (/home/br0ke/git/ais2/frontend/magic/node_modules/terser/dist/bundle.js:44:78330)
    at /home/br0ke/git/ais2/frontend/magic/node_modules/terser/dist/bundle.js:44:80778
    at kt.before (/home/br0ke/git/ais2/frontend/magic/node_modules/terser/dist/bundle.js:44:118530)
    at AST_Array.transform (/home/br0ke/git/ais2/frontend/magic/node_modules/terser/dist/bundle.js:44:78219)
    at /home/br0ke/git/ais2/frontend/magic/node_modules/terser/dist/bundle.js:44:78355
```

Additional files:
* [webpack.common.js](https://pastebin.com/NEU03Bf0)
* [package.json](https://pastebin.com/4e43hPkq)

**Comment by BrokeRU** [comment]
The problem is gone if I add `">1%"` to my browserslist config (it was `"last 2 Chrome versions, last 2 Firefox versions"` initially). It seems like babel produces something brand new that Terser can't process.

**Comment by hytromo** [comment]
I have the same issue and I cannot resolve this using `>1%` in `.browerlistrc`.

In my webpack config I just use 
```
        optimization: {
            minimize: true,
        }
```
and I get

```
ERROR in main.98d8b94328164479d76d.js from Terser
undefined
```

After lots of digging I realized that this error is the `Cannot read property 'name' of undefined` one, in disguise!

If you I go inside `terser-webpack-plugin`'s `minify.js` and print the `error` returned by `terser.minify`, then you get the good old error:

```
TypeError: Cannot read property 'name' of undefined
    at l (/project/path/node_modules/terser/dist/bundle.min.js:1:145596)
    at S (/project/path/node_modules/terser/dist/bundle.min.js:1:3199)
    at y (/project/path/node_modules/terser/dist/bundle.min.js:1:145643)
    at R (/project/path/node_modules/terser/dist/bundle.min.js:1:146725)
    at K (/project/path/node_modules/terser/dist/bundle.min.js:1:132574)
    at /project/path/node_modules/terser/dist/bundle.min.js:1:165169
    at AST_BlockStatement.optimize (/project/path/node_modules/terser/dist/bundle.min.js:1:120937)
    at Mn.before (/project/path/node_modules/terser/dist/bundle.min.js:1:120693)
    at AST_BlockStatement.transform (/project/path/node_modules/terser/dist/bundle.min.js:1:80177)
    at /project/path/node_modules/terser/dist/bundle.min.js:1:80939
```

For some reason the real error is suppressed and "undefined" comes out.
