### ISSUE TITLE
Source maps have been broken

### ISSUE THREAD

**Issue by gavacho** [webpack/webpack#848]
I'm using karma-webpack in order to run unit tests.  This has recently broken after doing an `npm install`.  The exception message is:

```
WARN [preprocess]: Can not load "webpack"!
  TypeError: Cannot read property 'filename' of null
    at new SourceMapDevToolPlugin (/Users/ken/ecom-frontend/node_modules/webpack/lib/SourceMapDevToolPlugin.js:20:35)
    at OptionsApply.WebpackOptionsApply.process (/Users/ken/ecom-frontend/node_modules/webpack/lib/WebpackOptionsApply.js:191:18)
    at webpack (/Users/ken/ecom-frontend/node_modules/webpack/lib/webpack.js:23:48)
    at new Plugin (/Users/ken/ecom-frontend/node_modules/karma-webpack/index.js:51:17)
    at invoke (/Users/ken/ecom-frontend/node_modules/karma/node_modules/di/lib/injector.js:75:15)
    at Array.instantiate (/Users/ken/ecom-frontend/node_modules/karma/node_modules/di/lib/injector.js:59:20)
    at get (/Users/ken/ecom-frontend/node_modules/karma/node_modules/di/lib/injector.js:48:43)
    at /Users/ken/ecom-frontend/node_modules/karma/node_modules/di/lib/injector.js:71:14
    at Array.map (native)
    at Array.invoke (/Users/ken/ecom-frontend/node_modules/karma/node_modules/di/lib/injector.js:70:31)
```

I investigated a little bit and it appears that maybe recent changes to the `SourceMapDevToolPlugin` function do not account for the fact that null is passed from `WebpackOptionsApply`.

**Comment by sokra** [comment]
fixed by https://github.com/webpack/webpack/commit/56fb0fe6d955795ad86c086f15ef8187b26d241b
