### ISSUE TITLE
Cannot read property 'tap' of undefined

### ISSUE THREAD

**Issue by reggi** [webpack/webpack#8548]
# Bug report

I am able to recreate here https://github.com/reggi/webpack-failure

https://stackoverflow.com/questions/53916959/compiler-hooks-normalmodulefactory-tap-cannot-read-property-tap-of-undefined

**What is the current behavior?**

```
➜  webpack-failure yarn build
yarn run v1.12.3
warning package.json: No license field
$ webpack
/Users/thomas/Desktop/webpack-failure/NormalModuleReplacementPlugin.js:18
                compiler.hooks.normalModuleFactory.tap(
                                                   ^

TypeError: Cannot read property 'tap' of undefined
    at NormalModuleReplacementPlugin.apply (/Users/thomas/Desktop/webpack-failure/NormalModuleReplacementPlugin.js:18:38)
    at plugins.forEach.plugin (/Users/thomas/Desktop/webpack-failure/node_modules/enhanced-resolve/lib/ResolverFactory.js:276:10)
    at Array.forEach (<anonymous>)
    at Object.exports.createResolver (/Users/thomas/Desktop/webpack-failure/node_modules/enhanced-resolve/lib/ResolverFactory.js:275:10)
    at ResolverFactory._create (/Users/thomas/Desktop/webpack-failure/node_modules/webpack/lib/ResolverFactory.js:60:28)
    at ResolverFactory.get (/Users/thomas/Desktop/webpack-failure/node_modules/webpack/lib/ResolverFactory.js:52:28)
    at NormalModuleFactory.getResolver (/Users/thomas/Desktop/webpack-failure/node_modules/webpack/lib/NormalModuleFactory.js:519:31)
    at /Users/thomas/Desktop/webpack-failure/node_modules/webpack/lib/NormalModuleFactory.js:165:32
    at /Users/thomas/Desktop/webpack-failure/node_modules/webpack/lib/NormalModuleFactory.js:129:4
    at hooks.beforeResolve.callAsync (/Users/thomas/Desktop/webpack-failure/node_modules/webpack/lib/NormalModuleFactory.js:396:5)
    at AsyncSeriesWaterfallHook.eval [as callAsync] (eval at create (/Users/thomas/Desktop/webpack-failure/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesWaterfallHook.lazyCompileHook (/Users/thomas/Desktop/webpack-failure/node_modules/tapable/lib/Hook.js:154:20)
    at NormalModuleFactory.create (/Users/thomas/Desktop/webpack-failure/node_modules/webpack/lib/NormalModuleFactory.js:377:28)
    at semaphore.acquire (/Users/thomas/Desktop/webpack-failure/node_modules/webpack/lib/Compilation.js:966:18)
    at Semaphore.acquire (/Users/thomas/Desktop/webpack-failure/node_modules/webpack/lib/util/Semaphore.js:29:4)
    at Compilation._addModuleChain (/Users/thomas/Desktop/webpack-failure/node_modules/webpack/lib/Compilation.js:965:18)
    at Compilation.addEntry (/Users/thomas/Desktop/webpack-failure/node_modules/webpack/lib/Compilation.js:1072:8)
    at compiler.hooks.make.tapAsync (/Users/thomas/Desktop/webpack-failure/node_modules/webpack/lib/SingleEntryPlugin.js:46:17)
    at AsyncParallelHook.eval [as callAsync] (eval at create (/Users/thomas/Desktop/webpack-failure/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:7:1)
    at AsyncParallelHook.lazyCompileHook (/Users/thomas/Desktop/webpack-failure/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.beforeCompile.callAsync.err (/Users/thomas/Desktop/webpack-failure/node_modules/webpack/lib/Compiler.js:541:20)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/thomas/Desktop/webpack-failure/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/thomas/Desktop/webpack-failure/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.compile (/Users/thomas/Desktop/webpack-failure/node_modules/webpack/lib/Compiler.js:534:28)
    at readRecords.err (/Users/thomas/Desktop/webpack-failure/node_modules/webpack/lib/Compiler.js:274:11)
    at Compiler.readRecords (/Users/thomas/Desktop/webpack-failure/node_modules/webpack/lib/Compiler.js:401:11)
    at hooks.run.callAsync.err (/Users/thomas/Desktop/webpack-failure/node_modules/webpack/lib/Compiler.js:271:10)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/thomas/Desktop/webpack-failure/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/thomas/Desktop/webpack-failure/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.beforeRun.callAsync.err (/Users/thomas/Desktop/webpack-failure/node_modules/webpack/lib/Compiler.js:268:19)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/thomas/Desktop/webpack-failure/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/thomas/Desktop/webpack-failure/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.run (/Users/thomas/Desktop/webpack-failure/node_modules/webpack/lib/Compiler.js:265:24)
    at processOptions (/Users/thomas/Desktop/webpack-failure/node_modules/webpack-cli/bin/cli.js:533:20)
    at yargs.parse (/Users/thomas/Desktop/webpack-failure/node_modules/webpack-cli/bin/cli.js:536:3)
    at Object.parse (/Users/thomas/Desktop/webpack-failure/node_modules/yargs/yargs.js:567:18)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

For a module to be resolved.

**Other relevant information:**
webpack version:  ^4.28.2
Node.js version: v11.3.0
Operating System:  osx
Additional tools:

I am able to recreate here https://github.com/reggi/webpack-failure

**Comment by sokra** [comment]
https://github.com/reggi/webpack-failure/blob/88a4549192952cf2599117962feab4db348403f1/webpack.config.js#L8-L15

Plugins for the compiler should be in `plugins` not in `resolve.plugins`.
