### ISSUE TITLE
Cannot find module '@webassemblyjs/wasm-opt'

### ISSUE THREAD

**Issue by Phoenix99srj** [webpack/webpack#8558]
# Bug report

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Other relevant information:**
webpack version:  
Node.js version: 
Operating System: 
Additional tools:

**Comment by Phoenix99srj** [comment]
Cannot find module '@webassemblyjs/wasm-opt'
Error: Cannot find module '@webassemblyjs/wasm-opt'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (E:\angular\ng6-proj\node_modules\@webassemblyjs\wasm-edit\lib\index.js:17:16)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
This is the whole issue

**Comment by xtuc** [comment]
This package is no longer used in Wepback, could you please update?

If you can't, are you using a npm cache or proxy?

**Comment by Phoenix99srj** [comment]
I tried to update it. But, again the same issue. 
Yes, I am using npm for that.

**Comment by Phoenix99srj** [comment]
i updated node, npm and angular-cli. 
Is there any way in which it can ignore that dependency?

**Comment by xtuc** [comment]
I mean do you have a proxy/cache configured in your .npmrc (likely in your $HOME).

**Comment by Phoenix99srj** [comment]
oh, no, I havn't used any.

**Comment by xtuc** [comment]
Could you try to remove `node_modules` and retry your setup?

Also, coud you please run `npm ls | grep webassemblyjs` to see what version it's using.

**Comment by Phoenix99srj** [comment]
node_modules deleted and reinstalled.
**npm ls | grep webassemblyjs**
npm ERR! missing: @webassemblyjs/wasm-opt@1.7.10, required by @webassemblyjs/wasm-edit@1.7.10
| | +-- @webassemblyjs/ast@1.7.10
| | | +-- @webassemblyjs/helper-module-context@1.7.10 deduped
| | | +-- @webassemblyjs/helper-wasm-bytecode@1.7.10
| | | `-- @webassemblyjs/wast-parser@1.7.10
| | |   +-- @webassemblyjs/ast@1.7.10 deduped
| | |   +-- @webassemblyjs/floating-point-hex-parser@1.7.10
| | |   +-- @webassemblyjs/helper-api-error@1.7.10 deduped
| | |   +-- @webassemblyjs/helper-code-frame@1.7.10
| | |   | `-- @webassemblyjs/wast-printer@1.7.10 deduped
| | |   +-- @webassemblyjs/helper-fsm@1.7.10
| | +-- @webassemblyjs/helper-module-context@1.7.10
| | +-- @webassemblyjs/wasm-edit@1.7.10
| | | +-- @webassemblyjs/ast@1.7.10 deduped
| | | +-- @webassemblyjs/helper-buffer@1.7.10
| | | +-- @webassemblyjs/helper-wasm-bytecode@1.7.10 deduped
| | | +-- @webassemblyjs/helper-wasm-section@1.7.10
| | | | +-- @webassemblyjs/ast@1.7.10 deduped
| | | | +-- @webassemblyjs/helper-buffer@1.7.10 deduped
| | | | +-- @webassemblyjs/helper-wasm-bytecode@1.7.10 deduped
| | | | `-- @webassemblyjs/wasm-gen@1.7.10 deduped
| | | +-- @webassemblyjs/wasm-gen@1.7.10
| | | | +-- @webassemblyjs/ast@1.7.10 deduped
| | | | +-- @webassemblyjs/helper-wasm-bytecode@1.7.10 deduped
| | | | +-- @webassemblyjs/ieee754@1.7.10 deduped
| | | | +-- @webassemblyjs/leb128@1.7.10 deduped
| | | | `-- @webassemblyjs/utf8@1.7.10 deduped
| | | +-- UNMET DEPENDENCY @webassemblyjs/wasm-opt@1.7.10
| | | +-- @webassemblyjs/wasm-parser@1.7.10 deduped
| | | `-- @webassemblyjs/wast-printer@1.7.10
| | |   +-- @webassemblyjs/ast@1.7.10 deduped
| | |   +-- @webassemblyjs/wast-parser@1.7.10 deduped
| | +-- @webassemblyjs/wasm-parser@1.7.10
| | | +-- @webassemblyjs/ast@1.7.10 deduped
| | | +-- @webassemblyjs/helper-api-error@1.7.10
| | | +-- @webassemblyjs/helper-wasm-bytecode@1.7.10 deduped
| | | +-- @webassemblyjs/ieee754@1.7.10
| | | +-- @webassemblyjs/leb128@1.7.10
| | | `-- @webassemblyjs/utf8@1.7.10npm ERR! missing: safe-buffer@5.1.1, required by readable-stream@2.3.6

npm ERR! missing: safe-buffer@5.1.1, required by string_decoder@1.1.1
npm ERR! missing: strip-ansi@3.0.1, required by gauge@2.7.4
npm ERR! missing: strip-ansi@3.0.1, required by string-width@1.0.2
npm ERR! missing: ansi-regex@2.1.1, required by strip-ansi@3.0.1
npm ERR! missing: wrappy@1.0.2, required by inflight@1.0.6
npm ERR! missing: wrappy@1.0.2, required by once@1.4.0
npm ERR! missing: safe-buffer@5.1.1, required by tar@4.4.1
npm ERR! missing: yallist@3.0.2, required by tar@4.4.1
npm ERR! missing: safe-buffer@5.1.1, required by minipass@2.2.4
npm ERR! missing: yallist@3.0.2, required by minipass@2.2.4

**Comment by evilebottnawi** [comment]
@Phoenix99srj clean cache `npm cache clean -f`

**Comment by Phoenix99srj** [comment]
Yes, its done. 
Thanks xtuc & evilebottnawi.
