### ISSUE TITLE
availableModules is not iterable at RemoveParentModulesPlugin

### ISSUE THREAD

**Issue by Elminday** [webpack/webpack#8567]
# Bug report

**What is the current behavior?**

I launch command:
`cross-env NODE_ENV=development webpack ./run/start.web.js`

Webpack build is succesful, but when launching my source I get error:

```
node_modules/webpack/lib/optimize/RemoveParentModulesPlugin.js:101
						for (const m of availableModules) {
						                ^

TypeError: availableModules is not iterable
    at handler (/home/minnak/Darbas/market/app/myccio/node_modules/webpack/lib/optimize/RemoveParentModulesPlugin.js:101:23)
    at SyncBailHook.eval [as call] (eval at create (/home/minnak/Darbas/market/app/myccio/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:13:16)
    at SyncBailHook.lazyCompileHook (/home/minnak/Darbas/market/app/myccio/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.seal (/home/minnak/Darbas/market/app/myccio/node_modules/webpack/lib/Compilation.js:1234:35)
    at hooks.make.callAsync.err (/home/minnak/Darbas/market/app/myccio/node_modules/webpack/lib/Compiler.js:546:17)
    at _err0 (eval at create (/home/minnak/Darbas/market/app/myccio/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:11:1)
    at _addModuleChain (/home/minnak/Darbas/market/app/myccio/node_modules/webpack/lib/Compilation.js:1093:12)
    at processModuleDependencies.err (/home/minnak/Darbas/market/app/myccio/node_modules/webpack/lib/Compilation.js:1005:9)
    at process._tickCallback (internal/process/next_tick.js:176:11)
yarn
```

**What is the expected behavior?**

Successful client launch.

**Configs:**

```
const load = () => ({
  target: 'async-node',
  node: { __filename: true, __dirname: true },
  plugins: [
    new webpack.ProvidePlugin({ Promise: 'bluebird' }),
    new webpack.DefinePlugin({
      'global.CONFIG': JSON.stringify(CONFIG_EXPOSED),
      'global.TYPE': JSON.stringify('SERVER'),
      'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV),
    }),
    new webpack.LoaderOptionsPlugin({
      minimize: true,
      debug: false,
      options: { postcss: postcss(webpack) },
    }),
  ],
});
```

```
export function loader() {
  return {
    jsx: {
      use: {
        query: {
          cacheDirectory: true,
          presets: [
            [
              'env',
              {
                modules: false,
                targets: {
                  node: '10.13.0',
                  chrome: '49',
                  edge: '14',
                  firefox: '52',
                  safari: '10',
                  ie: '11',
                },
                exclude: [
                  'transform-async-to-generator',
                  'transform-regenerator',
                  'transform-es2015-typeof-symbol',
                ],
              },
            ],
            'react',
          ],
          plugins: [
            'system-import-transformer',
            'transform-decorators-legacy',
            'transform-runtime',
            'transform-class-properties',
            'babel-root-import',
          ],
        },
      },
    },
    cssModules: { use: ['css-loader'] },
    cssGlobal: { use: ['css-loader', 'postcss-loader'] },
  };
}

export function config(entry) {
  return {
    devtool: 'module-eval-source-map',
    mode: 'development',
    entry: [
      'babel-polyfill',
      'isomorphic-fetch',
      'whatwg-fetch',
      path.join(Dir.run, entry.toLowerCase()),
    ],
    output: {
      path: Dir.nodeBuild,
      filename: [entry, 'dev', 'bundle', 'js'].join('.'),
      chunkFilename: '[id].[hash:5]-[chunkhash:7].js',
      devtoolModuleFilenameTemplate: '[absolute-resource-path]',
      libraryTarget: 'commonjs2',
    },
    externals: [nodeExternalModules()],
    plugins: [
      new MiniCssExtractPlugin({
        filename: '[name].css',
        chunkFilename: '[id].css',
      }),
      new StartServerPlugin(),
      new HotModuleReplacementPlugin(),
      new NamedModulesPlugin(),
      new NoEmitOnErrorsPlugin(),
    ],
  };
}
```

webpack version:  4.28.2
Node.js version: 9.11.2
Operating System: Ubuntu

**Comment by sokra** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by Elminday** [comment]
Found that this issue is related to a different library import.

**Comment by BenEast** [comment]
> Found that this issue is related to a different library import.

I'm running into a very similar issue with my build. I know it's been a while, but do you remember how you identified the root cause for this one?
