### ISSUE TITLE
DefinePlugin throws "unexpected token" on special characters

### ISSUE THREAD

**Issue by worc** [webpack/webpack#8641]
using webpack ^4.12.0 i've run into a bug with `DefinePlugin` creating *unexpected token* errors. in my webpack config i am injecting global values like this:

```
new webpack.DefinePlugin({
  API_ENDPOINT: 'https://api.test.company.io',
}),
```

but when running a webpack build i get this error (everything still transpiles, but if i do a find-all in the generated code the value of the global was never injected):

```
{ SyntaxError: Unexpected token (1:6)
at Parser.pp$4.raise (/<node_modules>/acorn/dist/acorn.js:2757:13)
at Parser.pp.unexpected (/<node_modules>/acorn/dist/acorn.js:647:8)
at Parser.pp.expect (/<node_modules>/acorn/dist/acorn.js:641:26)
at Parser.pp$3.parseParenAndDistinguishExpression (/<node_modules>/acorn/dist/acorn.js:2228:38)
at Parser.pp$3.parseExprAtom (/<node_modules>/acorn/dist/acorn.js:2163:41)
at Parser.parseExprAtom (/<node_modules>/acorn-dynamic-import/lib/inject.js:60:31)
at Parser.pp$3.parseExprSubscripts (/<node_modules>/acorn/dist/acorn.js:2047:19)
at Parser.pp$3.parseMaybeUnary (/<node_modules>/acorn/dist/acorn.js:2024:17)
at Parser.pp$3.parseExprOps (/<node_modules>/acorn/dist/acorn.js:1966:19)
at Parser.pp$3.parseMaybeConditional (/<node_modules>/acorn/dist/acorn.js:1949:19)
at Parser.pp$3.parseMaybeAssign (/<node_modules>/acorn/dist/acorn.js:1925:19)
at Parser.pp$3.parseExpression (/<node_modules>/acorn/dist/acorn.js:1896:19)
at Parser.pp$1.parseStatement (/<node_modules>/acorn/dist/acorn.js:815:45)
at Parser.parseStatement (/<node_modules>/acorn-dynamic-import/lib/inject.js:47:31)
at Parser.pp$1.parseTopLevel (/<node_modules>/acorn/dist/acorn.js:706:23)
at Parser.parse (/<node_modules>/acorn/dist/acorn.js:551:15)
at Object.parse (/<node_modules>/acorn/dist/acorn.js:5288:37)
at Function.parse (/<node_modules>/webpack/lib/Parser.js:2229:16)
at Parser.evaluate (/<node_modules>/webpack/lib/Parser.js:2132:22)
at parser.hooks.evaluateIdentifier.for.tap.expr (/<node_modules>/webpack/lib/DefinePlugin.js:180:29)
...
```

the stack trace keeps going, but that last line was what finally unlocked this issue for me and led me to [this thread on visionmedia's debug repo](https://github.com/visionmedia/debug/issues/301). where the suggested solution to wrap values in JSON.stringify actually fixed my issue.

so, my next guess was that special characters were killing the DefinePlugin constructor. i tried running builds without special characters in the DefinePlugin constructor, and then slowly reintroduced characters into its diet until it died:

```
// works with no special characters
new webpack.DefinePlugin({
  API_ENDPOINT: 'httpsapitestcompanyio',
}),

// works when introducing the period character
new webpack.DefinePlugin({
    API_ENDPOINT: 'httpsapi.test.company.io',
}),

// dies when introducing colon
new webpack.DefinePlugin({
    API_ENDPOINT: 'https:api.test.company.io',
}),

// works when introducing one slash
new webpack.DefinePlugin({
    API_ENDPOINT: 'https/api.test.company.io',
}),

// dies when introducing two slashes
new webpack.DefinePlugin({
    API_ENDPOINT: 'https//api.test.company.io',
}),

// dies with both colon and slashes
new webpack.DefinePlugin({
    API_ENDPOINT: 'https://api.test.company.io',
}),
```

wrapping the URL container special characters in a JSON.stringify call is a valid workaround for the bug:

```
new webpack.DefinePlugin({
    API_ENDPOINT: JSON.stringify('https://api.test.company.io'),
}),
```

the other (maddening, table-flip inducing, completely nonsensical) workaround is to lowercase the name of the global var:

```
new webpack.DefinePlugin({
  api_endpoint: 'https://api.test.company.io'), // this works...
}),
```

🤷‍♂️

**Comment by sokra** [comment]
``` js
new webpack.DefinePlugin({
  API_ENDPOINT: JSON.stringify('https://api.test.company.io'),
}),
```

**Comment by evilebottnawi** [comment]
Answer https://github.com/webpack/webpack/issues/8641#issuecomment-455098071 also please use issue template in future

**Comment by worc** [comment]
@evilebottnawi that's not an answer, that's a workaround.

**Comment by evilebottnawi** [comment]
@worc please format your issue as template and ping me, when we reopen

**Comment by Enteleform** [comment]
@sokra @evilebottnawi 

I'm having this same issue, although my usage scenario is different.

&nbsp;  
[**define-plugin/#usage**](https://webpack.js.org/plugins/define-plugin/#usage) states:
> If the value is a string it will be used as a code fragment.

&nbsp;
I'm using the `code fragment` functionality to execute code for development purposes, rather than to render a static value.

For example, the following configuration
```
new Webpack.DefinePlugin({
  foo: ";(()=>{console.log('@ injected.foo')})",
})
```
allows me to execute the defined code snippet with `foo()` in my source code.

&nbsp;  
I've found that `webpack-dev-server`'s execution is entirely functional and the exemplified usage of `DefinePlugin` is successful for my intended purposes. However, I am getting a stack trace in the console:

```
SyntaxError: Unexpected token (2:2)
  at Parser.pp$4.raise                              (./node_modules/acorn/src/location.js:15:13)
  at Parser.pp.unexpected                           (./node_modules/acorn/src/parseutil.js:110:8)
  at Parser.pp$3.parseExprAtom                      (./node_modules/acorn/src/expression.js:463:10)
  at Parser.pp$3.parseExprSubscripts                (./node_modules/acorn/src/expression.js:266:19)       
  at Parser.pp$3.parseMaybeUnary                    (./node_modules/acorn/src/expression.js:243:17)
  at Parser.pp$3.parseExprOps                       (./node_modules/acorn/src/expression.js:178:19)
  at Parser.pp$3.parseMaybeConditional              (./node_modules/acorn/src/expression.js:161:19)     
  at Parser.pp$3.parseMaybeAssign                   (./node_modules/acorn/src/expression.js:129:19)
  at Parser.pp$3.parseParenAndDistinguishExpression (./node_modules/acorn/src/expression.js:559:28)
  at Parser.pp$3.parseExprAtom                      (./node_modules/acorn/src/expression.js:423:41) {
    pos:      4,
    loc:      Position { line: 2, column: 2 },
    raisedAt: 5
  }
```

&nbsp;  
Is there anything I can do to avoid that error? I think it would be helpful to have an option for `DefinePlugin` like `allowSpecialCharacters` or `disableParsing` to allow this type of usage without causing errors.

Also; I wouldn't mind opening a new issue using the issue template (*or posting it here*), if it would help to move the issue towards resolution.

**Comment by evilebottnawi** [comment]
You should not use DefinePlugin for injecting code

**Comment by Ratstail91** [comment]
For those who don't know, DefinePlugin can't handle empty strings either...

**Comment by scarletsky** [comment]
> You should not use DefinePlugin for injecting code

If we should not use `DefinePlugin`, what should we use ?

**Comment by janzenz** [comment]
@Ratstail91 that's correct I just found out about it now and was pulling my hair off for the past 24 hours.
