### ISSUE TITLE
additional chunk assets processing HtmlWebpackPlugin

### ISSUE THREAD

**Issue by marco-carvalho** [webpack/webpack#8657]
# Bug report

**What is the current behavior?**
```
ℹ ｢webpack｣: webpack 5.0.0-alpha.8
 90% additional chunk assets processing HtmlWebpackPlugin✖ ｢webpack｣: Uncaught exception: TypeError: Cannot read property 'add' of undefined
✖ ｢webpack｣: TypeError: Cannot read property 'add' of undefined
```

**If the current behavior is a bug, please provide the steps to reproduce.**
```
git clone https://github.com/marco-carvalho/csg
npm i
npm run build
```

**What is the expected behavior?**
The output build would be generated, and therefore I would put it in some static hosting provider.

**Other relevant information:**
webpack version:  5.0.0-alpha.8
Node.js version: 11.7.0
Operating System: Ubuntu
Additional tools: VSCode

**Comment by sokra** [comment]
Stack Trace?

**Comment by marco-carvalho** [comment]
```
travis_fold:start:worker_info
[0K[33;1mWorker information[0m
hostname: 175af498-4bad-4cde-a34f-f596a6368d77@1.production-2-worker-org-gce-1cx2
version: v6.2.0 https://github.com/travis-ci/worker/tree/5e5476e01646095f48eec13196fdb3faf8f5cbf7
instance: travis-job-29d914e6-62e2-4be8-96a2-e10eb0037b6b travis-ci-garnet-trusty-1512502259-986baf0 (via amqp)
startup: 6.471986469s
travis_fold:end:worker_info
[0Ktravis_fold:start:system_info
[0K[33;1mBuild system information[0m
Build language: node_js
Build group: stable
Build dist: trusty
Build id: 491286758
Job id: 491286759
Runtime kernel version: 4.4.0-101-generic
travis-build version: 7675838a8
[34m[1mBuild image provisioning date and time[0m
Tue Dec  5 19:58:13 UTC 2017
[34m[1mOperating System Details[0m
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty
[34m[1mCookbooks Version[0m
7c2c6a6 https://github.com/travis-ci/travis-cookbooks/tree/7c2c6a6
[34m[1mgit version[0m
git version 2.15.1
[34m[1mbash version[0m
GNU bash, version 4.3.11(1)-release (x86_64-pc-linux-gnu)
[34m[1mgcc version[0m
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[34m[1mdocker version[0m
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:38 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:41:20 2017
 OS/Arch:      linux/amd64
 Experimental: false
[34m[1mclang version[0m
clang version 5.0.0 (tags/RELEASE_500/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/clang-5.0.0/bin
[34m[1mjq version[0m
jq-1.5
[34m[1mbats version[0m
Bats 0.4.0
[34m[1mshellcheck version[0m
0.4.6
[34m[1mshfmt version[0m
v2.0.0
[34m[1mccache version[0m
ccache version 3.1.9

Copyright (C) 2002-2007 Andrew Tridgell
Copyright (C) 2009-2011 Joel Rosdahl

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation; either version 3 of the License, or (at your option) any later
version.
[34m[1mcmake version[0m
cmake version 3.9.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).
[34m[1mheroku version[0m
heroku-cli/6.14.39-addc925 (linux-x64) node-v9.2.0
[34m[1mimagemagick version[0m
Version: ImageMagick 6.7.7-10 2017-07-31 Q16 http://www.imagemagick.org
[34m[1mmd5deep version[0m
4.2
[34m[1mmercurial version[0m
Mercurial Distributed SCM (version 4.2.2)
(see https://mercurial-scm.org for more information)

Copyright (C) 2005-2017 Matt Mackall and others
This is free software; see the source for copying conditions. There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
[34m[1mmysql version[0m
mysql  Ver 14.14 Distrib 5.6.33, for debian-linux-gnu (x86_64) using  EditLine wrapper
[34m[1mopenssl version[0m
OpenSSL 1.0.1f 6 Jan 2014
[34m[1mpacker version[0m
Packer v1.0.2

Your version of Packer is out of date! The latest version
is 1.1.2. You can update by downloading from www.packer.io
[34m[1mpostgresql client version[0m
psql (PostgreSQL) 9.6.6
[34m[1mragel version[0m
Ragel State Machine Compiler version 6.8 Feb 2013
Copyright (c) 2001-2009 by Adrian Thurston
[34m[1msubversion version[0m
svn, version 1.8.8 (r1568071)
   compiled Aug 10 2017, 17:20:39 on x86_64-pc-linux-gnu

Copyright (C) 2013 The Apache Software Foundation.
This software consists of contributions made by many people;
see the NOTICE file for more information.
Subversion is open source software, see http://subversion.apache.org/

The following repository access (RA) modules are available:

* ra_svn : Module for accessing a repository using the svn network protocol.
  - with Cyrus SASL authentication
  - handles 'svn' scheme
* ra_local : Module for accessing a repository on local disk.
  - handles 'file' scheme
* ra_serf : Module for accessing a repository via WebDAV protocol using serf.
  - using serf 1.3.3
  - handles 'http' scheme
  - handles 'https' scheme

[34m[1msudo version[0m
Sudo version 1.8.9p5
Configure options: --prefix=/usr -v --with-all-insults --with-pam --with-fqdn --with-logging=syslog --with-logfac=authpriv --with-env-editor --with-editor=/usr/bin/editor --with-timeout=15 --with-password-timeout=0 --with-passprompt=[sudo] password for %p:  --without-lecture --with-tty-tickets --disable-root-mailer --enable-admin-flag --with-sendmail=/usr/sbin/sendmail --with-timedir=/var/lib/sudo --mandir=/usr/share/man --libexecdir=/usr/lib/sudo --with-sssd --with-sssd-lib=/usr/lib/x86_64-linux-gnu --with-selinux
Sudoers policy plugin version 1.8.9p5
Sudoers file grammar version 43

Sudoers path: /etc/sudoers
Authentication methods: 'pam'
Syslog facility if syslog is being used for logging: authpriv
Syslog priority to use when user authenticates successfully: notice
Syslog priority to use when user authenticates unsuccessfully: alert
Send mail if the user is not in sudoers
Use a separate timestamp for each user/tty combo
Lecture user the first time they run sudo
Root may run sudo
Allow some information gathering to give useful error messages
Require fully-qualified hostnames in the sudoers file
Visudo will honor the EDITOR environment variable
Set the LOGNAME and USER environment variables
Length at which to wrap log file lines (0 for no wrap): 80
Authentication timestamp timeout: 15.0 minutes
Password prompt timeout: 0.0 minutes
Number of tries to enter a password: 3
Umask to use or 0777 to use user's: 022
Path to mail program: /usr/sbin/sendmail
Flags for mail program: -t
Address to send mail to: root
Subject line for mail messages: *** SECURITY information for %h ***
Incorrect password message: Sorry, try again.
Path to authentication timestamp dir: /var/lib/sudo
Default password prompt: [sudo] password for %p: 
Default user to run commands as: root
Value to override user's $PATH with: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
Path to the editor for use by visudo: /usr/bin/editor
When to require a password for 'list' pseudocommand: any
When to require a password for 'verify' pseudocommand: all
File descriptors >= 3 will be closed before executing a command
Environment variables to check for sanity:
	TZ
	TERM
	LINGUAS
	LC_*
	LANGUAGE
	LANG
	COLORTERM
Environment variables to remove:
	RUBYOPT
	RUBYLIB
	PYTHONUSERBASE
	PYTHONINSPECT
	PYTHONPATH
	PYTHONHOME
	TMPPREFIX
	ZDOTDIR
	READNULLCMD
	NULLCMD
	FPATH
	PERL5DB
	PERL5OPT
	PERL5LIB
	PERLLIB
	PERLIO_DEBUG 
	JAVA_TOOL_OPTIONS
	SHELLOPTS
	GLOBIGNORE
	PS4
	BASH_ENV
	ENV
	TERMCAP
	TERMPATH
	TERMINFO_DIRS
	TERMINFO
	_RLD*
	LD_*
	PATH_LOCALE
	NLSPATH
	HOSTALIASES
	RES_OPTIONS
	LOCALDOMAIN
	CDPATH
	IFS
Environment variables to preserve:
	JAVA_HOME
	TRAVIS
	CI
	DEBIAN_FRONTEND
	XAUTHORIZATION
	XAUTHORITY
	PS2
	PS1
	PATH
	LS_COLORS
	KRB5CCNAME
	HOSTNAME
	HOME
	DISPLAY
	COLORS
Locale to use while parsing sudoers: C
Directory in which to store input/output logs: /var/log/sudo-io
File in which to store the input/output log: %{seq}
Add an entry to the utmp/utmpx file when allocating a pty
PAM service name to use
PAM service name to use for login shells
Create a new PAM session for the command to run in
Maximum I/O log sequence number: 0

Local IP address and netmask pairs:
	10.240.0.28/255.255.255.255
	172.17.0.1/255.255.0.0

Sudoers I/O plugin version 1.8.9p5
[34m[1mgzip version[0m
gzip 1.6
Copyright (C) 2007, 2010, 2011 Free Software Foundation, Inc.
Copyright (C) 1993 Jean-loup Gailly.
This is free software.  You may redistribute copies of it under the terms of
the GNU General Public License <http://www.gnu.org/licenses/gpl.html>.
There is NO WARRANTY, to the extent permitted by law.

Written by Jean-loup Gailly.
[34m[1mzip version[0m
Copyright (c) 1990-2008 Info-ZIP - Type 'zip "-L"' for software license.
This is Zip 3.0 (July 5th 2008), by Info-ZIP.
Currently maintained by E. Gordon.  Please send bug reports to
the authors using the web page at www.info-zip.org; see README for details.

Latest sources and executables are at ftp://ftp.info-zip.org/pub/infozip,
as of above date; see http://www.info-zip.org/ for other sites.

Compiled with gcc 4.8.2 for Unix (Linux ELF) on Oct 21 2013.

Zip special compilation options:
	USE_EF_UT_TIME       (store Universal Time)
	BZIP2_SUPPORT        (bzip2 library version 1.0.6, 6-Sept-2010)
	    bzip2 code and library copyright (c) Julian R Seward
	    (See the bzip2 license for terms of use)
	SYMLINK_SUPPORT      (symbolic links supported)
	LARGE_FILE_SUPPORT   (can read and write large files on file system)
	ZIP64_SUPPORT        (use Zip64 to store large files in archives)
	UNICODE_SUPPORT      (store and read UTF-8 Unicode paths)
	STORE_UNIX_UIDs_GIDs (store UID/GID sizes/values using new extra field)
	UIDGID_NOT_16BIT     (old Unix 16-bit UID/GID extra field not used)
	[encryption, version 2.91 of 05 Jan 2007] (modified for Zip 3)

Encryption notice:
	The encryption code of this program is not copyrighted and is
	put in the public domain.  It was originally written in Europe
	and, to the best of our knowledge, can be freely distributed
	in both source and object forms from any country, including
	the USA under License Exception TSU of the U.S. Export
	Administration Regulations (section 740.13(e)) of 6 June 2002.

Zip environment options:
             ZIP:  [none]
          ZIPOPT:  [none]
[34m[1mvim version[0m
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 24 2016 16:43:18)
Included patches: 1-52
Extra patches: 8.0.0056
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by buildd@
Huge version without GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +syntax
+arabic          +file_in_path    +mouse_sgr       +tag_binary
+autocmd         +find_in_path    -mouse_sysmouse  +tag_old_static
-balloon_eval    +float           +mouse_urxvt     -tag_any_white
-browse          +folding         +mouse_xterm     -tcl
++builtin_terms  -footer          +multi_byte      +terminfo
+byte_offset     +fork()          +multi_lang      +termresponse
+cindent         +gettext         -mzscheme        +textobjects
-clientserver    -hangul_input    +netbeans_intg   +title
-clipboard       +iconv           +path_extra      -toolbar
+cmdline_compl   +insert_expand   -perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    +keymap          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       +python          +viminfo
+cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con      -lua             +rightleft       +windows
+diff            +menu            -ruby            +writebackup
+digraphs        +mksession       +scrollbind      -X11
-dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     -xim
+emacs_tags      -mouseshape      -sniff           -xsmp
+eval            +mouse_dec       +startuptime     -xterm_clipboard
+ex_extra        +mouse_gpm       +statusline      -xterm_save
+extra_search    -mouse_jsbterm   -sun_workshop    -xpm
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H     -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1      
Linking: gcc   -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,--as-needed -o vim        -lm -ltinfo -lnsl  -lselinux  -lacl -lattr -lgpm -ldl    -L/usr/lib/python2.7/config-x86_64-linux-gnu -lpython2.7 -lpthread -ldl -lutil -lm -Xlinker -export-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions      
[34m[1miptables version[0m
iptables v1.4.21
[34m[1mcurl version[0m
curl 7.35.0 (x86_64-pc-linux-gnu) libcurl/7.35.0 OpenSSL/1.0.1f zlib/1.2.8 libidn/1.28 librtmp/2.3
[34m[1mwget version[0m
GNU Wget 1.15 built on linux-gnu.
[34m[1mrsync version[0m
rsync  version 3.1.0  protocol version 31
[34m[1mgimme version[0m
v1.2.0
[34m[1mnvm version[0m
0.33.6
[34m[1mperlbrew version[0m
/home/travis/perl5/perlbrew/bin/perlbrew  - App::perlbrew/0.80
[34m[1mphpenv version[0m
rbenv 1.1.1-25-g6aa70b6
[34m[1mrvm version[0m
rvm 1.29.3 (latest) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io]
[34m[1mdefault ruby version[0m
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
[34m[1mCouchDB version[0m
couchdb 1.6.1
[34m[1mElasticSearch version[0m
5.5.0
[34m[1mInstalled Firefox version[0m
firefox 56.0.2
[34m[1mMongoDB version[0m
MongoDB 3.4.10
[34m[1mPhantomJS version[0m
2.1.1
[34m[1mPre-installed PostgreSQL versions[0m
9.2.24
9.3.20
9.4.15
9.5.10
9.6.6
[34m[1mRabbitMQ Version[0m
3.6.14
[34m[1mRedis version[0m
redis-server 4.0.6
[34m[1mriak version[0m
2.2.3
[34m[1mPre-installed Go versions[0m
1.7.4
[34m[1mant version[0m
Apache Ant(TM) version 1.9.3 compiled on April 8 2014
[34m[1mmvn version[0m
Apache Maven 3.5.2 (138edd61fd100ec658bfa2d307c43b76940a5d7d; 2017-10-18T07:58:13Z)
Maven home: /usr/local/maven-3.5.2
Java version: 1.8.0_151, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-oracle/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.4.0-98-generic", arch: "amd64", family: "unix"
[34m[1mgradle version[0m

------------------------------------------------------------
Gradle 4.0.1
------------------------------------------------------------

Build time:   2017-07-07 14:02:41 UTC
Revision:     38e5dc0f772daecca1d2681885d3d85414eb6826

Groovy:       2.4.11
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_151 (Oracle Corporation 25.151-b12)
OS:           Linux 4.4.0-98-generic amd64

[34m[1mlein version[0m
Leiningen 2.8.1 on Java 1.8.0_151 Java HotSpot(TM) 64-Bit Server VM
[34m[1mPre-installed Node.js versions[0m
v4.8.6
v6.12.0
v6.12.1
v8.9
v8.9.1
[34m[1mphpenv versions[0m
  system
  5.6
* 5.6.32 (set by /home/travis/.phpenv/version)
  7.0
  7.0.25
  7.1
  7.1.11
  hhvm
  hhvm-stable
[34m[1mcomposer --version[0m
Composer version 1.5.2 2017-09-11 16:59:25
[34m[1mPre-installed Ruby versions[0m
ruby-2.2.7
ruby-2.3.4
ruby-2.4.1
travis_fold:end:system_info
[0K

travis_fold:start:git.checkout
[0Ktravis_time:start:09690375
[0K$ git clone --depth=50 --branch=master https://github.com/marco-carvalho/csg.git marco-carvalho/csg
Cloning into 'marco-carvalho/csg'...
travis_time:end:09690375:start=1549816826107731448,finish=1549816826804140732,duration=696409284
[0K$ cd marco-carvalho/csg
$ git checkout -qf 46de6902a1a36132d160842f590182d4dead8611
travis_fold:end:git.checkout
[0K

[33;1mSetting environment variables from repository settings[0m
$ export GITHUB_API_KEY=[secure]

travis_fold:start:nvm.install
[0Ktravis_time:start:0a699557
[0K$ nvm install node
Downloading and installing node v11.9.0...
Downloading https://nodejs.org/dist/v11.9.0/node-v11.9.0-linux-x64.tar.xz...
Computing checksum with sha256sum
Checksums matched!
Now using node v11.9.0 (npm v6.5.0)
travis_time:end:0a699557:start=1549816827651345561,finish=1549816831338735387,duration=3687389826
[0Ktravis_fold:end:nvm.install
[0K
travis_fold:start:cache.1
[0KSetting up build cache
$ export CASHER_DIR=${TRAVIS_HOME}/.casher
travis_time:start:0a9a9c12
[0K$ Installing caching utilities
travis_time:end:0a9a9c12:start=1549816836025758556,finish=1549816836180509522,duration=154750966
[0Ktravis_time:start:1012163c
[0Ktravis_time:end:1012163c:start=1549816836186282692,finish=1549816836189488154,duration=3205462
[0Ktravis_time:start:04211644
[0K[32;1mattempting to download cache archive[0m
[32;1mfetching master/cache-linux-trusty-e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855--node-node.tgz[0m
[32;1mfound cache[0m
travis_time:end:04211644:start=1549816836193490208,finish=1549816837642618006,duration=1449127798
[0Ktravis_time:start:113b0eea
[0Ktravis_time:end:113b0eea:start=1549816837647138906,finish=1549816837650221109,duration=3082203
[0Ktravis_time:start:0609d818
[0K[32;1madding /home/travis/build/marco-carvalho/csg/node_modules to cache[0m
[32;1mcreating directory /home/travis/build/marco-carvalho/csg/node_modules[0m
travis_time:end:0609d818:start=1549816837654580868,finish=1549816841704938956,duration=4050358088
[0Ktravis_fold:end:cache.1
[0K
$ node --version
v11.9.0
$ npm --version
6.5.0
$ nvm --version
0.34.0

travis_fold:start:install.npm
[0Ktravis_time:start:086d5400
[0K$ npm ci 
npm WARN prepare removing existing node_modules/ before installation

> fsevents@1.2.7 install /home/travis/build/marco-carvalho/csg/node_modules/fsevents
> node install

added 922 packages in 11.421s
travis_time:end:086d5400:start=1549816842095564039,finish=1549816853885601098,duration=11790037059
[0Ktravis_fold:end:install.npm
[0K
travis_time:start:11bbc540
[0K$ npm run build

> csg@1.0.0 build /home/travis/build/marco-carvalho/csg
> webpack --mode production



â„¹ ï½¢webpackï½£: webpack 5.0.0-alpha.10
  0% compiling 10% building 0/1 entries 0/0 modules 0 active 10% building 0/1 entries 0/1 modules 0 active 10% building 0/1 entries 0/1 modules 1 active .../travis/build/marco-carvalho/csg/app.js                                            10% building 0/1 entries 1/1 modules 0 active 10% building 0/1 entries 1/2 modules 0 active 10% building 0/1 entries 1/2 modules 1 active ...ld/marco-carvalho/csg/src/examples/2.js                                            10% building 0/1 entries 2/2 modules 0 active 10% building 0/1 entries 2/3 modules 0 active 10% building 0/1 entries 2/3 modules 1 active ...ode_modules/three/build/three.module.js 10% building 0/1 entries 2/4 modules 1 active ...ode_modules/three/build/three.module.js 10% building 0/1 entries 2/4 modules 2 active ...uild/marco-carvalho/csg/src/threeCSG.js 10% building 0/1 entries 3/4 modules 1 active ...ode_modules/three/build/three.module.js 10% building 0/1 entries 3/5 modules 1 active ...ode_modules/three/build/three.module.js 10% building 0/1 entries 3/5 modules 2 active ...ild/marco-carvalho/csg/src/vertexCSG.js 10% building 0/1 entries 3/6 modules 2 active ...ild/marco-carvalho/csg/src/vertexCSG.js 10% building 0/1 entries 3/6 modules 3 active ...ld/marco-carvalho/csg/src/polygonCSG.js 10% building 0/1 entries 3/7 modules 3 active ...ld/marco-carvalho/csg/src/polygonCSG.js 10% building 0/1 entries 3/7 modules 4 active ...build/marco-carvalho/csg/src/nodeCSG.js 10% building 0/1 entries 4/7 modules 3 active ...build/marco-carvalho/csg/src/nodeCSG.js 10% building 0/1 entries 5/7 modules 2 active ...build/marco-carvalho/csg/src/nodeCSG.js 10% building 0/1 entries 6/7 modules 1 active ...ode_modules/three/build/three.module.js                                            10% building 0/1 entries 7/7 modules 0 active 70% building 1/1 entries 7/7 modules 0 active                       70% finish module graph 70% finish module graph FlagDependencyExportsPlugin   70% finish module graph WasmFinalizeExportsPlugin                                       70% sealing 70% sealing WarnCaseSensitiveModulesPlugin              72% dependencies optimization 72% dependencies optimization SideEffectsFlagPlugin 72% dependencies optimization FlagDependencyUsagePlugin                     72% after dependencies optimization                     71% chunk graph 71% after chunk graph 71% after chunk graph WebAssemblyModulesPlugin                                 73% optimizing 74% module optimization 74% after module optimization        75% chunk optimization 75% chunk optimization EnsureChunkConditionsPlugin   75% chunk optimization RemoveParentModulesPlugin   75% chunk optimization RemoveEmptyChunksPlugin 75% chunk optimization MergeDuplicateChunksPlugin          75% chunk optimization SplitChunksPlugin 75% chunk optimization RemoveEmptyChunksPlugin                   75% after chunk optimization 76% module and chunk tree optimization 76% after module and chunk tree optimization               77% chunk modules optimization 77% chunk modules optimization ModuleConcatenationPlugin                     78% after chunk modules optimization                  78% module reviving 78% module reviving RecordIdsPlugin               79% before module ids        79% module ids 79% module ids DeterministicModuleIdsPlugin                  80% module id optimization 81% module id optimization         81% chunk reviving 81% chunk reviving RecordIdsPlugin               82% before chunk ids        82% chunk ids 82% chunk ids DeterministicChunkIdsPlugin                 83% chunk id optimization 83% chunk id optimization FlagIncludedChunksPlugin                    83% after chunk id optimization              84% record modules 84% record modules RecordIdsPlugin                  85% record chunks 85% record chunks RecordIdsPlugin                85% module hashing 86% runtime requirements              86% hashing 87% content hashing 87% content hashing JavascriptModulesPlugin                         87% content hashing 87% content hashing JavascriptModulesPlugin                           88% after hashing   88% record hash 89% module assets processing  89% chunk assets processing 90% additional chunk assets processing 90% additional chunk assets processing HtmlWebpackPluginâœ– ï½¢webpackï½£: Uncaught exception: TypeError: Cannot read property 'add' of undefined
âœ– ï½¢webpackï½£: TypeError: Cannot read property 'add' of undefined
    at childCompilerDependencies.forEach.fileDependency (/home/travis/build/marco-carvalho/csg/node_modules/html-webpack-plugin/index.js:142:47)
    at Array.forEach (<anonymous>)
    at compilation.hooks.additionalChunkAssets.tap (/home/travis/build/marco-carvalho/csg/node_modules/html-webpack-plugin/index.js:141:35)
    at SyncHook.eval [as call] (eval at create (/home/travis/build/marco-carvalho/csg/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:12:1)
    at SyncHook.lazyCompileHook (/home/travis/build/marco-carvalho/csg/node_modules/tapable/lib/Hook.js:154:20)
    at cont (/home/travis/build/marco-carvalho/csg/node_modules/webpack/lib/Compilation.js:1316:38)
    at createChunkAssets.err (/home/travis/build/marco-carvalho/csg/node_modules/webpack/lib/Compilation.js:1352:6)
    at /home/travis/build/marco-carvalho/csg/node_modules/neo-async/async.js:2825:7
    at done (/home/travis/build/marco-carvalho/csg/node_modules/neo-async/async.js:2861:11)
    at /home/travis/build/marco-carvalho/csg/node_modules/neo-async/async.js:2813:7
    at process.nextTick (/home/travis/build/marco-carvalho/csg/node_modules/webpack/lib/Compilation.js:2396:52)
    at processTicksAndRejections (internal/process/next_tick.js:74:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! csg@1.0.0 build: `webpack --mode production`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the csg@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2019-02-10T16_40_58_064Z-debug.log
travis_time:end:11bbc540:start=1549816853891125791,finish=1549816858090687631,duration=4199561840
[0K[31;1mThe command "npm run build" exited with 1.[0m

travis_fold:start:cache.2
[0Kstore build cache
travis_time:start:02f18ab9
[0Ktravis_time:end:02f18ab9:start=1549816858096241803,finish=1549816858100423467,duration=4181664
[0Ktravis_time:start:17985c53
[0K[32;1mchange detected (content changed, file is created, or file is deleted):
/home/travis/build/marco-carvalho/csg/node_modules/acorn-dynamic-import/CHANGELOG.md
/home/travis/build/marco-carvalho/csg/node_modules/acorn-dynamic-import/lib/index.js
/home/travis/build/marco-carvalho/csg/node_modules/acorn-dynamic-import/lib/walk.js
/home/travis/build/marco-carvalho/csg/node_modules/acorn-dynamic-import/LICENSE
/home/travis/build/marco-carvalho/csg/node_modules/acorn-dynamic-import/package.json
/home/travis/build/marco-carvalho/csg/node_modules/acorn-dynamic-import/README.md
/home/travis/build/marco-carvalho/csg/node_modules/acorn-dynamic-import/src/index.js
/home/travis/build/marco-carvalho/csg/node_modules/acorn-dynamic-import/src/walk.js
/home/travis/build/marco-carvalho/csg/node_modules/duplexify/package.json
/home/travis/build/marco-carvalho/csg/node_modules/duplexify/.travis.yml
/home/travis/build/marco-carvalho/csg/node_modules/flush-write-stream/package.json
/home/travis/build/marco-carvalho/csg/node_modules/flush-write-stream/.travis.yml
/home/travis/build/
[0m
[32;1m...
[0m
[32;1mchanges detected, packing new archive[0m
[32;1muploading master/cache-linux-trusty-e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855--node-node.tgz[0m
[32;1mcache uploaded[0m
travis_time:end:17985c53:start=1549816858105359694,finish=1549816865446842204,duration=7341482510
[0Ktravis_fold:end:cache.2
[0K

Done. Your build exited with 1.
```
