### ISSUE TITLE
Error: Cannot find module '@webassemblyjs/ast'

### ISSUE THREAD

**Issue by kingsaiffu** [webpack/webpack#8746]
# Bug report

Currently setting-up my environment for Laravel and whenever I try to run the npm run dev command, it always seem to keep showing me this error.

```
> lsapp@ development D:\XAMPP\htdocs\lsapp
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

D:\XAMPP\htdocs\lsapp\node_modules\webpack-cli\bin\cli.js:231
                                throw err;
                                ^

Error: Cannot find module '@webassemblyjs/ast'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (D:\XAMPP\htdocs\lsapp\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (D:\XAMPP\htdocs\lsapp\node_modules\webpack\lib\wasm\WebAssemblyParser.js:7:11)
    at Module._compile (D:\XAMPP\htdocs\lsapp\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (D:\XAMPP\htdocs\lsapp\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (D:\XAMPP\htdocs\lsapp\node_modules\webpack\lib\wasm\WebAssemblyModulesPlugin.js:8:27)
    at Module._compile (D:\XAMPP\htdocs\lsapp\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (D:\XAMPP\htdocs\lsapp\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (D:\XAMPP\htdocs\lsapp\node_modules\webpack\lib\WebpackOptionsApply.js:11:34)
    at Module._compile (D:\XAMPP\htdocs\lsapp\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (D:\XAMPP\htdocs\lsapp\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (D:\XAMPP\htdocs\lsapp\node_modules\webpack\lib\webpack.js:10:29)
    at Module._compile (D:\XAMPP\htdocs\lsapp\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lsapp@ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the lsapp@ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Coding\AppData\Roaming\npm-cache\_logs\2019-02-06T15_48_29_298Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lsapp@ dev: `npm run development`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the lsapp@ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Coding\AppData\Roaming\npm-cache\_logs\2019-02-06T15_48_29_530Z-debug.log
```

When I run the command, it should compile the css for laravel which would reflect all my current changes for the project.

**Other relevant information:**
webpack version:  4.29.2
Node.js version: 10.15.1
Operating System: Windows 10
Additional tools:
My current set-up in package.json

```
{
    "name": "lsapp",
    "private": true,
    "scripts": {
        "dev": "npm run development",
        "development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
        "watch": "npm run development -- --watch",
        "watch-poll": "npm run watch -- --watch-poll",
        "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
        "prod": "npm run production",
        "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
    },
    "devDependencies": {
        "@webassemblyjs/ast": "^1.8.1",
        "axios": "^0.18.0",
        "webpack": "^4.29.2",
        "webpack-cli": "^3.2.3",
        "bootstrap": "^4.2.1",
        "cross-env": "^5.2.0",
        "jquery": "^3.3.1",
        "laravel-mix": "^4.0.14",
        "lodash": "^4.17.11",
        "popper.js": "^1.14.7",
        "resolve-url-loader": "^3.0.0",
        "sass": "^1.17",
        "sass-loader": "^7.1.0",
        "vue": "^2.6.2"
    }
}
```

**Comment by xtuc** [comment]
Have you tried to `rm -rf node_modules` and `npm install`?

**Comment by kingsaiffu** [comment]
Thank you so much for the quick response!

Before your suggestion, I had tried manually deleting the node_modules folder and then running npm install again.

Both running the command to install all in one time (npm install), and also installing the libraries one at a time(npm install <library>).

Now, I have also tried deleting the folder using the rm command and running the npm install, but to no avail.

```
Coding@asus-pc MINGW64 /d/XAMPP/htdocs/lsapp
$ rm -rf node_modules

Coding@asus-pc MINGW64 /d/XAMPP/htdocs/lsapp
$ npm install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 966 packages from 430 contributors and audited 22162 packages in 128.143s
found 0 vulnerabilities


Coding@asus-pc MINGW64 /d/XAMPP/htdocs/lsapp
$ npm run dev

> lsapp@ dev D:\XAMPP\htdocs\lsapp
> npm run development


> lsapp@ development D:\XAMPP\htdocs\lsapp
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

D:\XAMPP\htdocs\lsapp\node_modules\webpack-cli\bin\cli.js:231
                                throw err;
                                ^

Error: Cannot find module '@webassemblyjs/ast'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (D:\XAMPP\htdocs\lsapp\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (D:\XAMPP\htdocs\lsapp\node_modules\webpack\lib\wasm\WebAssemblyParser.js:7:11)
    at Module._compile (D:\XAMPP\htdocs\lsapp\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (D:\XAMPP\htdocs\lsapp\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (D:\XAMPP\htdocs\lsapp\node_modules\webpack\lib\wasm\WebAssemblyModulesPlugin.js:8:27)
    at Module._compile (D:\XAMPP\htdocs\lsapp\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (D:\XAMPP\htdocs\lsapp\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (D:\XAMPP\htdocs\lsapp\node_modules\webpack\lib\WebpackOptionsApply.js:11:34)
    at Module._compile (D:\XAMPP\htdocs\lsapp\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (D:\XAMPP\htdocs\lsapp\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (D:\XAMPP\htdocs\lsapp\node_modules\webpack\lib\webpack.js:10:29)
    at Module._compile (D:\XAMPP\htdocs\lsapp\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lsapp@ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the lsapp@ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Coding\AppData\Roaming\npm-cache\_logs\2019-02-06T16_15_01_491Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lsapp@ dev: `npm run development`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the lsapp@ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Coding\AppData\Roaming\npm-cache\_logs\2019-02-06T16_15_01_643Z-debug.log
```

**Comment by sokra** [comment]
What's the output of `npm ls @webassemblyjs/ast`?

**Comment by kingsaiffu** [comment]
@sokra the current output is as follows when I run that command

`
$ npm ls @webassemblyjs/ast
lsapp@ D:\XAMPP\htdocs\lsapp
+-- laravel-mix@4.0.14
| `-- webpack@4.29.2
|   `-- UNMET DEPENDENCY @webassemblyjs/ast@1.7.11
`-- webpack@4.29.2
  +-- UNMET DEPENDENCY @webassemblyjs/ast@1.7.11
  | `-- UNMET DEPENDENCY @webassemblyjs/wast-parser@1.7.11
  |   `-- UNMET DEPENDENCY @webassemblyjs/ast@1.7.11
  +-- UNMET DEPENDENCY @webassemblyjs/wasm-edit@1.7.11
  | +-- UNMET DEPENDENCY @webassemblyjs/ast@1.7.11
  | +-- UNMET DEPENDENCY @webassemblyjs/helper-wasm-section@1.7.11
  | | `-- UNMET DEPENDENCY @webassemblyjs/ast@1.7.11
  | +-- UNMET DEPENDENCY @webassemblyjs/wasm-gen@1.7.11
  | | `-- UNMET DEPENDENCY @webassemblyjs/ast@1.7.11
  | +-- UNMET DEPENDENCY @webassemblyjs/wasm-opt@1.7.11
  | | `-- UNMET DEPENDENCY @webassemblyjs/ast@1.7.11
  | `-- UNMET DEPENDENCY @webassemblyjs/wast-printer@1.7.11
  |   `-- UNMET DEPENDENCY @webassemblyjs/ast@1.7.11
  `-- UNMET DEPENDENCY @webassemblyjs/wasm-parser@1.7.11
    `-- UNMET DEPENDENCY @webassemblyjs/ast@1.7.11

npm ERR! missing: @webassemblyjs/ast@1.7.11, required by webpack@4.29.2
npm ERR! missing: @webassemblyjs/wasm-edit@1.7.11, required by webpack@4.29.2
npm ERR! missing: @webassemblyjs/wasm-parser@1.7.11, required by webpack@4.29.2
npm ERR! missing: @webassemblyjs/ast@1.7.11, required by webpack@4.29.2
npm ERR! missing: @webassemblyjs/helper-wasm-section@1.7.11, required by @webassemblyjs/wasm-edit@1.7.11
npm ERR! missing: @webassemblyjs/ast@1.7.11, required by @webassemblyjs/wasm-edit@1.7.11
npm ERR! missing: @webassemblyjs/wasm-gen@1.7.11, required by @webassemblyjs/wasm-edit@1.7.11
npm ERR! missing: @webassemblyjs/wasm-opt@1.7.11, required by @webassemblyjs/wasm-edit@1.7.11
npm ERR! missing: @webassemblyjs/wast-printer@1.7.11, required by @webassemblyjs/wasm-edit@1.7.11
npm ERR! missing: @webassemblyjs/ast@1.7.11, required by @webassemblyjs/helper-wasm-section@1.7.11
npm ERR! missing: @webassemblyjs/ast@1.7.11, required by @webassemblyjs/wasm-gen@1.7.11
npm ERR! missing: @webassemblyjs/ast@1.7.11, required by @webassemblyjs/wasm-opt@1.7.11
npm ERR! missing: @webassemblyjs/ast@1.7.11, required by @webassemblyjs/wast-printer@1.7.11
npm ERR! missing: @webassemblyjs/ast@1.7.11, required by @webassemblyjs/wasm-parser@1.7.11
npm ERR! missing: @webassemblyjs/wast-parser@1.7.11, required by @webassemblyjs/ast@1.7.11
npm ERR! missing: @webassemblyjs/ast@1.7.11, required by @webassemblyjs/wast-parser@1.7.11
`

**Comment by sokra** [comment]
Could you try to delete your package-lock.json file and run `npm i` again?

**Comment by kingsaiffu** [comment]
@sokra I tried deleting package-lock.json as well as node_modules and did a fresh npm install. The problem still seem to persist.

```
Coding@asus-pc MINGW64 /d/XAMPP/htdocs/lsapp
$ rm package-lock.json

Coding@asus-pc MINGW64 /d/XAMPP/htdocs/lsapp
$ rm -rf node_modules

Coding@asus-pc MINGW64 /d/XAMPP/htdocs/lsapp
$ npm install
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 968 packages from 430 contributors and audited 22487 packages in 207.918s
found 0 vulnerabilities
```

This is the log when I try to 'npm run dev':

```
Coding@asus-pc MINGW64 /d/XAMPP/htdocs/lsapp
$ npm run dev

> lsapp@ dev D:\XAMPP\htdocs\lsapp
> npm run development


> lsapp@ development D:\XAMPP\htdocs\lsapp
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

D:\XAMPP\htdocs\lsapp\node_modules\webpack-cli\bin\cli.js:231
                                throw err;
                                ^

Error: Cannot find module '@webassemblyjs/ast'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (D:\XAMPP\htdocs\lsapp\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (D:\XAMPP\htdocs\lsapp\node_modules\webpack\lib\wasm\WebAssemblyParser.js:7:11)
    at Module._compile (D:\XAMPP\htdocs\lsapp\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (D:\XAMPP\htdocs\lsapp\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (D:\XAMPP\htdocs\lsapp\node_modules\webpack\lib\wasm\WebAssemblyModulesPlugin.js:8:27)
    at Module._compile (D:\XAMPP\htdocs\lsapp\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (D:\XAMPP\htdocs\lsapp\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (D:\XAMPP\htdocs\lsapp\node_modules\webpack\lib\WebpackOptionsApply.js:11:34)
    at Module._compile (D:\XAMPP\htdocs\lsapp\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (D:\XAMPP\htdocs\lsapp\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (D:\XAMPP\htdocs\lsapp\node_modules\webpack\lib\webpack.js:10:29)
    at Module._compile (D:\XAMPP\htdocs\lsapp\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lsapp@ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the lsapp@ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Coding\AppData\Roaming\npm-cache\_logs\2019-02-07T12_29_30_629Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lsapp@ dev: `npm run development`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the lsapp@ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Coding\AppData\Roaming\npm-cache\_logs\2019-02-07T12_29_30_752Z-debug.log
```

This is the log when I try to npm ls @webassemblyjs/ast:
```
Coding@asus-pc MINGW64 /d/XAMPP/htdocs/lsapp
$ npm ls @webassemblyjs/ast
lsapp@ D:\XAMPP\htdocs\lsapp
`-- webpack@4.29.3
  +-- UNMET DEPENDENCY @webassemblyjs/ast@1.7.11
  | `-- UNMET DEPENDENCY @webassemblyjs/wast-parser@1.7.11
  |   `-- UNMET DEPENDENCY @webassemblyjs/ast@1.7.11
  +-- UNMET DEPENDENCY @webassemblyjs/wasm-edit@1.7.11
  | +-- UNMET DEPENDENCY @webassemblyjs/ast@1.7.11
  | +-- UNMET DEPENDENCY @webassemblyjs/helper-wasm-section@1.7.11
  | | `-- UNMET DEPENDENCY @webassemblyjs/ast@1.7.11
  | +-- UNMET DEPENDENCY @webassemblyjs/wasm-gen@1.7.11
  | | `-- UNMET DEPENDENCY @webassemblyjs/ast@1.7.11
  | +-- UNMET DEPENDENCY @webassemblyjs/wasm-opt@1.7.11
  | | `-- UNMET DEPENDENCY @webassemblyjs/ast@1.7.11
  | `-- UNMET DEPENDENCY @webassemblyjs/wast-printer@1.7.11
  |   `-- UNMET DEPENDENCY @webassemblyjs/ast@1.7.11
  `-- UNMET DEPENDENCY @webassemblyjs/wasm-parser@1.7.11
    `-- UNMET DEPENDENCY @webassemblyjs/ast@1.7.11

npm ERR! missing: @webassemblyjs/ast@1.7.11, required by webpack@4.29.3
npm ERR! missing: @webassemblyjs/wasm-edit@1.7.11, required by webpack@4.29.3
npm ERR! missing: @webassemblyjs/wasm-parser@1.7.11, required by webpack@4.29.3
npm ERR! missing: @webassemblyjs/wast-parser@1.7.11, required by @webassemblyjs/ast@1.7.11
npm ERR! missing: @webassemblyjs/ast@1.7.11, required by @webassemblyjs/wast-parser@1.7.11
npm ERR! missing: @webassemblyjs/ast@1.7.11, required by @webassemblyjs/wasm-edit@1.7.11
npm ERR! missing: @webassemblyjs/helper-wasm-section@1.7.11, required by @webassemblyjs/wasm-edit@1.7.11
npm ERR! missing: @webassemblyjs/wasm-gen@1.7.11, required by @webassemblyjs/wasm-edit@1.7.11
npm ERR! missing: @webassemblyjs/wasm-opt@1.7.11, required by @webassemblyjs/wasm-edit@1.7.11
npm ERR! missing: @webassemblyjs/wast-printer@1.7.11, required by @webassemblyjs/wasm-edit@1.7.11
npm ERR! missing: @webassemblyjs/ast@1.7.11, required by @webassemblyjs/helper-wasm-section@1.7.11
npm ERR! missing: @webassemblyjs/ast@1.7.11, required by @webassemblyjs/wasm-gen@1.7.11
npm ERR! missing: @webassemblyjs/ast@1.7.11, required by @webassemblyjs/wasm-opt@1.7.11
npm ERR! missing: @webassemblyjs/ast@1.7.11, required by @webassemblyjs/wast-printer@1.7.11
npm ERR! missing: @webassemblyjs/ast@1.7.11, required by @webassemblyjs/wasm-parser@1.7.11
```

This is the current package-json file:
```
{
    "name": "lsapp",
    "private": true,
    "scripts": {
        "dev": "npm run development",
        "development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
        "watch": "npm run development -- --watch",
        "watch-poll": "npm run watch -- --watch-poll",
        "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
        "prod": "npm run production",
        "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
    },
    "devDependencies": {
        "@webassemblyjs/ast": "^1.7.11",
        "@webassemblyjs/helper-code-frame": "^1.7.11",
        "@webassemblyjs/helper-wasm-section": "^1.7.11",
        "@webassemblyjs/wasm-edit": "^1.7.11",
        "@webassemblyjs/wasm-gen": "^1.7.11",
        "@webassemblyjs/wasm-opt": "^1.7.11",
        "@webassemblyjs/wasm-parser": "^1.7.11",
        "@webassemblyjs/wast-parser": "^1.7.11",
        "@webassemblyjs/wast-printer": "^1.7.11",
        "axios": "^0.18.0",
        "bootstrap": "^4.2.1",
        "cross-env": "^5.2.0",
        "jquery": "^3.3.1",
        "laravel-mix": "^4.0.14",
        "lodash": "^4.17.11",
        "popper.js": "^1.14.7",
        "resolve-url-loader": "^3.0.0",
        "sass": "^1.17",
        "sass-loader": "^7.1.0",
        "vue": "^2.6.2",
        "webpack": "^4.29.2",
        "webpack-cli": "^3.2.3"
    }
}
```

**Comment by sokra** [comment]
I copied your package.json and run `npm i`. It installs everything fine.

I used node 10.15.1 and npm 6.4.1 under windows 10 in cmd.

* Could you try normal cmd to install?
* Could you try yarn to install?
* Could you try removing all `@webassemblyjs` entries from package.json? (This won't work anyway, as it installs a different version than webpack)
* Could you try updating node, npm, windows?

**Comment by kingsaiffu** [comment]
@sokra I have the same version of node, npm and windows.
I removed all @webassemblyjs libraries and tried to install it both in cmd and in powershell, yet the same result persists.

On the other hand, after successfully installing using yarn, I ran the npm run dev command again and the error stated in the subject no longer existed.

```
Coding@asus-pc MINGW64 /d/XAMPP/htdocs/lsapp
$ npm run dev

> lsapp@ dev D:\XAMPP\htdocs\lsapp
> npm run development


> lsapp@ development D:\XAMPP\htdocs\lsapp
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

The system cannot find the path specified.
        Additional dependencies must be installed. This will only take a moment.

        Running: npm install vue-template-compiler --save-dev --production=false

npm WARN rm not removing D:\XAMPP\htdocs\lsapp\node_modules\.bin\regjsparser.cmd as it wasn't installed by D:\XAMPP\htdocs\lsapp\node_modules\regjsparser
npm WARN rm not removing D:\XAMPP\htdocs\lsapp\node_modules\.bin\regjsparser as it wasn't installed by D:\XAMPP\htdocs\lsapp\node_modules\regjsparser
npm WARN rm not removing D:\XAMPP\htdocs\lsapp\node_modules\.bin\json5.cmd as it wasn't installed by D:\XAMPP\htdocs\lsapp\node_modules\json5
npm WARN rm not removing D:\XAMPP\htdocs\lsapp\node_modules\.bin\json5 as it wasn't installed by D:\XAMPP\htdocs\lsapp\node_modules\json5
npm WARN rm not removing D:\XAMPP\htdocs\lsapp\node_modules\.bin\jsesc.cmd as it wasn't installed by D:\XAMPP\htdocs\lsapp\node_modules\jsesc
npm WARN rm not removing D:\XAMPP\htdocs\lsapp\node_modules\.bin\jsesc as it wasn't installed by D:\XAMPP\htdocs\lsapp\node_modules\jsesc
npm WARN rm not removing D:\XAMPP\htdocs\lsapp\node_modules\.bin\cssesc.cmd as it wasn't installed by D:\XAMPP\htdocs\lsapp\node_modules\cssesc
npm WARN rm not removing D:\XAMPP\htdocs\lsapp\node_modules\.bin\cssesc as it wasn't installed by D:\XAMPP\htdocs\lsapp\node_modules\cssesc
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN babel-loader@8.0.5 requires a peer of @babel/core@^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

        Okay, done. The following packages have been installed and saved to your package.json dependencies list:

        - vue-template-compiler

 98% after emitting SizeLimitsPlugin

 DONE  Compiled successfully in 11402ms                                                                       8:41:46 PM                                                                                           Asset      Size   Chunks
        Chunk Names
/css/app.css   170 KiB  /js/app  [emitted]  /js/app
  /js/app.js  1.36 MiB  /js/app  [emitted]  /js/app
```

Installing using npm did not solve the problem but Yarn was the countermeasure needed.

Thank you very much for helping. :)

**Solution the Question:**
    - Install using Yarn

**Comment by sokra** [comment]
The whole thing sounds like a npm bug to me

**Comment by mihai-craita** [comment]
I had the same error and I resolved it by changing my first line my webpack.mix.js file:

```
const { mix } = require('laravel-mix');
```
with

```
const mix = require('laravel-mix');
```

npm run dev works like a charm now

**Comment by saber13812002** [comment]
i have the same with windows 10 32 bit with my one of my project
i have the same project with same configuration but it worked as well

node 10.15
npm 6.4.1

**Comment by thaonguyen90** [comment]
<img width="703" alt="Screen Shot 2019-09-28 at 11 32 13 AM" src="https://user-images.githubusercontent.com/15682278/65811510-b1e65980-e1e3-11e9-9950-11b8d6df260b.png">

I have the same problem, has anyone fixed this error yet

**Comment by thaonguyen90** [comment]
UPDATE
FIXED:
update npm last version
rm folder node_moduls
npm install

**Comment by evilebottnawi** [comment]
I close the problem as it is resolved, update your lock file and node_modules, thanks
