### ISSUE TITLE
Angular 6 

### ISSUE THREAD

**Issue by Pratysha** [webpack/webpack#8772]
internal/moodules/cjs/loader.js --> throw err;

Error: Cannot find module '\\yhansw.org.au\dfs\YHAHome\pratyusha.yerramsett\AppD
ata\Roaming\npm\node_modules\@angular\cli\bin\ng'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)

I have tried to uninstall Angular , node as mentioned in various blogs but the error does not resolve.
![angular](https://user-images.githubusercontent.com/32826556/52545441-a9374380-2e0b-11e9-83af-43b9cdc1db89.png)

**Comment by montogeek** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
