### ISSUE TITLE
Latest webpack no longer works with rustwasm

### ISSUE THREAD

**Issue by crazyquark** [webpack/webpack#8781]
# Bug report

**What is the current behavior?**
I just followed this tutorial: 
https://rustwasm.github.io/book/game-of-life/hello-world.html

However, with the latest version of webpack-dev-server the wasm module doesn't load:
```
ERROR in ../pkg/rust_wasm_test_bg.wasm
Module parse failed: Unexpected section: 0xfe
You may need an appropriate loader to handle this file type.
Error: Unexpected section: 0xfe
    at new CompileError (/home/cristian/Desktop/Workspace/rust-wasm-test/www/node_modules/@webassemblyjs/helper-api-error/lib/index.js:40:109)
    at parseSection (/home/cristian/Desktop/Workspace/rust-wasm-test/www/node_modules/@webassemblyjs/wasm-parser/lib/decoder.js:1542:11)
    at Object.decode (/home/cristian/Desktop/Workspace/rust-wasm-test/www/node_modules/@webassemblyjs/wasm-parser/lib/decoder.js:1559:25)
    at decode (/home/cristian/Desktop/Workspace/rust-wasm-test/www/node_modules/@webassemblyjs/wasm-parser/lib/index.js:240:21)
    at WebAssemblyParser.parse (/home/cristian/Desktop/Workspace/rust-wasm-test/www/node_modules/webpack/lib/wasm/WebAssemblyParser.js:74:19)
    at doBuild.err (/home/cristian/Desktop/Workspace/rust-wasm-test/www/node_modules/webpack/lib/NormalModule.js:460:32)
    at runLoaders (/home/cristian/Desktop/Workspace/rust-wasm-test/www/node_modules/webpack/lib/NormalModule.js:342:12)
    at /home/cristian/Desktop/Workspace/rust-wasm-test/www/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/cristian/Desktop/Workspace/rust-wasm-test/www/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/home/cristian/Desktop/Workspace/rust-wasm-test/www/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/home/cristian/Desktop/Workspace/rust-wasm-test/www/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:43:16)
    at provider (/home/cristian/Desktop/Workspace/rust-wasm-test/www/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:79:9)
    at /home/cristian/Desktop/Workspace/rust-wasm-test/www/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
 @ ../pkg/rust_wasm_test.js 2:0-44 8:71-82 9:45-56 26:11-21
 @ ./index.js
 @ ./bootstrap.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./bootstrap.js

ERROR in chunk 0
077d415e7c86fc0caa5c.module.wasm
/home/cristian/Desktop/Workspace/rust-wasm-test/pkg/rust_wasm_test_bg.wasm
unexpected end
```

If I downgrade webpack to 4.16.2 then it works.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
It should load the generated WASM module

**Other relevant information:**
webpack version:  4.29.3
Node.js version: v10.6.0
Operating System: Linux x64
Additional tools: nvm

**Comment by montogeek** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

**Comment by crazyquark** [comment]
Updated issue

**Comment by sokra** [comment]
@xtuc

**Comment by macmillen** [comment]
++

**Comment by ize8** [comment]
any solution to this error yet? I spent the last few days to get this work with CRA, but nothing seems to work :(

**Comment by gliheng** [comment]
Hey @ize8 , I came into this problem today. It's fixed. You need to update webpack. I'm sure webpack@4.29.5 works.

**Comment by ize8** [comment]
@gliheng, amazing, thank you! CRA eject it is then ...
