### ISSUE TITLE
`libsass` bindings not found. Try reinstalling `node-sass`

### ISSUE THREAD

**Issue by haf** [webpack/webpack#880]
I'm having trouble using webpack - it's a repo that used to work, but now I'm stuck.

It won't help to reinstall node-sass, because it's a docker image where I reinstall every single time, so I have tried it.

Grateful for any help.

```
node node_modules/webpack/bin/webpack.js
Error: `libsass` bindings not found. Try reinstalling `node-sass`?
    at getBinding (/home/builder/src/node_modules/node-sass/lib/index.js:22:11)
    at Object.<anonymous> (/home/builder/src/node_modules/node-sass/lib/index.js:188:23)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/builder/src/node_modules/sass-loader/index.js:4:12)
    at Module._compile (module.js:460:26)
```

**Comment by haf** [comment]
```
  "devDependencies": {
    "css-loader": "*",
    "file-loader": "*",
    "jsx-loader": "*",
    "sass": "*",
    "sass-loader": "*",
    "style-loader": "*",
    "url-loader": "*",
    "webpack": "*",
    "webpack-dev-server": "*"
  },
  "dependencies": {
    "fractional": "git+https://github.com/ekg/fraction.js.git#HEAD",
    "immutable": "^3.4.1",
    "jquery": "^2.1.1",
    "moment": "^2.9.0",
    "node-sass": "^2.0.1",
    "react": "^0.12.1",
    "react-datepicker": "*",
    "react-router": "^0.11.6",
    "uri-templates": "^0.1.5"
  }
}
```

**Comment by haf** [comment]
If I downgrade to what used to work, I get this instead:

```
npm ERR! node-sass@1.2.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@1.2.3 postinstall script 'node scripts/build.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.
```

**Comment by browniefed** [comment]
What version of node are you using and what version of node gets detected by node-sass.
I've run into this issue running node v.12 but a maven plugin was running v.10.36 and the correct bindings didn't get pulled down.

**Comment by haf** [comment]
I've tried using v0.10 and v0.12.

I've tried all latest 1.x, 2.x and 3.x releases no node-sass.

**Comment by haf** [comment]
I've tried using both root to install node-sass then I get something like https://stackoverflow.com/questions/22152162/npm-cannot-install-dependencies-attempt-to-unlock-something-which-hasnt-been or not root, and then I get the above errors.

**Comment by browniefed** [comment]
@haf when you do an npm install of node-sass go into the node_modules, into the `vendor` folder and check out what it has downloaded as its bindings.

Also this has nothing to do with webpack. Thought we were in node-sass repo

**Comment by haf** [comment]
Ok, let's close this in favor of the other thread!
