### ISSUE TITLE
Webpack fails when including files from `/packages/moduleName/node_modules`

### ISSUE THREAD

**Issue by robtarr** [webpack/webpack#8809]
# Bug report

**What is the current behavior?**
**Describe the bug**
Using Lerna and Storybook,js.org, each of my modules has it's own `node_modules` folder. When Webpack bundles `moment` (and other dependencies) from `packages/moduleName/node_modules` it does not get bundled correctly. This results in 
```
Cannot set property 'moment' of undefined
    TypeError: Cannot set property 'moment' of undefined
    at http://localhost:6007/vendors~main.f4ce6b32bc79f7651537.bundle.js:66663:309
    at Module.<anonymous> (http://localhost:6007/vendors~main.f4ce6b32bc79f7651537.bundle.js:66664:3)
    at Module../packages/timeModule/node_modules/moment/moment.js (http://localhost:6007/vendors~main.f4ce6b32bc79f7651537.bundle.js:71242:30)
    at __webpack_require__ (http://localhost:6007/runtime~main.f4ce6b32bc79f7651537.bundle.js:782:30)
    at fn (http://localhost:6007/runtime~main.f4ce6b32bc79f7651537.bundle.js:150:20)
    at Module../packages/timeModule/index.js (http://localhost:6007/main.f4ce6b32bc79f7651537.bundle.js:71:64)
    at __webpack_require__ (http://localhost:6007/runtime~main.f4ce6b32bc79f7651537.bundle.js:782:30)
    at fn (http://localhost:6007/runtime~main.f4ce6b32bc79f7651537.bundle.js:150:20)
    at Module.<anonymous> (http://localhost:6007/main.f4ce6b32bc79f7651537.bundle.js:48:59)
    at Module../packages/timeModule/index-story.js (http://localhost:6007/main.f4ce6b32bc79f7651537.bundle.js:56:30)
```

**If the current behavior is a bug, please provide the steps to reproduce.**
I have put together a repo top show this problem.
https://github.com/robtarr/storybook-test
- `master` is in the broken state
- `working-without-lerna` builds correctly

1. `git checkout working-without-lerna`
1. `npm install`
1. `npm start`
1. http://localhost:6007 should show the current time
1. `git checkout master`
1. `npm install`
1. `npm start`
1. http://localhost:6007 should show an error message

In the broken version, it appears that Webpack simply includes `moment.js` as is and results in:
```
Cannot set property 'moment' of undefined
    TypeError: Cannot set property 'moment' of undefined
    at http://localhost:6007/vendors~main.f4ce6b32bc79f7651537.bundle.js:66663:309
    at Module.<anonymous> (http://localhost:6007/vendors~main.f4ce6b32bc79f7651537.bundle.js:66664:3)
    at Module../packages/timeModule/node_modules/moment/moment.js (http://localhost:6007/vendors~main.f4ce6b32bc79f7651537.bundle.js:71242:30)
    at __webpack_require__ (http://localhost:6007/runtime~main.f4ce6b32bc79f7651537.bundle.js:782:30)
    at fn (http://localhost:6007/runtime~main.f4ce6b32bc79f7651537.bundle.js:150:20)
    at Module../packages/timeModule/index.js (http://localhost:6007/main.f4ce6b32bc79f7651537.bundle.js:71:64)
    at __webpack_require__ (http://localhost:6007/runtime~main.f4ce6b32bc79f7651537.bundle.js:782:30)
    at fn (http://localhost:6007/runtime~main.f4ce6b32bc79f7651537.bundle.js:150:20)
    at Module.<anonymous> (http://localhost:6007/main.f4ce6b32bc79f7651537.bundle.js:48:59)
    at Module../packages/timeModule/index-story.js (http://localhost:6007/main.f4ce6b32bc79f7651537.bundle.js:56:30)
```

When running without the `node_modules` folder inside of the module, it modifies moment's loading code in `vendors~main.######.js` to
```
/***/ "./node_modules/moment/moment.js":
/*!***************************************!*\
  !*** ./node_modules/moment/moment.js ***!
  \***************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

/* WEBPACK VAR INJECTION */(function(module) {var require;//! moment.js

;(function (global, factory) {
     true ? module.exports = factory() :
    undefined
}(this, (function () { 'use strict';
```

**What is the expected behavior?**
I expect that Webpack includes `moment.js` from `/packages/moduleName/node_modules` the same way it would as if it were in `/node_modules`.

**Other relevant information:**
webpack version:  4.28.4
Node.js version: 10.11.0
Operating System: MacOS 10.14.2
Additional tools: StoryBook 4.1.11, Lerna, Babel@7

I cross posted this issue with Storybook - https://github.com/storybooks/storybook/issues/5651

**Comment by robtarr** [comment]
This was due to an error in my alias config.
