### ISSUE TITLE
Error: Cannot find module 'os-locale/index.js'

### ISSUE THREAD

**Issue by forest1102** [webpack/webpack#8848]
After I webpack and output bundle.js, I try to execute `node ./lib/bundle.js`, but the following error occurred. 

```
Error: Cannot find module '/Users/***/Desktop/basblu/node_modules/os-locale/index.js'
    at webpackEmptyContext (/Users/***/Desktop/basblu/lib/bundle.js:90812:10)
    at ./node_modules/require-uncached/index.js.module.exports (/Users/***/Desktop/basblu/lib/bundle.js:90858:78)
    at Object.<anonymous> (/Users/***/Desktop/basblu/lib/bundle.js:17421:23)
    at Object../node_modules/cheerio-httpcli/lib/client.js (/Users/***/Desktop/basblu/lib/bundle.js:18010:30)
    at __webpack_require__ (/Users/***/Desktop/basblu/lib/bundle.js:20:30)
    at Object../node_modules/cheerio-httpcli/lib/core.js (/Users/***/Desktop/basblu/lib/bundle.js:18032:21)
    at __webpack_require__ (/Users/***/Desktop/basblu/lib/bundle.js:20:30)
    at Object../node_modules/cheerio-httpcli/index.js (/Users/***/Desktop/basblu/lib/bundle.js:16133:18)
    at __webpack_require__ (/Users/***/Desktop/basblu/lib/bundle.js:20:30)
    at Object.<anonymous> (/Users/***/Desktop/basblu/lib/bundle.js:120813:16)
```

## webpack.config.js

```
const path = require('path')

module.exports = {
  mode: 'development',
  entry: './src/index.ts',
  target: 'node',
  devtool: 'inline-source-map',
  module: {
    rules: [
      // All files with a '.ts' or '.tsx' extension will be handled by 'awesome-typescript-loader'.
      { test: /\.tsx?$/, loader: 'awesome-typescript-loader' },

      // All output '.js' files will have any sourcemaps re-processed by 'source-map-loader'.
      { enforce: 'pre', test: /\.js$/, loader: 'source-map-loader' }
    ]
  },
  resolve: {
    extensions: ['.tsx', '.ts', '.js'],
    modules: ['node_modules']
  },

  output: {
    filename: 'bundle.js',
    path: path.resolve(__dirname, 'lib'),
    publicPath: '',
    library: '',
    libraryTarget: 'commonjs'
  }
}
```

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template.
