### ISSUE TITLE
Critical dependency error when use react-loadable

### ISSUE THREAD

**Issue by chnliquan** [webpack/webpack#8893]
# Bug report

**What is the current behavior?**
In the code splite, `react-loadable is used`. For reuse, I encapsulate the `Loadable` function and return a loadable component through the path of the incoming component, but this causes an error `Critical dependency: the request of a dependency is an expression`, the page is always in the loading state, and the component is not loaded. If I don't use function encapsulation and use Loadable directly, there will be no problem.

```js
// wrong
import Loadable from 'react-loadable'

const LoadableComponent = path => {
  return Loadable({
    loader: () => import(path),
    loading() {
      return <CircularProgress />
    },
  })
}

const TopticList = LoadableComponent('views/topic-list')

export default () => [
  <Route exact render={() => <Redirect to="/list" />} path="/" key="home" />,
  <Route component={TopticList} path="/list" key="list" />,
```

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
```js
// right
import Loadable from 'react-loadable'

const TopticList = Loadable({
  loader: () => import('views/topic-list'),
  loading() {
    return <CircularProgress />
  },
})

const TopticList = LoadableComponent('views/topic-list')

export default () => [
  <Route exact render={() => <Redirect to="/list" />} path="/" key="home" />,
  <Route component={TopticList} path="/list" key="list" />,
```

**Other relevant information:**
webpack version:  4.29.5
Node.js version: 8.12.0
Operating System: os 10.3.0
react-loadable: 5.5.0

**Comment by sokra** [comment]
You code is too dynamic and not statically analysable. Rewrite it to have at least a partially constant expression in `import()`.

Maybe this way:

``` js
const TopticList = LoadableComponent(() => import('views/topic-list'))
```

**Comment by chnliquan** [comment]
@sokra 
```js
import React from 'react'
import { Route, Redirect, withRouter, } from 'react-router-dom'
import { inject, observer, } from 'mobx-react'
import Loadable from 'react-loadable'

import CircularProgress from '@material-ui/core/CircularProgress'

import compose from 'utils/compose'

// 结合 mobx 或者 redux 需要将 withRouter 放在最外层
// https://reacttraining.com/react-router/web/api/withRouter
const LoginRoute = ({ isLogin, component: Component, ...rest }) =>
  <Route
    {...rest}
    render={
      props =>
        isLogin ? <Component {...props} /> :
          <Redirect to={{ pathname: '/user/login', search: `?from=${rest.path}`, }} />
    }
  />

const InjectedRoute = compose(
  withRouter,
  inject(stores => ({
    isLogin: stores.appStore.user.isLogin,
  })),
  observer,
)(LoginRoute)

const LoadableComponent = path => {
  return Loadable({
    loader: () => import(path),
    loading() {
      return <CircularProgress />
    },
  })
}

const TopicList = Loadable({
  loader: () => import('views/topic-list'),
  loading() {
    return <CircularProgress />
  },
})

export default () => [
  <Route exact render={() => <Redirect to="/list" />} path="/" key="home" />,
  <Route component={TopicList} path="/list" key="list" />,
  <Route component={LoadableComponent('views/topic-detail')} path="/detail/:id" key="detail" />,
  <Route component={LoadableComponent('views/user/login')} path="/user/login" key="login" />,
  <InjectedRoute component={LoadableComponent('views/user/info')} path="/user/info" key="info" />,
  <InjectedRoute component={LoadableComponent('views/topic-create')} path="/topic/create" key="create" />,
]
```
There is still a problem with your solution

```
Error: Cannot find module './0.server-entry.js'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Function.requireEnsure [as e] (server-entry.js:46:25)
    at loader (webpack:///./client/router/index.jsx?:68:60)
    at load (/Users/ender/learning/github/react-cnode/node_modules/react-loadable/lib/index.js:28:17)
    at init (/Users/ender/learning/github/react-cnode/node_modules/react-loadable/lib/index.js:121:13)
    at new LoadableComponent (/Users/ender/learning/github/react-cnode/node_modules/react-loadable/lib/index.js:150:7)
    at /Users/ender/learning/github/react-cnode/node_modules/react-tree-walker/dist/react-tree-walker.js:174:30 code: 'MODULE_NOT_FOUND'
```

**Comment by chnliquan** [comment]
i use react ssr, after using react-loaderable, the server portal page has been packed a lot. When I started the server, I only read the server-entry on the hard disk. Other versions don't know where to come from. and the issue is above

```
0.server-entry.js  75.5 KiB       0  [emitted]  
2.server-entry.js  25.7 KiB       2  [emitted]  
3.server-entry.js  11.6 KiB       3  [emitted]  
4.server-entry.js  13.3 KiB    4, 9  [emitted]  
5.server-entry.js  9.04 KiB       5  [emitted]  
6.server-entry.js  5.95 KiB       6  [emitted]  
7.server-entry.js  6.38 KiB       7  [emitted]  
8.server-entry.js     5 KiB       8  [emitted]  
9.server-entry.js     2 KiB       9  [emitted]  
  server-entry.js   116 KiB       1  [emitted]  app
```

**Comment by RevanScript** [comment]
@chnliquan have you found the solution? I'm experiencing the same problem.

**Comment by Schachte** [comment]
I'm having this same issue as well.

**Comment by imkane** [comment]
I'm also having this issue
