### ISSUE TITLE
ProfilingPlugin crashes with devserver and in watch mode

### ISSUE THREAD

**Issue by villesau** [webpack/webpack#9114]
# Bug report

**What is the current behavior?**

When using ProfilingPlugin and run webpack in `--watch` mode or devserver, following error is thrown:

```
 98% after emitting(node:79437) UnhandledPromiseRejectionWarning: Error [ERR_INSPECTOR_NOT_CONNECTED]: Session is not connected
    at Session.post (inspector.js:75:13)
    at Promise (/Users/path/to/code/node_modules/webpack/lib/debug/ProfilingPlugin.js:54:25)
    at new Promise (<anonymous>)
    at Profiler.sendCommand (/Users/path/to/code/node_modules/webpack/lib/debug/ProfilingPlugin.js:53:11)
    at Profiler.stopProfiling (/Users/path/to/code/node_modules/webpack/lib/debug/ProfilingPlugin.js:76:15)
    at compiler.hooks.done.tapAsync (/Users/path/to/code/node_modules/webpack/lib/debug/ProfilingPlugin.js:209:21)
    at args (/Users/path/to/code/node_modules/webpack/lib/debug/ProfilingPlugin.js:394:11)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/path/to/code/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:18:1)
    at Watching._done (/Users/path/to/code/node_modules/webpack/lib/Watching.js:97:28)
    at compiler.emitRecords.err (/Users/path/to/code/node_modules/webpack/lib/Watching.js:72:19)
    at Compiler.emitRecords (/Users/path/to/code/node_modules/webpack/lib/Compiler.js:449:39)
    at compiler.emitAssets.err (/Users/path/to/code/node_modules/webpack/lib/Watching.js:53:20)
    at hooks.afterEmit.callAsync.err (/Users/path/to/code/node_modules/webpack/lib/Compiler.js:435:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/path/to/code/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:9:1)
    at asyncLib.forEachLimit.err (/Users/path/to/code/node_modules/webpack/lib/Compiler.js:432:27)
    at /Users/path/to/code/node_modules/neo-async/async.js:2760:7
    at done (/Users/path/to/code/node_modules/neo-async/async.js:3450:9)
    at /Users/path/to/code/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:141:20)
(node:79437) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:79437) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

After this webpack does not crash completely, but no files are watched anymore. events.json file is produced, but I'm fairly sure it does not contain anything from the point when exception is thrown.

This makes it fairly difficult to debug performance issues in incremental builds.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. setup the plugin like in documentation
2. run webpack in watch mode
3. after initial build modify watched file -> error thrown

**What is the expected behavior?**

plugin should not crash

**Other relevant information:**
webpack version:  4.31.0
Node.js version: v10.15.0
Operating System: macOS 10.14.4
Additional tools: 

@pleunv seems to be experiencing the same: https://github.com/webpack/webpack/issues/6767#issuecomment-384713454

**Comment by evilebottnawi** [comment]
Looks like a bug, feel free to send a PR

**Comment by villesau** [comment]
How the plugin knows when webpack is in watch mode? I think that the plugin should use some different hooks when in watch mode: https://webpack.js.org/api/compiler-hooks/#watching . Looks like `compiler` here: https://github.com/webpack/webpack/blob/master/lib/debug/ProfilingPlugin.js#L167 has `watchMode` (or similar) flag but it's always false no matter wether webpack is in watch mode or not.

Are there examples of similar behaviour where plugin would behave slightly differently wether it's in watch mode or not?

**Comment by evilebottnawi** [comment]
bump

**Comment by IronSean** [comment]
This is really frustrating when you're attempting to profile an incremental build. And by really frustrating, I mean it makes it impossible.

**Comment by evilebottnawi** [comment]
bump

**Comment by swillis12** [comment]
Any news or workaround for this?

**Comment by evilebottnawi** [comment]
No, need send a fix

**Comment by vjpr** [comment]
Any update?

**Comment by alexander-akait** [comment]
Still need fix

**Comment by seiyab** [comment]
I encountered it too.

**Comment by alexander-akait** [comment]
bump

**Comment by Mathieuu** [comment]
Same problem here!

**Comment by heyheyhello** [comment]
Is this Node crash known to be related to the ProfilingPlugin crash? When using `--watch` I get:

```
splunk-web-ui/web_v2 on  webpack5 [$] via △ v3.13.5 via  v16.3.0
❯ npx webpack --config ./build_tools/profiles/pages_enterprise.config.js --mode=development --no-devtool --watch
(node:20226) [DEP_WEBPACK_COMPILATION_NORMAL_MODULE_LOADER_HOOK] DeprecationWarning: Compilation.hooks.normalModuleLoader was moved to NormalModule.getCompilationHooks(compilation).loader
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:20226) [DEP_WEBPACK_MODULE_ID] DeprecationWarning: Module.id: Use new ChunkGraph API
FATAL ERROR: v8::ToLocalChecked Empty MaybeLocal.
 1: 0x10eb0d985 node::Abort() (.cold.1) [/usr/local/bin/node]
 2: 0x10d7c0aa9 node::Abort() [/usr/local/bin/node]
 3: 0x10d7c0c25 node::OnFatalError(char const*, char const*) [/usr/local/bin/node]
 4: 0x10d93f700 v8::V8::ToLocalEmpty() [/usr/local/bin/node]
 5: 0x10d8a69a7 node::inspector::(anonymous namespace)::JSBindingsConnection<node::inspector::(anonymous namespace)::LocalConnection>::JSBindingsSessionDelegate::SendMessageToFrontend(v8_inspector::StringView const&) [/usr/local/bin/node]
 6: 0x10d89c58b node::inspector::(anonymous namespace)::ChannelImpl::sendResponse(int, std::__1::unique_ptr<v8_inspector::StringBuffer, std::__1::default_delete<v8_inspector::StringBuffer> >) [/usr/local/bin/node]
 7: 0x10e086cf7 non-virtual thunk to v8_inspector::V8InspectorSessionImpl::SendProtocolResponse(int, std::__1::unique_ptr<v8_crdtp::Serializable, std::__1::default_delete<v8_crdtp::Serializable> >) [/usr/local/bin/node]
 8: 0x10e0b4085 v8_crdtp::DomainDispatcher::sendResponse(int, v8_crdtp::DispatchResponse const&, std::__1::unique_ptr<v8_crdtp::Serializable, std::__1::default_delete<v8_crdtp::Serializable> >) [/usr/local/bin/node]
 9: 0x10e18f701 v8_inspector::protocol::Profiler::DomainDispatcherImpl::stop(v8_crdtp::Dispatchable const&) [/usr/local/bin/node]
10: 0x10e0b49e8 v8_crdtp::UberDispatcher::DispatchResult::Run() [/usr/local/bin/node]
11: 0x10e087d42 v8_inspector::V8InspectorSessionImpl::dispatchProtocolMessage(v8_inspector::StringView) [/usr/local/bin/node]
12: 0x10d89cfae node::inspector::NodeInspectorClient::dispatchMessageFromFrontend(int, v8_inspector::StringView const&) [/usr/local/bin/node]
13: 0x10d89cbfa node::inspector::(anonymous namespace)::SameThreadInspectorSession::Dispatch(v8_inspector::StringView const&) [/usr/local/bin/node]
14: 0x10d8a58cf node::inspector::(anonymous namespace)::JSBindingsConnection<node::inspector::(anonymous namespace)::LocalConnection>::Dispatch(v8::FunctionCallbackInfo<v8::Value> const&) [/usr/local/bin/node]
15: 0x10d9b2805 v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo) [/usr/local/bin/node]
16: 0x10d9b1dd8 v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/usr/local/bin/node]
17: 0x10d9b138f v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/usr/local/bin/node]
18: 0x10e23e299 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit [/usr/local/bin/node]
19: 0x10e1d6d45 Builtins_InterpreterEntryTrampoline [/usr/local/bin/node]
fish: Job 1, 'npx webpack --config ./build_to…' terminated by signal SIGABRT (Abort)

splunk-web-ui/web_v2 on  webpack5 [$] via △ v3.13.5 via  v16.3.0 took 4m43s
```
The deprecation warnings go away if I comment out the plugin

```js
// new webpack.debug.ProfilingPlugin(),
```
