### ISSUE TITLE
Error from mini-css-extract-plugin introduced by 4.32.0

### ISSUE THREAD

**Issue by aaronjensen** [webpack/webpack#9156]
# Bug report

**What is the current behavior?**

```
Module build failed (from /home/circleci/project/node_modules/mini-css-extract-plugin/dist/loader.js):
  TypeError: Cannot read property 'identifier' of null
      at text.map.line (/home/circleci/project/node_modules/mini-css-extract-plugin/dist/loader.js:160:32)
      at Array.map (<anonymous>)
      at childCompiler.runAsChild (/home/circleci/project/node_modules/mini-css-extract-plugin/dist/loader.js:157:21)
      at compile (/home/circleci/project/node_modules/webpack/lib/Compiler.js:306:11)
      at hooks.afterCompile.callAsync.err (/home/circleci/project/node_modules/webpack/lib/Compiler.js:631:15)
      at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/circleci/project/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:24:1)
      at AsyncSeriesHook.lazyCompileHook (/home/circleci/project/node_modules/tapable/lib/Hook.js:154:20)
      at compilation.seal.err (/home/circleci/project/node_modules/webpack/lib/Compiler.js:628:31)
      at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/circleci/project/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
      at AsyncSeriesHook.lazyCompileHook (/home/circleci/project/node_modules/tapable/lib/Hook.js:154:20)
      at hooks.optimizeAssets.callAsync.err (/home/circleci/project/node_modules/webpack/lib/Compilation.js:1329:35)
      at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/circleci/project/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
      at AsyncSeriesHook.lazyCompileHook (/home/circleci/project/node_modules/tapable/lib/Hook.js:154:20)
      at hooks.optimizeChunkAssets.callAsync.err (/home/circleci/project/node_modules/webpack/lib/Compilation.js:1320:32)
      at _promise1.then._result1 (eval at create (/home/circleci/project/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:18:1)
      at <anonymous>
   @ ./style/index.ts 1:0-29
   @ multi ./common/errorTracker ./common/polyfills ./style ./frames/about
```

**If the current behavior is a bug, please provide the steps to reproduce.**

My configuration is huge. I'd be happy to try and narrow down a minimal repro if necessary, but I hope that the error would be obvious given that this is a regression in a minor release. If it's not, just let me know.

**What is the expected behavior?**

There should be no error during build.

**Other relevant information:**
webpack version:  4.32.0
Node.js version: 8.9.0
Operating System: macOS 10.14.5
Additional tools: mini-css-extract-plugin 0.4.4

**Comment by sokra** [comment]
I can't read much from the error message: It seems like a module couldn't be found in the child compilation. Not sure why.

**Comment by luckyvin** [comment]
I have the same problem. Buld fails by starting task on jenkins with grunt.
While I starting ng build with sudo grunts on target folder all correct.
Otherwise this problem doesn't performs on local windows build.

Webpack: 4.29.6
Node.js: 8.11.3
OS: Ubuntu
mini-css-extract-plugin 0.5.0

**Comment by sokra** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by ghaiat** [comment]
same issue here:

ERROR in ./src/styles.scss
Module build failed (from /bitrise/src/node_modules/mini-css-extract-plugin/dist/loader.js):
TypeError: Cannot read property 'identifier' of null
    at text.map.line (/bitrise/src/node_modules/mini-css-extract-plugin/dist/loader.js:134:32)
    at Array.map (<anonymous>)
    at childCompiler.runAsChild (/bitrise/src/node_modules/mini-css-extract-plugin/dist/loader.js:131:21)
    at compile (/bitrise/src/node_modules/webpack/lib/Compiler.js:306:11)
    at hooks.afterCompile.callAsync.err (/bitrise/src/node_modules/webpack/lib/Compiler.js:631:15)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/bitrise/src/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (/bitrise/src/node_modules/tapable/lib/Hook.js:154:20)
    at compilation.seal.err (/bitrise/src/node_modules/webpack/lib/Compiler.js:628:31)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/bitrise/src/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (/bitrise/src/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.optimizeAssets.callAsync.err (/bitrise/src/node_modules/webpack/lib/Compilation.js:1329:35)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/bitrise/src/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/bitrise/src/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.optimizeChunkAssets.callAsync.err (/bitrise/src/node_modules/webpack/lib/Compilation.js:1320:32)
    at _err2 (eval at create (/bitrise/src/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:27:1)
    at taskRunner.run (/bitrise/src/node_modules/terser-webpack-plugin/dist/index.js:318:9)

**Comment by sschoorens** [comment]
I got the same problem in angular cli build, I was using a webpack version too recent 4.32 it works with the 4.29 one

**Comment by stephanrauh** [comment]
Same here. The bug occurs only with the production build (ng build --prod). 

I'm running Windows 10 (but I don't think the OS doesn't make any difference)

**Comment by stephanrauh** [comment]
Here's a reproducer: https://github.com/opitzconsulting/ui-frontend-integration/tree/webpack-issue-9156

The repository actually is a monorepository containing four projects. Luckily, each of the projects is simple. You can reproduce the bug in less than five minutes. Follow these steps:

* checkout the repo
* git checkout webpack-issue-9156
* cd into the new folder
* cd basket/source/basket
* npm install
* ng build --prod

Now you should see the error. It's a regression between 4.31.0 and 4.32.0.
*

**Comment by ttudor** [comment]
Long time user of webpack, got into the same problem with mini-css-extract-plugin. Spent some time and this is what I found. My knowledge of Webpack internals is far too superficial to fully  understand it, but I hope it will be of some help to somebody more knowledgeable than myself.

The problem (in mini-css-extract-plugin) lies in `loader.js` around line 160;

```javascript
text = text.map(line => {
  const module = findModuleById(compilation.modules, line[0]);
  return {
    identifier: module.identifier(),
    content: line[1],
    media: line[2],
    sourceMap: line[3]
  };
});
```
The problem is that `line[0]` contains `undefined`, so `module` is `null`

The `text` is actually a `module.exports` coming from the following (line 52 of `loader.js`):

```javascript
const exec = (loaderContext, code, filename) => {
  const module = new _module.default(filename, loaderContext);
  module.paths = _module.default._nodeModulePaths(loaderContext.context); // eslint-disable-line no-underscore-dangle
  module.filename = filename;
  module._compile(code, filename); // eslint-disable-line no-underscore-dangle
  return module.exports;
};

// _module is defined as follows:

var _module = _interopRequireDefault(require("module"));
function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }
```
Up to 4.31.0, the `module.exports` contains a list of of lists, the first element of the first list (the `line[0]` above) being `0`.
Once we get to 4.32.0 the first element of the first list is `undefined`.

This is as far as I could get, and as said already - I am not knowledgeable enough to go deeper.
Maybe a problem with the way the module identifier is handled for ES modules ? Wild guessing ...
Cheers !

**Comment by roblan** [comment]
@sokra here is the smallest example https://github.com/roblan/webpack-issue-9156

line https://github.com/roblan/webpack-issue-9156/blob/master/webpack.config.js#L21 seems to introduce the problem.

**Comment by matthiasbaldi** [comment]
@stephanrauh we got the same issue on Windows 10 and Linux (Windows Subsystem and Jenkins).
Also the node version does not matter, so it must be a problem somewhere in the webpack stack, as already reproduced.

**Comment by KondakovArtem** [comment]
Hello, i found the problem

in file:///../node_modules/mini-css-extract-plugin/dist/loader.js

in this line
`try {
      text = exec(this, source, request);   
      locals = text && text.locals;`

the variable source has wrong generated code string

![Снимок](https://user-images.githubusercontent.com/12134542/58103563-dbff8d80-7beb-11e9-9e4f-1d54a24fec5e.PNG)

expected module.i (has value), but is module.id (is undefined)

Does anyone know where the value of the variable "source" is generated

**Comment by jaikme** [comment]
Very good, I've been trying to find the problem all day.
Does this have anything to do with core-js @ 3?

**Comment by sokra** [comment]
should be fixed in 4.32.1

**Comment by kabe5965** [comment]
Version 4.32.1 fixed it. Great work!

**Comment by matthiasbaldi** [comment]
Yeah fixed. Thank you. Great and fast work!

**Comment by jaikme** [comment]
Thanks guys

**Comment by stephanrauh** [comment]
I'm impressed by your fast reaction. Keep up the good work!

**Comment by zensarCompass** [comment]
Version 4.32.1 fixed it. Working fine. Thanks!

**Comment by OtabekSadiridinov** [comment]
Please fix that

**Comment by stephanrauh** [comment]
@OtabekSadiridinov Several people confirmed above that the bug has been fixed. So I suppose you should add a few words what happened. What are you trying to do? Which version of the plugin are you using? What does the error look like on your machine? I guess you also need to open a new issue. This issue is closed. Probably it'll slip the attention of the team.

**Comment by cbernth** [comment]
@OtabekSadiridinov I got the same problem after migrating an SSR app to 9.x (from 6.x). After lot's of troubleshooting it turned out I was having two references to styles.css (one in app.component.ts, one in angular.json). Removing the one in app.component removed the build error.

The funky stuff is that I got two different errors in prod and dev builds for the same problem:
ng build:

`ERROR in document is not defined`

ng build --prod

```
ERROR in Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
TypeError: Cannot read property 'replace' of undefined
    at normalizeBackSlashDirection (D:\Data\Visual Studio\SjareIt.Site\AspNetCoreSpaPrerendering\ClientApp\node_modules\webpack\lib\RequestShortener.js:16:17)
    at new RequestShortener (D:\Data\Visual Studio\SjareIt.Site\AspNetCoreSpaPrerendering\ClientApp\node_modules\webpack\lib\RequestShortener.js:26:15)
    at new Compiler (D:\Data\Visual Studio\SjareIt.Site\AspNetCoreSpaPrerendering\ClientApp\node_modules\webpack\lib\Compiler.js:195:27)
    at Compiler.createChildCompiler (D:\Data\Visual Studio\SjareIt.Site\AspNetCoreSpaPrerendering\ClientApp\node_modules\webpack\lib\Compiler.js:558:25)
    at Compilation.createChildCompiler (D:\Data\Visual Studio\SjareIt.Site\AspNetCoreSpaPrerendering\ClientApp\node_modules\webpack\lib\Compilation.js:2243:24)
    at Object.pitch (D:\Data\Visual Studio\SjareIt.Site\AspNetCoreSpaPrerendering\ClientApp\node_modules\mini-css-extract-plugin\dist\loader.js:89:43)
error Command failed with exit code 1.
```
Both errors were fixed by removing the duplicate style entry.

**Comment by Abunyousra** [comment]
> # Bug report
> **What is the current behavior?**
> 
> ```
> Module build failed (from /home/circleci/project/node_modules/mini-css-extract-plugin/dist/loader.js):
>   TypeError: Cannot read property 'identifier' of null
>       at text.map.line (/home/circleci/project/node_modules/mini-css-extract-plugin/dist/loader.js:160:32)
>       at Array.map (<anonymous>)
>       at childCompiler.runAsChild (/home/circleci/project/node_modules/mini-css-extract-plugin/dist/loader.js:157:21)
>       at compile (/home/circleci/project/node_modules/webpack/lib/Compiler.js:306:11)
>       at hooks.afterCompile.callAsync.err (/home/circleci/project/node_modules/webpack/lib/Compiler.js:631:15)
>       at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/circleci/project/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:24:1)
>       at AsyncSeriesHook.lazyCompileHook (/home/circleci/project/node_modules/tapable/lib/Hook.js:154:20)
>       at compilation.seal.err (/home/circleci/project/node_modules/webpack/lib/Compiler.js:628:31)
>       at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/circleci/project/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
>       at AsyncSeriesHook.lazyCompileHook (/home/circleci/project/node_modules/tapable/lib/Hook.js:154:20)
>       at hooks.optimizeAssets.callAsync.err (/home/circleci/project/node_modules/webpack/lib/Compilation.js:1329:35)
>       at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/circleci/project/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
>       at AsyncSeriesHook.lazyCompileHook (/home/circleci/project/node_modules/tapable/lib/Hook.js:154:20)
>       at hooks.optimizeChunkAssets.callAsync.err (/home/circleci/project/node_modules/webpack/lib/Compilation.js:1320:32)
>       at _promise1.then._result1 (eval at create (/home/circleci/project/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:18:1)
>       at <anonymous>
>    @ ./style/index.ts 1:0-29
>    @ multi ./common/errorTracker ./common/polyfills ./style ./frames/about
> ```
> 
> **If the current behavior is a bug, please provide the steps to reproduce.**
> 
> My configuration is huge. I'd be happy to try and narrow down a minimal repro if necessary, but I hope that the error would be obvious given that this is a regression in a minor release. If it's not, just let me know.
> 
> **What is the expected behavior?**
> 
> There should be no error during build.
> 
> **Other relevant information:** webpack version: 4.32.0 Node.js version: 8.9.0 Operating System: macOS 10.14.5 Additional tools: mini-css-extract-plugin 0.4.4

Verify the compatibility of your project's dependencies. Sometimes, a specific version of mini-css-extract-plugin might not be compatible with other packages in your project. Check the documentation or release notes for compatibility information.

**Comment by Abunyousra** [comment]
Verify the compatibility of your project's dependencies. Sometimes, a specific version of mini-css-extract-plugin might not be compatible with other packages in your project. Check the documentation or release notes for compatibility information.
