### ISSUE TITLE
Errors with WebpackNotifier on large build

### ISSUE THREAD

**Issue by DelvarWorld** [webpack/webpack#930]
full stack trace:

    $ webpack -p

        ./node_modules/webpack-notifier/index.js:29
            var message = error.module.rawRequest;
                                    ^
        TypeError: Cannot read property 'rawRequest' of undefined
            at WebpackNotifierPlugin.compileMessage (./node_modules/webpack-notifier/index.js:29:31)
            at WebpackNotifierPlugin.compilationDone (./node_modules/webpack-notifier/index.js:39:20)
            at Tapable.applyPlugins (./node_modules/webpack/node_modules/tapable/lib/Tapable.js:26:37)
            at Tapable.<anonymous> (./node_modules/webpack/lib/Compiler.js:189:12)
            at Tapable.emitRecords (./node_modules/webpack/lib/Compiler.js:277:37)
            at Tapable.<anonymous> (./node_modules/webpack/lib/Compiler.js:183:11)
            at ./node_modules/webpack/lib/Compiler.js:270:11
            at Tapable.applyPluginsAsync (./node_modules/webpack/node_modules/tapable/lib/Tapable.js:60:69)
            at Tapable.afterEmit (./node_modules/webpack/lib/Compiler.js:267:8)
            at Tapable.<anonymous> (./node_modules/webpack/lib/Compiler.js:262:14)

Plugins list:

    plugins: [
        new webpack.ProvidePlugin({
            $: 'jquery',
            jQuery: 'jquery'
        }),
        new WebpackNotifierPlugin(),
        new webpack.optimize.UglifyJsPlugin({
            compress: {
                warnings: false
            }
        })
    ]

**Comment by DelvarWorld** [comment]
When I remove the notifier, I get a very large amount of warnings from uglify, which might be related?

    $ webpack -p

        Hash: 8b99c30c6cfe657f0be5
        Version: webpack 1.6.0
        Time: 49426ms
            Asset     Size  Chunks             Chunk Names
        bundle.js  1419317       0  [emitted]  main
            + 330 hidden modules

        WARNING in bundle.js from UglifyJs

(616 warnings follow)

**Comment by sokra** [comment]
Please report this to the webpack-notifier.

**Comment by asologor** [comment]
So a lot of people have this issue and it's closed?

My case:
```
 WAIT  Compiling...                                                                                                              1:27:01 PM

 95% emitting                                                
                      
 WARNING  Compiled with 0 warnings

/.../node_modules/webpack-notifier/index.js:42
    if (error.module && error.module.rawRequest)
              ^
```

`WARNING  Compiled with 0 warnings` - well done
