### ISSUE TITLE
Unable to run build -> npm ERR! code ELIFECYCLE 

### ISSUE THREAD

**Issue by bellancaf** [webpack/webpack#9353]
# Bug report

**What is the current behavior?**
The build breaks when it comes to executing the 'dist' script. 
It comes back with a not super clear debug/log: 

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/lib/node_modules/node/lib/node_modules/node/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'run',
1 verbose cli   'dist' ]
2 info using npm@6.9.2
3 info using node@v10.15.3
4 verbose run-script [ 'predist', 'dist', 'postdist' ]
5 info lifecycle feralhorses-client@4.6.8~predist: feralhorses-client@4.6.8
6 info lifecycle feralhorses-client@4.6.8~dist: feralhorses-client@4.6.8
7 verbose lifecycle feralhorses-client@4.6.8~dist: unsafe-perm in lifecycle true
8 verbose lifecycle feralhorses-client@4.6.8~dist: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/deploy/applications/fhd/tmp/client/feralhorses-client/node_modules/.bin:/home/deploy/bin:/home/deploy/.local/bin:/home/deploy/.rvm/bin:/home/deploy/bin:/home/deploy/.local/bin:/home/deploy/.rvm/bin:/home/deploy/.rvm/gems/ruby-2.3.1/bin:/home/deploy/.rvm/gems/ruby-2.3.1@global/bin:/home/deploy/.rvm/rubies/ruby-2.3.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/deploy/.rvm/bin:/snap/bin:/home/deploy/.rvm/bin:/home/deploy/.rvm/bin:/home/deploy/.rvm/bin
9 verbose lifecycle feralhorses-client@4.6.8~dist: CWD: /home/deploy/applications/fhd/tmp/client/feralhorses-client
10 silly lifecycle feralhorses-client@4.6.8~dist: Args: [ '-c',
10 silly lifecycle   'webpack -p --config webpack.config.dist.js --display-error-details' ]
11 silly lifecycle feralhorses-client@4.6.8~dist: Returned: code: 2  signal: null
12 info lifecycle feralhorses-client@4.6.8~dist: Failed to exec dist script
13 verbose stack Error: feralhorses-client@4.6.8 dist: `webpack -p --config webpack.config.dist.js --display-error-details`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:970:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid feralhorses-client@4.6.8
15 verbose cwd /home/deploy/applications/fhd/tmp/client/feralhorses-client
16 verbose Linux 4.4.0-38-generic
17 verbose argv "/usr/lib/node_modules/node/lib/node_modules/node/bin/node" "/usr/bin/npm" "run" "dist"
18 verbose node v10.15.3
19 verbose npm  v6.9.2
20 error code ELIFECYCLE
21 error errno 2
22 error feralhorses-client@4.6.8 dist: `webpack -p --config webpack.config.dist.js --display-error-details`
22 error Exit status 2
23 error Failed at the feralhorses-client@4.6.8 dist script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]
```

**Here is the webpack config setup:** 

```
const path = require('path');
const loaders = require('./loaders.js');
const plugins = require('./plugins');

module.exports = {
  entry: ["./src/index.js"],
  target: "web",
  module: {
    rules: [
      loaders.JSLoader,
      loaders.ESLintLoader,
      loaders.FontLoader,
      loaders.ImgLoader,
      loaders.ScssLoader,
      loaders.SVGLoader
    ]
  },
  plugins: [
    plugins.MiniCssExtractPlugin,
    plugins.ContextRep
  ],
  output: {
    path: path.resolve(__dirname, "dist"),
    filename: "app.js",
    publicPath: '/'
  }
};
```

**Postcss.config.js**

```
module.exports = {
  plugins: {
    'postcss-import': {},
    'postcss-preset-env': {
      browsers: 'last 3 versions'
    },
    'cssnano': {}
  }
};
```

**loaders.js**

```
const MiniCssExtractPlugin = require("mini-css-extract-plugin");

const JSLoader = {
  test: /\.js$/,
  exclude: /node_modules/,
  use: {
    loader: 'babel-loader'
  }
};

const ESLintLoader = {
  test: /\.js$/,
  enforce: 'pre',
  exclude: /node_modules/,
  use: {
    loader: 'eslint-loader',
    options: {
      configFile: __dirname + '/.eslintrc'
    }
  }
};

const CSSLoader = {
  test: /\.css$/,
  exclude: /node_modules/,
  use: [
    {
      loader: MiniCssExtractPlugin.loader
    },
    {
      loader: 'css-loader',
      options: { importLoaders: 1 }
    },
    {
      loader: 'postcss-loader',
      options: {
        config: {
          path: __dirname + '/postcss.config.js'
        }
      }
    }
  ]
};

const FontLoader = {
  test: /\.(otf|eot|ttf|woff)/,
  loader: 'url-loader'
};

const ImgLoader = {
  test: /\.(png|jpe?g|gif)$/,
  use: [
    {
      loader: 'file-loader',
      options: {
        name: '[name].[ext]'
      }
    }
  ]
};

const ScssLoader = {
  test: /\.scss$/,
  use: [
    {
      loader: 'style-loader'
    }
  ]
};

const SVGLoader = {
  test: /\.svg$/,
  loader: 'svg-inline-loader'
};

module.exports = {
  JSLoader,
  ESLintLoader,
  CSSLoader,
  FontLoader,
  ImgLoader,
  ScssLoader,
  SVGLoader
};

```

**plugins.js** 

```
const _MiniCssExtractPlugin = require('mini-css-extract-plugin');
const webpack = require('webpack');

const MiniCssExtractPlugin = new _MiniCssExtractPlugin({
  filename: '[name].bundle.css',
  chunkFilename: '[id].css'
});

const ContextRep = new webpack.ContextReplacementPlugin(
    /moment[\\\/]locale$/,
    /^\.\/(en|it)$/
    );

module.exports = {
  MiniCssExtractPlugin,
  ContextRep
};
```
Last but not least my **package.json**

```
{
  "name": "feralhorses-client",
  "version": "4.6.8",
  "description": "The client for the Feral Horses app.",
  "main": "index.js",
  "scripts": {
    "start": "webpack-dev-server --progress --colors --config webpack.config.dev.js",
    "dist": "webpack -p --config webpack.config.dist.js --display-error-details"
  },
  "repository": {
    "type": "git",
    "url": "git+ssh://git@gitlab.com/feralhorses/feralhorses-client.git"
  },
  "author": "FeralHorses",
  "license": "MIT",
  "homepage": "https://gitlab.com/feralhorses/feralhorses-client#readme",
  "dependencies": {
    "actioncable": "5.2.3",
    "axios": "^0.19.0",
    "babel-runtime": "^6.26.0",
    "classnames": "2.2.5",
    "cookies-js": "1.2.2",
    "country-list": "1.1.0",
    "moment": "^2.24.0",
    "number-format.js": "1.1.10",
    "prop-types": "^15.7.2",
    "react": "^16.4.0",
    "react-datepicker": "2.7.0",
    "react-dom": "^16.4.0",
    "react-dropzone": "^10.1.5",
    "react-easy-swipe": "0.0.18",
    "react-facebook-login": "^4.1.1",
    "react-ga": "^2.6.0",
    "react-google-invisible-recaptcha": "^0.2.7",
    "react-google-login": "5.0.4",
    "react-image-gallery": "0.8.10",
    "react-infinite-scroller": "0.2.9",
    "react-intercom": "^1.0.14",
    "react-router": "5.0.1",
    "react-router-redux": "4.0.5",
    "react-scroll": "1.4.4",
    "react-select": "^2.4.4",
    "react-slick": "0.24.0",
    "react-waypoint": "^9.0.2",
    "recharts": "^1.6.2",
    "redux-form": "8.2.4",
    "smoothscroll": "^0.4.0",
    "validator": "^11.0.0",
    "video-react": "^0.14.0"
  },
  "devDependencies": {
    "autoprefixer": "^9.4.3",
    "babel-core": "^6.26.3",
    "babel-eslint": "10.0.2",
    "babel-loader": "^7.0.0",
    "babel-plugin-recharts": "^1.2.0",
    "babel-plugin-transform-object-assign": "6.22.0",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "babel-preset-env": "^1.7.0",
    "css-loader": "^2.0.2",
    "cssnano": "^4.1.10",
    "clean-webpack-plugin": "^1.0.0",
    "eslint": "^5.16.0",
    "eslint-config-airbnb": "17.1.0",
    "eslint-loader": "2.1.2",
    "eslint-plugin-import": "2.18.0",
    "eslint-plugin-jsx-a11y": "6.2.1",
    "eslint-plugin-react": "7.14.2",
    "extract-text-webpack-plugin": "4.0.0-beta.0",
    "file-loader": "4.0.0",
    "html-loader": "0.5.5",
    "html-webpack-plugin": "^3.2.0",
    "image-webpack-loader": "^5.0.0",
    "mini-css-extract-plugin": "0.7.0",
    "node-sass": "^4.12.0",
    "path": "0.12.7",
    "postcss": "^7.0.17",
    "postcss-import":"^12.0.1",
    "postcss-preset-env": "^6.6.0",
    "postcss-loader": "^3.0.0",
    "react-hot-loader": "4.11.1",
    "react-redux": "6.0.0",
    "redux": "4.0.1",
    "redux-immutable-state-invariant": "2.1.0",
    "redux-thunk": "2.3.0",
    "sass-loader": "7.1.0",
    "style-loader": "0.23.1",
    "svg-inline-loader": "^0.8.0",
    "svg-react-loader": "0.4.6",
    "url-loader": "^2.0.1",
    "uglifyjs-webpack-plugin": "^2.1.3",
    "webpack": "^4.4.1",
    "webpack-cli": "^3.1.2",
    "webpack-dashboard": "3.0.7",
    "webpack-dev-server": "^3.7.2",
    "webpack-md5-hash": "^0.0.6",
    "webpack-validator": "2.2.6",
    "webpack-node-externals": "^1.7.2"
  }
}
```
 
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
I am usually able to complete my deployment with my dist script but since I updated webpack to 4 it really feels like the struggle is real :( 

**Other relevant information:**
webpack version:  4.4.1
Node.js version: 10.15.3
Operating System: Ubuntu v 16.04
Additional tools:

**Comment by evilebottnawi** [comment]
Please create minimum reproducible test repo

**Comment by bellancaf** [comment]
@evilebottnawi  I am trying to do so but I am struggling to find a simple version of the client that I can dump on a repo, is there some documentation on how to do that without dumping the whole code? :)

**Comment by evilebottnawi** [comment]
@bellancaf i don't know how you can reproduce your problem, it is depends on how you configure repo and how you use this
