### ISSUE TITLE
'yarn build' commend works from bash directly but failed when it was executed through Jenkins

### ISSUE THREAD

**Issue by GuoanNB** [webpack/webpack#9495]
# Bug report

**What is the current behavior?**

'yarn build' works from bash but failed through Jenkins:
In Jenkins, it gives the following report:

Building in workspace /var/lib/jenkins/workspace/pricing-frontend-test
 > /usr/local/git/bin/git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > /usr/local/git/bin/git config remote.origin.url http://git.jd.com/likaiya/pricing-frontend-prod.git # timeout=10
Fetching upstream changes from http://git.jd.com/likaiya/pricing-frontend-prod.git
 > /usr/local/git/bin/git --version # timeout=10
using GIT_ASKPASS to set credentials likaiyaERP
 > /usr/local/git/bin/git fetch --tags --progress http://git.jd.com/likaiya/pricing-frontend-prod.git +refs/heads/*:refs/remotes/origin/*
 > /usr/local/git/bin/git rev-parse refs/remotes/origin/dev^{commit} # timeout=10
 > /usr/local/git/bin/git rev-parse refs/remotes/origin/origin/dev^{commit} # timeout=10
Checking out Revision a4bfb0cf8127e144cd119d13bc074d03a416a046 (refs/remotes/origin/dev)
 > /usr/local/git/bin/git config core.sparsecheckout # timeout=10
 > /usr/local/git/bin/git checkout -f a4bfb0cf8127e144cd119d13bc074d03a416a046
Commit message: "Update compression module version."
 > /usr/local/git/bin/git rev-list --no-walk a4bfb0cf8127e144cd119d13bc074d03a416a046 # timeout=10
[pricing-frontend-test] $ /bin/sh -xe /tmp/jenkins3396471848524572684.sh
+ export DISABLE_V8_COMPILE_CACHE=1
+ DISABLE_V8_COMPILE_CACHE=1
+ sudo yarn install
yarn install v1.17.3
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > bootstrap@4.3.1" has unmet peer dependency "jquery@1.9.1 - 3".
warning " > bootstrap@4.3.1" has unmet peer dependency "popper.js@^1.14.7".
warning " > redux-observable@0.18.0" has incorrect peer dependency "redux@>=3 <4".
warning " > babel-loader@8.0.6" has unmet peer dependency "@babel/core@^7.0.0".
[4/4] Building fresh packages...
Done in 10.92s.
+ sudo yarn build
yarn run v1.17.3
$ webpack --mode production --config webpack.prod.js
/var/lib/jenkins/workspace/pricing-frontend-test/node_modules/compression-webpack-plugin/node_modules/pkg-dir/index.js:5
const pkgDir = async cwd => {
                     ^^^

SyntaxError: Unexpected identifier
    at NativeCompileCache._moduleCompile (/var/lib/jenkins/workspace/pricing-frontend-test/node_modules/v8-compile-cache/v8-compile-cache.js:240:18)
    at Module._compile (/var/lib/jenkins/workspace/pricing-frontend-test/node_modules/v8-compile-cache/v8-compile-cache.js:186:36)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (/var/lib/jenkins/workspace/pricing-frontend-test/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/var/lib/jenkins/workspace/pricing-frontend-test/node_modules/compression-webpack-plugin/node_modules/find-cache-dir/index.js:4:16)
    at Module._compile (/var/lib/jenkins/workspace/pricing-frontend-test/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (/var/lib/jenkins/workspace/pricing-frontend-test/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/var/lib/jenkins/workspace/pricing-frontend-test/node_modules/compression-webpack-plugin/dist/index.js:22:44)
    at Module._compile (/var/lib/jenkins/workspace/pricing-frontend-test/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (/var/lib/jenkins/workspace/pricing-frontend-test/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/var/lib/jenkins/workspace/pricing-frontend-test/node_modules/compression-webpack-plugin/dist/cjs.js:3:18)
    at Module._compile (/var/lib/jenkins/workspace/pricing-frontend-test/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (/var/lib/jenkins/workspace/pricing-frontend-test/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/var/lib/jenkins/workspace/pricing-frontend-test/webpack.common.js:7:27)
    at Module._compile (/var/lib/jenkins/workspace/pricing-frontend-test/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Build step 'Execute shell' marked build as failure
Finished: FAILURE

**If the current behavior is a bug, please provide the steps to reproduce.**

I reinstalled all packages in my React project so all of them were updated to the lasted version, then I used 'yarn' to build the project and it was successful. So I pushed the updated 'package.json' file to the git repository and used Jenkins to execute the 'yarn install' and 'yarn build' commends on the remote test environment, it was failed and gave the following error report, while if I execute the same commends from bash directly, it works.

**What is the expected behavior?**

**Other relevant information:**
webpack version:  "^4.36.1",
Node.js version: v10.16.0
Operating System: Linux
Additional tools: 
yarn version 1.17.3
compression-webpack-plugin: 3.0.0,
webpack-cli: 3.3.6

**Comment by sokra** [comment]
Looks like the node.js version on jenkins is too old...

**Comment by shaodahong** [comment]
yep, you can print node version in Jenkins

**Comment by evilebottnawi** [comment]
Yes, problem in old node version
