### ISSUE TITLE
Error: No element indexed by 1

### ISSUE THREAD

**Issue by vunguyentuan** [webpack/webpack#952]
```
/Users/vunguyen/Projects/media-product/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:161
			if(isError) throw e;
			                  ^
Error: No element indexed by 1
    at ArraySet_at [as at] (/Users/vunguyen/Projects/media-product/node_modules/webpack/node_modules/webpack-core/node_modules/source-map/lib/source-map/array-set.js:83:11)
    at SourceMapConsumer_parseMappings [as _parseMappings] (/Users/vunguyen/Projects/media-product/node_modules/webpack/node_modules/webpack-core/node_modules/source-map/lib/source-map/source-map-consumer.js:410:44)
    at SourceMapConsumer.Object.defineProperty.get (/Users/vunguyen/Projects/media-product/node_modules/webpack/node_modules/webpack-core/node_modules/source-map/lib/source-map/source-map-consumer.js:73:14)
    at SourceMapConsumer_eachMapping [as eachMapping] (/Users/vunguyen/Projects/media-product/node_modules/webpack/node_modules/webpack-core/node_modules/source-map/lib/source-map/source-map-consumer.js:139:24)
    at Function.SourceNode_fromStringWithSourceMap [as fromStringWithSourceMap] (/Users/vunguyen/Projects/media-product/node_modules/webpack/node_modules/webpack-core/node_modules/source-map/lib/source-map/source-node.js:84:26)
    at new OriginalSource (/Users/vunguyen/Projects/media-product/node_modules/webpack/node_modules/webpack-core/lib/OriginalSource.js:39:21)
    at DependenciesBlock.onModuleBuild (/Users/vunguyen/Projects/media-product/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:294:19)
    at nextLoader (/Users/vunguyen/Projects/media-product/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:268:25)
    at /Users/vunguyen/Projects/media-product/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:285:15
    at context.callback (/Users/vunguyen/Projects/media-product/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:146:14)
```

**Comment by vunguyentuan** [comment]
```javascript
var path = require('path');
var webpack = require('webpack');

module.exports = {
  entry: [
    './app/scripts/index'
  ],
  output: {
    path: path.join(__dirname, 'public'),
    filename: 'bundle.js',
    publicPath: '/assets/',
    contentBase: 'public/'
  },
  plugins: [
    new webpack.optimize.UglifyJsPlugin()
  ],
  resolve: {
    modulesDirectories: ['web_modules', 'node_modules', 'app/scripts', 'app/styles'],
    extensions: ['', '.js', '.jsx']
  },
  module: {
    loaders: [
      {
        test: /\.jsx?$/,
        loaders: ['babel', 'jsx-loader?harmony=true'],
        include: path.join(__dirname, 'app/scripts')
      },
      {
        test: /\.scss$/,
        loader: 'style!css!sass'
      },
      { test: /bootstrap\/js\//, loader: 'imports?jQuery=jquery' },
      { test: /\.woff2?$/, loader: 'url-loader?limit=10000&minetype=application/font-woff' },
      { test: /\.ttf$/, loader: 'file-loader' },
      { test: /\.eot$/, loader: 'file-loader' },
      { test: /\.svg$/, loader: 'file-loader' }
    ]
  }
};

```

**Comment by vunguyentuan** [comment]
That error cause by https://github.com/bline/bootstrap-webpack, after remove it everything work fine

**Comment by volkanunsal** [comment]
Running into the same error. I'm not using bootstrap-webpack, though.

**Comment by sokra** [comment]
Please open a new issue with your stack trace and config.
