### ISSUE TITLE
sourceMap not always available in `SourceMapDevToolPlugin`

### ISSUE THREAD

**Issue by sairion** [webpack/webpack#955]
I'm not still sure why this is happening (investigating, not reproducible in local env), but reporting:

```pytb
TypeError: Cannot read property 'sources' of null
    at Tapable.<anonymous> (/some/path/node_modules/webpack/lib/SourceMapDevToolPlugin.js:63:19)
    at Array.map (native)
    at Tapable.<anonymous> (/some/path/node_modules/webpack/lib/SourceMapDevToolPlugin.js:44:84)
    at Array.forEach (native)
    at Tapable.<anonymous> (/some/path/node_modules/webpack/lib/SourceMapDevToolPlugin.js:43:11)
    at Tapable.applyPlugins (/some/path/node_modules/webpack/node_modules/tapable/lib/Tapable.js:26:37)
    at Tapable.<anonymous> (/some/path/node_modules/webpack/lib/Compilation.js:543:10)
    at Tapable.next (/some/path/node_modules/webpack/node_modules/tapable/lib/Tapable.js:69:11)
    at Tapable.<anonymous> (/some/path/node_modules/webpack/lib/optimize/UglifyJsPlugin.js:136:4)
    at Tapable.applyPluginsAsync (/some/path/node_modules/webpack/node_modules/tapable/lib/Tapable.js:73:13)
```

https://github.com/webpack/webpack/commit/92f53176a2ccccea45d1bb97011463338337e8d6

Not completely sure yet, but it seems this commit break my company's CI ;) `sourceMap` isn't always avaiable, maybe. I will try to fix to earlier version (`@1.7.3`) to dodge the problem and see what's happening in `@1.8.0`.

**Comment by sokra** [comment]
https://github.com/webpack/webpack/commit/0f3a9cd199cfaa2d2cd79d088c432b5133374328
