### ISSUE TITLE
Conflict: Multiple assets emit to the same filename app.js.map

### ISSUE THREAD

**Issue by ar-cf** [webpack/webpack#9693]
# Bug report

**What is the current behavior?**
Webpack refuses to compile anything when sourcemaps are enabled. The codebase worked last week; firing it up this week & doing a fresh npm install && webpack --mode=development results in:

/path/node_modules/webpack/lib/Compilation.js:1994
                                throw new Error(
                                ^

Error: Conflict: Multiple assets emit to the same filename app.js.map
    at Compilation.emitAsset (/path/node_modules/webpack/lib/Compilation.js:1994:11)
    at tasks.forEach (/path/node_modules/webpack/lib/SourceMapDevToolPlugin.js:377:20)
    at Array.forEach (<anonymous>)
    at compilation.hooks.afterOptimizeChunkAssets.tap (/path/node_modules/webpack/lib/SourceMapDevToolPlugin.js:295:12)
    at SyncHook.eval [as call] (eval at create (/path/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:1)
    at SyncHook.lazyCompileHook (/path/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.optimizeChunkAssets.callAsync.err (/path/node_modules/webpack/lib/Compilation.js:1394:42)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/path/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/path/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.additionalAssets.callAsync.err (/path/node_modules/webpack/lib/Compilation.js:1390:36)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/path/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/path/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.optimizeTree.callAsync.err (/path/node_modules/webpack/lib/Compilation.js:1386:32)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/path/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/path/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.seal (/path/node_modules/webpack/lib/Compilation.js:1323:27)
    at compilation.finish.err (/path/node_modules/webpack/lib/Compiler.js:675:18)
    at hooks.finishModules.callAsync.err (/path/node_modules/webpack/lib/Compilation.js:1242:4)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/path/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (/path/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.finish (/path/node_modules/webpack/lib/Compilation.js:1234:28)
    at hooks.make.callAsync.err (/path/node_modules/webpack/lib/Compiler.js:672:17)
    at _done (eval at create (/path/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at _err1 (eval at create (/path/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:32:22)
    at _addModuleChain (/path/node_modules/webpack/lib/Compilation.js:1166:12)
    at processModuleDependencies.err (/path/node_modules/webpack/lib/Compilation.js:1078:9)
    at processTicksAndRejections (internal/process/task_queues.js:79:9)

Seems to be tied to this config chunk:
new webpack.SourceMapDevToolPlugin({
                'filename':     '[name].js.map',
                'exclude':       ['node_modules'],
            })

Removing 'filename' and 'exclude' allow it to work properly. Given I'm the backend developer on this project and simply want to build the front-end (as I did last week), I don't have the time to debug this.

**If the current behavior is a bug, please provide the steps to reproduce.**
Try to load up an old project with Source Maps enabled, and see if they work.
(I have confirmed in an old docker container that 4.39.3 is building fine; 

**What is the expected behavior?**
Things work the same as they have for the past six months of using webpack.

**Other relevant information:**
webpack version:  4.40.0
Node.js version: 11.15.0
Operating System:  Linux
Additional tools: Half dozen webpack plugins, all of which worked last week.

**Comment by sokra** [comment]
Please check if 4.40.1 fixes the problem. Otherwise open a new issue with a reproduction repo. Also make sure to not apply the SourceMapDevToolPlugin twice (i. e. with `devtool` option and the plugin).
