### ISSUE TITLE
after update version-4.40.1，my product not work.then  Version down to 4.39.2，it‘s ok~

### ISSUE THREAD

**Issue by wuguodong** [webpack/webpack#9698]
# Bug report

**What is the current behavior?**
after update version-4.40.1，my product not work.then  Version down to 4.39.2，it‘s ok~

**If the current behavior is a bug, please provide the steps to reproduce.**
my config as below:
![image](https://user-images.githubusercontent.com/4179192/64845404-aa984b00-d63c-11e9-945d-6e8b8af5743d.png)

when npm run start, show the error:
[ERROR] Error: Conflict: Multiple assets emit to the same filename images/keyroad_redcell.png
    at Compilation.emitAsset (/Users/mac/Documents/Codes/Project_React/tocc-bigscreen/node_modules/_webpack@4.40.0@webpack/lib/Compilation.js:1994:11)
    at Compilation.createModuleAssets (/Users/mac/Documents/Codes/Project_React/tocc-bigscreen/node_modules/_webpack@4.40.0@webpack/lib/Compilation.js:2075:11)
    at hooks.optimizeTree.callAsync.err (/Users/mac/Documents/Codes/Project_React/tocc-bigscreen/node_modules/_webpack@4.40.0@webpack/lib/Compilation.js:1375:9)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/mac/Documents/Codes/Project_React/tocc-bigscreen/node_modules/_tapable@1.1.3@tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/mac/Documents/Codes/Project_React/tocc-bigscreen/node_modules/_tapable@1.1.3@tapable/lib/Hook.js:154:20)

**What is the expected behavior?**
I'm not sure if it's a bug or if I have a configuration problem，thanks！

**Other relevant information:**
webpack version:  
Node.js version: 
Operating System: 
Additional tools:

**Comment by sokra** [comment]
Upgrade to 4.40.1

**Comment by evilebottnawi** [comment]
Answer above
