### ISSUE TITLE
TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by azhard4int** [webpack/webpack#9700]
# Bug report

After the recent release of Webpack 4.40.0, we are facing compiling issue, the same configuration was used previously and was working fine.

```
configureWebpack: {
    output: {
      filename: '[name].[contenthash].js',
      chunkFilename: '[name].[contenthash].js'
    },
    optimization: {
      moduleIds: 'hashed',
      runtimeChunk: 'single',
      splitChunks: {
        cacheGroups: {
          vendor: {
            test: /[\\/]node_modules[\\/]/,
            name: 'vendors',
            chunks: 'all'
          }
        }
      }
    }
  },
```

**What is the current behavior?**

Build fails with the error:

```
{ Error: Command failed: yarn run build
-  Building for production...
 ERROR  TypeError: Cannot read property 'name' of undefined
TypeError: Cannot read property 'name' of undefined
    at fileFilter (/var/www/html/lumotive/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:71:30)
    at Array.filter (<anonymous>)
    at compiler.hooks.afterEmit.tap.compilation (/var/www/html/lumotive/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:82:31)
    at _next0 (eval at create (/var/www/html/lumotive/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at _err0 (eval at create (/var/www/html/lumotive/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:24:1)
    at callback (/var/www/html/lumotive/node_modules/copy-webpack-plugin/dist/index.js:126:17)
    at afterEmit (/var/www/html/lumotive/node_modules/copy-webpack-plugin/dist/index.js:220:13)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/var/www/html/lumotive/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:20:1)
    at AsyncSeriesHook.lazyCompileHook (/var/www/html/lumotive/node_modules/tapable/lib/Hook.js:154:20)
    at asyncLib.forEachLimit.err (/var/www/html/lumotive/node_modules/webpack/lib/Compiler.js:482:27)
    at /var/www/html/lumotive/node_modules/neo-async/async.js:2818:7
    at done (/var/www/html/lumotive/node_modules/neo-async/async.js:3522:9)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/var/www/html/lumotive/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at outputFileSystem.writeFile.err (/var/www/html/lumotive/node_modules/webpack/lib/Compiler.js:464:33)
    at /var/www/html/lumotive/node_modules/graceful-fs/graceful-fs.js:57:14
    at FSReqWrap.oncomplete (fs.js:135:15)
error Command failed with exit code 1.

```

**If the current behavior is a bug, please provide the steps to reproduce.**

Use the above configuration for the output provided in the first step, run the `yarn run build` or `yarn build`

The above error will be produced.

**What is the expected behavior?**

Compile the build successfully. 

**Other relevant information:**
webpack version:  4.40.0
Node.js version: v8.12.0
Operating System: Linux/Ubuntu
Additional tools:

**Comment by evilebottnawi** [comment]
Update to `4.40.1`

**Comment by azhard4int** [comment]
@evilebottnawi I have tried updating to 4.40.1. The same issue persists.

**Comment by evilebottnawi** [comment]
@azhard4int you still use old version

**Comment by evilebottnawi** [comment]
https://github.com/webpack/webpack/commit/025c253732a269d617c8a4f7113389fbea81b9c2

**Comment by evilebottnawi** [comment]
Looks i was wrong, here potential problem place https://github.com/webpack/webpack/blob/025c253732a269d617c8a4f7113389fbea81b9c2/lib/performance/SizeLimitsPlugin.js#L71

**Comment by sokra** [comment]
fixed by #9701

**Comment by TONSILEBG** [comment]
https://imgur.com/a/oEUHNJt

pls help me dude

**Comment by TONSILEBG** [comment]
pls help me 

https://imgur.com/a/h3rCYZg
