### ISSUE TITLE
webDll-webpack error ModuleNotFoundError: Module not found: Error: Can't resolve 'child_process' in '/home/ubuntu/apps/2019-2-Grupo5-Web/web-frontend/node_modules/npm/node_modules/uid-number'

### ISSUE THREAD

**Issue by jbsaeza** [webpack/webpack#9760]
Hello, I'm trying to deploy an apollo-react-graphql frontent app with webpack and when I do `npm start` I get the following error:

```
webDll-webpack error ModuleNotFoundError: Module not found: Error: Can't resolve 'child_process' in '/home/ubuntu/apps/2019-2-Grupo5-Web/web-frontend/node_modules/npm/node_modules/uid-number'
    at /home/ubuntu/apps/2019-2-Grupo5-Web/web-frontend/node_modules/webpack/lib/Compilation.js:823:10
    at /home/ubuntu/apps/2019-2-Grupo5-Web/web-frontend/node_modules/webpack/lib/NormalModuleFactory.js:397:22
    at /home/ubuntu/apps/2019-2-Grupo5-Web/web-frontend/node_modules/webpack/lib/NormalModuleFactory.js:130:21
    at /home/ubuntu/apps/2019-2-Grupo5-Web/web-frontend/node_modules/webpack/lib/NormalModuleFactory.js:224:22
    at /home/ubuntu/apps/2019-2-Grupo5-Web/web-frontend/node_modules/neo-async/async.js:2830:7
    at /home/ubuntu/apps/2019-2-Grupo5-Web/web-frontend/node_modules/neo-async/async.js:6877:13
    at /home/ubuntu/apps/2019-2-Grupo5-Web/web-frontend/node_modules/webpack/lib/NormalModuleFactory.js:214:25
    at /home/ubuntu/apps/2019-2-Grupo5-Web/web-frontend/node_modules/enhanced-resolve/lib/Resolver.js:184:12
    at /home/ubuntu/apps/2019-2-Grupo5-Web/web-frontend/node_modules/enhanced-resolve/lib/Resolver.js:238:5
    at eval (eval at create (/home/ubuntu/apps/2019-2-Grupo5-Web/web-frontend/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
zen error Error: Build error
    at webpackReporter (/home/ubuntu/apps/2019-2-Grupo5-Web/web-frontend/node_modules/@larix/zen/src/executor.ts:120:11)
    at reporter (/home/ubuntu/apps/2019-2-Grupo5-Web/web-frontend/node_modules/@larix/zen/src/executor.ts:729:50)
    at finalCallback (/home/ubuntu/apps/2019-2-Grupo5-Web/web-frontend/node_modules/webpack/lib/Compiler.js:220:39)
    at onCompiled (/home/ubuntu/apps/2019-2-Grupo5-Web/web-frontend/node_modules/webpack/lib/Compiler.js:228:20)
    at /home/ubuntu/apps/2019-2-Grupo5-Web/web-frontend/node_modules/webpack/lib/Compiler.js:620:21
    at eval (eval at create (/home/ubuntu/apps/2019-2-Grupo5-Web/web-frontend/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /home/ubuntu/apps/2019-2-Grupo5-Web/web-frontend/node_modules/webpack/lib/Compilation.js:1083:13
    at /home/ubuntu/apps/2019-2-Grupo5-Web/web-frontend/node_modules/webpack/lib/Compilation.js:1006:25
    at /home/ubuntu/apps/2019-2-Grupo5-Web/web-frontend/node_modules/webpack/lib/Compilation.js:920:13
    at /home/ubuntu/apps/2019-2-Grupo5-Web/web-frontend/node_modules/neo-async/async.js:2830:7
```

I have browse all over the internet and I haven't been able to solve this, thing I have tried:

- Adding `target: 'node'` in webpack.config.js
- Adding `"browser":{"child_process": false}`  in package.json
- Using [webpack-node-externals](https://www.npmjs.com/package/webpack-node-externals)
- Adding `node: {"child_process": "empty"}` in webpack.config.js (also `false`)

But nothing above has worked, please send help D:

**Comment by sokra** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.
