### ISSUE TITLE
Loaders aren't required properly when using different compiler.inputFileSystem

### ISSUE THREAD

**Issue by notgiorgi** [webpack/webpack#9840]
# Bug report

**What is the current behavior?**
When using any `compiler.inputFileSystem` other then `require('fs')` loaders are not required properly.

E.g. if (see the repo down bellow for more details):
- `compiler.inputFileSystem = myMemfs`
- `webpackConfig.context = /memfs/`
- I have `babel-loader` as one of my loaders

this is the error I get:

```

  './index.js\n' +
    'Module build failed (from ./node_modules/babel-loader/lib/index.js):\n' +
    "Error: Cannot find module '/memfs/node_modules/babel-loader/lib/index.js'\n" +
    'Require stack:\n' +
    '- /Users/Gio/develop/webpack-memfs-bug-demo/node_modules/loader-runner/lib/loadLoader.js\n' +
    '- /Users/Gio/develop/webpack-memfs-bug-demo/node_modules/loader-runner/lib/LoaderRunner.js\n' +
    '- /Users/Gio/develop/webpack-memfs-bug-demo/node_modules/webpack/lib/NormalModule.js\n' +
    '- /Users/Gio/develop/webpack-memfs-bug-demo/node_modules/webpack/lib/NormalModuleFactory.js\n' +
    '- /Users/Gio/develop/webpack-memfs-bug-demo/node_modules/webpack/lib/Compiler.js\n' +
    '- /Users/Gio/develop/webpack-memfs-bug-demo/node_modules/webpack/lib/webpack.js\n' +
    '- /Users/Gio/develop/webpack-memfs-bug-demo/index.js\n' +
    '    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:780:15)\n' +
    '    at Function.Module._load (internal/modules/cjs/loader.js:685:27)\n' +
    '    at Module.require (internal/modules/cjs/loader.js:838:19)\n' +
    '    at require (internal/modules/cjs/helpers.js:74:18)\n' +
    '    at loadLoader (/Users/Gio/develop/webpack-memfs-bug-demo/node_modules/loader-runner/lib/loadLoader.js:22:17)\n' +
    '    at iteratePitchingLoaders (/Users/Gio/develop/webpack-memfs-bug-demo/node_modules/loader-runner/lib/LoaderRunner.js:169:2)\n' +
    '    at runLoaders (/Users/Gio/develop/webpack-memfs-bug-demo/node_modules/loader-runner/lib/LoaderRunner.js:365:2)\n' +
    '    at NormalModule.doBuild (/Users/Gio/develop/webpack-memfs-bug-demo/node_modules/webpack/lib/NormalModule.js:295:3)\n' +
    '    at NormalModule.build (/Users/Gio/develop/webpack-memfs-bug-demo/node_modules/webpack/lib/NormalModule.js:446:15)\n' +
    '    at Compilation.buildModule (/Users/Gio/develop/webpack-memfs-bug-demo/node_modules/webpack/lib/Compilation.js:739:10)\n' +
    '    at /Users/Gio/develop/webpack-memfs-bug-demo/node_modules/webpack/lib/Compilation.js:1111:12\n' +
    '    at /Users/Gio/develop/webpack-memfs-bug-demo/node_modules/webpack/lib/NormalModuleFactory.js:409:6\n' +
    '    at /Users/Gio/develop/webpack-memfs-bug-demo/node_modules/webpack/lib/NormalModuleFactory.js:155:13\n' +
    '    at AsyncSeriesWaterfallHook.eval [as callAsync] (eval at create (/Users/Gio/develop/webpack-memfs-bug-demo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)\n' +
    '    at AsyncSeriesWaterfallHook.lazyCompileHook (/Users/Gio/develop/webpack-memfs-bug-demo/node_modules/tapable/lib/Hook.js:154:20)\n' +
    '    at /Users/Gio/develop/webpack-memfs-bug-demo/node_modules/webpack/lib/NormalModuleFactory.js:138:29'

```

**If the current behavior is a bug, please provide the steps to reproduce.**
See the repo for reproduction: https://github.com/notgiorgi/webpack-memfs-bug-demo (to run `yarn install && yarn start`, for code check out the `index.js`) 

(As you can see I'm even loading babel-loader from into the memfs `node_modules` if I don't do that, exactly the same happens but the error message is just less helpul) 

I managed to "fix this" by changing this line of code: https://github.com/webpack/loader-runner/blob/master/lib/loadLoader.js#L5 to this:

```js
const fallback = {
    ['/memfs/node_modules/babel-loader/lib/index.js']: 'babel-loader',
}
var module = require(fallback[loader.path] || loader.path);
```

**What is the expected behavior?**

Expected behavior is for webpack to always require loaders from the "real" (`require('fs')`) filesystem

**Other relevant information:**
webpack version:  4.41.2
Node.js version: 12
Operating System: macOS sierra

**Comment by evilebottnawi** [comment]
@notgiorgi problem still exists?
