### ISSUE TITLE
HMR Bug in Current Chunk Assignment (4.41.2)

### ISSUE THREAD

**Issue by sbeaney** [webpack/webpack#9871]
# Bug report

**What is the current behavior?**
`currentChunk` in HotModuleReplacementPlugin.js doesn't get properly assigned a value (line 262).
```javascript
const chunkId = isNaN(+key) ? key : +key;
const currentChunk = compilation.chunks.find(
	chunk => `${chunk.id}` === key
);
```
In this context it appears `key` can be essentially any type, but the expression in `find()` checks `key` against a template literal. Because of the strict type comparison if `key` is any type other than a string it will return `false`.

This becomes an issue further down when `removedModules` tries to get assigned using `chunkId`
```javascript
const removedModules = records.chunkModuleIds[chunkId].filter(
	id => !allModules.has(id)
);
```

At that point the application breaks:
```
Application started. Press Ctrl+C to shut down.
fail: Microsoft.AspNetCore.NodeServices[0]
      C:\...\node_modules\webpack\lib\HotModuleReplacementPlugin.js:272
fail: Microsoft.AspNetCore.NodeServices[0]
      								const removedModules = records.chunkModuleIds[chunkId].filter(
fail: Microsoft.AspNetCore.NodeServices[0]
      								                                                       ^
fail: Microsoft.AspNetCore.NodeServices[0]
      TypeError: Cannot read property 'filter' of undefined
fail: Microsoft.AspNetCore.NodeServices[0]
          at C:\...\node_modules\webpack\lib\HotModuleReplacementPlugin.js:272:64
fail: Microsoft.AspNetCore.NodeServices[0]
          at SyncHook.eval [as call] (eval at create (C:\...\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:7:1)
fail: Microsoft.AspNetCore.NodeServices[0]
          at SyncHook.lazyCompileHook (C:\...\node_modules\tapable\lib\Hook.js:154:20)
fail: Microsoft.AspNetCore.NodeServices[0]
          at C:\...\node_modules\webpack\lib\Compilation.js:1399:37
fail: Microsoft.AspNetCore.NodeServices[0]
          at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\...\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
fail: Microsoft.AspNetCore.NodeServices[0]
          at AsyncSeriesHook.lazyCompileHook (C:\...\node_modules\tapable\lib\Hook.js:154:20)
fail: Microsoft.AspNetCore.NodeServices[0]
          at Compilation.seal (C:\...\node_modules\webpack\lib\Compilation.js:1342:27)
fail: Microsoft.AspNetCore.NodeServices[0]
          at C:\...\node_modules\webpack\lib\Compiler.js:675:18
fail: Microsoft.AspNetCore.NodeServices[0]
          at C:\...\node_modules\webpack\lib\Compilation.js:1261:4
fail: Microsoft.AspNetCore.NodeServices[0]
          at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\...\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
fail: Microsoft.AspNetCore.NodeServices[0]
          at AsyncSeriesHook.lazyCompileHook (C:\...\node_modules\tapable\lib\Hook.js:154:20)
fail: Microsoft.AspNetCore.NodeServices[0]
          at Compilation.finish (C:\...\node_modules\webpack\lib\Compilation.js:1253:28)
fail: Microsoft.AspNetCore.NodeServices[0]
          at C:\...\node_modules\webpack\lib\Compiler.js:672:17
fail: Microsoft.AspNetCore.NodeServices[0]
          at _done (eval at create (C:\...\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:9:1)
fail: Microsoft.AspNetCore.NodeServices[0]
          at eval (eval at create (C:\...\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:80:22)
fail: Microsoft.AspNetCore.NodeServices[0]
          at C:\...\node_modules\webpack\lib\Compilation.js:1185:12
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ChunkedEncodingReadStream.CopyToAsyncCore(Stream destination, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.PerformProxyRequest(HttpContext context)
   at Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
warn: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[2]
      The response has already started, the error page middleware will not be executed.
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLQMBNMU9S82", Request id "0HLQMBNMU9S82:00000005": An unhandled exception was thrown by the application.
System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ChunkedEncodingReadStream.CopyToAsyncCore(Stream destination, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.PerformProxyRequest(HttpContext context)
   at Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

In an older version of HotModuleReplacementPlugin.js the expression to assign `currentChunk` worked a bit differently (no forced string comparison) and uses `chunkId`.
```javascript
const chunkId = isNaN(+key) ? key : +key;
const currentChunk = compilation.chunks.find(
	chunk => chunk.id === chunkId
);
```

If I replace the current expression with this old one, HMR works as intended and doesn't break the application.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Other relevant information:**
webpack version:  4.41.2
Node.js version: 12.10.0
Operating System: Windows 10 (1809)
Additional tools: Visual Studio 2019, IIS 10.0.17763.1

**Comment by sokra** [comment]
> In this context it appears `key` can be essentially any type, but the expression in `find()` checks `key` against a template literal. Because of the strict type comparison if `key` is any type other than a string it will return `false`.

`key` is an item from `Object.keys`, which can only be a string

https://github.com/webpack/webpack/blob/11e94dd2d0a8d8baae75e715ff8a69f27a9e3014/lib/HotModuleReplacementPlugin.js#L259-L263
